### ISSUE TITLE
Discussion: Suggested naming convention for spacemacs layers in github

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#7971]
I know external layers are not planned for the short term,  but as of now there is no easy way to search on github for community created layers.   I wanted to ask the community what naming convention we should follow to make the layers more visible in github searches.   I was thinking a prefix like 'sl-'  or 'space-',  but wanted to see if anyone had more robust suggestion.

**Comment by LemmingAvalanche** [comment]
I’ve seen Eivind Fonn interactively shorten the `spacemacs-` prefix for functions to `sm-` in his Spacemacs (on YouTube).  Based on that, maybe `sml-` or `sm-layer-`? Just throwing it out there.

On the other hand, I like how functions in Emacs are so long and verbose due to Elisp not having namespaces (or just a flat one?). But I mostly use them interactively.

**Comment by ralesi** [comment]
I think the sm- is from the nameless package which isn't included in spacemacs currently.   

What I am referring to has nothing to do with namespaces though,  and more how we should name the layer repository in github for improved visibility.   I.e. Should I put my folding layer on github as `ralesi/sm-folding` or something else?

**Comment by LemmingAvalanche** [comment]
Alright I see, good stuff.  I think we’re on the same page though, as I meant
“namespaces” in a side sense, not just in the narrow sense of Emacs Lisp
namespaces.  (Or maybe I’m just trying to save face.)  In this case it’s the
namespace of GitHub repositories.

Maybe I should use another word than “namespace” in this context?

**Comment by syl20bnr** [comment]
`sml` feels like an extension and so it is opened to lot of possible conflicts.
`-sm-layer` looks fine.
I personally prefer the longer and non ambiguous suffix `-spacemacs-layer`.

**Comment by LemmingAvalanche** [comment]
I agree with Sylvain.  A fully qualified affix, either suffix or prefix.  I am
leaning more towards a prefix, for the following reason: moving a third-party
layer into this project would consist of stripping the prefix `spacemacs-layer-`
and adding it as a directory somewhere with the remaining string as its name.
This feels more natural than stripping it of a suffix.

**Comment by nixmaniack** [comment]
I would vote for `spacemacs-layer-` prefix as I generally see `evil` related pacakges named with `evil-` prefix and similarly for emacs packages `emacs-` prefix is used on github (`emacs-which-key`, `emacs-purpose` to name a few) 

Also, it might not be suitable but just suggesting an abbreviated form of `spacemacs-layer-` as `slayer-` which would make every layer _`a killer layer`_ (based on slay meaning kill) ;)

**Comment by LemmingAvalanche** [comment]
> I would vote for spacemacs-layer- prefix as I generally see evil related pacakges named with evil- prefix and similarly for emacs packages emacs- prefix is used on github (emacs-which-key, emacs-purpose to name a few)

+1 on this part, I agree.  You bring up good points.

> Also, it might not be suitable but just suggesting an abbreviated form of spacemacs-layer- as slayer- which would make every layer a killer layer (based on slay meaning kill) ;)

This is too cutesy for my tastes.  Programming already has too many puns to deal
with.  😛 And what about things like “kill ring”?  A “slayer” name might be
suggestive of that.

Just my opinion.  ☺

**Comment by LemmingAvalanche** [comment]
Sylvain wrote:

> sml feels like an extension and so it is opened to lot of possible conflicts.

Another thing is that “SML” is sometimes used to mean “Standard ML”.  Indeed,
there is already an “sml” layer in Spacemacs.  Now if this was a third-party
layer, it might be called `sml-sml` in order to adhere to the hypothetical
“`sml-` prefix” convention.  Or perhaps a more qualified `sml-standard-ml`, but
that is potentially confusing, too.

So that’s an example of the confusion that three-character abbreviations can
bring with them.

**Comment by jwintz** [comment]
Not to mention that AFAIK, sml reminds me of the smart-modeline-package: https://github.com/Malabarba/smart-mode-line <https://github.com/Malabarba/smart-mode-line>.

  - ju

**Comment by syl20bnr** [comment]
Prefix or suffix I have no preference.
`spacemacs-` prefix may be good enough if we go the route proposed by @nixmaniack. It is a universal prefix for everything `spacemacs` related (dotfiles, layers etc..) in the same same spirit as `emacs-` prefix (nothing tells that the repo is about a package for emacs, but for sure it is for emacs).

**Comment by ralesi** [comment]
OK,  it seems `spacemacs-` as a prefix is the minimum common consensus from this group.  Regardless of what is chosen,  if we make this a convention,  can I suggest we make a template repo such as `spacemacs-layer` with the initial files and point to that so we can have users fork it? The benefit I see from this is that everyone can see within the network in github to see the other layers being worked on.  Can you fork a repo more than once?

**Comment by deb0ch** [comment]
Just to upvote `spacemacs-` prefix, IMHO the `layer-` addition not necessary or even redundant.

@ralesi Just tried, you can't even if you rename your first fork.

**Comment by LemmingAvalanche** [comment]
I've changed my mind closer to Sylvain's and deb0ch's now. I agree with deb0ch that adding "layer" is probably redundant. Like Sylvain says, repos aren't called long things like "emacs-package-..." in practice.

**Comment by ralesi** [comment]
What about if each branch was a different layer? Then it would all still be visible on the github network

**Comment by syl20bnr** [comment]
@ralesi Not sure to understand what you mean.

Did you mean that each layer could be a fork of spacemacs ? AFAIK only forks are in the github network.

**Comment by ralesi** [comment]
@syl20bnr, here is the proposal, make a spacemacs-layers repo with a template branch. Each user forks it and creates branches consistent with the layers they want. Each layer change (represented as branches in their layers repo) will be visible in the github network.  

It's just an alternate way of providing visibility to 3rd party layer development.

**Comment by syl20bnr** [comment]
I like the idea :-)

**Comment by ralesi** [comment]
The only issue I see is that we will need to clone multi copies of the same repo in order to get them in individual folders on the file system,  however we can build in a system to manage that.
