### ISSUE TITLE
`version-control layer` breaks dotspacemacs/emacs-custom-settings and error "selecting deleted buffer" occurs

### ISSUE THREAD

**Issue by yang-ling** [syl20bnr/spacemacs#7973]
#### Description :octocat:
`version-control` layer breaks `dotspacemacs/emacs-custom-settings` and error "selecting deleted buffer" occurs

#### Reproduction guide :beetle:
- Clone spacemacs repository
- Check develop branch
- Start Emacs
- Always choose default options during installation
- `SPS f e d`
- Uncomment `version-control` in `dotspacemacs/layers`
- Restart Emacs to install `version-control`

*Observed behaviour:* :eyes: :broken_heart:
- Error message "selecting deleted buffer" occurs
- When I try to exit Emacs by `C-x C-c`, it asks me whether to save `~/.spacemacs`. Choose `y`
- Restart Emacs. It prompts that my `~/.spacemacs` file is broken.
- Open `~/.spacemacs`, I find `dotspacemacs/emacs-custom-settings` is broken, like below, all things like `custom-set-variables` are gone, and the end `)` is missing.
```
(defun dotspacemacs/emacs-custom-settings ()
  "Emacs custom settings.
This is an auto-generated function, do not modify its content directly, use
Emacs customize menu instead.
This function is called at the very end of Spacemacs initialization."
```

*Expected behaviour:* :heart: :smile:
- Be able to install `version-control` layers
- No "selecting deleted buffer" error
- No broken `dotspacemacs/emacs-custom-settings`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 628562f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 better-defaults
 (chinese :variables chinese-enable-fcitx t chinese-enable-youdao-dict t)
 chrome csv
 (elfeed :variables rmh-elfeed-org-files
         '("~/.emacs.d/private/my-elfeed-config/feed.org"))
 emacs-lisp git
 (go :variables go-tab-width 4)
 helm html javascript markdown my-elfeed-config my-fold
 (my-fonts :variables cfs-use-system-type t)
 my-image my-network my-notmuch pandoc php pkgbuild python
 (org :variables org-enable-bootstrap-support t org-enable-github-support t)
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts spell-checking syntax-checking windows-scripts yaml my-misc)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
I didn't get backtrace. I will provide it if I get some
```

**Comment by yang-ling** [comment]
I believe the following issues are relevant 
[`SPC a k` is broken, showing message `selecting deleted buffer` in the minibuffer](https://github.com/syl20bnr/spacemacs/issues/7963)
[dotspacemacs/emacs-custom-settings is broken, messages "selecting deleted buffer" #7898](https://github.com/syl20bnr/spacemacs/issues/7898)

**Comment by d12frosted** [comment]
Indeed, looks like #7898. Closing this issue in favour of #7898.

**Comment by syl20bnr** [comment]
Should be fixed now, more info here: https://github.com/syl20bnr/spacemacs/issues/7898#issuecomment-267807191

**Comment by yang-ling** [comment]
@syl20bnr  I checked the latest develop branch and confirmed this issue is fixed. Thanks!.
