### ISSUE TITLE
Can someone explain what is going on with dotspacemacs-emacs-custom-settings?

### ISSUE THREAD

**Issue by hicksy994** [syl20bnr/spacemacs#7976]
When I run update packages, it changes my dotfile to contain a function with an opening parentheses but no closing one. It also dumps a load of settings into the .custom-settings file. This breaks my config every single time so I have to manually go and fix the broken function it placed. Is this somehow intended and something else in my config is breaking the intended functionality somehow?

Also aren't emacs-custom-settings just to do with the emacs customise interface? I never use this, so why are custom settings even being set at all?

**Comment by d12frosted** [comment]
Related: https://github.com/syl20bnr/spacemacs/issues/7898

**Comment by syl20bnr** [comment]
@hicksy994 Can you post your emacs info (output from `SPC h d s` in message buffer) ? It will help us in resolving what is wrong.

Even if you are not using custom settings some packages can use them via dedicated functions, this is why everybody has custom-settings even if they don't use them.

**Comment by syl20bnr** [comment]
Should be fixed now, more info here: https://github.com/syl20bnr/spacemacs/issues/7898#issuecomment-267807191

**Comment by hicksy994** [comment]
Hi, sorry for not responding for a few days. I am still getting the same behavior. After running update packages, my dotfile gets messed up (I.E it removes the closing parentheses in the custom settings function) and I get the behavior from the other thread. I use a .spacemacs.d/ config and here is my emacs info:

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 5d73a500)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion themes-megapack better-defaults emacs-lisp git version-control ranger github org markdown
                 (erc :variables erc-server-list
                      '(("irc.freenode.net" :port "6697" :ssl t :nick "hicksy")))
                 rust java haskell html yaml
                 (c-c++ :variables c-c++-enable-clang-support t)
                 gtags
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 hicksy-theming)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by hicksy994** [comment]
Nevermind, I had to completely delete the function and the custom settings file.
