### ISSUE TITLE
Python mode `%` motion not working

### ISSUE THREAD

**Issue by off99555** [syl20bnr/spacemacs#7982]
#### Description :octocat:
`%` key (jump to matching paren) does not work correctly in Python mode
#### Reproduction guide :beetle:
- Start Emacs
- Open scratch buffer `SPC b s`
- Set it to python-mode using `SPC h M python RET`
- Type `print('hello')`
- Move point to the last parenthesis
- Press `%` you will notice that the point does not jump to the matching
  parenthesis

*Observed behaviour:* :eyes: :broken_heart:
The point does not jump. 

*Expected behaviour:* :heart: :smile:
The point should jump to the matching parenthesis.

#### System Info :computer:
- OS: windows-nt (Windows 10) Occurs in other OS too
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 4c50373)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python html vimscript ipython-notebook gtags emoji themes-megapack imenu-list
        (colors :variables colors-colorize-identifiers 'all colors-enable-nyan-cat-progress-bar t)
        helm
        (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip nil auto-completion-enable-sort-by-usage t)
        better-defaults emacs-lisp git markdown
        (org :variables org-enable-github-support t org-enable-bootstrap-support t)
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by bmag** [comment]
@robbyoconnor can you help? I recall you added evil-matchit integration for python. @off99555 you might just need to disable evil-matchit for python.

**Comment by off99555** [comment]
@bmag How can I disable it?

**Comment by bmag** [comment]
This is what python layer uses to enable evil-matchit:
```elisp
(add-hook `python-mode-hook `turn-on-evil-matchit-mode)
```
So putting this in `user-config` should negate it:
```elisp
(remove-hook `python-mode-hook `turn-on-evil-matchit-mode)
```

**Comment by off99555** [comment]
@bmag Thanks. It works! Hopefully it will be fixed soon so that I can use a better functionality of it.

**Comment by robbyoconnor** [comment]
@bmag I'm not sure if it ever worked for Python...

**Comment by robbyoconnor** [comment]
I don't do python work -- it works for Ruby though

**Comment by robbyoconnor** [comment]
Edit, I just tested this it works: Here's a test case for you to try (it's really contrived): 

```python
def foo(bar):
  baz = True
  foo = True
  if baz:
    return 3
  elif bar:
    print "Hi"
  else:
    return 5
  return 3
```

**Comment by robbyoconnor** [comment]
I just tested this it works: Here's a test case for you to try (it's really contrived): 

```python
def foo():
  baz = True
  foo = True
  if foo:
    return 3
  elif bar:
    print "Hi"
  else:
    return 5
  return 3
```

The way you use evil-matchit is you place the cursor on the if statement, and then hit `%` and it SHOULD work.  Worked for me anyways. Something is weird with your setup. This works fine. 

@bmag this isn't a bug. It's PEBKAC.

**Comment by robbyoconnor** [comment]
@off99555, how were you trying to use it?

**Comment by robbyoconnor** [comment]
yeah, I just tested it with your snippet too...it works fine...something is weird with your setup.

**Comment by robbyoconnor** [comment]
Here's my system info: 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.50.2
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. afa222605)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(bibtex nginx twitter graphviz ivy asciidoc elfeed speed-reading swift plantuml
        (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-show-snippets-in-popup t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets")
        better-defaults emacs-lisp
        (git :variables git-magit-status-fullscreen t)
        github gnus version-control
        (markdown :variables markdown-live-preview-engine 'vmd)
        syntax-checking
        (latex :variables latex-enable-auto-fill t)
        (colors :variables colors-colorize-identifiers 'all colors-enable-nyan-cat-progress-bar t)
        docker ansible puppet evil-commentary
        (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
        fasd finance floobits xkcd autohotkey csv nlinum
        (c-c++ :variables c-c++-enable-clang-support t)
        (clojure :variables clojure-enable-fancify-symbols t)
        extra-langs go
        (haskell :variables haskell-enable-ghci-ng-support t haskell-enable-shm-support t haskell-enable-hindent-style "andrew-gibiansky")
        html java
        (javascript :variables javascript-disable-tern-port-files t)
        (python :variables python-enable-yapf-format-on-save t python-test-runner
                '(nose pytest))
        racket
        (ruby :variables ruby-version-manager `rvm)
        ruby-on-rails
        (rust :variables rust-enable-rustfmt-on-save t)
        scala shell-scripts
        (restclient :variables restclient-use-org t)
        themes-megapack tmux vim-empty-lines spotify pandoc vagrant
        (ibuffer :variables ibuffer-group-buffers-by 'projects)
        semantic deft
        (shell :variables shell-default-shell 'ansi-term shell-default-position 'bottom shell-default-height 30 shell-default-term-shell "/bin/zsh")
        erc chrome d emoji gtags prodigy evernote
        (org :variables org-enable-github-support t org-enable-reveal-js-support t)
        search-engine evil-little-word yaml sql nim ipython-notebook lua scheme purescript sml common-lisp ranger dash spell-checking jabber cscope vinegar rcirc games react php vimscript geolocation idris
        (elm :variables elm-reactor-port "3000" elm-reactor-address "0.0.0.0")
        elixir
        (typography :variables typography-enable-typographic-editing nil)
        evil-cleverparens pdf-tools imenu-list slack systemd command-log)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS LIBSYSTEMD

**Comment by off99555** [comment]
@robbyoconnor Your example works fine. It jumps through if-else list and the paren normally.
But for my example, the `%` does not jump when the cursor is on the last paren. It only works if the cursor is on the first paren (the open paren).

**Comment by robbyoconnor** [comment]
@off99555, Nope works fine for me in both cases.

**Comment by robbyoconnor** [comment]
@off99555 --- I see it.. if you have parens on your if statement...it breaks...that's a bug in evil-matchit directly I think @redguardtoo may have something to say -- but I am able to jump back and forth between parans but having parens around the if statement means it doesn't jump among the clauses...weird Definitely a bug

**Comment by robbyoconnor** [comment]
Should probably report upstream

**Comment by robbyoconnor** [comment]
https://github.com/redguardtoo/evil-matchit

**Comment by off99555** [comment]
Ok I opened an issue here: https://github.com/redguardtoo/evil-matchit/issues/75

**Comment by robbyoconnor** [comment]
We may need to configure this further....more so than we are now.

**Comment by off99555** [comment]
Closing this issue now, the problem is resolved after adding `(setq evilmi-always-simple-jump t)`.
If I want to jump to the statement I can just do `0%`.
