### ISSUE TITLE
Can not use 'C-x C-left' or 'C-x C-right' to back to spacemacs buffer

### ISSUE THREAD

**Issue by was4444** [syl20bnr/spacemacs#7983]
Hi,
If I change to a new buffer(e.g. scratch) use `C-x C-right`, then can not back to spacemacs buffer with `C-x C-left`.

spacemacs version: 0.200.5
emacs version: 24.5.1

**Comment by bmag** [comment]
Duplicate of #7104. Different command (`alternate-buffer` vs. `previous-buffer`) same reason
