### ISSUE TITLE
How do I make spacemacs use the emacs built-in version of org?

### ISSUE THREAD

**Issue by MRFaria** [syl20bnr/spacemacs#7994]
I have written a package that depends on some functions provided by the built-in version of ORG, it looks like the more recent versions of ORG don't have backwards compatibility and my package breaks when I use spacemacs, what I find strange is that this happens even when I don't have the ORG layer enabled.

Is there a way to force spacemacs to load the ORG version that comes preloaded with emacs? I'm on emacs25.1

One of the functions missing is: org-table-clean-before-export

**Comment by d12frosted** [comment]
> what I find strange is that this happens even when I don't have the ORG layer enabled

Distribution named `spacemacs` enables layer named `spamceacs-org` which adds `org` as dependency. I guess you are using `spacemacs` distribution 😸 

> Is there a way to force spacemacs to load the ORG version that comes preloaded with emacs?

I can't test the solution I am going to propose right now but theoretically following might work.

1. Open up your `.spacemacs` file. 
2. Locate `dotspacemacs-additional-packages`.
3. Add `(org :location (recipe :fetcher file :path /usr/local/share/emacs/26.0.50/lisp/org/org.el))` (just don't forget to add real path to `org-mode`).
4. Reload. 

There should be better solution though.

**Comment by d12frosted** [comment]
Somewhat related to #4979. This is not about local version of packages, but about built-in. Note that solving #4979 might solve this one.

> I can't test the solution I am going to propose right now but theoretically following might work.

I've tested solution proposed for #4979 yesterday, but with other package. Since `org` is a special package it might not work, but I don't see any reasons for this to happen.

------

Another solution would be to add `(require 'org)` at the top level of `.spacemacs` file 😸 But it increases loading time of Spacemacs.

**Comment by MRFaria** [comment]
Thanks for the quick response, I tried the first solution and I get the following errors:
Problems while trying to load feature ‘org-w3m’
Problems while trying to load feature ‘org-bbdb’
Problems while trying to load feature ‘org-bibtex’
Problems while trying to load feature ‘org-docview’
Problems while trying to load feature ‘org-gnus’
Problems while trying to load feature ‘org-info’
Problems while trying to load feature ‘org-irc’
Problems while trying to load feature ‘org-mhe’
Problems while trying to load feature ‘org-rmail’

**Comment by MRFaria** [comment]
i get the following errors trying the first solution:
Problems while trying to load feature ‘org-w3m’
Problems while trying to load feature ‘org-bbdb’
Problems while trying to load feature ‘org-bibtex’
Problems while trying to load feature ‘org-docview’
Problems while trying to load feature ‘org-gnus’
Problems while trying to load feature ‘org-info’
Problems while trying to load feature ‘org-irc’
Problems while trying to load feature ‘org-mhe’
Problems while trying to load feature ‘org-rmail’

I put in the line:
 dotspacemacs-additional-packages '((org :location (recipe :fetcher file :path /home/userXXX/share/emacs/25.1/lisp/org/org.elc)))

ls /home/userXXX/share/emacs/25.1/lisp/org gives me:
a bunch of files including org.elc, but no org.el

**Comment by MRFaria** [comment]
extracting all the gz files didn't help
