### ISSUE TITLE
org agenda fails, "wrong type argument: number-or-marker-p"

### ISSUE THREAD

**Issue by jonbash** [syl20bnr/spacemacs#8000]
#### Description :octocat:
After updating packages, on attempting to load org-agenda (even on startup (since I have org-agenda items on the home screen)) it fails and I get the error "**Wrong type argument: number-or-marker-p, <2016-12-30 Fri>**" or another datestamp.

Reverting my updated packages seemed to fix the bug, but I would like to be able to use the latest version of stuff.

#### Reproduction guide :beetle:
- Start Emacs
- C-c a a (or , a a or , a [insert any agenda command])
- receive error above

*Observed behaviour:* :eyes: :broken_heart:
see error/traceback above/below

*Expected behaviour:* :heart: :smile:
I'd expect to see the org-agenda view.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6ab)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion emacs-lisp git markdown org shell spell-checking syntax-checking version-control javascript osx colors deft ibuffer themes-megapack command-log csv csharp
     (c-c   :variables c-c  -enable-clang-support t)
     html python swift yaml ruby shell-scripts lua dash tmux evil-cleverparens vinegar
     (geolocation :variables geolocation-enable-location-service t geolocation-enable-weather-forecast t)
     semantic speed-reading)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p "<2016-12-30 Fri>")
  org-agenda-get-deadlines()
  org-agenda-get-day-entries("/Users/jonbash/notes/wwu-todo.org" (12 19 2016) :deadline :scheduled :timestamp :sexp)
  apply(org-agenda-get-day-entries "/Users/jonbash/notes/wwu-todo.org" (12 19 2016) (:deadline :scheduled :timestamp :sexp))
  org-agenda-list(nil)
  funcall-interactively(org-agenda-list nil)
  call-interactively(org-agenda-list)
  org-agenda(nil)
  funcall-interactively(org-agenda nil)
  call-interactively(org-agenda nil nil)
  command-execute(org-agenda)
```

**Comment by paulreiser** [comment]
I can confirm this. Repeated tasks and their timestamps are causing this problem.

This is how you reproduce the bug:
Insert this timestamp anywhere in your org file: `<2015-12-07 Mon +1m>` 

It will cause the following error message to display in the minibuffer when you run `M-x org-agenda RET a RET`:
> Wrong number of arguments: (1 . 5), 6

This is how you fix it: remove `+1m` from that timestamp (so it is `<2015-12-07 Mon>`) and the agenda will displays as usual.

I'm on org mode version 9.0.2 (Emacs 25.1, Windows).

**Comment by syl20bnr** [comment]
Did you try to delete all the `.elc` files in the `org-plus-contrib` folder installed in `~/.emacs.d/elpa` directory ?

**Comment by paulreiser** [comment]
Actually, the problem went away after I updated org-mode.

**Comment by syl20bnr** [comment]
Marking this issue as closed since it has had. I activity for 1 month and the problem is likely related with deleting the elc files.
