### ISSUE TITLE
imenu (SPC j i) in Python mode does not recognize async functions

### ISSUE THREAD

**Issue by mkleehammer** [syl20bnr/spacemacs#8001]
#### Description :octocat:
imenu (SPC j i) in Python mode does not recognize async functions

#### Reproduction guide :beetle:
- Start Emacs
- Create Python module with a function and an async function:

        def test():
            pass

        async def again():
            pass
        
- Press `SPC j i` to get the jump menu.
- Note that "test" is in the list but "again" is not.

*Observed behaviour:* :eyes: :broken_heart:

Note that "test" is in the list but "again" is not.

*Expected behaviour:* :heart: :smile:

The jump menu should contain both "test" and "again".

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6ab)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(csv html sql python javascript yaml ivy
     (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup t)
     emacs-lisp
     (git :variables git-magit-status-fullscreen t)
     markdown spell-checking)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by mineo** [comment]
I think this is a bug in upstream Emacs: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24820

**Comment by mkleehammer** [comment]
Good catch. Thanks.
