### ISSUE TITLE
stracing emacs with spacemacs config shows a lot of pselect timeouts

### ISSUE THREAD

**Issue by naseer** [syl20bnr/spacemacs#801]
I was trying to debug some stutters and hangs in emacs so I fired up strace and saw a lot of these pselect timeouts happening continuously

```
pselect6(9, [3 4 8], [], NULL, {0, 62541168}, {NULL, 8}) = 0 (Timeout)
```

I'm using terminal emacs 24.4.1 on Ubuntu 14.04.

**Comment by syl20bnr** [comment]
Interesting can you post the list of the layers in your dotfile ?

**Comment by naseer** [comment]
This happens by default (no .spacemacs)

**Comment by naseer** [comment]
Also, spacemacs version is today's master.

**Comment by syl20bnr** [comment]
Ok, I have no linux box right now to test but blind shot: can you add `guide-key` to `dotspacemacs-excluded-packages` and check again ?

**Comment by naseer** [comment]
Are you on OS X? On OSX  dtruss spews the following on idle screen.



select(0xC, 0x7FFF5FBFEAF0, 0x7FFF5FBFEA70, 0x0, 0x7FFF5FBFE790)		 = 0 0
__pthread_sigmask(0x1, 0x7FFF5FBFC08C, 0x0)		 = 0 0
__pthread_sigmask(0x2, 0x7FFF5FBFC08C, 0x0)		 = 0 0
select(0xC, 0x7FFF5FBFEAF0, 0x7FFF5FBFEA70, 0x0, 0x7FFF5FBFE790)		 = 0 0
__pthread_sigmask(0x1, 0x7FFF5FBFC08C, 0x0)		 = 0 0
select(0xC, 0x7FFF5FBFEAF0, 0x7FFF5FBFEA70, 0x0, 0x7FFF5FBFE790)		 = 0 0
__pthread_sigmask(0x1, 0x7FFF5FBFC08C, 0x0)		 = 0 0

**Comment by naseer** [comment]
Adding `(setq-default dotspacemacs-excluded-packages '(guide-key)` to .spacemacs didn't work

**Comment by syl20bnr** [comment]
Thank for trying my proposal. I'm eager to find where it comes from.

**Comment by naseer** [comment]
Thanks for looking at it :) let me know if there are more packages that are worth disabling - there are so many :)

**Comment by StreakyCobra** [comment]
Any news on this issue? Is this still the happening?

**Comment by naseer** [comment]
Yes - but the frequency is much lesser (once every 2-3 seconds) so it may be WAI
