### ISSUE TITLE
Residual text in registers

### ISSUE THREAD

**Issue by abhi18av** [syl20bnr/spacemacs#8025]
#### Description :octocat:
When I open up `spacemacs` sometimes the register contents from the previous session are inserted into the buffer automatically. Which is of course a dubious behavior. 

#### Reproduction guide :beetle:
- Start Emacs
- Open up file from the main home-screen in `spacemacs`
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(mu4e
 (auto-completion :disabled-for shell)
 better-defaults emacs-lisp clojure git markdown org
 (haskell :variables haskell-enable-hindent-style "johan-tibell")
 html c-c   python sql xkcd finance search-engine dash fasd chinese restclient prodigy gtags deft colors
 (shell :variables shell-default-height 30 shell-default-position 'bottom :packages
        (not company))
 (ruby :variables ruby-enable-enh-ruby-mode t ruby-test-runner 'rspec ruby-version-manager 'rbenv)
 spell-checking syntax-checking version-control)
```
- System configuration features: JPEG RSVG IMAGEMAGICK DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by kccai** [comment]
Cannot reproduce ...
Maybe you have some clipboard manager installed on your system?

**Comment by abhi18av** [comment]
@kccai Nope, no clipboard manager apart from the vanilla one that comes packaged. Plus the issue is not even that frequent but say every 2-3 days it'd show up.

**Comment by abhi18av** [comment]
@kccai Hey, so I think the issue is with the vim feature of persistent content in the registers. Is there a way I could reset the registers - all, apart from the usual one - while quitting emacs?

**Comment by abhi18av** [comment]
I've reported this issue to the evil-emacs maintainers. Hopefully, this and the related issues would soon be resolved and closed.
