### ISSUE TITLE
Leader key doesn't work in customisation buffers

### ISSUE THREAD

**Issue by soulawaker** [syl20bnr/spacemacs#8029]
#### Description :octocat:
not working evil mode SPC key in parameter selection window.

#### Reproduction guide :beetle:
- Start Emacs
- Install clojure layer
- sync .spacemacs configuration
- open cider-boot-parameters window (SPC SPC customize-variable cider-boot-parameters)
- not work evil mode SPC key.

*Observed behaviour:* :eyes: :broken_heart:
just not working evil mode SPC key.

*Expected behaviour:* :heart: :smile:
working evil mode SPC key in parameter setting windows

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :variables auto-completion-enable-help-tooltip t)
 emacs-lisp
 (clojure :variables clojure-enable-fancify-symbols t)
 (colors :variables colors-colorize-identifiers 'all)
 spell-checking syntax-checking)
```

#### Backtrace :paw_prints:
```
```

**Comment by d12frosted** [comment]
Since I am not using `vim` editing style, I am not sure what is the state of customize evilification.
