### ISSUE TITLE
Too many closing "end"s in Elixir

### ISSUE THREAD

**Issue by pdilyard** [syl20bnr/spacemacs#8030]
#### Description :octocat:
Since upgrading spacemacs recently, too many closing `end` keywords are being inserted automatically in the Elixir language.

#### Reproduction guide :beetle:
- Start Emacs
- Enter elixir-mode, and make sure smartparens-mode is enabled
- Start a case statement with multiple clauses (see behaviours below)
- As you enter newlines, notice that too many `end`s are created

*Observed behaviour:* :eyes: :broken_heart:
```elixir
case something do
  {:ok, x} ->
    x
  {:ok, y} ->
    y
  {:ok, z} ->
    z
end
end
end
end
```

*Expected behaviour:* :heart: :smile:
```elixir
case something do
  {:ok, x} ->
    x
  {:ok, y} ->
    y
  {:ok, z} ->
    z
end
```

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ansible auto-completion better-defaults clojure colors deft docker elixir elm erlang emacs-lisp git github haskell html ivy javascript markdown org osx python react restclient rust shell spell-checking syntax-checking themes-megapack version-control yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by michalmuskala** [comment]
I can confirm this issue.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(better-defaults git osx github version-control
     (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell shell-enable-smart-eshell t)
     syntax-checking spell-checking auto-completion colors dash emacs-lisp
     (org :variables org-enable-github-support t)
     markdown elixir erlang javascript haskell html latex yaml ruby python racket rust c-c++ go ruby-on-rails react docker ansible)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by d12frosted** [comment]
Looks like it's because of [configurations](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/elixir/packages.el#L157-L172) of smartparens. But it's interesting that this change [was made](https://github.com/syl20bnr/spacemacs/commit/c476c033606d63c5f277d4582efa202572f06d8a) on 11 Feb 2016. 

Since I have never used elixir, I have a question - is following snippet valid?

```
case something do
  {:ok, x} ->
    x
  end
  {:ok, y} ->
    y
  end
  {:ok, z} ->
    z
  end
end
```

So basically is `end` after `->` optional or invalid at all?

**Comment by sdwolf** [comment]
Here is the output from the elixir shell:

```elixir
Erlang/OTP 19 [erts-8.1.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.3.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> something = {:ok, 1}
{:ok, 1}
iex(2)> case something do
...(2)>   {:ok, x} ->
...(2)>     x
...(2)>   end
1
iex(3)>   {:ok, y} ->
** (SyntaxError) iex:3: syntax error before: '->'
    
iex(3)>     y
** (CompileError) iex:3: undefined function y/0
    
iex(3)>   end
** (SyntaxError) iex:3: unexpected token: end
    
iex(3)>   {:ok, z} ->
** (SyntaxError) iex:3: syntax error before: '->'
    
iex(3)>     z
** (CompileError) iex:3: undefined function z/0
    
iex(3)>   end
** (SyntaxError) iex:3: unexpected token: end
    
iex(3)> end
```

Pretty much, `end` is not for the `->` but for the `case`.  The `{:ok, _} ->` are pattern matches, much like in c you have a switch statement:

```c
switch(something) {
  case: 1; // The equivalent of {:ok, _} ->
  case: 2;
  //...
} // The equivalent of `end`
```

**Comment by pdilyard** [comment]
Correct, the block should look like this:

```elixir
case x do
  {:ok, 1} ->
    1000
  {:ok, 2} ->
    2000
end
```

**Comment by sdwolf** [comment]
I believe the end was intended for when someone defines a lambda:

```elixir
Erlang/OTP 19 [erts-8.1.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.3.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> a = fn (x) -> 1 end
#Function<6.52032458/1 in :erl_eval.expr/5>
iex(2)> a.(:whatever)
1
```

This is the other place where `->` is used. Maybe the configuration should be:

```emacs-lisp
(defun elixir/pre-init-smartparens ()
  (spacemacs|use-package-add-hook smartparens
    :post-config
    (progn
      (sp-with-modes '(elixir-mode)
        (sp-local-pair
         "fn" "end"
         :when '(("RET"))
         :post-handlers '(:add spacemacs//elixir-do-end-close-action)
         :actions '(insert)))
      (sp-with-modes '(elixir-mode)
        (sp-local-pair
         "do" "end"
         :when '(("SPC" "RET"))
         :post-handlers '(:add spacemacs//elixir-do-end-close-action)
         :actions '(insert))))))
```

since you can also have a lambda defined like:

```elixir
Erlang/OTP 19 [erts-8.1.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.3.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> a = fn
...(1)> (1) -> 1
...(1)> (2) -> 2 
...(1)> end
#Function<6.52032458/1 in :erl_eval.expr/5>
iex(2)> a.(2)
2
```

**Comment by pdilyard** [comment]
@sdwolf has got it. So it would be nice (but ok if missing) if it would complete the `end` here:
```elixir
Enum.reduce([1, 2, 3], 0, fn x, acc ->
  x + acc
end)
```

But other than that, it should really only complete the `end` if there is a matching `do`.

**Comment by sdwolf** [comment]
@pdilyard How about `:when '(("SPC" "RET" "("))`

**Comment by pdilyard** [comment]
@sdwolf where should I put that configuration? `dotspacemacs/user-config` seems to have no effect. (Sorry, I have limited knowledge of elisp/emacs)

**Comment by sdwolf** [comment]
Right now I'm modifying the [file](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/elixir/packages.el#L157-L172) @d12frosted pointed out. I'm getting some weird results:

```elixir
    a = fn
    # <- cursor here, all is well
    end

    # Cursore at `a`
    a = fn( # <- pressed `(`
    end)

    # Cursor at `a`
    a = fn # <- pressed space
    end
```

**Comment by pdilyard** [comment]
Your example should actually be like this for correct syntax:
```elixir
    a = fn -> # ADDED: ->
    # <- cursor here, all is well
    end

    # Cursore at `a`
    a = fn( # <- pressed `(`
    end)

    # CORRECTED version of above
    a = fn () ->
    end

    # Cursor at `a`
    a = fn -> # <- pressed space
    end
```

**Comment by pdilyard** [comment]
I've got this so far:

```lisp
(defun elixir/pre-init-smartparens ()
  (spacemacs|use-package-add-hook smartparens
    :post-config
    (progn
      (sp-with-modes '(elixir-mode)
        (sp-local-pair
         "fn ->" "end"
         :when '(("RET"))
         :post-handlers '(:add spacemacs//elixir-do-end-close-action)
         :actions '(insert)))
      (sp-with-modes '(elixir-mode)
        (sp-local-pair
         "do" "end"
         :when '(("SPC" "RET"))
         :post-handlers '(:add spacemacs//elixir-do-end-close-action)
         :actions '(insert))))))

```

**Comment by sdwolf** [comment]
I's a start. I'm lookig into modifying [this function](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/elixir/funcs.el#L12) for better results.

**Comment by pdilyard** [comment]
I guess having a wilcard between `fn` and `->` would be pretty naive...this example wouldn't work correctly:

```elixir
fn
  1 -> 1000
  2 -> 2000
end
```

**Comment by pdilyard** [comment]
@michalmuskala Can you think of anything that really needs an automated `end` other than `do`?

Personally, I would be OK with it not autocompleting `fn x -> end` for now.

**Comment by michalmuskala** [comment]
I looked at it and with some changes, I was able to achieve this behavior:

```
fn # press SPC
fn | end
# this allows to continue into
fn _x -> 122 end
fn -> 123 end
```
```
fn # press RET
fn
|
end
# this allows to continue into
fn
  a -> a
  b -> b
end
```
```
case x do # press SPC
case x do | end
```
```
case x do # press RET
case x do
  |
end
```
The `fn RET` case could probably indent the point by 2 spaces similar to the `do` situation, but that is to be corrected in https://github.com/elixir-lang/emacs-elixir regarding the indentation, and not here.

I think the examples above cover all the usages and prevent excessive `end`s. If you agree I will assemble a PR.

**Comment by pdilyard** [comment]
@michalmuskala This seems to work pretty well. I'll play with it for the next few days and report back with any problems, but I say go for the PR 👍

**Comment by d12frosted** [comment]
Hey folks, nice work here 😸 

> but I say go for the PR

👍

**Comment by Fuco1** [comment]
I'm getting lost here but if this is an issue with smartparens config (which for elixir is rather immature at the moment) I would very much love it if someone who understands what's going on could wrap this up in a PR upstream so we can have it properly integrated :)

Cheers!
