### ISSUE TITLE
spacemacs/select-current-block, unused variable "p2", and possibly a superfluous "(progn"

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#8031]
#### Description :octocat:
I only have basic lisp knowledge so i might be wrong here, but it seems like a couple of lines in the `spacemacs/select-current-block` could be removed.

*Observed behaviour:* :eyes: :broken_heart:
This is what it currently looks like:
```elisp
(defun spacemacs/select-current-block ()
  "Select the current block of text between blank lines."
  (interactive)
  (let (p1 p2)
    (progn
      (if (re-search-backward "\n[ \t]*\n" nil "move")
          (progn (re-search-forward "\n[ \t]*\n")
                 (setq p1 (point)))
        (setq p1 (point)))
      (if (re-search-forward "\n[ \t]*\n" nil "move")
          (progn (re-search-backward "\n[ \t]*\n")
                 (setq p2 (point)))
        (setq p2 (point))))
    (set-mark p1)))
```
It's defined here:
https://github.com/syl20bnr/spacemacs/blob/b6d52030b165fc5b74c95d2ade9f1ba6b5c15ab7/layers/%2Bdistributions/spacemacs-base/funcs.el#L767

*Expected behaviour:* :heart: :smile:
The `p2` variable doesn't seem to be used, so it's initial definition `(let (p1 p2)` probably could be removed: `(let (p1)`.

If i understand it correctly, then a `progn` is used to call several commands from one place, like it does in both if statements, but it doesn't seem to be needed below the `let` variable definitions.

If the `p2` variable isn't needed, then both of it's assignment lines:
``` elisp
(setq p2 (point)))
        (setq p2 (point))))
```
could be removed, and the `progn` in the second if statement won't be needed either.

With the suggestions above, the function would look like this:
```elisp
(defun spacemacs/select-current-block ()
  "Select the current block of text between blank lines."
  (interactive)
  (let (p1)
    (if (re-search-backward "\n[ \t]*\n" nil "move")
        (progn (re-search-forward "\n[ \t]*\n")
               (setq p1 (point)))
      (setq p1 (point)))
    (if (re-search-forward "\n[ \t]*\n" nil "move")
        (re-search-backward "\n[ \t]*\n"))
    (set-mark p1)))
```

The `spacemacs/select-current-block` function is bound to left mouse button double clicking to the left of a text block on the line number margin <kbd>SPC t n</kbd>. That will select everything between the blank lines above and below. The function can also be called with the cursor in a text block from HELM M-x:
- press: <kbd>SPC SPC</kbd>
- type: `select cur`
- press <kbd>RET</kbd>

It seems to work the same way after removing the suggested lines and evaluating the function.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 5d73a50)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
‘‘‘elisp
(auto-completion autohotkey emacs-lisp git helm html org)
‘‘‘
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by d12frosted** [comment]
Yeah, it seems that you're right. PR is welcome 😸
