### ISSUE TITLE
React-mode: Cannot indent within a class definition

### ISSUE THREAD

**Issue by DarrenN** [syl20bnr/spacemacs#8035]
## Description:

When in `react-mode` in a file such as `App.jsx`:

```javascript
class App extends Component {
// <-- cursor here, when I hit TAB, nothing happens / no indentation
  // <-- when I hit enter from above, it then indents 2 spaces
constructor() // <-- placing the cursor before the 'c' and hitting TAB does nothing
}

export App;
```

When I place the cursor in between the braces of the `class` definition (where the comment is) and hit `TAB` - nothing happens. If I hit `ENTER` from that position, then the cursor starts indented 2 spaces on the next line.

## Expected return

I would expect the cursor to indent 2-spaces.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(clojure helm auto-completion c-c++ clojure emacs-lisp git javascript markdown osx
         (python :variables python-enable-yapf-format-on-save t)
         racket react
         (ruby :variables ruby-version-manager 'rbenv)
         (shell :variables shell-default-height 30 shell-default-position 'bottom)
         syntax-checking)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by liadbiz** [comment]
same issue here.

+ os: ubuntu 16.04LTS
+ emacs: 24.5.1
+ spacemacs: 0.200.5

**Comment by DarrenN** [comment]
Update: I've stripped down my layers to the following and still have the same problem:

```
   '(
     helm
     auto-completion
     emacs-lisp
     flow-type
     git
     javascript
     osx
     (python :variables python-enable-yapf-format-on-save t)
     react
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom)
     syntax-checking
     )
```

**Comment by DarrenN** [comment]
Update: This isn't just happening in class definition, it;s also happening whenever I need to indent something that's already inside a bracket. It is definitely related to `react-mode` - if I switch to `js2-mode`, select all, and hit tab everything auto-indents nicely.

**Comment by gabriel-dehan** [comment]
Any news on that issue ? Having the same problem 👍
