### ISSUE TITLE
Docs on searching projects, broken link

### ISSUE THREAD

**Issue by lindboe** [syl20bnr/spacemacs#8036]
When trying to find the best way to search for a phrase in files in a project, I came across [this section](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#managing-projects
). It does mention a way to search, but the two links ("To search in a project see project searching.", "See search in a project") are broken. It looks like they're intended to link to https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#searching-in-a-project. I'll probably submit a PR for this a little later if no one else gets to it.

**Comment by nikolaiam** [comment]
Well spotted! #8138 fixes this together with #8146.

**Comment by syl20bnr** [comment]
Should be fixed on http://develop.spacemacs.org
