### ISSUE TITLE
Reduce the 9 buffer-to-window SPC b entries to one 1..9, like it was done with SPC window 0..9

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#8038]
Maybe someone is working on this already, but the <kbd>SPC b</kbd> entries: 
1 -> buffer-to-window-1
...
9 -> buffer-to-window-9

probably should be reduced to a single line that looks something like this: 
1..9 -> buffer-to-window 1..9

The same way as the <kbd>SPC</kbd> window entries:
0  → window 0
..
9  → window 9

recently were reduced to:
0..9 -> window 0..9

as mentioned in this issue: https://github.com/syl20bnr/spacemacs/issues/7582, in fact the <kbd>SPC b</kbd> entries were mentioned in that issue.

The buffer-to-window-(nr) entries seem to be defined here:
https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bdistributions/spacemacs-base/keybindings.el#L135

I don't know how it should be done. So someone with more knowledge is going to have to do it.

**Comment by bmag** [comment]
For reference, here's how it's been done for `window 0..9`: https://github.com/syl20bnr/spacemacs/commit/c69c3b76842af298068f82bfb29fe42c65ce77b1 (from #7839)

**Comment by duianto** [comment]
I tried duplicating the lines:
```elisp
  (push '(("\\(.*\\) 0" . "select-window-0") . ("\\1 0..9" . "window 0..9"))
        which-key-replacement-alist)
  (push '((nil . "select-window-[1-9]") . t) which-key-replacement-alist)
```

and changing these in the duplicate entries: 
"select-window-0" to "buffer-to-window-0",
"window 0..9" to "buffer to window 0..9"
and "select-window-[1-9]" to "buffer-to-window-[1-9]"

```elisp
  (push '(("\\(.*\\) 0" . "buffer-to-window-0") . ("\\1 0..9" . "buffer to window 0..9"))
        which-key-replacement-alist)
  (push '((nil . "buffer-to-window-[1-9]") . t) which-key-replacement-alist)
```

but after restarting emacs then all of the `buffer-to-window-1` to `buffer-to-window-9` entries disappeared. They still work but they are just not listed in the <kbd>SPC b</kbd> buffers panel.

Since there's a "select-window-0" but "buffer-to-window-1" starts at 1, i also tried changing the 0s into 1s:

from:
```elisp
  (push '(("\\(.*\\) 0" . "buffer-to-window-0") . ("\\1 0..9" . "buffer to window 0..9"))
```
to:
```elisp
  (push '(("\\(.*\\) 1" . "buffer-to-window-1") . ("\\1 1..9" . "buffer to window 1..9"))
```
but it didn't help, they are still not visible in the <kbd>SPC b</kbd> buffers panel.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. bca0e4b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
‘‘‘elisp
(auto-completion autohotkey emacs-lisp git helm html org)
‘‘‘
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by bmag** [comment]
The attached patch seems to work for me. I believe the only difference from your effort that `[1-9]` became `[2-9]`. Can you confirm that it does work? If so, you're welcome to make a PR (most of it is your work).
To apply the patch:
```sh
git apply buffer-to-window.txt
```
Off topic, you can create a patch like this (to help explain what you tried) with:
```sh
git diff -p
```
or:
```sh
git diff -p --cached
```
[buffer-to-window.txt](https://github.com/syl20bnr/spacemacs/files/671258/buffer-to-window.txt)

**Comment by duianto** [comment]
It works with `[2-9]` 😄
