### ISSUE TITLE
Freeze/hang/hung on startup with CPU at 100%

### ISSUE THREAD

**Issue by tuxayo** [syl20bnr/spacemacs#8039]
#### Description :octocat:
I just got a freeze/hang/hung on startup with on CPU thread at 100%

Killing Spacemacs and relaunching worked.

So I can't reproduice.

I'm opening this issue so eventually other people experiencing this will find it and we could gather more details.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6ab)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby sql emacs-lisp git markdown org spell-checking syntax-checking haskell python javascript c-c++ php gtags)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by syl20bnr** [comment]
Do you have any repro steps ? Do this freeze when helm is about to show up ?

**Comment by tuxayo** [comment]
Didn't happen again, I think I can close it and we could reopen it if someone else has the same issue and finds this discussion.
