### ISSUE TITLE
React mode does not do smart parentheses

### ISSUE THREAD

**Issue by hiaw** [syl20bnr/spacemacs#8040]
#### Description :octocat:
React mode does not do smart parentheses

#### Reproduction guide :beetle:
- Start Emacs
- Open file in react-mode
- Try to program with it but parentheses do not auto generate closing parentheses

*Observed behaviour:* :eyes: :broken_heart:
Typing '(' gives '(|' in react-mode

*Expected behaviour:* :heart: :smile:
Typing '(' should give '(|)' instead of '(|'

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6ab)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(octave html javascript markdown react elixir yaml elm shell-scripts git
        (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence-delay 0.1)
        syntax-checking
        (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
        ranger org osx speed-reading colors better-defaults emoji)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by d12frosted** [comment]
Is `smartparens` minor mode is enabled?

**Comment by hiaw** [comment]
The point is that I have to turn it on via `Spc t C-p` everytime. How can I make it so that it has `smartparens` automatically just like `javascript-mode`?

**Comment by d12frosted** [comment]
Hm. That's strange. Could you please share your `.spacemacs` file?

**Comment by hiaw** [comment]
I thought it might be that problem and so I created another user on my mac and install spacemacs from fresh and still have the same problem. This is the `.spacemacs` from fresh install


[spacemacs.txt](https://github.com/syl20bnr/spacemacs/files/671184/spacemacs.txt)
