### ISSUE TITLE
Haskell layer tries to install intero 0.1.18, failing with recent ghc.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [syl20bnr/spacemacs#8041]
Two bugs:

1. This is not the latest intero release, and the layer should be updated.
2. Why isn't spacemacs accepting an intero version that is more recent than the one it is compatible with?  This would make it possible to at least avoid the issue by installing a working copy externally.

**Comment by DevJac** [comment]
I worked around this issue by updating the file `elpa/intero-20160927.127/intero.el` to install intero version `0.1.20` instead of `0.1.18`. I also had to delete the `elpa/intero-20160927.127/intero.elc` file for emacs to recognize the change.

**Comment by Miciah** [comment]
Spacemacs should just install the latest package from MELPA, and the upstream package has bumped the intero version that it installs several times since this issue was reported.  Is anyone still encountering the problem?

**Comment by vanceism7** [comment]
I'm still having this problem, just different versions. Currently using GHC 8.6.4, but spacemacs tries to install intero-0.1.34, but the latest is intero-0.1.37 as of this date
