### ISSUE TITLE
slime-edit-definition unbound in common-lisp layer

### ISSUE THREAD

**Issue by phoe** [syl20bnr/spacemacs#8043]
#### Description :octocat:
The SLIME function `slime-edit-definition` is unbound in the common-lisp layer. I need to `SPC SPC slime-edit-definition` manually to reach the source code of a given function.

#### Reproduction guide :beetle:
- Start Emacs and SLIME
- Open a Lisp file
- Move point to a known Common Lisp function
- `g d`

*Observed behaviour:* :eyes: :broken_heart:
SLIME Inspector is opened.

*Expected behaviour:* :heart: :smile:
slime-edit-definition is fired and opens the file where function is defined.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.50.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp common-lisp git org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
;; none
```

**Comment by bmag** [comment]
SLIME Inspector is opened because `SPC mgg` is bound to `slime-inspect-definition`. (`gd` calls the function bound to `SPC mgg`). I don't know which function is better: `slime-inspect-definition` or `slime-edit-definition`.
If you just want to add a binding for `slime-edit-definition` (not on `SPC mgg`), then PR welcome.

**Comment by phoe** [comment]
@bmag:
"Go to definition" should go to the definition - meaning, where the function is defined in the source code.

I am for changing the default keybinding to `slime-edit-definition` because it fulfills this - allows the user to see the source code for a given function.

`slime-inspect-definition` does not open the source code - it opens the SLIME inspector with the function **object** open in the inspector. While the function **object** contains some valuable data, it does not contain the *definition* itself - which is what the user wants in this case.

**Comment by bmag** [comment]
Ok, I was not aware that `slime-inspect-definition` doesn't go to the definition, and I don't know why it was chosen in the first place. I found an abandoned PR (#2648) on this subject, that had some issues with it.
I definitely think `slime-inspect-definition` should move to `SPC m h i` (or similar), and `slime-edit-definition` should be the "goto" function (the "goto" function is configured in `common-lisp/config.el`).

**Comment by phoe** [comment]
I sadly do not know how to make a PR for Spacemacs. Will substituting the function name in https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/common-lisp/config.el be enough for this? Also, how do I add a new binding for `SPC m h i`?

**Comment by bmag** [comment]
> Will substituting the function name in https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/common-lisp/config.el be enough for this?

Should be enough.

> how do I add a new binding for `SPC m h i`?

Look at `common-lisp/packages.el`, it already defines several keys with `spacemacs/set-leader-keys-for-major-mode`. It's also worth reading the documentation for functions/macros/variables you encounter along the way.

**Comment by phoe** [comment]
https://github.com/syl20bnr/spacemacs/pull/8051 was created.
