### ISSUE TITLE
Changes coming to org-projectile

### ISSUE THREAD

**Issue by IvanMalison** [syl20bnr/spacemacs#8045]
I have a pretty serious refactor coming for org-projectile (work is happening at https://github.com/IvanMalison/org-projectile/tree/big-changes, but I have not put most of the changes there yet.)

I'm going to try to keep it as backwards compatible as possible, but there may be some things that I'm not able to do this for.

As I'm not a spacemacs user, I'm not sure if spacemacs is able to pull packages from melpa-stable or something like that, but it may be a good idea to do so for org-projectile if possible. If not I can always make a pull request to try to ensure that thing still work in spacemacs, but things may not work for users with old version of spacemacs

**Comment by syl20bnr** [comment]
Thank you for warning us about the changes.
Make your changes and we will update Spacemacs as fast as possible to match the development in progress.

**Comment by IvanMalison** [comment]
@TheBB These changes are here. Not sure how you want to deal with this. I'm happy to adapt the existing spacemacs code to the new stuff, but unfortunately that will cause breakage for people that still have the old code (This is probably why backwards incompatible changes are bad).

Maybe the best thing to do is to check to see if they have an old version of org-projectile and then message about updating in case of an error?

**Comment by IvanMalison** [comment]
This has happened and the changes have been made in spacemacs see #9312
