### ISSUE TITLE
Complete freeze of spacemacs anytime new window is opened with 100% CPU

### ISSUE THREAD

**Issue by bryanbecker** [syl20bnr/spacemacs#8060]
**UPDATE**  I have narrowed the issue down to vim-empty-lines layer.  Remove that layer seems to fix the issue

#### Description :octocat:

Anytime I open a 2nd window, spacemacs freezes instantly, and then quickly consumes 100% CPU.  Same things happens when running `SPC h d s`

#### Reproduction guide :beetle:
- Start Emacs
- open file
- open new window (same file or new file, doesn't matter)
- almost instant freezing

*Observed behaviour:* :eyes: :broken_heart:
Freezing

*Expected behaviour:* :heart: :smile:
No Freezing

(%LAST_KEYS%)
%SYSTEM_INFO%
(sorry, not sure what to replace the above with)

Extra info:

Spacemacs version 0.200.5@24.5.1
Ubuntu

Backtrace below is obtained by running `pkill -SIGUSR2 emacs`.  Those are the only two lines displayed.

Nothing is "autogenerated" at the bottom of my .spacemacs file (unsure if expected or unexpected behavior).

Already tried based on reading other issues with no result:

 - adding `(setq helm-echo-input-in-header-line nil)` to user-config

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (quit)
  Redisplay_internal \ \(C\ function\)()
```

**Comment by bryanbecker** [comment]
Follow up:

Completely reinstalling everything seems to have fixed the issue, at least temporarily.  Will reopen issue if problem returns

**Comment by bryanbecker** [comment]
This is still happening every time

**Comment by bryanbecker** [comment]
I figured out how to reproduce with 100% effectiveness:

1.  Open more than one window horizontally
2.  With focus on the top window, press any key that causes helm to appear (such as `:`)
3.  Helm doesn't appear; spacemacs freezes, CPU use goes to 100%

**Comment by syl20bnr** [comment]
May be duplicate of https://github.com/syl20bnr/spacemacs/issues/7964

**Comment by syl20bnr** [comment]
From OP it seems that removing `vim-empty-lines` layer fixes it.
https://github.com/syl20bnr/spacemacs/issues/7964#issuecomment-272362778
