### ISSUE TITLE
Package development workflow

### ISSUE THREAD

**Issue by jameskolce** [syl20bnr/spacemacs#8063]
Hello,

I just installed Spacemacs and I love it so far (thank you), however, I'm a little confused regarding the development of a package for Emacs.

I'm improving some things in the [emacs-pug-mode](https://github.com/hlissner/emacs-pug-mode) package, before installing Spacemacs my workflow was:

1. Clone the package repository in `.emacs.d/packages/emacs-pug-mode`.
2. Include the .el file with `(add-to-list 'load-path "~/.emacs.d/packages/emacs-pug-mode")`.
3. Open `pug-mode.el` and `test.pug` in different windows.
4. Make changes to `pug-mode.el`.
5. Restart the `test.pug` window to see changes.
6. Repeat step 4 until everything is good.
7. Commit changes and push to the repository

However, looks like with Spacemacs things are different, and that's where I'm lost. What's the optimal way to do it with Spacemacs? considering that pug-mode is already included in a layer.

Thanks.

**Comment by jameskolce** [comment]
Alright, maybe I'm getting closer, I tried doing:

```elisp
dotspacemacs-additional-packages '((pug-mode :location local))
```

And cloning my [emacs-pug-mode](https://github.com/jameskolce/emacs-pug-mode) fork in `layers/+lang/html/local/`. Since the repository is cloned as `emacs-pug-mode` I was getting `File mode specification error: (file-error Cannot open load file No such file or directory pug-mode)`, but after changing the directory name to `pug-mode` it was working.

Now I can follow a workflow similar to the one I mentioned from step 3 to 7 but it feels a little slow, is there a way to improve the process?

**Comment by jameskolce** [comment]
I wrote this function and keybinding inside `user-config`:

```elisp
(defun reload-current-major-mode ()
    "Reloads the current major mode."
    (interactive)

    (let ((mode major-mode))
      (progn
        (message "%s is going to be unloaded" mode)
        (unload-feature mode t)
        (message "%s unloaded" mode)
        (funcall-interactively mode)
        (message "%s loaded" mode))
      )
    )

  (evil-leader/set-key "m r" 'reload-current-major-mode)
```

Now I can see my changes with <kbd>M-m m r</kbd> without having to restart emacs or without having to unload and load the mode manually.

That was all the problem, the process now feels more natural. If there is a better way to do this I would like to know, otherwise this issue can be closed, I'm happy now.

**Comment by sergeyklay** [comment]
Just found this https://stackoverflow.com/q/4359653/1661465
