### ISSUE TITLE
Idea: better start experience ala vim-startify

### ISSUE THREAD

**Issue by jasonkuhrt** [syl20bnr/spacemacs#807]
I thought this was a great idea: https://github.com/mhinz/vim-startify

I've been using it in `vim` for a week or so now and generally my feeling has been that it helps provide better context on boot. Its helpful to "continue from where you left off" or get a sense for "what you've been doing lately".

I think spacemacs could take this a lot further but I just wanted to reference it as an example to get the discussion going.

At this point I can only contribute the suggestion, maybe I can help implement this or other things in the future.

**Comment by stormpat** [comment]
That looks really nice!

**Comment by syl20bnr** [comment]
Thank you for the great idea and reference!

This is a planned feature of spacemacs but... when ? I don't know. :-)

**Comment by CarlQLange** [comment]
I was inspired by this, so I put a bit of it together. Works for recent files, projects, and bookmarks (I don't use them so they don't show up). Sorry for the blacked-out project titles.

![screen shot 2015-03-28 at 16 22 55](https://cloud.githubusercontent.com/assets/859820/6881413/1ecefe96-d567-11e4-979f-b89753ad8744.png)

I'm a complete noob at this - picked up Spacemacs about two weeks ago for the first time. [Here's the commit on my fork with the code](https://github.com/syl20bnr/spacemacs/commit/e7740d9ced2bbc38e8bd81af7448bb54a362bad3). It's probably totally awful, so any tips would be greatly appreciated! I'd love to contribute to Spacemacs, so please let me know if there's anything I can do to further that goal :)

**Comment by stormpat** [comment]
@CarlQLange Good job!

**Comment by CarlQLange** [comment]
Here's an update, with configurable lists, and its own branch (so this could theoretically be merged): https://github.com/syl20bnr/spacemacs/compare/develop...CarlQLange:feature-startup-lists

Not sure where to go from here. Suggestions welcome! :)

**Comment by syl20bnr** [comment]
This is really cool, nice work !

My review:
- when you are comparing symbols you can use `eq` instead of `equal`. `eq` is a more efficient.
- delcare the new dotspacemacs variable in the `core/core-dotspacemacs.el` with a default value. This is where all the dotspacemacs variables get their default variable. Thus you won't have to check if the variable has been bound.

Create a PR whenever you want :+1:

**Comment by tuhdo** [comment]
After this, it will be even more convenient with [ace-link](https://github.com/abo-abo/ace-link).

**Comment by CarlQLange** [comment]
It looks like ace-link doesn't work with these links, because it's not an Info, eww, org, or help buffer. I guess I could fork it and add the necessary feature... Is that the right way to go about it in emacs-land?

**Comment by tuhdo** [comment]
@CarlQLange you are right. Yes, you could fork it, but you should also contribute back to the main repo to avoid future confusion for the community. Or you can create your own package, something like `ace-button` and add it to Spacemacs core packages.

**Comment by CarlQLange** [comment]
I guess this can be closed? That feature is merged :) But it could still be improved with ace-link.
