### ISSUE TITLE
Elixir: checker does not work

### ISSUE THREAD

**Issue by dvzubarev** [syl20bnr/spacemacs#8070]
#### Description :octocat:
Elixir checker (credo) does not work.

#### Reproduction guide :beetle:
- Create test project: `mix new test`
- Follow these  [instructions](https://github.com/syl20bnr/spacemacs/tree/develop/layers/+lang/elixir#credo).
- Open `test/lib/test.ex` in emacs.
- `SPC-e-l`

*Observed behaviour:* :eyes: :broken_heart:
No errors

*Expected behaviour:* :heart: :smile:
There should be one error:
`1  11 info            Modules should have a @moduledoc tag. (elixir-credo)`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.2
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
 spacemacs-layouts ibuffer
 (colors :variables colors-enable-rainbow-identifiers t)
 emacs-lisp semantic my-dired my-diffs my-projects
 (dash :variables helm-dash-docset-newpath "~/.local/share/Zeal/Zeal/docsets")
 my-dash eww python my-python docker ansible my-ansible cypher
 (c-c   :variables c-basic-offset 4 c-default-style "linux" c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support nil)
 c   markdown html
 (org :variables org-enable-reveal-js-support t)
 my-org pandoc ob-ipython
 (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
 my-shell
 (syntax-checking :variables syntax-checking-enable-by-default t)
 spell-checking
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 git github my-gpg advance-vc evil-cleverparens
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 finance sql edbi edit-utils imenu-list prog-utils vagrant vinegar yaml my-ycmd floobits exactus csv elixir my-elixir plantuml my-plantuml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by dvzubarev** [comment]
There is a PR, that fixes this issue (#8052).

**Comment by thecodethinker** [comment]
This doesn't seem to be fixed in dev. I still see nothing after hitting `SPC-e-l`

**Comment by thecodethinker** [comment]
So it looks like you also need to add `dogma` to the project deps for the whole thing to work. I'm going to make a pull request adding that to the docs

**Comment by dvzubarev** [comment]
Hi,
It does not work due to credo regression. I reported upstream https://github.com/rrrene/credo/issues/349 
Dogma goes with flycheck and it heavily overlaps with credo. I think there is no reason to use both of them in one project. It may be mentioned in the docs as an alternative to credo.

**Comment by thecodethinker** [comment]
I'm also seeing thing when running `flycheck-verify-checker`

```
Syntax checker in buffer table_sup.ex in elixir-mode:

  elixir-credo
    - major mode: `elixir-mode' supported
    - may enable: yes
    - predicate:  nil
    - executable: Found at /usr/local/bin/mix

Flycheck cannot use this syntax checker for this buffer.

Flycheck Mode is enabled. Use SPC u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 31snapshot (package: 20170323.614)
Emacs version:    25.1.1
System:           x86_64-apple-darwin13.4.0
Window system:    ns
```

**Comment by dvzubarev** [comment]
It is strange. Did you try to run credo from the command line? `mix credo` Are you sure it is installed without any error? Try install 0.6.1 for now. `{:credo, "== 0.6.1", only: [:dev, :test]}`. It works for me. 
Also for further testing you can use `C-c ! C-c` It wil show the command that flycheck tries to run and its output.

**Comment by thecodethinker** [comment]
It works from the command line just fine. It gives me the correctly formatted flycheck output too

When I run `C-c ! C-c` it just tells me that `Flycheck cannot use this syntax checker for this buffer.`

**Comment by benbotwin** [comment]
Why was this closed? Was there a fix?

**Comment by benbotwin** [comment]
@dvzubarev Does this now work for you on `develop`? Flycheck still isn't giving me any credo messages

**Comment by dvzubarev** [comment]
@benbotwin It works for me with credo 0.6.1 but not with recent 0.7.3. 
`predicate:  nil` in the output of `flycheck-verify-checker` means that flycheck can't locate `deps/credo/` directory in your project. Does this directory exist?

**Comment by benbotwin** [comment]
Ah I had credo 0.7.3 installed globally. Do you know if the latest version not working is a spacemacs bug or a credo bug?

If it's a spacemacs bug, this issue should stay open right?

@dvzubarev

**Comment by dvzubarev** [comment]
There is still a problem in credo. See https://github.com/rrrene/credo/issues/349#issuecomment-289197109
I will try to investigate it or report a new issue at least.
