### ISSUE TITLE
Semantic layer misbehaiving

### ISSUE THREAD

**Issue by vv111y** [syl20bnr/spacemacs#8072]
#### Description :octocat:
emacs/nextstep/Emacs.app/Contents/Resources/lisp/cedet/ede/loaddefs.el: Obsolete name arg "emacs" to constructor ede-project-autoload
emacs/nextstep/Emacs.app/Contents/Resources/lisp/cedet/ede/loaddefs.el: Obsolete name arg "linux" to constructor ede-project-autoload
Loading /Users/Will/.emacs.d/.cache/company-statistics-cache.el (source)...done
Cache Error: [/Users/Will/.emacs.d/.cache/semanticdb/!usr!include!sys!semantic.cache] (error In save file, list of object constructors found, but no :type specified for slot reference-directory of type nil), Restart
eieio--validate-slot-value: Invalid slot type: semanticdb-project-database-file, reference-directory, string, nil

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>
can't recall what happened. fresh install of emacs via homebrew and still there.
Currently happens only in GUI app, not terminal. But it has happened there as well. 

*Observed behaviour:* :eyes: :broken_heart:
doesn't work
fwiw autocomplete very slow - unusable.

*Expected behaviour:* :heart: :smile:
Want to have semantic/cedet work

(%LAST_KEYS%)
#### System Info :computer:
- OS: darwin
- Emacs: 25.0.50.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 8840c94)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 ansible better-defaults bibtex c-c++ chrome clojure command-log common-lisp cscope deft docker emacs-lisp erc ess fasd finance git github go haskell html ibuffer imenu-list ipython-notebook java javascript latex lua
 (markdown :variables markdown-live-preview-engine 'vmd)
 nim
 (osx :variables osx-use-option-as-meta t)
 (org :variables org-enable-github-support t org-enable-reveal-js-support t org-enable-bootstrap-support t org-startup-indented t org-startup-folded t org-projectile-file "TODOs.org")
 pandoc pdf-tools php python ranger scala search-engine semantic
 (spell-checking :variables spell-checking-enable-by-default nil)
 sql syntax-checking
 (shell :variables shell-default-height 30 shell-default-position 'right)
 themes-megapack tmux vagrant version-control WillsLayer)
```

#### Backtrace :paw_prints:
```
%BACKTRACE%
```

**Comment by bmag** [comment]
I don't really know what's happening (I tried Semantic and didn't like it), but have you tried deleting `/Users/Will/.emacs.d/.cache/semanticdb/!usr!include!sys!semantic.cache`? (or perhaps the entire `/Users/Will/.emacs.d/.cache/semanticdb` directory)

**Comment by vv111y** [comment]
closing, sorry I didn't attend to this before.
