### ISSUE TITLE
void function org-link-types

### ISSUE THREAD

**Issue by sangjeedondrub** [syl20bnr/spacemacs#8074]
how to fix the following error which occurs when opening an org file
```lisp
Debugger entered--Lisp error: (void-function org-link-types)
  (org-link-types)
  (regexp-opt (org-link-types))
```

**Comment by d12frosted** [comment]
@sangjeedondrub it's great that you opened this issue without reading the message we posted for new issues. I am going to duplicate it in the end of my comment. Since you have already opened this issue, could you please share the output of `SPD h d s`? Also, have you updated all your packages? 

> If you are posting about a *bug* please close this issue and open a new one
using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs. If the
bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template)
You can delete this message to start typing.

**Comment by sangjeedondrub** [comment]
```
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. f5957eb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy better-defaults github ranger colors prodigy search-engine graphviz
     (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips nil)
     (spell-checking :variables spell-checking-enable-by-default nil)
     (vinegar :variables vinegar-reuse-dired-buffer t)
     (spacemacs-layouts :variables layouts-enable-autosave nil layouts-autosave-delay 300)
     (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
     (ibuffer :variables ibuffer-group-buffers-by 'projects)
     (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t :disabled-for org markdown)
     (osx :variables osx-dictionary-dictionary-choice "Simplified Chinese - English")
     restclient
     (gtags :disabled-for clojure emacs-lisp javascript latex python shell-scripts)
     (shell :variables shell-default-shell 'eshell)
     docker deft markdown org shaders yaml react
     (python :variables python-test-runner
             '(nose pytest))
     (ruby :variables ruby-version-manager 'chruby)
     ruby-on-rails lua html javascript
     (typescript :variables typescript-fmt-on-save nil typescript-fmt-tool 'typescript-formatter)
     emacs-lisp
     (clojure :variables clojure-enable-fancify-symbols t)
     racket
     (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
     zilongshanren
     (chinese :packages youdao-dictionary fcitx :variables chinese-enable-fcitx nil chinese-enable-youdao-dict t))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES
```

**Comment by lujianmei** [comment]
@sangjeedondrub  It seems you copied configuration from https://github.com/zilongshanren/spacemacs-private
And there is a setting which will cause this issue which was defined in this file:
https://github.com/zilongshanren/spacemacs-private/blob/develop/layers/zilongshanren-org/packages.el
you will find:  `(org :location built-in)`
and spacemacs using org-plus-contrib package which is a newer org-mode version, and built-in is an old version.
So you can just change 
`(org :location built-in)`
into 
`org`
It will be ok.

**Comment by RockyRoad29** [comment]
I'm using the official repo and the "faulty statement" is there:
https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bemacs/org/packages.el#L24

Since my today's upgrade to Spacemacs 0.200.7 I find many issues related to this `org-link-type` type change.
I'm gathering more information here:
https://gist.github.com/RockyRoad29/55936d3f1e220f5db093dc028e321e0c

**Comment by RockyRoad29** [comment]
Date:   Fri Feb 17 23:16:52 2017 +0100

    FIX #8074: removed org-plus-contrib packages from org-layer
```
diff --git a/layers/+emacs/org/packages.el b/layers/+emacs/org/packages.el
index 4963f4a43..1ed3af9f6 100644
--- a/layers/+emacs/org/packages.el
+++ b/layers/+emacs/org/packages.el
@@ -20,12 +20,13 @@
     htmlize
     mu4e
     ;; ob, org and org-agenda are installed by `org-plus-contrib'
-    (ob :location built-in)
-    (org :location built-in)
-    (org-agenda :location built-in)
+    ;; which is loaded from core layers/+spacemacs/spacemacs-org/packages.el
+    ;; (ob :location built-in)
+    ;; (org :location built-in)
+    ;; (org-agenda :location built-in)
     org-download
     ;; org-mime is installed by `org-plus-contrib'
-    (org-mime :location built-in)
+    ;; (org-mime :location built-in)
     org-pomodoro
     org-present
     (org-projectile :toggle (configuration-layer/package-usedp 'projectile))
```
This solves the first issue:
```elisp
ELISP> (functionp #'org-link-types)
t
```
The concerned packages are still available, but now without loading anything from `emacs/site-lisp/`
```elisp
ELISP> (require 'ob)
ob
ELISP> (require 'org)
org
ELISP> (require 'org-agenda)
org-agenda
ELISP> (setq l1 (seq-filter (lambda (x) (string-match "/org" x)) (mapcar #'car load-history)) rslt t)
t
ELISP> (length l1)
50 (#o62, #x32, ?2)
ELISP> (prog1 t (dolist (x l1) (princ x) (princ "\n")))
/home/mich/.emacs.d/elpa/org-20170210/org-agenda.elc
/home/mich/.emacs.d/elpa/org-plus-contrib-20170210/org-eldoc.elc
/home/mich/.emacs.d/layers/+emacs/org/local/evil-org/evil-org.el
/home/mich/.emacs.d/elpa/org-bullets-20140918.1137/org-bullets.elc
/home/mich/.emacs.d/elpa/org-download-20170213.1151/org-download.elc
/home/mich/.emacs.d/elpa/org-20170210/org-rmail.elc
/home/mich/.emacs.d/elpa/org-20170210/org-mhe.elc
/home/mich/.emacs.d/elpa/org-20170210/org-irc.elc
/home/mich/.emacs.d/elpa/org-20170210/org-info.elc
/home/mich/.emacs.d/elpa/org-20170210/org-gnus.elc
/home/mich/.emacs.d/elpa/org-20170210/org-docview.elc
/home/mich/.emacs.d/elpa/org-20170210/org-bibtex.elc
/home/mich/.emacs.d/elpa/org-20170210/org-bbdb.elc
/home/mich/.emacs.d/elpa/org-20170210/org-w3m.elc
/home/mich/.emacs.d/elpa/orgit-20170118.1647/orgit.elc
/home/mich/.emacs.d/elpa/org-20170210/org-element.elc
/home/mich/.emacs.d/elpa/org-20170210/org.elc
/home/mich/.emacs.d/elpa/org-20170210/org-macro.elc
/home/mich/.emacs.d/elpa/org-20170210/org-footnote.elc
/home/mich/.emacs.d/elpa/org-20170210/org-pcomplete.elc
/home/mich/.emacs.d/elpa/org-20170210/org-list.elc
/home/mich/.emacs.d/elpa/org-20170210/org-faces.elc
/home/mich/.emacs.d/elpa/org-20170210/org-entities.elc
/home/mich/.emacs.d/elpa/org-20170210/org-version.el
/home/mich/.emacs.d/elpa/org-20170210/ob-emacs-lisp.elc
/home/mich/.emacs.d/elpa/org-20170210/ob.elc
/home/mich/.emacs.d/elpa/org-20170210/ob-tangle.elc
/home/mich/.emacs.d/elpa/org-20170210/org-src.elc
/home/mich/.emacs.d/elpa/org-20170210/ob-ref.elc
/home/mich/.emacs.d/elpa/org-20170210/ob-lob.elc
/home/mich/.emacs.d/elpa/org-20170210/ob-table.elc
/home/mich/.emacs.d/elpa/org-20170210/ob-keys.elc
/home/mich/.emacs.d/elpa/org-20170210/ob-exp.elc
/home/mich/.emacs.d/elpa/org-20170210/ob-comint.elc
/home/mich/.emacs.d/elpa/org-20170210/ob-core.elc
/home/mich/.emacs.d/elpa/org-20170210/ob-eval.elc
/home/mich/.emacs.d/elpa/org-20170210/org-compat.elc
/home/mich/.emacs.d/elpa/org-20170210/org-macs.elc
/home/mich/.emacs.d/elpa/org-20170210/org-loaddefs.el
/home/mich/.emacs.d/elpa/orgit-20170118.1647/orgit-autoloads.el
/home/mich/.emacs.d/elpa/org-projectile-20161205.1508/org-projectile-autoloads.el
/home/mich/.emacs.d/elpa/org-present-20141109.1756/org-present-autoloads.el
/home/mich/.emacs.d/elpa/org-20170210/org-autoloads.el
/home/mich/.emacs.d/elpa/org-pomodoro-20161119.226/org-pomodoro-autoloads.el
/home/mich/.emacs.d/elpa/org-download-20170213.1151/org-download-autoloads.el
/home/mich/.emacs.d/elpa/org-bullets-20140918.1137/org-bullets-autoloads.el
/home/mich/.emacs.d/elpa/org-plus-contrib-20170210/org-plus-contrib-autoloads.el
/home/mich/.emacs.d/layers/+emacs/org/config.el
/home/mich/.emacs.d/layers/+emacs/org/funcs.el
/home/mich/.emacs.d/layers/+emacs/org/packages.el

t

```

**Comment by RockyRoad29** [comment]
The patch I submitted appears not to be a solution, sorry for the inconvenience.
More details in the comments of the PR #8399 .

**Comment by syl20bnr** [comment]
Thank for all the effort you put in this investigation 💜  Indeed this PR is not a valid solution and break Spacemacs loading mechanism so I close this PR.

**Comment by coljamkop** [comment]
For me I used C-h v and typed in org-link-types to determine where it was. Turned out that emacs was not referencing the org installed through/updated through melpa, in .emacs.d rather it was referencing the org installed through homebrew in my Emacs.app directory.

**Potential solution (for Macs)**:
`brew update`

**Comment by imcvampire** [comment]
This is my output:


#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by brickZA** [comment]
I've run into this issue with recent fresh spacemacs installs both on macos and ubuntu 17.04. In both cases the emacs configs were completely vanilla with no pre-configuration apart from cloning spacemacs.

In can confirm that changing spacemacs packages.el for the or layer as follows seems to fix the issue for me:

```
diff --git a/layers/+emacs/org/packages.el b/layers/+emacs/org/packages.el
index 06d73192..568aaeb6 100644
--- a/layers/+emacs/org/packages.el
+++ b/layers/+emacs/org/packages.el
@@ -21,8 +21,10 @@
     mu4e
     ;; ob, org and org-agenda are installed by `org-plus-contrib'
     (ob :location built-in)
-    (org :location built-in)
+    ;; (org :location built-in)
+    org
```

I'm not sure what else this would break, but so far so good :)

**Comment by malcook** [comment]
I expect the issue is really that the version of the .el file was compile under different version of emacs than currently running.  Delete the package, restart emacs with -Q, re-get the package(s), all should be good.  I just recovered myself from this issue as I describe.

**Comment by RockyRoad29** [comment]
Given the docstring of [`byte-recompile-directory`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Compilation-Functions.html#Compilation-Functions#index-byte_002drecompile_002ddirectory-1161
"link to gnu manual") :

    (byte-recompile-directory DIRECTORY &optional ARG FORCE)

> Recompile every ‘.el’ file in DIRECTORY that needs recompilation.
> This happens when a ‘.elc’ file exists but is older than the ‘.el’ file.
> Files in subdirectories of DIRECTORY are processed also.
>
> If the ‘.elc’ file does not exist, normally this function **does not**
> compile the corresponding ‘.el’ file.  However, if the prefix argument
> ARG is 0, that means do compile all those files.  A nonzero
> ARG means ask the user, for each such ‘.el’ file, whether to
> compile it.  A nonzero ARG also means ask about each subdirectory
> before scanning it.
>
> If the third argument FORCE is non-nil, recompile every ‘.el’ file
> that already has a ‘.elc’ file.

I think that `spacemacs/recompile-elpa` could be rewritten like this:

```elisp
      (defun spacemacs/recompile-elpa (arg)
        "Compile or recompile packages in elpa directory, if needed, that is
    if the corresponding .elc file is either missing or outdated.

      If ARG is non-nil, also recompile every `.el' file, regardless of date.

      Useful if you switch Emacs versions."
        (interactive "P")
        (byte-recompile-directory package-user-dir 0 ARG))
```

Currently, it just calls

```elisp
  (byte-recompile-directory package-user-dir nil t)
```

which means that *missing .elc files won't be rebuilt*, but existing
ones will be recompiled over and over each time (time-consuming for often no improvement).
