### ISSUE TITLE
Javascript layer: js2 and flycheck conflict on `next-error-function`

### ISSUE THREAD

**Issue by lbonn** [syl20bnr/spacemacs#8078]
#### Description :octocat:

I'd like to delegate syntax checking to flycheck in javascript mode.

When the layer is enabled, js2 conflicts with flycheck and makes it hard to cycle through errors.
This happens even if js2 is configured to silence its warnings (`js2-mode-show-parse-errors` and `js2-mode-show-strict-warnings` set to `nil`).

Apparently, in my setup, js2 sets `next-error-function` after flycheck. So, this works for me (in `dotspacemacs/user-config`):

```
(setq js2-mode-show-parse-errors nil)
(setq js2-mode-show-strict-warnings nil)
(add-hook 'js2-init-hook
          '(lambda ()
              (setq next-error-function 'flycheck-next-error)
              )
          )
```

I've been trying spacemacs (and emacs) for about a week, so I don't know if this should go into the javascript layer like this...

#### Reproduction guide :beetle:
- Start Emacs
- Disable js2 errors
- Open a javascript file with errors
- Look at `spacemacs/goto-flycheck-error-list`
- Try to cycle with `]q`

*Observed behaviour:* :eyes: :broken_heart:

The error jumps do not match with the flycheck list.

*Expected behaviour:* :heart: :smile:

`spacemacs/next-error` should use `flycheck-next-error`.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: nil (rev. 664ba6ab)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults git
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      (spell-checking :variables spell-checking-enable-by-default nil)
      syntax-checking version-control org evil-commentary evil-snipe vinegar c-c++ emacs-lisp haskell html javascript markdown python yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by duianto** [comment]
The following PR is now on the `develop` branch:
javascript, typescript and react layers: linter option, next-error-function fix #12207
