### ISSUE TITLE
[META] Consider using Danger to do cursory checks and inform users

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#8079]
I know we've all gotten used to telling users to do things. I propose we use [Danger](https://danger.systems) to do this. Looks cool -- runs from Travis. 

Opinions?

**Comment by bmag** [comment]
Looks interesting to me, but will require someone to actually set it up. Are there any examples of projects using it?

**Comment by robbyoconnor** [comment]
the option is http://gitmate.io
