### ISSUE TITLE
macOS Source Code Pro font installation step

### ISSUE THREAD

**Issue by ylluminate** [syl20bnr/spacemacs#8085]
For Step 3 regarding installing Source Code Pro, it might be nice to provide macOS users a quick incantation to get the font:

~~brew tap caskroom/fonts~~
~~brew cask install font-source-code-pro~~

2021 UPDATE: 

Can use the following for homebrew:
```
brew tap homebrew/cask-fonts
brew install --cask font-source-code-pro
```

But I would prefer to use a MacPorts options since we're eliminating homebrew from our workflow entirely. For now we're just manually installing fonts vs homebrew.

**Comment by nikolaiam** [comment]
Good idea! I included your suggestion in a PR moving the installation instructions from the readme to the beginners tutorial: #8217

**Comment by syl20bnr** [comment]
@nikolaiam could you submit the change on the README.md file directly instead ?

**Comment by nikolaiam** [comment]
Done in #8752!

**Comment by Blaisorblade** [comment]
The PR was cherry-picked into the develop branch (though it's somehow not yet in master, which would be nice, not sure what the branch model is). Should this issue be closed?

**Comment by lambdamusic** [comment]
These days the right commands are 

```
brew tap homebrew/cask-fonts
brew cask install font-source-code-pro
```

**Comment by ylluminate** [comment]
So close, yet so far away ;)

**Comment by mukherjeea** [comment]
for those who are listening to this in 2020 commands are as follows

`$brew tap homebrew/cask-fonts`
`$brew install font-source-code-pro`

**Comment by duianto** [comment]
It looks like `brew cask <command>` was:
- deprecated on 2020-12-01
- disabled on 2020-12-21

in favor of `brew <command> --cask`

sources:
https://github.com/Homebrew/discussions/discussions/340#discussioncomment-232364
https://github.com/ansible-collections/community.general/issues/1524#issuecomment-749945392

Can someone with knowledge about how `brew` and `cask`  works, open a PR that updates the readme instructions:
https://github.com/syl20bnr/spacemacs#using-cask
https://github.com/syl20bnr/spacemacs#install-source-code-pro-font

**Comment by sshine** [comment]
@ylluminate: Could you perhaps edit your original post and update the commands?

This would save a few seconds overall. :)

**Comment by duianto** [comment]
The font installation instructions:
https://github.com/syl20bnr/spacemacs/blob/develop/README.md#install-source-code-pro-font

Have just been updated to list both the new and old syntax:
Update README.md with new Cask syntax #14576

**Comment by ylluminate** [comment]
@sshine updated as you requested, but would like to see a MacPorts option since we've needed to eliminate homebrew from our workflow for various reasons.

**Comment by lebensterben** [comment]
how to install a font is quite out of scope.

closing.
