### ISSUE TITLE
neotree won't show help under Emacs style key-binding

### ISSUE THREAD

**Issue by asdfasdfasdfasdf4** [syl20bnr/spacemacs#8086]
**Description**:
Neotree will prompt "Cannot make side window the only window" and no hot-key help shows up when "?" is pressed under Emacs style key binding, where Vim style key-binding works perfectly, does shows the help prompt.

**Reproduction Guide** (The problem):
1) set dotspacemacs to _emacs_ style key-binding
2) Start spacemacs "M-x neotree"
3) In the neotree side window press "?"

_Observed Behaviour_:
Will prompt "Cannot make side window the only window"
![emacs](https://cloud.githubusercontent.com/assets/24813745/21578296/5b54eb54-cfad-11e6-95aa-e954d976e0de.png)

_Expected Behaviour_:
Shows a new window above the mini-buffer on short-cuts for neotree.
Under Vim style key-binding, the help window does appear.

#### System Info :computer:
- OS: gnu/linux (Linuxmint 17)
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(python helm auto-completion emacs-lisp spell-checking syntax-checking)
```

**Comment by bmag** [comment]
Using develop branch, I had to disable `purpose-mode` to be able to reproduce the error. Here's the backtrace:
```
Debugger entered--Lisp error: (error "Cannot make side window the only window")
  signal(error ("Cannot make side window the only window"))
  error("Cannot make side window the only window")
  delete-other-windows(#<window 550 on  *NeoTree*>)
  #[(&rest --cl-rest--) "\203\f [ ... snipped byte-code ...]
  apply(#[(&rest --cl-rest--) "\203\f [ ... snipped byte-code ...]
  ad-Advice-popwin:create-popup-window(#[(&rest --cl-rest--) "\203\f [ ... snipped byte-code ...]
  apply(ad-Advice-popwin:create-popup-window #[(&rest --cl-rest--) "\203\f [ ... snipped byte-code ...]
  popwin:create-popup-window(0.4 bottom t)
  popwin:popup-buffer(#<buffer *Help*> :width 30 :height 0.4 :position bottom :noselect t :dedicated t :stick t :tail nil)
  popwin:display-buffer-1(#<buffer *Help*> :if-config-not-found #[(buffer) "\302	\"\207" [buffer not-this-window popwin:original-display-buffer] 3])
  popwin:display-buffer(#<buffer *Help*> nil)
  popwin:display-buffer-action(#<buffer *Help*> nil)
  display-buffer(#<buffer *Help*> nil)
  temp-buffer-window-show(#<buffer *Help*> nil)
  describe-mode()
  funcall-interactively(describe-mode)
  call-interactively(describe-mode nil nil)
  command-execute(describe-mode)
```

Apparently, `popwin` doesn't handle side windows correctly, and `neotree` had become a real side window (from a technical perspective) a few months ago. This probably reproduces with stock Emacs, Neotree and Popwin, so I suggest you report it upstream to [Popwin](https://github.com/m2ym/popwin-el)

**Comment by bmag** [comment]
For anyone wondering, this only happens for Emacs editing style, because in Hybrid and Vim editing styles a transient state is used instead of calling `describe-mode`.

**Comment by feluxe** [comment]
I get the same error when I open Neotree and try to create a new file `SPC-f-T c`

> Cannot make side window the only window.

I'm using Vim editing style.

**Comment by bmag** [comment]
@feluxe that's a different upstream issue, see https://github.com/jaypei/emacs-neotree/issues/226

**Comment by clm1** [comment]
Related issue I think: when trying to delete multiple buffers from IBuffer while neotree is open on the side, I get: 
```
Cannot split side window or parent window of side window
```

**Comment by oracleyue** [comment]
I confirm the bug pointed by @bmag : it is due to `popwin`. Once I turn off the `popwin` mode, it will work fine.

**Comment by dennismayr** [comment]
> I confirm the bug pointed by @bmag : it is due to `popwin`. Once I turn off the `popwin` mode, it will work fine.

This worked for me too.

Proposed solutions in [NeoTree](https://github.com/jaypei/emacs-neotree/issues/226) did not.
