### ISSUE TITLE
base16-theme package is missing base16-onedark and others

### ISSUE THREAD

**Issue by metamode** [syl20bnr/spacemacs#8087]
#### Description
The base16-theme package is missing the following themes:
 - base16-atelier-cave-light
 - base16-atelier-dune-light
 - base16-atelier-estuary-light
 - base16-atelier-forest-light
 - base16-atelier-heath-light
 - base16-atelier-lakeside-light
 - base16-atelier-plateau-light
 - base16-atelier-savanna-light
 - base16-atelier-seaside-light
 - base16-atelier-sulphurpool-light
 - base16-cupcake
 - base16-materia
 - base16-mexico-light
 - base16-onedark
 - base16-rebecca
 - base16-seti
 - base16-spacemacs
 - base16-tube
 - base16-woodland

#### Reproduction guide:

1. Start Emacs
2. Add `base16-onedark` to the `dotspacemacs-themes` variable in .spacemacs (or any of the other missing base16 themes listed above).
3. Restart Emacs

#### Observed behaviour:
A default white theme is applied, and the following error message is displayed in the `*Warnings*` buffer:
>Warning (spacemacs): An error occurred while retrieving the theme, using default theme. (error: (error Package ‘base16-onedark-theme-’ is unavailable))

#### Expected behaviour:
Expected editor to install and apply the `base16-onedark` theme.

#### System Info:
OS: darwin
Emacs: 25.0.94
Spacemacs: 0.200.5
Spacemacs branch: master (rev. 9f9faa4)
Graphic display: t
Distribution: spacemacs
Editing style: vim
Completion: helm
Layers:
   '(
     yaml
     markdown
     auto-completion
     ;; better-defaults
     emacs-lisp
     (git :variables
          git-magit-status-fullscreen t)
     org
     (shell :variables
            shell-default-shell 'multi-term
            shell-default-height 30
            shell-default-position 'bottom)
     syntax-checking
     semantic
     (c-c++ :variables
              c-c++-default-mode-for-headers 'c++-mode
              c-c++-enable-clang-support t)
     python
     go
     eyebrowse
     php
     ruby
     rust
     colors
     private
     )

#### Backtrace:
N/A

**Comment by asdfasdfasdfasdf4** [comment]
I was able to reproduce the observation.

I suspect that spacemacs assume that the `base16-[name here]` is, on it's own, a package, so it adds `-theme` at the end to find the theme package. And it end up with `base16-[name here]-theme` so it can't find the package to install.*

I was also able to install the theme through `M-x package-install` and `base16-theme` then `M-x load-theme` and choose one of the theme that comes with the base16-theme package. 

*Tested using `material` theme under theme variable and spacemacs install the package with `material-theme`

**Comment by asdfasdfasdfasdf4** [comment]
Under the updated version of spacemacs (0.200.6) the error seems like it still exists.
Tested using `base16-onedark` theme in dotspacemacs file
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.6
- Spacemacs branch: master (rev. d51f619)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
![stillerror2](https://cloud.githubusercontent.com/assets/24813745/21591180/45a59fc8-d134-11e6-9494-a1788d780a3c.png)

**Comment by d12frosted** [comment]
> Under the updated version of spacemacs (0.200.6) the error seems like it still exists.

The PR was only proposed 3 days ago. And it was just merged into develop. That's why it wasn't fixed in master 2 days ago 😸 

---

@metamode thanks for finding this issue and instantly solving it 😸
