### ISSUE TITLE
Error (use-package): helm :config: ‘fuzzy-match’ not supported in async sources.

### ISSUE THREAD

**Issue by rangelke** [syl20bnr/spacemacs#8091]
#### Description
Fresh install of Spacemacs throws an error after the initial setup. Talked with some people on gitter. Apparantly [this commit](https://github.com/emacs-helm/helm/commit/53ebdfd1b49a4825f6aa556edf5dbfa94520f1b0) is causing the problem.

#### Reproduction guide
- Fresh install Emacs
- Clone Spacemacs
- Open Spacemacs, Spacemacs installs properly, no errors
- Close Spacemacs
- Open Spacemacs again
- Following line pops up: Error (use-package): helm :config: ‘fuzzy-match’ not supported in async sources.

*Observed behaviour:*
It throws an error. Fuzzy-finding does not work, SPC SPC results in the same error as above.
This happens in Spacemacs on develop and master branch, tested using Emacs 25.1 and 24.5.

*Expected behaviour:*
SPC SPC should work
No errors should popup after opening spacemacs

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```

**Comment by aldanor** [comment]
Confirming, just ran into the same thing.

**Comment by et2010** [comment]
I can confirm that. New helm update breaks spacemacs.

**Comment by aldanor** [comment]
Setting `dotspacemacs-helm-use-fuzzy` to `'source` seems like a (temporary?) workaround.

**Comment by tranchis** [comment]
> Setting dotspacemacs-helm-use-fuzzy to 'source seems like a (temporary?) workaround.

I've tried this and every operation involving helm hangs emacs.

**Comment by hujianxin** [comment]
confirm that

**Comment by DnOberon** [comment]
I was able to reproduce the bug exactly =(

**Comment by agzam** [comment]
dammit ;(

**Comment by mixmixmix** [comment]
I got the same bug after updating packages, surprisingly though I was able to roll back packages without any hacking.

**Comment by Zemacs** [comment]
I encountered the same error just now

**Comment by everettjf** [comment]
+1

**Comment by suhasdarsi** [comment]
I was able to reproduce that

**Comment by syl20bnr** [comment]
Should be fixed in develop, looking for a hotfix release in master.

**Comment by hujianxin** [comment]
thanks very much

**Comment by rangelke** [comment]
That was fast, awesome job! ;)

**Comment by elandx** [comment]
I got the same error with `helm-recoll` and recently updated spacemacs ... :(
`Error (use-package): helm-recoll :init: ‘fuzzy-match’ not supported in async sources.`
