### ISSUE TITLE
Error ‘fuzzy-match’ not supported in async sources

### ISSUE THREAD

**Issue by elandx** [syl20bnr/spacemacs#8094]
#### Description 

I know, that the issue #8091 was closed.

But i got the same error with `helm-recoll` and recently updated spacemacs.
Sorry, but the error is not fixed for all cases yet :(

#### Reproduction guide
- Update Spacemacs (master branch)
- `helm-recoll` must be installed and configured

*Observed behaviour:* 
Error at start:
`Error (use-package): helm-recoll :init: ‘fuzzy-match’ not supported in async sources.`

*Expected behaviour:* 
Working as before update `helm-recoll`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.6
- Spacemacs branch: master (rev. d51f6199)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(python typography vimscript html helm auto-completion
        (org :variables org-enable-reveal-js-support t org-enable-github-support t)
        (shell :variables shell-default-term-shell "/bin/zsh" shell-default-height 30 shell-default-position 'bottom)
        (spell-checking :variables spell-checking-enable-by-default nil)
        emacs-lisp
        (ess :variables ess-enable-smart-equals t)
        (latex :variables latex-enable-folding t latex-enable-auto-fill t)
        (mu4e :variables mu4e-enable-mode-line t)
        asciidoc markdown lua pdf-tools csv systemd pandoc bibtex graphviz google-calendar helm-add xah-math writeroom no-mouse langtool wcheck djvu ebib multiple-cursors)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by syl20bnr** [comment]
Thanks for the report, I did a quick fix yesterday because Emacs was not usable.
I pushed the correct fix in develop, should be good now.
I will release a 0.200.7 with the correct fix.

**Comment by elandx** [comment]
Thank you!

**Comment by JoshTGreenwood** [comment]
for those coming to this later, I updated to 0.200.7 which fixed the issue for me.
