### ISSUE TITLE
Online documentation seems frozen @ 0.200.0

### ISSUE THREAD

**Issue by panchoh** [syl20bnr/spacemacs#8098]
Hi!

I've noticed that both the [stable](http://spacemacs.org/layers/+lang/go/README.html) and [development](http://develop.spacemacs.org/layers/+lang/go/README.html) online versions of the documentation seem to be stuck at precisely one day after the [0.200.0 release](https://github.com/syl20bnr/spacemacs/blob/c2774bc0dea3dbc63621709d54685fbbe9212d55/CHANGELOG.org#02000-20161002).  For instance, the linked pages above show the go layer, and both still mention the obsolete `go-oracle` tool, replaced by `go-guru`.  Note that both `master` and `develop` branches are up to date with regard to `go-guru` (both the code and the [documentation](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/go#go-guru)).

So, in the case that publishing to http://spacemacs.org and/or http://develop.spacemacs.org is an automated process, I think something might be stuck there.

Hope that it helps.

Cheers,

**Comment by d12frosted** [comment]
Thanks for the report. I am not sure how website is built, so I'll just ping @syl20bnr 😸

**Comment by panchoh** [comment]
Hi!  It seems that http://develop.spacemacs.org has been updated recently, showing the updated stuff.  Closing, then.  Thanks!
