### ISSUE TITLE
override leader key?

### ISSUE THREAD

**Issue by rphillips** [syl20bnr/spacemacs#81]
I'm working on my own customization layer. Is there a clean way to override the leader from 'space' to something else?

**Comment by joefromct** [comment]
It seems changing the leader this way doesn't set the guide-mode to pop up with my new comma-leader.   It still however works with space.

**Comment by syl20bnr** [comment]
@joefromct I received an email with a reply from you on this issue but cannot find it. Is it ok with the guide-key in the end ?

**Comment by chenyukang** [comment]
Emacs style the leader is available on M-m
How can i override leader key in Emacs style,

**Comment by TheBB** [comment]
You can try changing the appropriately named variable `dotspacemacs-emacs-leader-key` in your ~/.spacemacs file.
