### ISSUE TITLE
Window maximize bug with Neotree 

### ISSUE THREAD

**Issue by travisallison** [syl20bnr/spacemacs#8107]
#### Description :octocat:
Window mazimize doesn't toggle windows back to their previous state before being maximized when there is a side window with NeoTree.
#### Reproduction guide :beetle:
- Start Emacs
- Open a file
- Split window (either with SPACE w / or SPACE w -) 
- SPACE f t (to open the file tree)
- SPACE 1 (to go to the first window)
- SPACE w m (to maximize first window)
- SPACE w m (to toggle back to split windows)
*Observed behaviour:* :eyes: :broken_heart:
One window remains in maximized state along with the file tree side window.
*Expected behaviour:* :heart: :smile:
Two windows should appear as split windows along with the Neotree side window.  The windows should toggle back to their previous state before being maximized.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python markdown ranger c-c++ auto-completion ycmd evil-commentary
        (c-c++ :variables c-c++-enable-clang-support t)
        emacs-lisp git org ibuffer pdf-tools tmux
        (shell :variables shell-default-shell 'term shell-default-height 40 shell-default-position 'bottom)
        version-control themes-megapack)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
Was able to reproduce the bug on develop, but had to disable `purpose-mode` for it. In `spacemacs/toggle-maximize-buffer`, we should wrap `(delete-other-windows)` in a let-bind to temporarily set `ignore-window-parameters` to `t`. PR welcome (I don't have much time to make the change myself right now, but didn't want to forget about this issue)

**Comment by simon-bourne** [comment]
I tried wrapping `delete-other-windows` in a let-bind with `ignore-window-parameters t`, but it didn't work for me. I'm very new to elisp, so I'm not sure what the intention was. What did work was:

```elisp
(defun spacemacs/toggle-maximize-buffer ()
  "Maximize buffer"
  (interactive)
  (if (let ((window-count (length (window-list))))
        (and
         (or ( = 1 window-count)
             (and
              ( = 2 window-count)
              (neo-global--window-exists-p)))
         (assoc ?_ register-alist)))
      (jump-to-register ?_)
    (progn
      (window-configuration-to-register ?_)
      (delete-other-windows))))
```

I need to do some more testing, but if this looks along the right lines I'll send a pull request.
