### ISSUE TITLE
[BUG] spacemacs default font couldn't be seen by a certain .otf font

### ISSUE THREAD

**Issue by babygau** [syl20bnr/spacemacs#8115]
#### Description :octocat:

`spacemacs` default font couldn't be seen by a certain `.otf font`, specifically `operator mono`

i also test with other `.otf font` such as `fira code`, `fantasque sans mono`, `hack` and they all worked for me.

in an attempt to use my favourite font, it took me a great while to find out a way to get it work

+ use `M-x set-frame-font`
+ `operator mono` is listed as `-outline-Operator Mono Medium-light-normal-normal-mono-22-*-*-*-c-*-iso10646-1`
+ copy this line and put it to `dotspacemacs-default-font` and it worked!

#### Reproduction guide :beetle:

- start emacs
- change default font in `.spacemacs` as following:

```commonelisp 
dotspacemacs-default-font '("Operator Mono Medium"
                            :size 22
                            :powerline-scale 1.0)
```

*Observed behaviour:* :eyes: :broken_heart:

- `operator mono` font is not set
- have this warning in `spacemacs` message buffer

```bash 
(Spacemacs) Warning: Cannot find any of the specified fonts (Operator Mono Medium)! Font settings may not be correct.
```

*Expected behaviour:* :heart: :smile:

- could use `operator mono` font as default

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.90.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. a1fcb13)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm auto-completion git markdown org
      (shell :variables shell-default-height 25 shell-default-position 'bottom)
      syntax-checking theming emacs-lisp javascript typescript react)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by immigrantsheep** [comment]
Seem to be working great for the normal font but no way to get it to load the italic font on start up. Works only after using `M-x set-frame-font`
