### ISSUE TITLE
error in process sentinel ? Gtags

### ISSUE THREAD

**Issue by phenix-factory** [syl20bnr/spacemacs#8116]
#### Description :octocat:
When using SPC p g, I get an error with process sentinel.

#### Reproduction guide :beetle:
- Start Emacs
- Index some php project with git and global
- Use SPC p g to jump to a function definition

*Observed behaviour:* :eyes: :broken_heart:
Gtags jump works, but i get some error (and it s slow, but I don't if it's related).

I get this in the message buffer :

```
Global found 1 definition
compilation ok.
error in process sentinel: and: Wrong type argument: stringp, nil
error in process sentinel: Wrong type argument: stringp, nil
```

*Expected behaviour:* :heart: :smile:
No error :) (and working faster ?)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 emacs-lisp git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking shell-scripts php html javascript lua gtags imenu-list yaml finance colors dash twitter
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp/mu4e/"))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by bmag** [comment]
A backtrace might be relevant here (`SPC t D` to toggle debug-on-eror)

**Comment by phenix-factory** [comment]
Hello,

I'm sorry for the delay, here's the backtrace i get :+1: 

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("compilation" nil)
  (and (string-match "compilation" (buffer-name buffer)) (string-match "finished" string) (not (save-current-buffer (set-buffer buffer) (goto-char (point-min)) (search-forward "warning" nil t))))
  (if (and (string-match "compilation" (buffer-name buffer)) (string-match "finished" string) (not (save-current-buffer (set-buffer buffer) (goto-char (point-min)) (search-forward "warning" nil t)))) (run-with-timer 1 nil (function (lambda (buf) (bury-buffer buf) (delete-windows-on "*compilation*"))) buffer))
  bury-compile-buffer-if-successful(#<killed buffer> "finished\n")
  run-hook-with-args(bury-compile-buffer-if-successful #<killed buffer> "finished\n")
  compilation-handle-exit(exit 0 "finished\n")
  compilation-sentinel(#<process global> "finished\n")
```
If you need it, you can find my spacemaces config here : https://github.com/phenix-factory/config-spacemacs.

**Comment by phenix-factory** [comment]
This is all my fault, some old code closing the compilation buffer

I fixed my .spacemacs https://github.com/phenix-factory/config-spacemacs/commit/8839662e68a95e80e4a94f3c58a5e01b497e52a5

Sorry
