### ISSUE TITLE
Scala auto indent places asterisk on the wrong column for multi-line comments

### ISSUE THREAD

**Issue by macalinao** [syl20bnr/spacemacs#8120]
#### Description :octocat:
Scala auto indent places asterisk on the wrong column for multi-line comments

Multi-line comments should have the asterisks aligned with the first rather than
the second asterisk, e.g.

```scala
/**
 * This is a comment.
 */
```

#### Reproduction guide :beetle:
- Start Emacs
- Create a Scala file with a method
- Write code as described above

*Observed behaviour:* :eyes: :broken_heart:

Code looks like this

```scala
/**<press enter here>
  * myMethod does asdf<cursor is here>
def myMethod = ???
```

*Expected behaviour:* :heart: :smile:

Asterisk should be here

```scala
/**<press enter here>
 * myMethod does asdf<cursor is here>
def myMethod = ???
```

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. a1516a6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(graphviz rust java elm haskell github chrome semantic python auto-completion ruby-on-rails ruby emacs-lisp themes-megapack php git markdown html org
          (go :variables go-tab-width 4)
          games clojure react docker
          (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'ansi-term)
          yaml javascript xkcd
          (scala :variables scala-auto-insert-asterisk-in-comments t))
```

#### Backtrace :paw_prints:
```

```

**Comment by bmag** [comment]
According to scala-mode's [documentation](http://ensime.org/editors/emacs/scala-mode/#multi-line-comments), this is the expected behavior. To change it, set the variable `scala-indent:use-javadoc-style` to `t`. This is also mentioned in Scala layer's README.
