### ISSUE TITLE
Discussion: All installation instructions in a single place?

### ISSUE THREAD

**Issue by nikolaiam** [syl20bnr/spacemacs#8125]
I am chiefly to blame for this, but it seems that we have installation instructions in two locations now: `BEGINNERS_TUTORIAL.org` and the `README.md`. It would seem to be preferable to have all installation-related information in one location. The `README.md` would be a good choice except it won't probably (?) be exported to spacemacs.org and can't be accessed with `SPC h SPC`. I would argue for using something in `/doc`. So where should installation instructions go:
- `DOCUMENTATION.org` (pro: a natural location to look first)
- `BEGINNERS_TUTORIAL.org` (pro: has to include a section on installation anyway and already has one)
- Somewhere else
- Leave them where they are

**Comment by nikolaiam** [comment]
Went ahead and did a PR moving the instructions to the beginners tutorial: #8217.

**Comment by syl20bnr** [comment]
See my comment on the PR: https://github.com/syl20bnr/spacemacs/pull/8217#issuecomment-294654854
