### ISSUE TITLE
[pdf-tools & layout] Restore last location in a PDF buffer

### ISSUE THREAD

**Issue by korayal** [syl20bnr/spacemacs#8128]
I have a layout for a programming book which allow me to recreate my workspace pretty fast. So In that layout, I have the book's PDF opened in one of the windows.

But the problem is, while in a text buffer the cursor is at the correct position whenever I saved the layout, the PDF buffer always loses it's saved location. Which as you can imagine requires some extra steps that it became boring after a bunch of repeats.

**Comment by braham-snyder** [comment]
I'm using a fixed-up version of a workaround found in the relevant `pdf-tools` issue (https://github.com/politza/pdf-tools/issues/18):

```
    ;; workaround for pdf-tools not reopening to last-viewed page of the pdf:
    ;; https://github.com/politza/pdf-tools/issues/18#issuecomment-269515117
    ;; TODO: save bookmarks in separate file

    (defun brds/pdf-set-last-viewed-bookmark ()
      (interactive)
      (when (eq major-mode 'pdf-view-mode)
        (bookmark-set (brds/pdf-gen-bookmark-name))))

    (defun brds/pdf-jump-last-viewed-bookmark ()
      (when
          (brds/pdf-tools--buffer-has-bookmark-from-previous-session)
        (bookmark-jump (brds/pdf-gen-bookmark-name))))

    (defun brds/pdf-tools--buffer-has-bookmark-from-previous-session ()
      (assoc
       (brds/pdf-gen-bookmark-name) bookmark-alist))

    (defun brds/pdf-gen-bookmark-name ()
      (concat "PDF-LAST-VIEWED: " (buffer-file-name)))

    (add-hook 'kill-buffer-hook 'brds/pdf-set-last-viewed-bookmark)
    (add-hook 'pdf-view-mode-hook 'brds/pdf-jump-last-viewed-bookmark)
```

**Comment by deb0ch** [comment]
@braham-snyder It would be neat to have it in Spacemacs (even neater to have it upstream in pdf-tools, but maybe we can add it here in the meantime).

Maybe you could open a PR with this code integrated so that we can review and test it ? :smile_cat:

**Comment by korayal** [comment]
@braham-snyder this snippet works nicely, but only if we kill the buffer before exiting emacs. after `SPC q R` I'm not seeing the page as I left before. Maybe there is some other hook to do this.

**Comment by deb0ch** [comment]
Maybe `kill-emacs-hook` ?

**Comment by korayal** [comment]
I was hoping for a more general approach, so there is also a `restart-emacs-hook`, I wonder how many cases are there. Also adding this hook to `kill-emacs` or `restart-emacs` or even `kill-buffer` seems like an overkill since this is only about `pdf-mode` buffers.

**Comment by braham-snyder** [comment]
perhaps we should do whatever it is `save-place-mode` does, since it's nearly the same idea
