### ISSUE TITLE
Changing the value of power of `powerline-scale` doesn't resize but breaks the mode-line.

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#8131]
#### Description :octocat:
Changing the value of power of `powerline-scale` doesn't resize but breaks the mode-line.

#### Reproduction guide :beetle:
- Start Emacs

1. Here is my original setting in the file `~/..spacemacs`
   dotspacemacs-default-font '("DejaVu Sans Mono"
                               :size 20
                               :weight normal
                               :width normal
                               :powerline-scale 1.2)

and here is how the mode line looks like:

![spaceline-1](https://cloud.githubusercontent.com/assets/20593743/21748049/133e127e-d5b5-11e6-8693-c2385d8efd9d.png)

2. When I change the value of `powerline-scale` to 0.9

   dotspacemacs-default-font '("DejaVu Sans Mono"
                               :size 20
                               :weight normal
                               :width normal
                               :powerline-scale 0.9)

*Observed behaviour:* :eyes: :broken_heart:

The mode-line size isn't decreased, and its visualization is also broken.
Notice edges of the wave in the mode-line

![spaceline-2](https://cloud.githubusercontent.com/assets/20593743/21748062/682ca44e-d5b5-11e6-9fd9-60586a214483.png)

*Expected behaviour:* :heart: :smile:

The mode-line should be resized and its visualization should not be broken.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6ab)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control spacemacs-layouts semantic pdf-tools latex ocaml haskell python tddsg)
```

#### Backtrace :paw_prints:
```
```

**Comment by qdzo** [comment]
Yep. The same issue on my linux work-pc. 
On macOS with the same config it  bevahes nice.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.2
- Spacemacs: 0.200.8
- Spacemacs branch: develop (rev. f79a169)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml theming themes-megapack ruby csv clojure emacs-lisp markdown org syntax-checking react colors docker shell-scripts dash
      (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t company-show-numbers t)
      (version-control :variables version-control-global-margin t version-control-diff-tool 'diff-hl)
      git
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      (ibuffer :variables ibuffer-group-buffers-by 'modes))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by neeasade** [comment]
hi there- my workaround for this is to call set-default-font after re-initializing `  (spacemacs/set-default-font dotspacemacs-default-font)`

**Comment by tddsg** [comment]
Can you explain explicitly where do you put this line in the `.spacemacs` or your config file?

**Comment by neeasade** [comment]
in my dotspacemacs/user-init

**Comment by tddsg** [comment]
@neeasade: I just do as you said but the problem still remains the same

**Comment by t478225** [comment]
I have same issue.
But zoom don't change powerline size and works fine.

**Comment by xiangsheng** [comment]
It seems that this problem only appears on emacs-mac-port. Using the same configuration, the vanilla emacs on macOS works well.

**Comment by alexryndin** [comment]
same issue on Ubuntu 18.04 with SourceCodePro

**Comment by mbrgm** [comment]
Setting `dotspacemacs-mode-line-unicode-symbols nil` "fixed" this for me.

**Comment by sluedecke** [comment]
2020, still an issue on ArchLinux, but easily solved as mentioned here
https://github.com/syl20bnr/spacemacs/issues/1012#issuecomment-170201103:

install ttf-unifont from AUR

**Comment by laynor** [comment]
> 2020, still an issue on ArchLinux, but easily solved as mentioned here
> [#1012 (comment)](https://github.com/syl20bnr/spacemacs/issues/1012#issuecomment-170201103):
> 
> install ttf-unifont from AUR

I tried but didn't work for me :(
