### ISSUE TITLE
Contribute link on homepage broken

### ISSUE THREAD

**Issue by k0105** [syl20bnr/spacemacs#8132]
A little offtopic, but when I open spacemacs.org and click on "contribute" (linking to http://spacemacs.org/doc/CONTRIBUTE.html) I get a 404 error.

Best wishes,
Joe

PS:
Spacemacs is ultracool and has replaced large parts of my Emacs configuration. Very nice work.

**Comment by nikolaiam** [comment]
Reported at syl20bnr/spacemacs.org#6

**Comment by k0105** [comment]
Thank you.
