### ISSUE TITLE
how to make configuration-layer/package-usedp 'helm return true?

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#8134]
#### Description :octocat:
I want to use package ```helm-gtags``` and ```helm-cscope``` without ```helm layer``` (I use ivy).

I add ```package helm``` into  ```dotspacemacs-additional-packages```, but package ```helm-gtags``` and ```helm-cscope``` still cann't be installed.

#### Reproduction guide :beetle:
- backup .emacs.d and .spacemacs.d
- git clone https://github.com/syl20bnr/spacemacs.git ~/.emacs.d -b develop
- add ```package helm``` into  ```dotspacemacs-additional-packages```
- Start Emacs
- cd .emacs.d/elpa 

*Observed behaviour:* :eyes: :broken_heart:
helm-gtags and helm-cscope not exist.

*Expected behaviour:* :heart: :smile:
helm-gtags and helm-cscope can be installed.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 3bbeae)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers: ```ivy emacs-lisp```

**Comment by syl20bnr** [comment]
Seems like a bug to me, need to investigate.

**Comment by chasinglogic** [comment]
I've submitted a PR with a fix #9617

**Comment by hgijeon** [comment]
Is this resolved?
