### ISSUE TITLE
evil-surround inserts literal escape character

### ISSUE THREAD

**Issue by rpglover64** [syl20bnr/spacemacs#814]
1. Be in visual mode
2. Press <kbd>s</kbd>
3. Press <kbd>Esc</kbd>

Expected: Return to visual mode without any surrounding characters
Got: `^[` surrounding the visual region

**Comment by syl20bnr** [comment]
I think this issue should be posted upstream: https://github.com/timcharper/evil-surround
We should be able to fix it locally while it is fixed upstream.
