### ISSUE TITLE
Twittering-mode freeze

### ISSUE THREAD

**Issue by DorianCBrwn** [syl20bnr/spacemacs#8143]
#### Description :octocat:
Twitter layer freezes spacemacs
<<DESCRIPTION OF THE PROBLEM>>
Whenever I start the twitter layer spacemacs completely freezes and CPU usage ramps up between 80-100%. The only way to exit spacemacs is to use the kill command.  

#### Reproduction guide :beetle:
-For Twitter
- Start Emacs
- SPC a t (twit)
_ Open OAuth authorization page with an external browser, click Allow, and enter the PIN code in the prompt of Emacs.
- Authorization goes through and it starts downloading from :home, Freeze occurs here

- <<REPRODUCTION STEPS>>

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>
UI completely freezes. C-g does not work, escape does not work. Screen goes black.

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>
Twitter timeline should show up

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion better-defaults emacs-lisp git markdown themes-megapack clojure osx twitter slack html javascript org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking syntax-checking)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by deb0ch** [comment]
Is the mess of this issue also a manifestation of your bug ? :rofl: :joy_cat:

**Comment by DorianCBrwn** [comment]
Oh trust me I was as confused as you were. I tried just using the emacs submit at first but that was what you saw. So i just copy and pasted instead.

**Comment by deb0ch** [comment]
Hmmmm I don't know how we could test around for this issue submit bug without creating a ton of garbage issues :confused: 

But that's off-topic.

**Comment by DorianCBrwn** [comment]
I think it is an issue with my mac. I tested twittering-mode on my Linux computer and it is just fine. Any tips on where I should start to diagnose the issues on my mac? I tried disabling all other layers except ivy and twittering mode and it still had the same issue.
