### ISSUE TITLE
":set cursorline" not working as in vim which is better

### ISSUE THREAD

**Issue by tarvos21** [syl20bnr/spacemacs#8145]
Hi, recently I have to compare several files, and I need to know which line I was when I change to another file. In vim, I can ":set cursorline" to make the line obviously seen even if I left the file.

Like this (the white fine line) :

![cursorline](https://cloud.githubusercontent.com/assets/18745870/21804074/0f5e22de-d768-11e6-821b-4072e43c2fa6.png)

I know which line I have been in every file easily.

In spacemacs, the `SPC t h h`, or `:setlocal cursorline` can highlight the current line, but when I left the file( on right pane), I can hardly see which line I am in just now. 

This is my problem, not big deal, just for function consideration. Thanks for reading.

**Comment by bmag** [comment]
The desired behavior can be achieved by setting `global-hl-line-sticky-flag` to `t` in `user-init` :wink:

**Comment by tarvos21** [comment]
Hi, @bmag, great thanks for your response! I have tried setting `global-hl-line-sticky-flag` in my `user-init-file`, I discover that this will highlight the same line on all panes, and move along. So if I want the highlighted line to be the cursor's last postition, how can I do? I mean, the cursorline in different line in all panes, let the cusrline (or highlighted line) be the last line I left that file.

**Comment by bmag** [comment]
> I discover that this will highlight the same line on all panes, and move along.

You mean all panes that show the same buffer? If I have two panes with two different buffers, only the highlight in the current window moves with the cursor. If I have two panes with the same buffer, then the highlight moves in both windows.

**Comment by tarvos21** [comment]
@bmag, yes, you are right, but I do not want to the highlight move together in the other buffer, so I can know which I was in just now. As show in the picture, in three different buffer, I can always know where I have been when I left the buffer. The cursorlines don't move in other buffers that I am not editing.

**Comment by bmag** [comment]
I don't know off hand how to have different lines of the same buffer highlighted in different windows, and I couldn't find a suitable `hl-line-*` variable.
