### ISSUE TITLE
[QUESTION] where to put miscellaneous config in private layer?

### ISSUE THREAD

**Issue by babygau** [syl20bnr/spacemacs#8148]
guys, i have prob, i'm trying to do away my config from .spacemacs to my personal layer, based on the spacemacs docs, i should not use `require` in `<layer>/init-package`, i have each file dedicated to a corresponding package, e.g `projectile-settings.el`. pls note that i don't *own* `projectile` package, so i don't put it under `<layer>/init-projectile`  just want to tweak it according to my preference.

my question is, could i load that file in `packages.el` at top-level inside layer folder as such

```emacslisp
(defconst <layer-packages ...)

(defun <layer>/init-packages...)

;; code here
(require 'projectile-settings)
```
thank you.

**Comment by deb0ch** [comment]
The recommended way of doing this is to lace this code in a function `layer-name/post-init-package-name`. 

See `~/.emacs.d/doc/LAYERS.org` (`SPC h SPC layers RET`) or search for `post-init-` in Spacemacs code base.

**Comment by jvillasante** [comment]
Here's what I have on my `dotspacemacs/user-config()`:

```
  (setq custom-file "~/.spacemacs.custom")
  (load-file custom-file)
```

In `.spacemacs.custom` I make my configurations and use the layers system only for new packages that don't come with spacemacs. Don't know if that the recommended way to do it!

**Comment by babygau** [comment]
@deb0ch according to my understanding, use `<layer/post-init-packages>` only when i want to customize a specific package, as i mentioned earlier, i don't own the package, so i would avoid put my config in that function. 

@jvillasante, your solution is really close to what i want, however i wanna move that `(load-file custom-file)` to  `packages.el` in my private layer, wondering if there is any side-effect for doing that

**Comment by deb0ch** [comment]
@babygau `<layer/post-init-package>` and `<layer/pre-init-package>` are for layers that *don't* own the package. They won't be called unless `<layer/init-package>` is called, and it is the role of `<layer/init-package>` to load the package (using `use-package` or `require`). All you can do in the `pre` and `post` you can do in the `init`.

So it is the layer that owns `<layer/init-package>` that owns the package, the other ones are for configuration from other layers.

**Comment by babygau** [comment]
@deb0ch, tks u for ur clarification!
