### ISSUE TITLE
Message about "Undefined color" when using any theme other than "default"

### ISSUE THREAD

**Issue by siddharthist** [syl20bnr/spacemacs#8150]
#### Description :octocat:
When I use any theme other than `default` in `dotspacemacs-themes`, spacemacs fails to start with the message
```
Warning (initialization): An error occurred while loading '[...]/.emacs.d/init.el':

error: Undefined color, #
```

#### Reproduction guide :beetle:
- Set a colorscheme other than `default`
- Start spacemacs

*Observed behaviour:* :eyes: :broken_heart:
I see the error above and the GNU Emacs logo, and Spacemacs doesn't start

*Expected behaviour:* :heart: :smile:
Spacemacs starts

(%LAST_KEYS%)
%SYSTEM_INFO%

#### Backtrace :paw_prints:
I'm not sure how to fill this part out, can someone give me some pointers?

**Comment by siddharthist** [comment]
This happened because I had bugs in my `~/.Xresources` file. I had things like `color0` defined to be `#`.

**Comment by emadbaqeri** [comment]
I fixed the bug buy changing ```*.background: [80] #222222``` to ```background: #222222```
