### ISSUE TITLE
Doubt about the loading process of spacemacs.

### ISSUE THREAD

**Issue by tianyu-bai** [syl20bnr/spacemacs#8151]
Hi，

I have som questiones about the [Spacemacs Configuration Layers](http://spacemacs.org/doc/LAYERS.html#case-study-auto-completion3) document:

1. A questione about loading process of spacemacs.

In the [Spacemacs Configuration Layers](http://spacemacs.org/doc/LAYERS.html#case-study-auto-completion3), section 5 said: "Spacemacs goes through all the enabled layers and evaluates their files. The changes introduced by config.el are thus applied, then funcs.el and packages.el are loaded, but nothing happens from packages.el, since these files only define functions and variables."

I think it's talking some thing that config.el has high priority than funcs.el and packages.el, it means that the layer's loading process is : config.el > funcs.el > packages.el?

But in section4 of the upper document , the priority of the layers' files is not like this. And I have a try to observe the loading and evaluate process in my layer, the result as follows:

Loading /Users/Baitianyu/.spacemacs.d/baitianyu/packages.el (source)...
Evaluate baitianyu/packages.el
Loading /Users/Baitianyu/.spacemacs.d/baitianyu/packages.el (source)...done

Loading /Users/Baitianyu/.spacemacs.d/baitianyu/layers.el (source)...
Evaluate baitianyu/layers.el
Loading /Users/Baitianyu/.spacemacs.d/baitianyu/layers.el (source)...done

Loading /Users/Baitianyu/.spacemacs.d/baitianyu/funcs.el (source)...
Evaluate baitianyu/funcs.el
Loading /Users/Baitianyu/.spacemacs.d/baitianyu/funcs.el (source)...done

Loading /Users/Baitianyu/.spacemacs.d/baitianyu/config.el (source)...
Evaluate baitianyu/config
Loading /Users/Baitianyu/.spacemacs.d/baitianyu/config.el (source)...done

Loading /Users/Baitianyu/.spacemacs.d/baitianyu/keybindings.el (source)...
Evaluate baitianyu/keybindings.el
Loading /Users/Baitianyu/.spacemacs.d/baitianyu/keybindings.el (source)...done

This shows the process is in accordance with section 4, but inverse with section 5. What I want to know is whether I have some mistakes in understanding or there's some error in the document?

2. Question about Cross-dependencies statements:

Section 7.1 says "For layers that require another layers to be enabled, use the functions configuration-layer/declare-layer and configuration-layer/declare-layers to ensure that layers are enabled even if the user has not enabled them explicitly. Calls to these functions must go in the config.el file." 

The "funtions" in last sentence means which function? 

Function "configuration-layer/declare-layer" and "configuration-layer/declare-layers" should be in the layer.el, right? So does function "configuration-layer/package-usedp" must go in the config.el?

**Comment by bmag** [comment]
Thank you, the documentation was wrong, I fixed it in https://github.com/syl20bnr/spacemacs/commit/0c3afd5a3f293f5a74203d889a68603ad41acdca.

> The "funtions" in last sentence means which function?

`configuration-layer/declare-layer` and `configuration-layer/declare-layers`

> Function "configuration-layer/declare-layer" and "configuration-layer/declare-layers" should be in the layer.el, right?

Correct.

> This shows the process is in accordance with section 4, but inverse with section 5. What I want to know is whether I have some mistakes in understanding or there's some error in the document?

There was an error in the document. `packages.el` comes before `funcs.el`, `funcs.el` comes before `config.el`.

**Comment by tianyu-bai** [comment]
Ok, thanks.
