### ISSUE TITLE
getting proxy error when python mode is installed

### ISSUE THREAD

**Issue by korsnick** [syl20bnr/spacemacs#8153]
When I open a python file and spacemacs prompts me to install python mode support I said yes. Spacemacs then keeps popping up a window (and stealing the cursor) with the error text below.

Before installing python-mode support this didn't seem to happen.

I've been using spacemacs for months at my company (with python mode installed via the spacemacs prompt) and never seen this before.

This error is produced by removing .emacs.d and .spacemacs, cloning a fresh copy of spacemacs, going through the setup and then opening a python file.

All the http_proxy, https_proxy, ftp_proxy environment variables are set.

Machine is running fedora 25 Xfce.

emacs is invoked via 'emacs -mm --insecure'

There have been no changes to the system configuration since spacemacs worked correctly.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(python yaml helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XWIDGETS

----------------------------------
error text

# status: (:error (error http 502))
# point: 179
HTTP/1.1 502 cannotconnect
Content-Type: text/html
Cache-Control: no-cache
Content-Length: 2635
Proxy-Connection: Keep-Alive
X-RBT-Optimized-By: us877-b1mr1-wa2 (RiOS 9.1.3) IK

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>

<head>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta http-equiv="X-UA-Compatible" content="IE=7" />
  <title>[company name removed] Proxy - Notification</title>
  <script src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js" type="text/javascript" ></script>
  <link rel="stylesheet" href="/mwg-internal/de5fs23hu73ds/files/default/stylesheet.css" />
</head>

<body onload="swOnLoad();">
  <table class='bodyTable'>
    <tr>
      <td class='bodyData' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_body.gif'>

<table class='logoTable'>
  <tr>
    <td class='logoData'>
              <img src='http://[company name removed].com/pac/[company name removed]_logo_blue.png'>
    </td>
  </tr>
</table>

<table class='titleTable' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg'>
  <tr>
    <td class='titleData'>
      Cannot Connect
    </td>
  </tr>
</table>

<table class="contentTable">
  <tr>
    <td class="contentData">
      The proxy could not connect to the destination in time.
    </td>
  </tr>
</table>

<table class="infoTable">
  <tr>
    <td class="infoData">
      <b>URL: </b><script type="text/javascript">break_line("http://127.0.0.1:42301");</script><br />
    </td>
  </tr>
</table>

<table class='policyTable'>
  <tr>
    <td class='policyHeading'>
      <hr>
      xxxx Internet Usage Policy
    </td>
  </tr>
  <tr>
    <td class='policyData'>
      Please refer to xxxx <a href="http://collab.xxxxx.com/is/sites/ispolicy/IS%20Policy%20Wiki/End%20User%20Policy%20for%20Securing%20the%20Enterprise%27s%20Electronic%20Information.aspx">End User Policy</a> for information regarding xxxxx acceptable use policies.
    </td>
  </tr>
</table>

<table class='footTable'>
  <tr>
    <td class='helpDeskData' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg'>
      For assistance please contact the xxxxx IT Service Desk for your region.
    </td>
  </tr>
  <tr>
    <td class='footData'>
      generated <span id="time">2017-01-12 19:07:34</span> by McAfee Web Gateway
      <br />
      URL/Emacs
    </td>
  </tr>
</table>

      </td>
    </tr>
  </table>
</body>

</html>

**Comment by rski** [comment]
>URL: <script type="text/javascript">break_line("http://127.0.0.1:42301");</script>

It's trying to connect to localhost via your proxy. Try setting no_proxy to "127.0.0.1,localhost" and use M-x getenv RET no_proxy RET to verify that is the value emacs sees.

**Comment by korsnick** [comment]
my no_proxy already has that and emacs does see it in getenv

no_proxy=localhost, 127.0.0.0/8, ::1, xxxx.com, 10.0.0.0/8

**Comment by rski** [comment]
Hm I think I solved that either by killing all Emacs sessions running or by rebooting.

**Comment by korsnick** [comment]
I did a fresh install of opensuse tumbleweed with the same proxy configuration and spacemacs worked fine- no errors popping up. I went back to fedora 25- KDE spin instead of GNOME this time- and I started getting the error again. This is really annoying since fedora is my preferred distro.

**Comment by korsnick** [comment]
Ok well I tried your first suggestion no_proxy="127.0.0.1,localhost" and it seems to have fixed it.

Maybe the CIDR notation or something in my no_proxy line is making it barf, but it seems to work fine like you listed it.

**Comment by korsnick** [comment]
Well this got me curious about the no_proxy variable and it appears you're not supposed to put CIDR or network ranges in there to begin with, so this one's on me.

Going to close it out.

**Comment by rski** [comment]
Yeah, many program don't support the cidr notation and will ignore the no_proxy config they don't understand.
