### ISSUE TITLE
helm-imenu not support in react-mode after upgrade

### ISSUE THREAD

**Issue by huaoguo** [syl20bnr/spacemacs#8156]
#### Description :octocat:
After I upgrade spacemacs, I found helm-imenu not working in react-mode. I check the code and found the js2-mode and imenu config was removed(https://github.com/syl20bnr/spacemacs/commit/a3e802b2ff3b3d8962f401e10dcc0a5e4e3a631a).

So is there another way to navigate between functions like helm-imenu which I doesn't know or it was a mistake?

Hope to solve this problem.

#### Reproduction guide :beetle:
- Start Emacs
- Enter a react file (.jsx)
- m-x helm-imenu

*Observed behaviour:* :eyes: :broken_heart:
show nothing but a little html tag which is not needed.

*Expected behaviour:* :heart: :smile:
show the functions defined in this file.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby python auto-completion emacs-lisp javascript git markdown react org clojure yaml toml syntax-checking themes-megapack)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
```

**Comment by huaoguo** [comment]
@axyz

**Comment by redguardtoo** [comment]
try rjsx-mode which inherits from js2-mode, all js2-mode functionality is still there.

**Comment by willopez** [comment]
I have found no way to navigate functions(declared inside a react component) in a react file. I use react-mode, and have tried to use helm-imenu :(

**Comment by huaoguo** [comment]
@redguardtoo cool, how to use it with spacemacs?

**Comment by redguardtoo** [comment]
@huaoguo , check https://github.com/syl20bnr/spacemacs/issues/8206
