### ISSUE TITLE
Common Lisp layer not working on Mac OS with `smartparens` error

### ISSUE THREAD

**Issue by CauchyChe** [syl20bnr/spacemacs#8158]
#### Description
Common Lisp layer not working on Mac OS with `smartparens` error. Note: this error may only happen in Mac OS, this common lisp layer runs smoothly on Ubuntu 14.

#### Reproduction guide
- Start Emacs
- Open the `.spacemacs` file with `SPC f e d`
- Search for the “dotspacemacs-configuration-layers” with `/ dotspacemacs-configuration-layers  RET`
- add `common-lisp` to the existing `dotspacemacs-configuration-layers` list

like:

```elisp
dotspacemacs-configuration-layers '(common-lisp)
```
- Install `SBCL` as the Common Lisp implementation by  `brew install sbcl RET` in terminal.
- Start a REPL by `M-x slime RET` in Emacs

*Observed behaviour:*

following error message show up:

```elisp
slime/disable-smartparens: Symbol's function definition is void: smartparens-strict-mode
```

*Expected behaviour:*

a REPL will start, a new windows with a prompt `CL-USER>` show up.

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 2074100)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy better-defaults github ranger colors prodigy search-engine graphviz
     (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips nil)
     (spell-checking :variables spell-checking-enable-by-default nil)
     (vinegar :variables vinegar-reuse-dired-buffer t)
     (spacemacs-layouts :variables layouts-enable-autosave nil layouts-autosave-delay 300)
     (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
     (ibuffer :variables ibuffer-group-buffers-by 'projects)
     (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t :disabled-for org markdown)
     (osx :variables osx-dictionary-dictionary-choice "Simplified Chinese - English")
     restclient
     (gtags :disabled-for clojure emacs-lisp javascript latex python shell-scripts)
     (shell :variables shell-default-shell 'eshell)
     docker deft markdown org shaders yaml react
     (python :variables python-test-runner
             '(nose pytest))
     (ruby :variables ruby-version-manager 'chruby)
     ruby-on-rails lua html javascript
     (typescript :variables typescript-fmt-on-save nil typescript-fmt-tool 'typescript-formatter)
     emacs-lisp
     (clojure :variables clojure-enable-fancify-symbols t)
     racket
     (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
     zilongshanren
     (chinese :packages youdao-dictionary fcitx :variables chinese-enable-fcitx nil chinese-enable-youdao-dict t)
     ess common-lisp slime ac-slime smartparens)
```

#### Backtrace

[Github gist](https://gist.github.com/CauchyChe/87e3d9e4d5f7ade0cc44c8db59bccfa3)

**Comment by bmag** [comment]
Do you have `smartparens` installed properly? According to the gist, the error is that `smartparens-strict-mode` is not defined. I see that you have `smartparens` listed as a layer. Is it a private layer that you created? If so, make sure that `smartparens` package is installed correctly and that its autoloads are properly generated.

**Comment by CauchyChe** [comment]
@bmag Thank for your help. I find that it is my own mistake, I add `smartparens` to `dotspacemacs-excluded-packages`, then I remove `smartparens` from `dotspacemacs=excluded-packages`, and it works now. This is not a problem in Mac OS, it's my init file conflict.
