### ISSUE TITLE
yapf not working with (python-enable-yapf-format-on-save t)

### ISSUE THREAD

**Issue by qiwei9743** [syl20bnr/spacemacs#8159]
<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-c C-c` TO SUBMIT>>
#### Description :octocat:
yapf is not working for python. Running SPC + m + = results nothing.
I have set below in dotspacemacs-configuration-layers.
(python :variables python-enable-yapf-format-on-save t python-fill-column 99 python-sort-imports-on-save t)

#### Reproduction guide :beetle:
- write a shell contains below. and place it to /usr/bin
PYTHONPATH=~/.local/lib/python2.7/site-packages/ python ~/.local/lib/python2.7/site-packages/yapf $@
- Start Emacs
- open a python file.
- make modification  to have multiple space like
self.fp =    fp
- press SPC+m+=    or  save file 

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>
In the last step, additional space is not deleted. Looks like yapf is not working.

*Expected behaviour:* :heart: :smile:
In the last step, additional space is not deleted. Looks like yapf is not working.

(%LAST_KEYS%)
%SYSTEM_INFO%

#### Backtrace :paw_prints:
```
%BACKTRACE%
```

**Comment by qiwei9743** [comment]
hi, 
After run "pip install -U yapf", python file can be formatted with command "SPC+m+=". But saving file doesn't format it. I find yapf mode is not enabled after opening python file. I indeed add "(python :variables python-enable-yapf-format-on-save t python-fill-column 99 python-sort-imports-on-save t)" to dotspacemacs-configuration-layers in file .spacemacs and find the variable python-enable-yapf-format-on-save has been set to true.

**Comment by andres-lowrie** [comment]
I also have this issue

So for me , `yapf-mode` doesn't get enabled by default when opening a file _but_ `SPC m =`  does work

After I enable yapf-mode manually by doing `SPC SPC yapf-mode` the format on save works

my .spacemacs looks like: 

```elisp
   dotspacemacs-configuration-layers
   '(
  ;; a bunch of other stuff
      (python :variables
             python-test-runner 'pytest
             python-enable-yapf-format-on-save t)
    )

```

I'm running latest build from `develop` branch (using the method outlined in the main readme)

I'm a noob at spacemacs and filing issues; please let me know what other information I can provide to help

**Comment by lsytj0413** [comment]
I have the same problem.
If i use the **SPC m =**, the yapf worked on the buffer, but it doesn't work when i save a py file.

**Comment by romise** [comment]
I also met the problem. I solved it by a compromise way, just add 
` (add-hook 'python-mode-hook 'yapf-mode)`
to dotspacemacs/user-config, and the yapf mode will be enabled.
