### ISSUE TITLE
Evil Tutorial does not work.

### ISSUE THREAD

**Issue by edge226** [syl20bnr/spacemacs#8160]
#### Description :octocat:
Evil Tutorial does not work.

#### Reproduction guide :beetle:
- Start Emacs
- Open Quickhelp with `[?]`
- Click `[Evil Tutorial]`

*Observed behaviour:* :eyes: :broken_heart:
wrong type argument: commandp, evil-tutor-start

*Expected behaviour:* :heart: :smile:
To see the Evil Tutorial and be able to learn how to use spacemacs in evil mode

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git markdown spell-checking syntax-checking shell-scripts yaml tmux)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by deb0ch** [comment]
Thanks for reporting !

It seems that you have used the report issue template but didn't include your system info, which could be useful. Would you mind adding them ?

`SPC h I` or `SPC h d s` should show them to you.

**Comment by edge226** [comment]
There you go, Updated with that information.

**Comment by bmag** [comment]
@edge226 I see you're using the `spacemacs-base` distribution. That is the minimal distribution, and it doesn't include `evil-tutor` package by default. If you are a new user, we recommend using the `spacemacs` distribution, which contains many good features.
If you want to keep using `spacemacs-base`, then a work-around is to enable the `evil-tutor` package from the `spacemacs-evil` layer (it's part of the `spacemacs` distribution). You can do so by adding the following to your enabled layers list:
```elisp
(spacemacs-evil :packages evil-tutor)
```

However, it is a genuine bug, we probably need a guard to protect from it. (in `spacemacs-buffer//notes-insert-quickhelp` I suppose)

**Comment by edge226** [comment]
Thanks for the tips. I've added the layer and it now works. The odd thing is that the other two tutorials worked, Just not this one.

In other areas of software I am generally a power user so I think I'll stick with the base and expand on it where I feel needed. I mostly do shell scripting and such so I'm catering the environment to the tasks I'll be doing. ;)

**Comment by bmag** [comment]
> The odd thing is that the other two tutorials worked, Just not this one.

The other tutorials just don't rely on a 3rd-party package.

>  so I'm catering the environment to the tasks I'll be doing. ;)

Sounds fun :)

**Comment by siddharthist** [comment]
Does this issue need anything else? Seems like @edge226 got their question answered and there isn't something to fix right now.
