### ISSUE TITLE
Move smart parens and evil lisp state to own layers

### ISSUE THREAD

**Issue by quicknir** [syl20bnr/spacemacs#8162]
I think that these packages should be moved from core to their own layers. The actual implementation is trivial and I'm happy to do it but it seems like it might be controversial so I thought it would be good to open a discussion about it first.

smartparens has been at the heart of performance issues for myself, as well as for others, including one person I chatted with in the gitter just the other day. So there is certainly negative to simply having this package present by default. And the flipside is that the benefit is very low. Few people use the features that smartparens provides; the noticeable functionality for most people is provided by rainbow parens and electric-pair mode (for auto matching delimiters), as well as vim's `%` and text object and surround. Things that are used by few and whose presence has actual negatives are a good candidate to be moved from core into their own layer. Users of smartparens would have to have one extra line in their config, and otherwise things would be unchanged.

evil-lisp-state depends on smartparens, so it would need to be moved out of the core, into a layer as well, potentially with a layer dependency on smartparens (which now seems to be possible). evil-lisp-state is a bit of an obscure package; the bindings under `SPC k` which are predominantly designed for lisp but are active in every language, sometimes work as you'd expect in non-lisps and sometimes don't. Most people I talk to never use the `SPC k` binding, and when they've tried it find it quite confusing. So I think again, the low breadth of utility makes moving this package out of the core layers a reasonable choice.

Any thoughts?

**Comment by djeis97** [comment]
Well, firstly, I use the `SPC k` bindings quite regularly. On the other hand, I work with lisps an awful lot, so I can see how I'd be a minority here. I agree that something better needs to be done with them though- they are awkward in other languages, and they don't fit in with the newer transient states. At the very least, they should be revisited.

As far as smartparens goes, I'm a quite happy user of global smartparens strict mode, but if other people aren't using most of its features I can see moving it out to its own layer.

**Comment by quicknir** [comment]
@djeis97 Thanks for your feedback and open mindedness. I'm definitely still prioritizing minimizing disruption to people who use these things. The goal would be for it to be no more than a few lines change to your .spacemacs, and have exactly the same outcome. The evil-lisp-state layer will (or at least by default w/ an option) setup the same keybindings. So it would just be a matter of adding two lines to your layer list. The only other change would be that the smartparen dotspacemacs variables would become layer variables. So I think in total it is perhaps delete 2 lines, add 4 new ones.

I think moving config variables from the global dotspacemacs vars to a layer is also a big win as it helps keep the global config a reasonable size, and it also makes it obvious exactly which package/layer functionality is providing the option.

**Comment by deb0ch** [comment]
A layer just for `smartparens` seems a little bit overkill, maybe a dotspacemacs variable could be better ?

No opinion about the lisp transient state that I never use because I don't know how to (and seriously, names like `barf` or `slurp` are really not self-descriptive), except that it should indeed be revisited. 

Yes lots of its commands work in other languages, but some of them shouldn't even be available in other languages than lisps.

**Comment by deb0ch** [comment]
@quicknir I was actually thinking of *reducing* the number of variables in the `.spacemacs`.

There are already 2 variables setting up stuff about smartparens: `dotspacemacs-smartparens-strict-mode` and `dotspacemacs-smart-closing-parenthesis`.

I was thinking of merging all that into one variable, sth like `dotspacemacs-smart-parenthesis` which would be a property list, a little bit like I did in https://github.com/syl20bnr/spacemacs/pull/7672:

``` elisp
  dotspacemacs-smart-parenthesis (:strict nil 
                                  :smart-closing t
                                  :disabled-for-mode blah-mode
                                  :whatever-option 'always)
```
But all that stayed in my head :smile_cat:

**Comment by deb0ch** [comment]
@quicknir I was calling it overkill not for the amount of code that it implies, but more for the fact that a layer is supposed to be a *collection* of packages grouped by functionality. Moreover, there are already too many layers and, same as for the dotspacemacs variables, adding too many will make it difficult to find anything at all in the layers list.

**Comment by fiveNinePlusR** [comment]
I always assumed a layer was a set of one or more packages that provided some functionality and was setup to work with the existing spacemacs ecosystem with shortcuts and sensible defaults already set up. Not necessarily required to be a bunch of packages.

**Comment by deb0ch** [comment]
My bad, I just checked and indeed some layers contain only one package.

I still prefer the dotspacemacs solution though.

**Comment by quicknir** [comment]
@deb0ch Well, if you want to add functionality, you have to add it somewhere. You still have not given any concrete pros/cons as to why this should be a dotspacemacs variable. Clearly your attitude taken generally is not feasible because everything cannot be a dotspacemacs variable; the configuration file will just be enormous and every single change will require users to do a bunch of working resolving diffs against the template.

Your linked example is line numbering, which is a very common thing to want, that every programmer already knows about and has an opinion on. smartparens is a very specialized package that most people new to emacs/spacemacs, or who don't use a lisp, will never have heard of.

I can't think of a single concrete reason why smartparens should have dotspacemacs variables, but say, evil snipe should not. Okay, so evil-snipe gets a dotspacemacs variable. Then evil-cleverparens (these are both layers with one package btw). And so it goes. If you think of 10 packages that 10% of people use, putting things in layers means that each person will have code in their .spacemacs that configures one of those packages, versus code that configures 10 of those packages if they are handled as dotspacemacs variables.

Your suggestion may technically reduce the number of variables, but it doesn't reduce the complexity of the dotspacemacsfile. There's still 3-4 lines of code configuring a package that relatively few people use. The whole point of layers is to be modular and avoid having everything in one global config.

**Comment by deb0ch** [comment]
@quicknir I thought of it and yes, your reasoning makes sense. Let's see what the others think about it.

I just want to point out that `smartparens` is not only useful for lisp(s). I've been using it since long before I even discovered lisp programming and still use it in other languages, so `smartparens` is not *that* specialized a package.

One more thing: if there was such a layer, I think that a name like `smart-parenthesis` would be better than a name like `smartparens` layer, to separate the functionality from the underlying implementation (I'm conscious that this is already not the case for some existing layers). Just suggesting.

**Comment by Somelauw** [comment]
If smartparens becomes a layer, would it make sense to merge it with the cleverparens layer? I believe both are backed by smartparens. Does one of them supersede the other or do they have different use cases?

**Comment by deb0ch** [comment]
Now that I think of it, having them into separate layers could get us rid of the 2 dotspacemacs variables that I was talking about earlier, because we'll have to make them layer local variables.

**Comment by sooheon** [comment]
My 2c on this topic, I'm all for especially moving the lisp state out into a layer. It is far less fleshed out than something like [lispy](github.com/abo-abo/lispy), there's little reason why it should be in core.

**Comment by Fuco1** [comment]
> smartparens has been at the heart of performance issues for myself

@quicknir Would appreciate if you would also open an issue in smartparens repo with some repro cases. We've been working quite a bit on performance but it's not optimal everywhere.

> the noticeable functionality for most people is provided by rainbow parens and electric-pair mode (for auto matching delimiters)

Smartparens basically started its existence as a reaction to `electric-pair-mode` being insufficient.  It can only handle simple pairs and has very little context-awareness.  All the parsing routines in smartparens can be disabled if one does not want them and the insertion code is extremly fast, and much much more flexible than what EPM provides.  I would much rather have people contribute more configuration for other languages (so things work "out of the box").

But yes, the 80/20 rules apply.

> (and seriously, names like barf or slurp are really not self-descriptive),

@deb0ch Those names come as legacy from `paredit` and have became somewhat of a "tradition", most packages providing these features call it that way.  I'm not against adding better aliases if someone comes up with the names.

**Comment by quicknir** [comment]
@Fuco1 Well, I relatively rarely work with lisps (other than my elisp config, but I don't do enough of that to center my editor/binding choices around that). Can you give an example in C++ or python, where electric-pair-mode does something stupid, that smartparens does smarter? My failure to file a performance issue isn't about laziness, it's just that it's so hard to meaningfully track these down. They rarely go anywhere in my experience. Sometimes a package just contributes to a general feeling of latency. Sometimes it is just interacting poorly with another package (evil's C-v I, i.e. visual block insert, interacts poorly with smartparens, for example).

AFAICS if you aren't working with lisps extensively (and even on emacs, most people aren't), smartparens does not provide enough value to be in by default. Note: I am not bad mouthing the package in any way. I just have a relatively high bar for being in by default; should include both non-intrusiveness and a very wide audience. smartparens in my experience doesn't satisfy either of these. I've made similar arguments about quite a few things (e.g. purpose mode).
