### ISSUE TITLE
Git blame micro state changed to a transient state

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#8166]
## Summary
The Git Blame Micro State <kbd>SPC g b</kbd> didn't look quite right (the underscores were shown):
> Press [\_b\_] again to blame further in the history, [\_q\_] to go up or quit.

So i changed it to a transient state:
```
Navigate                        History      Other
[p/P] prev chunk /same commit   [b] back     [t] toggle headings
[n/N] next chunk /same commit   [f] forward  [Y] copy hash
[RET] show commit                            [q] quit
[_SPC_] show diff or scroll up
[DEL] show diff or scroll down
```
the SPC binding is commented out so it will show underscores before and after SPC.

### Patch
I thought i'd try to submit a patch. I used the Magit key binding <kbd>W p</kbd> Format patches > Format patches. Is a patch the easiest way for others to try these changes, or should i have submitted these as a PR directly? It's seems to be working fine, but the <kbd>SPC</kbd> key isn't bound. even if it isn't complete, or would it also have worked if i push them to my spacemacs fork, and others could get them from there?

Github doesn't support `.patch` files, i renamed it to `.txt`, i hope it works anyway.
[0001-change-git-blame-micro-state-to-a-transient-state.txt](https://github.com/syl20bnr/spacemacs/files/705798/0001-change-git-blame-micro-state-to-a-transient-state.txt)

Suggestions for corrections & improvements are welcome.

### Keys:
<kbd>q</kbd> conflicts between magit-blame-mode and spacemacs transient states

Changed key:
- <kbd>q</kbd> only quits like other TS's, it doesn't navigate up in history any more

Added keys:
- <kbd>f</kbd> moves forward in history and stops at the earliest block with a message
- <kbd>Y</kbd> (uppercase) copies hash, like the git timemachine TS

### Questions:
- What should the `magit-diff-show-or-scroll-up` commands key binding be?
- Should the <kbd>f</kbd> key stop at the earliest block or exit blame mode
- One or two lines: "[p/P] prev chunk /same commit"
- Should the normal-state keys, C-j/k, etc. be listed in the TS?
- Is it possible to detect how many blame history blocks there are

### Comments Removed (no details below):
- The comment before the git blame micro state talked about `:on-enter` not working in transient states, this seems to have been fixed, since other TS's (ex: git timemachine) use `:on-enter`.
- The comment before the micro states "q" binding explained that the micro state exits when the magit blame mode is disabled. This is technically still correct but the exit code was moved to a new `:on-exit` section, and a new comment was added that describes what it does.

### Other changes (no details below)
The git blame micro state was defined in the `git/init-magit` functions `:init` section, the git blame TS was moved to the `:config` section, 
because the git timemachine TS is defined in the `git/init-git-timemachine` functions `:config` section, maybe it doesn't matter, but they should probably match.

### Keys:
The <kbd>q</kbd> keys behavior in the two states:
**Micro**: 
Moved up in history, disabled blame mode and closed the micro state.
**Transient**: 
Kills all recursive (older) blame buffers, disables blame mode and closes the TS.

The <kbd>f</kbd> key moves up/forward in history, and stops at earliest blame block with the message: "Block has no earlier history".

The <kbd>Y</kbd> (uppercase) key copies the hash of the current chunks commit, this is the same key that the git timemachine TS uses.
The default copy hash key binding is <kbd>M-w</kbd> and it still works in the transient state.

<kbd>C-g</kbd> seems to do the same thing as the transient states <kbd>q</kbd> key, it doesn't need to be bound (maybe it's a transient state feature, since it didn't work in the micro state).

The micro state didn't seem to have a key binding that instantly closed the blame mode when one was a couple of steps down in the history. One had to move up to the earliest blame block before being able to exit. 

With these changes to the transient state it's now possible to exit from anywhere in the blame history with <kbd>q</kbd> or <kbd>C-g</kbd>.

### What should the `magit-diff-show-or-scroll-up` commands key binding be?
Magit-blame binds <kbd>SPC</kbd> to `magit-diff-show-or-scroll-up`, but it's probably better to keep <kbd>SPC</kbd> with it's default spacemacs behavior, so that one can run some commands while the git blame TS is active, for example: closing the magit revision diff buffer.

The `magit-diff-show-or-scroll-up` and `..-down` commands open a magit-revision diff buffer of the commit under the cursor in another window but the cursor remains in the blame buffer.

When a magit diff window is open:
- Then the `magit-diff-show-or-scroll-up` and `..-down` commands scroll the diff window up or down. 
- When one navigates to the next or previous chunk, then the diff window updates. This causes a slight delay, it's expected since a new diff needs to be loaded.

Maybe there should be a way of closing the diff buffer and/or it's window so that navigating between chunks is instant again. 
The key binding could use a modifier key version of the `magit-diff-show-or-scroll-up` and `..-down` keys 

The current simplest solution is probably to use `ace-kill-this-buffer` <kbd>SPC b D</kbd>.

Another option that didn't work was to close the blame mode and start it again, but the diff buffer starts updating again as soon as one navigates to another blame chunk.

#### Stop at earliest block
If it stops at the earliest block and the message:
> Block has no earlier history

is shown, then it matches the `magit-blame` command that shows this message when one tries to navigate past the oldest block:
> Block has no further history

Another reason would be if one is viewing an older block and one wants to return to the earliest block quickly, then the <kbd>f</kbd> key can be pressed quickly until the message appears.

If it doesn't stop and shows the message, then it's easy to overshoot and exit magit blame mode. Then magit blame mode has to be started again, which requires some loading.

#### Exit blame mode
If there shouldn't be a message and it instead should exit out of blame mode when the earliest blame history is visible, then it would work the same way as the <kbd>q</kbd> key does in the git blame micro state, this is probably what most people that have been using magit blame mode are used to.

### One or two lines: "[p/P] prev chunk /same commit"
Is it easy to understand from the transient states chunk navigation entry:
"[p/P] prev chunk /same commit"

that the <kbd>p</kbd> key navigates to the previous chunk, and the <kbd>P</kbd> (uppercase) key navigates to the previous chunk in the same commit (same with <kbd>n/N</kbd>), or should they be split up into 4 lines?
[p] prev chunk
[P] prev chunk same commit
[n] next chunk
[N] next chunk same commit

other ways of writing the combined line would be to add or remove spaces:
"[p/P] prev chunk/same commit"
"[p/P] prev chunk/ same commit"
"[p/P] prev chunk / same commit"

### Should the normal-state keys, C-j/k, etc. be listed in the TS?
These keys are also bound in <kbd>C-h f</kbd> `magit-blame-mode`:
```
<normal-state> C-j              magit-blame-next-chunk
<normal-state> C-k              magit-blame-previous-chunk
<normal-state> g                Prefix Command
<normal-state> j                evil-next-visual-line
<normal-state> k                evil-previous-visual-line
<normal-state> g J              magit-blame-next-chunk-same-commit
<normal-state> g K              magit-blame-previous-chunk-same-commit
<normal-state> g j              magit-blame-next-chunk
<normal-state> g k              magit-blame-previous-chunk
```
should any of them also be listed or would it become to cluttered?

### Is it possible to detect how many blame history blocks/buffers there are
If it is, then maybe the current and total blame steps could be listed in the transient state ex: 2/4, similar to how search occurrences are listed in the <kbd>SPC s h</kbd>  symbol highlight transient state.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 0c3afd5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey emacs-lisp git helm html org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by nertpinx** [comment]
This looks like it could work better than what is currently in develop (although , the issues you are describing were present when I used master (not that long ago actually, but I can't say what version that was) but not in develop, also the patch does not apply, understandably.  I'd be willing to test an update if anyone thinks it's worth it.

**Comment by duianto** [comment]
I haven't looked at this since I posted the comment.
If you would like to implement it (or something better), feel free to open a PR.

**Comment by nertpinx** [comment]
Well, the patch posted by you does not apply for me and it behaves a bit differently in the develop branch. I was hoping you're keeping your patch applied locally and you might have an updated version. I, unfortunately, do not have the capacity to look into it, sorry :frowning_face:.

**Comment by duianto** [comment]
I opened a PR with a possible implementation of a Git Blame Transient State:
[source-control] Add Git Blame Transient State #13643

**Comment by duianto** [comment]
The PRs #13643 changes have been applied to the `develop` branch
