### ISSUE TITLE
Spacemacs freezes while trying to start a line of comment in rust mode

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#8172]
#### Description :octocat:
Spacemacs freezes while trying to start a line of comment in rust mode.

#### Reproduction guide :beetle:
- Start Emacs
- Open a buffer with `.rs` ending that enables rust mode, e.g. `test.rs`
- Try to start a line of comment by typing two `/` characters

*Observed behaviour:* :eyes: :broken_heart:
Emacs freezes with 100% CPU usage. Using `C-G` might get out of the freeze but it doesn’t succeed all the time.

*Expected behaviour:* :heart: :smile:
The editing continues normally.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.50.2
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 0c3afd5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm speed-reading auto-completion better-defaults spell-checking syntax-checking semantic rcirc git github version-control
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/zsh" shell-enable-smart-eshell t)
      (ranger :variables ranger-show-preview t ranger-show-literal nil ranger-parent-depth 3 ranger-cleanup-eagerly t ranger-show-dotfiles t ranger-max-preview-size 10)
      (typography :variables typography-enable-typographic-editing t)
      wakatime chrome search-engine restclient dash fasd pandoc colors themes-megapack gtags imenu-list vim-powerline evil-snipe emacs-lisp fsharp
      (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "gibiansky")
      elixir org latex markdown clojure python html yaml shell-scripts sql javascript ruby
      (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
      rust)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS LIBSYSTEMD

#### Backtrace :paw_prints:
Since Emacs freezes, I wasn’t able to get any backtrace.

**Comment by x-ji** [comment]
The version of my `rustc` is `rustc 1.16.0-nightly (1a2ed98d3 2017-01-13)`, `cargo` is `cargo 0.17.0-nightly (6291619 2017-01-12)`, racer is `racer 2.0.4`

**Comment by letheed** [comment]
@x-ji do you still have this issue? I can't reproduce on nightly with racer-2.0.9

**Comment by x-ji** [comment]
Seems stale and I haven't used Rust mode in a long time. Will reopen if I encounter it again.
