### ISSUE TITLE
nlinum not displaying first digit (found workaround)

### ISSUE THREAD

**Issue by bryanbecker** [syl20bnr/spacemacs#8173]
Everything works fine without nlinum.

The issue happens with or without relative line numbers.

What I see in margin, is something like the following:

```








1
1
1
1
1
1
1
1
1
2
2
2
(...)
````

[ Update ] 
I discovered that I can see the numbers if I decrease the font to be very small, but then emacs is too difficult to read

**Comment by bryanbecker** [comment]
Found a fix here: https://www.emacswiki.org/emacs/LineNumbers

Add the following to `(defun dotspacemacs/user-config ()`

```
;; Preset `nlinum-format' for minimum width.
(defun my-nlinum-mode-hook ()
  (when nlinum-mode
    (setq-local nlinum-format
                (concat "%" (number-to-string
                             ;; Guesstimate number of buffer lines.
                             (ceiling (log (max 1 (/ (buffer-size) 80)) 10)))
                        "d"))))
(add-hook 'nlinum-mode-hook #'my-nlinum-mode-hook)
```

**Comment by bmag** [comment]
Can't reproduce this behavior. Please add more info according to the [template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)

**Comment by bryanbecker** [comment]
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. d216880)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 helm better-defaults
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 org emoji xkcd asciidoc
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
 csv elixir elm emacs-lisp erlang html javascript lua
 (markdown :variables markdown-live-preview-engine 'vmd)
 python
 (ruby :variables ruby-enable-enh-ruby-mode t)
 shell-scripts sql typescript vimscript yaml nlinum git github version-control
 (colors :variables colors-colorize-identifiers 'variables colors-enable-rainbow-mode t colors-enable-nyan-cat-progress-bar t)
 theming themes-megapack ansible dash fasd finance imenu-list nginx pandoc pdf-tools restclient
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 systemd vagrant evil-cleverparens evil-commentary evil-snipe)
```


Possibly related to large screen size?  


No error is shown, just the digits are pushed too far to the right, essentially hidden under the margin where tildes are usually shown

**Comment by bmag** [comment]
Possibly related to screen size, but not necessarily.  Any chance for a screenshot, and what's the value of the faulty nlinum-format?

**Comment by bryanbecker** [comment]
Not sure what the value of the faulty nlinum-format is, but I can only assume it's the default:

```
(setq nlinum-format "%4d")
```

Here's screenshots of fixed/broken.  It should be noted that issue happens even when I remove theming / doom packages from my config

![nlinum-broken](https://cloud.githubusercontent.com/assets/469798/21968151/a07ffa9a-dbcc-11e6-925c-699f37c4a779.jpg)
![nlinum-fixed](https://cloud.githubusercontent.com/assets/469798/21968152/a0822f40-dbcc-11e6-82ca-d016a4a9c3e4.jpg)

**Comment by bryanbecker** [comment]
By the way, it might be worth considering making the suggested workaround the "official" implementation of nlinum.  It automatically sizes the line number margin to be the correct width (so opening a file with 1000 lines will show a large margin, while opening a file with 20 lines will show a smaller one)

**Comment by bmag** [comment]
@bryanbecker you can check the real value of `nlinum-format` by typing `SPC h d v nlinum-format RET`

**Comment by bryanbecker** [comment]
```
It's value is "%4d"
Original value was "%d"
```

**Comment by bmag** [comment]
That's the same value I have, and it works fine for me. I suspect the cause is something else.

If in a fixed buffer (where the value is `"%3d"`), you change the value back to `"%4d"` with <kbd>M-: (setq-local nlinum-format "%4d")</kbd>, then the line numbers are messed up again in that buffer?

**Comment by deb0ch** [comment]
@bryanbecker Your code snippet is an interesting idea. I guess more thought could be given to the "guesstimate" of the number of lines in the buffer, like having something more exact than assuming that the lines are all 80 cols if it doesn't impair too much on performance in large files.

**On another note:**

Just wanted to point out here that I also have similar (but slightly different) problems with `nlinum`: sometimes I will indeed face the problem described here, but also sometimes the line numbers go nuts, giving totally wrong numbers.

Like just after line 42 (or any number), a new numbering will start from for instance 234 for a few tens of lines, then on the next line the numbering will start from some negative (negative :scream_cat:) values for some lines and so on, randomly.

A quick example from a few seconds of using `nlinum`:
![image](https://cloud.githubusercontent.com/assets/6248219/22102960/9b9e76b8-de39-11e6-8e3c-c8682994780a.png)

Sometimes I also get negative values.

**Comment by bryanbecker** [comment]
Well, the issue seems to have... just fixed itself?

Suddenly I started emacs and line numbers are working as expected

@deb0ch  assuming all lines are 80 works out pretty well for a fast calculation.  Are other quick variables available similar to `buffer-size` we could base an estimate off of?

**Comment by deb0ch** [comment]
I mean, why not just get the exact number of lines in the file ?

Since it's done only once when opening the file why should we care about a few milliseconds ? If it appears to be an issue when opening millions+ lines files, we can also put a threshold after which we stop counting.

**Comment by bryanbecker** [comment]
I agree.  I don't think there is a performance expectation for files numbered in thousands (or more) lines
