### ISSUE TITLE
How to disable auto-completion in org-mode?

### ISSUE THREAD

**Issue by asdyjd** [syl20bnr/spacemacs#8175]
#### Description :octocat:
How to disable auto-completion in org-mode?
I put this into .emacs but it doesn't work:
```
(add-hook 'org-mode-hook (lambda ()
                           (spacemacs/toggle-auto-completion-off)
                           ))
```
#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults
                 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
                 chinese cscope emacs-lisp helm html org
                 (python :variables python-enable-yapf-format-on-save t)
                 spacemacs-layouts syntax-checking ycmd)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
On develop branch, you can replace `auto-completion` in your layers list with `(auto-completion :disabled-for org spacemacs-org)`. I'm not sure if it works on master or not, but you can try.

If it doesn't work on master, try calling `add-hook` with an `append` argument:
```elisp
(add-hook 'org-mode-hook (lambda () ...) 'append)
```
(the value for the last argument doesn't have to be `append`, any non-nil value will work)

**Comment by fosskers** [comment]
As of recently, these solutions no longer work. Even with:

```
(auto-completion :disabled-for org spacemacs-org)
...
(setq helm-mode-no-completion-in-region-in-modes
        '(org-mode))
```
in my `.spacemacs` and `spacemacs/toggle-auto-completion-off` triggered, attempts to expand [Org Mode Templates](https://nicholasvanhorn.com/posts/org-structure-completion.html) like `<s` fail. `TAB` is captured by a completion mechanism, and it suggests words to me instead of expanding to:
```
#+BEGIN_SRC

#+END_SRC
```
like it used to, until very recently.

**Comment by fosskers** [comment]
Possibly related: https://github.com/emacs-helm/helm/issues/673

**Comment by math0ne** [comment]
This is what worked for me:

`(spacemacs|disable-company org-mode)`
