### ISSUE TITLE
Question: Kernel includes

### ISSUE THREAD

**Issue by jkvargas** [syl20bnr/spacemacs#8182]
Hello,

How can I for a specific project folder add some specific include directories?
For example, I want to have autocomplete headers and code for the following include dir:
/usr/lib/modules/4.8.13-1-ARCH/build/include

inside of it I do have a linux/ folder which I do also have in /usr/include, how would that affect the program?

Remembering that is C code =)

Thank you.

**Comment by deb0ch** [comment]
Several ways to go about it, depending on the auto-completion tools you're using.

If using the default `auto-completion` layer alone (of course with the `c-c++` layer), this one only takes `.clang_complete` files that you can put at the root of your project. It is a file for specifying compilation flags, there should be one flag per line, so for your problem it would be a `-I/path/to/folder/include` per line. See [here](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bcompletion/auto-completion) for more details.

If you are using `ycmd` (which IMHO is much better), it also accepts compilation databases (`.compile_commands.json`), which is a json file conatining one entry per compilation unit with the command line that was used to compile it in your project. [Bear](https://github.com/rizsotto/Bear) is a great tool for generating it. I also heard of [scan-build](https://github.com/rizsotto/scan-build) which seems nice, don't hesitate to give feedback here if you happen to try it.

If using compilation databases with `ycmd`, there is also a way of passing extra flags in a `.ycm_extra_flags` file, one flag per line at the root of your project. See [here](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Btools/ycmd) or [here](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Btools/ycmd/global_conf.py) for more details.

**Comment by jkvargas** [comment]
hey deb0ch,
first let me thank you for taking your time to help me.
Now, If i may ask.

On the config side of ycmd did you have something else than this:

 (ycmd :variables
          ycmd-server-command '("/usr/bin/ycmd --options /home/jvargas/.config/ycmd/default_settings.json")
          ycmd-force-semantic-completion t
          ycmd-extra-conf-whitelist '("~/dev/*"))
I am getting an "server exited with error code 127"

but running it on command line seems that its working.

**Comment by deb0ch** [comment]
For the `ycmd-server-command`, you need to specify the program name and the arguments in separated strings, like:
``` elisp
  ;; ycm setup
  (setq ycmd-server-command `("python"
                              ,(expand-file-name "~/.emacs.d/private/ycmd/ycmd"))
        ycmd-extra-conf-whitelist '("~/Programming/*"
                                    "~/ParrotSrc/*")
        ycmd-force-semantic-completion nil)
```

Just like if you wrote `"ls -l"` instead of `ls -l` on the command line, it will fail to find the `"ls -l"` program.

Note that completion works just as well without forcing semantic completion but more fluid. I really don't know what difference forcing semanting completion brings that could justify the sluggishness.

**Comment by deb0ch** [comment]
See https://github.com/abingham/emacs-ycmd for more info

**Comment by jkvargas** [comment]
thanks deb0ch, now it is working perfectly.
=)

**Comment by d12frosted** [comment]
Closing this issue as the question was answered. @jkvargas let us know if you need further help 😸 

And thanks @deb0ch for the help ❤️
