### ISSUE TITLE
Feature Request: elm-test integration in elm layer

### ISSUE THREAD

**Issue by JoshTGreenwood** [syl20bnr/spacemacs#8183]
[Elm Mode](https://github.com/jcollard/elm-mode) integrates with [elm test](https://github.com/rtfeldman/node-test-runner).  It would be great if the elm layer could also add this support.

It's currently possible to run elm test with `C-c t` but I'd like a major mode binding as well as the ability to run individual tests at a given point.

I'll take a stab at this this week.

**Comment by juanedi** [comment]
Hi @JoshTGreenwood !

I made a [package](https://github.com/juanedi/elm-test-el) and [spacemacs layer](https://github.com/juanedi/elm-test-spacemacs-layer) with improved support for running `elm-test`.

There are still things to fix, but it's working pretty well for me so I decided to publish it and get some feedback. It currently supports keybindings for:

 - Running the current buffer's test suite
 - Running the current buffer's test suite in watch mode
 - Re running the last suite (with the same arguments)
 - Toggling back and forth between implementation and test module

Of course, this is work in progress and things will change without caring a lot for backwards compatibility, but feel free to check it out!

I would eventually like to get it into the stock elm layer, but before trying that I want to polish this a bit and getting some feedback would be great.

Hope you find it useful!
