### ISSUE TITLE
[haskell] Odd hi2-mode indentation after restart

### ISSUE THREAD

**Issue by imalsogreg** [syl20bnr/spacemacs#819]
After a fresh install of spacemacs, running the haskell layer, things work immediately. But after quitting and restarting, while typing a block of text, hitting return causes the *previous* line to pick up extra indentation (e.g: http://web.mit.edu/greghale/Public/out.gif   Expected behavior would be every line starting at column 1).

Work-around by turning off hi2-mode. `SPC : hi2-mode`

**Comment by chrisbarrett** [comment]
Is `aggressive-indent-mode` on in your Haskell buffers? Type `C-h m` for `describe-mode`, then look for `Aggressive Indent` in the list of active minor modes.

**Comment by imalsogreg** [comment]
Nope no sign of `aggressive-indent-mode`. But searching for it, I found `electric-indent-mode` is turned on, and deactivating that also returns me to working indentation (no need to deactivate `hi2-mod` in this case). So perhaps electric and hi2 are interacting badly?

Thanks. I'm also curious, what would cause my setup not to bring in aggressive-indent-mode, if that's standard and I'm on a fresh (almost fresh - added the `haskell` layer only) install.

**Comment by chrisbarrett** [comment]
Aggressive-indent should be disabled by default for languages like Haskell, which use significant whitespace. If it's turned on you would get behaviour much like what you were seeing. :)

Electric-indent has a similar problem. I would recommend disabling it in general, because aggressive-indent will usually do what you want.

**Comment by syl20bnr** [comment]
We had a discussion about this, `electric-indent-mode` is enabled by default since `24.4`, to keep things consistent we force it then even `24.3` users get the same behavior.

Then we disable it where it makes sense, in python we found a way to disable it only for `:` [1]. We can completely disable it if Haskell layer has its own way to perform it.

[1] https://github.com/syl20bnr/spacemacs/blob/master/contrib/lang/python/packages.el#L147-150

**Comment by syl20bnr** [comment]
BTW nice catch @imalsogreg and @chrisbarrett :+1:

**Comment by syl20bnr** [comment]
It may be fixed in develop, I pushed the changes to remove hi2 and use the now updated indentation internal support of haskell-mode.

Be sure to update haskell-mode from MELPA before testing it.

**Comment by imalsogreg** [comment]
Thanks!!

Trying to test, but when I try to run the develop branch, startup fails. --debug-init trace below. I'm assuming I'm doing something wrong - replying here in case it's not a problem on my end.

```bash
git clone -b develop --recursive git@github.com:syl20bnr/spacemacs.git  ~/.emacs.d
```

```
Debugger entered--Lisp error: (wrong-type-argument listp t)
  face-spec-choose((t (:background "#fdf6e3")) #<frame emacs@jellyroll 0x119c090>)
  face-spec-set-2(term-default-bg-color #<frame emacs@jellyroll 0x119c090> (t (:background "#fdf6e3")))
  face-spec-recalc(term-default-bg-color #<frame emacs@jellyroll 0x119c090>)
  custom-theme-recalc-face(term-default-bg-color)
  enable-theme(solarized-light)
  ad-Orig-load-theme(solarized-light t nil)
  (with-no-warnings (ad-Orig-load-theme theme no-confirm no-enable))
  (setq ad-return-value (with-no-warnings (ad-Orig-load-theme theme no-confirm no-enable)))
  (let (ad-return-value) (setq ad-return-value (with-no-warnings (ad-Orig-load-theme theme no-confirm no-enable))) (let ((theme theme)) (setq spacemacs--cur-theme theme) (spacemacs/post-theme-init theme)) ad-return-value)
  load-theme(solarized-light t)
  spacemacs/load-theme(solarized-light)
  (let ((default-theme (car dotspacemacs-themes))) (spacemacs/load-theme default-theme) (setq-default spacemacs--cur-theme default-theme) (setq-default spacemacs--cycle-themes (cdr dotspacemacs-themes)))
  spacemacs/init()
  (progn (load-file (concat user-emacs-directory "core/core-load-paths.el")) (require (quote core-spacemacs)) (require (quote core-configuration-layer)) (spacemacs/init) (configuration-layer/sync) (spacemacs/setup-after-init-hook) (spacemacs/maybe-install-dotfile) (require (quote server)) (if (server-running-p) nil (server-start)))
  (if (spacemacs/emacs-version-ok) (progn (load-file (concat user-emacs-directory "core/core-load-paths.el")) (require (quote core-spacemacs)) (require (quote core-configuration-layer)) (spacemacs/init) (configuration-layer/sync) (spacemacs/setup-after-init-hook) (spacemacs/maybe-install-dotfile) (require (quote server)) (if (server-running-p) nil (server-start))))
  eval-buffer(#<buffer  *load*> nil "/home/greghale/.emacs.d/init.el" nil t)  ; Reading at buffer position 912
  load-with-code-conversion("/home/greghale/.emacs.d/init.el" "/home/greghale/.emacs.d/init.el" t t)
  load("/home/greghale/.emacs.d/init" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()
```

**Comment by syl20bnr** [comment]
Seems to be a theme error. Comment out the customized variable generated by emacs at the end of your dotfile to see if it helps.

**Comment by imalsogreg** [comment]
Agreed it is theme related, but I'm on a fresh spacemacs install, so there does not yet exist a ~/.spacemacs  (this is the dotfile, right?)

If I comment out [core-spacemacs.el line 81](https://github.com/syl20bnr/spacemacs/blob/master/core/core-spacemacs.el#L81) then spacemacs will finish its first-time setup sequence, I do a dotspacemacs/install, add the haskell layer.. but still there is no customized variable being generated by emacs at the end of my dotfile.

From then on, spacemacs will only start with core-spacemacs.el line 81 commented out.

Now, attempting to open any Haskell source file, I get this error message, and I lose the ability to switch buffers with M-x b (although I can still switch buffers by right-clicking the buffer name in the mode line):
```
funcall: Symbol's function definition is void: haskell-indentation-disable-show-indentations
Error in post-command-hook (evil-mode-check-buffers): (void-function haskell-indentation-disable-show-indentations)
```

At this point, I restart emacs. Navigating buffers works fine as long as I don't try to touch any Haskell source files.

The function `haskell-indentation-disable-show-indentations` is defined in haskell-indentation.el (which comes with haskell-mode from melpa)... if I open that file up and `eval-buffer` on it, now I can open Haskell source files, although there is still an error being reported:

```
File mode specification error: (void-function electric-indent-local-mode)
```

Sorry for the data dump.

**Comment by syl20bnr** [comment]
What is the version of your Emacs, which build is it ? Also what is your OS ?

**Comment by imalsogreg** [comment]
```
GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7) of 2014-03-07 on lamiak, modified by Debian
```

Ubuntu 14.04 - got emacs through apt-get (in the normal Ubuntu repository)

**Comment by syl20bnr** [comment]
Ok, I think that all the errors comes from the fact you are using the 24.3 version. If you can, try to update to 24.4.+, there must be some repos available with this version. I'll check on a 24.3 at home.

**Comment by imalsogreg** [comment]
Ahh Yes - I'm so happy!  Thanks, that was it. :)  Had to build 24.4 from source.  Indentation works perfectly right of of the box now.
