### ISSUE TITLE
Org SRC Blocks with Session Hanging?

### ISSUE THREAD

**Issue by ddoherty03** [syl20bnr/spacemacs#8190]
Does anyone else have a problem with emacs hanging when executing a code block that uses a session?

I have noticed it with ruby and shell code blocks, but not with perl, so it may be language-dependent.

In the following, the first two cause emacs to hang with the message "executing <lang> code block",
the perl example works fine.  I tried these in a non-spacemacs configuration and all worked, so I am thinking there is something about spacemacs going on here.

Can someone try these and let me know if they experience the same hang?  If so, I'll enter a bug report; otherwise, I'll have to investigate further.

```org
#+BEGIN_SRC ruby :session rjunk
(1..100).inject(:+)
#+END_SRC

#+BEGIN_SRC shell :session sjunk
seq 10
#+END_SRC

#+BEGIN_SRC perl :results output :session pjunk
print "hello"
#+END_SRC
```

**Comment by rpls** [comment]
Maybe something with blocks in general. On my setup emacs will hang when updating clocktable blocks every now and then.

**Comment by ddoherty03** [comment]
@rpls, did you try the example blocks?  If so, with what result?

**Comment by ddoherty03** [comment]
I am no longer seeing this problem, so I'm closing this down.
