### ISSUE TITLE
COPY PASTE does not work (C-SPC, M-w, C-y)

### ISSUE THREAD

**Issue by Ctaque** [syl20bnr/spacemacs#8191]
I'm new to Emacs and Spacemacs and i have a issue with copy and paste.
I tried C-SPC (ctrl+space) to highlight, M-w (alt+w) to copy, C-y (ctrl+y) to paste as described in documentation and it does not work. I get this behaviour instead when hitting ctrl+y : the line above is copied letter by letter.
It works when i use emacs in CLI.
Thanks for your help.
I'm running archlinux and emacs version is 25.1.1

**Comment by bmag** [comment]
Not enough info. Please read about [Debugging](https://github.com/syl20bnr/spacemacs/wiki/Debugging) in our wiki.
