### ISSUE TITLE
flyspell suggestions don't seem to be working

### ISSUE THREAD

**Issue by mlinchitstest** [syl20bnr/spacemacs#8192]
(sorry for not using the bug report form--will do it next time)

I'm, windows 10, GNU Emacs 25.1.1 (i686-w64-mingw32), spacemacs master branch.

**I am not able to get spelling suggestions work. Presumably it should work out of the box. When I see a misspelled word, I can see a hand cursor, which suggests that the word is clickable, but I nothing happens when you click.**

It is using the right dictionaries and gives suggestion, but not in `flyspell-mode`:
![image](https://cloud.githubusercontent.com/assets/19510975/22004377/b1d3b114-dc63-11e6-8eae-bd3942817a14.png)

![image](https://cloud.githubusercontent.com/assets/19510975/22004385/ccb00a3c-dc63-11e6-835f-a8b321b5f5af.png)

```lisp
;;layer config
 spell-checking
     (spell-checking :variables
                     =enable-flyspell-auto-completion= t)
     syntax-checking

;;user
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuratuion.
This is the place where mosst of your configurations should be done. Unless it is
explicitly specified that a variable should be set before a package is loaded,
you should place your code there."
  (setq ispell-program-name "c:/msys64/mingw64/bin/hunspell.exe")
  (setenv "LANG" "en_US")
  (setq ispell-chage-dictionary "en_US")
  (setq ispell-hunspell-dict-paths-alist
        '(("en_US" "c:/msys64/mingw64/share/hunspell/en_US.aff")
          ("ru_RU" "c:/msys64/mingw64/share/hunspell/ru_RU.aff")))
  )
```

I'm also wondering about what all those out of the box options in `ispell-change-dictionary` in helm are for. Does emacs come with ispell dictionaries pre-loaded or something? —cause I only installed two languages. If so, can emacs even use all these dictionaries once you set the `ispell-program-name` to hunspell?

(btw; it might be a good idea to just ship hunspell with the package for windows users—its pretty small, but it's a pain to figure out where and how to get it (msys2), and the config step is also difficult, because apperently on WIN you have to set  `(setenv "LANG" "YOUR_LANG")` unix-style, otherwise hunspell wont work at all [see here](http://emacs.stackexchange.com/questions/2171/what-options-are-there-for-writing-better-non-programming-text-in-emacs)

Thanks again for all your effort!

**Comment by mlinchitstest** [comment]
answer is `(spell-checking :variables enable-flyspell-auto-completion t)`

might want to update your [docs ](http://spacemacs.org/layers/+checkers/spell-checking/README.html#enable-auto-completion-popup) which give `(setq-default dotspacemacs-configuration-layers
  '((spell-checking :variables =enable-flyspell-auto-completion= t)))`

**Comment by nixmaniack** [comment]
Will be taken care of by https://github.com/syl20bnr/spacemacs/pull/8170.

**Comment by CarlQLange** [comment]
Looks like this can be closed, maintainers!

**Comment by duianto** [comment]
>When I see a misspelled word, I can see a hand cursor, which suggests that the word is clickable, but I nothing happens when you click.

Moving the mouse cursor over a typo, shows this message in the minibuffer:
>mouse-2: correct word at point

Middle clicking (on the scroll wheel with this mouse Logitech MX518) opens a menu with corrections, and options for:
Save word
Accept (session)
Accept (buffer)

**Comment by duianto** [comment]
Ok, the issue might have been the `=` signs around `enable-flyspell-auto-completion`:
```elisp
(spell-checking :variables
                     =enable-flyspell-auto-completion= t)
```
Since that has been fixed in the documentation, this will be closed.
