### ISSUE TITLE
SPC m g g is undefined for `.tsx` files (web-mode)

### ISSUE THREAD

**Issue by vyorkin** [syl20bnr/spacemacs#8198]
#### Description
SPC m g g is undefined for `.tsx` files (in `web-mode`)

#### Reproduction guide
- Start Emacs
- Be sure to use `vim` editing mode
- Open any `.tsx` file
- Put your cursor over the symbol and hit `SPC m g g`

*Observed behaviour:*
I observe `SPC m g g is undefined`

![img](https://i.gyazo.com/de29587df7c0dc2ba1dc2bdb0350a3e6.gif)

*Expected behaviour:*
I expect `SPC m g g` to go to symbol definition

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.3
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 273e1e94)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm themes-megapack auto-completion better-defaults emacs-lisp git github version-control clojure scheme elm purescript typescript react html yaml elixir c-c++ osx markdown)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

Obviously everything works just fine for `.ts` files, this only relates to working with `.tsx` files in `web-mode`.

Here is what I’ve tried so far (with no luck):
in `(defun dotspacemacs/user-config ()`
1) `(with-eval-after-load 'tide (add-to-list 'spacemacs-jump-handlers-web-mode 'tide-jump-to-definition))`
2) `(with-eval-after-load 'web-mode (add-to-list 'spacemacs-jump-handlers-web-mode 'tide-jump-to-definition))`

^ (I'm new to spacemacs and dunno what that does actually)

maybe the desired behaviour could be added here: https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/typescript/packages.el#L66 (but I'm not sure about that though)

> Jump handler already exists, just needs to be hooked up correctly.

related discussion in gitter: https://gitter.im/syl20bnr/spacemacs?at=587e8803873d96e16d7ef55f

**Comment by bmag** [comment]
In `.ts` files the major mode is `typescript-mode`, right? I think what you need to get `SPC m g g` working in `web-mode` is `(spacemacs|define-jump-handlers web-mode)` and `(add-to-list 'spacemacs-jump-handlers-web-mode 'tide-jump-to-definition)`.

I don't think it's a good overall solution, because `web-mode` is used elsewhere as well.

**Comment by vyorkin** [comment]
@bmag yeah, I'm going to try this. I think it would be useful to make this the default,
I mean, if the file has `.tsx` extension we know that its definitely typescript. What do you think?

**Comment by jupl** [comment]
#7865?

**Comment by syl20bnr** [comment]
Fixed in develop.
