### ISSUE TITLE
auto-completion not work for python

### ISSUE THREAD

**Issue by hackrole** [syl20bnr/spacemacs#8199]
I am new to emacs from vim, I have tried emacs before but failed. I try to install auto-completion cause it has yasnippets and auto-complete. but both not work at all.
while I open a python file. I notice the company(or auto-complete)-mode and yasnippet-mode not actived. I actived company-mode by run (M-x company-mode). but the complete still not work. I search throught the net, and after run (M-x run-python) the auto-complete seems work, but only sometimes, the keybindings describe at the office site not work at all.
Then I try to use yasnippet, but if does not work. the keybinding doesnot exists.

I have check that the yasnippet and company(and some others) packages was installed in the ~/.emacs.d/elpa. But it just does not work. Also I have run `pip install anaconda-mode `  `pip install jedi==0.8.1 json-rpc==1.8.1 service_factory==0.1.2` and it success.

**Comment by d12frosted** [comment]
Hello,

When you create an issue on GitHub it asks you to use `SPC h I` in Emacs instead. Using that template is useful because it attaches some info that might hint on what's wrong with your setup. So I would like to ask you to share the output of `SPC h d s`. 😸 

Meanwhile, just a shot in the air, did you enable python layer?

**Comment by hackrole** [comment]
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
('((erc :variables erc-server-list
        '(("irc.freenode.net" :port "6697" :ssl t :nick "hackrole" :password "secret"))))
 helm
 '(auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup t spacemacs-default-comopany-backends
                   '(company-files company-capf)
                   auto-completion-enable-help-tooltip t)
 themes-megapack git markdown emacs-lisp
 (python :variables python-test-runner 'pytest)
 ipython-notebook erlang go haskell html lua plantuml elixir clojure scala ruby yaml rust typescript javascript sql docker
 (mu4e :variables mu4e-accounts-alist t))
```
- System configuration features: JPEG NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

And of course I enable python-layer. 

![image](https://cloud.githubusercontent.com/assets/2100811/22054550/1f7a5b7c-dd91-11e6-950f-47e29f54a408.png)

**Comment by d12frosted** [comment]
> And of course I enable python-layer.

Yeah, I know it seems strange, but sometimes people forget about that. 😸

**Comment by joting** [comment]
I also have the issue where autocomplete is not working with company-mode in python (and also csharp, but it works fine in html).  But after enabling auto-complete-mode, it works in both python and csharp.

**Comment by samwhitlock** [comment]
I was having the same issue. Switching `python-shell-interpreter` to `python3` also solved it

**Comment by d12frosted** [comment]
Does it gets fixed if you just revisit file (`find-alternate-file`)?

**Comment by samwhitlock** [comment]
Ah whoops, it appears like this was for a different issue, where anaconda mode would complain that it couldn't find `setuptools.command`, even though I could easily get those in a python shell for both python 2 and 3. I switched this environment variable and it fixed that issue, but now I see that this was a different issue.
