### ISSUE TITLE
frame-local zoom affects some parts of powerline globally

### ISSUE THREAD

**Issue by kini** [syl20bnr/spacemacs#820]
Reproduce:
1. open spacemacs
2. do `SPC z f + + + + + + + +` to zoom in
3. do `SPC F n` to create a new frame
4. notice that in the new frame, parts of the powerline are big and parts are not, but the rest of the frame is at normal size
5. do `SPC z f - - - - - - - -` in the new frame to zoom out
6. notice that in the old frame, parts of the powerline have become small again, though the rest of the frame remains zoomed in

**Comment by StreakyCobra** [comment]
@TheBB This bug is nearly solved by spaceline :clap: There is only one default, when the new frame is created, the height of its spaceline is wrong, but as soon as the zoom is changed its correct again. Probably something easy to correct no :smiley: ?

**Comment by TheBB** [comment]
The problem here is that the powerline cache is global and not frame-local. This will probably have to involve a feature request for https://github.com/milkypostman/powerline.

**Comment by TheBB** [comment]
Actually it looks like the powerline cache is already frame-local. Not sure why this doesn't work, then.

**Comment by TheBB** [comment]
Ah, I guess we have to make `powerline-height` frame-local somehow.

**Comment by StreakyCobra** [comment]
If you have an idea where we could make it `Beginner friendly` :-)

**Comment by duianto** [comment]
This is still valid.

The mode-line heights can be seen growing at the same time when two frames are open, and one zooms in `SPC z f +` in one of the frames, but only the zoomed in frames text increases in size.

Observed in both Windows 10 and Ubuntu 18.04.02

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0d08e69f8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm markdown multiple-cursors
            (org :variables org-enable-org-journal-support t)
            spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4c8d82058)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP

**Comment by kini** [comment]
The issue is still valid. Reproduction steps in the OP have been updated to account for changes in default keybindings over the last 5 years.

**Comment by Kazark** [comment]
This is still a regular nuisance. :/ I don't know enough about the mode line to know how to get started on fixing it---anybody with more knowledge able to chime in and give some pointers?

**Comment by lebensterben** [comment]
if simply making it buffer-local can fix the problem, just make-buffer-local

**Comment by Kazark** [comment]
@lebensterben thanks for the response. What needs to be made buffer local do you think, `powerline-height`?

**Comment by lebensterben** [comment]
Yep, as indicated by previous comments. But I haven't tried myself.
I also think this should be fixed upstream.
If this cannot be solved, or if the upstream is not active, maybe removing this package is the best thing to do.

**Comment by Kazark** [comment]
I cannot even figure out which layer owns `powerline`---it's all over the place with `require`s and whatnot.

I tried putting `(make-variable-buffer-local 'powerline-height)` in `dotspacemacs/user-init` but it didn't do anything.
