### ISSUE TITLE
Replace react-mode with rjsx-mode?

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#8206]
[rjsx-mode](https://github.com/felipeochoa/rjsx-mode) has been working quite well for me instead of `web-mode`/`react-mode`. It derives from `js2-jsx-mode`, but has working indentation and syntax highlighting for jsx. 

What does everyone think of dropping the web-mode derived react-mode and replacing it w/ rjsx-mode? Personally, I just use rjsx-mode for *all* javascript.

**Comment by d12frosted** [comment]
I have never tried `rjsx-mode` (and I don't do much react development), but `react-mode` and `web-mode` are both buggy whenever I use them for editing react files. Next time I'll try `rjsx-mode`.

Would be interesting to hear from react users on this matter.

**Comment by myme** [comment]
I was thinking about filing this request myself. I've been using `rjsx-mode` a bit and it feels much closer to editing in `js2-mode`, obviously. Since it's so close to `js2-mode`, perhaps parameterizing the `javascript` layer with `rjsx`/`react` which pulls in that extra package could be an idea?

**Comment by elvis-sik** [comment]
Flycheck with eslint isn't working out of the box with `rjsx-mode` for me.

**Comment by elvis-sik** [comment]
Was able to get it working easily with `SPC e S`. I am currently having two problems with `rjsx-mode`. `Tab` in insert mode is never indenting and always bringing the autocompletion tooltip, even with no previous input.

Also, there is some new ES syntax not yet supported in `js2-mode`, and therefore also not in `rjsx-mode`. Though I don't see why this should stop Spacemacs from adopting it. Anyway, the specific syntax rule I am thinking about has already been reported to `js2-mode` and it seems they are working on it.

**Comment by aaronjensen** [comment]
> Flycheck with eslint isn't working out of the box with rjsx-mode for me.

`(spacemacs/add-flycheck-hook 'rjsx-mode)`

> Tab in insert mode is never indenting and always bringing the autocompletion tooltip, even with no previous input.

Can't help you here. I don't experience this. I use company-mode with some custom stuff and my tab is bound to `indent-for-tab-command`.

> Anyway, the specific syntax rule I am thinking about has already been reported to js2-mode and it seems they are working on it.

What is the syntax out of curiosity?

**Comment by elvis-sik** [comment]
This kind of method assignment:

```javascript
class Foo {
  bar = () => {
    return this;
  }
}
```

And for my Tab complaint, it seems that when it is indented to where it is supposed to be, say, two spaces, then Tab doesn't indent and only fires autocompletion. If the cursor isn't indented where it should be, then Tab indeed indents.

I think this behavior may be desirable if indentation is configured correctly. The one problem I've had with indentation is in the following case:
```JSX
      <PrevButton
        onClick={props.gotoPrevious}
        disabled={props.prevDisabled}
        />
```
I want the final `/>` to be indented the same as the opening `PrevButton`, but `Tab` thinks it should be as it is. So I intuitively type `Tab` in `insert-state` to try to reposition `/>`, but it brings helm-autocompletion. I am able to correct the indentation by escaping to `normal-state` and deleting two space characters before `/>`.

I haven't investigated all of this further as I've barely used React and `rjsx-mode` yet, these are just things I've noticed.

**Comment by aaronjensen** [comment]
> I want the final /> to be indented the same as the opening PrevButton

Ah, I do too, but I run [`eslint --fix` on save](https://github.com/aaronjensen/spacemacs.d/blob/master/layers/+aj/aj-javascript/local/eslint-fix/eslint-fix.el), so it fixes these things for me.

**Comment by willmcclellan** [comment]
I'd love to see this. I've switched to rjsx-mode and it just feels a lot better than react-mode 👍

**Comment by aikeru** [comment]
@aaronjensen for a spacemacs newbie, is there an easy way to make the switch? do I need to fork the react layer to do this?

**Comment by aaronjensen** [comment]
@aikeru you could clone https://github.com/aaronjensen/spacemacs.d into your `~/.spacemacs.d/layers/+aaronjensen` directory and then add `aj-javascript` to your layers.

Alternatively, you can see how I do it here: https://github.com/aaronjensen/spacemacs.d/blob/master/layers/%2Baj/aj-javascript/packages.el

**Comment by aikeru** [comment]
@aaronjensen thank you! So I've cloned it, but if I start any JSX tag it automatically inserts a self-closing suffix.
IE: I start
```
class Foo extends React.Component {
  render() {
    return (
      //if I enter "<" here, it automatically inserts "/>" after it resulting in "</>" where the cursor is behind the "/"
    )
  }
}
```
Did I mess something up? Is it supposed to do this? Here are my layers:
```
   dotspacemacs-configuration-layers
   '(
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     helm
     auto-completion
     ;; better-defaults
     emacs-lisp
     git
     ;; markdown
     ;; org
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     ;; spell-checking
     syntax-checking
     version-control
     csharp
     ;; javascript
     ;; react
     aj-javascript
     )

```

**Comment by aaronjensen** [comment]
@aikeru nope, that's the default behavior. Just hit `C-d` before the `/>` and it'll delete the `/` and replace it w/ a closing tag. It's pretty handy once you're used to it.

If `C-d` doesn't work, it may be because you're using regular evil instead of hybrid. I think you can do something like:

```
(define-key evil-insert-state-map (kbd "C-d") 'delete-char)
```

To get it.

**Comment by aikeru** [comment]
@aaronjensen I've added that line but all it seemed to do was move the <div/> backwards. I've created a gist with my .spacemacs here:
https://gist.github.com/aikeru/39f96fe140998d88925c04eb59ce7f94

I added the define-key line at line # 352 inside dotspacemacs/user-config function.

**Comment by aaronjensen** [comment]
Make sure you restart emacs or `,ec` w/ your point on the define-key. What you're describing is the default `C-d` binding.

**Comment by aikeru** [comment]
@aaronjensen OK! So, I had to add a hook for js mode that would call a function to set this (I guess something must be overwriting it?), but now when I `C-d` it deletes the `/` but does not insert the closing tag :/

**Comment by aaronjensen** [comment]
Ah, that's because rjsx-mode uses `rjsx-delete-creates-full-tag`. 

Do this instead:

```
(define-key evil-insert-state-map (kbd "C-d") nil)
```

That will remove it from the insert map and hopefully fall back to the rjsx-mode-map

**Comment by aikeru** [comment]
Oooh, shiny! :D thank you!
Here's the recipe as added to my .spacemacs:
```
;; Somewhere in top level
(defun react-tag-fix ()
  (define-key evil-insert-state-map (kdb "C-d") nil)
  )

(add-hook 'js-mode-hook 'react-tag-fix)
```

**Comment by aikeru** [comment]
It seems like it still trips a little on this syntax:
```
const Bar = () =>
  <div>
    //add a new tag here/hit enter and it is put at the same indentation as div
  </div>
```
But it's already working better than the react layer (which didn't syntax highlight, etc. this JSX)!

**Comment by aaronjensen** [comment]
Wrap things in parens:

```js
const Bar = () => (
  <div>
    //add a new tag here/hit enter and it is put at the same indentation as div
  </div>
)
```

**Comment by aikeru** [comment]
@aaronjensen that is a perfectly _reasonable_ answer, but some of the code I work on is formatted this way and other tools such as WebStorm and VSCode seem to handle/format this fine (so it would be unreasonable in my situation to demand others accommodate spacemacs...

**Comment by aikeru** [comment]
Opened https://github.com/felipeochoa/rjsx-mode/issues/34

**Comment by axyz** [comment]
currently react-mode is mainly a mix of web-mode, tern and eslint to provide a good enough react dev experience. Of course some IDE like features are missing:
- IDE like code navigation (a lot can be achieved with dumb-jump and silver searcher, but a proper function list and or project structure is missing)
- refactor (something can be done with tern, but probably incomplete)
- jsdoc integration is not really working properly (maybe can be fixed)

The main problem with js2 derived solutions are mainly on the jsx parsing: 
- web-mode is always very up-to-date for parsing rules
- never had issues with es6/es7 stuff or new jsx features
- indentation is complete pain:
```javascript
//your example
const Bar = () =>
  <div>
  </div>

// other case
return bool ?
  <div>
  </div>
:
  <div>
  </div>

// other case
<div className={classnames({
  foo: true,
})}/>

// other case
<div 
  className={className({
    foo: true,
  })
}/>

// etc, etc, etc...
```
 we can discuss about what should be the correct way, but in the real world you may encounter code bases adopting very different styles sometimes not even breaking the common eslint rules :p 
on web-mode it is very easy to quite dumbly just default to some indentation level and 90% of the time a web-beautify also on some large pieces of jsx end up with the desired result

using eslint fix may be an interesting workaround, eslint_d seems a very nice idea, but how do you handle eslint version? react-mode will currently use the version bundled in the current project node_modules and if not found will default to the system-wide one, is that possible with eslint_d?

In the end I'm not a heavy user of IDE like features and always used spacemacs or vim for coding so I'm probably missing some use cases, would be great to have a list of the missing features or knwon issues on react-mode and in js2 based modes to evaluate the pros and cons and what can be fixed in each solution.

**Comment by aaronjensen** [comment]
> using eslint fix may be an interesting workaround, eslint_d seems a very nice idea, but how do you handle eslint version? react-mode will currently use the version bundled in the current project node_modules and if not found will default to the system-wide one, is that possible with eslint_d?

From the [eslint_d.js readme](https://github.com/mantoni/eslint_d.js#how-does-this-work)

> You can then run eslint_d commands the same way you would use eslint and it will delegate to the background server. It will load a separate instance of eslint for each working directory to make sure settings are kept local. If eslint is found in the current working directories node_modules folder, then this version of eslint is going to be used. Otherwise, the version of eslint that ships with eslint_d is used as a fallback.

In other words, it handles this automatically as long as you have eslint_d.js globally installed.

For what it's worth, however, I'm more and more leaning towards just letting [prettier](https://github.com/jlongster/prettier/), probably with [prettier-eslint](https://github.com/prettier/prettier-eslint-cli) do its thing and not worry about formatting at all. There is not yet a prettier-eslint_d, but work is underway on a prettier_d of sorts and combining them shouldn't be hard.

By the way, if you just want eslint fix on save via eslint_d, look at https://github.com/aaronjensen/eslintd-fix

That all said, I don't actually remember why I switched to rjsx-mode from web-mode. I should clearly do a better job of writing issues. I'm guessing poor indentation was part of it. Probably bad flow support was another part. I'd have to go back to using web-mode to know for sure why I stopped using rjsx-mode. If people that have made the switch more recently could chime in, that'd be great.

**Comment by axyz** [comment]
@aaronjensen wouldn't it work using eslint_d and configuring eslint to use https://github.com/not-an-aardvark/eslint-plugin-prettier ?

I would definitely give it a try and see if can be included in react-mode, maybe as an option or better with auto-discovery.

**Comment by aaronjensen** [comment]
> wouldn't it work using eslint_d and configuring eslint to use https://github.com/not-an-aardvark/eslint-plugin-prettier ?

Unfortunately, not if you don't want semi-colons (which my teams and I tend to not). From the readme:

> This plugin works best if you disable all other ESLint rules relating to code formatting, and only enable rules that detect patterns in the AST. (If another active ESLint rule disagrees with prettier about how code should be formatted, it will be impossible to avoid lint errors.) You can use eslint-config-prettier to disable all formatting-related ESLint rules. If your desired formatting does not match the prettier output (e.g. if you don't want semicolons), you should use a different tool such as prettier-eslint instead.

**Comment by felipeochoa** [comment]
@aikeru If you don't like that `<` automatically inserts `</>`, you can add this to your `.emacs`:

```elisp
(with-eval-after-load 'rjsx
  (define-key rjsx-mode-map "<" nil)
  (define-key rjsx-mode-map (kbd "C-d") nil))
```

**Comment by abhishiv** [comment]
Hey @aaronjensen

quick question. Why is `SPC m m g` not implemented in your mode. Is it because it lacks tern?

**Comment by aaronjensen** [comment]
@abhishiv it could be, yeah. I typically disable tern so it doesn't conflict w/ flow.

**Comment by abhishiv** [comment]
@aaronjensen  awesome yeah that's what I thought. But thanks for you layer. Got me started with rjsx. Which is like heaven compared to react/js2 mode.

My +1 for  replacing react-mode with rjsx-mode!

**Comment by tko** [comment]
It seems switching to rjsx-mode (as in aaronjensens repo currently) would lose all the nice things about web-mode, most notably automatically closing the innermost tag when you type just `</` -- but some of the other commands are also nice on occasion, like renaming tags.

Is there any way to keep both, rjsx-mode for syntax highlighting / indenting and web-mode for refactoring and other things?

On somewhat related note I noticed having three separate toplevel menus for javascript in rjsx-mode: `IM-JavaScript-IDE`, `JavaScript`, and `Javascript` -- could those be merged into one?

**Comment by aaronjensen** [comment]
> most notably automatically closing the innermost tag when you type jus

rjsx handles this differently, they insert the closing `/>` automatically and if you `C-d` the `/` it inserts the closing tag in its stead. It works well for me.



> On somewhat related note I noticed having three separate toplevel menus for javascript in rjsx-mode: IM-JavaScript-IDE, JavaScript, and Javascript -- could those be merged into one?

I don't know anything about this, maybe open an issue on [rjsx-mode](https://github.com/felipeochoa/rjsx-mode)

**Comment by tko** [comment]
> rjsx handles this differently, they insert the closing /> automatically and if you C-d the / it inserts the closing tag in its stead. It works well for me.

Using vim style for me `C-d` seems to just dedent the line, and `fn-<backspace>` (delete for mac) only deletes the slash. No idea what key would trigger the intended behavior. In any case it feels little off, backwards -- deleting a character inserts more characters? Well, I can see how it makes sense to maintain balanced tags but as for keybinding ergonomics I can't recall any vim equivalent precedent.

**Comment by aaronjensen** [comment]
> Well, I can see how it makes sense to maintain balanced tags but as for keybinding ergonomics I can't recall any vim equivalent precedent.

Sure. I use hybrid mode, so this thinking doesn't really apply. You can scroll up to see how you can add it in vim if you want to.

**Comment by felipeochoa** [comment]
Yeah I'm not sure what the equivalent command in evil mode would be, but I do think that rebinding `C-d` is probably not the optimal way of doing things. I considered advising `delete-char` but that felt too heavy-handed since it would leak to other buffers. 

I've also created an `rjsx-rename-tag-at-point`. If there are any other functions along those lines, feel free to open up issuesto request them.

**Comment by tko** [comment]
For the record to make `C-d` to replace `/>` with a `></tag>` in vim style the command is
```
(define-key evil-insert-state-map (kbd "C-d") 'rjsx-delete-creates-full-tag)
```
which is the default for hybrid/emacs styles I assume and the earlier examples were to _disable_ that behavior.

**Comment by aaronjensen** [comment]
> which is the default for hybrid/emacs styles I assume and the earlier examples were to disable that behavior.

@tko Just needed to scroll a bit further to https://github.com/syl20bnr/spacemacs/issues/8206#issuecomment-283148377 which accomplishes the same thing as your snippet, but in a different way 😄 

> I've also created an rjsx-rename-tag-at-point. If there are any other functions along those lines, feel free to open up issuesto request them.

Awesome, thanks @felipeochoa!

**Comment by laduke** [comment]
pro rxjs-mode
pro aj-javascript

**Comment by skattyadz** [comment]
@aikeru Tiny thing, but there's a typo in your code snippet. `kdb` vs `kbd` at https://github.com/syl20bnr/spacemacs/issues/8206#issuecomment-283149117

Thanks for your work in this thread @aaronjensen, I'm using your layer as a starting point and it's working well

**Comment by skattyadz** [comment]
Oh, and I find that indentation annoying too. There's a hacky fix here http://blog.binchen.org/posts/indent-jsx-in-emacs.html

**Comment by aaronjensen** [comment]
No problem, glad it's helping.

For what it's worth, I'd recommend not worry about indentation and using [prettier](https://github.com/prettier/prettier), [eslint-plugin-prettier](https://github.com/not-an-aardvark/eslint-plugin-prettier), [eslint_d](https://github.com/mantoni/eslint_d.js), and [eslintd-fix](https://github.com/aaronjensen/eslintd-fix). With that combo, every time you save your file it will completely format and indent your code for you. It's a game changer.

Sure, it'd be great if emacs indented things the way I wanted them on its own... but, it doesn't and even if it did, it's not the only editor in use on my team.

**Comment by aaronjensen** [comment]
That said, it still seems like a nice thing to have https://github.com/aaronjensen/spacemacs.d/commit/9efb1a58f7b334cff7370cfe66188225050ef4bf (I cleaned it up a bit to get rid of the replace flash and simplify the code), thanks @skattyadz  😄

**Comment by skattyadz** [comment]
In an ideal world that would be amazing, but it relies on the projects I contribute to using prettier, which isn't the case yet. That said, so long as it falls back gracefully there's no loss in having it. I am excited for how prettier eradicates these style inconsistencies

**Comment by dre-hh** [comment]
@aaronjensen there are multiple issues in this repo regarding react layer. would you like to pull request your config as rjx layer to the spacemacs repo?

**Comment by aaronjensen** [comment]
@dre-hh probably not, i'm not sure it's a good idea to have multiple layers to do the same thing. People can already use mine today if they want to. I think that the issues here should get worked out here--if that means replacing the layer entirely w/ pieces from mine/etc that's fine.

**Comment by laduke** [comment]
I can't reproduce it right now, but sometimes on-save will delete or duplicate lines o_O. 

I wonder if there's a way to prettier-region, that would help me in my existing non-prettier apps where I don't want to format a whole file when making a small change.

**Comment by laduke** [comment]
Maybe it would be easier to figure out time travel and go back and kill JSX?

**Comment by dre-hh** [comment]
@aaronjensen i`ve used your config and so far i enjoy it more than default react layer.
I had to do some adjustments though.

1. Are you using dev version of spacemacs, because `spacemacs/enable-flycheck` is not available for me. I also can`t find it in the spacemacs source code neither on master nor on dev branch (perhaps github search is bad). I`ve found something on another github repo and had do define this function. 

```elisp
(defun aj/enable-flycheck (mode)
  (when (and syntax-checking-enable-by-default
             (listp flycheck-global-modes)
             (not (eq 'not (car flycheck-global-modes))))
    (add-to-list 'flycheck-global-modes mode)))
```

So you just have to add `'rjsx-mode` to the `flycheck-global-modes` list

2. If you would like to use eslint package from the current project istead of the global one ,You  can add a call to the following function in `aj-javascript/eslintd-set-flycheck-executable` at the end.

```elisp
(defun aj-javascript/use-eslint-from-node-modules ()
  (let* ((root (locate-dominating-file
                (or (buffer-file-name) default-directory)
                "node_modules"))
         (eslint (and root
                      (expand-file-name "node_modules/eslint/bin/eslint.js"
                                        root))))
    (when (and eslint (file-executable-p eslint))
      (setq flycheck-javascript-eslint-executable eslint))))
```

**Comment by aaronjensen** [comment]
> Are you using dev version of spacemacs?

Yes. Github search only searches master.



> If you would like to use eslint package from the current project istead of the global one

I use `add-node-modules-path` which is also in `develop`.

https://github.com/aaronjensen/spacemacs.d/blob/master/init.el#L399
https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Btools/node/packages.el#L18

**Comment by tgroshon** [comment]
@aaronjensen None of those links to https://github.com/aaronjensen/spacemacs.d/ are working for me.  Did you rename or remove the repo?

**Comment by aaronjensen** [comment]
@tgroshon sorry, they've been moved to private, but there are still forks available. https://github.com/smdern/spacemacs.d is the most up to date, I believe.

**Comment by juboba** [comment]
That's a pity, you have a great layer I've been using for sometime. Are you planning on making it public again?

**Comment by myme** [comment]
I'm using this too. I just sneakily vendorized it into my private layers. Would upstreaming this as an alternative react layer perhaps be an option? Or perhaps a show of hands determining if people want a web-mode or rjsx-mode based solution. Dunno...

**Comment by itome** [comment]
https://github.com/itome/dotfiles/tree/master/.spacemacs.d/layers

I created experimental layer for react with rjsx-mode. This layer is almost same with javascript layer except for rjsx-mode. I created this for me, and it is very comfortable to write react code because the auto-completion and syntax-checking is same as javascript layer. 
This layer contains
- auto-completion
- syntax-checking
- formatting
- jump to declaration
- refactor
- js doc 
..etc
This layer is only experimental, but I hope this may be someone's help.

**Comment by abhishiv** [comment]
Hey @itome, just checked it out and looks great. Indentation is much more usable, and eslint is working as well. Just one question, how can I "jump to declaration" on a import/require? Can't seem to find it.

**Comment by itome** [comment]
Thanks for asking, jump to definition is also same as js2-mode, and you can jump from import statement like
```
import React from 'react';
             ^  <- press SPC m g g here
```
I don't know why but jsx module can't be reached. This occured also in javascript layer so I think this is not the issue of tern. Please see this issue. -> https://github.com/ternjs/tern/issues/939

**Comment by svepe** [comment]
@itome The RJSX mode layer that you have created looks great, however I experience a problem with the colors layers. I have enabled the rainbow identifiers with `(colors :variables colors-colorize-identifiers 'all)` in my config file, but this coloring is applied only to the segment of the buffer initially visible on the screen. When I scroll down to a new section of the buffer all identifiers are white. By running the beautifier with `SPC m =` the color of the white identifiers is properly updated, however, identifiers in the other part of the buffer, which was visible before, become white. I was wondering if you have any suggestions why this is the case?

**Comment by revmischa** [comment]
Yeah something is horribly broken with the default tab behavior in react-mode. Does autocomplete or turns something into an HTML tag (!?!?) instead of indenting like any other mode
Also I can't figure out how to change the indent to 2 spaces globally

**Comment by namelos** [comment]
According to @aaronjensen he probably don't want to duplicate another react layer.
But everyone in this thread compliment rjsx-mode quite a lot, and feels web-mode and react-mode quite buggy.
Any chance we could replace current react layer to rjsx-mode?

**Comment by NerdsvilleCEO** [comment]
This does seem to work better but I am getting the same indentation issue, any tips?

**Comment by aaronjensen** [comment]
I’d recommend using prettier and not worrying about indentationissues

**Comment by myme** [comment]
`prettier` followed by `eslint --fix` (using `eslintd-fix-mode`) is what I do. Take care in which order the mode hooks are added to the major mode hook, for it to be applied to the buffer in the correct order. Having `prettier-mode` after `eslintd-fix-mode` seems to make `prettier` run first.

**Comment by aaronjensen** [comment]
In my experience, https://github.com/prettier/eslint-plugin-prettier with eslintd-fix works best. I'd only recommend `prettier-js-mode` for typescript files if you don't have eslint set up on them. I've tried to make `eslintd-fix` very fast, so it's able to apply prettier (and other fixes) much faster than `prettier-js-mode` is.

**Comment by myme** [comment]
That sounds promising @aaronjensen. I'll try it out and thanks for the tip.

**Comment by axyz** [comment]
any extensive usage experience with typescript-tsx-mode (also in non typescript projects)? 
syntax and indent seems to work fairly. Jump to definition and autocomplete seems to work much better than with tern, but there may be issues I didn't see so far

**Comment by aaronjensen** [comment]
@axyz I've used it a lot (I added it to spacemacs). It's just web-mode. The auto-complete is better because it uses the typescript server.

**Comment by orther** [comment]
One issue to be aware of using the typescript server (tsserver) is that it can not support dynamic module resolution such as Webpack's `require.context`.

**Comment by aikeru** [comment]
FWIW as far as I'm aware TypeScript also does not support .mjs or .es6 (or breaks in certain ways on any extension that doesn't have hardcoded support). I'd love to hear that the situation has changed since last I checked, but a quick Google search seems to confirm what I saw last time I tried.

**Comment by axyz** [comment]
https://github.com/syl20bnr/spacemacs/pull/10548 this fixes the weird autocomplete behavior on typescript layer.

more things that definitely have to be fixed:
- removing company-web-html from the company backends to avoid not relevant autocomplete clutter when using tern or tsserver. Tried out a bit but was not able to do it properly, was someone able to leave only tern/tsscript suggestions without all the link, doctype, script, etc stuff?
- fix jsdoc, current behavior is quite buggy (e.g. describing functions usually add the doc on top of document) also proper keybindings also missing
- proper jump to definition in react-mode. It works quite well in typescript mode, but not really on react-mode probably because of tern vs tsserver?
- proper refactor (also slightly better on ts mode)

someone mentioned issues with indent, can you be more specific? In general indent seems more reliable on web-mode based layers for me.

for the js2/rjsx based layers the syntax checking is quite annoying, can it be disabled and only rely on eslint/tslint? (e.g. always complaining about trailing commas). The other "issue" is that they rely on their own parser that need to be maintained separately, while web-mode is always quite up to date with latest features and it is also more generic thinking of scenarios where using other templates like vue or similar.

Ideally all these features may be merged in a single js layer? Would be nice to rely on autodiscovery for everything (e.g. eslint, tslint, prettier, jsx, flow, etc...). Can we identify other pain points to fix?

**Comment by axyz** [comment]
**UPDATE**
https://github.com/felipeochoa/rjsx-mode/pull/66   this PR provides the rjsx-minor-mode, it seems to work correctly with js2-refactor.

I was not able to get js-doc to work properly though

**Comment by dagadbm** [comment]
what's the latest status on this?

This is the only think keeping me from using spacemacs completely in favor of vscode.

Btw, Why does the layer use tern and not an LSP? Isn't it better if it used an LSP?

Auto complete fails for things like enzyme and chai. 

Any tips on how to go the this working for good in one single layer for all js (jsx or not)?

**Comment by syl20bnr** [comment]
I merged PRs from @axyz . This is a long thread, I did not follow it entirely TBH.

We have a pending PR for `rjsx-mode` here: https://github.com/syl20bnr/spacemacs/pull/10627

**Comment by jmromer** [comment]
In case it helps future on-lookers: 

I had the same issue with `C-d` not behaving as intended by RJSX-mode [as described here](https://github.com/syl20bnr/spacemacs/issues/8206#issuecomment-283139504). But I was already using hybrid style

```emacs-lisp
;; home/spacemacs.d/init.el L134-137 (3bb5c114ea)

dotspacemacs-editing-style '(hybrid :variables
                                    hybrid-mode-enable-evilified-state t
                                    hybrid-mode-enable-hjkl-bindings t
                                    hybrid-mode-default-state 'normal)
```
<sup>
  <a href="https://github.com/jmromer/dotfiles/blob/3bb5c114ea/home/spacemacs.d/init.el#L134-L137">
    home/spacemacs.d/init.el L134-137 (3bb5c114ea)
  </a>
</sup>
<p></p>


so the [suggested fix](https://github.com/syl20bnr/spacemacs/issues/8206#issuecomment-283148377) was not effective. Neither was changing `hybrid-mode-default-state 'normal` to `hybrid-mode-default-state 'emacs`.

I worked around the issue by simply re-binding `rjsx-delete-creates-full-tag` for RJSX mode:

```emacs-lisp
;; home/spacemacs.d/init.el L395-400 (3bb5c114ea)

(defun rjsx-hybrid-keybindings ()
  "Bind C-d to `rjsx-delete-creates-full-tag'."
  (if (bound-and-true-p evil-hybrid-state-map)
      (define-key evil-hybrid-state-map (kbd "C-d") #'rjsx-delete-creates-full-tag)
    (error "Failed defining RJSX hybrid state keybindings")))
(add-hook 'rjsx-mode-hook #'rjsx-hybrid-keybindings)
```
<sup>
  <a href="https://github.com/jmromer/dotfiles/blob/3bb5c114ea/home/spacemacs.d/init.el#L395-L400">
    home/spacemacs.d/init.el L395-400 (3bb5c114ea)
  </a>
</sup>
<p></p>


Even with that, `C-d` only works if I'm on a space character, not a word char, producing, for example:

```jsx
<Form >text</Form>
// instead of 
<Form>text</Form>
```
Alternatively, with my cursor on a word char, I can switch to evil-normal state and then back into evil-insert state. I'm not sure if that's by design.

In any case, that's good enough for me for now :)

**Comment by adimit** [comment]
Unfortunately, `rjsx` does not support flow at all mooz/js2-mode#224 and is unlikely to add support soon. `react-mode`, however, does. As long as `rjsx` does not support flow I'd consider switching to it for JSX support a major regression.

**Comment by aaronjensen** [comment]
@adimit for that, I've been using: 

```el
     (js2-mode :location (recipe :fetcher github :repo "HairyRabbit/js2-mode"))
```

**Comment by adimit** [comment]
@aaronjensen Huh, thanks. I can't get it to work, though. After adding it to `dotspacemacs-additional-packages` it seems Spacemacs still prefers `js2-mode` from Elpa.

Which is probably sane, too, seeing as HairyRabbit's js2-mode hasn't been updated in almost 6 months…

**Comment by aaronjensen** [comment]
@adimit I believe you need to manually delete the package so it can be reinstalled. But yeah, if it has fallen behind it may not be worth it. I personally moved to typescript for this and other reasons.

**Comment by dagadbm** [comment]
3 years later ...

**Comment by tgroshon** [comment]
@dagadbm I just switched to the `develop` branch and called it good. Not perfect, but the enhancements are good. And RJSX
