### ISSUE TITLE
Fill column indicator doesn't actually indicate fill column

### ISSUE THREAD

**Issue by kini** [syl20bnr/spacemacs#821]
Reproduce:

1. Open spacemacs
2. Do `SPC t 8` and notice that a vertical line appears at the 79th column
3. Do `C-x f 20 RET` to set the fill column to 20 instead of 79
4. Notice that the vertical line does not move to the 20th column
5. Do `SPC t 8 SPC t 8` to turn the fill column indicator off and back on again, and notice that it still appears at the 79th column

**Comment by syl20bnr** [comment]
@kini @endrebak 
I also moved the binding from `SPC t 8` to `SPC t c`.
