### ISSUE TITLE
hindent has dropped support for different styles

### ISSUE THREAD

**Issue by langston-barrett** [syl20bnr/spacemacs#8214]
The `hindent` tool used in the `haskell` layer [has dropped support for styles](https://github.com/chrisdone/hindent/blob/2580027fe01f3c76a01e2695411f0b0b4b60e1c4/MIGRATION.md). The variable that enables it should likely be switched to a simple boolean switch. 

Here's [the code in config.el that should be changed](https://github.com/syl20bnr/spacemacs/blob/c788da709bb1c74344f5ab1b6f18cfdf6b930df8/layers/%2Blang/haskell/config.el#L28).

**Comment by Miciah** [comment]
Looks like this was fixed with #10072 / https://github.com/syl20bnr/spacemacs/commit/59f78d87006257d2dd2fd693fe50745bc37f6d38 on the develop branch.
