### ISSUE TITLE
[latex layer] About use xelatex instead of pdflatex to build tex file

### ISSUE THREAD

**Issue by zhcosin** [syl20bnr/spacemacs#8219]
Hi, spacemacs latex layer use pdflatex to build tex file by default, but I use xelatex to do the same work(I am Chinese), I can set the variable `TeX-engine` provided by auctex to "xetex" to implement this, weather latex layer could provide a layer variable to custom this?

**Comment by iamthad** [comment]
Does the [`latex-build-command` layer variable](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/latex#build-command) do what you want?

**Comment by zhcosin** [comment]
I had tried the following method in `dotspacemacs/layers()`:
```
dotspacemacs-configuration-layers '(
  (latex :variables latex-build-command "LaTeX"))
```
but after this, it still use pdflatex to build tex file and the variable `TeX-command-list` can not be described so I can not add entity to this list, if I add '(setq TeX-engine 'xetex)' in `dotspacemacs/user-config()` then it use xelatex to build tex file.

I use windows 7 and texlive 2016, spacemacs develop branch.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. f5957eb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(html ivy auto-completion better-defaults emacs-lisp git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control
      (latex :variables latex-build-command "LaTeX"))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS
