### ISSUE TITLE
Auto-completion is triggered in weird places with React layer

### ISSUE THREAD

**Issue by elvis-sik** [syl20bnr/spacemacs#8222]
#### Description :octocat:
Auto-completion is triggered in places in which it shouldn't using the React layer. So it is often necessary to cancel autocompletion. When I use the plain JavaScript layer this does not happen.

#### Reproduction guide :beetle:
- Start Emacs
- Open some JSX file.
- Type in `class Class extends Component {`

*Observed behaviour:* :eyes: :broken_heart:
An autocompletion popup appears right after `{`.
If one then quickly presses `Enter` to open a newline (to type in the code for the class), the first suggestion is accepted, and one has to manually remove it.

*Expected behaviour:* :heart: :smile:
No autocompletion should be triggered there.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 19bfb9ea)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv auto-completion better-defaults emacs-lisp git markdown
     (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell shell-default-term-shell "/bin/zsh" shell-enable-smart-eshell t)
     spell-checking smex syntax-checking version-control cscope gtags semantic xkcd github
     (c-c   :variables c-c  -default-mode-for-headers 'c-mode c-c  -enable-clang-support t)
     extra-langs html javascript shell-scripts sql yaml
     (python :variables python-test-runner 'pytest python-enable-yapf-format-on-save nil)
     ipython-notebook
     (haskell :variables haskell-enable-ghc-mod-support t haskell-enable-hindent-style "gibiansky" haskell-enable-shm-support t haskell-completion-backend 'intero)
     evil-commentary
     (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t evil-snipe-repeat-scope "visible")
     react idris evil-cleverparens asm octave systemd ess polymode
     (ranger :variables ranger-show-preview t)
     selectric)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by rcanepa** [comment]
Hi, could you solve this issue? I am having the exact same problem and it is super annoying.

**Comment by elvis-sik** [comment]
https://github.com/syl20bnr/spacemacs/issues/8206 using @aaronjensen 's layer works for me

**Comment by hakunin** [comment]
The aj layer did not work at all for me out of the box. It would be nice if this was addressed right out of the box.

**Comment by aaronjensen** [comment]
@hakunin can you say more? Were you using spacemacs develop? Did you get it working?

**Comment by hakunin** [comment]
I am back to Vim since spacemacs doesn't work with `evil-tabs` and I found no way to get tabs working yet. I wasn't able to get aj to work as suggested here, but I was able to run `rjsx-mode`.

**Comment by beta1440** [comment]
I'm certain that this issue is due to 3bbafcbfe35c8af746ec9d64a2d7d0c79ee1413b. The commit sets `company-minimum-prefix-length` to 0 which causes the auto-complete popup to show after typing any character. This fix works well for HTML, but it causes issues for other languages.

**Comment by alistaircolling** [comment]
hey @beta1440 ! thanks for that. I added this to my .spacemacs file and I can now write a function without having to delete unwanted auto completes!
`  (setq company-minimum-prefix-length 2)`

**Comment by cmatzenbach** [comment]
Has any further research been done on this?  Having this autocompletion window pop up at the end of every line makes react-mode literally unusuable for me.  I tried @beta1440 fix but it didn't work at all

**Comment by alistaircolling** [comment]
Yep, I'm afraid this is still happening for me too and @beta1440 fix isn't working either :/
![image](https://user-images.githubusercontent.com/111540/31815796-badfa816-b585-11e7-9fe3-6158294ea178.png)
Does anyone have any suggestions or is seeing this? Thanks! :)

**Comment by paulyoung** [comment]
I tried the suggestions here recently and it made no difference.

**Comment by zanemayo** [comment]
I had the same problem and setting `(setq company-minimum-prefix-length 2)` didn't work.

What did work was adjusting `company-minimum-prefix-length` in the source code of the html layer.

Go to `.emacs.d/layers/+lang/html/funcs.el` and change 
`  (set (make-local-variable 'company-minimum-prefix-length) 0))`
to 
`  (set (make-local-variable 'company-minimum-prefix-length) 2))`

Then restart emacs. 

If this works for everyone else, maybe we can get the html layer fixed.

**Comment by alistaircolling** [comment]
This works for me too! Only done a quick test but saves me about 6 keystrokes every time I write a function! Jeez. Thanks @zanemayo

**Comment by rifazn** [comment]
@zanemayo Thank you. This just saved me from a week long headache I was having to deal with.

**Comment by CMCDragonkai** [comment]
Why does `company-minimum-prefix-length` fix this problem and are there any side-effects? Right now the react layer is somewhat unusable.

**Comment by beta1440** [comment]
The `company-minimum-prefix-length` variable specifies the number of characters in a word you must enter for the company completion pop-up to show. When it is set to 0, the completion popup will show after typing any character. The commit 3bbafcbfe35c8af746ec9d64a2d7d0c79ee1413b introduced this behavior so that when writing HTML, you get the completion popup when you type in something like the `<` character like in this discussion: https://github.com/osv/company-web/issues/4.

**Comment by martinxyz** [comment]
Same issue when editing Vue templates. (.vue mixed html/js/css content in web-mode).

Fix:
`layers/+lang/html/packages.el`
```
-        company-minimum-prefix-length 0)
+        company-minimum-prefix-length 1)
```

**Comment by alimavrakis** [comment]
thanks @zanemayo--fixed the issue for me. I'm not sure I understand why changing the html layer's config fixed it for `.jsx` files though. Does installing the react layer put html and js minor modes on `.jsx` files? If so, is there anything we can do it fix it only for `.jsx` files, perhaps in the react layer's config?

**Comment by dsedivec** [comment]
I haven't tried this, but perhaps adding `<` to `company-auto-complete-chars` is a better solution than setting `company-minimum-prefix-length` to `0`?

**Comment by Compro-Prasad** [comment]
I also haven't tried this but I agree with @dsedivec .

**Comment by syl20bnr** [comment]
Can someone try this ?

**Comment by Compro-Prasad** [comment]
I did a bit of research on this and found out that the completion is triggered when one of the functions from `company-begin-commands` returns true. From an user perspective one should write their own function on when should the completion be triggered and put this function in `company-begin-commands`.
Following up there was a related issue on [company's](https://github.com/company-mode/company-mode/issues/688) repo which is closed now. It suggests that these things should be implemented by the backend. This led me to reading [company-clang](https://github.com/company-mode/company-mode/blob/master/company-clang.el#L344) source which enabled completion on `.` and some other characters in C and C++ sources.
Now, `company-web` is a totally different package that doesn't come with company. So, this backend should be having this feature which I am not sure of. Seeing [it's](https://github.com/osv/company-web/blob/master/company-web-html.el) source does reveal that it has some regexp for the purpose but I haven't written much Emacs Lisp to understand it.
For this I have opened an issue on company-web's repo: https://github.com/osv/company-web/issues/20

**Comment by Compro-Prasad** [comment]
Is it a company-web thing? I don't know. I don't use React. I tested this on an HTML file.

**Comment by delaanthonio** [comment]
@syl20bnr I've tried adding `<` to `company-auto-complete-chars` and it doesn't work. I think it's best to set `company-minimum-prefix-length` to `1` for the time being. Having `company-minimum-prefix-length` set to `0` causes autocomplete issues which provide a poor experience for new users to Spacemacs.

Below is a code snippet I used when modifying `company-auto-complete-chars`.

```emacs-lisp
(defun html/init-company-web ()
  (use-package company-web
    :defer t
    :init
    (progn
      (spacemacs|add-company-backends
        :backends (company-web-html company-css)
        :modes web-mode
        :variables
        ;; see https://github.com/osv/company-web/issues/4
        company-minimum-prefix-length 1
        company-auto-complete-chars "<"))))
```

**Comment by Compro-Prasad** [comment]
This is a problem with the `company-web` package. IMO it is not handling this situation properly. I have opened an issue there. 

https://github.com/osv/company-web/issues/20

**Comment by sdwolfz** [comment]
@delaanthonio if you can open a PR with this I will happily test and merge it.

**Comment by delaanthonio** [comment]
@sdwolfz I finally submitted the pull request: #11525.

**Comment by delaanthonio** [comment]
This issue should be fixed on the latest develop branch since my pull request was merged!

**Comment by ezmiller** [comment]
@delaanthonio I am on the develop branch and seeing a behavior that I think is related. If I am in react file and I type something like

```javascript
render() {
  return (
  );
}
```
In the line after the return, if the cursor is just before the closing paren and I hit `TAB`, I get this in-line list of control statements instead of the desired indent:
![image](https://user-images.githubusercontent.com/772738/50451808-5c071d00-0904-11e9-9d8e-df5b304dfb10.png)

Just by way of comparison, if I try the same in VSCode, the moment I hit return the parens are placed in the correct position, and the cursor is indented:

![image](https://user-images.githubusercontent.com/772738/50451838-8953cb00-0904-11e9-8af5-f176bce37223.png)

**Comment by ezmiller** [comment]
Following up on my previous comment https://github.com/syl20bnr/spacemacs/issues/8222#issuecomment-449992782, I checked the value of `company-minimum-prefix-length` and it is set to `2` when I'm in the react file and seting this problem
