### ISSUE TITLE
Scroll-margin is ignored when scrolling from the bottom of a buffer

### ISSUE THREAD

**Issue by Alexander-Miller** [syl20bnr/spacemacs#8224]
#### Description :octocat:
Scroll-margin and scroll-conservatively are ignored when scrolling up from the bottom of a buffer.

#### Reproduction guide :beetle:
- Start Emacs
- `(setq scroll-margin 10)`
- `(setq scroll-conservatively 10)`
- Move point to the very bottom of any long buffer, like your .spacemacs
- Scroll upwards

*Observed behaviour:* :eyes: :broken_heart:
Point moves to the very top of the screen and then the entire buffer is recentered.
This happens twice, afterwards scroll behaviour is as expected. This only happends when
scrolling from the bottom to the top.

In Pictures:

 - [Point reaches top of screen](http://i.imgur.com/xlIY0I0.png)
 - [The view then recenters](http://i.imgur.com/Q3247gS.png)

*Expected behaviour:* :heart: :smile:
The view should be scrolling upwards once point is 10 lines away from the top of the screen.

In Pictures:
 - [Point comes within 10 lines of the top of the screen](http://i.imgur.com/o8IUYVB.png)
 - [View smoothly scrolls along](http://i.imgur.com/eM5UsVJ.png)

The issue is reproducible with default spacemacs settings, but not with `emacs -q`, so I assume there's something inside spacemacs causing this.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.50.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. c6bf7f76)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-private-snippets-directory nil auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
 better-defaults emacs-lisp git html markdown org python ranger rust syntax-checking shell-scripts version-control vimscript)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES LIBSYSTEMD

**Comment by iryston** [comment]
Same problem in OS X El Capitan

**Comment by patata3000** [comment]
I've got the same problem on arch linux. It's sometimes recentered once or twice.

**Comment by Amatrelan** [comment]
Got same problem, macOS High Sierra.
Something goes wrong when buffer get's to bottom.

**Comment by sandorex** [comment]
I have same problem with vanilla emacs 26.1

**Comment by sollidsnake** [comment]
I came up with a fix using an advice around the `previous-line` function:

```
(defvar sm-use-visual-line t)

(defun sm-fix-enable()
  (advice-add 'previous-line :around 'sm-fix))

(defun sm-fix-disable()
  (advice-remove 'previous-line 'sm-fix))

(defun sm-get-lines-from-top ()
  (if sm-use-visual-line
      (save-excursion
        (beginning-of-line)
        (count-screen-lines (point) (window-start)))
    (- (line-number-at-pos (point)) (line-number-at-pos (window-start)) )))

(defun sm-fix(old-function &rest args)
  (apply old-function args)
  (let ((diff (- scroll-margin (sm-get-lines-from-top))))
    (when (> diff 0)
    (scroll-down diff))))

(sm-fix-enable)
```
Now it seems to work properly, but still it would be nice to be fixed upstream properly.

**Comment by duianto** [comment]
The issue occurs when `M-x global-hl-line-mode` is enabled.

Tested with `emacs -q` (26.1 and 27.0.50).

**Comment by sollidsnake** [comment]
It also happens when you have the `display-line-numbers-mode` enabled.

**Comment by Alexander-Miller** [comment]
This is not a spacemacs problem, it can be reproduced in `emacs -q` by enabling the scroll settings and `dispaly-line-numbers-mode`, so I will close here.

I'll also put reporting this to the emacs developers on my todo list.
