### ISSUE TITLE
salt-mode is unavailable

### ISSUE THREAD

**Issue by pwalsh** [syl20bnr/spacemacs#8225]
#### Description :octocat:
```
--> installing package: salt-mode@salt... [1/1]
Package salt-mode is unavailable. Is the package name misspelled?
```

#### Reproduction guide :beetle:
- Start Emacs
- Activate the `salt` layer

*Observed behaviour:* :eyes: :broken_heart:

salt-mode is unavailable.

*Expected behaviour:* :heart: :smile:

salt-mode is available.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(osx better-defaults
     (org :variables org-enable-github-support t org-projectile-file "TODOs.org")
     helm
     (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete)
     (shell :variables shell-default-shell 'eshell shell-default-term-shell "/bin/bash" shell-default-height 100 shell-default-position 'full)
     emacs-lisp python javascript typescript clojure sql html yaml markdown docker salt systemd nginx django react
     (version-control :variables version-control-diff-tool 'git-gutter )
     git github spell-checking syntax-checking restclient erc pwalsh)
```
- System configuration features: JPEG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by d12frosted** [comment]
It seems that author of `salt-mode` removed repository, so MELPA has to remove the recipe as well. 

@deybhayden it seems that you was the author of `salt-mode`, could you please help us understand what happened to `slat-mode`? And probably [restore](https://github.com/melpa/melpa/issues/4424) MELPA recipe.

**Comment by d12frosted** [comment]
We could use `https://github.com/emacsmirror/salt-mode` as a temporary mirror (but it's not ideal).

**Comment by d12frosted** [comment]
@pwalsh I am not sure if it works for `master` branch, but on develop you can temporarily place following snippet inside of `dotspacemacs/init` function.

```elisp
(add-to-list 'configuration-layer--elpa-archives
               '("melpa-mirror" . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/aa1d330894df95cdea964040a2f05da1c93967fc/melpa/"))
```

**Comment by pwalsh** [comment]
@d12frosted I prefer to keep on master branch for now. I'll wait a little to see if salt-mode will come back via @deybhayden first.

**Comment by deybhayden** [comment]
I don't see myself as an emacs'r anymore and am not looking to maintain those packages. I'd recommend one of the two of you guys to do the melpa restore based on your own repo. I think you'll need https://github.com/emacsmirror/mmm-jinja2 as well.

**Comment by purcell** [comment]
We (at MELPA) won't use emacsmirror directly if we can avoid it, because if there's no authoritative upstream for a repo there, then it's not a mirror! Preferred option would be if someone who wants to use these packages is happy to adopt them and be the maintainer, which I'm sure would not be a big commitment: MELPA would then be updated to build from that maintained fork. (There are other worse options, which involve more work for @tarsius and myself.)

**Comment by glynnforrest** [comment]
Hi folks, I've decided to step up and maintain these packages. Once the pull requests to melpa get merged this problem will be solved.

@deybhayden I sent you an email to confirm you're okay with this.

**Comment by pwalsh** [comment]
thanks for stepping up @glynnforrest

**Comment by purcell** [comment]
Yes, nice work @glynnforrest, much appreciated.

**Comment by mineo** [comment]
This can probably be closed since `salt-mode` is on MELPA again.
