### ISSUE TITLE
how to make my own key binding

### ISSUE THREAD

**Issue by weikent** [syl20bnr/spacemacs#8229]
Hi, all
thanks for you looking my issue.

when i use spacemacs to edit a c/c++ file, i want to use C-; to run command (yas-expand).

is (global-key-set "\C-;" 'yas-expand)   right?

but i don't know where i can write this command.   i just install spacemace on my mac, and not do any modification. 

please help me!!

thanks.

**Comment by d12frosted** [comment]
Typically such configurations goes to inside of `.spacemacs` file under `dotspacemacs/user-config` function.

But I highly advice you to read [FAQ](http://spacemacs.org/doc/FAQ) and [documentation](http://spacemacs.org/doc/DOCUMENTATION.html) (it's huge, but you can read only topics you are interested in).

**Comment by chrissound** [comment]
@weikent is your issue solved? Do you want to close this issue if so?

**Comment by d12frosted** [comment]
Closing this issue as original question was answered and had no further activity. Let us know if you have any other questions or problems with Spacemacs. Thanks 😸
