### ISSUE TITLE
Weird behavior in web-mode's minor mode

### ISSUE THREAD

**Issue by stormpat** [syl20bnr/spacemacs#823]
When in minor mode, most of the commands work as in the docs, however when wrapping or renaming an element (a basic .html file) some keys wont work as expected.

To reproduce:

Having this html

```html
<div>
  <h1>test</h1>
</div>
```
When trying to rename the ```<h1>test</h1>``` using ```, . r``` to a e.g. ```span``` the output will be ```<san>test</san>``` because the letter p is escaped. Same goes for other keys.

The "workaround" is to press ESC/SPC before typing the new tag. 

Obviously this is not that big of a deal, but i could imagine the same behavior in other minor modes as well, so i decided to report it here.

**Comment by StreakyCobra** [comment]
I can't reproduce this bug anymore, is it still the case for you?

**Comment by stormpat** [comment]
Hi, seems to have been fixed, and works correctly on the current master.
