### ISSUE TITLE
Dot command does not work in visual mode to repeat indent.

### ISSUE THREAD

**Issue by socketwiz** [syl20bnr/spacemacs#8233]
Sorry to post here, I tried to post from with Spacemacs but to submit it said to do `C-c C-c`.  When I do that it says: `C-c C-c is undefined`

<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-c C-c` TO SUBMIT>>
^ thats where it told me to do C-c Cc

#### Description :octocat:
Dot command does not work in visual mode to repeat indent.

#### Reproduction guide :beetle:
- Start Emacs
- Create two lines of text

```
line1
line2
<esc><shift-v> kk > .
```

*Observed behaviour:* :eyes: :broken_heart:
. is undefined

*Expected behaviour:* :heart: :smile:
Indent should repeat each time . is pressed

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml javascript helm emacs-lisp)
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
```

**Comment by chrissound** [comment]
I experience the same issue. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(php elixir markdown html yaml auto-completion emacs-lisp git
     (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "johan-tibell")
     syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by chrissound** [comment]
https://github.com/emacs-evil/evil/issues/626

Seems it's not a Spacemacs issue.

**Comment by wasamasa** [comment]
@chrissound I'm not sure how you get this idea.  I've yet to get a bug report of this with a proper minimal repro that doesn't involve Spacemacs.  The tag is clearly wrong.

**Comment by chrissound** [comment]
Thanks for the info @wasamasa. I've not been able to reproduce this with a new emacs install + evil.

However the issue is also present on prelude.

**Comment by hliebert** [comment]
Same here, I have the same problem and it occurs only when using spacemacs.
