### ISSUE TITLE
Purpose: Unknown filetypes (fundamental mode) have "general" purpose instead of "edit"

### ISSUE THREAD

**Issue by edrex** [syl20bnr/spacemacs#8238]
Buffers for files with unknown type (Fundamental mode) have `general` purpose.

It seems like opening a file with an unknown extension should result in an `edit` purpose, yes?

This results in unexpected behavior when there are two windows, one with general purpose (eg, multiterm) and the other with edit.

**Comment by edrex** [comment]
related https://github.com/syl20bnr/spacemacs/issues/8238

**Comment by edrex** [comment]
I'm able to get the purpose updated to "edit" for protobuf-mode with this init:

```
(add-to-list 'purpose-user-mode-purposes '(protobuf-mode . edit))
(purpose-compile-user-configuration)
```

Why is this needed though? I would have thought that edit would be used as the default for editable buffers.

**Comment by edrex** [comment]
@bmag

**Comment by bmag** [comment]
I disagree. There are many non-edit buffers that also get Fundamental mode, so giving `edit` purpose to Fundamental buffers isn't desired. However, I can add upstream in [window-purpose](https://github.com/bmag/emacs-purpose) another default purpose specifically for file buffers (similar to `default-purpose`) - if you submit a PR I'll willing to merge it (as long as the code is ok). If you're interested, we can continue the discussion upstream.

**Comment by edrex** [comment]
I'm not suggesting that all Fundamental mode buffers have edit purpose, only those which are file buffers. I looked at window purpose source code cursorily but it wasn't obvious to me how to make the change. My elisp is basically at the copy and paste level.

**Comment by bmag** [comment]
Okay. If anyone will submit a PR upstream I will merge it, given that the code is okay.
