### ISSUE TITLE
If .spacemacs is a symlink and is byte-compiled, changes will never be reflected.

### ISSUE THREAD

**Issue by brenns10** [syl20bnr/spacemacs#8239]
#### Description :octocat:
This issue may be really specific to my setup. I have a dotfiles repository
where each dotfile is symlinked into place, including my `.spacemacs`. The
timestamp on a symlink reflects its creation, not when its target was updated.
So, if my `.spacemacs` gets byte compiled, then any updates I make to it will
not update the timestamp of `.spacemacs`, and thus I won't see the changes until
I delete `.spacemacs.elc`.

I'm not sure when `.spacemacs` gets byte-compiled, but you can reproduce it with
the `byte-compile-file` command.

**TLDR:** This can be solved by adding a line to the `.spacemacs` to suppress
byte compilation, so it might be worth adding that to the template.

#### Reproduction guide :beetle:
- Start Emacs
- Run `byte-compile-file` on `~/.spacemacs`
- Open `.spacemacs` and add `(message "in user-config")` to your `user-config`
  function
- Restart Emacs
- Check for a `in user-config` printout in `*Messages*`
- Close Emacs
- `rm .spacemacs.elc`
- Open Emacs
- Check for a `in user-config` printout in `*Messages*`

Try this two times, once when `.spacemacs` is a symlink, once when it is not.

*Observed behaviour:* :eyes: :broken_heart: When `.spacemacs` is a symlink, the
byte-compiled copy is not updated alongside it, and so the output doesn't appear
the first time, but it does once you remove the byte-compiled copy. When
`.spacemacs` is not a symlink, the byte-compiled copy gets updated when you
save, and so the configuration never goes out of date. So, the output appears
both times you check.

*Expected behaviour:* :heart: :smile: Ideally, the byte-compiled copy would be
stored next to the *target* of the link, rather than the link itself, so that
the byte-compiled copy would be updated on save. However, I'm nearly certain
that the details of byte compilation are handled internally and you probably
can't do anything about them. So maybe instead the file should never be
byte-compiled in the first place, by adding `# -*- no-byte-compile: t -*-` to
the top of the `.spacemacs` template (this is how I solved this problem for
myself).

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby gtags erc helm auto-completion emacs-lisp git markdown org
      (c-c   :variables c-c  -enable-clang-support t)
      python yaml latex html javascript gnus
      (go :variables go-tab-width 4)
      spell-checking syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by brenns10** [comment]
Here is the manual page that mentions the no-byte-compile directive: https://www.gnu.org/software/emacs/manual/html_node/elisp/Byte-Compilation.html#Byte-Compilation

**Comment by manofearth** [comment]
Got the same configuration, however didn't have this problem until I initialized git repo in my dotfiles dir. And now I had the same problem
