### ISSUE TITLE
Can't enable shell layer

### ISSUE THREAD

**Issue by amirbilu** [syl20bnr/spacemacs#8240]
Hi all,

I'm relatively new to Emacs.

I'm trying to enable the shell layer by un-commenting the relevant configuration in the dot spacemacs file:
```
 (shell :variables
           shell-default-height 30
           shell-default-position 'bottom)
```

I'm getting the following error while restarting spacemacs:
`error: Required feature 'xterm-color' was not provided`.

What am I doing wrong?

Many thanks.

**Comment by d12frosted** [comment]
Hey, could you please share the output of `SPS h d s`?

**Comment by amirbilu** [comment]
Thanks for the quick answer!

This is the content (shell disabled for now):
```
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql markdown yaml ruby python emacs-lisp javascript react php)
```

**Comment by amirbilu** [comment]
Not sure what was changed. I was just about to debug it and it suddenly worked. Closing the ticket.

**Comment by eedahl** [comment]
I'm having this issue as well and it's not going away.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(javascript helm emacs-lisp git evil-commentary org rust
            (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by syl20bnr** [comment]
Does it happen in develop branch ?

**Comment by eedahl** [comment]
@syl20bnr it eventually worked out somehow but i got other problems, namely if i typed in one command it would execute it but then i couldn't run any more

**Comment by syl20bnr** [comment]
It happens to me too from time to time, I get `Text is read-only`, in this case I restart eshell :-(
