### ISSUE TITLE
helm-projectile-find-file finds the file, but, tries to open in the previous layout path

### ISSUE THREAD

**Issue by danielmt** [syl20bnr/spacemacs#8241]
#### Description :octocat:
After you use SPC f f to open files in one directory, then, use SPC l l to create a new layout, new layouts will reference the directory of the project of the first created layout.

#### Reproduction guide :beetle:
- Start Emacs
- Press SPC f f to open a file in a project foo.
- Press SPC l l to create a layout based on project foo (code/foo/).
- Press SPC f f to open another file, but this time, in project bar (code/bar/).
- Press SPC l l to create a layout based on project bar.
- Now, try to open any file on layout bar with SPC p f and watch as it bases it path around project foo (code/foo/) and ask you to create files or directories.

*Observed behaviour:* :eyes: :broken_heart:
You press SPC p f, and open your file only to find out it tries to open files from project bar (code/bar/) on project foo path (code/foo/), and asks if you want to create the file/directory which doesn't exist.

*Expected behaviour:* :heart: :smile:
You press SPC p f, and open your file correctly, from any isolated layout.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by mahinshaw** [comment]
I have the exact same problem.  I had to roll back to these versions of helm

  helm-20170119.158
  helm-core-20170121.1229

The later versions of helm seemed to be causing the problem.  However, I haven't looked to see if this is a side effect of how spacemacs is using helm.  I will try to dig in more if I can.

**Comment by gabesoft** [comment]
Same problem here. However, `project-find-file` and `projectile-find-file` (invoked with `C-c p f`) both work fine.

**Comment by mahinshaw** [comment]
I think I have narrowed it down to just helm-core where 20170121.1229 works as expected, and 20170122.250 has the aforementioned issue.

**Comment by mahinshaw** [comment]
I am no longer seeing this problem with the latest update of helm

**Comment by danielmt** [comment]
I've downgraded (manually) to helm-core 2.5.0 from melpa stable and it's working again.
Tested this morning against helm-core-20170125.14, gonna recheck soon against latest in melpa (20170125.543)

**Comment by danielmt** [comment]
helm-core 20170125.543 confirmed as fixed.
