### ISSUE TITLE
Go layer tests can result in spacemacs buffer hanging indefinitely.

### ISSUE THREAD

**Issue by GrappigPanda** [syl20bnr/spacemacs#8242]
#### Description :octocat:
Go tests resulting in infinite loops cause Spacemacs tab to hang and must be restarted.

#### Reproduction guide :beetle:
- Start Emacs
- Attempt to test an infintie loop `for {}`
- Watch Spacemacs test handler tab hang indefinitely.

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs go test handling tab will hang while waiting for the go tests to run. There needs to be a `-timeout 10s` or some other simlar option.

*Expected behaviour:* :heart: :smile:
The go test ought to timeout (or be able to time out via a config value). There's no necessary system info, so the following lines will be deleted.

See https://github.com/syl20bnr/spacemacs/pull/8121

**Comment by Miciah** [comment]
@GrappigPanda, since #8121 has been merged, can you confirm that this issue is fixed on the develop branch?

**Comment by GrappigPanda** [comment]
@Miciah, Yes, I can confirm the fix is working. Sorry for forgetting about this issue, and thanks for reminding me of it. Going to mark as closed
