### ISSUE TITLE
LLDB spacemacs

### ISSUE THREAD

**Issue by jkvargas** [syl20bnr/spacemacs#8243]
Hi, I am trying to use LLDB debugger with spacemacs.
Now, I saw this link https://opensource.apple.com/source/lldb/lldb-76/utils/emacs/gud.el.auto.html
And I am wondering, how can I use it together with spacemacs?
Which file do I need to overwrite?

**Comment by yanboyang713** [comment]
did you know how to use LLDB debugger with spacemacs now? I have same issues

**Comment by jkvargas** [comment]
Hey yanboyang713,
No man, I gave up after I considered how much effort I would need to put on this to make it happen.
But if you get anything new regarding this matter please let me know.

**Comment by yanboyang713** [comment]
Hi jkvargas,
ok, if I solve this problem. I will let you know

**Comment by 9527KGG** [comment]
+1
