### ISSUE TITLE
srefactor,c++: problem with generating functions in source-file?

### ISSUE THREAD

**Issue by fth86** [syl20bnr/spacemacs#8247]
Hi, 

I just installed the semantic layer containing srefactor. When I use srefactor for generating a function implementation in a header `test.h`, on the function `test()`, like here:

> class Test
> {
> public:
>   Test()
>   void test(int a);
> }

, I end up with a function definition in `test.cpp` that is missing the Test:: tag before it:

> void test(int a){
> }

Now, srefactor is clearly able to deal with this such a task ( [demos](https://github.com/tuhdo/semantic-refactor/blob/master/srefactor-demos/demos.org)).  Has anyone had this problem before, or has an idea on what is going wrong here?

**Comment by sixshotx** [comment]
Same problem here. My emacs version is 25.1, and uses spacemacs from develop branch.

**Comment by sukeyisme** [comment]
same problem

**Comment by beta1440** [comment]
This looks like an upstream issue. Try reporting it at the [semantic refacter repo](https://github.com/tuhdo/semantic-refactor/issues).
