### ISSUE TITLE
9ac779a breaks updating.

### ISSUE THREAD

**Issue by magthe** [syl20bnr/spacemacs#8249]
#### Description :octocat:
When the change https://github.com/syl20bnr/spacemacs/commit/9ac779a2e4651b58f3e8ac62d02ed740af259a2a is included updating of packages doesn't work.

#### Reproduction guide :beetle:
- Move to the `develop` branch
- Start Emacs
- Attempt to update

*Observed behaviour:* :eyes: :broken_heart:
Error message about network failure (even though network is fully functional) and some source list being `nil`.

*Expected behaviour:* :heart: :smile:
Packages with available updates are updated without errors.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. dcfa0048)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 dash evil-commentary evil-snipe git gtags helm mu4e syntax-checking vim-powerline
 (c-c   :variables c-c  -enable-clang-support t c-c  -enable-irony-support t)
 clojure emacs-lisp python
 (haskell :variables haskell-completion-backend 'company-ghci haskell-enable-hindent-style "johan-tibell")
 dockerfile html latex markdown org pandoc yaml archlinux clipboard-fix)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by magthe** [comment]
The exact message:

    Updating package archives, please wait...
    --> refreshing package archive: spacelpa... [1/1]
    --> Warning: cannot update 186 package(s), possibly due to a temporary network problem: zeal-at-point yasnippet yapfify yaml-mode ws-butler winum window-purpose which-key web-mode volatile-highlights vi-tilde-fringe uuidgen use-package undo-tree toc-org tagedit systemd spaceline smeargle smartparens slim-mode scss-mode sass-mode restart-emacs request rainbow-delimiters pyvenv pytest pyenv-mode py-isort pug-mode projectile powerline popwin popup pkgbuild-mode pip-requirements persp-mode pcre2el paradox pandoc-mode ox-pandoc orgit org-projectile org-present org-pomodoro org-plus-contrib org-download org-bullets open-junk-file neotree mu4e-alert move-text mmm-mode markdown-toc markdown-mode magit-gitflow magit macrostep lorem-ipsum live-py-mode linum-relative link-hint less-css-mode intero info+ indent-guide hydra hy-mode hungry-delete htmlize hlint-refactor hl-todo hindent highlight-parentheses highlight-numbers highlight-indentation hide-comnt help-fns+ helm-themes helm-swoop helm-pydoc helm-purpose helm-projectile helm-mode-manager helm-make helm-hoogle helm-gtags helm-gitignore helm-flx helm-descbinds helm-dash helm-css-scss helm-company helm-c-yasnippet helm-ag helm haskell-snippets haskell-mode haml-mode google-translate golden-ratio gnuplot gitignore-mode gitconfig-mode gitattributes-mode git-timemachine git-messenger git-link git-commit ghc gh-md ggtags flycheck-pos-tip flycheck-haskell flycheck flx-ido fill-column-indicator fancy-battery eyebrowse expand-region exec-path-from-shell evil-visualstar evil-visual-mark-mode evil-tutor evil-surround evil-snipe evil-search-highlight-persist evil-numbers evil-mc evil-matchit evil-magit evil-lisp-state evil-indent-plus evil-iedit-state evil-exchange evil-ediff evil-commentary evil-args evil-anzu evil eval-sexp-fu emmet-mode elisp-slime-nav dumb-jump disaster diminish define-word cython-mode company-web company-statistics company-quickhelp company-ghci company-ghc company-cabal company-c-headers company-auctex company-anaconda company column-enforce-mode cmm-mode cmake-mode clojure-snippets clojure-mode clj-refactor clean-aindent-mode clang-format cider-eval-sexp-fu cider bind-map bind-key avy auto-yasnippet auto-highlight-symbol auto-complete auto-compile auctex-latexmk auctex async anaconda-mode aggressive-indent adaptive-wrap ace-window ace-link ace-jump-helm-line ac-ispell
    --> All packages are up to date.

And in the bottom buffer it says: `Source: nil`.

**Comment by sebhahn** [comment]
I can confirm this issue! Stepping back one commit to dcfa004 helps.

**Comment by d12frosted** [comment]
5be07e9 fixes it. For now 😈
