### ISSUE TITLE
Reloading spacemacs configuration

### ISSUE THREAD

**Issue by ahmadnazir** [syl20bnr/spacemacs#825]
The README suggests that the spacemacs dotfile can be reloaded without having to restart emacs:

```
At anytime you can apply the changes made to the dotfile without restarting Spacemacs by pressing SPC m c c.
```

However, this keybinding doesn't work for me. Can you enlighten me?

**Comment by CestDiego** [comment]
What version of Spacemacs do you have? Be aware that this is only true while you are in your dotfile. Also if you just updated your spacemacs, you have to put this on top of your dotfile

````
;; -*- mode: dotspacemacs -*-
```

in order for it to work

**Comment by ahmadnazir** [comment]
Thanks for the pointer. I updated the spacemacs dotfile and it fixed the problem for me.
