### ISSUE TITLE
C-c C-e keybinding is missing in ag-helm

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#8254]
#### Description :octocat:
`C-c C-e` binding in ag-helm  no longer there

#### Reproduction guide :beetle:
- Start Emacs
- Open a project
- search for a string that expected to have a few occurrences
- in search results press `C-c C-e`

*Observed behaviour:* :eyes: :broken_heart:
The binding no longer exists
`C-z F4` though still available

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 5af909ab)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((org :variables org-enable-reveal-js-support t org-enable-bootstrap-support t org-enable-github-support t :packages
      (not org-present))
 (auto-completion :variables auto-completion-tab-key-behavior 'cycle)
 csv yaml emacs-lisp javascript
 (html :packages
       (not pug-mode slim-mode))
 (markdown :variables markdown-live-preview-engine 'vmd)
 (shell-scripts :packages
                (not fish-mode))
 clojure lua haskell
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 syntax-checking spell-checking helm
 (shell :variables shell-enable-smart-eshell t)
 fasd
 (ibuffer :variables ibuffer-old-time 8)
 osx restclient emoji ranger search-engine imenu-list docker git
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 (github :variables gist-view-gist t)
 ag-dired ag-general ag-dash ag-synonyms ag-org ag-clojure)
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by d12frosted** [comment]
Hey, could it be related to `helm-ag` or `helm` update?

**Comment by dvzubarev** [comment]
I can't reproduce this issue.
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 4361254)
- helm-20170413
- helm-ag-20170209

**Comment by agzam** [comment]
Oh, it's been fixed. @dvzuvarev thanks for reporting.
