### ISSUE TITLE
Improvements to bibtex layer? Add support for Zotero / Mendeley?

### ISSUE THREAD

**Issue by dangom** [syl20bnr/spacemacs#8257]
I'd like to setup a workflow with Spacemacs + Org-ref (via bibtex layer) + Zotero/Mendeley, but I'm having troubles getting the open-pdf functionality to work. 
I tried following instructions from the `org-ref` documentation, and added this to my `user-config`:

```emacs-lisp
(defun my/org-ref-open-pdf-at-point ()
    "Open the pdf for bibtex key under point if it exists."
    (interactive)
    (let* ((results (org-ref-get-bibtex-key-and-file))
           (key (car results))
           (pdf-file (car (bibtex-completion-find-pdf key))))
      (if (file-exists-p pdf-file)
          (org-open-file pdf-file)
        (message "No PDF found for %s" key))))

  (setq org-ref-open-pdf-function 'my/org-ref-open-pdf-at-point)
  (setq bibtex-completion-pdf-open-function 'my/org-ref-open-pdf-at-point)
```

But that doesn't work.

Does anyone have experience with the bibtex layer and or uses it consistently for citations with Mendeley / Zotero?

I'd be happy to contribute to the documentation if I could get that to work for myself.

**Comment by jellelicht** [comment]
@dangom , could you elaborate a bit on your workflow? I am trying to get this to work nicely as well, so maybe we can coordinate our efforts.

**Comment by dangom** [comment]
Currently I'm using Mendeley and sorting papers within per-project folders. I have Mendeley organize all my files in `~/Papers/MendeleyDesktop`, and create one BibTeX file per project in `~/Papers/bibtex`.

I load the org, latex, bibtex and pdf-tools layers from Spacemacs, and in my `dotspacemacs/user-config` I have the following somewhere:
```
  (with-eval-after-load 'org-ref
    (setq org-ref-default-bibliography '("~/org/library.bib")
          org-ref-pdf-directory "~/Papers/MendeleyDesktop/"
          org-ref-open-pdf-function 'org-ref-get-mendeley-filename
          org-latex-prefer-user-labels t
          org-ref-default-citation-link "parencite"
          bibtex-dialect 'biblatex))
```
Though 'org-ref-get-mendeley-filename also never worked properly (same problems as my solution in the previous comment). Neither get Mendeley's filenames correctly. 
I haven't invested much time into making it work, since `pdf-tools` wasn't compiling on my work machine anyway. 

On the org-mode side of things I add my bibresource with `#+latex_header: \addbibresource{~/Papers/bibtex/whatever-project.bib}`, and include it with:

```
#+BEGIN_EXPORT latex
\printbibliography
#+END_EXPORT
```

Org-ref automatically parses the bibresouce and the `C-c ]` functionality works like a charm. 

I'd love to get the pdf-functionality working at some point, so I look forward to hearing about your workflow as well.

**Comment by Isimoro** [comment]
For the function in you first comment to work you need to set `bibtex-completion-pdf-field` to the name of the Bibtex field in which the path to the PDF files is stored.
For Zotero(4 with better-biblatex) that would be `(setq bibtex-completion-pdf-field "file")`.
