### ISSUE TITLE
syncing configuration layers, shows: Symbol's function definition is void: toc-org-enable

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#8258]
#### Description :octocat:
<kbd>SPC f e R</kbd> doesn't sync the configuration layers, Emacs has to be restarted to reload them.

#### Reproduction guide :beetle:
- Start Emacs
- Press <kbd>SPC f e R</kbd>

*Observed behaviour:* :eyes: :broken_heart:
The configuration layers doesn't get synced, and the messages buffer shows: 
`run-hooks: Symbol’s function definition is void: toc-org-enable`.

*Expected behaviour:* :heart: :smile:
The configuration layers should get synced, without having to restart Emacs.

#### Tested
After uncommenting `org` in the configuration layers section of `.spacemace`, and restarting Emacs. When the `org` packages have been loaded, and one presses <kbd>SPC f e R</kbd>, then the messages buffer shows:
`org-element--set-regexps: Symbol’s function definition is void: org-link-types`.

After restarting Emacs again and the <kbd>SPC f e R</kbd> key binding is pressed, then the initial message returns:
`run-hooks: Symbol’s function definition is void: toc-org-enable`
but the layers still aren't getting synced.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. b3c8ebc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((markdown :variables markdown-live-preview-engine 'vmd)
 auto-completion emacs-lisp git helm html markdown org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by ffloyd** [comment]
+1

Same issue. Clean setup. Both ivy or helm ways are broken in described way.

But installation of new packages via restarting emacs works. After I've added following packages:

```lisp
   dotspacemacs-configuration-layers
   '(
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     helm
     auto-completion
     ;; better-defaults
     emacs-lisp
     git
     markdown
     org
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     ;; spell-checking
     ;; syntax-checking
     version-control
     )
```

command `SPC f e R` starts to work normal. At least, it able to install `elixir` and `themes-megapack` layer.

**Comment by snosov1** [comment]
For myself, I don't seem to be able to reproduce this. I've got `org-element--set-regexps: Symbol’s function definition is void: org-link-types.` once, but never the `toc-org-enable` fail. Now, the `org-link-types` thing also disappeared - not sure what I did, but it doesn't seem to occur anymore.

**Comment by duianto** [comment]
I tried it in the master branch and the same message appears there:
`run-hooks: Symbol’s function definition is void: toc-org-enable`
so it's not related to just the develop branch.

Back in the develop branch i tried adding toc-org as an excluded package: 
`   dotspacemacs-excluded-packages '(toc-org)` and after restarting emacs, then <kbd>SPC f e R</kbd> re-syncs the layers again.

**Comment by duianto** [comment]
hmm, now that i removed toc-org as an excluded package and restarted emacs, then the toc-org package was downloaded, and the messages buffer showed these messages:
```
Problems while trying to load feature ‘org-w3m’
Problems while trying to load feature ‘org-bbdb’
Problems while trying to load feature ‘org-bibtex’
Problems while trying to load feature ‘org-docview’
Problems while trying to load feature ‘org-gnus’
Problems while trying to load feature ‘org-info’
Problems while trying to load feature ‘org-irc’
Problems while trying to load feature ‘org-mhe’
Problems while trying to load feature ‘org-rmail’
```

and when i pressed <kbd>SPC f e R</kbd> then this message was shown:
`org-element--set-regexps: Symbol’s function definition is void: org-link-types`

After restarting emacs again, now it seems to work without the `...void: toc-org-enable` message appearing and the layers are re-synced.

Could it have been that a previous version of the toc-org package, or maybe just the old compiled files remained when the package was updated a couple of days ago?

**Comment by snosov1** [comment]
Well, I guess it could, but I don't know how it could break things =)

The recent change was nothing more than moving the tests into a separate file. As far as MELPA package is concerned - it was simple removal of some non-functional lines in the `toc-org.el` file. If I look at the downloaded package - it's still a single `.el` file with its compiled counterpart (the file with tests is ignored by MELPA).

So, yeah, the things you see are kind of odd and I'm not sure what code is to blame =)

**Comment by duianto** [comment]
It seems to be working now, so ill close this, but thanks for taking a look.
