### ISSUE TITLE
test if resources (links, etc.) are correct? | contribute link on spacemacs.org --> 404

### ISSUE THREAD

**Issue by toogley** [syl20bnr/spacemacs#8260]
Hey.

* on spacemacs.org, there's a [CONTRIBUTE](http://spacemacs.org/doc/CONTRIBUTE.html) Link - which is dead.
* Maybe automatic travis tests for html errors using [html-proofer](https://github.com/gjtorikian/html-proofer) could prevent that, or at least get attention for a fix in the future?

**Comment by duianto** [comment]
There's no CONTRIBUTE.html file in the https://github.com/syl20bnr/spacemacs.org/tree/gh-pages/doc folder, there is however a file called CONTRIBUTING.org in https://github.com/syl20bnr/spacemacs
If i have understood it correctly, then the `.html` files are generated from the `.org` files.

It sounds like a good idea to automatically check for html errors.

**Comment by duianto** [comment]
This issue:
CONTRIBUTE link on homepage broken #8290
has a PR for the broken contribute link.
