### ISSUE TITLE
Cannot jump to file when switching projects.

### ISSUE THREAD

**Issue by stormpat** [syl20bnr/spacemacs#8267]
#### Description :octocat:
When using ```SPC p p``` to switch projects (with projectile) Emacs first prompts what project to select.
Then Emacs prompts for what file to open/edit.
After selecting a new file to edit/open in the other project Emacs prompts me if i want to save the
file in the project i currently am working on.

#### Reproduction guide :beetle:
- Start Emacs
- Go a projectile project
- Toggle project list ```SPC p p```
- Select another project
- Select to file you want to open
- Press ENTER

*Observed behaviour:* :eyes: :broken_heart:
- Now Emacs prompts me if i want to save the selected file in the same project i was in.

*Expected behaviour:* :heart: :smile:
- I would assume i jump to the new file i want to work with.

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.50.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 better-defaults html evil-snipe php elm
 (gtags :variables gtags-enable-by-default t)
 javascript org deft react
 (elixir :variables elixir-enable-compilation-checking t)
 emacs-lisp git syntax-checking version-control)
```
- System configuration features: JPEG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by deathmaz** [comment]
Try to update you packages, the issue was fixed a few days ago

**Comment by stormpat** [comment]
@deathmaz  thanks for pointing out the roots of the cause.
