### ISSUE TITLE
Markdown mmm-mode integration impacts other modes, e.g. magit

### ISSUE THREAD

**Issue by itamarst** [syl20bnr/spacemacs#8268]
#### Description :octocat:
markdown/mmm-init-mode sets mmm-global-mode to 't. This breaks magit's color display.

#### Reproduction guide :beetle:
- Start Emacs
- Open markdown document. Run M-x markdown/mmm-init-mode (or I suspect 'M-m m c s').
- Open git repo in magit. notice colors are weird on diffs and the like.

*Observed behaviour:* :eyes: :broken_heart:

Magit diffs no  longer have the right colors and faces.

*Expected behaviour:* :heart: :smile:

Magit should be unaffected by markdown mode!

*How to fix it*:

Instead of setting mmm-global-mode to true, setting it to `'maybe` does the right thing - enables it in markdown mode but not in magit mode.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion better-defaults emacs-lisp git markdown
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     (spell-checking :variables spell-checking-enable-by-default nil)
     (syntax-checking :variables syntax-checking-enable-tooltips nil)
     version-control python javascript yaml react shell-scripts go c-c   html org semantic imenu-list)
```

#### Backtrace :paw_prints:
```
```

**Comment by itamarst** [comment]
Happy to submit PR with fix.

**Comment by agzam** [comment]
related #8967

**Comment by itamarst** [comment]
I believe in `develop` branch mmm-mode is just disabled (see commit above), but proposed `'maybe` would keep it enabled and therefore might still cause issues in #8967.
