### ISSUE TITLE
Update bitbucket evil urls to github evil urls

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#8273]
### Summary
Since the https://bitbucket.org/lyro/evil/wiki/Home project has migrated to 
https://github.com/emacs-evil/evil

Then any url that links to bitbucket issues/files need to be updated to point to the equivalent issues/files on github. Because the issues section seems to have been removed from the bitbucket evil repository, and the links to issues, are redirected to the bitbucket sign in page. And links to bitbucket evil src files are going to become outdated over time.

I found 3 urls to the bitbucket.org/lyro/evil repository, by performing these steps:
- Start Emacs 
- Open the `.emacs.d` folder with `helm-find-files` <kbd>SPC f f</kbd>
- In the HELM Find Files panel, press <kbd>~/</kbd> to navigate to the home folder
- Type `emacs` to narrow the results
- Choose the `.emacs.d` entry and press <kbd>RET</kbd>
- Search for `https bitbucket` with `spacemacs/helm-project-smart-do-search` <kbd>SPC /</kbd>

### Url 1
https://github.com/syl20bnr/spacemacs/blob/develop/layers/+distributions/spacemacs-bootstrap/packages.el#L82
>   ;; put back refresh of the cursor on post-command-hook see status of:
>   ;; https://bitbucket.org/lyro/evil/issue/502/cursor-is-not-refreshed-in-some-cases
>   ;; (add-hook 'post-command-hook 'evil-refresh-cursor)

#### Github link
This seems to be the github link to the same issue:
https://github.com/emacs-evil/evil/issues/502

### Url 2
https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Btools/finance/packages.el#L55
>       ;; temporary hack to work-around an issue with evil-define-key
>       ;; more info: https://bitbucket.org/lyro/evil/issues/301/evil-define-key-for-minor-mode-does-not
>       ;; TODO remove this hack if the limitation is removed upstream

#### Github link
This is probably the same github link issue:
https://github.com/emacs-evil/evil/issues/301

### Url 3
https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bdistributions/spacemacs-base/local/hybrid-mode/hybrid-mode.el#L109
> ;; This code is from evil insert state definition, any change upstream
> ;; should be reflected here
> ;; see https://bitbucket.org/lyro/evil/src/a25b848c90c7942fe89d9ec283c6bb44fb7b3cf4/evil-states.el?fileviewer=file-view-default#evil-states.el-74

#### Github link
This seems to be the link to the equivalent file on github:
https://github.com/emacs-evil/evil/blob/master/evil-states.el#L108

#### Question
The previous link points to a specific commit of the `evil-states.el` file. But the file has changed since that version. 

Is it fine to link to the most recent github version (linked above), or should the link point to the same commit version of the file on github, if that's possible.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. b3c8ebc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((markdown :variables markdown-live-preview-engine 'vmd)
 auto-completion emacs-lisp git helm html markdown org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by d12frosted** [comment]
> Is it fine to link to the most recent github version (linked above), or should the link point to the same commit version of the file on github, if that's possible.

Totally ok. At least, in my opinion.

PR is welcome 😸
