### ISSUE TITLE
PHP syntax doesn't works

### ISSUE THREAD

**Issue by artukrap** [syl20bnr/spacemacs#8274]
#### Description :octocat:
PHP syntax doesn't work

#### Reproduction guide :beetle:
- Start Emacs
- Install php layer
- Restart spacemacs
- Open `.php` and receive this error `byte-code: Recursive load: "/home/krapans/.emacs.d/elpa/php-mode-20170126.2227/php-mode.elc", "/home/krapans/.emacs.d/elpa/php-mode-20170126.2227/php-mode.elc", "/home/krapans/.emacs.d/elpa/php-mode-20170126.2227/php-mode.elc", "/home/krapans/.emacs.d/elpa/php-mode-20170126.2227/php-mode.elc", "/home/krapans/.emacs.d/elpa/php-mode-20170126.2227/php-mode.elc"
`

*Observed behaviour:* :eyes: :broken_heart:
No syntax highlighting

*Expected behaviour:* :heart: :smile:
PHP syntax highlighting

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 970acdd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(php helm auto-completion better-defaults emacs-lisp git markdown org
     (shell :variables shell-default-shell 'eshell)
     spell-checking syntax-checking version-control elixir javascript html ruby ruby-on-rails themes-megapack yaml php)
```

**Comment by rakyi** [comment]
Happened to me some time ago on master. Removing PHP related packages from `emacs.d/elpa/` solved it.

**Comment by artukrap** [comment]
@rakyi Yes, this helped. However, at least I think so, this is still a bug, because it happened and crashed somehow..

**Comment by artukrap** [comment]
@rakyi After restart same issue happened btw

**Comment by artukrap** [comment]
Example how it looks
![screenshot from 2017-01-31 12-12-01](https://cloud.githubusercontent.com/assets/11750685/22460672/a1c2e30c-e7ae-11e6-90c6-5eae553f3f10.png)

**Comment by artukrap** [comment]
@d12frosted Just pulled in 1. Feb update from spacemacs/develop and php-mode/master and now it works. Dunno though which commit fixed that.

**Comment by artukrap** [comment]
Sorry, just restarted spacemacs and bug again is there...

**Comment by d12frosted** [comment]
Shame to hear. Actually this looks like an upstream bug. Would be nice of you to report this.

**Comment by d12frosted** [comment]
Oh, actually it is already [reported][1]. 

  [1]: https://github.com/ejmr/php-mode/issues/269

**Comment by artukrap** [comment]
@d12frosted When its upstream bug, we close this or no?

**Comment by d12frosted** [comment]
Usually we keep the issue open until upstream issue is closed. Sometimes we close issue sooner (e. h. in cases when upstream is not interested in fixing this issue).

**Comment by artukrap** [comment]
Fixed issue with this:

1. https://github.com/ejmr/php-mode/issues/269#issuecomment-279118339
2. https://github.com/ejmr/php-mode/issues/269#issuecomment-279353268
