### ISSUE TITLE
Full configuration not loaded at startup

### ISSUE THREAD

**Issue by rschuetzler** [syl20bnr/spacemacs#8275]
#### Description :octocat:
Full configuration not loading on startup

#### Reproduction guide :beetle:
- Start Emacs
- Wait for Spacemacs to finish loading
- Note that at least the user-config font is not chosen
- Run `<SPC> f e R` to reload configuration
- Proper font is now used

*Observed behaviour:* :eyes: :broken_heart:
Configured font not selected during initial startup, but is once `dotspacemacs/sync-configuration-` is run

*Expected behaviour:* :heart: :smile:
Proper font should be loaded on first startup.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby auto-completion emacs-lisp git markdown org ess asciidoc python html react latex bibtex
      (rcirc :variables rcirc-enable-znc-support t)
      syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

Screen recording of startup behavior available here: https://webmshare.com/play/ZX45X

**Comment by d12frosted** [comment]
> Note that at least the user-config font is not chosen

What do you mean? Are you talking about `dotspacemacs-default-font` value that is being set in `dotspacemacs/init` function?

P. S. I can't play the video. It just doesn't start :(

**Comment by rschuetzler** [comment]
I'm setting the font in `dotspacemacs/user-config` with `set-face-attribute` because I use a different font depending on the OS, but I use the same configuration across OSes. On Windows I use Consolas, and on others I use Source Code Pro. Is there a good way to change the fonts by OS in `dotspacemacs/init`?

**Comment by d12frosted** [comment]
There might be some conflict with theme you are using. What about using `theming` layer? It's not ideal solution, but at least something I can offer 😸 

P. S. AFAIK, you can use `t` instead of theme name in the `theming` configuration so it is applied to all themes.

**Comment by rschuetzler** [comment]
Hmm, I hadn't thought of Theme issues, but it definitely looks related. Loading in, it looks like the default font is set to Source Code Pro. When I run `<SPC> f e R` I get Consolas like I'm supposed to. But switching themes puts me back to Source Code Pro.

**Comment by rschuetzler** [comment]
Here's the relevant config file stuff, if that helps:

In `dotspacemacs/init`

   ```
dotspacemacs-default-font '("Source Code Pro"
                               :size 13
                               :weight normal
                               :width normal
                               :powerline-scale 1.1)
```

And in `dotspacemacs/user-config`:

```
  (cond ((or (eq 'ms-dos system-type) (eq 'windows-nt system-type))
         (message "Customizing for Windows")
         (set-face-attribute 'default nil :family "Consolas")
         (set-face-attribute 'default nil :height 125)
         )
        ((eq 'darwin system-type)
         (message "Customizing for Mac")
         (setq-default dotspacemacs-default-font '("Source Code Pro"
                                     :size 12
                                     :weight normal
                                     :width normal
                                     :powerline-scale 1.1))
         )
        )
```

**Comment by rschuetzler** [comment]
I've tried setting it with a barebones `.spacemacs` starting from scratch. The following lines in my `dotspacemacs/init` do nothing to change the font:

```
   dotspacemacs-default-font '("Consolas"
                               :size 15
                               :weight normal
                               :width normal
                               :powerline-scale 1.1)
```

**Comment by d12frosted** [comment]
What theme do you use?

> The following lines in my dotspacemacs/init do nothing to change the font

Hm... setting to anything else works for me. Do you have `Consolas` on that machine? Silly question, I know, but want to make sure 😸

**Comment by rschuetzler** [comment]
It looks like I was wrong about it not working from a barebones configuration. That works just fine. The issue is only with the way I'm setting it to Consolas just for Windows machines, it appears. I've tried settings `dotspacemacs-default-font` inside my `user-config`, but that doesn't seem to work.

**Comment by d12frosted** [comment]
> I've tried settings dotspacemacs-default-font inside my user-config, but that doesn't seem to work.

`dotspacemacs-default-font` must be set inside of `dotspacemacs/init` function. Setting it inside of `user-config` function doesn't make much sense. 

---

I just realised that you can use following snippet.

```elisp
(setq-default dotspacemacs-default-font
              `(,(cond
                 ((or (eq 'ms-dos system-type) (eq 'windows-nt system-type)) "Consolas")
                 ((eq 'darwin system-type) "Source Code Pro")
                 (t "Source Code Pro"))
                :size 10
                :weight normal
                :width normal
                :powerline-scale 1.0))
```

**Comment by rschuetzler** [comment]
That works beautifully. I'm not not super good with elisp, but is there a way to change the font size by OS, too?
