### ISSUE TITLE
Error (bytecomp): Required feature ‘paredit’ was not provided

### ISSUE THREAD

**Issue by mattyulrich** [syl20bnr/spacemacs#8278]
When trying to install clj-refactor on startup and use cider (cider-connect), I see this error.

I've tried refreshing/uninstalling/installing all associated packages (paredit, cider, clj-refactor, etc) to no avail:

Windows 7 GNU Emacs 25.1.1 (x86_64-w64-mingw64) of 2016-09-21
Spacemacs 0.200.7

Any thoughts?

**Comment by mattyulrich** [comment]
In an effort to try again - I reinstalled spacemacs and added clojure to the dotspacemacs-configuration-layers and still see the same problem.

Is there some kind of log file that I can provide to try and debug this?

**Comment by noncom** [comment]
I've had this issue too. See the `Bugfix` section on this page: https://ejelome.com/install-and-setup-clj-cljs-development-environment/ it helped me.

And I'll just cite the solution it proposes here (note that both `paredit.el` and `paredit.elc` have to be removed):

     $ \
     cd ~/.emacs.d/elpa/paredit*                       # move to paredit directory  
     rm paredit.el*                                    # remove existing paredit.el*  
     wget http://mumble.net/~campbell/emacs/paredit.el # download original paredit.el*  

and restart Emacs after this.
