### ISSUE TITLE
question: bind-map vs general.el

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#8279]
Hi, just curious about what were the reasons that led the team to choose @justbur's  [bind-map](https://github.com/justbur/emacs-bind-map) over @noctuid's  [general.el](https://github.com/noctuid/general.el). I use bind-map myself but am studying noctuid's package and seems that it has more features.

**Comment by justbur** [comment]
It's actually very simple I don't think general was around when I wrote bind-map

**Comment by sooheon** [comment]
Yeah general.el came along later, pretty recently. general is now very featured and useful, and it's even supported in use-package under the :general keyword.

**Comment by ninrod** [comment]
All right, thanks gentleman!
