### ISSUE TITLE
Error (bytecomp): Symbol’s function definition is void: org-link-set-parameters when org-mode is enabled

### ISSUE THREAD

**Issue by pushkarajthorat** [syl20bnr/spacemacs#8282]
#### Description :octocat:
Error (bytecomp): Symbol’s function definition is void: org-link-set-parameters when org-mode is enabled

#### Reproduction guide :beetle:
- Start Emacs
I am new to emacs-orgmode and spacemacs overall. I enabled orgmode in .spacemacs dotspacemacs-configuration-layers and restarted emacs.

This started fetching orgmode packages from elpa, which failed with below errors:
orgmdoe pa

# grep -i error /tmp/log.txt 
Error (bytecomp): Symbol’s function definition is void: org-link-set-parameters
Error (bytecomp): Symbol’s function definition is void: org-link-set-parameters
Error (bytecomp): Symbol’s function definition is void: org-link-set-parameters
Error (bytecomp): Symbol’s function definition is void: org-link-types [2 times]
Error (bytecomp): Symbol’s function definition is void: org-link-types
    org-src-coderef-format, org-src-coderef-regexp, org-define-error,
Error (bytecomp): Symbol’s function definition is void: org-link-types [2 times]
Error (bytecomp): Symbol’s function definition is void: org-link-types [19 times]

Probably these packages are removed from elpa, I am wondering how will I install these packages in spacemacs.

*Observed behaviour:* :eyes: :broken_heart:
Logs pasted above.

*Expected behaviour:* :heart: :smile:
orgmode should be installed and enabled

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XWIDGETS

#### Backtrace :paw_prints:

Log - http://pastebin.com/1GgFULLS
```
```

**Comment by d12frosted** [comment]
Thanks for hiding log into pastebin 😸 

Regarding your problem, can't try to reproduce it right now. Probably someone else has any ideas? 😸

**Comment by d12frosted** [comment]
BTW, try to restart to see if it works 😸

**Comment by pushkarajthorat** [comment]
I tried restart spacemacs, no visible error as such, but I cannot see the agenda for my org files.

**Comment by pushkarajthorat** [comment]
I am able to use org-agenda with by following steps - http://emacs.stackexchange.com/questions/19386/configuring-org-mode-within-spacemacs. The org-agenda is working fine, but not sure what is failing due to this error.

**Comment by d12frosted** [comment]
If it doesn't repeat, it should be ok :smile_cat:

**Comment by pushkarajthorat** [comment]
Hi.. I am able to use the spacemacs now, not sure what functionality is affected, sure I am not using it ;-)

closing.

**Comment by nixmaniack** [comment]
Well you've figured from stackoverflow but it's already mentioned in FAQ. Check [here](http://develop.spacemacs.org/doc/FAQ.html#why-do-some-of-my-org-related-settings-cause-problems).

Nonetheless the problems could be 
1. you're configuring/using org-mode much before spacemacs sets up newer correct `org-mode` (version 9)
2. you're using some newer org packages which are using new `org-link-set-parameters` over the current obsolete function `org-add-link-type`

Correct way to avoid these errors would have been with some guard:
```elisp
(if (fboundp 'org-link-set-parameters)
    (org-link-set-parameters "xyz" ...)
  (org-add-link-type "xyz" '...))
```

Once you have taken care of what's mentioned in FAQ you can try following:
1. delete the byte compiled files 
`$ find ~/.emacs.d/elpa -name '*.elc' -delete`
2. Upgrade packages from spacemacs home buffer
3. Restart emacs (`SPC q r`)and check
