### ISSUE TITLE
Remove local copy of gorename from the go layer

### ISSUE THREAD

**Issue by harikb** [syl20bnr/spacemacs#8284]
Go layer is using a broken/obsolete local copy of gorename
```
diff --git a/layers/+lang/go/packages.el b/layers/+lang/go/packages.el
index bb32f88..c04f0ea 100644
--- a/layers/+lang/go/packages.el
+++ b/layers/+lang/go/packages.el
@@ -11,7 +11,7 @@
         go-eldoc
         go-mode
         go-guru
-        (go-rename :location local)
+        go-rename
         ))

```

**Comment by d12frosted** [comment]
> broken/obsolete

What do you mean?

**Comment by d12frosted** [comment]
Ah it seems that this package is [available on MELPA](https://melpa.org/#/go-rename). Is this what you meant?

**Comment by harikb** [comment]
Sorry I didn't see the question earlier, but the included copy referred to methods like 'go--position-bytes' which doesn't exist. So go-rename functionality was broken. The new code seems to work.

**Comment by syl20bnr** [comment]
Thank you ! 👍 
Cherry-picked into develop branch, you can safely delete your branch.
