### ISSUE TITLE
CONTRIBUTE link on homepage broken

### ISSUE THREAD

**Issue by trosel** [syl20bnr/spacemacs#8290]
http://spacemacs.org/doc/CONTRIBUTE.html

**Comment by smile13241324** [comment]
Same for http://develop.spacemacs.org/doc/CONTRIBUTE.html

**Comment by smile13241324** [comment]
Thanks for reporting, I have added a fix to the publishing mechanism which should solve the issue.

**Comment by smile13241324** [comment]
Link to related PR: #8468
