### ISSUE TITLE
Having problems getting tern to work properly

### ISSUE THREAD

**Issue by socketwiz** [syl20bnr/spacemacs#8296]
#### Description :octocat:
Brand new Spacemacs user here. I've been using it for a week or two.  I'm a long time vim user.  I'm really enjoying this new environment.  I've had a few small issues that I've been either able to deal with, fix, or work-around.  However this one seems to have defeated me.  I've tried the best I can to figure this out on my own including countless google searches.  If there is anything at all that I've missed I'd be happy to give it a try.  Any help is truly appreciated.  Here is my current .spacemacs configuration: https://github.com/socketwiz/dotfiles/blob/master/.spacemacs

No matter what I try I am unable to get tern to work properly.  I've followed all of the instructions on this page: https://github.com/syl20bnr/spacemacs/tree/master/layers/+lang/javascript but now matter what, I'm unable to get most of the key-bindings to work that are listed here https://github.com/syl20bnr/spacemacs/tree/master/layers/+lang/javascript#auto-complete-and-documentation-tern to work.  The exception seems to be with:

`SPC m g g` because I don't think its using tern for that, I think its fallen back to https://github.com/jacktasia/dumb-jump because that started working once I installed ack.  It was giving me some error about no available jump handler or something.
`SPC m C-g` does properly bring me back when `SPC m g g` takes me some where.

However `SPC m g G` does not work.  I would think it would behave exactly the same as `SPC m g g` once you type the keyword in but it only produces an error:

> Request failed: ((error http 400) . TypeError: Cannot read property 'ast' of undefined)

When I initially started looking into the problem, I didn't have tern installed properly.  I don't think that is the case any longer, tern is indeed running now.  When I do `SPC a p` to list processes I can see anywhere between 1-3 instances of it running.  Currently there are two:
```
Tern            run     --              /dev/ttys001 tern --no-port-file --strip-crs
Tern<1>         run     --              /dev/ttys005 tern --no-port-file --strip-crs
```
I've tried both a .tern-project and a ~/.tern-config.  I've tried various combinations of settings but I currently have the following .tern-config in my $HOME directory:
```json
{
    "ecmaVersion": 6,
    "libs": [
        "browser",
        "underscore",
        "chai"
    ],
    "dontLoad": [
        "node_modules/**"
    ],
    "plugins": {
        "complete_strings": {
            "maxLength": 15
        },
        "node": {},
        "doc_comment": {
            "fullDocs": true,
            "strong": true
        }
    }
}
```
I've tried no .tern-project or .tern-config at all.  When I have no .tern-project or .tern-config I don't seem to get the http 400 error listed above.

`SPC m h d` doesn't seem to do anything.  But to be honest, I'm not exactly sure what it is supposed to do.  It doesn't display any sort of popup around the cursor, it doesn't display anything below the status line at the bottom of the buffer, it doesn't throw an error into the messages buffer, it just does absolutely nothing.

`SPC m h t` behaves exactly like `SPC m h d`, it does nothing at all.

`SPC m r r V` behaves exactly like the previous two, it does nothing at all.

I've tried following this guide: https://github.com/syl20bnr/spacemacs/wiki/Debugging hoping I could figure this out myself but with no luck.  I enabled debug mode but no backtrace buffer is generated at any time.

#### Reproduction guide :beetle:
- Start Emacs
1) git clone git@github.com:socketwiz/react-starter.git
2) Open the file server/index.js
3) `SPC m g G`
4) Type the word hot (defined on line 31)

*Observed behaviour:* :eyes: :broken_heart:
Throws the following error below the status line and in the messages buffer:

> Request failed: ((error http 400) . TypeError: Cannot read property 'ast' of undefined)

*Expected behaviour:* :heart: :smile:
Jump to line 31

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html javascript markdown react yaml helm emacs-lisp git org spell-checking syntax-checking)
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
```

**Comment by rangelke** [comment]
I seem to be having issues with tern as well. Not sure if they are related or not, but some of the commands don't work and the code completion which should be provided when using a tern server does not work. 
Checking out what tern should do: http://ternjs.net/doc/demo/index.html#simple, tern simple does not do any of those, at least not automatically, which really bothers me at the moment. At the moment I'm just creating .ts files and write plain Javascript since the typescript-server does work properly. 

On some occasions I also get a tern binary not found, but the warning does show up everytime. Seems to be random at the moment.

**Comment by rangelke** [comment]
@socketwiz 
Did you find a solution to problem by accident? 
I just started using Visual Studio Code out of misery, because I get Javascript auto-completion, just like how tern.js is supposed to work. 

I really think there is something wrong with the Javascript layer, because the Typescript layer works as I would expect to with good auto-completion.
