### ISSUE TITLE
w/b/e always moves between subwords 

### ISSUE THREAD

**Issue by sergei-dyshel** [syl20bnr/spacemacs#8298]
#### Description :octocat:
w/b/e always moves between subwords 

#### Reproduction guide :beetle:
- Start Emacs
- Open some file.
- Try moving between words with w/b/e.

*Observed behaviour:* :eyes: :broken_heart:
Cursor moves between subwords

*Expected behaviour:* :heart: :smile:
Cursor should move between words, unless
subword-mode toggled (with SPC t c).

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 7d75e65)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XWIDGETS

**Comment by sergei-dyshel** [comment]
Can anybody confirm this bug?

**Comment by duianto** [comment]
Could provide some examples of words with subwords, and where the cursor should and shouldn't stop, both with and without subword-mode enabled. That would make sure that everyone is testing the same thing.

**Comment by sdwolf** [comment]
You probably need the following line added inside your `dotspacemacs/user-config` function from the `~/.spacemacs` file:

```emacs-lisp
(defalias 'forward-evil-word 'forward-evil-symbol)
```

**Comment by sergei-dyshel** [comment]
Apparently definition of word is different in Emacs and Vim hence the different behavior of w/b/e:
In Emacs and `_` and `-` are considered word separators but in Vim they are not. 

So my my problem is actually to have both symbol (including separators) and (sub)word (not including separators and also CamelCase as separate words) motions defined as separate functions, so that I can assign different keys to them. 

In Vim there is plugin [CamelCaseMotion](https://github.com/bkad/CamelCaseMotion) for that. AFAIU The alias by @sdwolf is not proper solution since it aliases one motion to another. So far I've only came with this:
```lisp
  (evil-define-motion evil-forward-symbol-begin (count)
    :type exclusive
    (let
        ((temp-table (make-syntax-table (syntax-table))))
      (with-syntax-table temp-table
        (modify-syntax-entry ?- "w")
        (modify-syntax-entry ?_ "w")
        (evil-forward-word-begin count))))
```

I'd also like to get some advice whether I should modify this issue, open a new one  or leave this discussion as is.

**Comment by duianto** [comment]
In both Emacs + Evil and Vim, the key binding <kbd>S-w</kbd> (uppercase W) jumps over WORDS, like 
`hyphen-separated-words` and `underscore_separated_words`, so if you turn on `camel-case-motion` <kbd>SPC t c</kbd> then you can stop at subWords, hyphens or underscores by pressing <kbd>w</kbd> and jump over them with <kbd>S-w</kbd>. Maybe that's what your looking for?

**Comment by sergei-dyshel** [comment]
@duianto 
That's not correct. WORD is sequence of non-blank characters separated with whitespace. So when you're editing a line such as
```
a=some_namespace::some_class.some_member(some_argument);
```
`W` will jump over the entire line.

The idea is to have different keybindings for WORD, symbol and (sub)word motion, which makes short-term navigation very effective.

**Comment by duianto** [comment]
That example makes it much easier to see what you mean. 👍 

sdwolfs suggestion shows the `forward-evil-symbol` command. It seems to work almost the same way as <kbd>w</kbd> in Vim, with the exception that `forward-evil-symbol` sees `a=some_namespace` as a symbol, and jumps over it. 

In Vim with the cursor on the first `a`, <kbd>w</kbd> stops at the `=` and the first `s`.

**Comment by sergei-dyshel** [comment]
Actually found previous issues with the same complaint: #1261, #1248. Closing this as a dup.
