### ISSUE TITLE
spacemacs/helm-project-smart-do-search completely ignores helm-ag-use-grep-ignore-list

### ISSUE THREAD

**Issue by danielmt** [syl20bnr/spacemacs#8299]
#### Description :octocat:
`SPC /` uses helm-ag for searching, however, ignores its options, searching large ignored directories anyway with `grep-find-ignored-directories` and `helm-ag-use-grep-ignore-list`, making it pretty much useless to me.

Using watch|grep to find how it's launching `ag`, it only uses `--nocolor --nogroup` options.
Using `SPC SPC` and calling `helm-ag` directly works as intended.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC f f` and open any file inside a directory with a large ignored directory (set on `grep-find-ignored-directories`)
- `SPC /` and search anything that would match one or more files in said ignored directory

*Observed behaviour:* :eyes: :broken_heart:
It hangs searching the large ignored directory, and presents loads of matches.

*Expected behaviour:* :heart: :smile:
Nothing should have been found, instantly.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by jeremyjh** [comment]
Just as a note for any others who might come across this, `ag` by default ignores any directories in a `.gitignore` file. Even if you don't use git, this could be a workaround for you.

**Comment by syl20bnr** [comment]
Submittted an issue upstream: https://github.com/syohex/emacs-helm-ag/issues/317

**Comment by axelson** [comment]
I _think_ this is fixed in https://github.com/emacsorphanage/helm-ag/pull/349 although I'm not sure how to verify
