### ISSUE TITLE
Python buffer not showing error messages

### ISSUE THREAD

**Issue by tarjeiba** [syl20bnr/spacemacs#8300]
#### Description :octocat:
Python buffer is not showing error messages.

#### Reproduction guide :beetle:
- Start Emacs
- Start a python process from a Python buffer.
- Either execute buffer containing erroneous code; or
- Type e.g. 2 + "hello" into REPL

*Observed behaviour:* :eyes: :broken_heart:
- Blank line, no error message

*Expected behaviour:* :heart: :smile:
- TypeError message printed before new next prompt.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.0.50.1
- Spacemacs: 0.200.7
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(html python helm emacs-lisp org
      (org :variables org-enable-reveal-js-support t))
```

#### Backtrace :paw_prints:
```

```

**Comment by ostrbor** [comment]
In emacs run `flycheck-describe-checker`.

Check if flake8 is installed in your system:
`pip show flake8`

**Comment by tarjeiba** [comment]
@ostrbor Does flycheck need to be enabled separately? I have no flycheck variables or functions defined. (The only functions are a few spaceline-toggle functions.) I can't find anything about it in the installation manuals neither. Yes, I have flake8 3.3.0 installed on my system. Thanks for looking into it!

**Comment by bmag** [comment]
> Does flycheck need to be enabled separately?

The `syntax-checking` layer needs to be enabled separately. Flycheck is part of it.

**Comment by tarjeiba** [comment]
It seems how I had defined my shell executable was the issue, the interpreter buffer now shows all output.

Thanks for all the help!
