### ISSUE TITLE
Python folding is bad

### ISSUE THREAD

**Issue by ipsod** [syl20bnr/spacemacs#8307]
# Good folding
See Vim, PyCharm with IdeaVim, or org-mode for a decent implementation of folding.  Unfold one level, and the levels below it remain folded, giving you an outline.

# Evil folding problems
Unfolding a region unfolds all sub-regions.  This basically ruins any benefit of folding.  

# Origami folding problems
Folds are only one-level deep.  Methods inside of classes, for example, are not fold-able.

People said that Origami is better than Evil, but Origami can't even fold class methods - am I missing something?

# Vimish-Fold problems
No syntax-based folding.

# Solution?
I don't know how people can browse code without proper folding.  Is there some navigation method I'm missing?

I've tried `helm-jump-in-buffer`, but it's way more clunky than code folding, since it always starts from the top instead of relative to where you are in code, and is an abstraction instead of a direct representation of code.

**Comment by ostrbor** [comment]
I use **C-c @ ...**
Also  `imenu`

**Comment by braham-snyder** [comment]
> syntax-based folding

Do you mean https://github.com/alexmurray/evil-vimish-fold? Or something else? Unfortunately, `vimish-fold` (upon which `evil-vimish-fold` depends) still has other (deal-breaking, I think) issues at the moment:
* [lack of folds over folds](https://github.com/mrkkrp/vimish-fold/issues/17) (if you're reading this and would like to see this feature implemented, I think it would help to go "vote for" (thumbs up) that issue)
* I think I need to further investigate and submit an issue for this still, but: unlike vim, `%s/foo/bar/g` doesn't affect text found in closed folds--nor does, e.g., `evil-mc`

**Comment by mixmixmix** [comment]
Hello, I've circled back to this issue - I cannot find any way of indentation-based folding in Python (tried all three origami/vimish/evil to no avail). The best I can do is to fold whole functions and classes in `evil`.
Anything eveolved in this regard since 2020?
