### ISSUE TITLE
How to add snippets in a layer? 

### ISSUE THREAD

**Issue by dannywillems** [syl20bnr/spacemacs#8308]
I want to add snippets for react to do a PR on this repository.
Can someone tell me where I have to put the snippets files?
I tried `+framework/react/local/snippets/react-mode/view.yasnippets` and `+framework/react/snippets/react-mode/view.yasnippets` but it doesn't work (when I restart Emacs, I can't use the snippets.

When I load the snippets manually, it's working.

**Comment by cpaulik** [comment]
I think we do not have snippets in spacemacs. They are all private or the ["official" yasnippet snippets](https://github.com/AndreaCrotti/yasnippet-snippets/tree/29da8e6c0444188406fdc5bb8b18e9b328fb710e). Maybe checkout https://github.com/johnmastro/react-snippets.el and how it adds the path to the yasnippet search paths.

**Comment by halfcrazy** [comment]
PUT your own snippets to ~/.emacs.d/private/snippets.

**Comment by dannywillems** [comment]
@halfcrazy It's what I do for the moment, but I was looking for a way to add it in Spacemacs.

**Comment by halfcrazy** [comment]
@dannywillems If you want to share, you may need to send a pull request to both 'https://github.com/AndreaCrotti/yasnippet-snippets' and 'https://github.com/joaotavora/yasnippet'

**Comment by nickanderson** [comment]
I have wanted to add snippets to layers as well.

For example I have some orgmode snippets that insert cfengine3 example blocks. This isn't useful for all org users. It would make sense to make the snippets available when your using cfengine and org together.

**Comment by syl20bnr** [comment]
There is a way to do this.

In the `cfengine` layer add `yasnippet` to the packages list and add a
`post-init-yasnippet` function to add the directory
`<cfengine_layer_directory>/local/snippets/org-mode` with a
`(if configuration-layer/package-usedp 'org ...)`.

Here is how to get the path of a layer:

```elisp
(configuration-layer/get-layer-path 'cfengine)
```

**Comment by nickanderson** [comment]
Oh cool, thanks for the tip. I'll try it out!
