### ISSUE TITLE
Combine beginning of line keys?

### ISSUE THREAD

**Issue by mkleehammer** [syl20bnr/spacemacs#8311]
Would it be convenient to map '0' to a function that toggles between column-0 and the first (non-whitespace) character, such as http://emacsredux.com/blog/2013/05/22/smarter-navigation-to-the-beginning-of-a-line?

Since S-v highlights entire lines regardless of cursor position, I find I don't need to go to column 0 very often.  I do often go to the first character, but the key to do so, ^', is not nearly as easy to press.  (Even worse, the 6 key is on the left side of some split/ergonomic keyboards and on the right of the other making it difficult to move between them.)

Consolidating them has been very handy, but I'd suggest keeping the '^' binding since it is a real vim one, of course.

**Comment by sooheon** [comment]
There's also `_` for that btw.

**Comment by dkleehammer** [comment]
:+1:

**Comment by mkleehammer** [comment]
@sooheon Ah, thanks.  I was not aware of the underscore binding.  That is pretty convenient, but not having to press shift is pretty nice too.  I'd still recommend people give it a try for a week or two.

**Comment by sooheon** [comment]
How does your rebinding affect evil digit arguments? Does it work fine with something like `yy10p` in normal state?

**Comment by mkleehammer** [comment]
Ah - I hadn't tried that yet.  Somehow it still works.  The 0 key was already mapped to a movement command so someone must have already worked some evil magic to know when to activate it and when not to.  My *guess* is that because it was preceded by another number it does not activate it's normal state binding.  I would assume it also means you can use 0 but not 1-9.
