### ISSUE TITLE
Org mode exporting wrong syntax highlighting colours

### ISSUE THREAD

**Issue by fladd** [syl20bnr/spacemacs#8313]
When exporting an org file to HTML, the resulting html file has wrong colours for code highlighting.

<img width="522" alt="image" src="https://cloud.githubusercontent.com/assets/2971539/22629298/95022c66-ebe3-11e6-952e-80e02bfbf064.png">

As you can see, the background of the comment is black for some reason, while the background of all other elements are white.

**Comment by dschrempf** [comment]
I also observed this problem. Recently, I fixed it by removing the background from comment lines, i.e., by using

      (setq spacemacs-theme-comment-bg nil)

However, after a recent update, even this measure stopped working. The background of comment lines is different which leads to these visual artefacts.
