### ISSUE TITLE
kill-whole-line/slick-cut as default behavior for C-w when no region selected

### ISSUE THREAD

**Issue by ejmg** [syl20bnr/spacemacs#8314]
Hi there,

I have a question regarding configuration. 

I have enabled [`better-defaults`](https://github.com/syl20bnr/spacemacs/blob/master/layers/+emacs/better-defaults/README.org) because I like indenting behavior it has for pasting code and formatting blocks of text. That said, its behavior with `kill-region` is not my favorite. I would prefer the behavior Spacemacs implements with `M-w` for an unselected region, i.e. it copies the current line if no region is selected.

Some call this `slick-cut`, and I had this functionality with my old Emacs configuration with the following snippet: 

```lisp
(defadvice kill-region (before slick-cut activate compile)
  "When called interactively with no active region, kill a single
  line instead."
  (interactive
   (if mark-active (list (region-beginning) (region-end))
     (list (line-beginning-position)
           (line-beginning-position 2)))))
```

On the Emacs wiki, they provide a slightly [different solution](https://www.emacswiki.org/emacs/WholeLineOrRegion) as follows:

```lisp
    (defun my-kill-ring-save (beg end flash)
      (interactive (if (use-region-p)
                       (list (region-beginning) (region-end) nil)
                     (list (line-beginning-position)
                           (line-beginning-position 2) 'flash)))
      (kill-ring-save beg end)
      (when flash
        (save-excursion
          (if (equal (current-column) 0)
              (goto-char end)
            (goto-char beg))
          (sit-for blink-matching-delay))))
    (global-set-key [remap kill-ring-save] 'my-kill-ring-save)
```

Neither of the provided solutions work. I have tried each snippet in both `user-config()` and `user-init()` to no avail. I have a feeling it is because of `better-defaults` own implementation, but cannot say. From the layer page, there seems to be no variable for disabling its `backward-kill-word` behavior unlike `better-defaults-move-to-beginning-of-code-first` which you can enable/disable.

I feel this is a basic fix but am not familiar enough with how spacemacs configures its various layers and keybindings to fix it myself. Any help would be appreciated!

**Comment by jundengdeng** [comment]
Did you finally find a way to make it work for spacemacs? I'd like to add the feature.
