### ISSUE TITLE
Agenda view not working properly.

### ISSUE THREAD

**Issue by danipozo** [syl20bnr/spacemacs#8323]
#### Description :octocat:
After last package update, org-agenda view fails to show.

#### Reproduction guide :beetle:
- Start Emacs.
- Update packages if you don't have the latest versions as of now.
- M-x org-agenda

*Observed behaviour:* :eyes: :broken_heart:
Agenda view shows nothing but the information about the current view (week number/month/day).

*Expected behaviour:* :heart: :smile:
That of a sane agenda view.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp git org haskell semantic
      (c-c++ :variables c-c++-enable-clang-support t)
      syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```Problems while trying to load feature ‘org-w3m’
   Problems while trying to load feature ‘org-bbdb’
   Problems while trying to load feature ‘org-bibtex’
   Problems while trying to load feature ‘org-docview’
   Problems while trying to load feature ‘org-gnus’
   Problems while trying to load feature ‘org-info’
   Problems while trying to load feature ‘org-irc’
   Problems while trying to load feature ‘org-mhe’
   Problems while trying to load feature ‘org-rmail’                                                                                                                                        
   File mode specification error: (void-function org-link-types)
   Saving file /media/sda1/home/dani/agenda.org...
   Wrote /media/sda1/home/dani/agenda.org
   (Spacemacs) Warning: Auto-evilication could not remap these functions in map `org-agenda-mode-map':
      - `org-agenda-next-line' originally mapped on `C-n'
   (Spacemacs) Warning: Auto-evilication could not remap these functions in map `org-agenda-mode-map':
      - `org-agenda-toggle-time-grid' originally mapped on `G'
   (Spacemacs) Warning: Auto-evilication could not remap these functions in map `org-agenda-mode-map':
      - `org-agenda-filter-remove-all' originally mapped on `|'
   Press key for agenda command (unrestricted):
   org-agenda-get-scheduled: Symbol’s function definition is void: org-at-planning-p
```

**Comment by Forec** [comment]
I met similar problems, but my `org-agenda` can still work.   
However, when I use `org-install` to generate config from `.org` files, `org-agenda` will out of work. The message buffer doesn't show any errors but only some warnings like yours. So I remove `org-install` and only generate `.el` from `.org` manually once I have modified it.

**Comment by RockyRoad29** [comment]
This seems related to #8074, here are my notes : [gist 55936](https://gist.github.com/RockyRoad29/55936d3f1e220f5db093dc028e321e0c)

**Comment by hanzejl** [comment]
I also have this problem while add 'elixir' layer, remove this layer, it's okay.

**Comment by rossputin** [comment]
I have the same 'Symbol’s function definition is void: org-at-planning-p' message with a minimal set of layers active, helm, emacs-lisp and org.

**Comment by enisozgen** [comment]
I got the same error about `org-at-planning-p` after upgrading packages in Spacemacs. 
I just restarted it by using `SPC q r` everything is fine for now.
