### ISSUE TITLE
Contents of clipboard get pasted when a file is opened

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#8324]
When I open a new file, the contents of my clipboard gets pasted wherever the cursor ends up.

**Comment by zestyr** [comment]
Duplicate of #5435

**Comment by bmag** [comment]
Not really enough information to decide if duplicate or not (or to understand what actually happened), but based on @beojan's lack of response I'm going to assume it is indeed a duplicate.

**Comment by beojan** [comment]
@bmag Sorry, yes it seems to be the same issue since @hemcsec's snippet seems to fix it.
