### ISSUE TITLE
Elixir: include alchemist-phoenix commands in SPC-m tree

### ISSUE THREAD

**Issue by natecox** [syl20bnr/spacemacs#8327]
It would be really helpful to have the phoenix related commands available from the SPC menu. For reference, here's a screenshot of what's available from the alchemist docs:

![image](https://cloud.githubusercontent.com/assets/2782695/22701977/0e7ce76c-ed14-11e6-8af2-019e38ffe294.png)

The list is available to browse [here](https://alchemist.readthedocs.io/en/latest/basic_usage/)

**Comment by sdwolf** [comment]
This seems straightforward, just need to add them [here](https://github.com/syl20bnr/spacemacs/blob/c2774bc0dea3dbc63621709d54685fbbe9212d55/layers/%2Blang/elixir/packages.el#L54). 

The only question is, what prefix should they have? The easy way would be to simply use `SPC m a` to replace the `C-c a` and keeping the rest but they do not quite feel "mnemonic". But then again this would be the easiest to maintain.

Any suggestions?

**Comment by natecox** [comment]
Maybe `SPC m a p` for "mix alchemist phoenix"?

I'd be fine either way though.

**Comment by sdwolf** [comment]
I've created a PR with the keybindings #8362. Please take a look and tell me what you think. You can check out my branch with the following commands:

```bash
cd ~/.spacemacs
git remote add sdwolf https://github.com/sdwolf/spacemacs.git
git fetch sdwolf keybindings/alchemist-phoenix
git checkout keybindings/alchemist-phoenix
```

**Comment by natecox** [comment]
Thanks, I've added my comments to that PR.

As a side note to this, maybe you can help me with my general lack of Emacs knowledge (yeah, I'm totally new). Is there a way that I could get these keybindings working from any file within the project? They work fantastically from a `.ex` file right now, but I'd want to also make those quick searches from other non-elixir files in the same project (e.g., `.vue`, `.eex`, `.css`).

**Comment by sdwolf** [comment]
Hmm... this is tricky, those functions are specific to alchemist and are available when `elixir-mode` is the major mode for those files. Those other extensions seem to be related to the `web-mode`. 

I'l have to take a look at how the ruby/rails layers handle cases this.

**Comment by natecox** [comment]
I wonder if this can be handled at the projectile level somehow

**Comment by sdwolf** [comment]
Found #8343 that seems to deal with exactly this... will give it a shot tomorrow and i'l ping you with the result.

**Comment by sdwolf** [comment]
Looks like #7192 is is exactly what you are looking for.

**Comment by sdwolf** [comment]
Also... about projectile keybindings... i think a better solution would be a `projectile-alchemist-mode` which creates those keybindings for projectile, this way people can exclude to install it if they see their projectile keybindings being overwritten.

**Comment by natecox** [comment]
Makes sense, although I'm still too much of a rookie to fully understand how the modes work.
