### ISSUE TITLE
JS auto-complete broken

### ISSUE THREAD

**Issue by ajrouvoet** [syl20bnr/spacemacs#8328]
#### Description :octocat:

Completion in react-mode is annoying (at least on develop branch): 
typing `return (|<ret>)` (where the right-paren is autoinserted) results in `return (return|)`.
Where the second `return` seems to be the first entry in the auto-complete menu that opened while
typing the last return keyword.

Particularly it seems to occur after typing a opening paren/brace/etc.

#### Reproduction guide :beetle:
- Tested on develop branch
- Start Emacs
- open a js file in react-mode. Type the above example.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: coq-layer (rev. 771faa85e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(windows-scripts yaml auto-completion better-defaults emacs-lisp git syntax-checking version-control markdown agda python scala javascript haskell html latex react shell coq ranger elm
                 (c-c   :variables c-c  -enable-clang-support t)
                 semantic gtags rust nixos)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by honza** [comment]
This affects me, too, and it's very annoying. I'm eager to help debug this, just not sure where to start. I had a look what changed in the `auto-complete` and `react` directories but nothing seems to indicate a possible source of this bug. I even tried disabling the `fuzzy` package to try and see if it affected things but no luck.

**Comment by JuanCaicedo** [comment]
I've been experiencing this with `coffee-mode` as well (also part of javascript layer). I have `company-mode` enabled, and tried turning it off an on again. This is also on stable. Let me know if I can provide any more details.

**Comment by yetone** [comment]
Same issue..

**Comment by honza** [comment]
I'm now using rxjs mode, as described in #8206. This brings many improvements to the React experience.

**Comment by JuanCaicedo** [comment]
Some combination of switching to the develop branch, reinstalling packages, switching back to master, and reinstalling again fixed this for me

**Comment by yetone** [comment]
@honza I just try rjsx-mode. But I found it don't work well with editorconfig plugin =.=

**Comment by delaanthonio** [comment]
This issue appears to be a duplicate of #8222. The issue is due to `company-minimum-prefix-length` being set to 0 in 3bbafcbfe35c8.
