### ISSUE TITLE
Fallback mode in case of broken packages?

### ISSUE THREAD

**Issue by m3hr** [syl20bnr/spacemacs#833]
Updating packages breaks emacs/spacemacs... a lot. The option to backup is extremely helpful but if someone's in a hurry to write something down, having the option (give users the choice) to fallback to just the core of spacemacs could be helpful.

**Comment by syl20bnr** [comment]
There is the rollback feature for this. It reverts to the state before the update (if you use the update link on the start page). The rollback operation is very fast.
The broken package could be in core so the user could loose even more time.
Being able to rollback only one package could be useful though.

**Comment by syl20bnr** [comment]
To fallback to the core of emacs, rename your dotfile and relaunch spacemacs.
