### ISSUE TITLE
Unstable declare-prefix-for-mode

### ISSUE THREAD

**Issue by averrin** [syl20bnr/spacemacs#8333]
hi. why when i add some language specific keys its works only for first opened file?

```
        (spacemacs/declare-prefix-for-mode 'dart-mode "m" "lang_tools")
        (spacemacs/set-leader-keys-for-major-mode 'dart-mode
          "j" 'dart-jump-to-defn
          "q" 'dart-quick-fix
          "d" 'dart-jump-to-defn
          "f" 'dartfmt
          "i" 'dart-imports
          )
```

i did it in dotfile and in my own dart layer (in packages.el  for dart-mode) - same result.

seems like when it calls more then once - it reset prefix and never return =(

any ideas?

**Comment by averrin** [comment]
I try use it here: https://github.com/syl20bnr/spacemacs/pull/8406 but still cant make it work.

**Comment by myrgy** [comment]
is there any advice how to fix that?

**Comment by bltavares** [comment]
This error seems to be caused by the same issue as https://github.com/syl20bnr/spacemacs/issues/7111

I'll try to send a patch to `dart-mode` package

**Comment by bradyt** [comment]
`dart-mode` now uses `defined-derived-mode`, is this issue resolved?

**Comment by duianto** [comment]
The PR:
Introduces Dart layer #11266
is now on the develop branch.
