### ISSUE TITLE
org mode export broken emacs 25.1.1 void org-link-types

### ISSUE THREAD

**Issue by greppy** [syl20bnr/spacemacs#8334]
#### Description :octocat:
cannot export org file

#### Reproduction guide :beetle:
- Install emacs 25.1.1 from source on RHEL7
- git clone spacemacs
- Start Emacs
- open org file
- C-c, C-e
- get error

*Observed behaviour:* :eyes: :broken_heart:
void-function org-link-types

*Expected behaviour:* :heart: :smile:
Export org mode file as html

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp git markdown python)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GCONF GSETTINGS NOTIFY LIBSELINUX LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11

#### Backtrace :paw_prints:
```
Problems while trying to load feature ‘org-w3m’
Problems while trying to load feature ‘org-bbdb’
Problems while trying to load feature ‘org-bibtex’
Problems while trying to load feature ‘org-docview’
Problems while trying to load feature ‘org-gnus’
Problems while trying to load feature ‘org-info’
Problems while trying to load feature ‘org-irc’
Problems while trying to load feature ‘org-mhe’
Problems while trying to load feature ‘org-rmail’
File mode specification error: (void-function org-link-types)
org-element--set-regexps: Symbol’s function definition is void: org-link-types
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
‘‘‘elisp
(ivy emacs-lisp git markdown python)
‘‘‘
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GCONF GSETTINGS NOTIFY LIBSELINUX LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11
```

**Comment by jorgemorais** [comment]
The error message "Symbol’s function definition is void: org-link-types" is also seen on #8351 .

**Comment by rgrinberg** [comment]
The way I've worked around this is by deleting the org mode that comes with emacs itself. On archlinux and emacs from master, this required something like:

```
$ sudo rm -rf /usr/share/emacs/26.0.50/lisp/org/*
```

**Comment by mbtuckersimm** [comment]
I just had this problem too. I had installed a new version of org-mode from elpa, and I had some code to set up org-mode in my init.el that only worked with this new version. But packages you install with the package manager get loaded *after* your emacs loads your init file (see the Info pages on Emacs Lisp Packages), so emacs was trying to evaluate the code using just the version of org-mode that comes with emacs, not the newer version. This is likely why deleting the older version works.

My solution was to call `package-initialize` in init.el before the org-mode code gets evaluated. This loads all of the user-installed packages, and hence ensures that the right version of org-mode is loaded when the relevant section of the init file is read.

Not sure if this is exactly the same as your problem, but I hope this is helpful.

**Comment by skyer9** [comment]
@mbtuckersimm you're solution is correct.

it is because after "install a new version of org-mode from elpa"
org-mode must be load after elpa initialized.

**Comment by stvharman** [comment]
The explanation about this could improve in the documentation. I had simply included org in my configuration layers and experienced this problem due to version conflict. However, the information provided at
http://spacemacs.org/layers/+emacs/org/README.html
lacks specific guidance.

A question

**Comment by jkw** [comment]
Just got this error too. Never had it before, installed Spacemacs on a RPi3 yesterday, didn't get this error. Installed it just now on a Linode VPS based on ArchLinux, got the error.

**Comment by ZaenChou** [comment]
For what it's worth, 
(spacemacs|use-package-add-hook org
:pre-init
(package-initialize)
)
worked for me

**Comment by othierry** [comment]
thanks @zaen323  your solution worked perfectly for me. Simple & Clean.

**Comment by zaen323** [comment]
@othierry Glad to be of help :)

**Comment by ckubrak** [comment]
@mbtuckersimm @othierry  @zaen323  Where did you put the (package-initialize) script?
I've tried in user-init and user-config and non of them worked.

**Comment by mbtuckersimm** [comment]
I put it near the beginning of my init.el. But really it just needs to go before any code that affects the packages you've loaded.

**Comment by rgrinberg** [comment]
Should this fix be upstreamed? I tried it out and it works just fine for me.

**Comment by ckubrak** [comment]
@mbtuckersimm I've fixed it, but I broke evaluating code blocks in org-mode. Everything started when I tried to fix the code evaluation in the first place

**Comment by mbtuckersimm** [comment]
@ckubrak What exactly is the problem that you're having? I have this code in my org-mode setup to allow code block evaluation for the languages that I need:

```
(org-babel-do-load-languages
      'org-babel-load-languages
      '((emacs-lisp . t)
        (sh . t)
	(shell . t)
	(perl . t)
	(python . t)))

```

**Comment by ckubrak** [comment]
@mbtuckersimm I managed to make it work by adding `  (package-initialize)` to my init.el

**Comment by mikaelv** [comment]
I had a similar issue when org-babel-do-load-languages was in my user-init.
I fixed it by moving the org-babel-load-languages variable to dotspacemacs-configuration-layers:
```
     (org :variables
          org-babel-load-languages '((emacs-lisp . t)
                                     (python . t)
                                     (scala . t))
          )
```
