### ISSUE TITLE
unable to get jedi autocomplete working in ipython-notebook layer

### ISSUE THREAD

**Issue by bmabey** [syl20bnr/spacemacs#8335]
I'm trying to get jedi autocompletion to work in the ipython-notebook layer. I found this [reddit post](https://www.reddit.com/r/spacemacs/comments/47wpl6/python_goodies_in_ipythonnotebook_layer/) by @millejoh and followed it with a basic spacemacs init file. The complete file with the suggested updates is [here](https://gist.github.com/bmabey/744b6b372f2b44531b03265e6a2a7b43). This doesn't seem to work. I've tried various other things but jedi never seems to be invoked. Any ideas?

**Comment by bmabey** [comment]
I should add that the bare-bones init file provided in `emacs-ipython-notebook` works fine so the problem is not with my host environment, it is an issue with the spacemacs setup. `jedi` makes the notebook much more useful and so I'll submit a PR for a working version if we can figure out what is wrong. TIA for any help!

**Comment by johnfarina** [comment]
I would love to have proper completion in the ipython-notebook layer, ideally using company, since that's what the rest of spacemacs uses.

**Comment by bmabey** [comment]
I was able to get jedi to work in some local notebooks after manually installing jedi and running some commands interactively. I'll try to isolate the steps at some point to see if I can make a worthwhile patch.

@johnfarina WRT company, I agree that would be nice but probably won't happen until EIN adds company support.

**Comment by johnfarina** [comment]
@bmabey Googleling around I found [this workaround](https://github.com/millejoh/emacs-ipython-notebook/issues/157#issuecomment-269091582) which purports to make company-anaconda work with EIN in regular emacs. Perhaps we can get that to work with spacemacs somehow? Alas, I'm brand new to spacemacs, and a total elisp neophyte so have no idea how to do this myself.

**Comment by tutysara** [comment]
@bmabey were you able to get jedi working in spacemacs?
