### ISSUE TITLE
Key bindings changing over time

### ISSUE THREAD

**Issue by arze1111** [syl20bnr/spacemacs#8345]
I have been using spacemacs for the last year to take notes and write papers.  Over time I have noticed that there seems to be certain keybindings that stop working for no reason that I can tell. The first one that I noticed was using SPC SPC for avy-word-1. The most recent one is the is no SPC m binding when I am trying to build a LaTeX file.  I was able to manage the avy word problem in my .spacemacs file, but I really want to reset EVERYTHING to have a clean install. 

To attempt this I have deleted my .spacemacs file and my d.emacs file, but reinstalling does not fix the problem. I am running El Capitan on a Mac. I have backed up the .spacemacs file.

**Comment by Stebalien** [comment]
> The first one that I noticed was using SPC SPC for avy-word-1.

Read the "IMPORTANT: Breaking changes" part of the 0.200.0 release notes. Specifically,

> - Key binding `SPC :` acting as `M-x` as been replaced by `SPC SPC`.
  If you want to revert to the old `SPC :` key binding set the new
  variable `dotspacemacs-emacs-command-key` to ":".

and

> - `SPC j` prefix has been modified to include `jump` commands:
>   - `avy` commands are now behind the prefix `SPC j` for `jump`:
>     - `SPC j j` to jump to a character in the buffer (works as an evil motion)
>     - `SPC j l` to jump to a line with avy (works as an evil motion)
>     - `SPC j w` to jump to a word in the current buffer (works as an evil motion)
>   - the following key bindings have been moved:
>     - `SPC j j` to split a line has been moved to `SPC j n`
>     - `SPC j h` and `SPC j l` have been moved to `SPC j 0` and `SPC j $`
>       respectively.
>     - `SPC J` to split a string or sexp has been moved to `SPC j s`

---

> The most recent one is the is no SPC m binding when I am trying to build a LaTeX file.

Assuming you have the latex layer enabled, that sounds like a bug. Please report it using `SPC h I`.

**Comment by arze1111** [comment]
Ok, that explains some things.  I reported the bug, and  I have been using C-c C-c in latex to work around the problem. Thanks for the quick reply.

**Comment by Stebalien** [comment]
> I reported the bug

Where?

**Comment by arze1111** [comment]
My bad, now I did.

**Comment by Stebalien** [comment]
And can you close this one (assuming it's been resolved)?
