### ISSUE TITLE
Vim Keybings not working in Markdown Mode

### ISSUE THREAD

**Issue by yashsriv** [syl20bnr/spacemacs#8348]
#### Description :octocat:
Certain Vim Keybings do not work in Markdown Mode. For example, `dd` does not work at all.
This issue cannot be reproduced while using just `markdown` layer. ~~I'll try and isolate out
the layers conflicting with each other. Current List of layers as attached with this issue.~~

#### Reproduction guide :beetle:
- Start Emacs
- Open Markdown File
- Try using `dd` on any line

*Observed behaviour:* :eyes: :broken_heart:
Nothing Happens. Pressing `d` pauses cursor as in other modes, but pressing another `d` does not delete a line.
Messages show:
```
Quit
```

*Expected behaviour:* :heart: :smile:
Pressing `dd` should delete the current line

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. d2168806)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(markdown nlinum)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by kenkangxgwe** [comment]
Getting the same bug! Both <kbd>D</kbd> and <kbd>dd</kbd> fail to work.

**Comment by kenkangxgwe** [comment]
Try delete `nlinum` & `markdown` layers and re-add `markdown` layer.

**Comment by peterhoeg** [comment]
I can confirm that @kenkangxgwe's workaround does the trick for me!

**Comment by non-Jedi** [comment]
Removing the nlinum layer solved this issue for me. Does anybody have ideas
about the root cause and what we can do to make the markdown layer compatible
with nlinum layer?

**Comment by Miciah** [comment]
I'm really curious as to the cause of this issue, but nlinum is deprecated in Emacs 26.1 (Spacemacs will not load it even if the layer is specific in `dotspacemacs-configuration-layers`), so this issue can be labeled "Emacs 25.1".

**Comment by peterhoeg** [comment]
I can confirm that with 26.1, this issue is no longer present.
