### ISSUE TITLE
SPC m binding not working in latex layer

### ISSUE THREAD

**Issue by arze1111** [syl20bnr/spacemacs#8350]
#### Description :octocat:
The key binding SPC m does not have an assigned value when I am using the latex package. To build a pdf from the tex file I have to use C-c C-c

#### Reproduction guide :beetle:
- Start Emacs
- open a .tex file
- press SPC
- notice that there is no "m" group of commands

*Observed behaviour:* :eyes: :broken_heart:
There is a message "SPC m is not defined"

*Expected behaviour:* :heart: :smile:

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp markdown org spell-checking gnus games)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Stebalien** [comment]
You appear to be missing the latex layer.

**Comment by arze1111** [comment]
lol, that explains it. I put that in my dotfile and and SPC m works.  But how was I able to use C-c C-c and other commands that changed the latex file if I did not have the layer enabled?

**Comment by sdwolf** [comment]
@arze1111 maybe it's because you have the `org` layer which seems to have some latex related functionality. `M-x latex` autocompletes me with `latex-mode` although I do not have it as a layer either.

**Comment by arze1111** [comment]
Ah, yes that would be it. Thank you

**Comment by Stebalien** [comment]
FYI, you can enable `dotspacemacs-enable-lazy-installation` for super auto magic.

**Comment by arze1111** [comment]
So go to my dotspacemacs file and do what?

**Comment by Stebalien** [comment]
Go to the `dotspacemacs/layers` section and play with the `dotspacemacs-enable-lazy-installation` setting. If you don't see it, you may need to update your dotspacemacs file (use `SPC f e D`).

**Comment by arze1111** [comment]
Oh, that is nice! being lazy is great.
