### ISSUE TITLE
"Error (bytecomp): Symbol’s function definition is void: org-link-set-parameters" (bug persists)

### ISSUE THREAD

**Issue by jorgemorais** [syl20bnr/spacemacs#8351]
#### Description :octocat:
See subject.  Occurs when starting Spacemacs for the first time (see reproduction guide below) and also later when updating Org.

Workaround is to, after seeing the error message, restart Emacs. I have not detected additional malfunctioning.  However, this leaves the user worried that it may cause further malfunctioning without conspicuous symptoms.

A probably related problem: my Spacemacs boot time is long because it initializes Org.  This should not happen, because I have already taken the FAQ[1] into account.  I put all the Org setup in the custom-set-variables form plus a file, and this file is loaded in dotspacemacs/user-config like this:
(eval-after-load 'org '(require 'J-org))
[1]: http://spacemacs.org/doc/FAQ#why-do-some-of-my-org-related-settings-cause-problems

In fact, I tried to (after making a backup) modify my .spacemacs by completely emptying dotspacemacs/user-config function and the custom-set-variables form[2].  Then when I boot Spacemacs from this modified .spacemacs and eval (featurep 'org), it returns t.  This means that Spacemacs is spuriously loading Org on startup, which explains this bug.
[2]: The resulting .spacemacs is in https://glot.io/snippets/en2ka7iyww

#### Reproduction guide :beetle:
Make sure there is no ~/.spacemacs and no ~/.emacs.d
Then:
- cd
- git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs initialization gives errors.
Compile log: http://pastebin.com/Lw7cvzZP
Messages: http://pastebin.com/gxSE14wj

*Expected behaviour:* :heart: :smile:
Spacemacs should initialize without errors.

#### System Info :computer:
Observation: I have chosen emacs editying style (holy mode), but after the initialization gives the error, I am left with the vim style.  This can be fixed with M-x holy-mode.
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by nixmaniack** [comment]
This seems to be happening because of org version mismatch and loading order. 

When you start spacemacs the first time (with no .spacemacs and .emacs.d) - org version 8.x.x is loaded when configuring the newly downloaded org-version 9.x.x as part of first-run setup. The said function `org-link-set-parameters` is defined in latest org 9 but since org 9 isn't available in the first run it throws error in compilation (as org 8 is already loaded). 

When you start spacemacs second time - it will load latest org and there shouldn't be any issues. 

So this looks like chicken-and-egg situation :).

**Comment by nixmaniack** [comment]
I had commented [here](https://github.com/syl20bnr/spacemacs/issues/8282#issuecomment-277057738) for similar errors on post-spacemacs-setup but those solutions won't help here.

**Comment by smile13241324** [comment]
@nixmaniack Do you have a workaround for this issue yet?

I am asking because I am trying to merge some new tests for the org html export but they fail due to this bug as travis installs emacs anew for each test and therefore we always load the wrong org version.

See: #8431

**Comment by nixmaniack** [comment]
@smile13241324 Unfortunately not yet. I have been busy and didn't look for workarounds here.

**Comment by smile13241324** [comment]
@nixmaniack found a workaround for the travisCI tests by introducing a dedicated installation step for the tests. By that emacs first installs all packages, then shutsdown and is started again for the tests. This time with all packages installed and therefore loading the right org version.
