### ISSUE TITLE
(void-variable company-backends-scheme-mode)

### ISSUE THREAD

**Issue by nalzok** [syl20bnr/spacemacs#8355]
Related issues:

1. [fix void-variable company-backends-scheme-mode][1]
2. [(void-variable company-backends-typescript-mode) when open `.ts` file][2]
3. [Add protobuf layer][3]

When I open a `.scm` file, the file opens successfully, but an error message is emitted:

    File mode specification error: (void-variable company-backends-scheme-mode)

When I explicitly enter **scheme-mode** with `<SPC> <SPC> scheme-mode`, I got the following error:

    spacemacs//init-company-scheme-mode: Symbol’s value as variable is void: company-backends-scheme-mode

[![screen shot 2017-02-13 at 21 26 47](https://cloud.githubusercontent.com/assets/13443062/22885218/6942c59e-f233-11e6-8987-a2c1440ce383.png)](https://cloud.githubusercontent.com/assets/13443062/22885218/6942c59e-f233-11e6-8987-a2c1440ce383.png)

I'm using the latest version of Spacemacs on the `master` branch (just checked update). 

- [Here is my dot file][4]
- [Here is the full output of the `*Messages*` buffer (you may want to look at the last few lines)][5]

This error disappears when I comment out (deactivate) `scheme` in `dotspacemacs-configuration-layers`, but I need it :(

  [1]: https://github.com/syl20bnr/spacemacs/pull/7652
  [2]: https://github.com/syl20bnr/spacemacs/issues/7377
  [3]: https://github.com/syl20bnr/spacemacs/pull/6799
  [4]: https://gist.github.com/sunqingyao/70ecf94d3d99777acbea2ff6843eb215
  [5]: https://gist.github.com/sunqingyao/eb5f39a6c3a14f7def43499db3039a5c

**Comment by bmag** [comment]
Isn't it the same bug that was solved by #7652, but the fix still isn't in master?
