### ISSUE TITLE
Perspective name shows in mode-line

### ISSUE THREAD

**Issue by stef264** [syl20bnr/spacemacs#8358]
#### Description :octocat:
Perspective name shows in mode-line
http://i.imgur.com/6ztkkH8.png

#### Reproduction guide :beetle:
- Install fresh Emacs and Spacemacs
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
"#Defau" in mode-line

*Expected behaviour:* :heart: :smile:
No perspective name in mode-line

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```

**Comment by elandx** [comment]
I have the same bug and oddly rollback don't helps.

**Comment by rakyi** [comment]
Experienced the same issue after updating packages recently. Rollback worked.

**Comment by duianto** [comment]
A temporary solution to remove `#Defau` from the modeline is to disable `persp-mode`:
<kbd>M-x</kbd> type: `persp-mode` and press <kbd>RET</kbd>
It comes back when emacs is restarted.

**Comment by stef264** [comment]
Same with sync config 'SPC f e R'

**Comment by syl20bnr** [comment]
Should be fixed in develop, seems to be a use-package bug, all the not diminished lighters were using the `:diminish` keyword of use-package.
