### ISSUE TITLE
Ranger issue. Void variable: bookmark-list, ranger-pre-header-format

### ISSUE THREAD

**Issue by ztlevi** [syl20bnr/spacemacs#8360]
Hi, guys. There is an issue after I update the packages. Every time I start to use ranger, it shows: _Symbol's value as variable is void: bookmart-alist_. And When I start to open a file using ranger, it shows: _Symbol's value as variable is void: ranger-pre-header-format_. So I add _(setq ranger-pre-header-format header-line-format)_ to my init.el. It works for me to open a file in ranger now. But the bookmark-alist variable is still void and I cannot use _(ranger-override-dired-mode t)_ to override dired mode.
It totally confused me now. Any suggestions would be grateful. Thanks.

**Comment by ztlevi** [comment]
Solved this problem by using `(require 'bookmark)`

**Comment by bmag** [comment]
@ztlevi if you're satisfied with the fix, you can close the issue. If not, please provide some more details (see [Debugging](https://github.com/syl20bnr/spacemacs/wiki/Debugging)).
