### ISSUE TITLE
Coq files are not opened in Coq mode

### ISSUE THREAD

**Issue by langston-barrett** [syl20bnr/spacemacs#8361]
#### Description :octocat:
When using the new Coq layer, *.v files are not automatically opened in Coq mode.

#### Reproduction guide :beetle:
- Put `coq` in your layers
- Open a .v file

*Observed behaviour:* :eyes: :broken_heart:
- Get dropped into `Fundamental` mode

*Expected behaviour:* :heart: :smile:
- SPC m is defined and gives us useful Coq functions

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 3072e727)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp
      (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-complete-with-key-sequence "ff")
      git
      (shell :variables shell-default-shell 'ansi-term shell-default-position 'bottom)
      spell-checking syntax-checking coq emacs-lisp
      (haskell :variables haskell-enable-hindent-style "fundamental")
      (latex :variables latex-build-command "LatexMk" latex-enable-auto-fill t)
      markdown nixos python shell-scripts yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 MODULES

**Comment by siddharthist** [comment]
After playing with spacemacs (deleting .emacs.d and reinstalling) this works. Feel free to close or keep open.
