### ISSUE TITLE
Word boundaries in- and outside symbol highlight transient state don't agree

### ISSUE THREAD

**Issue by jFransham** [syl20bnr/spacemacs#8364]
#### Description :octocat:
The word boundaries used by `*`/`#` in- and outside symbol highlight transient state don't agree.

#### Reproduction guide :beetle:
- Start Emacs
- Open `*scratch*` buffer
- Type:
    ```
    *test
    test
    test
    ```
- Hover over the `test` on the second line and press `*` or `#`
- Press `n` or `N` a few times
- Press `<ESC>` to leave symbol highlight transient state
- Press `n` or `N` a few times

*Observed behaviour:* :eyes: :broken_heart:
In the transient state, only the `test`s on the second and third lines are
jumped between, but outside the `test` on all three lines are detected.

*Expected behaviour:* :heart: :smile:
The same behaviour would happen in both (I'd say that the behaviour outside the
transient state is more intuitive).

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(javascript react html php csv lua haskell python yaml shell-scripts rust ivy auto-completion emacs-lisp git markdown)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
N/A

**Comment by duianto** [comment]
Confirmed in the develop branch as well:
#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 3072e727)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((markdown :variables markdown-live-preview-engine 'vmd)
 auto-completion chrome emacs-lisp git helm html markdown org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by Miciah** [comment]
This looks like a duplicate of #2710.
