### ISSUE TITLE
Spacemacs freezes in its help file.

### ISSUE THREAD

**Issue by andit001** [syl20bnr/spacemacs#8366]
#### Description :octocat:

Spacemacs freezes in its help file.

#### Reproduction guide :beetle:

- Start Emacs

- Input SPC-h-r
- Choose the Spacemacs documentation
- Input /helm-f

*Observed behaviour:* :eyes: :broken_heart:

Spacemacs doesn't respond anymore. It uses alot of CPU. About 30% on my system and won't get back to life anymore.

*Expected behaviour:* :heart: :smile:

Spacemacs to find or not to find the desired search result.

(%LAST_KEYS%)

#### System Info :computer:
Note: I tested it on my Laptop, too. And had different Layers installed. The bug persisted.
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey windows-scripts html helm colors shell git markdown org latex bibtex deft pandoc html emacs-lisp evil-commentary themes-megapack my-layer
            (c-c++ :variables c-c++-enable-clang-support t)
            (syntax-checking :variables syntax-checking-enable-by-default t)
            (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-complete-with-key-sequence "jk" auto-completion-tab-key-behavior 'cycle))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

#### Backtrace :paw_prints:

```

```

**Comment by rakyi** [comment]
I was able to reproduce the issue. Also happens with `helm-d`, `helm-f`, `helm-t`. Tried only lowercase ASCII letters after `helm-`.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.2
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip 'manual)
 c-c++ csv
 (elm :variables elm-format-on-save t elm-sort-imports-on-save t)
 git github
 (haskell :variables haskell-enable-hindent-style "johan-tibell")
 helm html javascript latex markdown org php python semantic
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES
