### ISSUE TITLE
God-mode in Spacemacs: the `f` key always makes buffer modified before moving the cursor forward

### ISSUE THREAD

**Issue by tddsg** [syl20bnr/spacemacs#8375]
#### Description :octocat:
When using `god-mode` in Spacemacs, pressing the `f` key always makes buffer modified before moving the cursor forward

#### Reproduction guide :beetle:
- Start Emacs
- Install `god-mode` (`M-x package-install god-mode` )
- Open a buffer and enable the `god-mode`

*Observed behaviour:* :eyes: :broken_heart:

- When `god-mode` is able, whenever pressing `f` to move the cursor forward, the character `f` is firstly inserted in the buffer, making the buffer modified, and then this character is removed and the cursor moves forward

- The problem only happens to the key `f`. No problems with `p`, `n`, `b`

- When I use `god-mode` with a fresh Emacs (not Spacemacs), no problems happen.

FYI, there used to be a similar issue reported to the `god-mode`, related to the key `n`. I tried to do as the suggestion but see no difference: https://github.com/chrisdone/god-mode/issues/67

*Expected behaviour:* :heart: :smile:

- In Spacemacs, with `god-mode` enabled, pressing `f` should move the cursor forward, without modifying the buffer

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control spacemacs-layouts semantic pdf-tools latex ocaml haskell tddsg)
```

**Comment by tddsg** [comment]
I've just found out that it is due to the `evil-mode`. Currently, I'm using the `holy-mode`, and if `evil-mode` is disabled, then the problem with `f` won't occur anymore.

I just wonder why the `evil-mode` affects only the `f` key, but not `p`, `n`, `b`?

**Comment by bmag** [comment]
It might be related to `evil-escape` package. If you don't use it (you probably don't, since you use `holy-mode`), you can add it to your excluded packages and maybe that will help.

**Comment by beta1440** [comment]
I also had the same issue. I fixed it by changing the `evil-escape-key-sequence`. Here's a snippet from by `user-config`.

```emacs-lisp
;; evil escape
  (setq-default
   evil-escape-delay 0.2
   evil-escape-key-sequence "jk"
   evil-escape-unordered-key-sequence t)
```
