### ISSUE TITLE
Haskell layer reinstalls backward version of intero

### ISSUE THREAD

**Issue by abhi18av** [syl20bnr/spacemacs#8377]
The haskell layer installs a previous version of Intero `0.18` whereas I already have the `0.20` version.

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>

```
run-haskell

intero-repl

```
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion
  (haskell :variables haskell-completion-backend 'intero))
 (auto-completion :disabled-for shell)
 better-defaults emacs-lisp clojure git markdown org
 (haskell :variables haskell-enable-hindent-style "johan-tibell")
 html ocaml go rust c-c   python fsharp racket scheme chinese restclient prodigy gtags deft colors
 (shell :variables shell-default-height 30 shell-default-position 'bottom :packages
        (not company))
 (ruby :variables ruby-enable-enh-ruby-mode t ruby-test-runner 'rspec ruby-version-manager 'rbenv)
 spell-checking syntax-checking version-control)
```
- System configuration features: JPEG RSVG IMAGEMAGICK DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by Miciah** [comment]
Is this a duplicate of #8041?
