### ISSUE TITLE
Allow for setting the color of the cursor in themes

### ISSUE THREAD

**Issue by belak** [syl20bnr/spacemacs#8378]
Right now, as far as I can tell, the only way to set the cursor is by using `evil-emacs-state-cursor` (as an example) and setting a number of variables.

It would be really nice if these could be defined in the theme itself, so themes can set the cursor color and the indicator color in spaceline to the same value, without relying on the user to add some additional code to their `.spacemacs` file to set the cursor color.

**Comment by bmag** [comment]
You can also use `spacemacs-evil-cursors`, which changes evil cursors when you change the theme. Do you know of any theme that actuaclly changes the evil cursors?

**Comment by belak** [comment]
I currently maintain the base16-themes package and was hoping to add this feature in, but as far as I can tell, there's no way to set the colors in the theme itself.

We do included a section in the readme (https://github.com/belak/base16-emacs/#evil-mode) about that, but it would be nice to just install the theme and have it work without any additional configuration.

**Comment by belak** [comment]
This was requested by a user in https://github.com/belak/base16-emacs/issues/36 and it seemed like it would be useful.

**Comment by belak** [comment]
I don't believe this has been fixed yet.

**Comment by belak** [comment]
I don't believe this is fixed yet...

**Comment by lebensterben** [comment]
I think it's just no one is interested in this.
It's to trivial. Just use `set-cursor-color`.

**Comment by belak** [comment]
That's fair
