### ISSUE TITLE
Rendering errors in Termite

### ISSUE THREAD

**Issue by jfeick** [syl20bnr/spacemacs#8379]
#### Description :octocat:
Buffer gets incorrectly rendered in Termite

#### Reproduction guide :beetle:
- Start Termite in default configuration
- Start emacs with spacemacs configuration in terminal mode (-nw)

*Observed behaviour:* :eyes: :broken_heart:
See gif: ![Image of Behaviour](https://i.imgur.com/53J71by.gif)

*Expected behaviour:* :heart: :smile:

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript html octave python helm emacs-lisp themes-megapack games xkcd selectric)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by nixmaniack** [comment]
I doubt this has anything to do with Spacemacs. It looks like the escape sequences generated and terminfo is messed up. 
I used to have same effect when my terminfo was corrupted with single escape sequence in my terminal. Also in case you're using any terminal multiplexer(screen, tmux etc) they might cause this unless you have set the TERM and termino correctly.

**Comment by jfeick** [comment]
Well - spacemacs works flawlessly in screen and tmux - so I guess you are right abotu a messed up terminfo.
Any idea how I could further debug this?

**Comment by chrissound** [comment]
This should probably be reported to termite instead. Shall we close this?

**Comment by VMatrix1900** [comment]
I have the same problem for windows 10 bash on Ubuntu subsystem. Same reason? Is there anything I can do to fix that? Can I set the TERM to fix that?
