### ISSUE TITLE
Clicking on links results in an extra character appended to it in the browser.

### ISSUE THREAD

**Issue by CMCDragonkai** [syl20bnr/spacemacs#8380]
#### Description :octocat:
Urls inside strings are clickable, when I click on them, it opens up the chrome browser, but the URL that I clicked as a quote character appended to it.

#### Reproduction guide :beetle:
- Start Emacs
- Enter `var x = 'http://google.com/blah';`.
- Click on the link.

*Observed behaviour:* :eyes: :broken_heart:

If I use `'http://google.com/blah'`, I get `http://google.com/blah'`.

*Expected behaviour:* :heart: :smile:

I shouldn't get that extra quote character.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript php html helm auto-completion emacs-lisp
            (git :variables git-magit-status-fullscreen t)
            markdown org
            (syntax-checking :variables syntax-checking-enable-by-default nil)
            python)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by Compro-Prasad** [comment]
Clicking on a link runs `goto-address-at-point` which is a native Emacs function. It doesn't have any information around the link. So, `'` is part of the link. Either you can report this to Emacs bug tracker or you can use `browse-url` then remove the `'` and hit return. Don't know if this a bug. A custom function can be written in such a case.
