### ISSUE TITLE
Haskell: support intero black and whitelisting 

### ISSUE THREAD

**Issue by PierreR** [syl20bnr/spacemacs#8383]
Intero supports the concept of whitelisting blacklisting a project:
https://github.com/commercialhaskell/intero#whitelistingblacklisting-projects

This is really useful because upon edition of a haskell configuration file such as `xmonad.hs`, not only `intero` would fail to start but the editor will enter a strange state where every key pressed takes age to respond (almost freezing state).

I have been trying to make this work 'manually' by hacking the `func.el` and `package.el` without success so far (see https://github.com/commercialhaskell/intero/issues/364, https://github.com/commercialhaskell/intero/issues/319)

**Comment by i-am-the-slime** [comment]
Is there any solution to this yet?

**Comment by PierreR** [comment]
I believe this fixes the issue: https://github.com/syl20bnr/spacemacs/pull/9762

Unfortunately the PR took so much time to get merged that I deleted it at some point. It is only one line change. I guess redoing the PR hoping for a quicker feedback would be the way to go.

**Comment by duianto** [comment]
The proposed PR #9762 was closed, because it might not be needed since this PR has been merged:
Haskell: add LSP support via HIE and lsp-haskell #11887

It seems to have added support for different haskell backends, which might have solved this issue.
