### ISSUE TITLE
Emacs doesn't load customized variables/faces

### ISSUE THREAD

**Issue by mkaito** [syl20bnr/spacemacs#8384]
#### Description :octocat:
Emacs doesn't load customized variables or faces

#### Reproduction guide :beetle:
- Start Emacs
- Check the value of `custom-file`. It should point to dotspacemacs.
- Execute `customize-saved` to see variables customize is aware of.

*Observed behaviour:* :eyes: :broken_heart:
- Only the terminal color vector is defined.

*Expected behaviour:* :heart: :smile:
- I expect to see the custom variables/faces I saved last session.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: nil (rev. c2774bc0d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(vimscript sql syntax-checking my-eshell c-c   emacs-lisp evil-commentary finance git html javascript pandoc markdown
					 (org :variables org-projectile-file "~/notes/projects.org")
					 my-org ruby vinegar yaml
					 (shell :variables shell-default-shell 'eshell shell-default-height 35)
					 shell-scripts nevermore beancount)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:

Not relevant

**Comment by bmag** [comment]
Not sure what branch/commit you're running on. Can you reproduce the issue in latest develop? On my machine `custom-file` points to `~/.emacs.d/.cache/.custom-settings`...

**Comment by mkaito** [comment]
I pulled from `develop` a couple days before posting this, and `custom-file` was pointing to `~/.spacemacs`.

I've since removed all custom stuff and moved it to `setq` calls in `spacemacs/user-config`.

**Comment by bmag** [comment]
From [core-custom-settings.el](https://github.com/syl20bnr/spacemacs/blob/develop/core/core-custom-settings.el#L13-L15):
```elisp
(defvar spacemacs--custom-file (concat spacemacs-cache-directory
                                       ".custom-settings"))
(setq custom-file spacemacs--custom-file)
```

It doesn't look like there's a bug here.
