### ISSUE TITLE
Default key binding "C-h h" freezes Emacs 

### ISSUE THREAD

**Issue by shelper** [syl20bnr/spacemacs#8386]
#### Description
key map freezes Emacs

#### Reproduction guide :beetle:
- windows 7
- Emacs 25.1.1
- spacemacs  0.200.7@25.1.1 
- try this in org-mode buffer, but any other buffer/major mode should also do the same.

*Observed behaviour:* :eyes: :broken_heart:
extremely slow when you first time type: `C-h` and followed by `h`, 
this should bring up the HELLO greeting of emacs.
sometimes it even freezes Emacs
but once it gets through, repeat doing this is find and quick

*Expected behaviour:* :heart: :smile:

#### Backtrace :paw_prints:
N/A

**Comment by rakyi** [comment]
I'm unable to reproduce the issue with my system.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.2
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip 'manual)
 c-c++ csv
 (elm :variables elm-format-on-save t elm-sort-imports-on-save t)
 git github
 (haskell :variables haskell-enable-hindent-style "johan-tibell")
 helm html javascript latex markdown org php python semantic
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by shelper** [comment]
can anyone uses windows 7 try to see if he/she can reproduce the issue?
