### ISSUE TITLE
Package update fails after gnutls error.

### ISSUE THREAD

**Issue by bauermann** [syl20bnr/spacemacs#8388]
#### Description :octocat:
After updating packages, the following error appears on emacs startup:

error: Required feature `persp-mode' was not provided

The error below appears on both the "update packages" phase (i.e., before
restarting emacs) and the actual package installation phase (after
restarting emacs), so it's probably related to this bug:

gnutls.c: [0] (Emacs) fatal error: The TLS connection was non-properly terminated.

I rolled back the update and tried again and the outcome was exactly the
same.

If relevant, the version of the libgnutls30 package I have installed is
3.4.10-4ubuntu1.2. This is an Ubuntu 16.04.2 system.

BTW .I tried submitting from within spacemacs, but I get the error "C-c C-c is undefined", so using github.

#### Reproduction guide :beetle:
- Start Emacs
- Activate "Update packages" button/feature in spacemacs home screen.

*Observed behaviour:* :eyes: :broken_heart:
When emacs starts, it shows the error below:

error: Required feature `persp-mode' was not provided

*Expected behaviour:* :heart: :smile:
emacs starts without error after package update.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0dea3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (c-c++ :variables c-c++-enable-clang-support t)
 cscope emacs-lisp git gnus)
```

**Comment by rakyi** [comment]
I was getting that gnutls error for a long time without any visible issues with Emacs 24.5.1 on Ubuntu 16.04. It went away after I updated to Emacs 25.1.2
