### ISSUE TITLE
JSX lost highlighting after using 'SPC m =' to format code

### ISSUE THREAD

**Issue by ThinkCats** [syl20bnr/spacemacs#8391]
Description :octocat:

JSX lost highlighting after using `SPC m =` to format code ,  I must type `SPC SPC`, and then type `react-mode` to recover highlight. 

At the same time, I found  that html code format is strange: 

``` javascript
class D extends Component {
	render() {
		return () {
			<div>
              hello world
          </div>
		}
	}
}
```

Reproduction guide 🐞

* Config React Layer and  Restart Emacs
* Open a JSX file and write a Component (JSX highlighting is perfect at now)
* Format Code using `SPC m =`(JSX is not highlighting) 

Observed behaviour: 👀 💔

* JSX lost highlighting
* html code is in mess 

Expected behaviour: ❤️ 😄

JSX is highlighted and the code is format well.

System Info 💻

OS: darwin
Emacs: 26.0.50.1
Spacemacs: 0.200.7
Spacemacs branch: master 
Graphic display: t
Distribution: spacemacs
Editing style: vim
Completion: helm
Layers:
``` lisp
(
     javascript
     (markdown :variables markdown-live-preview-engine 'vmd)
     html
     yaml
     shell
     emoji
     react
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     (go :variables gofmt-command "goimports"
         go-tab-width 4)
     ivy
     auto-completion
     ;; better-defaults
     emacs-lisp
     org
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     ;; spell-checking
     syntax-checking
     version-control
     )
```

**Comment by cyberxndr** [comment]
This is already known issue #5724

**Comment by ThinkCats** [comment]
@cyberxndr now, I using `js2-jsx-mode`, and I feel good when writing JSX file.  You can have a try it using `SPC SPC js2-jsx-mode` or `M-x js2-jsx-mode`, good luck.

**Comment by bmag** [comment]
@ThinkCats if you got it working properly you may want to comment on the original issue

**Comment by Nolski** [comment]
`js2-jsx-mode` doesn't seem to work for me. I get `unknown command: 'js'` as the output
