### ISSUE TITLE
 haskell-mode is 'void' in Spacemacs (Ubuntu)

### ISSUE THREAD

**Issue by mohanr** [syl20bnr/spacemacs#8393]
I have installed spacemacs in Ubuntu. I used to use this key binding in a Windows machine to execute code. But now it fails in ubuntu because the variable haskell-mode is void. Error shown when starting Spacemacs.
The installation is basic based on the instructions. stack is used. Why ?
       
          (defun dotspacemacs/user-config ()
           “Configuration function for user code.
           This function is called at the very end of Spacemacs   initialization after
           layers configuration. 
           This is the place where most of your configurations should be    done. Unless it is
           explicitly specified that a variable should be set before a package is loaded,
          you should place your code here.”
         (spacemacs/set-leader-keys-for-major-mode ‘haskell-mode
         “cx” ‘inferior-haskell-load-and-run
         )
 )
haskell layer is installed.

**Comment by rakyi** [comment]
The code you posted uses UTF characters for quotes. It works for me with normal quotes.
```elisp
(spacemacs/set-leader-keys-for-major-mode 'haskell-mode
  "cx" 'inferior-haskell-load-and-run)
```

**Comment by mohanr** [comment]
whoa! Closing.
