### ISSUE TITLE
Need help with config layer

### ISSUE THREAD

**Issue by averrin** [syl20bnr/spacemacs#8395]
Can anybody help me  to write config layer for Dart lang?
Im spacemacs newbie and packages for dart are not very robust. So i cant make it work:
https://github.com/averrin/dart-layer
Any help is very appreciated!

**Comment by averrin** [comment]
Yes, i add 
```(configuration-layer/lazy-install 'dart :extensions '("\\(\\.dart\\'\\)" dart-mode))
``` and layer installs on dart files, but its doesnt load dart-mode and any other actions.

**Comment by robbyoconnor** [comment]
Why not just make a layer for this? It's useful. Even if dart is more or less dead...

**Comment by robbyoconnor** [comment]
Make a pull request -- don't open an issue -- we already have a crapload of them...

**Comment by averrin** [comment]
unfortunately it uses forks and non-melpa packages. So imho it should be private for now...

**Comment by robbyoconnor** [comment]
Spacemacs allows for this...

**Comment by robbyoconnor** [comment]
via quelpa ;)

**Comment by duianto** [comment]
The PR:
Introduces Dart layer #11266
is now on the develop branch.
