### ISSUE TITLE
spacemacs-theme updates available, but I'm getting "All packages are up to date"

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#8397]
### Description
The `spacemacs-theme` has been updated and MELPA lists it's most recent version: `20170217.1753`, but when i press the `[Update Packages]` link in the `*spacemacs*` buffer, then i keep getting these messages:

> Updating package archives, please wait...
> --> refreshing package archive: gnu... [3/3]
> --> All packages are up to date.

the messages buffer shows this:

> (Spacemacs) --> refreshing package archive: melpa... [1/3]
> Contacting host: melpa.org:443 [2 times]
> Package refresh done
> (Spacemacs) --> refreshing package archive: org... [2/3]
> Contacting host: orgmode.org:80 [2 times]
> Package refresh done
> (Spacemacs) --> refreshing package archive: gnu... [3/3]
> Contacting host: elpa.gnu.org:443
> Package refresh done
> Fetcher: file
> Source: nil

this happens much less often, but sometimes the messages buffer shows this:

> (Spacemacs) --> refreshing package archive: melpa... [1/3]
> Contacting host: melpa.org:443
> Package refresh done
> Failed to download ‘melpa’ archive.
> (Spacemacs) --> refreshing package archive: org... [2/3]
> Contacting host: orgmode.org:80
> Package refresh done
> Failed to download ‘org’ archive.
> (Spacemacs) --> refreshing package archive: gnu... [3/3]
> Contacting host: elpa.gnu.org:443
> Package refresh done
> Failed to download ‘gnu’ archive.
> Fetcher: file
> Source: nil

### Is the spacemacs-theme not installed?

When i check the `paradox-list-packages` <kbd>SPC a k</kbd> buffer, and search for "spacemacs-theme", then it's status shows as "available". Shouldn't it say "Installed"? 

Isn't `spacemacs-theme` the default theme in Spacemacs? Pressing <kbd>SPC T n</kbd> works to cycle between the `spacemacs-dark` and `spacemacs-light` themes, so they seem to be installed.

### Tested
I renamed my previous `.spacemacs` file so that a new one was created automatically and the same thing still happens, so i don't think it's a setting i have made.

I tried installing the `spacemacs-theme` in the `*paradox*` buffer, but when i restarted emacs, then the `spacemacs-theme` gets uninstalled:

> (Spacemacs) --> deleting spacemacs-theme... [1/1]
> Package ‘spacemacs-theme-20170217.1753’ deleted.

When i look in the \*paradox \* buffer, then it's shown as `available` again.

At the bottom the `.spacemacs` file, in the `dotspacemacs/emacs-custom-settings` function, under 
`package-selected-packages`, there the first item it lists is `spacemacs-theme`, i'm not sure what it means for a package to be selected.

### Notes
It doesn't seem to be an issue with updating packages because 4 packages were updated yesterday:
- git-link
- helm
- use-package
- yasnippet

in the `*Packages*` buffer, `helm` is is listed as a `dependency`, the rest as `installed`.

So maybe updating packages isn't looking for updates from the `spacemacs-theme` because it's listed as `available`.

Before posting this i tried updating the packages a last time and the `use-package` updated again.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 3072e727)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by bmag** [comment]
In develop branch, Spacemacs now provides a copy of `spacemacs-theme` package instead of installing from MELPA. This is done so that the theme is available earlier in the startup process and also if there are problems during startup or during package installation. The downside is that we need to update the copy manually.

**Comment by duianto** [comment]
Improving the startup and package reliability definitely outweighs, the theme being updated automatically.
