### ISSUE TITLE
slime-connection: Not connected.

### ISSUE THREAD

**Issue by jnc-nj** [syl20bnr/spacemacs#8405]
#### Description
I'm having trouble with the `M-x slime` command. I get the following message:

`Polling "/var/folders/ns/2m50w6j95_50dw3v634wr2200000gn/T/slime.79195" .. 31 (Abort with ‘M-x slime-abort-connection’.)
`

`inferior-lisp` launches fine.

If I try to call components of slime while inferior-lisp is open it'll either be greyed out or message me `slime-connection: Not connected.`

I've tried looking through the FAQ, Documentation, and the search on Issues here, but nothing has worked thus far. Running on `emacs --insecure` on a fresh environment (i.e. removing everything in elpa) with slime deleted from the root directory isn't clearing the issue either.

Edit:

I'm running on OS X 10.9.5 with CCL as my inferior-lisp.
I'm not sure about reproducing the problem, since this seems to be a general emacs problem, based on the search results from google. Most suggest modifying the .emacs file, which can't be done in this case. I've tried doing the same modifications to user-config, but that hasn't helped either.

Post-install system info:
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp common-lisp colors
     (colors :variables colors-enable-nyan-cat-progress-bar t)
     search-engine themes-megapack spotify chinese
     (chinese :variables chinese-enable-fcitx t)
     (chinese :variables chinese-enable-youdao-dict t)
     spacemacs-layouts org syntax-checking)
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by carlosdagos** [comment]
I'm experiencing the same. Has there been any update?

**Comment by xz-dev** [comment]
You need manually run slime command first.
![图片](https://user-images.githubusercontent.com/32761048/170722486-662e47b9-b449-439e-aa52-e5c9365c6d63.png)
Or use slime-connect to connect to exist slime.
But I think it should auto, like python support etc.
Can't believe lisp support from spacemacs is so bad.
