### ISSUE TITLE
fasd layer and helm

### ISSUE THREAD

**Issue by theolaurent** [syl20bnr/spacemacs#8409]
Shouldn't the fasd layer rely on [helm-fasd](https://github.com/ajsalminen/helm-fasd) for queries ?

**Comment by bmag** [comment]
Not necessarily. According to #783 we already use `helm` for completing `fasd` commands. I don't use `fasd`, but according to the current layer's code, "fasd layer isn't using helm" is supposed to be a false statement.

AFAICT, helm-fasd isn't maintained or developed at all (3 commits total, last one a year ago), so I think we shouldn't rely on it anyway. It does use update the fasd database when a file is opened (via `find-file-hook`) or a directory is visited (via `dired-mode-hook`). That would be nice to have, although I do not know if `fasd` package doesn't already provide similar functionality. If anyone wants to investigate further, go ahead.

**Comment by theolaurent** [comment]
Ok, my mistake. Fasd layer indeed uses helm.
The advantages of helm-fasd is that you don't have to provide an initial query. Maybe it is possible to get this feature ?

About updating the fasd database, I think this is provided in the fasd package used by the layer.

**Comment by theolaurent** [comment]
For the sake of argument, what would be the consequences of always calling fasd with an empty query (getting all the results) and using only helm for filtering?

**Comment by bmag** [comment]
> what would be the consequences of always calling fasd with an empty query (getting all the results) and using helm for filtering?

I don't know. Helm is supposed to handle big amounts (IIRC at least 10k) of candidates quite well. Someone more familiar with fasd could give a better answer.

> The advantages of helm-fasd is that you don't have to provide an initial query. Maybe it is possible to get this feature ?

Perhaps [upstream](https://github.com/steckerhalter/emacs-fasd) is a better place to ask for this feature, so it will be available to more end-users when it's implemented.
