### ISSUE TITLE
The text-object "iw" includes trailing and preceding newlines

### ISSUE THREAD

**Issue by juhanikataja** [syl20bnr/spacemacs#8410]
The text-object `iw` includes trailing and preceding newlines unlike vim. For example:

```
foo
 <ciw>  bar
```
will become
```
foobar
```
instead of
```
foo
bar
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 0c8af96)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby yaml vimscript markdown helm auto-completion emacs-lisp git org sr-speedbar gtags)
```

**Comment by bmag** [comment]
worth reporting upstream if this reproduces with only stock emacs+evil
