### ISSUE TITLE
[Evil] setting `evil-bigword`?

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#8411]
`(setq evil-bigword "^ \t\r\n()[]{}")` does not work.

**Comment by Marlex31** [comment]
I have encountered the same problem, is there a solution?

The same issue seems to have been raised here:
[https://bytemeta.vip/repo/emacs-evil/evil/issues/1450](https://bytemeta.vip/repo/emacs-evil/evil/issues/1450)

**Comment by lebensterben** [comment]
@Marlex31 

Seems like an upstream problem.
