### ISSUE TITLE
Upgrading restart-emacs package breaks "restart after upgrade" as documented

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#8419]
#### Description :octocat:
Restart `SPC q r` stops working and can not restart after upgrading packages.
While the message says 
> Emacs has to be restarted to actually install the new version of the packages (SPC q r)

it doesn't actually work.

#### Reproduction guide :beetle:
- Start Emacs
- (presumably) wait until there's an update to `restart-emacs` package
- update packages
- restart emacs with `SPC q r` as instructed

*Observed behaviour:* :eyes: :broken_heart:
Cannot open load file: No such file or directory, restart-emacs

*Expected behaviour:* :heart: :smile:
Restart.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp
      (auto-completion :variables auto-completion-enable-help-tooltip t)
      (c-c   :variables c-c  -enable-clang-support t)
      (colors :variables colors-colorize-identifiers 'variables)
      dash docker elixir
      (elm :variables elm-sort-imports-on-save t)
      ess git go graphviz
      (haskell :variables haskell-enable-ghc-mod-support t haskell-process-type 'stack-ghci)
      html javascript javascript-flow lua markdown org
      (osx :variables osx-use-option-as-meta nil)
      outshine
      (puppet :variables puppet-use-smie t)
      python react restclient rust semantic syntax-checking version-control yaml)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by duianto** [comment]
I also noticed this issue.
A solution seems to be discussed here:
Delete packages on startup rather than before restarting #6583

There's also this PR that removes the key binding `(SPC q r)` suggestion when the `restart-emacs` package is being updated:
Don't suggest `SPC q r` if restart-emacs is missing #7760
But it didn't work, since the key binding was visible.

**Comment by kini** [comment]
Hmm.  My PR worked at the time, but perhaps something has changed since then...

**Comment by bmag** [comment]
Perhaps we should require `restart-emacs` packages before deleting packages. Something like `(require 'restart-emacs nil t)` in the correct place, then for controlling the prompt we can test `(featurep 'restart-emacs)`.

**Comment by antoszka** [comment]
Confirming this problem.

**Comment by JonasDralle** [comment]
I'm no emacs dev but how about offering restart capabilities without relying on `restart-emacs`? Maybe inform the user that custom shutdown hooks might not be called or something

**Comment by thecountoftuscany** [comment]
Confirming this issue for `spacemacs 0.200.13` and `emacs 24.5.1`.
