### ISSUE TITLE
How to add a package? (Beginner question)

### ISSUE THREAD

**Issue by feigaoxyz** [syl20bnr/spacemacs#8421]
I have just started using Spacemacs and I am sorry if this is a stupid question.

The problem is that I want to use this [package](https://github.com/dpo/ampl-mode/blob/master/emacs/ampl-mode.el) for AMPL language support.

1. I have compiled the `ampl-mode.el` by `SPC SPC byte-compile-file` to generate the `ampl-mode.elc`
2. I put the two files in `~/.emacs.d/private/local/ampl-mode` folder
3. I have put/update the following in my `~/.spacemacs`

```
   dotspacemacs-additional-packages '(ampl-mode)
```

4. I open a `ex.ampl` file and try to activate `ampl-mode` with `SPC SPC ampl-mode`. Emacs reports "Cannot open load file: No such file or directory, ampl-mode".

I have also tried to put the files directly under the `.emacs.d/private/local`, but not working either.

What did I do wrong?

**Comment by nixmaniack** [comment]
You need to load this package to be able to use it. `dotspacemacs-additional-packages` will only make sure that package is downloaded by spacemacs (and won't get deleted on next spacemacs run).

You can add following to your `user-config` section in `.spacemacs`to load the package. 
```elisp
(require 'ampl-mode)
```
In case you want to customize this package before using it, I would recommend `use-package`.

**Comment by feigaoxyz** [comment]
thank you very much! `(require 'ampl-mode)` is working! I will also look into `use-package`
