### ISSUE TITLE
Intero minor mode is not automatically loaded on entering haskell-mode.

### ISSUE THREAD

**Issue by louy2** [syl20bnr/spacemacs#8422]
#### Description :octocat:
Intero minor mode is not automatically loaded on entering haskell-mode.

#### Reproduction guide :beetle:
- Start Emacs
- Open a .hs file

*Observed behaviour:* :eyes: :broken_heart:
- There is no λ in mode cluster

*Expected behaviour:* :heart: :smile:
- There is a λ in mode cluster
- There is following log in \*Messages\*
```
Booting up intero ...
Booted up intero!
```

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion better-defaults emacs-lisp git markdown org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking syntax-checking version-control
     (haskell :variables haskell-process-type 'stack-ghci))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by rakyi** [comment]
There is a variable for that.

https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/haskell#completion-support

**Comment by louy2** [comment]
Thank you!
