### ISSUE TITLE
eshell very slow when the shell layer is installed

### ISSUE THREAD

**Issue by MRFaria** [syl20bnr/spacemacs#8430]
#### Description :octocat:
Eshell becomes slow when the shell layer is switched on and even simple commands like 'ls', or even standard file auto-completion can take a couple of seconds to complete.

#### Reproduction guide :beetle:
- Start Emacs
Navigate around big directories and run ls 

*Observed behaviour:* :eyes: :broken_heart:
There can be delays or around 1-2 seconds when executing simple commands.

*Expected behaviour:* :heart: :smile:
eshell without the shell layer just instantly returns from ls and cd

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: nil (rev. 0c8af96)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm semantic python ibuffer auto-completion better-defaults emacs-lisp c-c++ gnus
      (gtags :variables gtags-enable-by-default t)
      org
      (shell :variables shell-default-shell 'eshell))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11

**Comment by olessavluk** [comment]
For me, eshell works fine locally. But it's extremely slow with TRAMP over ssh. Just pressing enter takes about ~5sec.
This issue also reproducible in a clean environment using docker:
 1. start spacemacs container `docker run -ti --name spacemacs spacemacs/emacs25:develop emacs -nw`
 2. open config(`M-m f e d`) and uncomment `shell` layer, and set `shell-default-shell 'eshell`
 3. open something over ssh
 4. press `M-m '` to open `eshell` over TRAMP
 5. press `Enter` several times and see how big the delay is

**Comment by olessavluk** [comment]
Seems like this was cased by `eshell-prompt-extras`, see https://github.com/kaihaosw/eshell-prompt-extras/issues/20

As a temporary workaround you can use this library with disabled git prompt. In order to do this:
  1. remove `eshell-prompt-extras` from `~/.emacs.d/elpa` folder
  2. specify different location in your config:
```elisp
dotspacemacs-additional-packages '(
  (eshell-prompt-extras :location (recipe :fetcher github :repo "olessavluk/eshell-prompt-extras" :branch "nogit"))
)
```
