### ISSUE TITLE
Syntax highlighting breaks in LaTeX mode often 

### ISSUE THREAD

**Issue by exrok** [syl20bnr/spacemacs#8435]
#### Description :octocat:
Syntax highlighting breaks in LaTeX mode often in a large file and going in and out of math money sign blocks, especially when creating new ones, but also when adding the forward slash and backward slash inside of them.

#### Reproduction guide :beetle:
- Start Emacs
- open large tex file
- use a lot of math $$ things with slash character in them with text after them

*Observed behaviour:* :eyes: :broken_heart:
the rest of the buffer will get stuck in math mode. Saving, killing the buffer resolves this.

*Expected behaviour:* :heart: :smile:
syntax highlighting will stay the same

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust auto-completion emacs-lisp racket latex html c-c   search-engine javascript themes-megapack theming python org spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by exrok** [comment]
Apparently this is a known Upstream Problem in AucTeX: https://www.gnu.org/software/auctex/manual/auctex/Known-problems.html

**Comment by braham-snyder** [comment]
this is also a duplicate of https://github.com/syl20bnr/spacemacs/issues/7722
