### ISSUE TITLE
Helm / Ivy

### ISSUE THREAD

**Issue by jvillasante** [syl20bnr/spacemacs#8437]
I really want to use Ivy/Counsel instead of Helm but it feels that Helm is still much more mature than Ivy.

Recently I started using the slack layer which is great!
Now, if you want to upload a picture to a channel you call `slack-file-upload` and then the completion framework of choice pops up and it lets you select the channel. The thinking is that you should be able to upload a file to more than one channel, so the completion framework enters a loop on which you select the channel for the upload. In Helm, you just type `C` + `RET` to break out of the loop and go on with the upload. With Ivy I can't find a way to get out of the loop. Does anybody knows a way?

Also, it seems that Spacemacs uses Helm at the core, even with Ivy I can see some helm related packages installed. Can it be in the future that everything that helm does now can be done with Ivy/Counsel and we can get rid of the Helm dependency if we choose to?

I really like Ivy, hope it can completely replace Helm in the future!

**Comment by Stebalien** [comment]
> Can it be in the future that everything that helm does now can be done with Ivy/Counsel and we can get rid of the Helm dependency if we choose to?

Have some free time?

* [ ] Tricky: The `ivy` layer itself pulls in `helm-make`. `helm-make` actually supports ivy internally (it's even written by the author of ivy) but requires helm at the package level. You may be able to convince the author to drop the hard dependency on helm (or split the package into `completion-make-common`, `helm-make`, `ivy-make`) but none of those solutions are both clean and easy.
* [ ] Easy: The `bibtex` layer pulls in `helm-bibtex` unconditionally. It should use `ivy-bibtex` (in the same git repo) when appropriate.
* [ ] Requires Work: Several layers pull in `emoji-cheat-sheet-plus` (which pulls in `helm`). You could send a PR upstream to use ivy. Alternatively, you can just globally exclude this layer.
