### ISSUE TITLE
after-init-hook not run ...

### ISSUE THREAD

**Issue by deech** [syl20bnr/spacemacs#844]
When I start Emacs with:

```
emacs -q -l ~/.emacs.d/init.el
```
The `after-init-hook` is never reached. This can be verified by using the command above and typing `SPC-:` to invoke `helm-execute-extended-command` and getting an `SPC : undefined` error.

When I moved my old `.emacs` file out of the way and started it with just: `emacs`. This and some other problems I've been having just disappear.

**Comment by syl20bnr** [comment]
This is expected. `emacs -q` is the same thing as having

**Comment by deech** [comment]
Ah. That's clear. It took me a while to figure it out so maybe having it in a list of FAQ's might help the next person. Thanks!

**Comment by syl20bnr** [comment]
I reopen to add it to the FAQ

**Comment by syl20bnr** [comment]
FAQ added in develop
