### ISSUE TITLE
would be possible improve the selection in expand region?

### ISSUE THREAD

**Issue by cocodrino** [syl20bnr/spacemacs#8440]
Hi guys, something than I love about intellij is how smart it is when you expand the region, maybe you need repeat the keystroke a few more times but you'll always end selecting the right region...for instance

```go
func serveWs(w http.ResponseWriter, r *http.Request) {
	ws, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		if _, ok := err.(websocket.HandshakeError); !ok {
			log.Println(err)
		}
		return
	}

	var lastMod time.Time
	if n, err := strconv.ParseInt(r.FormValue("lastMod"), 16, 64); err == nil {
		lastMod = time.Unix(0, n)
	}

	go writer(ws, lastMod)
	reader(ws)
}

```

in spacemacs if you put the coursor before func and expand the region you'll get
1) the word func is selected
2) the entire block is selected

would be better
1) the word func is selected
2) the words func serverWs is selected
3) the function name and arguments are selected
4) the entire block
I've many more examples but I think than the idea is clear, I think than would be something like this
expand to right until found an space, a comma, a semicolon or a close parenthesis, in the case of parenthesis is a bit special because only expand when in the other side also can expand to the parent parenthesis (or brace)
expand to the left until found space,comma or open parenthesis 

spaces and words has a high priority so when you expand a region and it has spaces around the selection always expand 
commas,semicolons and parenthesis has low priority so for instance

(|word| xx xx  )

considering than |word| is the only selection and you press expand must be expand first to the right
(|word xx| xx)
(|word xx xx|)
|(word xx  x)|

what do you think about this?..would be possible improve this?..thank you!

**Comment by dangom** [comment]
I think this is something you should discuss upstream:
https://github.com/magnars/expand-region.el

Spacemacs defines nothing but the keybindings and the package management for expand-region. It does not implement the functionality afaik.
