### ISSUE TITLE
Spacemacs update blocked by Chinese layer.

### ISSUE THREAD

**Issue by DCPRevere** [syl20bnr/spacemacs#8441]
#### Description :octocat:
Updating Spacemacs throws an error due to the presence of `~/.emacs.d/pyim`.
The directory is created as part of normal use of the  intl/chinese layer.

#### Reproduction guide :beetle:
- Start Emacs
- Install the `chinese` layer.
- Backup and then delete `~/.emacs.d/pyim` if it exists.
- Run `set-input-method`, choosing `chinese-pyim`.
- Ignore the error that no dictionary is exists.
- Type some Chinese words into `*scratch*` ("xiexie", for example), using numbers to select the correct characters.
- Run Spacemacs update.

*Observed behaviour:* :eyes: :broken_heart:
```
Getting version information...
Your Emacs directory is not clean.
git status:
?? pyim/
Warning (emacs): Chinese-pyim 没有安装词库，请运行词库管理命令 `pyim-dicts-manager' 来安装词库。
```

The directory `~/.emacs.d/pyim` exists.

*Expected behaviour:* :heart: :smile:
Spacemacs updates as usual.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: nil (rev. 38d0760)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 (chinese :variables chinese-enable-youdao-dict t)
 colors clojure csharp docker emacs-lisp emoji git go gtags helm html java javascript latex
 (markdown :variables markdown-live-preview-engine 'vmd markdown-command "pandoc")
 (org :variables org-enable-reveal-js-support t)
 octave pandoc pdf-tools python
 (ranger :variables ranger-show-preview t)
 ruby scala
 (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/bin/zsh")
 shell-scripts
 (spell-checking :variables spell-checking-enable-by-default nil)
 sql syntax-checking themes-megapack vagrant version-control vimscript windows-scripts xkcd yaml ycmd)
```

#### Backtrace :paw_prints:
```
```

**Comment by d12frosted** [comment]
@DCPRevere if you are using `develop` branch, you should update, the fix for your issue is there 😄
