### ISSUE TITLE
Fontification error in org-mode R code blocks caused by ess layer

### ISSUE THREAD

**Issue by elandx** [syl20bnr/spacemacs#8448]
#### Reproduction guide
- Start fresh-installed Spacemacs (master branch)
- Enable `ess` and `org` layers
- Restart to install needed packages
- Open org-fle with R source code block

*Observed behaviour:* 
- Fontification of R code blocks is broken and the error messages apper
  `org-mode fontification error in #<buffer bla-bla.org> at xxx`
- After removing `ess` layer and instlling ess and related packages
  (adding to `dotspacemacs-additional-packages`) all works as expected.

*Expected behaviour:*
- Normally fontified blocks

#### System Info
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp ess org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by elandx** [comment]
Commenting out the line 
`(add-hook 'ess-mode-hook 'spacemacs/run-prog-mode-hooks)`
in `ess/packages.el` i get fontification working.

Meanwhile i was faced with the following problem (unrelated to this one).  `Evaluation of this R code block is disabled` after `C-c C-c` on the R-code block...

**Comment by jia-j-chen** [comment]
> Commenting out the line `(add-hook 'ess-mode-hook 'spacemacs/run-prog-mode-hooks)` in `ess/packages.el` i get fontification working.

This issue happens to me today. I am not sure how to implement this solution. Where can I find this line?
