### ISSUE TITLE
How to simulate ESC keypress in ansi-shell?

### ISSUE THREAD

**Issue by Somelauw** [syl20bnr/spacemacs#8451]
Steps to reproduce:
1. Open ansi-term shell by <SPC>ast
2. $ vim
3. i or any command that brings you into insert mode

Now how to escape to normal mode?
- ESC or C-[ already brings evil to normal mode without passing ESC to the shell
- C-q ESC leaves a ^ in the vim buffer, then brings evil to normal mode
- C-c ESC prompts for repeat-complex-command

The only thing I have found to work so far is:
1. Switch to emacs mode
2. Press ESC (twice)

Is there an easier way to simulate <ESC> and if not, should there be?

**Comment by CeleritasCelery** [comment]
I know this is a non-answer, but why do you need to open vim inside Emacs that is already running evil? You now have two layer of modualarity, insert state in insert state. 
However you should be able to fix this with
`(evil-set-initial-state 'term-mode "emacs")` which will disable evil in `term-mode` buffers.

**Comment by Somelauw** [comment]
@CeleritasCelery Well, there are two reasons:

1. I haven't figured out how to open a file from shell in the existing emacs frame.
I can type

```
$ emacs filename
```

But that opens a new Emacs frame, but I want to use the existing frame. If you know a trick around this, let me know.

2. I may need to use ESC in other shell programs.

Thanks for the work-around. Ideally though, I want to use evil in line-mode and emacs in char-mode.

**Comment by CeleritasCelery** [comment]
`C-c C-f` will open the file at point in `term-mode`. If you are using `emacsclient` can also use `emacsclient -n` to open the file in your current Emacs frame. 

What other applications are you using that require the escape key?

**Comment by Somelauw** [comment]
@CeleritasCelery 
Thanks, emacsclient -n works. I'll probably need to define some alias for that.

C-c C-f doesn't look at file at point for me and doesn't even respect the current working dir in my shell. I'm using zsh.

**Comment by CeleritasCelery** [comment]
Yes, term has a hard time tracking your directory (one the reasons I don't use it). You can look [here](https://www.emacswiki.org/emacs/ShellDirtrackByPrompt) for a solution to that if you want. 

You can also rebind the escape sequence of vim by adding `inoremap fd <esc>` to your .vimrc, which is [highly recommended](http://vim.wikia.com/wiki/Avoid_the_escape_key).

If you feel that your questions has been addressed you can close this issue.

**Comment by Somelauw** [comment]
Thanks

**Comment by singpolyma** [comment]
For future people who land here from google like I did: https://emacs.stackexchange.com/a/58115/28569
