### ISSUE TITLE
Why sudo is required to start spacemacs?

### ISSUE THREAD

**Issue by bitmingw** [syl20bnr/spacemacs#8456]
I am using spacemacs in ubuntu 14.04. The version is `0.200.7@25.1.1`. Whenever I type `emacs` in the terminal, the original GNU emacs is up. To start spacemacs I have to use `sudo emacs`. There is no error caught by `--debug-init` flag. Can someone explain why sudo is needed to start spacemacs?

**Comment by sebhahn** [comment]
Maybe a problem with your PATH variable or in which home directory did you
clone spacemacs (and who is owning this direcotyr)?

**Comment by bitmingw** [comment]
spacemacs is cloned to `$HOME/.emacs.d`. I override `$LOGNAME` variable so `/home/$LOGNAME` is not the same as `$HOME`. After `$LOGNAME` is changed to the same name as my home folder, I can run spacemacs without sudo. Wired behavior.

**Comment by bmag** [comment]
sudo is not required to start Spacemacs. In fact, **you shouldn't run Spacemacs with sudo**.

Make sure that `$HOME/.emacs.d` and everything in it is owned by your user, and remove `$HOME/.emacs` if you have one.

**Comment by bitmingw** [comment]
@bmag I believe emacs compares `$LOGNAME` with the owner of `$HOME/.emacs.d` to determine whether to load those files. In my case it happens to be inconsistent.

**Comment by bitmingw** [comment]
This is not a bug, thanks everyone.

**Comment by bmag** [comment]
@bitmingw for posterity, can you tell us how you resolved the problem?

**Comment by bitmingw** [comment]
@bmag I disabled the override of `$LOGNAME` in my `.zshrc` file and then spacemacs worked fine.
