### ISSUE TITLE
feature request: go-layer automatically import golang package

### ISSUE THREAD

**Issue by cocodrino** [syl20bnr/spacemacs#8459]
Hi, good day, I really like a feature in atom/vscode golang package where I just need type my code and the editor automatically import the necesary packages, i.e

```go

e := echo.New() 
jwtMidleware := jwtmiddleware.New()

and magically appears at the top of the file 

import (
	jwtmiddleware "github.com/auth0/go-jwt-middleware"
	"github.com/labstack/echo"
) 


```

I think than it could be achieve using this package https://godoc.org/golang.org/x/tools/cmd/goimports
although I'm not so much experience writing emacs code

thank you so much

**Comment by vadimi** [comment]
@cocodrino it already does it. Please see the doc here:

https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/go#configuration

**Comment by TinySong** [comment]
strongly suggest close this issue

**Comment by cocodrino** [comment]
thank so much @vadimi, I didnt know that
