### ISSUE TITLE
Spacemacs hangs frequently.

### ISSUE THREAD

**Issue by ruiyang** [syl20bnr/spacemacs#8462]
#### Reproduction guide :beetle:
- Start Emacs
- Keep using it
- It freezes after using for sometime.

*Observed behaviour:* :eyes: :broken_heart:
- It freezes after using for sometime.
- I have 8 cores, one core usage is 12%, which is 100% usage of one core
- Memory usage is fine.
- I have to kill spacemacs and restart it to continue.
- It happened once when I tried to C-x b (helm-buffers-list).
- It happened once when I try to type a command in clojure repl.

*Expected behaviour:* :heart: :smile:
It should not freeze.

#### System Info :computer:
- OS: windows 7 and Ubuntu
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
     ruby
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     helm
     auto-completion
     ;; better-defaults
     emacs-lisp
     git
     markdown
     org
     (shell :variables
             shell-default-height 30
             shell-default-position 'bottom)
;;     '((syntax-checking :variables syntax-checking-enable-by-default nil))
     version-control
     javascript
     react
     clojure
     ryang-custom
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace :paw_prints:

**Comment by ruiyang** [comment]
I suspect it was caused by helm. is there a way to disable the helm?

**Comment by ruiyang** [comment]
It hanged again on my windows 7 machine when I tried to do C-r to search in a eshell buffer.
Not sure now if it is related to helm or not.

Any tips for me to get a dump of what is happening in emacs itself?

Unfortunately my working environment is windows 7 virtual machine. It is slower than native. But the hanging also happened in my native Ubutntu machine.

**Comment by goFrendiAsgard** [comment]
To make sure whether it is related to helm or not, try to use `ivy` instead of `helm`.
I don't sure how to do this correctly tough. Probably one of these:
* Delete `~/.spacemacs`, and start it again. This time, choose `ivy` instead of `helm`
* Modify `~/.spacemacs`, go to `dotspacemacs/layers` section, replace `helm` instead of `ivy`.

Also, have you try to run `emacs` as `daemon`?
I'm using ubuntu, and trying this:
`emacs --daemon && emacs`
More info: https://www.emacswiki.org/emacs/EmacsAsDaemon

**Comment by et2010** [comment]
You can try to debug this following this answer:
http://emacs.stackexchange.com/a/507/12431

I also expericenced same issue. When it hangs, usually hit <kbd>C-g</kbd> will bring it back, if not, it's probably caused by c code error. If you're on linux, you can try this:
```sh
kill -SIGUSR2 <emacs_pid_goes_here>
```
hopefully emacs 

> will break out of its current loop into the Lisp debugger
All credits goes here: http://emacs.stackexchange.com/questions/506/debugging-a-frozen-emacs
.

**Comment by bmag** [comment]
> To make sure whether it is related to helm or not, try to use ivy instead of helm.
I don't sure how to do this correctly tough.

Remove `helm` layer from list of enabled layers and add `ivy` layer instead.

**Comment by et2010** [comment]
My spacemacs hangs again, and I use `kill -SIGUSR2` and get following debug trace back:
```
Debugger entered--entering a function:
* eval((spaceline-ml-main))
  redisplay_internal\ \(C\ function\)()
  recursive-edit()
  debug(lambda)
* linum-after-scroll(#<window 66 on *Backtrace*> 3837)
  redisplay_internal\ \(C\ function\)()
  recursive-edit()
  debug(error (quit))
  redisplay_internal\ \(C\ function\)()
```
I guess it's linum? I'll try disabling linum and keep watching

**Comment by ruiyang** [comment]
I replaced helm with ivy, but I also disabled auto-complete. will see how it goes on my Windows machine. It is a virtual machine in working place.

**Comment by ruiyang** [comment]
I disabled autocomplete and helm. it happened less often, but still happened once in a day. The following is the output of dump file opened with WDK.

SYMSRV:   is not a valid store
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for ntdll.dll - 

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  PDB not found : SRV*https://msdl.microsoft.com/download/symbols

The following location did not respond and were excluded during symbol loading:
cache*

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for KERNELBASE.dll - 
ntdll!ZwWaitForMultipleObjects+0xa:
00000000`77bdc2ea c3              ret

************* Symbol Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\srcsrv


Anyone could help to how I could get more detailed info? seemed that I don't have some symbols.
I downloaed Windows Symbol file. but not sure where it is installed to.
https://msdn.microsoft.com/en-gb/library/windows/hardware/ff551035(v=vs.85).aspx

Any help would be appreciated.

**Comment by CeleritasCelery** [comment]
@et2010 look at #4730 which deals with ediff freezing. different people have found different solutions. But somethings that seem to work are `(setq dotspacemacs-mode-line-unicode-symbols nil)`, `(setq ediff-window-setup-function 'ediff-setup-windows-default)`, or excluding the `spaceline` package. All the freezes can be traced back to `redisplay_internal`. Unfortunately I don't think there is the expertise within the Spacemacs community to comprehend this problem and resolve it.

**Comment by et2010** [comment]
@CeleritasCelery Thanks for the tip. It's good to know it's not just me having this problem.

**Comment by TheBaronHimself** [comment]
I'm  having similar issues: 

- Sometimes it freezes entirely and I have to kill it. 
- Oftentimes it stutters when navigating through a document or even when typing and doesn't react for a second or so. 


It's very annoying and makes for a very laggy experience overall. I tried disabling helm, auto-complete, syntax-checking and spell-checking but nothing really solved the issue. 

I'm on macOS/OSX 10.11.6.

**Comment by aleksandar78** [comment]
I'm encountering similar problems with spacemacs. I'm new with spacemacs, not with emacs. I'm trying to use it for simple js projects. Everything works fine until I add git layer and try to call magit to see ustaged files ( M-m g s ). Spacemacs freezes completely. I'm forced to kill it from terminal using htop. I also noticed high number of running processes, very unusual for emacs. 

I've tried almost every possible combination inside user configuration but without success. 

I'm on Manjaro Linux 
Emacs ver. 25.1.4

**Comment by folkwang** [comment]
Similar issue to @aleksandar78 here. Mine hangs when I press `i` inside magit buffer. I have to press `c-g` to bring spacemacs back to life. I suspect it's related to some sort of dynamic loading. Sometimes I encounter freeze over short period of time when I press some specific keys I don't frequently use, and I can see some compilation messages in the bottom line.

And idea on how to debug this issue is appreciated.

**Comment by FiloSpaTeam** [comment]
Same here with Rails project. Freeze if i try to call SPC-p-f to search a file in the project.
I need to kill manually and restart.

**Comment by gone** [comment]
I've been getting a lot of slowdown freezes as well - I wish I could be more helpful. Also on OSX

**Comment by damienrg** [comment]
I encounter a similar problem sometimes when commenting a line (`SPC c l`) and I had to do `kill -SIGUSR2` which gives this [stacktrace](https://pastebin.com/KJqJ92J5).

**Comment by stormpat** [comment]
I upgraded to emacs 25.2 and dropped helm for ivy. I have not seen a freeze since. Also on OSX (using emacs-plus via brew).

**Comment by stormpat** [comment]
Ok so the freezing is back. It makes Emacs almost unusable. I deleted lots of layers (i rarely use) but the biggest issues seems to be gone with removing auto-completion.

**Comment by sebhahn** [comment]
I've experienced similar problems that from one moment to the next the Emacs process needs 100% of one CPU and doesn't react anymore. I'm running Emacs from the Terminal now, which never froze so far.

**Comment by FiloSpaTeam** [comment]
You think that can be related to UI?

**Comment by sebhahn** [comment]
I don't know, but it never happened in the terminal so far.

**Comment by CeleritasCelery** [comment]
From what I have seen this is a "GUI only" problem

**Comment by FiloSpaTeam** [comment]
Oh :(

**Comment by chenyangguang** [comment]
@CeleritasCelery , I found it appear also when i startup with `emacs -nw `  command

**Comment by CeleritasCelery** [comment]
@FiloSpaTeam Yeah this bug always seems to come back to unicode

**Comment by FiloSpaTeam** [comment]
Oh damn...

**Comment by leezu** [comment]
@fredRos have you tried deleting `.emacs.d` and cloning it again from github? That solved the problem for me as it forces the recompilation of all packages.

**Comment by fredRos** [comment]
I have done it now and I only had one freeze when I used tramp. But that package often leads to a hang, so it seems with ivy the issues are gone. Now I have to learn to master ivy :cry:

**Comment by leezu** [comment]
@fredRos I was mentioning it as that also fixed the hangs for me when using helm. So perhaps its worth trying that again, or indeed you can just continue with ivy.

**Comment by pfaure** [comment]
Deactivated version-control layer and had no more hangs.

**Comment by fredRos** [comment]
For me, the problem had nothing to do with ivy or helm, it was about unicode symbols. In `dotspacemacs/init`, I set 

```lisp
   ;; If non nil unicode symbols are displayed in the mode line. (default t)
   dotspacemacs-mode-line-unicode-symbols nil
```

and that solved all problems for me. I went back to helm and didn't have a freeze either

**Comment by cweill** [comment]
I'm running the develop branch at commit 0fa3658cd8e283825dcd0a54ce1579dec55eb568. For me the fix was to disable starting an emacs server:

```lisp
;; If non-nil, start an Emacs server if one is not already running.
dotspacemacs-enable-server nil
```
Everything is now running smoothly.

**Comment by MarcoIeni** [comment]
I excluded the package spaceline by editing the .spacemacs file in this way: `dotspacemacs-excluded-packages '(spaceline)` and now it works fine.

The problem now is that the line is very ugly.
Anyone knows how to install a replacement for spaceline or how to personalize the line without using spaceline?

**Comment by fredRos** [comment]
See my comment above on unicode characters. Perhaps that allows you to
continue with spaceline but avoid hangs. It did the job for me!

**Comment by MarcoIeni** [comment]
Thank you, but I have already tried it and it didn't work.

2018-04-24 16:17 GMT+02:00 Frederik Beaujean <notifications@github.com>:

**Comment by MarcoIeni** [comment]
UPDATE: I am using spaceline again and I obtained a stable situation by adding this in my user-config
```
(spaceline-toggle-minor-modes-off)
```
If the method of @fredRos doesn't work for you also try this.

By the way, it will hide the minor modes from your spaceline.

**Comment by Compro-Prasad** [comment]
@Marcoleni https://emacs-fu.blogspot.com/2011/08/customizing-mode-line.html

**Comment by Compro-Prasad** [comment]
@aleksandar78 is your git status too large. It happens if the status is too large.

**Comment by gred7** [comment]
freezes everywhere, freezes everyday, freezes over and over again
emacs 26.1 on OpenBSD
same observed on Ubuntu and Centos. 
no helm, ivy layer is installed.
i need the IDE features, so most of development support layers are installed.

**Comment by gred7** [comment]
I moved to purcell's emacs config. not as good as spacemacs or doom in terms of ease of use, but at least works smooth enough for me

**Comment by ar1a** [comment]
Could be linked to the gc threshold being set massively high

**Comment by timothywangdev** [comment]
same here

**Comment by planetA** [comment]
Try to disable global-linum-mode. For me the situation gets much better.
