### ISSUE TITLE
search after expand region fail with error

### ISSUE THREAD

**Issue by shelper** [syl20bnr/spacemacs#8463]
#### Description :octocat:

when using expand region, "SPC v /" or "SPC v f" fail with error, 

#### Reproduction guide :beetle:

- Start Emacs

- in normal mode, press "SPC v /"

*Observed behaviour:* :eyes: :broken_heart:

fail with error message:
"let: Wrong type argument: commandp, helm-do-grep"

*Expected behaviour:* :heart: :smile:

(%LAST_KEYS%)

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. c42e487)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
```
- System configuration features:

#### Backtrace :paw_prints:
Debugger entered--Lisp error: (wrong-type-argument commandp helm-do-grep)
  call-interactively(helm-do-grep)
  (let ((projectile-require-project-root nil)) (call-interactively (spacemacs//helm-do-search-find-tool "helm-project-do" dotspacemacs-search-tools default-inputp)))
  spacemacs/helm-project-smart-do-search(t)
  spacemacs/helm-project-smart-do-search-region-or-symbol()
  funcall-interactively(spacemacs/helm-project-smart-do-search-region-or-symbol)
  call-interactively(spacemacs/helm-project-smart-do-search-region-or-symbol)
  (lambda nil (call-interactively (quote spacemacs/helm-project-smart-do-search-region-or-symbol)))()
  eval(((lambda nil (call-interactively (quote spacemacs/helm-project-smart-do-search-region-or-symbol)))))
  (lambda nil (interactive) (setq this-command (\` (\, (cadr (quote ("/" (lambda nil ...))))))) (or (minibufferp) (message "%s" "Type v to expand again, V to contract, r to reset, e to edit, / to search in project, f to search in files, b to search in opened buffers")) (eval (\` (\, (cdr (quote ("/" (lambda nil ...))))))))()
  funcall-interactively((lambda nil (interactive) (setq this-command (\` (\, (cadr (quote ("/" (lambda nil ...))))))) (or (minibufferp) (message "%s" "Type v to expand again, V to contract, r to reset, e to edit, / to search in project, f to search in files, b to search in opened buffers")) (eval (\` (\, (cdr (quote ("/" (lambda nil ...)))))))))
  call-interactively((lambda nil (interactive) (setq this-command (\` (\, (cadr (quote ("/" (lambda nil ...))))))) (or (minibufferp) (message "%s" "Type v to expand again, V to contract, r to reset, e to edit, / to search in project, f to search in files, b to search in opened buffers")) (eval (\` (\, (cdr (quote ("/" (lambda nil ...)))))))) nil nil)
  command-execute((lambda nil (interactive) (setq this-command (\` (\, (cadr (quote ("/" (lambda nil ...))))))) (or (minibufferp) (message "%s" "Type v to expand again, V to contract, r to reset, e to edit, / to search in project, f to search in files, b to search in opened buffers")) (eval (\` (\, (cdr (quote ("/" (lambda nil ...)))))))))

```

```

**Comment by bmag** [comment]
Apparently the command `helm-do-grep` was [removed upstream](https://github.com/emacs-helm/helm/commit/013ee11b695f52c68b0a0648dbd143b3592e2ef3) at December 2015, but we still use `helm-do-grep` in `spacemacs//helm-do-search-find-tool`. The solution is to either implement `helm-do-grep` in Spacemacs or find a different existing command to use.

**Comment by longtomjr** [comment]
Related: 
https://github.com/emacs-helm/helm/wiki/Grep
