### ISSUE TITLE
Spacemacs confused about use of auctex-latexmk package

### ISSUE THREAD

**Issue by eullerborges** [syl20bnr/spacemacs#8467]
#### Description :octocat:
Spacemacs doesn't properly install the auctex-latexmk package.

#### Reproduction guide :beetle:
- Start Emacs
- add `latex` to `dotspacemacs-configuration-layers`
- add `(setq latex-build-command "LatexMk")` to  `dotspacemacs\user-config`
- Reload .spacemacs configuration
- Observe message buffer
- Restart spacemacs
- Try building a TeX document.

*Observed behaviour:* :eyes: :broken_heart:
After reloading the spacemacs configuration, an error occurs: `Error (use-package): tex post-:config hook: Cannot open load file: No such file or directory, auctex-latexmk`. 
Restarting spacemacs, the package `auctex-latexmk` gets deleted with the message:
```
Found 1 orphan package(s) to delete...
--> deleting auctex-latexmk... [1/1]
```
Trying to build any TeX document fails with error `Wrong type argument: string, nil`
Sometimes, the installation worked, but on any restart the `auctex-latexmk` package was deleted as an orphan. Now, upon many reinstalls of the layer, it fails.

*Expected behaviour:* :heart: :smile:
Correct installation of the package, and building with LatexMk. 

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 semantic better-defaults themes-megapack osx dash ranger emacs-lisp git version-control markdown gtags cscope org syntax-checking version-control
 (c-c   :variables c-c  -enable-clang-support t)
 gtags latex bibtex python games spotify shell)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by bmag** [comment]
Setting `latex-build-command` in `user-config` is too late. You should set it in `user-init` or in the layer declaration: `(latex :variables latex-build-command "LatexMk")`.

**Comment by eullerborges** [comment]
Thanks a lot, @bmag, that solves it.

**Comment by Blaisorblade** [comment]
Spacemacs 0.200.10 seems to keep installing (as “new package”) and uninstalling (as “orphan”) auctex-latemk even when latexmk is not mentioned at all in `.spacemacs`. @bmag’s suggestion seems to fix the problem.

**Comment by digizeph** [comment]
Spacemacs 0.200.13@25.3.1 still sees this problem, and @bmag's suggestion fixes the problem. Thanks!

**Comment by George9000** [comment]
Spacemacs 0.300.0 continues to have the issue, and the suggestion above by @bmag still fixes it.
