### ISSUE TITLE
elixir-mode: keyword (if) inside of a comment still triggers do ... end insertion

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#8477]
#### Description :octocat:
In Elixir-mode, if I type `if` inside of a line of comment, `do ... end` still gets inserted. I viewed the repo of `alchemist` first but it seems to be a problem introduced by `smartparens`, as indicated by similar issues at https://github.com/tonini/alchemist.el/issues/276 and https://github.com/syl20bnr/spacemacs/issues/8030

Alchemist version: 1.9.0snapshot (package: 20170118.142)

#### Reproduction guide :beetle:
- Start Emacs
- In a buffer with Elixir major mode activated, open a line of comment starting with `#`
- Type `if`
- Type space

*Observed behaviour:* :eyes: :broken_heart:
Code completion is triggered. `do` is inserted on this line and `end` is inserted on the next line.

*Expected behaviour:* :heart: :smile:
The space should be normally inserted and nothing else should happen.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.50
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. b8c9100)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm speed-reading auto-completion better-defaults spell-checking syntax-checking semantic rcirc git github version-control
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/zsh" shell-enable-smart-eshell t)
      typography wakatime chrome restclient dash fasd pandoc colors themes-megapack gtags imenu-list vim-powerline evil-snipe emacs-lisp
      (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "gibiansky")
      elixir org latex markdown python html yaml shell-scripts javascript
      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
      rust)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS LIBSYSTEMD

**Comment by Fuco1** [comment]
This should now be fixed in https://github.com/Fuco1/smartparens/commit/1bf46316558d1bb49d5250bcdd79211cd04ec6d2
