### ISSUE TITLE
Report Spacemacs Issue Fail

### ISSUE THREAD

**Issue by gitfoxi** [syl20bnr/spacemacs#8478]
%23%23%23%23%20Description%20:octocat:%0AOrg-mode%20Screenshot%20needs%20macos%20configuration.%0A%0A%23%23%23%23%20Word-around%0A%0A%60%60%60%0A%20%20(if%20(equal%20system-type%20'darwin)%0A%20%20%20%20%20%20(setq%20org-download-screenshot-method%20%22/usr/sbin/screencapture%20-i%20%s%22))%0A%60%60%60%0A%0A%23%23%23%23%20Reproduction%20guide%20:beetle:%0A-%20Start%20Emacs%20in%20macos%0A-%20Edit%20an%20orgmode%20buffer%0A-%20%60,%20i%20s%60%0A%0A*Observed%20behaviour:*%20:eyes:%20:broken_heart:%0A%22File%20/tmp/screenshot.png%20does%20not%20exist%22%0A%0A*Expected%20behaviour:*%20:heart:%20:smile:%0ATake%20a%20screenshot%0A%0A%23%23%23%23%20System%20Info%20:computer:%0A-%20OS:%20darwin%0A-%20Emacs:%2025.1.1%0A-%20Spacemacs:%200.200.7%0A-%20Spacemacs%20branch:%20lisp-mode-2%20(rev.%2020f8ebd)%0A-%20Graphic%20display:%20t%0A-%20Distribution:%20spacemacs%0A-%20Editing%20style:%20vim%0A-%20Completion:%20helm%0A-%20Layers:%0A%60%60%60elisp%0A(html%20python%20dash%20helm%20auto-completion%20better-defaults%20emacs-lisp%20common-lisp%20osx%20git%20markdown%20org%20spell-checking%20syntax-checking%20version-control%20chrome)%0A%60%60%60%0A-%20System%20configuration%20features:%20JPEG%20RSVG%20NOTIFY%20ACL%20GNUTLS%20LIBXML2%20ZLIB%20TOOLKIT_SCROLL_BARS%20NS%20MODULES%0A

**Comment by bmag** [comment]
You mentioned the problem in #8479. Care to give more details?

**Comment by gitfoxi** [comment]
I was trying to make the report in #8479 from emacs. When I submitted it this is what got copied into the Github Issue text box in Firefox instead. It looks like the text of the issue got URL-encoded or something. It might matter the Firefox version more than anything:

53.0a2 (2017-03-06) (64-bit)

They've made some hostile choices lately ...
