### ISSUE TITLE
C-c C-c is not sending the bug report from Spacemacs

### ISSUE THREAD

**Issue by AlexIljin** [syl20bnr/spacemacs#8487]
#### Description :octocat:
C-c C-c is not sending the bug report from Spacemacs.

#### Reproduction guide :beetle:
- Start Emacs
- Try to report an issue by pressing SPC h I
- Fill in the bug report
- The top line of the buffer instructs you to delete it and press C-c C-c
- Delete the top line and press C-c C-c

*Observed behaviour:* :eyes: :broken_heart:
The status text says "C-c C-c is undefined". Bug report is not sent.

*Expected behaviour:* :heart: :smile:
Bug report is sent.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git org spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by jinyangustc** [comment]
I meet the save problem with a clean install of Spacemacs.

**Comment by bmag** [comment]
I remember there being a similar bug report, but couldn't find one in a quick search.

**Comment by duianto** [comment]
@bmag It might be this one:
Cannot submit in internal issue reporting mode #7907

**Comment by bmag** [comment]
@duianto thanks

**Comment by achikin** [comment]
Was able to reproduce this by removing `markdown` layer https://github.com/syl20bnr/spacemacs/issues/9627

**Comment by rcmosher** [comment]
I'm still seeing this bug in 0.200.13
