### ISSUE TITLE
C-g is assigned to something other than "get me outta here!"

### ISSUE THREAD

**Issue by AlexIljin** [syl20bnr/spacemacs#8488]
#### Description :octocat:
C-g is supposed to be the universal "cancel" hotkey, but it has a binding assigned at SPC p C-g.

#### Reproduction guide :beetle:
- Start Emacs
- Press SPC p

*Observed behaviour:* :eyes: :broken_heart:
- Observe C-g binding at the lower right corner of the screen

*Expected behaviour:* :heart: :smile:
C-g should not be used except as the "cancel current operation" hotkey.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git org spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by duianto** [comment]
This has been fixed in the develop branch: Remove SPC p C-g #7580

**Comment by bmag** [comment]
Closing as duplicate (and it's fixed in develop), but thanks anyway.
