### ISSUE TITLE
Haskell layer causes editing to be slow when file contains a very large expression

### ISSUE THREAD

**Issue by sdemos** [syl20bnr/spacemacs#8489]
#### Description :octocat:
When editing a haskell file that has a very large type expression, the editing responsiveness drops off drastically. I tried disabling intero, and the problem seemed to persist (although I might not have disabled it properly, I'm not sure). The problem also happens when I have a very large function definition, like the one I included in the reproduction guide, and happens whether or not the file can be successfully interpreted (it doesn't need to be a complete haskell file, it can just be a snippet). 

#### Reproduction guide :beetle:
- Start Emacs
- Have an expression like this (it doesn't need to type check) - lpaste.net/353333
- try and edit the file

*Observed behaviour:* :eyes: :broken_heart:
Editing is very slow, like seconds to respond

*Expected behaviour:* :heart: :smile:
Editing to be the normal speed

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults org themes-megapack syntax-checking version-control docker git nginx
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      systemd markdown
      (haskell :variables haskell-completion-backend 'intero haskell-enable-stack-support t)
      emacs-lisp c-c   coq python html extra-langs asm csv elm graphviz java shaders sml sql yaml vimscript latex
      (go :variables go-tab-width 4))
```
- System configuration features: DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB

#### Backtrace :paw_prints:
```
```

**Comment by asheshambasta** [comment]
I'm seeing the same problem with my setup, although I'm not using spacemacs. It seems like an issue with Haskell mode that is trying to write the entire large type in and out, depending on the cursor position. That makes the entire editor feel very laggy. 
I also think the issue has to do with "writing" the large type within emacs, which Haskell mode seems to be doing. 
Maybe there should be a way to 'truncate' these large types? Or maybe, not expand them at all?
