### ISSUE TITLE
Popup warning whenever opening python file

### ISSUE THREAD

**Issue by benneti** [syl20bnr/spacemacs#8492]
#### Description :octocat:
A warning with the content:
"Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support readline, yet ‘python-shell-completion-native’ was t and "ipython" is not part of the ‘python-shell-completion-native-disabled-interpreters’ list.  Native completions have been disabled locally." pops up.
I don't know whether this is a real problem or only annoying, can I just disable this warning in any way?

#### Reproduction guide :beetle:
- Start Emacs
- open python file

*Observed behaviour:* :eyes: :broken_heart:
Display a warning in a pop up window

*Expected behaviour:* :heart: :smile:
function correctly or do not display this warning.

#### System Info :computer:
- OS: gnu/linux (archlinux)
- IPython: 5.1.0
- Python: 3.6.0
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle)
 emacs-lisp git org
 (shell :variables shell-default-shell 'multi-term shell-default-position 'bottom shell-default-height 35)
 (dash :variables dash-helm-dash-docset-path "~/.docsets")
 (spell-checking :variables spell-checking-enable-auto-dictionary t)
 syntax-checking
 (c-c++ :variables c-c++-enable-clang-support t)
 semantic bibtex
 (latex :variables latex-enable-folding t latex-enable-auto-fill t)
 python octave
 (rust :variables racer-rust-src-path "/usr/src/rust/src/")
 shell-scripts html games colors pdf-tools speed-reading systemd evil-cleverparens markdown theming)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by zestyr** [comment]
This is a bug with Emacs 25.1, fixed in newer versions.
If you don't want to update Emacs, the fix is listed here:
http://emacs.stackexchange.com/a/30970

Simply put the following in your user-init or user-config:
```elisp
(with-eval-after-load 'python
  (defun python-shell-completion-native-try ()
    "Return non-nil if can trigger native completion."
    (let ((python-shell-completion-native-enable t)
          (python-shell-completion-native-output-timeout
           python-shell-completion-native-try-output-timeout))
      (python-shell-completion-native-get-completions
       (get-buffer-process (current-buffer))
       nil "_"))))
```

**Comment by benneti** [comment]
thank you, i don't have problem upgrading, I just searched the web for about 2 hours trying to fix it. Should have asked for help earlier.
Thanks again
