### ISSUE TITLE
[go-layer] Symbol's function definition is void: go--position-bytes

### ISSUE THREAD

**Issue by lsytj0413** [syl20bnr/spacemacs#8495]
#### Description :octocat:
[go-layer] Symbol's function definition is void: go--position-bytes

#### Reproduction guide :beetle:
- Start Emacs
- Open go src file
- use [SPC m r n] to rename a variables

*Observed behaviour:* :eyes: :broken_heart:
*Message* Buffer output:
1-: Symbol's function definition is void: go--position-bytes

*Expected behaviour:* :heart: :smile:

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 3072e72)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-sort-by-usage t)
 better-defaults emacs-lisp git markdown org
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 asm
 (python :variables python-sort-imports-on-save t)
 javascript github semantic
 (go :variables go-tab-width 4 go-use-gometalinter t)
 ranger gtags ibuffer sql
 (colors :variables colors-enable-nyan-cat-progress-bar t colors-enable-rainbow-identifiers t)
 (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
 (syntax-checking :variables syntax-checking-enable-by-default t)
 (chinese :variables chinese-enable-fcitx t)
 liter ycmd)
```

#### Backtrace :paw_prints:
```
byte-code: Beginning of buffer [13 times]
(No files need saving)
1-: Symbol's function definition is void: go--position-bytes
Quit
(No files need saving)
1-: Symbol's function definition is void: go--position-bytes
```

**Comment by TinySong** [comment]
@lsytj0413, this bug already fixed, but PR  no merged, you can see #8179
