### ISSUE TITLE
Do not modify .emacs.d when launched with sudo

### ISSUE THREAD

**Issue by gnzlbg** [syl20bnr/spacemacs#8497]
When spacemacs is launched with sudo (e.g. to modify some system files), it will try to update on startup, and modify some files in .emacs.d. 

When it is then relaunched without sudo, and an update is triggered, it will fail spectacularly when trying to remove directories that where created with root permissions. 

I don't know what's the best approach here, but "don't do anything that can change the permissions of .emacs.d files while being run as root" seems the most sensible thing to do. 

Also, disable updating when run as root, and probably display an error if an user tries to update spacemacs while being run as root.

**Comment by bmag** [comment]
AFAIK Emacs doesn't handle root user differently. My best advice is don't run Emacs (or Spacemacs) as root. There are commands in Emacs (and Spacemacs) to open a specific file as root when the need arises, for example `SPC f E` (`spacemacs/sudo-edit`).

**Comment by gnzlbg** [comment]
I did not knew about `sudo-edit`, that sounds like I was just doing the wrong thing.

**Comment by Fuco1** [comment]
For these situations I've written this little piece of code: https://gist.github.com/Fuco1/72451629d89b835143ff26b9c9c48d22
