### ISSUE TITLE
use-package/smartparens Error on Cygwin

### ISSUE THREAD

**Issue by gilch** [syl20bnr/spacemacs#8507]
#### Description :octocat:
Every time I start Spacemacs, a window appears with:
`Error (use-package): smartparens :config: Symbol’s function definition is void: wrap`

#### Reproduction guide :beetle:
- Install Cygwin on Windows with Cygwin emacs and Cygwin git packages.
- Start Cygwin bash.
- Rename the `.emacs.d/` and clone Spacemacs in Cygwin home folder using Cygiwn git on Cygwin bash.
- Start Cygwin emacs from Cygwin bash and do initial setup (evil, helm, and full install).
- Every time you start emacs you see the error.

*Observed behaviour:* :eyes: :broken_heart:
Window with `*Warnings*` buffer appears with
`Error (use-package): smartparens :config: Symbol’s function definition is void: wrap`

*Expected behaviour:* :heart: :smile:
No errors/warnings.

#### System Info :computer:
- OS: cygwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG IMAGEMAGICK SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by gilch** [comment]
I noticed this error in the Windows version too. However, with the latest package update, I can no longer reproduce this issue. It may have already been resolved.

**Comment by aijony** [comment]
Just for a side note, this seems to be #8500.

**Comment by Fuco1** [comment]
It's scary, there was maybe 20 hour window to get this issue and soooo many people were affected :O I guess this got a bit more popular than I thought and I should take more care releasing to master :/
