### ISSUE TITLE
Evil-write inserts a space.

### ISSUE THREAD

**Issue by person808** [syl20bnr/spacemacs#851]
Whenever I save a file using <kbd>:w</kbd>, <kbd>:x</kbd>, and <kbd>SPC f s</kbd>, a space is inserted where the cursor is.

Before:
![screenshot from 2015-03-16 11 11 26](https://cloud.githubusercontent.com/assets/6396431/6676656/a97b0aec-cbcd-11e4-84bb-d35cd510690b.png)

After (see line 128):
![screenshot from 2015-03-16 11 11 05](https://cloud.githubusercontent.com/assets/6396431/6676661/b48e5088-cbcd-11e4-8115-defe16d11973.png)

**Comment by syl20bnr** [comment]
I cannot reproduce, even after update all the packages. It does not seem to come from your dotfile config on the screenshot. What layers are you using ?

**Comment by person808** [comment]
```elisp
(setq-default dotspacemacs-configuration-layers '(colors company-mode evil-commentary (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t) (git :variables git-gutter-use-fringe nil) python themes-megapack)
```
