### ISSUE TITLE
Anaconda-mode error 

### ISSUE THREAD

**Issue by IanQS** [syl20bnr/spacemacs#8517]
#### Description :octocat:
Autocompletion in emacs python layer specifically anaconda-mode isn't autocompleting (because of an error)

#### Reproduction guide :beetle:
- Start Emacs
- open python file
- import some package as sp
- sp (then press TAB or your autocomplete button)

*Observed behaviour:* :eyes: :broken_heart:
no completion with an error message in minibuffer

*Expected behaviour:* :heart: :smile:
Completion with no errors

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. d0464aae)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(markdown javascript
          (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
          (latex :variables latex-build-command "LaTeX" latex-enable-folding t)
          (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-complete-with-key-sequence-delay 0.05 auto-completion-enable-sort-by-usage t)
          (gtags :variables gtags-enable-by-default t)
          python ycmd helm emacs-lisp git
          (shell :variables shell-enable-smart-eshell t shell-default-height 20)
          org syntax-checking version-control spacemacs-completion imenu-list)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:

[Messages buffer]
Server error: ValueError('need more than 0 values to unpack',)

[anaconda-mode buffer]
Traceback (most recent call last):
  File "/home/ian/.emacs.d/.cache/anaconda-mode/0.1.7/service_factory-0.1.5-py3.6.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/ian/.emacs.d/.cache/anaconda-mode/0.1.7/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/ian/.emacs.d/.cache/anaconda-mode/0.1.7/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/ian/.emacs.d/.cache/anaconda-mode/0.1.7/service_factory-0.1.5-py3.6.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "ValueError(\'need more than 0 values to unpack\',)"}}')

**Comment by bmag** [comment]
maybe related: https://github.com/proofit404/anaconda-mode/issues/234

**Comment by cmorgan** [comment]
it's related to this https://github.com/davidhalter/jedi/issues/873
you can resolve by downgrading jedi to v0.9.0
