### ISSUE TITLE
Better buffer navigation.

### ISSUE THREAD

**Issue by AnthonyJacob** [syl20bnr/spacemacs#8519]
Spacemacs buffer have the following problem:

1) It is very hard to remember where will next/previous-buffer command bring you.
2) It is also on very inconvenient shortcut SPC-b-n which is exactly three keystrokes for one buffer. But I typically want to move to the third or fourth buffer.

Therefore I almost never use anything but SPC-TAB and I kill buffers frequently to not go nuts.

So I am wondering whether there could be better system than the current one.

1) There could be a bar with buffer names at the top (similar to any web browser or IDE) that would be shared across all windows (similar to spaceline and powerline).
2) Alt+[0-9] could be used to move between buffers similar to SPC-[0-9] moves between windows or the other way around.

**Comment by NJBS** [comment]
What you describe is similar to tabbar-mode, there isn't an official layer for this yet but googling "spacemacs tabbar" will give you some unofficial layers and configurations you can test out.

Also, try looking at the [ibuffer](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bemacs/ibuffer) layer and see if that helps with your organization woes.

**Comment by fiveNinePlusR** [comment]
one thing that I like to use but it's not perfect is binding ctrl-shift-left and right arrow to buffer next and buffer previous. makes it much quicker to navigate nearby buffers. if you have an org file open you will have to revert to `spc b n` and `spc b p` though or override it in org mode too. 

``` lisp
  ;; faster buffer switching
  (global-set-key (kbd "<C-S-right>") 'next-buffer)
  (global-set-key (kbd "<C-S-left>") 'previous-buffer)
```

I would love for there to be a well executed tabbar mode but the ones that I have found are really bad comparatively.

**Comment by yqrashawn** [comment]
I was using `tabbar-mode` for three months. I disabled it. It kept me from remembering buffer names. I can only remember function names or what does the file do. There's a package called [buffer-flip](https://github.com/killdash9/buffer-flip.el) you may have a look at that. It's depend on key chord. And `imenu-anywhere` is another choice in some cases.

**Comment by untoreh** [comment]
I think a saner alternative to tabs would be a plugin that hooks into like neotree to make a tree of buffers in a firefox tree-style-tabs fashion

**Comment by Miciah** [comment]
If you haven't already tried it, check out the [buffer transient state](http://develop.spacemacs.org/doc/DOCUMENTATION.html#buffers-manipulation-transient-state).  Enter it by pressing <kbd>SPC b .</kbd>, and then press <kbd>n</kbd> and <kbd>N</kbd> (or <kbd>p</kbd>) to move forward and backward through buffers.

**Comment by kazimuth** [comment]
The [treemacs extensions tutorial](https://github.com/Alexander-Miller/treemacs/blob/master/Extensions.org) has an example of something like this, and there's work on a [more robust version](https://github.com/Alexander-Miller/treemacs/issues/326) to be added to master.

**Comment by sdwolfz** [comment]
I've been thinking about this as it sometimes anoys me as well. Maybe integrating something like https://github.com/manateelazycat/awesome-tab and then having a transient state pop up when `SPC b n` would be a better UX?

**Comment by duianto** [comment]
Another tabs package is: https://github.com/ema2159/centaur-tabs

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
[layers/+emacs/tabs] introduces tabs layer with Centaur backend #13907

**Comment by sdwolfz** [comment]
Awesome, I'll work with @WarFox in the following days to improve the key bindings.
