### ISSUE TITLE
scala layer not using stable ensime

### ISSUE THREAD

**Issue by ashic** [syl20bnr/spacemacs#8540]
It appears the scala layer is using ensime 2.0.0-SNAPSHOT, and as such, .ensime files created with sbt ensimeConfig don't work anymore. Is there a way to force it to use 1.12.7?

**Comment by sdwolf** [comment]
See: http://ensime.org//editors/emacs/install/#spacemacs
Also this issue: https://github.com/syl20bnr/spacemacs/issues/6531#issuecomment-232268446

**Comment by ashic** [comment]
Thanks.
