### ISSUE TITLE
 Propose adding hub as an option when you include `git`

### ISSUE THREAD

**Issue by zhexuany** [syl20bnr/spacemacs#8546]
Right now, when you enable `git`, `magit` will be configured for you. It is nice until I found an alternative for `git`. It is `hub`. I think I will be nice we can support this in native `spacemacs`.  

`hub` already has support for emacs.  That is a relief actually. We do not need a lot of work for this. If you want to find more details about how to get `hub`  work in  spacemacs. You can click [this](http://www.zhexuany.com/2017/03/17/use-hub-in-spacemacs/). 

I am intended to add `hub` as a post-configuration for in side `git`.  Is this ok?

**Comment by bmag** [comment]
Thank you, magithub was already added in develop branch last month: https://github.com/syl20bnr/spacemacs/commit/b53a8957a16f3f107a5e8cdc978129bd629a51de :smile:

**Comment by zhexuany** [comment]
@bmag haha. That is really awesome!!!

**Comment by bmag** [comment]
the README is updated in develop branch
