### ISSUE TITLE
man -l not supported on macos

### ISSUE THREAD

**Issue by gitfoxi** [syl20bnr/spacemacs#8549]
#### Description :octocat:
man -l not supported on macos

#### Reproduction guide :beetle:
- Start Emacs
- [Spc h m]
- ls \<return\>

*Observed behaviour:* :eyes: :broken_heart:

    Invoking man -l /usr/share/man/man1/ls.1 in the background
    Can’t find the /usr/share/man/man1/ls.1 manpage

*Expected behaviour:* :heart: :smile:
View a man page

#### Workaroud
customize `helm-man-format-switches` to be "%s" instead of "-l %s"

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: lisp-mode-2 (rev. e956e88a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ranger restclient ipython-notebook imenu-list ibuffer evil-cleverparens colors
        (mu4e :variables mu4e-installation-path "/usr/local/share/emacs/site-lisp/mu/mu4e" mu4e-account-alist t)
        html javascript haskell deft search-engine evil-snipe python dash fasd auto-completion better-defaults emacs-lisp common-lisp osx git markdown
        (org :variables org-enable-github-support t org-enable-reveal-js-support t org-enable-journal-support t org-projectile-file "TODOs.org" spaceline-org-clock-p t)
        shell syntax-checking version-control chrome graphviz
        (markdown :variables markdown-live-preview-engine 'vmd))
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
Hopefully this can be solved upstream by setting the default value of `helm-man-format-switches` to depend on the user's machine. The obvious advantage is that `helm-man` will work out of the box for macOS users. Can you suggest this [upstream](https://github.com/emacs-helm/helm/issues/) please? If they don't want to change the default value, then of course we can make the necessary changes in our config.

**Comment by Miciah** [comment]
The issue has been fixed upstream.  Can this issue be labeled as "Fixed upstream" and closed?
