### ISSUE TITLE
Tooltips flicker or do not work at all [syntax-checking -- flycheck-pos-tip]

### ISSUE THREAD

**Issue by hchapman** [syl20bnr/spacemacs#8551]
#### Description :octocat:
Inclusion of layer syntax-checking pulls in flycheck-pos-tip which makes tooltips flicker instantly (or not work at all)

#### Reproduction guide :beetle:
- Start Emacs
- Ensure syntax-checking layer is included in configuration file
- Execute (tooltip-show "flicker") in scratch or using M-:

*Observed behaviour:* :eyes: :broken_heart:
Tooltip appears and disappears nearly instantly (or doesn't appear at all)

*Expected behaviour:* :heart: :smile:
Tooltip shows at mouse cursor for length of time given in settings (a few seconds)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.50
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. e624e8f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(yaml auto-completion better-defaults emacs-lisp git markdown org c-c   bibtex html pdf-tools javascript cscope
      (latex :variables latex-enable-auto-fill nil latex-enable-folding t)
      visual-fill python lua semantic spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS LIBSYSTEMD

#### Backtrace :paw_prints:
```

```

**Comment by LdBeth** [comment]
It is because that `flycheck-pos-tip` added a hook to cancel the display of pos-tip every time at the end of calling a function.

You can use something like this to avoid this annoying problem.
```
(run-at-time 0.1 nil #'pos-tip-show string nil nil nil -1))
```

Or you can just exclude `flycheck-pop-tip` if you don't think it is necessary.

**Comment by yqrashawn** [comment]
Same problem. Is there any solution other than disable it?
