### ISSUE TITLE
Magithub not initializing properly

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#8561]
#### Description :octocat:
Magithub is not initializing

#### Reproduction guide :beetle:
- Make sure `hub` is installed and configured as [described in documentation](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+source-control/github/README.org#hub-configuration).
 Running following should open Spacemacs github page:

      cd  ~/.emacs.d
      hub browse

- Start Emacs
- `SPC f i`
- `SPC g s`

*Observed behaviour:* :eyes: :broken_heart:
- Issues and Pulls are not shown in magit-status buffer
- `magithub-feature-autoinject` is void 

*Expected behaviour:* :heart: :smile:
- Issues and Pulls should appear in magit-status buffer automatically
- pressing `@` in magit-status buffer should open magithub dispatch

*Workaround:*
Explicitly running `(require 'magithub)` fixes it

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. c9d332fb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((org :variables org-enable-reveal-js-support t org-enable-bootstrap-support t org-enable-github-support t :packages
      (not org-present))
 csv yaml emacs-lisp javascript
 (html :packages
       (not pug-mode slim-mode))
 (markdown :variables markdown-live-preview-engine 'vmd)
 (shell-scripts :packages
                (not fish-mode))
 clojure lua haskell
 (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 syntax-checking spell-checking helm
 (shell :variables shell-enable-smart-eshell t comint-scroll-show-maximum-output nil comint-move-point-for-output nil)
 fasd
 (ibuffer :variables ibuffer-old-time 8)
 osx restclient emoji search-engine imenu-list docker git
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 (github :packages
         (not magit-gh-pulls)
         :variables gist-view-gist t)
 ag-dired ag-general ag-dash ag-synonyms ag-org ag-clojure ag-cal)
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by planigan** [comment]
Confirmed. Magithub was working for me in additional packages. I hadn't used it since switching to the github layer on develop. Workaround didn't work for me.

**Comment by jr0cket** [comment]
I am using Spacemacs master and had magithub installed as an additional package and it was working as of 14th February 2017 - http://jr0cket.co.uk/2017/02/spacemacs-using-magit-with-github.html

I just did a package update which update magit (version magit-20170320.1936) and now magithub (version (version magithub-20170214.1710) is no longer working.  When I open a version controlled project with `SPC g s` then no details about issues or pulls is retrieved.

As I am not using the layer from Spacemacs develop, so perhaps this is a magit & magithub compatibility issue.

**Comment by bmag** [comment]
If anyone can verify weather this is an upstream bug or not it would be nice.

**Comment by agzam** [comment]
This now works for me. Probably it was and upstream issue that resolved itself. As soon someone else confirms, this could be closed

**Comment by planigan** [comment]
I just pulled the latest packages down and can confirm that this is now working for me.

**Comment by costa** [comment]
Doesn't work for me at the moment (at the latest version);
`magithub-debug-mode t` revealed `ghub-auth-error "Token not found"` ;
`$ hub...` works perfectly;
Thank you for your work and for your support.

**Comment by CestDiego** [comment]
Same for me as @costa

**Comment by costa** [comment]
I would like this issue to be re-opened.

Right now I'm caught in a loop:
```
Such a Github API token is not available:

  Host:    api.github.com
  User:    costa
  Package: magithub

  Scopes requested in `magithub-github-token-scopes':
    repo
    user
    notifications
  Store locally according to `auth-sources':
    ("~/.authinfo" "~/.authinfo.gpg" "~/.netrc")
  Store on Github as:
    "Emacs package magithub @ lashadko-2"

WARNING: If you have enabled two-factor authentication then
         you have to abort and create the token manually.

If in doubt, then abort and view the documentation first.

Otherwise confirm and then provide your Github username and
password at the next two prompts.  Depending on the backend
you might have to provide a passphrase and confirm that you
really want to save the token.

Create and store such a token? (y or n) y
Contacting host: api.github.com:443
A token named "Emacs package magithub @ lashadko-2"
already exists on Github.  Replace it? (y or n) y
```

Trying to workaround...

**Comment by costa** [comment]
Ok, still stuck in the loop — when trying to do any GH action. However, some GH info is shown on the status page, and I don't know where the hell the auth is stored, it is not at any location above.

I'm ready to work online (gitter) with any maintainer who'd like to get to the bottom of this.

It's really frustrating this useful package couldn't get fixed in almost half a year now.

**Comment by aaronjensen** [comment]
@costa it'd be good to open your issue https://github.com/magit/ghub

**Comment by costa** [comment]
@aaronjensen thanks for you response.
You see I'm an almost-plain-vanilla spacemacs user and I would like it to stay this way, very much.

To me, it's a github layer dysfunction and a pretty annoying one too — since it required a [workaround](http://jr0cket.co.uk/2017/02/spacemacs-using-magit-with-github.html), but used to work, then stopped working, then worked for some time again, now not working.

As much as I'd like to help the magithub community, this is beyond my capacity at the moment, so I hope someone more involved with the project will check (isolating the issue the proper way) and take it upstream if needed.
