### ISSUE TITLE
Spacemacs GUI on Windows not showing spacemacs image logo

### ISSUE THREAD

**Issue by andrewbanchich** [syl20bnr/spacemacs#8570]
When I run emacs it displays the text-based version of the spacemacs logo, even though I am in GUI mode. I use runemacs.exe, but I've tried running the other executables as well and none display the image.

**Comment by duianto** [comment]
Emacs might need to be compiled with image support.
I have used this version: `emacs-w64-25.1-O2.7z`
from here: https://github.com/zklhp/emacs-w64/releases
for 5 months and haven't run into any issues. It has some "Optimizations", including image support.
