### ISSUE TITLE
Not possible to create new file, if another file with similar name exists

### ISSUE THREAD

**Issue by abellmann** [syl20bnr/spacemacs#8571]
If I want to create a new file in spacemacs, I usually use SPC f f or C-x C-w in a new buffer.

This fails to work, if a file with a similar name already exists, because the existing file is matched and opened..

example: I want to create the file test.org, but a file sometest.org already exists in the same directory. I have no way to create the file. (note: I am using ivy).

**Comment by abellmann** [comment]
In evil mode, this can be done with ":e filename", but this is more a workaround than a solution. I think it should be possible to decide in ivy, if I want to create a new file or open an existing one.

I also found, that this is possible with C-M-j in ivy, but this is anything, but intuitive..

**Comment by sdwolf** [comment]
I agree, just tried it out, not intuitive but `C-M-j` is the [official keybind](https://github.com/abo-abo/swiper/blob/ac944ead01871bea01e95b09f18459c83ef1eae2/ivy.el#L275). Maybe a README file for ivy could help by documenting it, currently there is no such file.

I could start writing one if it's OK with everybody.

**Comment by d12frosted** [comment]
Oh right, this particular issue bogged me as well when I tried ivy for the first time. Thanks to official documentation I've found solution pretty fast. 

There is a [good place][1] for mentioning this key binding.

  [1]: https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#ivy

**Comment by Stebalien** [comment]
Maybe bind it to something like `S-RET`, `M-RET`, or `C-RET`. Also, I've opened an issue (https://github.com/abo-abo/swiper/issues/933) to discuss ways to make this more user friendly.

**Comment by fabacino** [comment]
Please see https://github.com/abo-abo/swiper/issues/933#issuecomment-310638597 for a possible solution to this issue.

**Comment by duianto** [comment]
Tested on the latest master and develop branches:
- press: `SPC SPC`, type: `set-variable` and press: `RET`
- type: `ivy-use-selectable-prompt` and press: `RET`
- type: `t` and press: `RET`
- press: `SPC f f`, type: the first letter(s) of a file/folder in the current folder. The first match gets selected.
- Move up the selection `C-p` to the "Find file: " prompt, and press: `RET`

A new buffer opens, with the same name as the letters that were typed at the "Find file: " prompt. 👍

**Comment by d12frosted** [comment]
I have updated documentation to include information about `C-M-j`. So I mark it as `fixed in develop`. Also please see #9309 regarding `ivy-use-selectable-prompt`. 

P. S. FYI you can also you arrows, not only `C-p` and `C-n`. Just in case you use them in other places.
