### ISSUE TITLE
Update frequency?

### ISSUE THREAD

**Issue by maikol-solis** [syl20bnr/spacemacs#8575]
Hi!

I am a novice/medium user of Emacs, but since I discovered spacemacs I use it everyday. 

Saying this, I love the project and I see that it evolves fast and strong, but the regular user (in the master branch) has to wait long periods to get the newest commits from the community. 

I don't know if you have some internal schedule, but it would be great if once a month (just one example) the devs could release the latest stable version. The idea is not wait too much to enjoy the improvements and keep bringing more people to the project. 

I hope the idea has any sense. 

Best regards.

**Comment by d12frosted** [comment]
Thanks for the interest in the project and I am glad that you love Spacemacs 😸 

As far as I can tell, there is no release schedule right now. Usually Sylvain makes major release when there is something 'major' to release 😸 Minor releases usually are made in two cases: there is critical bug fix or there is something minor and stable that worth releasing.

As for the next release, unfortunately I have no information on when it's going to happen. Maybe @syl20bnr can share his plans here 😸

**Comment by beojan** [comment]
I just use the development branch. I don't know if the devs would recommend that, but it seems to work fine for me.
