### ISSUE TITLE
Ruby syntax highlighting broken for quoted symbols

### ISSUE THREAD

**Issue by andreasknoepfle** [syl20bnr/spacemacs#8577]
#### Description :octocat:
Enh-Ruby mode syntax highlighting seems to be broken for symbols that use quotes: 

```ruby
def some_function('param': nil)
end
```
=>
<img width="307" alt="screen shot 2017-03-24 at 15 34 11" src="https://cloud.githubusercontent.com/assets/239398/24298803/70e1eafe-10a7-11e7-9990-cc2e8898257c.png">

Another example:
<img width="258" alt="screen shot 2017-03-24 at 15 33 36" src="https://cloud.githubusercontent.com/assets/239398/24298816/7ac80e9a-10a7-11e7-861e-43752ef8d514.png">

It messes up syntax highlighting from that point on onwards, where it always looks a bit like it is off by 2 chars or something.

#### Reproduction guide :beetle:
- Start Emacs
- Open a ruby file
- Enter ruby code like this
```ruby
def some_function('param': nil)
end
```
*Observed behaviour:* :eyes: :broken_heart:
You can already see it on the `i` of `nil` that something is off in the example. 
*Expected behaviour:* :heart: :smile:
Does not mess up highlighting.
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql yaml html helm auto-completion better-defaults emacs-lisp
     (ruby :variables ruby-enable-ruby-on-rails-support t ruby-enable-enh-ruby-mode t ruby-test-runner 'rspec)
     ruby-on-rails git markdown org html javascript
     (osx :variables mac-right-option-modifier nil)
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking syntax-checking version-control)
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by Miciah** [comment]
Looks like a problem with enh-ruby-mode.  This should be reported upstream.

**Comment by Nate-Wilkins** [comment]
@andreasknoepfle when you report it upstream can you reference this? Thanks!

**Comment by andreasknoepfle** [comment]
https://github.com/zenspider/enhanced-ruby-mode/issues/150
