### ISSUE TITLE
Smartparens and Web-mode ?

### ISSUE THREAD

**Issue by phenix-factory** [syl20bnr/spacemacs#8584]
Hi !

I can't find a way to enable smartparens in web-mode. I can turn it on using `SPC t p` and it work nice.
But I have to do it every time, it's painfull.

You can find my [.spacemacs](https://github.com/phenix-factory/config-spacemacs/blob/master/.spacemacs) and the [webmode hook](https://github.com/phenix-factory/config-spacemacs/blob/master/.spacemacs#L360).
I m using the 200.7 version of Spacemacs on emacs 25.1.

Thank's in advance !

**Comment by dangom** [comment]
Won't `(add-hook 'web-mode-hook #'smartparens-mode)` work?

**Comment by phenix-factory** [comment]
No, it s not working :(

**Comment by 15cm** [comment]
The same problem.

**Comment by zzhjerry** [comment]
use `(add-hook 'web-mode-hook #'turn-on-smartparens-mode t)`. You need the third argument `t` to ensures `turn-on-smartparens-mode` to be executed at last because `spacemacs/toggle-smartparens-off` is also executed in the `web-mode-hook`

**Comment by phenix-factory** [comment]
Work nice for me ! Thank you @zzhjerry !
