### ISSUE TITLE
(wrong-type-argument listp t) error during starting spacemacs

### ISSUE THREAD

**Issue by sangjeedondrub** [syl20bnr/spacemacs#8589]
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.50.2
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. ed8772f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:

```elisp
(ivy auto-completion better-defaults git
     (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
     (spell-checking :variables spell-checking-enable-by-default nil)
     syntax-checking version-control graphviz search-engine github colors pandoc sangjee markdown org latex php javascript emacs-lisp
     (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
     java docker yaml html lua
     (chinese :packages youdao-dictionary fcitx :variables chinese-enable-fcitx nil chinese-enable-youdao-dict t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS LIBSYSTEMD

#### Error
```
`An error occurred while post-configuring org in layer org (error: (wrong-type-argument listp t))` 
```
#### ?
How to solve the problem, it occurred during starting Spacemacs

**Comment by bmag** [comment]
For how to get the backtrace: [enable-debug-at-initialization](https://github.com/syl20bnr/spacemacs/wiki/Debugging#enable-debug-at-initialization) and [get-the-backtrace](https://github.com/syl20bnr/spacemacs/wiki/Debugging#get-the-backtrace)
