### ISSUE TITLE
YCMD times out on launch

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#8596]
When I first load a C++ file (with a fairly long list of -I flags, admittedly), YCMD seems to timeout at first. Restarting with `C-c Y o` then reparsing the buffer seems to fix this though.

Perhaps the default timeout should be increased?

**Comment by beta1440** [comment]
The `company-ycmd-request-sync-timeout` variable controls how long ycmd will timeout. Its default value is 0.05. Try adding this to `user-config` in your `.spacemacs`. You may need to increase it beyond 0.10 seconds. 

```emacs-lisp
(setq company-ycmd-request-sync-timeout 0.10)
```
