### ISSUE TITLE
[Clojure-Mode] Integrate Sayid

### ISSUE THREAD

**Issue by royalaid** [syl20bnr/spacemacs#8597]
[Sayid](http://bpiel.github.io/sayid/) seems very useful. Would anyone else be interesting in it integrated into clojure mode to support functional keybindings and fitting better with the existing tooling?

**Comment by JAremko** [comment]
Solved in #8536

**Comment by kommen** [comment]
As #8536 is merged I guess this can be closed.

**Comment by JAremko** [comment]
@kommen  thx :+1:
