### ISSUE TITLE
Display the number of yanked lines such as Vim

### ISSUE THREAD

**Issue by PierreR** [syl20bnr/spacemacs#860]
In Vim by default you get a visual clue about what you have just yanked. For instance : 
```
3 lines yanked
```

I am not sure if this is possible but it would be really nice to have a similar clue in spacemacs.

Cheers

**Comment by syl20bnr** [comment]
It is better to ask for this feature on the evil repo since it may be part of the Vim emulation: https://bitbucket.org/lyro/evil/issues?status=new&status=open

**Comment by TheBB** [comment]
No movement on this in almost a year, and it seems nobody wants this enough to bother to report upstream. Closing.
