### ISSUE TITLE
Error in dotspacemacs/layers: Symbol’s value as variable is void: macs-distribution

### ISSUE THREAD

**Issue by Reapor-Yurnero** [syl20bnr/spacemacs#8607]
I have done nothing and one time I open emacs it starts to updating something and soon this error occurred: Error in dotspacemacs/layers: Symbol’s value as variable is void: macs-distribution.

I'm using macOS 10.12.4.

**Comment by Stebalien** [comment]
Have you tried searching for `macs-distribution` in your emacs file? This sounds like an accidental edit.
