### ISSUE TITLE
"SPC q r" cannot restart spacemacs

### ISSUE THREAD

**Issue by xarthurx** [syl20bnr/spacemacs#8610]
after an update, when calling "spacemacs/restart-emacs", Emacs does nothing but return:

`process-get: Wrong type argument: processp, nowait 
`
Not sure what is causing this.

**Comment by nixmaniack** [comment]
> If you are posting about a *bug* please close this issue and open a new one
using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs. If the
bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template)

Or you can check https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report
