### ISSUE TITLE
SPC q r cannot restart spacemacs

### ISSUE THREAD

**Issue by xarthurx** [syl20bnr/spacemacs#8611]
#### Description :octocat:
SPC q r cannot restart spacemacs

#### Reproduction guide :beetle:
- Start Emacs
- SPC q r

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs cannot be restarted and a message shows in the mini buffer:
process-get: Wrong type argument: processp, nowait

*Expected behaviour:* :heart: :smile:
Spacemacs restart normally.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp
                 (better-defaults :variables better-defaults-move-to-beginning-of-code-first t better-defaults-move-to-end-of-code-first nil)
                 colors fasd latex
                 (latex :variables latex-enable-folding t)
                 markdown org bibtex pandoc pdf-tools spell-checking syntax-checking git version-control
                 (python :variables python-enable-yapf-format-on-save t)
                 html javascript
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 x-chinese-related)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XWIDGETS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by dubnde** [comment]
I also observe this issue on `ubuntu` and on `windows` setup. I do not observe it on `mac` setup.

**Comment by braham-snyder** [comment]
same, on OS X:

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 2f746d1c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((auto-completion :variables auto-completion-tab-key-behavior nil auto-completion-return-key-behavior nil auto-completion-enable-sort-by-usage t)
 better-defaults emacs-lisp git markdown
 (org :variables org-bullets-bullet-list
      '("■" "◆" "◉" "✸")
      org-enable-github-support t org-projectile-file "TODOs.org")
 (shell :variables shell-enable-smart-eshell t)
 spell-checking syntax-checking version-control ruby
 (colors :variables colors-colorize-identifiers 'all)
 (mu4e :variables mu4e-installation-path "~/.emacs.d/layers/+email/")
 shell-scripts vimscript pdf-tools
 (ranger :variables ranger-show-preview t ranger-show-hidden t ranger-cleanup-on-disable t ranger-show-literal nil ranger-ignored-extensions
         '("mkv" "iso" "mp4" "avi")
         ranger-override-dired t)
 ivy extra-langs javascript ipython-notebook
 (python :variables python-enable-yapf-format-on-save t python-sort-imports-on-save t python-test-runner 'pytest)
 osx dash bibtex evil-cleverparens theming nlinum github yaml
 (latex :variables latex-enable-auto-fill t))
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by OmanF** [comment]
Same issue, what I'm getting is `Symbol's function definition is void: restart-emacs`.
Funny thing it worked fine till about a few days ago there was an package update for the package `restart-spacemacs` and from then on, all hell broke loose.

**System Info:** 💻
* OS: Antergos Linux
* Emacs: 25.1.1
* Spacemacs: 0.200.8 (Probably stable/master/what you call when you just pull the repo once and update ever since).
* Graphic display: ?
* Distribution: Spacemacs
* Editing style: Vim
* Completion: Helm
* Layers:
** auto-completion
** better-default
** elixir
** emacs-lisp
** haskell
** rust
** shell
** spell-checking
** syntax-checking
** themes-megapack

**Comment by hghwng** [comment]
I tried to rollback the package of `restart-emacs` from `20170413.2305` to `20170220.2245`, and it works now. If there's no solution yet, you can mitigate by downgrading.

**Comment by OmanF** [comment]
For me, I went MOAB on my `.emacs.d` folder, and, after restarting Spacemacs and reinstalling all plugins/layers, everything works fine.

Guessing in my case it was a matter of faulty installation of the spacemacs-restart plugin (which I've seen a couple of threads discussing).

As far as *I'm* concerned the problem is gone.

**Comment by hghwng** [comment]
@OmanF I removed the `~/.emacs.d/elpa` and reinstalled every packages, but the error is still there.

```
Debugger entered--Lisp error: (wrong-type-argument processp nowait)
  process-plist(nowait)
  process-get(nowait frame)
  restart-emacs--record-tty-file((client . nowait) (...)
  apply(restart-emacs--record-tty-file (client . nowait) (...) (...) t nil)
  #...
  frameset-filter-params(...)
  #[257 "\302\303!\300\206		\304#\305\306!\304\"B\207" [nil frameset-filter-alist frameset-filter-params frame-parameters t window-state-get frame-root-window] 5 "\n\n(fn FRAME)"](#<frame emacs@HghThinkPad 0x74f1af0>)
  mapcar(#[257 "\302\303!\300\206		\304#\305\306!\304\"B\207" [nil frameset-filter-alist frameset-filter-params frame-parameters t window-state-get frame-root-window] 5 "\n\n(fn FRAME)"] (#<frame emacs@HghThinkPad 0x74f1af0> #<frame F1 0xc2f680>))
  frameset-save(nil :app (desktop . "208") :name "hugh@HghThinkPad" :predicate desktop--check-dont-save)
  desktop-save-frameset()
  desktop-save("/tmp/" t t)
  restart-emacs--save-frames-using-desktop()
  restart-emacs--frame-restore-args()
  restart-emacs(("--resume-layouts"))
  spacemacs/restart-emacs(("--resume-layouts"))
  spacemacs/restart-emacs-resume-layouts()
  funcall-interactively(spacemacs/restart-emacs-resume-layouts)
  call-interactively(spacemacs/restart-emacs-resume-layouts nil nil)
  command-execute(spacemacs/restart-emacs-resume-layouts)
```

**Comment by OmanF** [comment]
I wish I knew better so I could help.

I also know, from past experiences, that, again, *for me*, when I need a "Hail Mary" I just pull the entire Spacemacs repo (AKA "soft reinstall") and then just reconfigure everything that changed.

That's my usual MO: first the `.emacs.d` folder then "going nuclear".
Hope any of this helps.

**Comment by hghwng** [comment]
@OmanF Haha, that's an interesting and useful strategy! Following your advice, I removed `~/.emacs.d` this time. Unfortunately, the problem is reluctant to go.

Maybe you should try to start Emacs in server mode. According to my observation, if I start Emacs by `emacs` instead of `emacs-client`, I can't reproduce the bug anymore.

**Comment by petr-tik** [comment]
I have the same problem. 

Furthermore, after running "Update Packages" from the home screen and packages are downloaded, the following message shows up in the buffer.

> Emacs has to be restarted to actually install the new version of the packages (SPC q r).

Grepping the code, I find it here

https://github.com/syl20bnr/spacemacs/blob/develop/core/core-configuration-layer.el#L2149-L2151

which suggests that "restart-emacs" is erroneously marked as a member of update-packages 

System info
OS: gnu/linux ubuntu
Emacs 25.2.2
Spacemacs: 0.300.0@25.2.2
Spacemacs branch: develop (rev. 988e6778ba0619cf3128c0cc205c11947643e4f0)
Graphic display: t
Distribution: spacemacs
Editing style: emacs
Completion: helm

**Comment by PrestanceDesign** [comment]
Hi,

Same for me.
I cannot no more restart Spacemacs since 10-15 days.

Any clue, how we can debug ?

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6f3418578)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(vimscript
 (clojure :variables clojure-enable-clj-refactor t)
 parinfer sql rust nginx python csv ansible yaml javascript php lsp dash html react ruby helm
 (auto-completion :variables auto-completion-enable-help-tooltip t)
 emacs-lisp git markdown search-engine docker spotify plantuml gtags restclient
 (elfeed :variables rmh-elfeed-org-files
         (list "~/Dropbox/org/elfeed.org"))
 pass colors vagrant finance
 (org :variables org-enable-bootstrap-support t org-enable-github-support t org-enable-reveal-js-support nil org-enable-hugo-support t org-want-todo-bindings t org-enable-trello-support t)
 (shell :variables shell-default-shell 'eshell shell-default-height 35 shell-default-position 'bottom)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LCMS2

**Comment by duianto** [comment]
>which suggests that "restart-emacs" is erroneously marked as a member of update-packages

What these commands do:
```
(format
     (concat "\nEmacs has to be restarted to actually install the "
             "new version of the packages%s.\n")
     (if (member "restart-emacs" update-packages) "" " (SPC q r)"))
```
is to create a string with or without the key binding:
`Emacs has to be restarted to actually install the new version of the packages (SPC q r)`

depending on if `restart-emacs` is a member of the `update-packages` list.

Restarting with `SPC q r` or `SPC q R` works for me on the develop branch with the latest packages.

In both Windows 10 and Ubuntu 18.04.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8671362aa)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm markdown multiple-cursors
            (org :variables org-enable-org-journal-support t)
            spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8671362aa)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP

**Comment by harshitgarg22** [comment]
+1, is there any update on this issue?
