### ISSUE TITLE
Set frame title to something useful

### ISSUE THREAD

**Issue by mfaerevaag** [syl20bnr/spacemacs#8613]
### Ehancement

I suggest setting the `frame-title-format` to something more useful, as Emacs Prelude does [here](https://github.com/bbatsov/prelude/blob/e0ca7c700389e70df457177ea75b0936dbe254e0/core/prelude-ui.el#L66-L71).

In the screenshot below I have two Emacs instances. The one to the left with the `frame-title-format` set (see code in screenshot) and the other one as vanilla Spacemacs.

![frame-title](https://cloud.githubusercontent.com/assets/1221244/24532607/b1e00716-15fc-11e7-97d2-7230b2666806.png)

I am not familiar enough with Spacemacs to dare post a pull-request. Though, if someone where to say insert a `spacemacs//set-frame-title-format` the same manner as `spacemacs//removes-gui-elements` I would be happy to make a PR! 😄 

PS. Just started using Spacemacs... Thank you ❤️

**Comment by jvillasante** [comment]
Yeah, this will be useful.

This is what i have on my `dotspacemacs/user-config`
```
;; Display Visited File's Path in the Frame Title
(setq frame-title-format
      '((:eval (if (buffer-file-name)
                   (abbreviate-file-name (buffer-file-name))
                 "%b"))))
```

**Comment by edrex** [comment]
in 0.200.9, spacemacs shows buffer title, but not in develop. did something change recently?

emacs 25, X11

**Comment by chrissound** [comment]
This seems to be handled by: https://github.com/syl20bnr/spacemacs/pull/5924 ?

**Comment by mfaerevaag** [comment]
It seems so. Should we wait for an answer into the documentation of the feature, before we close this?

**Comment by chrissound** [comment]
It's available here (develop branch): https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#frame-title

We should close this.

**Comment by mfaerevaag** [comment]
Thanks! Done

**Comment by PrestanceDesign** [comment]
Hi everybody !

I just update yesterday my .spacemacs config file (I'm on developer branch) and I tried to setup `dotspacemacs-frame-title-format` to change default value but nothing happen after reload/restart Spacemacs.

I want to display file path, so is I set `dotspacemacs-frame-title-format "%a"` in .spacemacs but it doesn't works.
If I manually eval `(spacemacs/title-prepare dotspacemacs-frame-title-format)', it works.


Until a solution, I restore that snippet and this works :
```lisp
;; Display Visited File's Path in the Frame Title
(setq frame-title-format
      '((:eval (if (buffer-file-name)
                   (abbreviate-file-name (buffer-file-name))
                 "%b"))))
``` 

Best regards.

**Comment by ro6** [comment]
I had the same issue as @PrestanceDesign, changing `dotspacemacs-frame-title-format` didn't change the title from the default, even after restart. 
Has it just not hit `master` yet? 
Do most people in the community just follow `develop`? I would but I'm having a [problem with `org-plus-contrib` over there](https://github.com/syl20bnr/spacemacs/issues/10251#issuecomment-646664044).

**Comment by AnweshGangula** [comment]
You can set a custom frame title for spacemacs using `dotspacemacs-frame-title-format` inside `dotspacemacs/init` like below ([reference](https://emacs.stackexchange.com/a/81513/36093))

Spacemacs documentation: https://develop.spacemacs.org/doc/DOCUMENTATION.html#title

```lsp
dotspacemacs-frame-title-format   "%b - Spacemacs"
```
