### ISSUE TITLE
Emacs as daemon, emacsclient can't open files with Unicde characters in their path

### ISSUE THREAD

**Issue by oyarsa** [syl20bnr/spacemacs#8616]
#### Description :octocat:

With Emacs running as daemon, emacsclient can't open files with Unicde characters in their path.

Also, for some reason running `emacs --daemon` makes the client instances show the default font
instead of the one I chose (Fira Code), but this might be another bug (or incorrect setting).

Another thing that may be related: I had to include some `setenv` calls into my config to force
`anaconda-mode` (in Python layer) to use UTF8 instead of cp1257 when loading files, which also
caused a similar issue (the interpreter couldn't find the file).

#### Reproduction guide :beetle:

- Start Emacs as daemon (`emacs --daemon` or just `runemacs`)

- Open file via `emacsclient file` in cmd

*Observed behaviour:* :eyes: :broken_heart:

Emacs can't find the file, the Unicode characteres are replaced by gibberish, e.g. Á becomes k

*Expected behaviour:* :heart: :smile:

Emacs successfully opens the file. If I run `emacs -q --daemon` instead, it works alright.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(racket
 (haskell :variables haskell-enable-hindent-style "johan-tibell")
 (python :variables python-sort-imports-on-save t python-enable-yapf-format-on-save t)
 vim-powerline ivy auto-completion emacs-lisp git syntax-checking semantic themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by SamHasler** [comment]
I have the same issue, and as far as I'm aware I haven't got any setenv calls as I don't use Python mode. So I doubt that's the cause.
