### ISSUE TITLE
How to expand symbol signature area?

### ISSUE THREAD

**Issue by everedifice** [syl20bnr/spacemacs#8622]
<img width="900" alt="2017-04-01 11 39 14" src="https://cloud.githubusercontent.com/assets/1061205/24574590/24a2f8c0-16d0-11e7-8ff9-b73029725d8c.png">

Hello.

I want to expand help area without ellipsis (marked as red arrow)

I'm trying to find configuration for this. but i can't.

When i moving mouse cursor to that area. then expanded but, i want show it always expanded state.

Please help :)

**Comment by bmag** [comment]
The feature that provides the signature is called "eldoc", and it is displayed in the "minibuffer" or "echo area". I don't know how to expand the echo area off the top of my head, but these terms might help you search for relevant variables or commands.
