### ISSUE TITLE
evil-jump-backwards: jump to currently displayed buffers only?

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#8626]
.. or just to a current buffer.

**Comment by Stebalien** [comment]
(@xged you're missing the bug report body).

**Comment by xged** [comment]
@Stebalien its not bug, but behaviour I am looking for.

**Comment by duianto** [comment]
Maybe a jump list transient state could include a toggle "jump range" feature, similar to how it currently works in the Symbol Highlight Transient State `*`, where `[r] change range`, toggles between: `Buffer`, `Display`, and `Function`.

**Comment by Stebalien** [comment]
@xged sorry, I meant that some context and motivation would be nice (although, on second reading, it's probably not necessary).
