### ISSUE TITLE
global-linum-mode not working after update to 200.8

### ISSUE THREAD

**Issue by b-rodrigues** [syl20bnr/spacemacs#8631]
Hi,

after updating to 200.8, global-linum-mode does not seem to work. I have the following line in my .spacemacs:

(global-linum-mode)

which worked until I've updated.

**Comment by houli** [comment]
Have you tried using the default `dotspacemacs-line-numbers` variable instead in your `.spacemacs` file?

**Comment by b-rodrigues** [comment]
No I didn't, and it works! Thanks.
