### ISSUE TITLE
The yellowish button long term perspectives

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#8634]
### As some of you might have noticed, a strange yellow button appeared at  http://spacemacs.org/ 

![http://i.imgur.com/sljoUWn.png?1](http://i.imgur.com/sljoUWn.png?1)

If you press the button and if you're lucky (with like `1.0 - PI*0.2` chances out of one) you'll get a fully working Spacemacs ... In the web page??? **What The Fun**, right?  Right.

But as I'm coughing my lungs out, I just can't help but wonder... Can the button have any purpose besides being simply cool? Can we make "online Spacemac guide" ? For example, we can display an org file with a bunch of links to demos. Like evil tutor, a list of layers etc. Mb showcase transient states and some basic `SPC` combos.

Any ideas?

**Comment by triklsbg** [comment]
was actually nothing more than a April Fool's Day hoax.  ??? A long term perspective of an April Fool's Day Hoax ? I think next year we'll have a fresh one!

**Comment by JAremko** [comment]
@triklsbg  The hoax was that it was not a hoax :shipit:

**Comment by JAremko** [comment]
btw direct link(worse quality) http://jaremko.tk:10000

**Comment by seengularitee** [comment]
Compilation error using Chromium under Arch Linux, but Firefox works fine.

**Comment by JAremko** [comment]
> Compilation error using Chromium(Emacs window opens but not responding to any input) under Arch Linux, but Firefox works fine.
 
@syl20bnr  It's like 5th already.  Stop trolling. man, not cool :roll_eyes: 

:rofl:

**Comment by seengularitee** [comment]
jeez...
![spectacle m11364](https://cloud.githubusercontent.com/assets/8686360/24715762/4d465084-1a35-11e7-9b0b-379f7c797651.png)

**Comment by jredville** [comment]
I love the idea of keeping this around if possible, and opening an org mode tutorial file

**Comment by syl20bnr** [comment]
@JAremko Oops, removing the fake error 😄

**Comment by syl20bnr** [comment]
Done!

**Comment by nixmaniack** [comment]
@JAremko @syl20bnr 👍  This is awesome! Running Spacemacs in browser.

**Comment by JAremko** [comment]
![http://i.imgur.com/gCMRY4a.png?1](http://i.imgur.com/gCMRY4a.png?1)

@syl20bnr Illuminati confirmed :scream_cat:

**Comment by thushalala** [comment]
Hello. Sorry if i misunderstood reason for this thread, but i think from long term point of view it would be great to implement something similar to jupyter project. I mean implementing tiny local server, that will store your config and layers, then with it you open spacemacs in any browser you want. It will be cool to work in spacemacs from basically any platform. Or maybe ability to save in cash somehow current state with config to work oflline. It works pretty fast, really great thing. This way it have chances to become more popular than classic emacs installation.

**Comment by greboide** [comment]
i would really love to use this from school for example with my user config and ability to keep my files, even if i had to setup my own server.

**Comment by Qqwy** [comment]
I would also love to be able to give a link to an online Spacemacs window to someone else; my coworkers keep complaining that I send them `.org` files that they are unable to read without `org-mode`'s syntax highlighting. :sweat_smile: 


What a wonderful feature! This is absolutely insane.

**Comment by VMatrix1900** [comment]
The Org mode is one of the killer features of Emacs. However, the lack of the web editor of Orgmode is a big hurdle of this wonderful note format. The Emacs in browser can solve this problem. We can build a note webapp compatible with the Orgmode file format.

**Comment by alphapapa** [comment]
This is amazing.  I imagine this will bring in a lot of new users, because they can try it without even needing to install Emacs!

**Comment by linchen2chris** [comment]
The performance is not good enough. When I type, it block a second. BUT the idea is so cooooool, :)

**Comment by JAremko** [comment]
@linchen2chris  Most of it is ping. The server is in Eastern Europe and if you are in South Korea (for example) the ping can be around 1 second (connection almost wraps around the world)

**Comment by teodorlu** [comment]
Fantastic feature!

I'm getting unexpected behavior with my Norwegian keyboard. Some keys are swapped with US (`*`, `/`) keyboards, others neither where I expect them with Norwegian layout nor with US layout, (`;`, `:`) . Any place suitable to report?

**Comment by JAremko** [comment]
@teodorlu That's probably a keyboard layout mismatch. Xpra has an option to select it but the Spacemacs thingy doesn't expose it(for now)

**Comment by bhipple** [comment]
This is really neat.  Are there docs on how to set this up on our own server?  Like @Qqwy, I'd like to be able to share org mode files with my peers, without requiring them to have a full org-mode setup.  Currently I'm exporting to [themed HTML](https://github.com/fniessen/org-html-themes), but this would be a nicer option for people who have some org experience.

**Comment by JAremko** [comment]
@bhipple  This is back-end that we're using https://github.com/JAremko/browsermax  this is front-end https://github.com/syl20bnr/spacemacs.org/blob/gh-pages/index.html#L37 (code related to Xpra marked with `<!-- +Xpra stuff -->`)

Also you can use https://github.com/JAremko/docker-x11-bridge

**Comment by nasfarley88** [comment]
Would love to be able to use Spacemacs on my chromebook to edit local files. Or even better: google drive files.

**Comment by ArneBab** [comment]
This is awesome! It resolves a years-long problem I had with using specialized infrastructure! It’s hard to describe how many problems this makes disappear with one cut … I want to provide this for my readers to adapt documents and publish via org-latex-export-to-pdf — and let them download the result and source.

Thank you!

**Comment by jbyler** [comment]
+1 and a slight twist on the org-mode idea: if it worked well on mobile, the browser-based spacemacs could potentially provide a nice mobile interface to org-mode files.  I would love to be able to self-host or otherwise have a secure & private spacemacs-in-browser to use for accessing my personal agenda, notes, reference material, etc. on mobile.

**Comment by mattalhonte** [comment]
Echoing how cool this would be to be able to run on a remote server.  I often use Jupyter notebooks in this way - it'd be great to be able to do use Spacemacs like that.

**Comment by jb55** [comment]
I believe this is currently broken...

**Comment by JAremko** [comment]
Yeah It dies sometimes... 
 I'm currently hosting it on a spare laptop :smile:

**Comment by souvik1997** [comment]
This seems to be open to denial of service attacks. I ran a fork bomb in `M-x shell` and it crashed (and would not start again).

**Comment by JAremko** [comment]
@souvik1997  Yeah. fork bomb seems to hang docker host. Fortunately it should be easy to fix by stringing sandbox.

**Comment by JAremko** [comment]
We'll probably move it to develop https://github.com/syl20bnr/spacemacs.org/pull/27 

I'll rework it and add some of the features discussed in this issue.

**Comment by Compro-Prasad** [comment]
Shouldn't this be closed? I could see this before but the Try Online option has gone.

**Comment by JAremko** [comment]
Yeah at this time it's too far in my TODO list. 
But one day...  :shipit:
