### ISSUE TITLE
evil-mc: misaligned cursors in insert mode on macOS

### ISSUE THREAD

**Issue by AndreaOrru** [syl20bnr/spacemacs#8641]
#### Description :octocat:
The default configuration of evil-mc causes cursors to misalign in insert mode, on macOS only.
The issue has already been confirmed and addressed by the package maintainer: https://github.com/gabesoft/evil-mc/issues/49. `evil-mc-enable-bar-cursor` should be set to nil on macOS.

#### Reproduction guide :beetle:
- Start Emacs
- Enable `evil-mc-mode`
- Write `bool x = 0;` on 3 separate lines
- With the cursor on the first `bool`, press `C-n` twice
- Press `i` to enter insert mode

*Observed behaviour:* :eyes: :broken_heart:
<img width="107" alt="2" src="https://cloud.githubusercontent.com/assets/3673952/23759777/077da4d2-04ee-11e7-922f-1863baa8115a.png">

*Expected behaviour:* :heart: :smile:
All cursors should be on the same column without causing the following text to misalign.

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.50
- Spacemacs: 0.200.8
- Spacemacs branch: develop (rev. f79a1693)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion dash emacs-lisp
      (haskell :variables haskell-completion-backend 'intero)
      git osx
      (shell :variables shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom)
      syntax-checking python version-control)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by benjamreynolds** [comment]
This is fixed in #9585. ping @syl20bnr
