### ISSUE TITLE
Symbol’s function definition is void: provide

### ISSUE THREAD

**Issue by chengyi** [syl20bnr/spacemacs#8646]
when I open a markdown file
the error appear, the emacs become abnormal
so I cannot post issue using emacs.

 I'm using develop branch

**Comment by syl20bnr** [comment]
I cannot reproduce it. Did you test with a vanilla `~/.spacemacs` file ?

**Comment by chengyi** [comment]
when I open a project's md file, it appears.
the urls git@github.com:chengyi/libpersistence.git

**Comment by chengyi** [comment]
@syl20bnr the baff1ba8974e09f035d1f0fe2e3edd4770ac49d8 commit in develop branch that enable mmm-mode in markdown introduce the issue. maybe mmm-mode has bugs.

**Comment by chengyi** [comment]
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 076bd627)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(graphviz javascript ivy better-defaults emacs-lisp markdown org lua python colors git spacemacs-layouts ranger
          (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
          ycmd auto-completion
          (chinese :variables chinese-enable-youdao-dict t)
          deft shell semantic prow)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

Here is my system info
