### ISSUE TITLE
Rcirc initialization errors

### ISSUE THREAD

**Issue by jcpetkovich** [syl20bnr/spacemacs#865]
I get the following backtrace when starting rcirc on the `develop` branch:

    Debugger entered--Lisp error: (void-variable rcirc-authinfo)
      (member x rcirc-authinfo)
      (if (member x rcirc-authinfo) rcirc-authinfo (setq rcirc-authinfo (cons x rcirc-authinfo)))
      (let* ((x (list (plist-get p :host) method (plist-get p :user) (if (functionp secret) (funcall secret) secret)))) (if (member x rcirc-authinfo) rcirc-authinfo (setq rcirc-authinfo (cons x rcirc-authinfo))))
      (let ((secret (plist-get p :secret)) (method (intern (plist-get p :port)))) (let* ((x (list (plist-get p :host) method (plist-get p :user) (if (functionp secret) (funcall secret) secret)))) (if (member x rcirc-authinfo) rcirc-authinfo (setq rcirc-authinfo (cons x rcirc-authinfo)))))
      (while --dolist-tail-- (setq p (car --dolist-tail--)) (let ((secret (plist-get p :secret)) (method (intern (plist-get p :port)))) (let* ((x (list (plist-get p :host) method (plist-get p :user) (if (functionp secret) (funcall secret) secret)))) (if (member x rcirc-authinfo) rcirc-authinfo (setq rcirc-authinfo (cons x rcirc-authinfo))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
      (let ((--dolist-tail-- (auth-source-search :port (quote ("nickserv" "bitlbee" "quakenet")) :require (quote (:port :user :secret)))) p) (while --dolist-tail-- (setq p (car --dolist-tail--)) (let ((secret (plist-get p :secret)) (method (intern (plist-get p :port)))) (let* ((x (list (plist-get p :host) method (plist-get p :user) (if ... ... secret)))) (if (member x rcirc-authinfo) rcirc-authinfo (setq rcirc-authinfo (cons x rcirc-authinfo))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
      spacemacs//rcirc-authinfo-config()
      (if (file-exists-p "~/.authinfo.gpg") (spacemacs//rcirc-authinfo-config) (message "Warning: Cannot find file ~/.authinfo.gpg"))
      (if arg nil (if (file-exists-p "~/.authinfo.gpg") (spacemacs//rcirc-authinfo-config) (message "Warning: Cannot find file ~/.authinfo.gpg")))
      spacemacs//rcirc-with-authinfo(nil)
      (cond (rcirc-enable-authinfo-support (spacemacs//rcirc-with-authinfo arg)) (rcirc-enable-znc-support (spacemacs//rcirc-with-znc arg)) (t (rcirc arg)))
      spacemacs/rcirc(nil)
      call-interactively(spacemacs/rcirc nil nil)
      command-execute(spacemacs/rcirc)

The same problem I was running into in issue #847. The problem is the same, the `spacemacs/rcirc` function is trying to configure rcirc before it's loaded (through `spacemacs//rcirc-with-authinfo` and `spacemacs//rcirc-with-znc`).

**Comment by syl20bnr** [comment]
We have fix :-)
I will soon push the `0.100.1`, thank you for the report !

**Comment by syl20bnr** [comment]
@jcpetkovich Are you around ? Can you test again with the fix on develop ?

**Comment by jcpetkovich** [comment]
It works! But one small problem, the log directory isn't created by default. Should this be added to the git repo? Or created during init?

**Comment by syl20bnr** [comment]
Great ! Thank you for testing.
It should be created during init when the path is defined.

**Comment by syl20bnr** [comment]
I close this issue since it fixed in master.
@jcpetkovich do you PR a fix for the creation of the directory ?

**Comment by jcpetkovich** [comment]
Hmm, no I didn't, but it should be easy enough if you want it.

**Comment by jcpetkovich** [comment]
Done #899
