### ISSUE TITLE
projectile-rails-global-mode not disabled  cause emacs hanging

### ISSUE THREAD

**Issue by lihuanshuai** [syl20bnr/spacemacs#8650]
#### Description :octocat:
`projectile-rails-global-mode` is not disabled automatically after config loaded, which cause emacs hanging on `Sending Password ...` when use tramp with ssh sudo

related commit: syl20bnr/spacemacs@6aff353f279fbfed2689888b10477584eb3d3896

#### Reproduction guide :beetle:

- Start Emacs
- open remote file on remote severs with ssh+sudo

*Observed behaviour:* :eyes: :broken_heart:

can not view or edit file on remote servers with ssh+sudo

*Expected behaviour:* :heart: :smile:

`projectile-rails-global-mode` should be disabled automatically after config loaded

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust search-engine vinegar vim-powerline chrome command-log dash docker puppet ranger
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      systemd themes-megapack cscope
      (gtags :variables gtags-enable-by-default nil)
      git github osx bibtex c-c   clojure common-lisp csv emacs-lisp erlang ess extra-langs go html java javascript latex lua markdown ocaml python ruby scala shell-scripts sml sql swift typescript yaml chinese django react ruby-on-rails better-defaults org ibuffer spell-checking syntax-checking
      (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
      helm slack)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
```

**Comment by asok** [comment]
Unfortunately I don't have a remote box I could test tramp with ssh+sudo.

If you first do `M-x eval-expression RET (projectile-rails-global-mode -1) RET` and later visit a remote file do you have the same error?
Are you opening a file within a rails project on the remote server? If yes, do you have this error when opening any other file outside of a rails project?

**Comment by lihuanshuai** [comment]
I can reproduce it now after updating my packages, but I did struggled with the problem for a while and get a  workaround: I will run `M-x projectile-rails-global-mode` to disable it after booting on emacs. thanks!
