### ISSUE TITLE
How do I deactivate the *spacemacs* buffer?

### ISSUE THREAD

**Issue by dangom** [syl20bnr/spacemacs#8652]
Don't get me wrong, I just like to startup on an empty scratch buffer, that's all.

**Comment by jdtw** [comment]
Try putting `(setq initial-buffer-choice t)` in your `dotspacemacs/user-config`. From the documentation (`SPC h d v initial-buffer-choice`):

```
Documentation:
Buffer to show after starting Emacs.
If the value is nil and ‘inhibit-startup-screen’ is nil, show the
startup screen.  If the value is a string, switch to a buffer
visiting the file or directory that the string specifies.  If the
value is a function, call it with no arguments and switch to the buffer
that it returns.  If t, open the ‘*scratch*’ buffer.
```

**Comment by dangom** [comment]
This doesn't work for Spacemacs. Only for vanilla Emacs.

**Comment by jdtw** [comment]
Have you tried it? It works for me -- and [this](https://github.com/syl20bnr/spacemacs/blob/master/core/core-spacemacs.el#L203-L207) comment in the source seems to imply that it's supported:

```
     ;; This is set here so that emacsclient will show the startup buffer (and
     ;; so that it can be changed in user-config if necessary). It was set to
     ;; nil earlier in the startup process to properly handle command line
     ;; arguments.
     (setq initial-buffer-choice (lambda () (get-buffer spacemacs-buffer-name)))
```

**Comment by dangom** [comment]
I tried it and it didn't work. 

Now I killed all my buffers, deleted my layouts, quit and restart, and it worked.
My bad, and thanks for the answer.
