### ISSUE TITLE
Problem running projectile compile

### ISSUE THREAD

**Issue by boothead** [syl20bnr/spacemacs#866]
I've just switched from regular emacs where I use projectile compilation heavily in my workflow `C-c p c` and then enter a custom command.

I've tried what I thought was the equivalent in spacemacs: `<SPC> p c` and I get the following error:

```
command-execute: Symbol's function definition is void: projectile-compile-project
```

I assume I've missed some set up, but I couldn't find what the issue might be. The only change I've made is to generate a `~/.spacemacs` file and add haskell to the `dotspacemace-configuration-layers`

**Comment by boothead** [comment]
I see that this keybinding is quite new: #715. I've also confirmed that it's broken on my windows machine.

**Comment by mijoharas** [comment]
Just fyi, I was seeing this for a bit, and I think it may only be bound after you have ensured that projectile is loaded as projectile is lazy loaded by `use-package`. so try `SPC p f` and then going to a file, and then try `SPC p c`. Your issue may be different. This still seems like a bug, I've found this happening with a few functions that don't seem to be loaded when you might assume that they would be by `use-package`.

**Comment by boothead** [comment]
Yes, you're right `<SPC> p f` loads projectile and then the other command works too!

Do you have this setup to somehow work at start up?

**Comment by syl20bnr** [comment]
I added the missing functions to `:commands`, it is fixed in develop.

**Comment by mijoharas** [comment]
Ahhh... so you add it to commands in `use-package`.

Incidentally, how should I address this issue in the case of dependencies? say I have layer `my-foo-layer` that defines `foo-function` that requires that `projectile` be loaded for it to work. I have `(use-package 'foo-package ...)` and stuff, but the function that `foo-package` exports (`foo-function`) won't work unless it loads projectile. How would I deal with something like that? is there a command to load projectile in the `init` of my `use-package` call there? (p.s. really sorry if this is confusing, i'm trying to give a small example of an issue I ran into a while ago)

**Comment by syl20bnr** [comment]
I guess that `foo-package` will have a `(require 'projectile)` in its implementation if it depends on projectile API so no problem with that.

**Comment by mijoharas** [comment]
ok cool, Thanks.

**Comment by boothead** [comment]
Great work thanks! Is it generally safe to switch to the develop branch?

**Comment by syl20bnr** [comment]
Since spacemacs has a modular architecture and since 0.100.0 with non blocing errors at startup I would say yes it is pretty safe.
