### ISSUE TITLE
Neo Tree Open on Right Regression?

### ISSUE THREAD

**Issue by jamieorc** [syl20bnr/spacemacs#8662]
#### Description :octocat:
NeoTree regression? NeoTree no longer opens on right when configured to do so.
Formerly, worked on master branch from a few months ago. This week I
upgraded to current develop branch and can no longer configure NeoTree
to open on right.

I confirmed this is a develop branch regression. Restarting Spacemacs from the 
master branch reverts to NeoTree working as configured--opens on right side
of window.

#### Reproduction guide :beetle:
- Start Emacs from develop branch
- in dotspacemacs/init, set `neo-window-position 'right`
- restart Spacemacs
- open project file
- open NeoTree

*Observed behaviour:* :eyes: :broken_heart:
NeoTree opens on left instead of right

*Expected behaviour:* :heart: :smile:
NeoTree opens on right

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 12eacab6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults clojure csv elixir emacs-lisp erlang git github html java javascript markdown org osx ranger
      (ruby :variables ruby-version-manager 'rvm ruby-test-runner 'rspec)
      ruby-on-rails scheme
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking sql syntax-checking tabbar themes-megapack version-control yaml)
```
- System configuration features: DBUS NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by duianto** [comment]
Confirmed, evaluating `M-:` `(setq neo-window-position 'right)`, works on master but not on develop.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. e2a45e0c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(haskell
 (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
 autohotkey emacs-lisp git helm markdown neotree org spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by Tehnix** [comment]
Has anyone figured out any workaround for this? I find it mildly annoying, and am not sure what to do to fix it.
