### ISSUE TITLE
Jump-to-definition could be improved

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#8663]
#### Description :octocat:
Jump-to-definition is awful in Clojure and Clojurescript

#### Explanation
The way how Spacemacs handles `jump-to-definiton` (`g d` or `, g g`) with `core-jump.el` is nice, yet it does not work as one would expect. Currently my main language of use is Clojure, so I can only describe Clojure here, it may be applicable to other languages as well.

Clojure layer defines jump-handlers and adds `cider-find-var` to the list.

There is a couple of problems with this:

a) `cider-find-var` only works when there's a connected repl and miserably fails when there's no REPL 
b) `cider-find-var` prompts for a symbol to jump to, even when the cursor on a symbol, although `cider-prompt-for-symbol` is set to nil in the layer's packages.el. I'm not sure about this one - might be an upstream issue

#### Proposed solution

Maybe we could do something like this:

- If there's a connected REPL (cider jacked in) - then try to use `cider-find-var` (without it prompting for a symbol)
- when there's no repl - use `dumb-jump-go`. 

Can someone suggest maybe even better way? Thanks!

### Also

it seems that `g d` and `, g g` - strictly not the same. sometimes the first one uses `evil-goto-definition` and not the function listed in jump-handler list. Can someone elaborate on the differences and how to make (if they should be) the same thing?

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 12eacab6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((org :variables org-enable-reveal-js-support t org-enable-bootstrap-support t org-enable-github-support t :packages
      (not org-present))
 csv yaml emacs-lisp javascript
 (html :packages
       (not pug-mode slim-mode))
 (markdown :variables markdown-live-preview-engine 'vmd)
 (shell-scripts :packages
                (not fish-mode))
 clojure lua
 (ruby :variables ruby-version-manager 'rvm)
 haskell
 (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 syntax-checking spell-checking helm
 (shell :variables shell-enable-smart-eshell t comint-scroll-show-maximum-output nil comint-move-point-for-output nil)
 fasd
 (ibuffer :variables ibuffer-old-time 8)
 osx restclient emoji search-engine imenu-list docker git
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 (github :packages
         (not magit-gh-pulls)
         :variables gist-view-gist t)
 ag-dired ag-general ag-dash ag-synonyms ag-org ag-clojure ag-cal)
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by syl20bnr** [comment]
> If there's a connected REPL (cider jacked in) - then try to use cider-find-var (without it prompting for a symbol)
when there's no repl - use dumb-jump-go

For this one a wrapper function should do the trick. This function should do nothing if there is no REPL otherwise it should call `cider-find-var`

> it seems that g d and , g g - strictly not the same. sometimes the first one uses evil-goto-definition and not the function listed in jump-handler list. Can someone elaborate on the differences and how to make (if they should be) the same thing?

I need a repro step for this one, `SPC h d k` for `gd` gives the expected key binding:

```
g d runs the command spacemacs/jump-to-definition (found in
evil-normal-state-map), which is an interactive Lisp function in ‘core-jump.el’.
```

**Comment by jr0cket** [comment]
If it were just a matter of detecting the REPL was connected, then you could have a keybinding as follows

```
          "gg" (if (cider-connected-p)
                   'spacemacs/jump-to-definition
                 'dumb-jump-go)
```
You would also need to include `(require 'cider-client)` in the file somewhere.

However, it seems the definition needs to be evaluated in the Clojure REPL before `spacemacs/jump-to-definition` will find it (unless I've missed some argument I need to give jump-to-definition).  With the above code I am still prompted for a Symbol to jump to, altough when typing the symbol name in then the symbol definition is found.

The function `cider-connected-p` is from cider-client.el https://github.com/clojure-emacs/cider/blob/master/cider-client.el

**Comment by syl20bnr** [comment]
PR has been merged in develop branch.

**Comment by wallydrag** [comment]
Is there an immediate fix for this?
