### ISSUE TITLE
Add support for RefactoringTools/HaRe to the Haskell layer

### ISSUE THREAD

**Issue by mrkgnao** [syl20bnr/spacemacs#8664]
[HaRe](https://github.com/RefactoringTools/HaRe) is an amazing refactoring tool that I just learned about. It does renaming, promoting and demoting of definitions, etc. 

I actually learned about it from an announcement for [haskell-tools](http://haskelltools.org/), which is seeing more activity but only has Atom integration now. On the other hand, a HaRe installation generates some Emacs Lisp (**it's not on MELPA yet**, which is a problem) which you can autoload in `user-config`.

I think many people would like Spacemacs support for it: see https://github.com/RefactoringTools/HaRe/issues/7. I've written some bindings for my own use, which are given below. Here's an example: suppose we have this silly code:

```haskell

original :: IO ()
original = print val
  where
    val =
      if val' == 3
        then 4
        else 5
    val' = 3

```
With my cursor on the definition of `val`, on pressing `SPC m e k` or `, e k` (`hare-refactor-lift-one`), `val` is extracted as follows:

```haskell
original :: IO ()
original = print (val val')
  where
    val' = 3

val val' =
  if val' == 3
    then 4
    else 5
```

Here is what I have currently in `init.el`, in `user-config`. (I don't know if it's good to load packages there, I'm a noob, haha.) The first few lines are from the HaRe readme.

```elisp

(add-to-load-path 
  "/home/mrkgnao/.stack/snapshots/x86_64-linux/lts-8.8/8.0.2/share/x86_64-linux-ghc-8.0.2/HaRe-0.8.4.0/elisp/")
(require 'hare)
(autoload 'hare-init "hare" nil t)

(spacemacs/declare-prefix-for-mode 'haskell-mode "me" "haskell/hare-refactor")
(spacemacs/set-leader-keys-for-major-mode 'haskell-mode
  "ej" 'hare-refactor-demote
  "ek" 'hare-refactor-lift-one
  "eK" 'hare-refactor-lifttotop
  "ei" 'hare-refactor-iftocase
  "ey" 'hare-refactor-dupdef
  "ec" 'hare-refactor-rename
  )

(defun haskell-mode-custom-hook ()
  (message "Running haskell-mode-hook")
  (intero-mode)
  (push '(company-ghci :with company-yasnippet
                       :with company-dabbrev)
        company-backends-haskell-mode)
  (interactive-haskell-mode)
  (turn-on-haskell-indentation)
  (hlint-refactor-mode +1)
  (hindent-mode)

  ;; This is new
  (ghc-init)
  (hare-init)

  (setq haskell-stylish-on-save t)
  (message "Completed haskell-mode-hook"))

(add-hook 'haskell-mode-hook 'haskell-mode-custom-hook)

```

Other concerns:

* how well will it play with Intero? Not seeing any trouble so far, but it relies on `ghc-mod` internally, which I've heard isn't very compatible with Stack.

**Comment by alanz** [comment]
In terms of other concerns, ghc-mod does work with stack. But also with plain cabal projects. Which is one of the main reasons we use it.

If you want to make a PR on haskell mode, or the spacemacs layer, that would be awesome.

**Comment by mrkgnao** [comment]
I'm not sure how to go about "guessing" the path to the `elisp/` directory as I don't have any experience with writing cross-platform-y things like that, especially since there will be people who don't use Stack.

If that could be put into a `defvar` (I think that's the correct term?) then I could just copy my bindings into the existing Haskell layer.

**Comment by alanz** [comment]
Sounds good to me. Then experts who are irked by the defvar can fix it up, which is the joy of community driven software dev. Make a positive change, even if it is not perfect.
