### ISSUE TITLE
Themes only change character colors.

### ISSUE THREAD

**Issue by kgourgou** [syl20bnr/spacemacs#8669]
#### Description :octocat:
Switching themes only changes the color of the characters and not the background.
I have this issue on two different computers, both running Ubuntu 16.04. with the same 
setup. 

Tried to re-install the themes-megapack and momentarily (meaning, during installation) I could see some colors in the background but nothing had changed when I restarted the editor. 

Also run without the megapack and tried switching between a light and a dark theme. Again, nothing changed. 

#### Reproduction guide :beetle:
- Start Emacs
- [SPC T s] and pick a theme.

*Observed behaviour:* :eyes: :broken_heart:
The color of the characters changes to match the theme,
but not the background colors. That is fixed to the standard theme (spacemacs-dark).

With spacemarks-dark:
![screenshot from 2017-04-09 14-10-24](https://cloud.githubusercontent.com/assets/2594318/24839752/69a1567e-1d2e-11e7-92c7-f1e1dcf13a50.png)

With solarized-light:
![screenshot from 2017-04-09 14-10-44](https://cloud.githubusercontent.com/assets/2594318/24839751/676ce1d4-1d2e-11e7-96ac-67479c542e87.png)

*Expected behaviour:* :heart: :smile:
Everything changes to match the theme. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.50.2
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(octave auto-completion emacs-lisp git github markdown
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        spell-checking syntax-checking
        (latex :variables latex-enable-auto-fill t latex-enable-folding t)
        python html themes-megapack ipython-notebook pdf-tools)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by syl20bnr** [comment]
Do you have some custom settings related to background color in your dotfile ?

**Comment by kgourgou** [comment]
I should have researched more. However, I reinstalled spacemacs from scratch while keeping the same .spacemacs file and now colors change again on both machines. Maybe we can close this for now and I'll see if I have the same issue after an update of the packages or something.

**Comment by syl20bnr** [comment]
Great, you can close the issue if it is resolved for you 👍

**Comment by lijingjiang** [comment]
Exactly the same issue happens here, the whole reinstall doesn't solve this bug.

**Comment by mathpunk** [comment]
I've got the same issue. In case it helps, here's my system config. I'm going to try reinstalling.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 22deb27)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(javascript own ivy better-defaults
            (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-space-key-behavior 'reject auto-completion-return-key-behavior 'reject auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-complete-with-key-sequence "df" auto-completion-complete-with-key-sequence-delay 0.3)
            (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/usr/bin/zsh" shell-default-height 40 shell-default-position 'bottom)
            shell-scripts
            (org :variables org-enable-reveal-js-support t org-enable-org-journal-support t)
            yaml csv html restclient emacs-lisp javascript clojure
            (ruby :variables ruby-test-runner 'rspec ruby-version-manager 'chruby ruby-enable-enh-ruby-mode t)
            syntax-checking git github markdown deft latex colors themes-megapack typography emoji)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by mathpunk** [comment]
Reinstall worked. :man_shrugging:

**Comment by yourpalal** [comment]
I resolved this problem by deleting custom-set-faces calls from my spacemacs config, as described [here](https://unix.stackexchange.com/questions/421803/emacs-background-color-doesnt-change-when-i-load-different-themes?newreg=587008b53ab9430ab2b484e7945b4bc3).
