### ISSUE TITLE
access ghci history

### ISSUE THREAD

**Issue by amilkov1** [syl20bnr/spacemacs#8671]
Is there a way to see/access your ghci history in the standard REPL that comes as part of the Haskell layer? (Essentially the equivalent of Ctrl-r in a shell or even just up arrow key to view recently submitted commands)

**Comment by mrkgnao** [comment]
@amilkov1 does `C-k` work (or `C-c M-o` in Emacs mode, or maybe `M-n`/`M-p`)?

**Comment by amilkov1** [comment]
`C-k` yields a `Text is read-only : #<buffer myfile*>
`M-n` `M-p` and `C-c M-o` don't do anything

**Comment by ccressent** [comment]
up arrow, down arrow, `M-n`, `M-p`, `C-j` and `C-k` work as expected for me.
No special configuration necessary. I just `, s S` from a Haskell buffer to get a REPL and it all works. I'm using stack and intero if that makes a difference. Here is my Haskell layer configuration:

```emacs-lisp
(haskell :variables
         haskell-completion-backend 'intero
         haskell-enable-hindent-style "johan-tibell")
```

**Comment by amilkov1** [comment]
Yup. Doesn't seem to work with `ghci` as the designated backend (just tried it) but intero does the trick

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
Add C-j, C-k, C-l to ghci repl in haskell layer #13184
