### ISSUE TITLE
Report spacesmacs issue instruction submission doesn't work 

### ISSUE THREAD

**Issue by mpacer** [syl20bnr/spacemacs#8676]
#### Description
After filling text out, selecting an issue and deleting the line saying 
``<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-c C-c` TO SUBMIT>>``
and pressing `C-c C-c` no issue submission occurs. 

#### Reproduction guide :beetle:
- Start Emacs
- activate REPORT_SPACEMACS_ISSUE buffer using `Spc h I` 
- edit text
- enter another buffer (or maybe something else…I can't figure out what exactly happened)
- Follow instructions, hit <kbd>⌃</kbd>-<kbd>c</kbd>  <kbd>⌃</kbd>-<kbd>c</kbd> (using kbd notation to point out that these were the actual keys hit)

*Observed behaviour:* :eyes: :broken_heart:
It does not submit and close. 

*Expected behaviour:* :heart: :smile:
It submits and closes.

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.50
- Spacemacs: 0.200.8
- Spacemacs branch: master (rev. bd7ef98e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm command-log better-defaults emacs-lisp git
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      version-control)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
```

**Comment by syl20bnr** [comment]
I cannot reproduce it here.
Are you able to reproduce it 100% of the time ?
Looks to me that you somehow changed the major mode of the buffer.

**Comment by mpacer** [comment]
Does not reproduce 100% of the time (just successfully submitted #8684 via the spacemacs interface), but it's unclear what's happening when it does go wrong (or how to debug it when it happens).

It wasn't a vim/evil mode issue (that's where I'm coming from so I can navigate around that pretty easily) but I tried hitting ⌃-g and Esc many times to get out of whatever mode I was in and it did nothing to help. 

Given the issue with reproducing this, feel free to close but it's still a usability issue (given the difficulty I had trying to figure out what was going on let alone being unable to get submission to work).

**Comment by achikin** [comment]
I have the same issue `C-c C-c is undefned`

**Comment by achikin** [comment]
I've used undo tree to undo some changes in the buffer which got me back into command mode.

**Comment by achikin** [comment]
I've tried once more. Pasting any text gets you back into normal mode.
