### ISSUE TITLE
Windows server mode

### ISSUE THREAD

**Issue by sho-87** [syl20bnr/spacemacs#8678]
I'm able to start emacs as a daemon and connect using client by following the instructions [here](https://www.emacswiki.org/emacs/EmacsMsWindowsIntegration#toc7)

However, I want to avoid having to create shortcuts on all of my machines so I wonder if theres a way to do it in the `.spacemacs` file

What I want is be able to open `runemacs.exe` and if no server is running, start one. Then when I `SPC-q-q`, quit the running frame but keep the server alive. When I open `runemacs.exe` again, connect to the existing server

In my `.spacemacs` file I have `dotspacemacs-persistent-server` set to true but it doesnt seem to do anything. And when I kill the frame with `SPC-q-z` and open `runemacs.exe` again it doesn't connect to the existing server

I've seen a potential solution [here](http://emacs.stackexchange.com/questions/25039/emacs-24-5-1-on-windows-how-to-use-server-mode), but where would I put that code in my `.spacemacs` file?

**Comment by luochen1990** [comment]
+1, I'm using the following command

`"emacsclientw.exe" --alternate-editor="runemacs.exe" "%1"`

and find that when a emacs client is quited, the server process is still running, and when repeat running the command for several times, there will be a lot of server process here.
![image](https://user-images.githubusercontent.com/2309868/28516804-0bbff4ba-7095-11e7-8fb1-99686a66bdf3.png)

Seems like every time I run this command, a new server process is created.

I'm trying with the following environment:
OS: windows 10
Emacs: 
![image](https://user-images.githubusercontent.com/2309868/28516904-5d4cc308-7095-11e7-80bf-2fdb387b5f36.png)

**Comment by GoorMoon** [comment]
Hi,
I'm using the following command

`emacsclientw.exe -nw -a ""`

and no additional servers is created
OS: **Windows 10**
Emacs: 
**GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-09-17**

**Comment by peschkaj** [comment]
[emacswiki](https://www.emacswiki.org/emacs/EmacsMsWindowsIntegration) encourages @GoorMoon's approach on systems newer than XP. I've also had a great deal of success using [Emacs modified for Windows](https://vigou3.github.io/emacs-modified-windows/) (really just an all-inclusive build).
