### ISSUE TITLE
fill-column-indicator does not display with split windows.

### ISSUE THREAD

**Issue by barischrooneyj** [syl20bnr/spacemacs#8681]
#### Description :octocat:
fill-column-indicator does not display with split windows.

#### Reproduction guide :beetle:
- Start Emacs
- Open a buffer with some text
- Ensure fill-column-indicator enabled with `SPC t f`
- Vertical split window using `SPC w v`
- Ensure the character width in each window is enough such that fill column indicator is expected.

*Observed behaviour:* :eyes: :broken_heart:
- Only arrows are displayed on the right-hand side of each window.

*Expected behaviour:* :heart: :smile:
Fill column indicator at expected character limit.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp git markdown org spell-checking syntax-checking version-control
      (haskell :variables haskell-completion-backend 'intero)
      javascript osx python react)
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by bmag** [comment]
Can you post a screenshot? I tried to repro but as long as the window is wide enough I can see the indicator. Perhaps you can't see the indicator because the window isn't wide enough?

**Comment by barischj** [comment]
Here are 4 screen shots:

- single window, showing fill-column-indicator.

- vertical split, **not** showing fill-column-indicator.

- small font (`cmd -`), single window, showing fill-column-indicator.

- small font (`cmd -`), vertical split, **not** showing fill-column-indicator.

*Interestingly* the fill-column-indicator does not change position when font is decreased.

<img width="1276" alt="screen shot 2017-04-19 at 09 41 44" src="https://cloud.githubusercontent.com/assets/6631452/25171225/fd8c353a-24e4-11e7-8fd3-17683e06dd9c.png">
<img width="1276" alt="screen shot 2017-04-19 at 09 41 55" src="https://cloud.githubusercontent.com/assets/6631452/25171224/fd870182-24e4-11e7-85d1-c306ccd803a9.png">
<img width="1276" alt="screen shot 2017-04-19 at 09 42 11" src="https://cloud.githubusercontent.com/assets/6631452/25171223/fd827946-24e4-11e7-947f-e105913206ff.png">
<img width="1276" alt="screen shot 2017-04-19 at 09 42 58" src="https://cloud.githubusercontent.com/assets/6631452/25171222/fd7c8824-24e4-11e7-854a-c1121bcb4017.png">

I then checked if the issue occurs when I change font in my `.spacemacs` config and `SPC q r`, lo and behold the fill-column-indicator appears.

Seems to be the osx layer[bindings](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bos/osx#key-bindings) `cmd -` (and `cmd +)` using spacemacs font scaling which font-column-indicator doesn't correctly adapt to.
