### ISSUE TITLE
No TAB for shell-command completion

### ISSUE THREAD

**Issue by maxbeegee** [syl20bnr/spacemacs#8691]
#### Description :octocat:
Tab completion for shell command does not work. Instead I get the message
`helm-flx-fuzzy-matching-sort: Wrong number of arguments: (2 . 2), 3`

#### Reproduction guide :beetle:
- Start Emacs
- M-!
- Type `ls .e` and press `TAB`
- The above error message appears (although, e.g., the `.emacs.d` folder exists) 

*Observed behaviour:* :eyes: :broken_heart:
Minibuffer echoes `Wrong number of arguments: (2 . 2), 3`. No completion

*Expected behaviour:* :heart: :smile:
Completion to `.emacs.d` (in the esample above)

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.8
- Spacemacs branch: master (rev. bd7ef98)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(markdown python helm
          (auto-completion :variables auto-completion-enable-help-tooltip t)
          better-defaults emacs-lisp org spell-checking latex c-c  )
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by bmag** [comment]
This is a bug that was fixed upstream 9 days, see #8630. Please update your packages and close the report if the issue was solved.
