### ISSUE TITLE
C-c C-e in counsel-ag results in "C-c C-e is undefined" error.

### ISSUE THREAD

**Issue by tizoc** [syl20bnr/spacemacs#8693]
#### Description :octocat:
`C-c C-e` in `counsel-ag` does nothing, but it should switch to edit mode.

According to:

https://github.com/syl20bnr/spacemacs/blob/master/layers/+completion/ivy/funcs.el#L119-L123

it should work.

I see that I'm not the only one with this issue:

https://sam217pa.github.io/2016/09/11/nuclear-power-editing-via-ivy-and-ag/

#### Reproduction guide :beetle:
- Start Emacs
- Do a search with `counsel-ag`
- Do `C-c C-e` to enter in edit mode (like in `helm-ag`)

*Observed behaviour:* :eyes: :broken_heart:
"C-c C-e is undefined" error.

*Expected behaviour:* :heart: :smile:
Enter edit mode like in `helm-ag`.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(sql
 (auto-completion :variables auto-completion-enable-help-tooltip t)
 better-defaults emacs-lisp git markdown org ocaml python syntax-checking yaml ansible themes-megapack react ivy)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
no backtrace
```

**Comment by bmag** [comment]
Spacemacs doesn't bind the command `counsel-ag`, that's why `C-c C-e` doesn't work there. Instead Spacemacs uses its own command `spacemacs/counsel-search` and various wrapper commands around it. The various search commands are those bound `SPC s a` (ag), `SPC s t` (pt), etc. and have names similar to "spacemacs/search-project-ag".

**Comment by tizoc** [comment]
That makes sense. Thank you.
