### ISSUE TITLE
helm-project-do-rg broken on master

### ISSUE THREAD

**Issue by agriffis** [syl20bnr/spacemacs#8694]
#### Description :octocat:
SPC-/ says `Wrong type argument: commandp, helm-project-do-rg`

#### Reproduction guide :beetle:
- Install ripgrep
- Start Emacs
- Set `dotspacemacs-search-tools '("rg" "ag" "pt" "ack" "grep")`
- Press `SPC-/`

*Observed behaviour:* :eyes: :broken_heart:
`Wrong type argument: commandp, helm-project-do-rg`

*Expected behaviour:* :heart: :smile:
helm search

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults git github
                 (clojure :variables clojure-enable-fancify-symbols t)
                 csv django emacs-lisp haskell html javascript markdown org python react ruby rust vimscript yaml
                 (syntax-checking :variables syntax-checking-enable-by-default nil))
```
- System configuration features: JPEG SOUND GPM DBUS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 ZLIB

**Comment by bmag** [comment]
That's because ripgrep isn't supported in the stable release yet. Support for ripgrep should be added in the next major release (I don't have an estimate for when that will happen).

**Comment by agriffis** [comment]
Thanks @bmag, my mistake. I've been using develop for a long time and switched back to master, just didn't realize that ripgrep wasn't included yet.
