### ISSUE TITLE
Symbol’s value as variable is void: hydra-ivy/keymap

### ISSUE THREAD

**Issue by et2010** [syl20bnr/spacemacs#8698]
#### Description :octocat:
When start spacemacs, a warning pops:
Error (use-package): ivy :config: Symbol’s value as variable is void: hydra-ivy/keymap

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Error (use-package): ivy :config: Symbol’s value as variable is void: hydra-ivy/keymap

*Expected behaviour:* :heart: :smile:
No error

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: private (rev. 8f870250)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :disabled-for org latex)
 autohotkey better-defaults bibtex chrome csv dash elpy emacs-lisp
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 git github ibuffer imenu-list latex markdown nlinum
 (org :variables org-projectile-file "TODOs.org" org-enable-reveal-js-support t org-reveal-js "file:///home/neoarch/git/reveal")
 org-config
 (han :variables han-enable-youdao-dict t han-enable-fcitx t han-org-line-spacing 0.2)
 pdf-tools
 (plantuml :variables org-plantuml-jar-path "/usr/bin/plantuml" plantuml-jar-path "/usr/bin/plantuml")
 pfc-fish rcirc
 (rebox :variables rebox-style-loop
        '(71 72 73))
 scimax
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts spell-checking syntax-checking version-control vim-powerline whizzytex yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:

This line from recent commit seems to be the culprit:
https://github.com/syl20bnr/spacemacs/commit/a8f68c0cca450ce93d527b5a581a54a3edd3c474#diff-3848bd6ce8c59b7e9edb57c083a62d14R170

**Comment by jackkamm** [comment]
I also get this error upon updating develop branch this morning

**Comment by bmag** [comment]
Waiting for @Somelauw to fix the PR, then I'll merge it. In the meantime you can comment out the offending line (`define-key hydra-ivy/keymap ...`).

**Comment by bmag** [comment]
Upon further testing I realised the PR is good and doesn't need to be fixed, so I merged it. Introduced and fixed in develop, so I'm closing this issue.
