### ISSUE TITLE
Command `f` is not documented internally

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#870]
`describe-key f` says its function is not documented, link to its function source is wrong and its function name `evil-escape-motion-state` is weird (I think it should be `evil-find-char-forward`). Command `F` does not have those problems.

**Comment by syl20bnr** [comment]
Thanks for the report. Evil-escape wraps the command on `f` in order to provide the `fd` behavior. I will improve the documentation string on the wrapper to explain what it is and what it allows.

**Comment by syl20bnr** [comment]
Added to evil-escape 2.26 (will be available in MELPA in a couple of hour).
