### ISSUE TITLE
add support for easily managing config files in repos

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#8701]
What I realy like about emacs is that I can just save the whole `.emacs.d/` folder in my repo and wherever I am I can clone it and have an exactly same emacs everywhere.
With spacemacs its not that trivial.
It would be nice, if saving the `.spacemacs `and the `/private/` folder in a repo would be enough and spacemacs asks for a config repo at its first startup.
This way I just have to clone the spacemacs repo into my` .emacs.d/ `
and  then when I start spacemacs I would be asked for my config repo, and I dont have to clone it manualy and move config files around.

**Comment by Somelauw** [comment]
You can rename ~/.spacemacs to ~/.spacemacs.d/init.el and move the contents of ~.emacs.d/private to ~/.spacemacs.d

**Comment by madand** [comment]
This is easily doable with ol' good shell scripting.

Here my installation script: https://github.com/madand/dotemacs/blob/master/install.sh. Note that I use `~/.emacs` as my custom config directory, but you can easily change it to `.spacemacs.d` or anything.

Then installation on the new machine is as easy as:

```bash
curl -Lo - "https://raw.githubusercontent.com/MadAnd/dotemacs/master/install.sh" | bash
```

If you want to include your private layers, you also need to set `dotspacemacs-configuration-layer-path`, like this:
```emacs-lisp
   dotspacemacs-configuration-layer-path '("~/.emacs/layers/")
```

If you use Yasnippet from `auto-completion` layer, you can also include your private snippets:
```emacs-lisp
   dotspacemacs-configuration-layers
   '(
     (auto-completion :variables
                      auto-completion-private-snippets-directory "~/.emacs/snippets")
```

**Comment by bitwalda** [comment]
@madand this is realy nice, but It doesnt work on windows i think.

**Comment by bitwalda** [comment]
@madand this is realy nice, but It doesnt work on windows i think.

**Comment by madand** [comment]
I stopped using windows about 10 years ago, so can't say for sure. But I heard that they added official [support of Linux](https://msdn.microsoft.com/en-us/commandline/wsl/about) environment. Also, there is [Cygwin](http://www.cygwin.com/).

**Comment by JAremko** [comment]
You can run Emacs in docker https://github.com/JAremko/docker-emacs  also https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bdistributions/spacemacs-docker (currently not at hub.docker.com - you'll need to build it)
