### ISSUE TITLE
mu4e send prompts for buffer removal from perspective.

### ISSUE THREAD

**Issue by choppsv1** [syl20bnr/spacemacs#8705]
#### Description :octocat:
Mu4e compose creates a new frame and buffer which land in default perspective
(even if you have mu4e in it's own perspective). When you send the mail and the
frame and buffer are being removed the system prompts you to verify you want to
remove the buffer from the perspective, which of course you do as you just told
the system to do that (by sending the mail).

This seems to be very similar to #7931
(https://github.com/syl20bnr/spacemacs/issues/7931).

#### Reproduction guide :beetle:
- Start Emacs
- load mu4e in it's own perspective
- compose a message
- send message
- get prompted

*Observed behaviour:* :eyes: :broken_heart:
As described above.

*Expected behaviour:* :heart: :smile:
Should not prompt for removal of buffer, should just do it.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 817f6e9f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :variables auto-completion-private-snippets-directory "~/.spacemacs.d/private/snippets" auto-completion-tab-key-behavior 'cycle)
 better-defaults docker github graphviz gtags ietf jabber mu4e org
 (osx :variables osx-use-option-as-meta t)
 pdf-tools ranger rebox
 (shell :variables)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-tooltips t)
 theming themes-megapack php csv
 (c-c   :variables c-c  -default-mode-for-headers 'c-mode c-c  -enable-clang-support t)
 emacs-lisp git go html javascript
 (latex :variables latex-build-command "latexmk")
 lua markdown
 (python :variables python-fill-column 120 python-test-runner
         '(pytest nose)
         python-auto-set-local-pyvenv-virtualenv nil python-auto-set-local-pyenv-virtualenv nil)
 (semantic :disabled-for emacs-lisp)
 shell-scripts systemd yaml
 (erc :variables erc-server-list
      '(("irc.freenode.net" :port "6697" :ssl t :nick "chopps"))))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by Miciah** [comment]
Does the following resolve this issue?
```emacs-lisp
(setq persp-add-buffer-on-after-change-major-mode 'free)
```

**Comment by choppsv1** [comment]
No I still get the prompt. Double checked that the value was set to 'free too, it was.
