### ISSUE TITLE
magit and smooth scrolling slow on windows 10

### ISSUE THREAD

**Issue by sho-87** [syl20bnr/spacemacs#8710]
I've been using spacemacs-base (with a few packages from spacemacs layers) on windows, and while the base distribution certainly feels faster than the standard distribution, there are still some moments of slowness that really interrupt my flow

There are 2 main culprits of this:

1. magit. the initial `git status` is slow because magit still needs to be inititalized, which is fine but every subsequent `SPC g s` takes 2-3 seconds to load the status buffer. The same things happens with commits `SPC g m c c`. This is on a really small repo (~50 commits, very few files). While 2 seconds doesnt sound like a lot, its enough to interrupt my thinking. Furthermore, both status and commit are instant when I run the same spacemacs config on my macbook  pro

2. smooth scrolling. When I move the cursor towards the bottom of the buffer and it begins to scroll it tends to lag, like the redraw rate isnt fast enough to match the scroll speed so line scrolling feels a bit jerky as if a few frames have been skipped. Again, this seems to work ok on OSX

My question is, is there an emacs build for windows that is optimized for these types of problems? If not, is there a way to speed up magit so the buffers show up quickly on windows?

**Comment by duianto** [comment]
I've used this windows version `emacs-w64-25.1-O2.7z` of Emacs for several months. I switch to it because it's built with image support. There's also a version with modules, but I don't know what means.
You could test if they work better: https://github.com/zklhp/emacs-w64/releases

I don't know how they compare to the official Gnu Emacs version.

**Comment by sho-87** [comment]
yeah I tried that version a couple of days ago and for some reason it feels worse on my computer

**Comment by sho-87** [comment]
I tried some cpu profiling to figure out whats going on with the scrolling issue:

```
- command-execute                                     101  43%
 - call-interactively                                        101  43%
  - byte-code                                                   91  39%
   - helm-M-x-read-extended-command        91  39%
    - helm-comp-read                                      91  39%
     - helm                                                        91  39%
      - apply                                                      91  39%
       - helm                                                      91  39%
        - apply                                                    91  39%
         - helm-internal                                      91  39%
          - helm-read-pattern-maybe                 85  36%
           - read-from-minibuffer                        78  33%
            + timer-event-handler                        34  14%
            + redisplay_internal (C function)            6   2%
            + command-execute                              5   2%
              minibuffer-inactive-mode                     1   0%
              evil-escape-pre-command-hook          1   0%
            + linum-update-current                          1   0%
            + winum--update                                    1   0%
           + helm-update                                         6   2%
          + helm-initialize                                        4   1%
          + #<compiled 0x211196f>                       2   0%
  + funcall-interactively                                     10   4%
- linum-update-current                                    99  42%
 - linum-update                                                99  42%
  - apply                                                             99  42%
   - ad-Advice-linum-update                             98  42%
    + #<compiled 0x27a7bc5>                          88  38%
      line-number-at-pos                                     10   4%
+ redisplay_internal (C function)                       12   5%
+ ...                                                                     11   4%
+ timer-event-handler                                         5   2%
+ yas--post-command-handler                           1   0%
+ which-key--hide-popup                                   1   0%
  undo-auto--add-boundary                                1   0%

```

I got those numbers by opening my `.spacemacs` file (https://github.com/sho-87/dotfiles/blob/master/spacemacs/.spacemacs), going to line 370, and just holding down `j` until end of buffer, then displayed the profile report

Emacs seems to want to spend a lot of calling `read-from-minibuffer` and doing line number updates? I've turned off both smooth scroll and highlight line for this (as suggested in https://github.com/syl20bnr/spacemacs/issues/6689) but they dont seem to be causing the issue

What else could I try?

**Comment by sho-87** [comment]
Also, it seems to be the long wrapped line in my `.spacemacs` that makes the screen lag a lot more than usual (line 452: https://github.com/sho-87/dotfiles/blob/master/spacemacs/.spacemacs#L452)
