### ISSUE TITLE
Rust: Could not locate executable "rustfmt"

### ISSUE THREAD

**Issue by JesApp** [syl20bnr/spacemacs#8713]
#### Description :octocat:
Could not locate executable "rustfmt"

When I try to run format a rust buffer, using (`SPC m =`) or (`SPC : rust-format-buffer`) I get the above error message. Using rustfmt via the command line works. The path variable - via (`SPC ! "echo $PATH"`) contains the rust bin directory. Code completion via racer (located in the same directory) works just fine.

#### Reproduction guide :beetle:
- Start Emacs
- Open rust file
- Type: `SPC m =`

*Observed behaviour:* :eyes: :broken_heart:
Minibuffer displays `Could not locate executable "rustfmt"`, source code in buffer is not formatted.

*Expected behaviour:* :heart: :smile:
Sourcecode in buffer is formatted by rustfmt.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown csv auto-completion better-defaults emacs-lisp org
          (latex :variables latex-enable-auto-fill nil latex-build-command "LaTeX")
          bibtex git
          (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
          semantic
          (python :variables python-enable-yapf-format-on-save t python-sort-imports-on-save t)
          (rust :variables rust-format-on-save t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by letheed** [comment]
I'm unable to reproduce.
@JesApp do you still have the same issue?

**Comment by JesApp** [comment]
Yes, I do. What's your setup? Maybe I can find the problem from looking at a working setup.

I just realized it doesn't say what distribution one's using up there. In my case it's arch linux. How about you?

**Comment by TinySong** [comment]
@JesApp maybe your PATH is incorrect in spacemacs, you can use below code to check your path,:
`(message "PATH: %s" (getenv "PATH"))
`in emacs-lisp mode

**Comment by letheed** [comment]
From what I can tell this is the error you get when `rust-format-buffer` from [rust-mode.el](https://github.com/rust-lang/rust-mode/blob/master/rust-mode.el#L1307) can't locate `rustfmt` using `executable-find` which will search your `exec-path` for it.

Could you check your exec-path with `SPC h d v` `exec-path`?

**Comment by JesApp** [comment]
Right, that helped! I wasn't aware that emacs had it's own search path for executables. I simply linked rustfmt into /usr/local/bin and now it works.

Thanks for your help, I learned something today. :)

**Comment by letheed** [comment]
@JesApp Alternatively:
* I don't know where you set your PATH but I'm going to assume that it's shell specific, since emacs doesn't inherit it in it's environment. Setting your PATH in .profile may solve this and make it available session wide.
* Or you may simply want to add `(exec-path-from-shell-initialize)` to your `dotspacemacs/user-config` to sync `exec-path` with your shell PATH.
