### ISSUE TITLE
Java layer failed to produce completion with eclim

### ISSUE THREAD

**Issue by WallyYang** [syl20bnr/spacemacs#8714]
#### Description :octocat:
Eclim Failed to complete at the point

#### Reproduction guide :beetle:
- Start Emacs
- Open a .java file
- Use SPC m d s to start eclimd
- type System.

*Observed behaviour:* :eyes: :broken_heart:
No completion options and "Cannot complete at the point" in minibuffer
java version "1.8.0_121"
eclipse version "Eclipse Java EE IDE Neon.3 Release (4.6.3)
eclim version "2.6.0"
*Message* buffer:
eclimd serving at port 9091
error in process filter: eclim--parse-result: Eclimd is currently being started. Please wait for it to be ready and retry.
error in process filter: Eclimd is currently being started. Please wait for it to be ready and retry.

*Expected behaviour:* :heart: :smile:
Method and objects in the packages shown in completion options, and can select from them

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion
 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
 emacs-lisp helm html markdown java org python semantic syntax-checking wally ycmd)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
```

**Comment by hshin23** [comment]
Same issue with me.

**Comment by hshin23** [comment]
adding the line `(setq eclimd-executable "path/to/your/eclimd")` to `dotspacemacs/user-config` fixed the problem for me. Running Spacemacs ver 200.9 with emacs version 25.2.1.

**Comment by WallyYang** [comment]
Eclim has been replaced with LSP in the newest version, I will close this for now.
