### ISSUE TITLE
rename should work with case-sensitive file names

### ISSUE THREAD

**Issue by timofeytt** [syl20bnr/spacemacs#8715]
#### Description :octocat:
`SPC f R` and the related rename-functionality with auto-complete makes it impossible 
to rename into case-sensitive versions of the same file.

#### Reproduction guide :beetle:
- Start Emacs
- Choose a file starting with an upper-case letter.
- Try to rename it to a lower-case.
- It matches its old name (underlined) and doesn't want to select what I've typed.

*Observed behaviour:* :eyes: :broken_heart:
- If I still press enter, it says that I've selected the same file. (It ignores letter case.)

*Expected behaviour:* :heart: :smile:
- It should accept the new case-sensitive name for a rename.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(markdown lua clojure php csv ocaml ivy auto-completion better-defaults emacs-lisp git org
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          ess extra-langs)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by timofeytt** [comment]
This also affects `magit-file-rename`.

**Comment by timofeytt** [comment]
As pointed out by @madand `C-M-j` is a work-around.

**Comment by madand** [comment]
This is already documented by #8702

**Comment by timofeytt** [comment]
Well, I feel like this is a user experience problem to be honest. Can't the implementation be a little smarter to handle this case with more grace? But you're right that at this point it's not a Spacemacs issue, but rather an ivy(?) issue.

**Comment by bmag** [comment]
As pointed by @madand, it is now documented in develop. It is more of a discovery issue with Ivy, really.

**Comment by timofeytt** [comment]
It is nice that there is now documentation, but in my opinion there is still a user experience problem. This issue depends on the linked swiper issue.

**Comment by madand** [comment]
Great news that ivy docs got merged. But in my opinion key chord `C-M-j` is not very vim-style-friendly in the sense of having too many modifier keys. So I also bound `ivy-immediate-done` to `C-RET` in my config:
```elisp
(define-key ivy-minibuffer-map (kbd "C-<return>") 'ivy-immediate-done)
```

If others consider that this is worth to be added to the ivy layer, I can make a PR.

I think that's pretty much all we can do on the Spacemacs side. Possible changes on the `ivy` side are up to the upstream. So this issue can be closed.

**Comment by duianto** [comment]
@madand 
There's a PR open for binding `C-<return>` to `ivy-immediate-done`
rebind 'ivy-immediate-done' to 'C-<return>' in ivy minibuffer #7753
and
`C-return` has been suggested on the Swiper repo:
ivy: Add C-return for immediate-done [#418](https://github.com/abo-abo/swiper/pull/418)

But that issue seems to have been closed because `C-return` translates to `C-j` in the terminal, and `C-j` is currently bound to `ivy-alt-done`.

**Comment by timofeytt** [comment]
Shouldn't this issue be assigned a special label like "external dependency" instead of being closed?

**Comment by bmag** [comment]
@timofeytt the issue is about renaming a file with Ivy. The official and supported way to do this is through <kbd>C-M-j</kbd> (`ivy-immediate-done`). It's documented in Ivy's official documentation and now also in our Ivy layer's documentation. As far as I'm concerned that means the issue is fixed. Adding another binding for `ivy-immediate-done` is already proposed in #7753.

**Comment by duianto** [comment]
Another way to confirm a filename with another case, has been introduced by @fabacino in this PR: 
ivy.el: Make prompt line selectable https://github.com/abo-abo/swiper/pull/1059

Just set the new `ivy-use-selectable-prompt` variable to `t`, then the `SPC f R` "New name: " prompt can be selected, by moving up the selection `C-p` above the first match.
