### ISSUE TITLE
Spacemacs ignores Magnet on macOS

### ISSUE THREAD

**Issue by carlodicelico** [syl20bnr/spacemacs#8717]
#### Description :octocat:
Spacemacs ignores Magnet on macOS

#### Reproduction guide :beetle:
- Start Spacemacs
- Use any Magnet shortcut to snap the window
- Try dragging to an edge of the window
- Click the Magnet menubar icon

*Observed behaviour:* :eyes: :broken_heart:
- Note that Spacemacs does not respond to commands or snapping
- Note that "Ignore Spacemacs" is not checked in the menubar menu
- Note that the menu items for controlling window snapping are all disabled

*Expected behaviour:* :heart: :smile:
- Spacemacs should responds to window management tool commands

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git markdown org osx
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      scheme syntax-checking version-control)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by nixmaniack** [comment]
Is this the same behaviour with vanilla emacs?

**Comment by carlodicelico** [comment]
Ah, it is. Thanks.

**Comment by pascalpoizat** [comment]
Hello @carlodicelico , did you found a solution to this issue?

**Comment by AlexZurek** [comment]
@pascalpoizat I realize that it's been quite some time since you asked that question. Unfortunately, I haven't been able to get this to work with Magnet, but [Spectacle](https://www.spectacleapp.com/) seems to work with Spacemacs as expected. I hope this helps!

**Comment by pascalpoizat** [comment]
Thanks @AlexZurek. It works fine (just a behaviour a bit different wrt the left/right moves that do not seem to go from a display to another one but it is perfect wrt Spacemacs).
