### ISSUE TITLE
Give proper error in case of empty $(SHELL) variable

### ISSUE THREAD

**Issue by dfordivam** [syl20bnr/spacemacs#8719]
I tried to install spacemacs by doing git clone and then running the emacs.
But I am getting this error.

> -Lisp error: (file-error "Searching for program" "Is a directory" "")
  call-process("" nil t nil "-c" "/run/current-system/sw/bin/timeout --help")
  apply(call-process "" nil t nil ("-c" "/run/current-system/sw/bin/timeout --help"))
  process-file("" nil t nil "-c" "/run/current-system/sw/bin/timeout --help")

On NixOS this file is actually a link to the executable.

lrwxrwxrwx 1 root root 70 Jan  1  1970 /run/current-system/sw/bin/timeout -> /nix/store/4d6f8hg5gv20nsbq7b52qzn6bcs4fvlh-coreutils-8.26/bin/timeout

**Comment by dfordivam** [comment]
Figured out the issue. The $(SHELL) variable was empty, and this error is due to not finding the shell command. There should be better error message in such case.

**Comment by bmag** [comment]
If it's reproducible with stock Emacs, then not sure there's much we can do about it on our side. Perhaps report it as a bug to Emacs?

**Comment by bmag** [comment]
I'm going to assume it is reproducible in stock Emacs and this isn't our bug, but if it doesn't reproduce in stock Emacs please let us know and I'll reopen it.

**Comment by dfordivam** [comment]
The emacs opens up fine. It definitely does not throw any error. May be once you start doing some things (like installation of plugin) it might complain.

**Comment by bmag** [comment]
Ok, I'm reopening this issue, but I won't be able to debug this myself. I'm not sure anyone else will be able to debug this, so I encourage you to try and find a solution.
