### ISSUE TITLE
Differences from vim: Jump to end/beginning of sentence

### ISSUE THREAD

**Issue by mathpunk** [syl20bnr/spacemacs#872]
Spacemacs and Evil by default treat the `)` and `(` motions as being about lines. Vim treats them as being about sentences, i.e., they look for periods, question marks, and exclamation marks and take the cursor to the first word character that comes after. It's not such an important difference for code, but the sentence is the fundamental unit of prose. I propose the default behavior of the motion ought to be like vim.

**Comment by syl20bnr** [comment]
This makes sense and could be accepted upstream, you can make a feature request om the official evil repo here: https://bitbucket.org/lyro/evil/issues?status=new&status=open

**Comment by fasddag** [comment]
It could be your config problem. Try adding this to your .emacs:

(global-visual-line-mode 1) ;this is clever word wrap
(setq sentence-end-double-space nil) ;sentence end is one space not two

**Comment by StreakyCobra** [comment]
> Spacemacs and Evil by default treat the ) and ( motions as being about lines.

This seems to be corrected in both `develop` and `master`, so I'm closing this issue. Feel free to open a new issue if you notice any problem :smiley:
