### ISSUE TITLE
Customized face for whitespace-space is ignored on startup

### ISSUE THREAD

**Issue by lnrdgmz** [syl20bnr/spacemacs#8721]
#### Description :octocat:
Customized face for whitespace-space is ignored on startup

#### Reproduction guide :beetle:
- Start Emacs
- Add a hook inside dotspacemacs/user-config to enable whitespace-mode.

    (defun dotspacemacs/user-config ()
      "Configuration function for user code. ..."
      (add-hook 'prog-mode-hook 'whitespace-mode)
      )

- Change the color of `whitespace-space` with `customize-face`.
- Confirm change in .spacemacs.

    (custom-set-faces
    ;; custom-set-faces was added by Custom. ...
    '(whitespace-space ((t (:foreground "white")))))

- Restart Spacemacs. 

*Observed behaviour:* :eyes: :broken_heart:
Whitespace-space characters will be their original color.

*Expected behaviour:* :heart: :smile:
Whitespace-space characters should be set to the custom color.

The expected behavior will briefly be observed if `dotspacemacs/sync-configuration-layers` is invoked, but the the characters will return to their default color once the sync is complete. I was able to acheive the expected behavior by commenting out the following code from ~/.emacs.d/layers/+distributions/spacemacs-base/packages.el:

    (progn
      (set-face-attribute 'whitespace-space nil
                          :background nil
                          :foreground (face-attribute 'font-lock-warning-face
                                                      :foreground))

... but I'm not sure if that is a proper solution.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XWIDGETS

**Comment by CeleritasCelery** [comment]
have you tried putting
```
  (set-face-attribute 'whitespace-space nil
                      :background nil
                      :foreground "white")
```
in your `dotspacemacs/user-config`?
