### ISSUE TITLE
Sign commits for added security

### ISSUE THREAD

**Issue by sptankard** [syl20bnr/spacemacs#8722]
Please consider signing your git commits for added security. This will allow people to verify code integrity upon download. 

You can configure git to sign all commits by default. This is a very easy "set it and leave it" solution that provides notable benefit. [GitHub provides a howto.](https://help.github.com/articles/signing-commits-using-gpg/) Why is this a good idea? [This, among other reasons.](https://mikegerwitz.com/papers/git-horror-story.html)

Here is an example of a repo where most contributors sign their commits: 
https://github.com/QubesOS/qubes-core-admin/commits/master

You may also wish to sign tags/releases with an offline key. This provides more security than online-key auto-signing every commit, but is also more hassle (more manual work). I'd sleep easier with just automatic online-key signing configured for now ;)

Here is an example use-case for how downloaders might verify your code before running:
https://github.com/mail-in-a-box/mailinabox/blob/master/README.md#installation

This touches tangentially on https://github.com/syl20bnr/spacemacs/issues/7006
(The Emacs/MELPA packaging infrastructure is horribly broken with respect to security, and so even verified spacemacs code will in turn have to download and execute unverified packages. But verified spacemacs code would be a step in the right direction.)

**Comment by robbyoconnor** [comment]
Why did you open an issue here? You just added to the noise....
