### ISSUE TITLE
#+STARTUP: noindent is ignored

### ISSUE THREAD

**Issue by pmiddend** [syl20bnr/spacemacs#873]
I tried disabling org-indent-mode via #+STARTUP: noindent at the top of an org file, e.g.:

    #+STARTUP:noindent
    * foo
    ** bar
    - baz

But it is simply ignored, apparently.

**Comment by d12frosted** [comment]
Is this still a problem?

**Comment by TheBB** [comment]
I can't reproduce, at least.

**Comment by d12frosted** [comment]
The same. Tried with different setups. So waiting for more input from @pmiddend

**Comment by pmiddend** [comment]
Cannot reproduce anymore, so I'm closing it.
