### ISSUE TITLE
test doc URLs

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#8735]
We probably can make https://github.com/syl20bnr/spacemacs/blob/develop/tests/doc/org-export-ftest.el#L60 work with Travis if we replace [`url-retrieve-synchronously`](https://github.com/syl20bnr/spacemacs/blob/develop/tests/doc/org-export-ftest.el#L86) with something like `curl -s -I -X POST <LINK>`  source http://stackoverflow.com/a/38679650/1224362 and run a bunch of them concurrently.  Alternatively we can simply dump URLs to a file and then run `curl -s -I -X POST <LINK>`  with bash and log errors (404 etc) to a file.  Also we probably do not need to test all the links. But only those in git diff from commit (similar to [`space-test`](https://github.com/syl20bnr/spacemacs/blob/develop/.travis-build.sh#L34)) + mb  test some extra random links each time to to keep Spacemacs healthy.

@deb0ch  :roll_eyes:

**Comment by JAremko** [comment]
Also we probably we'll be better of with timeouts https://unix.stackexchange.com/a/94612/145842

**Comment by JAremko** [comment]
I'm not sure that we need Emacs for this. a bunch of bash scripts should do.

**Comment by deb0ch** [comment]
Huh ?

**Comment by JAremko** [comment]
@deb0ch  I was thinking that you contributed URL tests? Hmmm

**Comment by JAremko** [comment]
Ah it was @smile13241324

**Comment by deb0ch** [comment]
:laughing:

**Comment by JAremko** [comment]
I think checking links in only updated files isn't sufficient because moving/renaming files can also break links to the files. But if we combine it with a full URL test for develop.spacemacs.org repo it will be ok. Also we need a way to make ` spacemacs/publish-doc` silent because it spams a log too much.
