### ISSUE TITLE
`split-window-{right,below}` should select the new window (RFC?)

### ISSUE THREAD

**Issue by jody-frankowski** [syl20bnr/spacemacs#8738]
When I use the `split-window-{right,below}` functions, I want to work on a new file in the new window. However as of today spacemacs doesn't select the new window. I know it's still possible to use the current window to open the new file, but I find it *counterintuitive*.
What is your opinion on this?

**Comment by ngoonee** [comment]
Well, the current behaviour is, at the very least, expected. Vim does it that way out-of-the-box, and plenty of spacemacs users are formerly from vim and would expect that.

Besides that, I don't always want to work on the file in the new window (depends on context really).

**Comment by dubnde** [comment]
You may want to look at `split-window-{right,below}-and-focus`.

`SPC w V` or `SPC w S` provide the behaviour.

**Comment by jody-frankowski** [comment]
Fair enough. I hadn't seen `SPC w V` and `SPC w S`. I'll just rebind them.
Thank you @ngoonee @dubnde
