### ISSUE TITLE
Bibtex layer: insert citation just opens bibtex file

### ISSUE THREAD

**Issue by mlinchitstest** [syl20bnr/spacemacs#8745]
`C-c-]` Just opens a full screen selector of entries. Selecting an entry using `RET` just brings up the bibtex file. It doesn't actually insert any citation. The `M-m-m-i-c` action does the same thing. Is this the right behavior? If so, how do you actually insert citations?

**Comment by JP-Ellis** [comment]
Thanks for the bug report :) This is a duplicate of #8739.
