### ISSUE TITLE
Evil paste `p` with register is broken

### ISSUE THREAD

**Issue by liaowang11** [syl20bnr/spacemacs#8759]
#### Description :octocat:
Evil paste `p` with register is broken

#### Reproduction guide :beetle:
- Start Emacs
- Input `aaa` and yank with `"ayy`
- Input `bbb` and yank with `"byy`
- Paste with `"ap`

*Observed behaviour:* :eyes: :broken_heart:
bbb

*Expected behaviour:* :heart: :smile:
aaa

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. f974b4c9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(personal ivy themes-megapack
          (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip nil auto-completion-enable-sort-by-usage t)
          better-defaults emacs-lisp spacemacs-purpose
          (colors :variables colors-enable-nyan-cat-progress-bar nil)
          (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
          github ibuffer
          org
          (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/zsh" shell-enable-smart-eshell nil)
          (syntax-checking :variables syntax-checking-enable-by-default t)
          (spell-checking :variables spell-checking-enable-by-default nil)
          (vinegar :variables vinegar-reuse-dired-buffer t)
          (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
          (chinese :variables chinese-enable-youdao-dict t chinese-enable-fcitx t)
          evil-cleverparens xkcd emoji
          (clojure :variables clojure-enable-fancify-symbols t)
          nlinum yaml haskell html java javascript go react typescript purescript
          (markdown :variables markdown-live-preview-engine 'vmd)
          (python :variables python-enable-yapf-format-on-save t)
          (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rvm ruby-test-runner 'rspec)
          rust sql lua
          (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t)
          vimscript c-c  
          (semantic :disabled-for emacs-lisp)
          shell-scripts dash imenu-list command-log systemd pdf-tools plantuml search-engine erc csv restclient twitter
          elfeed
          (ranger :variables ranger-show-preview t)
          prodigy
          (gtags :variables gtags-enable-by-default nil)
          spacemacs-layouts
          (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by duianto** [comment]
Confirmed, pasting from registers doesn't work. It seems like the last item on the kill ring always gets pasted.

This functionality might have been lost as a consequence of this PR:
[evil-mc] Disable paste transient state when multiple cursors are active #8620

`p` calls `spacemacs/evil-mc-paste-after`, which calls `evil-paste-after`.
When i bind `p` to `evil-paste-after`:
`(define-key evil-normal-state-map "p" 'evil-paste-after)`
then pasting from registers starts working again.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. f974b4c9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown html ranger emacs-lisp git github helm org version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by liaowang11** [comment]
``` elisp
(defun spacemacs/evil-mc-paste-after (&optional count register)
  "Disable paste transient state if there is more that 1 cursor."
  (interactive "p")
  (if (spacemacs//paste-transient-state-p)
      (spacemacs/paste-transient-state/evil-paste-after)
    (evil-paste-after count register)))
```
did not pass `evil-this-register` to `evil-paste-after`, causing the issue.

**Comment by duianto** [comment]
I don't know if this is the "correct" solution but it starts working when the the last line is changed to:
`(evil-paste-after count evil-this-register)))`
