### ISSUE TITLE
Sync recentf between Spacemacs instances?

### ISSUE THREAD

**Issue by fmthoma** [syl20bnr/spacemacs#8763]
When using two instances of Spacemacs, the `recentf` are written by the instance that exits last, overwriting the `recentf` saved by the previous instance. This way, half of the files I open are missing from `recentf`.

It appears there exists a package ([`sync-recentf`](https://github.com/ffevotte/sync-recentf)) to solve this, would it be feasible to use this package in Spacemacs to synchronize the `recentf` between instances?

**Comment by Stebalien** [comment]
I strongly recommend you use a daemon with multiple frames instead of multiple instances of spacemacs. For one, this will save you a *lot* of RAM.

**Comment by fmthoma** [comment]
@Stebalien Yes, I'd like to do that. However, for almost all themes, the colors in the terminal are broken (see #1269). Hence I use different themes in the terminal (for quickly editing a file from the command line, so I use the daemon here) and in a persistent instance of Spacemacs (IDE-style). Can't use the daemon for both, though, because the theme then will apply to all windows, terminal or not.

So yes, in my case this problem is caused by a very particular workflow to work around a totally different problem, and I'd be better off to solve the underlying problem. OTOH, this feature would still be nice to have.

**Comment by patata3000** [comment]
I've got a problem using one instance of spacemacs with several frames. I can only have one neotree instance over all the frames...
