### ISSUE TITLE
Unable to navigate spacemacs panes when spacemacs opened inside tmux

### ISSUE THREAD

**Issue by jamesla** [syl20bnr/spacemacs#8769]
#### Description :octocat:
Unable to navigate in tmux

#### Reproduction guide :beetle:
- Start tmux
- Start Emacs and project tree
- C-j / C-l

*Observed behaviour:* :eyes: :broken_heart:
Does not navigate between 

*Expected behaviour:* :heart: :smile:
Should navigate between panes

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(lua shell-scripts haskell vimscript ansible ruby ansible vagrant yaml auto-completion emacs-lisp git markdown osx docker tmux spell-checking html markdown javascript syntax-checking version-control)
```

**Comment by CeleritasCelery** [comment]
have you enabled this functionality in tmux with 
```
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)n?vim(diff)?$|emacs.*$' && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)n?vim(diff)?$|emacs.*$' && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)n?vim(diff)?$|emacs.*$' && tmux send-keys C-l) || tmux select-pane -R"
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)n?vim(diff)?$|emacs.*$' && tmux send-keys C-h) || tmux select-pane -L"
```
in your tmux.conf?

**Comment by jamesla** [comment]
Nope that fixed it - thanks!
