### ISSUE TITLE
SPC b d for "kill-this-buffer"

### ISSUE THREAD

**Issue by triklsbg** [syl20bnr/spacemacs#8771]
is not mnemonic or consistent. The "k" (which would stand for "kill") is not bound in this scope or spacemacs/kill-this-buffer can be renamed to ...delete-this-buffer; breaking with the kill-xxx emacs tradition. I would prefer "d" for "delete".
Thanks

**Comment by nixmaniack** [comment]
`SPC b d` is an agreed upon mnemonic for **`delete`** `buffer`. Check https://github.com/syl20bnr/spacemacs/issues/5031 for more details.

Since the function is a custom function and not emacs native - we can rename it to `spacemacs/delete-this-buffer` to make it consistent in the UI.

**Comment by triklsbg** [comment]
Whatever is chosen, I'd like to see a matching letter in the following command name which is displayed by the marvellous which-key. For me the which-key display is the first address and opportunity to burn the key-sequence and an assoziated name in my brain.
![smacs_buffer_ops_screenshot_20170423_102121](https://cloud.githubusercontent.com/assets/3647083/25312183/16a49fa4-2813-11e7-9655-13bd8e18ed81.png)

I knew there are min 3 groups of people with more or less settled assoziations aka muscle-memory
- former emacs user
- former vim user
- and spacesmacs beginners the ever minority and future majority
trying to find a compromise to please them all.

**Comment by robbyoconnor** [comment]
Yeah -- that's possible -- the keybinding should remain the same -- but rename the functions.

**Comment by triklsbg** [comment]
Putting this code in the dotspacemacs/user-config is a workaround for me.
  ```elisp 
  (defalias 'delete-this-buffer 'spacemacs/kill-this-buffer)
  (spacemacs/set-leader-keys "bd" 'delete-this-buffer)
 ````
Thanks
