### ISSUE TITLE
Always auto delete the packages i installed

### ISSUE THREAD

**Issue by vritxii** [syl20bnr/spacemacs#8776]
When I installed the packages, Before i close spacemacs i can use the plugin, but after i restart the emacs, they would be deleted...like this
Found 1 orphan package(s) to delete...
--> deleting company... [1/1]
Symbol's function definition is void: elpy-enable

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

**Comment by nixmaniack** [comment]
Check http://develop.spacemacs.org/doc/FAQ.html#why-are-packages-installed-with-package-install-automatically-deleted-by-spacemacs-when-it-boots.
