### ISSUE TITLE
goimports can't download

### ISSUE THREAD

**Issue by firemiles** [syl20bnr/spacemacs#8778]
```sh
go get -u -v golang.org/x/tools/cmd/goimports
```

goimports repo can't be downloaded from golang.org. Could you change README like downside.

```sh
go get -u -v github.com/golang/tools/cmd/goimports
```

**Comment by robbyoconnor** [comment]
You can...

**Comment by Miciah** [comment]
Since #8780 / https://github.com/syl20bnr/spacemacs/commit/b8c17cf3c574e615e4fe187c3053dec670ff12c2 has been merged, can we close this issue or label it as "Fixed in develop"?

**Comment by robbyoconnor** [comment]
@Miciah great work you're doing to help us triage things :)
