### ISSUE TITLE
How to use ediff as default merge tool?

### ISSUE THREAD

**Issue by jamesla** [syl20bnr/spacemacs#8779]
I really like the spacemacs version of ediff that is loaded when you use SPC-f e D.

How can I launch this normally so I can set it as my default git merge tool?

**Comment by CeleritasCelery** [comment]
include the `version-control` layer and use `magit-ediff-resolve`

**Comment by jamesla** [comment]
How could I magit-ediff-resolve from the shell? (with the ultimate intention of putting it in my .gitconfig as my merge tool)

**Comment by CeleritasCelery** [comment]
That not really how the magit workflow is designed to work. You can do everything from within Emacs.

**Comment by CeleritasCelery** [comment]
http://stackoverflow.com/questions/1817370/using-ediff-as-git-mergetool
