### ISSUE TITLE
semantic mode function description hides flycheck messages for c-c++ layer

### ISSUE THREAD

**Issue by mijoharas** [syl20bnr/spacemacs#878]
If you are working in a c++ file, semantic-mode puts some information on what is under the point in the minibuffer. This is good, but it hides output from flycheck (where it actually tells you what the syntax error is). I'm not sure how we should go about fixing this. Any ideas? is there somewhere else where output could be written? can we display both pieces of information at once? or make flycheck take precedence (as the information is more useful)?

**Comment by tuhdo** [comment]
We can use flycheck-postip and so the error message in a tooltip or open a flycheck buffer that lists all error.

**Comment by tuhdo** [comment]
You can use the command flycheck-list-error (bound to "C-c ! l" to open the list and as you move to the next error, the corresponding error in the list is highlighted.

**Comment by mijoharas** [comment]
Ahh, that seems handy. We should bind that and some other things to leader keys, both for greater visibility and so that they're easier to type.

**Comment by syl20bnr** [comment]
@mijoharas should be available on `SPC e l` but it will be moved to `SPC e f l` soon, I have to split `flycheck` and plain `emacs` errors functions.

**Comment by syl20bnr** [comment]
I'll make a pass on the ergonomy for Flycheck, there is some work to do.

**Comment by tuhdo** [comment]
I think we can remove `spacemacs-next/previous-error` since `flycheck` already took care of it. See [Navigating and jumping to errors](https://flycheck.readthedocs.org/en/latest/guide/usage.html#navigating-and-jumping-to-errors). Just bind `SPC e n` and `SPC e p` when `flycheck` is activated and we can solve the navigation problem in the other issue.
