### ISSUE TITLE
How do I configure YAML linting?

### ISSUE THREAD

**Issue by jamesla** [syl20bnr/spacemacs#8781]
YAML lint not working, I have just added the yaml layer to my config file - Am I supposed to install anything else like fly check or a specific yaml linter?

#### Reproduction guide :beetle:
- Start Emacs with badly formatted YAML file
- SPC j = 

*Observed behaviour:* :eyes: :broken_heart:
nothing

*Expected behaviour:* :heart: :smile:
Should report that YAML file error

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(lua shell-scripts haskell vimscript ansible ruby ansible vagrant yaml auto-completion emacs-lisp git markdown osx docker tmux spell-checking html markdown javascript syntax-checking version-control)
```

**Comment by nixmaniack** [comment]
As per the [documentation](http://develop.spacemacs.org/layers/+lang/yaml/README.html#syntax-checking-with-flycheck) - you'll need to install either `yaml-jsyaml` or `yaml-ruby`.

**Comment by jamesla** [comment]
Have installed the latest version of yaml-jsyaml and space macs is throwing the  occasional error asking me to update etc

I thought I would try with yaml-ruby however I can't seem to find where to get that? It doesn't appear to be in gem, apt, npm and there is no GitHub project with that name. The fly check documentation doesn't seem to link to it either. 

Any ideas which project it is referring to and where I could find it?

**Comment by nixmaniack** [comment]
`yaml-ruby` means it would parse the yaml file with ruby's built-in parser - so if you have ruby installed it should pick up automatically. Currently I'm my checker is `yaml-ruby` only. 

What errors are you getting with `yaml-jsyaml`? If you can describe - maybe someone could help.

**Comment by rski** [comment]
@jamesla  this sounds like flycheck complains about yaml-jsyaml for some reason. To get help you should probably open an issue on flycheck if there isn't one already and provide the full error that you are getting.

**Comment by jamesla** [comment]
Sorry about delayed response - when I install js-yaml from npm this works. Thanks guys.
