### ISSUE TITLE
[Git] magit-stash-drop should be bind to `d` instead of `k`

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#8782]
And `git-rebase-reword` should be bind to <kbd>w</kbd> instead of <kbd>r</kbd> (as `magit-commit-reword` is bind to <kbd>c</kbd><kbd>w</kbd>).

**Comment by nixmaniack** [comment]
`k` looks like default magit binding which isn't modified if it's emacs state. 
In case of `evil/hybrid` states - the magit bindings are managed by `evil-magit` or `evilified`. 
For `evil-magit` it was decided as per the discussion at https://github.com/emacs-evil/evil-magit/pull/2.

Could you elaborate your reasoning?

**Comment by xged** [comment]
https://github.com/syl20bnr/spacemacs/issues/2174
Now in interactive rebase: `# d  drop = remove commit`
