### ISSUE TITLE
add(maybe?) nameless-mode

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#8783]
https://github.com/Malabarba/Nameless

Do we need it? Do we even want it?

**Comment by LdBeth** [comment]
I think that might confuse some starters when navigating the source code. And most people would never use it for writing configurations.
Though it will be a good standard if nameless-mode can be buildin to Emacs.

**Comment by syl20bnr** [comment]
I prefer explicit and expected elisp code for Spacemacs.
