### ISSUE TITLE
spacemacs is very slow when open a large project

### ISSUE THREAD

**Issue by yejunsun** [syl20bnr/spacemacs#8786]
#### Description
Press [SPC p p] to find a project, then open it. It takes about 15s to open it.
There are 875 files, include files in subdirectory , in the project.
It's a maven project.

#### Reproduction guide
- Start Emacs
- Press [SPC p p] to find a project, open a large project.

*Observed behaviour:*
It took too long time to open a large project.

*Expected behaviour:*
Open a large project fast.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(javascript helm auto-completion better-defaults emacs-lisp git markdown org
            (shell :variables shell-default-term-shell "/bin/zsh" shell-default-position 'bottom shell-default-height 30)
            spell-checking syntax-checking version-control)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by CeleritasCelery** [comment]
You should enable caching so that it is only slow the first time `(setq projectile-enable-caching t)`. All subsequent calls will be much quicker.
