### ISSUE TITLE
'No useful browser' when trying to use fymd on MacOS

### ISSUE THREAD

**Issue by joaquinlpereyra-ml** [syl20bnr/spacemacs#8789]
#### Description :octocat:
'No useful browser' when trying to use fymd on MacOS

#### Reproduction guide :beetle:
- Start Emacs on MacOs
- Set up 'chrome' layer and 'markdown' layer
- Try to use flymd when on a markdown file

*Observed behaviour:* :eyes: :broken_heart:
No useful broswer displayed, even when I set up an alias on .zprofile to point 'google-chrome-stable' to the specific binary on mac os.

*Expected behaviour:* :heart: :smile:
A real-time preview of the markdown would open with support for Github flavored markdown :)

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html python helm java auto-completion osx emacs-lisp git
      (markdown :variables markdown-live-preview-engine 'vmd)
      org chrome spell-checking syntax-checking)
```
- System configuration features: JPEG NOTIFY ACL LIBXML2 TOOLKIT_SCROLL_BARS NS

**Comment by JAremko** [comment]
Hmm might be a bug @syl20bnr  [`my-flymd-browser-function`](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Btools/chrome/packages.el#L43) probably needs MacOs option. :thinking:

**Comment by vv111y** [comment]
Same here

**Comment by JAremko** [comment]
@vv111y  can you plz `SPC` `h` `I` here ?

**Comment by youqad** [comment]
Same here :-( 

@JAremko Here is mine:

#### Description :octocat:
'No useful browser' when trying to use fymd on MacOS

#### Reproduction guide :beetle:
- Start Emacs
- Set up 'chrome' layer and 'markdown' layer
- Try to use flymd (`SPC a F`) on a markdown file

*Observed behaviour:* :eyes: :broken_heart:
Error : "No useful broswer displayed", and nothing shows up :-( (even though I have chrome and chromium installed (with homebrew))

*Expected behaviour:* :heart: :smile:
A real-time preview of the markdown file should open in Chrome/Chromium :-)

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python ocaml haskell agda html helm auto-completion better-defaults emacs-lisp git
        (markdown :variables markdown-live-preview-engine 'vmd)
        (spell-checking :variables spell-checking-enable-auto-dictionary t spell-checking-enable-by-default t enable-flyspell-auto-completion t)
        (syntax-checking :variables syntax-checking-enable-tooltips t syntax-checking-enable-by-default t)
        coq javascript
        (osx :variables osx-use-option-as-meta nil)
        c-c++ themes-megapack latex graphviz csv ipython-notebook version-control
        (colors :variables colors-colorize-identifiers 'all colors-enable-nyan-cat-progress-bar nil)
        xkcd bibtex deft pandoc chrome)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by vv111y** [comment]
#9183 
Sorry @JAremko ! I knew there was a response to do and I couldn't find it, this got lost. 
Above is my report, I can just paste contents here if you want (thanks @youqad for responding).

**Comment by longlinht** [comment]
#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults c-c++ gtags cscope python java emacs-lisp git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking version-control html javascript chrome)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

I also face same problem!

**Comment by tripplilley** [comment]
As a workaround, in your spacemacs layers config, you can set the `chrome-exec-path` layer variable:

``` emacs-lisp
(chrome :variables chrome-exec-path "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome")
```

(assuming you're using a standard install of Google Chrome)

**Comment by longlinht** [comment]
@tripplilley , thank you,  it works.

**Comment by swapnilsm** [comment]
+1

**Comment by akumria** [comment]
I think having flymd as part of chrome is the real problem here; it is really related to Markdown.

Ideally flymd would be part of the markdown layer, and on MacOS it would default to calling the function `browse-url-default-macosx-browser` which seems to do the right thing.

**Comment by akumria** [comment]
No, I tell a lie. Because the file is on the local filesystem, `browse-url-default-macosx-browser` does not work.
