### ISSUE TITLE
In Elixir mode, writing quotes in a string sigil escapes the quotes.

### ISSUE THREAD

**Issue by fabrik42** [syl20bnr/spacemacs#8791]
#### Description :octocat:

In Elixir mode, writing quotes in a string sigil escapes the quotes.

#### Reproduction guide :beetle:
- Start Emacs
- Open .ex(s) file
- Write `~s()`
- Write `"` within parentheses

*Observed behaviour:* :eyes: :broken_heart:
Two doublequotes are inserted, but both escaped with a backslash, resulting in `~s(\"\")`

*Expected behaviour:* :heart: :smile:
Two doublequotes are inserted, not escaped at all, resulting in `~s("")`.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :disabled-for markdown)
 deft elixir emacs-lisp emoji erlang git github go helm html javascript react restclient sql yaml
 (ruby :variables ruby-version-manager 'rvm ruby-test-runner 'rspec)
 (markdown :variables markdown-live-preview-engine 'vmd)
 (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
 osx org typescript)
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by hoosierEE** [comment]
I noticed a similar behavior in c-mode.  Typing one single quote (i.e. `'`) results in the following text: `\'\'`, with the cursor placed after the first quote.

**Comment by innerout** [comment]
I am not a spacemacs user but the reason this is happening is due to smartparens-mode probably.

**Comment by hoosierEE** [comment]
I think you're right. Temporarily disabling smart parens fixes it for me. 

-----Original Message-----
