### ISSUE TITLE
Ipython interpreter warning - doesnt support readline

### ISSUE THREAD

**Issue by sho-87** [syl20bnr/spacemacs#8797]
When I try to open ipython (`SPC m s i`) my frame splits with a working ipython on the right, and a new window on the left containing a warning:

`Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support readline, yet ‘python-shell-completion-native’ was t and "ipython" is not part of the ‘python-shell-completion-native-disabled-interpreters’ list.  Native completions have been disabled locally. 
`

I've tried setting `python-shell-completion-native` to `nil` in my spacemacs config but I still get the same warning. I'm not sure what this warning is referring to and while ipython appears to work, these window splits replace my python buffer and its annoying to have to switch back to it due to how these new windows appear

OS: Windows 10
Emacs: 25.1.1
Spacemacs: 0.200.9
config file: https://github.com/sho-87/dotfiles/blob/master/spacemacs/.spacemacs

**Comment by swaroopch** [comment]
This is an upstream issue - https://github.com/jorgenschaefer/elpy/issues/887

**Comment by sho-87** [comment]
got it. Also realized that I was setting the wrong variable to nil. It should be  `(setq python-shell-completion-native-enable nil)`
