### ISSUE TITLE
Ipython inline plotting

### ISSUE THREAD

**Issue by sho-87** [syl20bnr/spacemacs#8798]
I have some python scripts that contain a number of plots. When I open the interpreter (`SPC m s i`) and send my buffer over (`SPC m s b`), ipython hangs and doesn't show any plots

After some digging, I realized that I need to add `(setq python-shell-interpreter-args "-pylab")` to my config

Now plots show in new popup windows. Is there a way to show inline plots inside ipython? This works when running ipython from a terminal but for some reason opens up new windows when I try it in spacemacs

OS: Windows 10
Python: 3.5
Emacs: 25.1.1

**Comment by sho-87** [comment]
I've also tried settings the args to `--matplotlib=inline` but I keep getting the popup window for my plots

**Comment by ragloo** [comment]
I thinks this is the expected behavior. Try the same script in a ipython launched from your os terminal (xterm, konsole, ...) it should be the same. I may be wrong bu to my knowledge inline plotting only works in ipython-console, jupyter-console and jupyter-notebook
