### ISSUE TITLE
Perl 5 (Not Perl 6) Layer

### ISSUE THREAD

**Issue by CeleritasCelery** [syl20bnr/spacemacs#8804]
I originally opened #7758, but is was mistakenly assumed to be a duplicate of #5019 which is for Perl 6. Perl 5 and Perl 6 are two different languages. So don't erroneously close this one. I am opening this issue so that those interested in a Perl 5 layer can input what they would like included. #8572 is an attempt at Perl 5 layer but is too messy to be merged in its current state. 

Some of the packages that I would like to include would be 
[PLSense](https://github.com/aki2o/emacs-plsense) - auto-completion
[dumb jump](https://github.com/jacktasia/dumb-jump) - jump to definition
[perl-flycheck](http://www.flycheck.org/en/latest/) - linting and syntax checking
[helm perldoc](https://github.com/syohex/emacs-helm-perldoc) - perldoc browsing
[Perlnow](https://github.com/doomvox/perlnow) - improved perl debugger
[PDE](https://github.com/wenbinye/emacs-pde) - useful perl utilities 

We could also include a fix for #480 

Once we have an idea of what we want, I can put together a PR. Hopeful once #8686 is resolved it can actually get merged.

**Comment by vibrys** [comment]
I'm missing perl5 layer.
Looks like the progress on this one has been stopped for a while.

Could You please suggest any other perl5 usable layer that could be checkout as private one for a while?

**Comment by CeleritasCelery** [comment]
I have a PR open for it @vibrys

**Comment by TheBB** [comment]
Ay, sorry about closing that PR earlier. I must have had a serious brain fart.

**Comment by vibrys** [comment]
@CeleritasCelery, this is great news! I just saw TheBB approved the changes, although these still didn't land into develop branch.

**Comment by bersace** [comment]
Nice addition ! Can't wait for next release :D

**Comment by CeleritasCelery** [comment]
Also for this interested, I have created a company backend for perl5 based the plsense server. You can find it [here](https://github.com/CeleritasCelery/company-plsense). I am going to also create a Spacemacs PR to add it to this layer.
