### ISSUE TITLE
Question: How to un-evilify a mode? 

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#8805]
I wanted to un-evilify `edebug-mode`. I'm basically looking for a function which will undo whatever `evilified-state-evilify` does. Is it possible?

**Comment by braham-snyder** [comment]
@nixmaniack this isn't about <kbd>escape</kbd> remaining bound to `evil-evilified-state` in the edebugged buffer after `edebug-mode` has been exited, is it?

**Comment by braham-snyder** [comment]
Oh--didn't realize there were more symptoms (to the issue I'm talking about, at least): `i` from `visual-state` becoming `evil-insert`, and surely more.

I'd thought this was just a bug in my configuration, but I'm seeing this on a fresh develop install.

**Comment by CeleritasCelery** [comment]
`(add-to-list 'evil-emacs-state-modes 'edebug-mode)`

**Comment by nixmaniack** [comment]
@CeleritasCelery Doesn't seem to work.

**Comment by JAremko** [comment]
@TheBB  is the master of Evil mb he can help :roll_eyes:

**Comment by nertpinx** [comment]
Would it be enough to do `(evil-set-initial-state 'edebug-mode 'emacs)` ?

**Comment by nixmaniack** [comment]
@nertpinx I believe I had tried that along with CeleritasCelery's suggestion. But it didn't work.

**Comment by nertpinx** [comment]
@nixmaniack Sorry to hear that. I had a problem with different mode and the suggestion from @CeleritasCelery didn't work for me because the mode was already in `evil-normal-state-modes` or similar that took precedence and the `evil-set-initial-state` fixed that.
Maybe looking at what `evilified-state-evilify` does and if it's not easy to revert that, then writing an advice for it or disabling it for that mode somehow are the only ideas that I have left.

**Comment by nixmaniack** [comment]
Thanks for the suggestions, @nertpinx. I could use an advice and disable for this particular mode but I think I will need it for more than just one mode. So having a proper spacemacsy solution would be beneficial in the long run.

**Comment by bmag** [comment]
I think @nertpinx's advice would work on a usual evilified mode. However, for `edebug-mode` we use an advice. You can try removing that advice.

```elisp
;; two options to un-evilify a standard evilified mode
(evil-set-initial-state 'edebug-mode 'emacs) ; set mode's state to `emacs' instead of `evilified'
(evil-set-initial-state 'edebug-mode nil) ; set mode's state to the default state (`normal')

;; option to un-evilify edebug-mode
(advice-remove 'edebug-mode 'spacemacs//edebug-mode)
```

**Comment by nixmaniack** [comment]
That's perfect. The advice on `edebug-mode` is what was missing from this equation! Thank you @bmag.

**Comment by bmag** [comment]
Question was answered, so I'm closing the issue.
