### ISSUE TITLE
Various `Wrong type argument: keymapp, nil` errors when using keyboard-layout layer.

### ISSUE THREAD

**Issue by drwebb** [syl20bnr/spacemacs#8806]
#### Description :octocat:
Various `Wrong type argument: keymapp, nil` errors when using
keyboard-layout layer. Example output below. This appears in
many different modes, and is more of an annoyance than anything,
as after the warning the problem seems to go away.

I use markdown as an example in the reproduction guide, but 
it's not necessarily `markdown-mode` specific.

#### Reproduction guide :beetle:
- Start Emacs
Start spacemacs with keyboard-layout layer and markdown layer

I use the 
 (keyboard-layout :variables kl-layout 'colemak)

*Observed behaviour:* :eyes: :broken_heart:
Warnings buffer shows
`Error (use-package): markdown-mode :config: Wrong type argument: keymapp, nil`

Inputting `C-x b` shows a `Wrong type argument: keymapp, nil` in the minibuffer,
but only the first time.

I've also gotten the `(use-package)` warning Error with `git-gutter ` but cannot
reproduce at the moment.

*Expected behaviour:* :heart: :smile:
No error messages

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 177da959)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(clojure auto-completion better-defaults chrome
         (colors :variables colors-enable-nyan-cat-progress-bar t)
         ess git github
         (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "johan-tibell")
         html ipython-notebook ivy javascript
         (keyboard-layout :variables kl-layout 'colemak)
         latex emacs-lisp
         (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
         evil-commentary markdown org osx pandoc
         (python :variables python-test-runner 'pytest)
         (shell :variables shell-default-shell 'multi-term shell-default-term-shell "/usr/local/bin/zsh" shell-default-height 30 shell-default-position 'bottom)
         slack spell-checking syntax-checking themes-megapack twitter
         (version-control :variables version-control-diff-tool 'git-gutter )
         vinegar ycmd yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
See observed behavior
```

**Comment by drwebb** [comment]
The only reference to `keymapp` I get from a GH search on the spacemacs repo is

https://github.com/syl20bnr/spacemacs/blob/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/core/core-micro-state.el#L158

I not sure of the internals of loading a micro-state, but my intuition says that the layer is not expecting the additional arguments that `keyboard-layout` is adding.

**Comment by drwebb** [comment]
This issue with markdown mode is fixed, if I notice in another layer I will reopen again.

**Comment by guraltsev** [comment]
The same problem occurs with layer `shell`.
