### ISSUE TITLE
Q: usepackage and  dotspacemacs-additional-packages

### ISSUE THREAD

**Issue by mlinchitstest** [syl20bnr/spacemacs#8808]
Is it possible or recommended to use both? If so how?

Or do you just put `use-package` in the `user-config`, and leave the package name out of the `dotspacemacs-additional-packages`.

Thanks

**Comment by CeleritasCelery** [comment]
If you have enough additional configuration to justify `use-package` you might as well make a layer out of it. Otherwise `dotspacemacs-additional-packages` is the preferred way to do it.
