### ISSUE TITLE
Error running timer `sp-show--pair-function`

### ISSUE THREAD

**Issue by chenyangguang** [syl20bnr/spacemacs#8809]
When `kill-some-buffers`,  sometimes spacemacs  appear : 

Error running timer 'sp-show--pair-function': (args-out-of-range #("<"  0 1 (fontified t)) 1 2) 
then stop `kill-some-buffers`  continue.

**Comment by CeleritasCelery** [comment]
You will need to give a reproduction guide if you want help with this.
