### ISSUE TITLE
(package-initialize) on startup?

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#881]
Some packages such as `flycheck-pos-tip` and `highlight-numbers` won't be available if we do not run `package-initialize`. I added `package-initialize` and saw no impact on start up time. We should add it otherwise users may not be able to load their packages even after installing from MELPA.

**Comment by syl20bnr** [comment]
Can you be more specific ? `package-intialize` is certainly run otherwise nothing would work.

**Comment by syl20bnr** [comment]
See: https://github.com/syl20bnr/spacemacs/blob/master/core/core-configuration-layer.el#L18-31

**Comment by tuhdo** [comment]
When I add package like `highlight-numbers` and its init function with usual `use-package` and this only init form:

```elisp
(add-hook 'prog-mode-hook 'highlight-numbers-mode)
```

But even after Spacemacs starts, it won't load until I run `package-initialize` to see the mode.

**Comment by syl20bnr** [comment]
I need more information, I just tried it and it works. Maybe you are missing `:defer t` ?

**Comment by tuhdo** [comment]
Yes that's it.

**Comment by syl20bnr** [comment]
By the way PR welcome :-)
We can add it to the Spacemacs layer.

**Comment by syl20bnr** [comment]
By the way PR welcome :-)
We can add it to the Spacemacs layer.
