### ISSUE TITLE
Allow spacemacs not to invert face colors under the cursor

### ISSUE THREAD

**Issue by ice9js** [syl20bnr/spacemacs#8811]
I find colored cursors distracting, so I set the cursor color to slightly lighter than my background.
Unfortunately, it still keeps on inverting the face colors of whatever is beneath the cursor, and I'd like for it not to.

<img width="319" alt="screen shot 2017-04-27 at 10 05 22 am" src="https://cloud.githubusercontent.com/assets/8056203/25474247/cbd619c6-2b32-11e7-8bf7-c1fb7ab369f4.png">

The `f` under the cursor on the image above should still be green.
I tried the following with no success:

```
(set-cursor-color "#555555")
(set-face-attribute 'cursor nil :inverse-video nil)
(set-face-attribute 'cursor nil :foreground 'unspecified)
```

The latter two lines don't seem to have any effect, no matter the value.

**Comment by nixmaniack** [comment]
Have you tried changing somewhat relevant dotspacemacs' variable? 

```elisp
   ;; If non nil the cursor color matches the state color in GUI Emacs.
   dotspacemacs-colorize-cursor-according-to-state t

```

Try setting it to `nil`.

**Comment by ice9js** [comment]
I had `dotspacemacs-colorize-cursor-according-to-state` set to `nil`.

After some more investigation, it seems like the issue lies with GNU Emacs itself, as described [here](https://www.gnu.org/software/emacs/manual/html_node/emacs/Cursor-Display.html):

>To customize its color, change the :background attribute of the face named cursor (see Face Customization). (The other attributes of this face have no effect; the text shown under the cursor is drawn using the frame's background color.)

I thought I read somewhere this didn't affect Emacs for OSX anymore, but it looks like it still does.
