### ISSUE TITLE
Helm causes relative line numbers in horizontal split become "1"

### ISSUE THREAD

**Issue by westlywright** [syl20bnr/spacemacs#8813]
#### Description
Helm causes relative line numbers in horizontal split become "1" with linum-relative when escaping from the search. Could related to syl20bnr/spacemacs#6493

#### Reproduction guide
- Start Emacs
- Enable relative line numbers if you haven't already (dotspacemacs-line-numbers 'relative)
- Open any non-empty buffer in a project
- Split the buffer horizontally (`SPC w S`)
- Open a NEW file in the newly split buffer
- From the buffer, open any helm buffer (SPC f f, SPC b b, SPC :, etc.)
- Escape from the helm buffer using `esc`

*Observed behaviour:*
Line numbers in top most buffer are all 1's

*Expected behavior:*
Line numbers should be displayed correctly

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm yaml vimscript html
        (javascript :variables javascript-disable-tern-port-files nil tern-command
                    '("node" "/Users/arion/.config/yarn/global/node_modules/.bin/tern"))
        (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t :disabled-for org git github)
        emacs-lisp git github markdown docker org theming shell-scripts vim-empty-lines
        (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
        spotify tmux
        (shell :variables shell-default-shell 'multi-term shell-default-term-shell "/bin/zsh" shell-default-heightnil 30 shell-default-position 'bottom)
        (syntax-checking :variables syntax-checking-use-original-bitmaps t)
        (version-control :variables version-control-diff-tool 'git-gutter+ version-control-global-margin t))
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

![spacerelnum](https://cloud.githubusercontent.com/assets/858614/25494782/aa5dc530-2b2f-11e7-9ca9-6f86d3b12ae5.gif)

**Comment by jbhannah** [comment]
I've also experienced this with vertical splits.
