### ISSUE TITLE
:noh doesn't work

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#8817]
@TheBB  Vim's `:noh` seems to stop working :worried:  

It supposed to clear highlights on search matches but I still can see them :thinking:

**Comment by singul0** [comment]
But `SPC s c` works just fine.

**Comment by JAremko** [comment]
@singul0  but I want my `:noh`  :cry:

**Comment by duianto** [comment]
This might be related to or a duplicate of this issue:
ex command :nohlsearch has no effect on evil-search-module highlights #8518

**Comment by JAremko** [comment]
@duianto  Looks like so. I'll close this. Thx
