### ISSUE TITLE
Velocity support for the Dash layer

### ISSUE THREAD

**Issue by crmne** [syl20bnr/spacemacs#8820]
Velocity is a Windows native Dash clone, advertised also by Kapeli (creator of Dash) in his blog. Being native it's faster than Zeal on Windows, which makes it my favourite offline documentation browser.

Would be nice if it could be integrated in the Dash layer of spacemacs!

http://velocity.silverlakesoftware.com/

**Comment by JAremko** [comment]
This should be solved by [dash-at-point](https://github.com/stanaka/dash-at-point/issues/22) or [zeal-at-point](https://github.com/jinzhu/zeal-at-point/issues) devs
You can bump/create corresponding issue there.
