### ISSUE TITLE
evil-paste-pop doesn't work, previous command was not an evil-paste

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#8823]
#### Description :octocat:
Replacing the just pasted text (by pressing `p`) with a previous entry from the kill ring (by pressing `C-p`) doesn't work.

#### Reproduction guide :beetle:
1. Start Emacs
2. Open the `*scratch*` buffer `SPC b s`
3. Type: `two words`
4. Move the cursor to the first character `gg`
5. Yank both words: press `yww` and `yw`
6. Open a newline below: `o`
7. Exit insert state: `Esc`
8. Paste the last yanked text: `p`
9. Try to replace it with a previous item from the kill ring: `C-p`

*Observed behaviour:* :eyes: :broken_heart:
The `*Messages*` buffer shows:
`user-error: Previous command was not an evil-paste: spacemacs/evil-mc-paste-after`

*Expected behaviour:* :heart: :smile:
A previous entry in the kill ring should replace the just pasted text.

#### Possible cause
`evil-paste-pop` (`C-p`) expects that the `last-command` was any of these 3:
```elisp
  (unless (memq last-command
                '(evil-paste-after
                  evil-paste-before
                  evil-visual-paste))
```
https://github.com/emacs-evil/evil/blob/f0684c1f6644a8c4e0e5fce50a1a04796555eaf1/evil-common.el#L2598

But `p` is bound to: `spacemacs/evil-mc-paste-after`. And the same thing applies to: `]p` which is bound to `evil-unimpaired/paste-below`, it shows this message:
`user-error: Previous command was not an evil-paste: evil-unimpaired/paste-below`

#### When it does work
Replacing the last pasted text with `C-p` works, if there was an active selection when the text was pasted with either `p` or `]p`.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 177da959)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey markdown html ranger emacs-lisp git github helm org syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by MHOOO** [comment]
I can confirm this bug happening on the develop branch

**Comment by off99555** [comment]
It is still happening. It is not there before.

**Comment by nochiel** [comment]
@off99555 You might want to try using my [patch](https://github.com/nochiel/spacemacs/commit/288722d4c0d4a7dafd0ebb3a33e4017a2829c2ef).

**Comment by JAremko** [comment]
refer #9073

**Comment by troyp** [comment]
Would redefining `this-command` have any side-effects? Would it be better to just redefine `evil-paste-pop` to update the list of paste commands (it's a shame it's not defined as variable in the first place).

**Comment by Miciah** [comment]
Since #9073 / https://github.com/syl20bnr/spacemacs/commit/eb5e6ed9204d5157935b055f915a931b404c8e34 has been merged, can this issue be labeled as "Fixed in develop"?

**Comment by natusdrew** [comment]
I am on emacs 26.3 with spacemacs. I am running into this issue when I copy something to my clipboard from say... the browser. Then try to Ctrl-p inside of spacemacs. I am using Ubuntu 18 LTS.

**Comment by natusdrew** [comment]
The solution was to use Shift-P instead of Ctrl-p. hahahahahah!
