### ISSUE TITLE
Warning: Cannot find any of the specified fonts (Linux)

### ISSUE THREAD

**Issue by jtruchan** [syl20bnr/spacemacs#8829]
I have seen a few similar issues reported but I could not find a solution. Spacemacs starts with the following warning: `Cannot find any of the specified fonts (Source Code Pro)! Font settings may not be correct.` Source Code Pro font is installed on the system:
```
$ fc-list | grep 'Source Code Pro'
~/.fonts/adobe-fonts/source-code-pro/TTF/SourceCodePro-Light.ttf: Source Code Pro,Source Code Pro Light:style=Light,Regular
~/.fonts/adobe-fonts/source-code-pro/TTF/SourceCodePro-Regular.ttf: Source Code Pro:style=Regular
~/.fonts/adobe-fonts/source-code-pro/TTF/SourceCodePro-Bold.ttf: Source Code Pro:style=Bold
```
My font config:
```
dotspacemacs-default-font '("Source Code Pro"
                               :size 13
                               :weight normal
                               :width normal
                               :powerline-scale 1.1)
```
My OS is OpenMandriva Lx 3.01. Emacs 24.5.1, Spacemacs 0.200.9. How can I make Spacemacs see the font?

**Comment by duianto** [comment]
Did you rebuild the font cache?

I think i only ran the command: `sudo fc-cache`
in ubuntu 16.10, but some suggestions here:

Add font installation instructions for Linux
https://github.com/adobe-fonts/source-code-pro/issues/17

show the command as: `sudo fc-cache -f -v`

**Comment by jtruchan** [comment]
I ran `sudo fc-cache -f -v ~/.fonts/adobe-fonts/source-code-pro` and `sudo fc-cache -f -v /usr/share/fonts/TTF/` but it did not help.

**Comment by duianto** [comment]
I installed OpenMandriva Lx 3.01 in virtual box on windows 10. And I'm getting the same results, Spacemacs can't find the fonts.

These instructions might be useful: 
https://doc.openmandriva.org/OpenMandriva-Lx-2014#add-fonts-special-71

The system updates are taking a while, and I don't want to try it at the same time. But i can try them when the updates are done.

**Comment by duianto** [comment]
I couldn't get it to work by following those instructions either.

This issue:
Can't find Source Code Pro fonts..... https://github.com/syl20bnr/spacemacs/issues/7340
Might have a clue to why it isn't working. There it's suggested that Emacs might not have been built with font support.

The Emacs version I installed was 24.5.1, from the Application Launcher (bottom left button) > Configure Your Computer > Software Management > Install & Remove Software.

The next thing you could try is to compile Emacs with font support.

**Comment by jtruchan** [comment]
I think that the problem is indeed that the OpenMandriva package of Emacs has been built without font support. I followed the same steps on Kubuntu and it worked fine. I will close this issue as it is probably related to the system.

**Comment by costis-t** [comment]
For future net stumblers: Yes, emacs needs to be built with xft " Build with support for XFT font renderer (x11-libs/libXft)" support.
