### ISSUE TITLE
No such file or directory, ocp-indent

### ISSUE THREAD

**Issue by purpleladydragons** [syl20bnr/spacemacs#8832]
#### Description :octocat:
Spacemacs can't find ocp-indent despite it being installed. There's an ocp-indent directory inside my elpa directory, and from the backtrace, the functions in the .el file seem to get called properly.

#### Reproduction guide :beetle:
- Start Emacs
- With the ocaml layer installed, [SPC m =]

*Observed behaviour:* :eyes: :broken_heart:
No such file or directory, ocp-indent 

*Expected behaviour:* :heart: :smile:
Proper indentation

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ocaml helm emacs-lisp)
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (file-error "Searching for program" "No such file or directory" "ocp-indent")
  call-process-region(1 38 "ocp-indent" "/var/folders/vz/q3dgx5jj3y1989n9y7np1h8w0000gn/T/emacsCIYxzp" (#<buffer  *string-output*> "/var/folders/vz/q3dgx5jj3y1989n9y7np1h8w0000gn/T/ocp-indent-error97945Cyf") nil "--numeric" "--lines" "4-4")
  apply(call-process-region 1 38 "ocp-indent" nil (#<buffer  *string-output*> "/var/folders/vz/q3dgx5jj3y1989n9y7np1h8w0000gn/T/ocp-indent-error97945Cyf") nil ("--numeric" "--lines" "4-4"))
  (/= 0 (apply (quote call-process-region) (point-min) (point-max) ocp-indent-path nil (list standard-output errfile) nil (ocp-indent-args start-line end-line)))
  (if (/= 0 (apply (quote call-process-region) (point-min) (point-max) ocp-indent-path nil (list standard-output errfile) nil (ocp-indent-args start-line end-line))) (error "Can't indent: %s returned failure" ocp-indent-path))
  (let ((standard-output standard-output)) (if (/= 0 (apply (quote call
```

**Comment by purpleladydragons** [comment]
I found a temporary workaround by explicitly setting the path of ocp-indent in my .spacemacs config.

**Comment by dudelson** [comment]
I also had this issue, and I found that the root of the problem was that `PATH` in spacemacs was different from my shell's `PATH`. Since spacemacs uses [`exec-path-from-shell`](https://github.com/purcell/exec-path-from-shell), this is not supposed to happen, and I had to change my `exec-path-from-shell` settings per my comment [here](https://github.com/syl20bnr/spacemacs/issues/3920#issuecomment-319559581).  To check whether your two `PATH`s match:

1. From your shell, verify that `echo $PATH` and `env | grep PATH` match and are what you expect.
2. From spacemacs, see if `M-: (getenv "PATH")` and `M-: exec-path` match each other and the `PATH` given by your shell.

**Comment by mfaerevaag** [comment]
Should this issue be reopened? I am also experiencing the same issue. It doesn't really look like it was fixed in the first place.

**Comment by dudelson** [comment]
I think that depends on whether or not the underlying cause is a misconfigured `PATH`, as was the case for me. At this point I'm inclined to think that it isn't a problem with the OCaml layer, but if in your case `PATH` isn't the problem, then I agree it might need to be re-opened.

**Comment by mfaerevaag** [comment]
It seems like my issue was also caused by a misconfigured `PATH`, also fixed by
```lisp
(setq exec-path-from-shell-arguments '("-i"))
```

Maybe an issue describing the `PATH` issue would be better suited.
