### ISSUE TITLE
Disable evil-escape-mode in holy-mode

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#884]
This mode is unneeded for `holy-mode`.

**Comment by tuhdo** [comment]
It should really be disabled because when I start Isearch (`C-s`) with it, pressing `f` and the character `f` is repeatedly inserted into Isearch prompt. `C-h k` and I found out the `f` key is bound to `evil-escape-isearch`.

**Comment by syl20bnr** [comment]
This has been fixed upstream, I guess you don't have the last version of evil-escape.
I'm ok to remove it in holy-mode.

**Comment by tuhdo** [comment]
Right, I had the old version. But it should be removed entirely, so Emacs users won't accidentally enter normal mode.

**Comment by CestDiego** [comment]
I'd appreciate if this would be a toggle default to off. Because I still find it cool   to have full emacs + vim power \*.\* . Also I have a question though. Will Multiple cursors work now in emacs-state? :P

**Comment by syl20bnr** [comment]
@CestDiego It always will be possible to reenable it in your dotfile.
For multiple cursors I don't see any reason why it would not work in emacs state. This is a known trick of evil users: switch to insert state when using multiple cursors.
We could think again about it in #101

**Comment by justbur** [comment]
Evil escape is disabled in holy mode by default now so this can probably be marked fixed in develop.
