### ISSUE TITLE
ESS layer change default replacement of underscore

### ISSUE THREAD

**Issue by jackkamm** [syl20bnr/spacemacs#8841]
By default, the ESS (R) layer automatically replaces underscore `_` with assignment `<-` when underscore is typed (typing the underscore twice gives a true underscore).

I propose to:
1. Add an ESS layer variable to toggle this behavior
2. Disable the automatic replacement by default.

Re: (1), There are instructions in the Readme to on how disable this behavior with a hook, but given how common it is to do it, it should really be a variable in the ESS layer, similar to `ess-enable-smart-equals`. Also, I've found the hook recommended in the Readme to occasionally cause strange behavior; it is more reliable to call `(ess-toggle-underscore nil)` just once in the `use-package` setup.

Re: (2), I think the default behavior should disable the automatic replacement of underscore, it is a relic of an earlier time when `_` was uncommon in R code. However, in modern R code it is ubiquitous. As a result, R users new to emacs typically find the default ESS behaviour confusing and unwieldy.

I'm happy to submit both (1) and (2) as a PR. I actually just submitted (1) as a PR (https://github.com/syl20bnr/spacemacs/pull/8827) but have closed that pending discussion of this issue to add both (1) and (2) together.

References:
https://github.com/syl20bnr/spacemacs/issues/3222
https://github.com/syl20bnr/spacemacs/issues/2373

**Comment by leezu** [comment]
This is not fixed in develop @TheBB. It seems not all commits from https://github.com/syl20bnr/spacemacs/pull/9102 where cherry-picked
