### ISSUE TITLE
how to access mysql and save mysql login information in spacemacs

### ISSUE THREAD

**Issue by csfreebird** [syl20bnr/spacemacs#8843]
I did not find the layer for mysql or other database in spacemacs. 
I want to access mysql in spacemacs without input host login information everytime.

**Comment by robbyoconnor** [comment]
You'd do that via a terminal...

**Comment by robbyoconnor** [comment]
You'd use the [sql layer](http://develop.spacemacs.org/layers/+lang/sql/README.html).

**Comment by robbyoconnor** [comment]
No, you probably shouldn't save your pw anyways.

**Comment by adnan-panalytics** [comment]
I also have the same question. How to save server name, user name, db name (and password if  I choose to, fully understanding why it shouldn't be stored)? I know there is a hook for sql mode, but it requires creating a folder in the .emacs.d directory. 
```
  (defun my-sql-save-history-hook ()
    (let ((lval 'sql-input-ring-file-name)
          (rval 'sql-product))
      (if (symbol-value rval)
          (let ((filename 
                 (concat "~/.emacs.d/sql/"
                         (symbol-name (symbol-value rval))
                         "-history.sql")))
            (set (make-local-variable lval) filename))
        (error
         (format "SQL history will not be saved because %s is nil"
                 (symbol-name rval))))))
 
  (add-hook 'sql-interactive-mode-hook 'my-sql-save-history-hook)
```
But I read that you aren't allowed to create/delete anything from that directory. Is there a workaround/solution to this?

**Comment by adnan-panalytics** [comment]
I found a workaround, can just put it in the sql-product list in the .spacemacs config (which is created by the sql-connect command).
