### ISSUE TITLE
Spacemacs quits without warning sometimes when using helm/ivy

### ISSUE THREAD

**Issue by natfarleydev** [syl20bnr/spacemacs#8844]
#### Description :octocat:
Spacemacs quits without warning randomly when executing an helm/ivy function. Seems to last longer with Ivy (but this could be wrong as bug happens randomly). Happens in graphical and non-graphical mode.

#### Reproduction guide :beetle:
- Start Emacs
- Use emacs for 10 mins to 2 days
- Try to use helm/ivy (often by SPC f f or SPC b b, but not always)
- Spacemacs quits without warning

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs quits without warning when using a helm/ivy function.

*Expected behaviour:* :heart: :smile:
Spacemacs does not quit without warning.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 177da95)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp javascript html python emacs-lisp git markdown org python c-c   yaml latex syntax-checking
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      (c-c   :variables c-c  -default-mode-for-headers 'c  -mode))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XWIDGETS

#### Backtrace :paw_prints:
Would love to figure out how to get this

**Comment by istinspring** [comment]
Segmentation fault?

**Comment by nasfarley88** [comment]
Could be. I get no 'Segmentation violation' or similar after it quits on the terminal, but the behaviour is exactly like a segfault.

How would I test theory?

**Comment by sdwolf** [comment]
See my comment [here](https://github.com/syl20bnr/spacemacs/issues/8833#issuecomment-298289200) on how to intercept segfaults and get a backtrace.

**Comment by sdwolf** [comment]
Yup, this seems to be the problem from #8197. It was fixed on emacs master but not backported. Your best option is to build emacs 26 from source.

Here is how I do it:
```bash
git clone https://github.com/emacs-mirror/emacs.git ~/emacs
cd ~/emacs
./autogen.sh
./autogen.sh git
CFLAGS='-O2 -g3' ./configure --program-transform-name='s/^ctags$/ctags.emacs/'
make
sudo make install
```
You might need to install some missing packages like `gcc`, `texinfo` and `autoconf`

**Comment by istinspring** [comment]
@sdwolf there is brew formula from @d12frosted d12froster/emacs-plus/emacs-plus  is i will install it with --HEAD option it would be similar to emacs master c/d?

**Comment by sdwolf** [comment]
I am not sure because I never used `homebrew` nor `linuxbrew`. But if you do an `emacs --version` after you install it and it prints `GNU Emacs 26.0.50` it means it built from master. Also I don't know how you would check the date of the last commit in that case to be sure you indeed have the fix.

**Comment by istinspring** [comment]
@sdwolf got it, able to get version `26.0.50` using --HEAD flag `brew upgrade d12frosted/emacs-plus/emacs-plus --HEAD`
