### ISSUE TITLE
Org completion: confusion or bug?

### ISSUE THREAD

**Issue by mlinchitstest** [syl20bnr/spacemacs#8846]
Apparently, org-mode uses `M-TAB` to invoke `pcomplete` for completion after things like `#+`. Since `M-TAB` is not usable with modern keyboards and desktop environments, there are supposedly alternative default bindings. People on forums have suggested `ESC TAB`, while `helm describe binds` tells us that `M-TAB` is "translated to" to an awkward `C-M-i`. However neither of these alternatives actually invokes any kind of completion interface on spacemacs — they just make the cursor jump down one line.

I tried `helm pcomplete` and it brought up a pretty hefty buffer with completions. However this buffer is distracting and you have to mouse click on a completion (can't use keyboard). I'd expect the completions to just pop up as you type in a little popup menu, like with company or any normal IDE/text editor. Is `pcomplete` really the preferred way to do completions for tags, properties etc in Org?

**Comment by LdBeth** [comment]
I think you can config your desktop to treat some keys as META, like the Alt key, at least it is not a bug of Spacemacs, because both <kbd>M-TAB<\kbd> and <kbd>C-M-i</kbd> works for me (my platform is macOS). 

CAUTION: <kbd>C-M-i</kbd> stands for <kbd>Control + Meta + i</kbd>, don't mess it up with <kbd>Control + m + i</kbd>, which actually can make the cursor jump down one line.

**Comment by mlinchitstest** [comment]
Oh right Mac has cmd, I've only used Linux and Win, so I had no idea.

So when you press those keys do you get something like this:
![image](https://cloud.githubusercontent.com/assets/19510975/25742764/a788bcc8-3199-11e7-9023-c6dc493ecd93.png)

**Comment by LdBeth** [comment]
This is the default and expected behavior of pcomplete, it seems company do not support pcomplete in Spacemacs right now.

**Comment by LdBeth** [comment]
If you prefer to use `helm` instead of a buffer pop up like the screen capture you've post, you can bind `helm-pcomplete` to some proper keys, like `M-TAB`. 

>However this buffer is distracting and you have to mouse click on a completion (can't use keyboard). 

In `helm`, you can use `C-n` `C-p` to move down and up, or use `C-q` to jump to a selection.

**Comment by Somelauw** [comment]
@mlinchitstest
> However neither of these alternatives actually invokes any kind of completion interface on spacemacs — they just make the cursor jump down one line.

You may have a conflicting binding. By default M-tab is bound to pcomplete, but flycheck also uses this binding. If you don't like (or can't use) M-tab, you can bind it to C-tab of some other key.

> I tried helm pcomplete and it brought up a pretty hefty buffer with completions. However this buffer is distracting and you have to mouse click on a completion (can't use keyboard). I'd expect the completions to just pop up as you type in a little popup menu, like with company or any normal IDE/text editor. Is pcomplete really the preferred way to do completions for tags, properties etc in Org?

You can use it without a mouse by typing some characters and pressing M-tab again.

**Comment by DonHugo69** [comment]
I was struggling with the same "issue" for quite some time and found a solution [here](https://emacs.stackexchange.com/questions/21171/company-mode-completion-for-org-keywords) and [here](https://github.com/company-mode/company-mode/issues/50).
Adding 
```  
(defun add-pcomplete-to-capf ()
    (add-hook 'completion-at-point-functions 'pcomplete-completions-at-point nil t))
    (add-hook 'org-mode-hook #'add-pcomplete-to-capf)
```
to `dotspacemacs/user-config` allows company-mode to take care of the completion after `#+`.
