### ISSUE TITLE
text in middle column in ranger is invisible

### ISSUE THREAD

**Issue by vigilancetech-com** [syl20bnr/spacemacs#8857]
#### Description :octocat:
middle column missing in ranger

#### Reproduction guide :beetle:
- Start Emacs
- hit SPC a r to start ranger

*Observed behaviour:* :eyes: :broken_heart:
text (file names) in the middle column is invisible

*Expected behaviour:* :heart: :smile:
text would be visible

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm ranger auto-completion better-defaults themes-megapack emacs-lisp git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

#### Backtrace :paw_prints:
```

```

![image](https://cloud.githubusercontent.com/assets/20651234/25773576/60ba6058-3234-11e7-9621-69cf4e49ae6e.png)

**Comment by duianto** [comment]
There's an open issue about this in the ranger repository:
Problem under Windows https://github.com/ralesi/ranger.el/issues/156

The first suggested workaround seems to fix it:
`(setq ls-lisp-use-insert-directory-program t)`

It makes the file names visible, and it also solved another issue where folder names with spaces in them, excluded the first word: 
- `Blender Foundation` was shown as `Foundation`
- `Sublime Text 3` was shown as `Text 3`

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. e6927436)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey markdown ranger emacs-lisp git github helm org syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by vigilancetech-com** [comment]
That did it!   Thanks!

**Comment by duianto** [comment]
@vigilancetech-com This issue has been fixed in the ranger.el package. The workaround isn't needed anymore. If it's also working for you, then you can close this issue.
