### ISSUE TITLE
Debug when typing

### ISSUE THREAD

**Issue by 0c70pu5** [syl20bnr/spacemacs#8859]
#### Description :octocat:

Debug when typing

#### Reproduction guide :beetle:

- Start Emacs
- Run Slime (M-x^ slime)
- Typing in repl (ql

*Observed behaviour:* :eyes: :broken_heart:
- spacemacs open debug window
Unknown symbol: ql: [in #<PACKAGE "COMMON-LISP-USER">]
   [Condition of type SIMPLE-ERROR]

*Expected behaviour:* :heart: :smile:
I think that the autocomplete should not throw an exception in the REPL

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.8
- Spacemacs branch: master (rev. bd7ef98e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(javascript html ivy
            (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil)
            common-lisp emacs-lisp git markdown spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by LdBeth** [comment]
Which Common Lisp do you use?
Or, have you loaded quicklisp in your Common Lisp init file?

**Comment by 53c701d** [comment]
SBCL 1.3.15 from here http://www.sbcl.org/platform-table.html
Windows, amd64

**Comment by nivpgir** [comment]
same bug happens to me too, using arch linux, sbcl 1.3.19.
contents of `.sbclrc`:

``` common-lisp
;;; The following lines added by ql:add-to-init-file:
#-quicklisp
(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp"
                                       (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))
```

also, this  doesn't happen if i don't set (autocompletion-enable-tooltip t) in my .spacemacs.
