### ISSUE TITLE
Change buffer-move key bindings for holy-mode

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#886]
Currenlty, it is using Vim key bindings:

```elisp
(defun spacemacs/init-buffer-move ()
  (use-package buffer-move
    :defer t
    :init
    (evil-leader/set-key
      "bmh" 'buf-move-left
      "bmj" 'buf-move-down
      "bmk" 'buf-move-up
      "bml" 'buf-move-right)))
```

It should be switched to something resembles arrow keys. For example, instead of `hjkl`, we can use `jkli` that resembles arrow keys.

**Comment by syl20bnr** [comment]
I won't go so far for the holy-mode by touching the key bindings behind the leader keys.

Tweaking the bindings too much will bring complexity to the documentation, to the convention rules, to the interactions between spacemacs users, and it will hurt the project in the long run. 

The idea of the holy-mode is to be as less intrusive as possible while allowing emacs users to jump in without being lost. I think we are pretty close.

Moreover `jkli` is not even a standard in the pure emacs world so there is very little gain to pay the price above for this. So I consider `jkli` as a personal preference and as such I cannot accept it as default in spacemacs.

I'm more in favor to support regular arrow keys which are not a replacement, they are additional key bindings accessible in the two editing styles.

**Comment by tuhdo** [comment]
Then, we can use the arrow keys. But how about `f`, `b`, `n`, `p`?

**Comment by syl20bnr** [comment]
This is a tough question and I think we cannot do much than supporting arrow-key.

In your example though, we cannot use `f, b, n, p` for buffer moves, `f,b,n,p` is not a full replacement for arrow keys, it means going `forward, backward, next, previous` which don't map well in all cases with arrow keys `up, down, left, right`.

**Comment by tuhdo** [comment]
Alright then, we can use the arrow key. But I still think `jkli` are nice key bindings with no learning curve.; we can reuse the existing 3 keys from Evil and replace one key User should also realize its arrow keys layout instantly.
