### ISSUE TITLE
Some compiling errors

### ISSUE THREAD

**Issue by BowenWang** [syl20bnr/spacemacs#8862]
When I download the configuration, and started to download the packages the first time, information shows up:
Error: Symbol's function definition is void: org-link-type

Packages related to this function all have such error.

**Comment by BowenWang** [comment]
I just reinstall the spacemacs configuration, and took the screenshot. I think it might help.
![emacserror](https://cloud.githubusercontent.com/assets/14265711/25784640/634247fc-3336-11e7-8a05-022e42fc7e19.png)

**Comment by G1enY0ung** [comment]
Maybe this can help you [link](https://emacs.stackexchange.com/questions/29471/error-message-symbols-function-definition-is-void-org-link-types-when-i-open)

**Comment by BowenWang** [comment]
Are you sure it is the same issue here? I have seen the link you gave, but he said that there will be error message when he open an org-file. 
But my emacs didn't output any error messages when I open an org-file.
By the way, my emacs version is 24.4.1

**Comment by G1enY0ung** [comment]
View the question's comments. Just **maybe**, I didn't say it's an exact solution.

**Comment by BowenWang** [comment]
Alright, thanks anyway.
