### ISSUE TITLE
How to make Spacemacs commands like 'previous-buffer', 'next-buffer' not ignore magit buffers?

### ISSUE THREAD

**Issue by tddsg** [syl20bnr/spacemacs#8867]
Hi,

I'd like to ask if there is a way to make Spacemacs's commands like `previous-buffer`, `next-buffer` not ignore some buffers like `magit`, `monky` buffers?

I tried to google but couldn't find an appropriate solution.

Thank you!

**Comment by person808** [comment]
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#special-buffers

See the linked faq (`spacemacs-useful-buffers-regexp` is probably the variable you want to use)

**Comment by tddsg** [comment]
Thank you so much! This is the right way to go. 

FIY, my new setting is as the following, in case there are people wanting the same thing like me:

```
(push "\\*magit\.\+\\*" spacemacs-useful-buffers-regexp)
(push "\\*monky\.\+\\*" spacemacs-useful-buffers-regexp)
```

**Comment by duianto** [comment]
This works for me:
```
(push "\\*magit\.\+" spacemacs-useful-buffers-regexp)
```
I removed the last `\\*` characters, because magit buffers don't have an ending asterisk in their buffer name.

**Comment by tddsg** [comment]
Thanks for the correction! I was testing only with monky but forgot to test with magit! :-D
