### ISSUE TITLE
Themes not loading

### ISSUE THREAD

**Issue by sho-87** [syl20bnr/spacemacs#8871]
I'm installing a few select themes from the megapack like so inside `dotspacemacs/layers`:

```
     (themes-megapack :packages
                      badwolf-theme
                      gruvbox-theme
                      material-theme
                      molokai-theme
                      monokai-theme
                      seti-theme
                      zenburn-theme)
```

Then I'm trying to load gruvbox on startup like this inside `dotspacemacs/init`:

`dotspacemacs-themes '(gruvbox)`

The themes seem to have installed OK (the first restart shows the a list of packages being downloaded). However, the gruvbox doesnt load and defaults to the spacemacs theme with this error:

```
Warnings:
- An error occurred while applying the theme "gruvbox", fallback on theme "spacemacs-dark". Error was: (file-error Cannot open load file No such file or directory autothemer)      
 - Please check the value of "dotspacemacs-themes" in your dotfile or open an issue so we can add support for the theme "gruvbox". 
```

Is there a workaround for this problem?

**Comment by jakemcarthur** [comment]
You will also need the autothemer package to use gruvbox, and it may require you to use dash if you aren't already using it.

I haven't tried in a while, but there are also other reasons I don't remember which prevented me from using gruvbox in the past.

**Comment by OkayDave** [comment]
I'm having the same issue after updating to `0.200.9.x`.

However, after start up if I can select the `gruvbox` theme from the `SPC T s` menu and it'll work fine.

**Comment by sho-87** [comment]
yeah I have the autothemer package installed (I can see it in `~/.emacs.d/elpa`, and like @OkayDave I can manually load the gruvbox theme, but spacemacs doesn't load it automatically on start

**Comment by aatxe** [comment]
I'm also having this issue on a new setup with `0.200.9`. Has anyone figured this out?

**Comment by aatxe** [comment]
I found some other issues on this as well, but the gist is autothemer is loading after the themes. The work around is to load autothemer (and its dependency dash) before themes. So, I added the following to user-init:

```elisp
  (load-file "~/.emacs.d/elpa/dash-20170523.219/dash.el")
  (load-file "~/.emacs.d/elpa/autothemer-20170112.1324/autothemer.el")
```

**Comment by henriquenj** [comment]
I also experiencing the same issue, if gruvbox is the first theme on `dotspacemacs-themes`, it will fall back to default spacemacs with the error message. I noticed that others variants of gruvbox also  have the same behaviour.

**Comment by henriquenj** [comment]
I'm unable to reproduce this on the develop branch, I think it might be fixed, can someone confirm? I tested on e09385d29ef2c95cef14b992028ca85da142dad7.

**Comment by OkayDave** [comment]
@henriquenj I've just done a fresh install this evening (unrelated to this issue, or even Spacemacs).

Using `master` the problem is present as described.

Using `develop` the problem appears to have gone away :+1:

**Comment by DWShuo** [comment]
running 0.200.9@25.2.2 (spacemacs) seems to only be an issue when using gruvbox theme

**Comment by richarddewit** [comment]
What's the status on this? I still have the issue on `0.200.10@25.3.1`

**Comment by henriquenj** [comment]
@richarddewit `0.200.10` is just a hotfix release. You need to switch to the `develop` branch to get the fix, or wait for the next release.

**Comment by rushsteve1** [comment]
The issue is still present on 0.200.13 for me at least.

**Comment by radoslawg** [comment]
I'm also experiencing this issue on 0.200.13 with theme darktooth.

**Comment by rouxbuciu** [comment]
Also experiencing this issue with gruvbox (and it's variants) on 0.200.13@26.1.
Works like a charm through `SPC T s`.
Halp! Gruvbox is love!

**Comment by IngvarListard** [comment]
Issue is still present  0.200.13@26.2
