### ISSUE TITLE
Defer loading packages

### ISSUE THREAD

**Issue by sho-87** [syl20bnr/spacemacs#8872]
I'm using the base distribution and adding specific packages from spacemacs layers like this:

`(spacemacs-editing :packages avy)`

I see that under the hood `which-key` is being used in various places

Is it possible to lazy load specific packages (say avy in this case) either by deferring it, or having it load only when a specific avy command is called?

What would the syntax look like in the context of adding specific packages like the example above?

**Comment by LdBeth** [comment]
Say, `avy` is actually deferred by default in Spacemacs.

**Comment by sho-87** [comment]
I'm just using `avy` as an example. Im wondering if its possible to defer loading any package in a layer through the `.spacemacs` file

**Comment by z3t0** [comment]
Defer until what event

**Comment by sho-87** [comment]
for example `use-package` allows you to defer loading until after x seconds of idle time, or only load once a certain command from the package is executed. I'm mostly looking for the latter, but either will help with overall startup time

**Comment by z3t0** [comment]
[this](https://github.com/syl20bnr/spacemacs/blob/master/doc/LAYERS.org#use-package) might have some useful information
