### ISSUE TITLE
zsh causing exec-path-from-shell :init: Expected printf output from shell (still)

### ISSUE THREAD

**Issue by zeroasterisk** [syl20bnr/spacemacs#8873]
#### Description :octocat:

re: exec-path-from-shell :init: Expected printf output from shell - #4755

I'm also getting this problem - and so far, none of the suggestions are helping.  I am new to spacemacs.

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:

```
Error (use-package): exec-path-from-shell :init: Expected printf output from shell, but got: "__RESULT/Users/alan/.nvm/versions/node/v6.7.0/bin:/Users/alan/.rvm/gems/ruby-2.2.2/bin:/..."
```

*Expected behaviour:* :heart: :smile:
no errors on startup

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by ublubu** [comment]
My error looks like this:

```
Error (use-package): exec-path-from-shell :init: Expected printf output from shell, but got: "__RESULT2945ad54c3e6b37c561ff49f058c4cc8/home/kynan/workspace/go/src/k8s.io/kubernetes:/home/kynan/go/bin:/home/kynan/workspace/go/bin:/home/kynan/workspace/go/src/k8s.io/kubernetes/third_party/etcd:/home/kynan/bin:/home/kynan/.local/bin:/home/kynan/workspace/go/src/k8s.io/kubernetes:/home/kynan/go/bin:/home/kynan/workspace/go/bin:/home/kynan/workspace/go/src/k8s.io/kubernetes/third_party/etcd:/home/kynan/bin:/home/kynan/.local/bin:/home/kynan/workspace/gcloud/google-cloud-sdk/bin:/home/kynan/workspace/go/src/k8s.io/kubernetes:/home/kynan/go/bin:/home/kynan/workspace/go/bin:/home/kynan/workspace/go/src/k8s.io/kubernetes/third_party/etcd:/home/kynan/bin:/home/kynan/.local/bin:/home/kynan/bin:/home/kynan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/kynan/Android/Sdk/tools:/home/kynan/Android/Sdk/platform-tools:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin__RESULT"
```

I'm on Ubuntu 16.04 with Emacs 25.1.1, Spacemacs 200.9, and these layers:

```
helm
auto-completion
emacs-lisp
syntax-checking
go
haskell
html
javascript
markdown
yaml

**Comment by RomanKapitonov** [comment]
Getting the same error. I've been trying to find the reason and it seems that the following code from .zshrc is broken:

```
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
```

Removing these lines eliminates the warning. But then another issue appears:
`PATH` is not being extended with nvm location and hence tern binary is not being found for the `javascript` layer. `tern binary not found spacemacs` warning appears in the warnings buffer.

**Comment by RomanKapitonov** [comment]
An interesting observation:

If to replace 
```
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
```
with

```
export NVM_DIR=~"$HOME/.nvm"
source $(brew --prefix nvm)/nvm.sh
```

the warning message disappears. I'm not sure how it's different from the above path, but that seems to make the warning disappear.

**Comment by hhxjzyr** [comment]
@RomanKapitonov  Yes...I change my code from
```
source ~/.oh-my-zsh/plugins/git/git.plugin.zsh
```
to 
```
source $HOME/.oh-my-zsh/plugins/git/git.plugin.zsh
```
Then the error disappear....
