### ISSUE TITLE
underscores `_` not shown in Info mode

### ISSUE THREAD

**Issue by MaskRay** [syl20bnr/spacemacs#8876]
Underscores in Info mode seem to be interpreted as "displaying the surrounding text as italics".

In this Info page '(gdb) Basic Python', `__init__` is displayed as `_init_` with `init` being italicized, the underscores in `parse_and_eval` are lost, and so on.

**Comment by MaskRay** [comment]
Found the issue. info+ tries to italicize text surrounded by underscores and add `'(invisible t)'` text property to underscores themselves. Excluding info+ resolves the issue.

**Comment by wushuyu** [comment]
@MaskRay thanks! I have the same problem. Your post solved my problem.
