### ISSUE TITLE
False error-reports in Python mode

### ISSUE THREAD

**Issue by zeka0** [syl20bnr/spacemacs#8888]
After uninstalled the old Anaconda2, I installed Anaconda3.
But I later found spacemacs Python mode is reporting errors that is false.
Here is a screenshot:
![default](https://cloud.githubusercontent.com/assets/13997167/25991318/555e6a82-3735-11e7-9d5a-599412614ea8.PNG)

You can see, at line 13, it reports that 
_**"standard import "import os" comes before "import tensorflow as tf" "**_
at line 21, it reports:
**_"no module 'python' in 'tensorflow' "_**, but I have that package, I have verified it in python _console.
and the weird thing is, at line 25, it reports:
_**"invalid constant name: 'sess' "**_
And line 52, 51, 28 report the same error.
Any ideas?

**Comment by CeleritasCelery** [comment]
Should report upstream at [flycheck/flycheck](https://github.com/flycheck/flycheck).

**Comment by robbyoconnor** [comment]
Yeah this is not a bug with spacemacs. Report to flycheck.

**Comment by zeka0** [comment]
I have submitted a new issue there.
Gonna say been waiting quite a long time.
https://github.com/flycheck/flycheck/issues/1252
