### ISSUE TITLE
org-plus-contrib install fails with spacemacs-base and no spacemacs-org layer

### ISSUE THREAD

**Issue by y0ast** [syl20bnr/spacemacs#8890]
The `git` layer depends on `org-plus-contrib`, which lives on org elpa instead of the normal elpa. The information that `org-plus-contrib` lives on org elpa is in `spacemacs-org` layer.

When using `spacemacs-base` the `spacemacs-org` is not added. When one tries to install `org-plus-contrib` or anything that depends on `org-plus-contrib`, one is presented with the following (unhelpful) error:

```
An error occurred while installing orgit (error: (file-error http://elpa.gnu.org/packages/org-plus-contrib-20170502.tar Not found))
```

I think it would be good to add some documentation, or an extra check when installing orgit.

(I fixed it by just adding the `spacemacs-org` layer).

**Comment by vaz** [comment]
:+1: thanks for the fix @y0ast, I was having the same error on every startup using `spacemacs-base`, since last update.

**Comment by JAremko** [comment]
@d12frosted  :shipit:

**Comment by d12frosted** [comment]
I can easily reproduce that error, but I don't think that adding `spacemacs-org` is a _solution_. What about installing`orgit` only when `org` package is used? Though I am not really sure why not using `spacemacs-org` layer prevents from installing `orgit`.

**Comment by d12frosted** [comment]
Anyways, here is PR :)

**Comment by tcstory** [comment]
yeah, use spacemacs-org instead will work
