### ISSUE TITLE
company complete conflit with emmet-mode

### ISSUE THREAD

**Issue by liuchong** [syl20bnr/spacemacs#8893]
When I'm editing a HTML file, such as type a "p", will pop out a list "p param picture plaintext...", so I cannot type tab to insert a `"<p></p>"` via emmet-mode, anybody have the same problem? Is there a solution on this, or there is something wrong of my config or usage? Thanks a lot!

**Comment by CeleritasCelery** [comment]
Should report upstream at [company-mode/company-mode](https://github.com/company-mode/company-mode)

**Comment by liuchong** [comment]
ok, let me open an issue there

**Comment by dgutov** [comment]
I don't get it.

You don't want idle completion in `html-mode` files? Disable it there, then.

**Comment by liuchong** [comment]
let me check, thanks
