### ISSUE TITLE
Decrease `scroll-conservatively` when `smooth-scrolling` is on

### ISSUE THREAD

**Issue by MaskRay** [syl20bnr/spacemacs#8894]
Currently `scroll-conservatively` is set to 101 when `smooth-scrolling` is on. It should suffice for a smaller value like 30 or so to enable simple navigational keys such as `j`, `k`, `C-f`. For `C-o` (evil-jump-backward), if the jump point is far away from the point, the cursor will be at the top or at the bottom, not recentered, which is annoying as not context lines are revealed.

```elisp
(defun spacemacs-navigation/init-smooth-scrolling ()
  (setq scroll-preserve-screen-position t
        scroll-margin 0
        scroll-conservatively (if dotspacemacs-smooth-scrolling 101 0))
  (spacemacs|add-toggle smooth-scrolling
    :status (< 0 scroll-conservatively)       ; this comparison can be changed to check if  < 0
    :on (spacemacs/enable-smooth-scrolling)
    :off (spacemacs/disable-smooth-scrolling)
    :documentation "Smooth scrolling."
    :evil-leader "tv"))
```

**Comment by CeleritasCelery** [comment]
what are you trying to do here?

**Comment by MaskRay** [comment]
After `evil-jump-backward`, I want the cursor to stay at the center.

**Comment by fiveNinePlusR** [comment]
This should really be asked in the gitter chat as this is not a bug in spacemacs

**Comment by CeleritasCelery** [comment]
Does your solution fix it?

**Comment by MaskRay** [comment]
@CeleritasCelery I'm still unclear how this should be implemented
