### ISSUE TITLE
Add more convenient editing commands for Emacs users

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#890]
Since Emacs users use chording, they won't have as many key bindings as Vim users. To make up for it, they make smart commands. For example, move to beginning of line or beginning of indentation with one key binding: [Smarter Navigation to the Beginning of a Line](http://emacsredux.com/blog/2013/05/22/smarter-navigation-to-the-beginning-of-a-line/). The newer implementation is in Prelude [here](https://github.com/bbatsov/prelude/blob/master/core/prelude-core.el#L138).

Some useful commands that I use daily:

- Open line below/above.
- Join line. We get `evil-join-line` for this
- Smart `kill-line`: If you press `C-w` and no region is active, it kills a line. If regions is active, it kills region instead. It can be done by advising `kill-region` like [this](https://bitbucket.org/hoangtu/.emacs.d/src/4ae1e7eabfa180fb474d7268854845b51a5c6329/custom/setup-editing.el?at=master#cl-359).
- Smart `kill-ring-save`: similar to `C-w`, but copy a line when no region is active and copy a region otehrwise. It can be done by advising [kill-ring-save](https://bitbucket.org/hoangtu/.emacs.d/src/4ae1e7eabfa180fb474d7268854845b51a5c6329/custom/setup-editing.el?at=master#cl-350).
- A command to indent whole buffer without moving point.

I will think of more.

**Comment by syl20bnr** [comment]
I agree to enhance the stock Emacs key bindings which can be gathered in a layer like `better-emacs-defaults` or something like this so emacs style could be used with pure or enhanced version to the preference of the user. Prelude is a good place to search for such improvements.
