### ISSUE TITLE
Magit commit opens *Async Shell Command* window

### ISSUE THREAD

**Issue by 3rd3** [syl20bnr/spacemacs#8900]
#### Description :octocat:

- Commit via `SPC g s c c` opens an empty *Async Shell Command* window near the bottom and puts the focus there. Is that intended? How can I change this behavior such that this window does not open or that the focus is set to the `COMMIT_EDIT_MSG` buffer?

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp syntax-checking auto-completion semantic
            (latex :variables latex-enable-auto-fill t)
            org git github version-control extra-langs markdown emacs-lisp haskell html lua php javascript shell-scripts java
            (haskell :variables haskell-enable-ghc-mod-support nil haskell-enable-ghci-ng-support t haskell-enable-hindent-style "gibiansky" haskell-enable-shm-support nil)
            (c-c++ :variables c-c++-enable-clang-support t)
            (python :variables python-test-runner 'pytest)
            (clojure :variables clojure-enable-fancify-symbols t)
            (shell :variables shell-default-height 20 shell-default-position 'bottom shell-enable-smart-eshell t shell-default-shell 'eshell)
            evil-snipe)
```
- System configuration features: JPEG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by CeleritasCelery** [comment]
Should report upstream at [magit/magit](https://github.com/magit/magit)

**Comment by robbyoconnor** [comment]
Please close -- This isn't an upstream bug -- the large majority of bugs are upstream bugs.
