### ISSUE TITLE
Spacemacs is slow in moving cursor continuously in a big file

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#8905]
Hi,

I notice that when using the arrow keys to move the cursor continuously in a big file, such as `.emacs.d/core/core-configuration-layer.el`, the cursor movement often lags and is not smooth. 

My guess is that during the cursor moving, there are some computations corresponding to the new cursor position, such as displaying eldoc, flycheck, flyspell... As the cursor continuously moves to a new position, these computations are performed again and again and this makes the cursor moving unsmooth.

Are there any ways to make the continuous cursor moving smooth?

If my guess is correct, is it possible to temporarily disable the events update during a continuous cursor moving?

Thanks for spending your time to look at my question!

**Comment by CeleritasCelery** [comment]
It is smooth for me. Sounds like you may need a performance upgrade for your computer.

**Comment by tddsg** [comment]
Not really. My computer's CPU is Intel Core i7 6700, with 16GB of RAM.
This slowness can happen when Emacs load many modules.

**Comment by scriptmode** [comment]
You could [profile](https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html) emacs to figure out which functions eats up most performance. And then selectivly deactivate stuff or optimize their behaviour.

**Comment by CeleritasCelery** [comment]
Also keep in mind that Spacemacs can only optimize load time performance. The individual package owners control the preformace of their code. Therefore if a package or combination of packages are slowing you down, then there is not much Spacemacs can do. You can either disable packages or live with the preformace. @scriptmode's suggestion about profiling may be a good idea if you are looking for packages to disable. But you may just want to start with removing the packages and minor-modes you use the least.

**Comment by CeleritasCelery** [comment]
On another note, if you ever dealing with really large files (over 10,000 lines) you should consider [vlf-mode](https://github.com/m00natic/vlfi)

**Comment by tddsg** [comment]
@scriptmode, @CeleritasCelery: Thanks for your suggestions. These sound really logical. I will monitor my Emacs's performance.

**Comment by tddsg** [comment]
Hi, just a follow-up question. 

I profiled the CPU usage and found out that the CPU consumption for `redisplay_internal` is quite high, especially the feature `spacline-ml-tddsg`, which is a customized version of `spaceline`. Is abnormal for the `redisplay` function?

In addition, the CPU usage of `spaceline-ml-tddsg` is 17%, but all its sub-items add up to only 6%. (2%  + 1% + 1% + 1% + 1%). Where is the other 11%?

```
- redisplay_internal (C function)                                 420  21%
 - eval                                                           389  19%
  - spaceline-ml-tddsg                                            355  17%
   + powerline-raw                                                 46   2%
   + powerline-buffer-id                                           35   1%
   + mapcar                                                        29   1%
   + flycheck-has-current-errors-p                                 27   1%
   + run-hooks                                                     20   1%
   + powerline-wave-right                                          19   0%
   + powerline-wave-left                                           14   0%
     powerline-render                                              11   0%
     vc-state                                                       8   0%
   + powerline-width                                                7   0%
   + s-trim                                                         5   0%
   + powerline-hud                                                  4   0%
     eyebrowse--get                                                 4   0%
     file-remote-p                                                  4   0%
     get-frame-persp                                                2   0%
  + concat                                                         14   0%
    if                                                              4   0%
 + jit-lock-function                                               31   1%

```

**Comment by CeleritasCelery** [comment]
`spaceline` is notorious for causing problems with `redisplay_internal` (see #8462, #8060, #6120, #5063, #4730, or #4552). Some users have found that  `dotspacemacs-mode-line-unicode-symbols nil` helps significantly. Others just disable the package all together. This seems to be a "works fine for some people, crashes everything for others" kind of problem.

**Comment by zeka0** [comment]
I encountered similar problem, but the file I was editing is small (less than 50 lines).
Spacemacs is slow when moving cursors using `j or w`, and what is odd is that,
when you press `j` multiple times, the cursor simply disappeared then reappeared at the expected position.
I was running Spacemacs on a virtual machine consisting of only 2G ram with 4 threads 2 core CPU.
Any ideas what might cause the problem and how to improve it?

**Comment by CeleritasCelery** [comment]
@zeka0 The problem is probably "running Spacemacs on a virtual machine consisting of only 2G ram with 4 threads 2 core CPU". You can take the advice mentioned above if you want to improve performance.

**Comment by armnrd** [comment]
> Hi, just a follow-up question.
> 
> I profiled the CPU usage and found out that the CPU consumption for `redisplay_internal` is quite high, especially the feature `spacline-ml-tddsg`, which is a customized version of `spaceline`. Is abnormal for the `redisplay` function?
> 
> In addition, the CPU usage of `spaceline-ml-tddsg` is 17%, but all its sub-items add up to only 6%. (2% + 1% + 1% + 1% + 1%). Where is the other 11%?
> 
> ```
> - redisplay_internal (C function)                                 420  21%
>  - eval                                                           389  19%
>   - spaceline-ml-tddsg                                            355  17%
>    + powerline-raw                                                 46   2%
>    + powerline-buffer-id                                           35   1%
>    + mapcar                                                        29   1%
>    + flycheck-has-current-errors-p                                 27   1%
>    + run-hooks                                                     20   1%
>    + powerline-wave-right                                          19   0%
>    + powerline-wave-left                                           14   0%
>      powerline-render                                              11   0%
>      vc-state                                                       8   0%
>    + powerline-width                                                7   0%
>    + s-trim                                                         5   0%
>    + powerline-hud                                                  4   0%
>      eyebrowse--get                                                 4   0%
>      file-remote-p                                                  4   0%
>      get-frame-persp                                                2   0%
>   + concat                                                         14   0%
>     if                                                              4   0%
>  + jit-lock-function                                               31   1%
> ```

I am new to Emacs, and am not familiar with the profiler. Could you tell me how you did this?
My attempt:
`M-x profiler-start
M-x profiler-stop
M-x profiler-report`

**Comment by duianto** [comment]
- `profiler-start`
- Choose cpu, mem or cpu+mem
- Perform the action you want to profile
- `profiler-report` opens the report buffer(s)
- `profiler-stop` when your done profiling.

https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html

**Comment by armnrd** [comment]
Thanks, that helps.

**Comment by elvinzeng** [comment]
+ redisplay_internal (C function)                               12618  76%
+ evil-escape-pre-command-hook                                   2158  13%
+ command-execute                                                 703   4%
+ timer-event-handler                                             466   2%
+ ...                                                             415   2%
+ flycheck-handle-signal                                           66   0%
+ flycheck-perform-deferred-syntax-check                            6   0%
+ which-key--hide-popup                                             3   0%
+ evil--jump-hook                                                   3   0%
  global-hl-line-unhighlight                                        3   0%

Mine is worse

**Comment by darrenkenny** [comment]
I certainly experience a lot of lag when using either the spaceline or doom mode lines on MacOS - but only if running as a GUI, not if I use it in a terminal, in a terminal it flies along, but I lack the benefits then of the GUI mode.

In the reading that I've done this appears to be mainly down to the font rendering - suggestions that I've looked at has been to disable unicode characters and pick some specific fonts - some had minor benefits, but nothing reduced the lag as much as switching to the 'vanilla' mode line.

While not as pretty, it certainly helps for usability to avoid the lag.

**Comment by fab6** [comment]
Hi,
for me it is the same like @darrenkenny described. Using spacemacs development and emacs 27.1 on macos.

**Comment by lebensterben** [comment]
@darrenkenny 
There is middle ground between terminal Emacs and full-GUI Emacs.
If you run an Emacs server in background daemon mode, then you are able to launch "terminal" Emacs in a GUI window. That is to say, you still have GUI only features like menubar, scroll bar, etc. But meanwhile, it's actually an terminal Emacs sessionl.

**Comment by fab6** [comment]
@lebensterben  Could you elaborate on this a bit more; I understand that I could start a server with emacs-gui with ```server-start``` and open a file using emacsclient from the terminal with ```emacsclient file```.
Is this what you meant?
Thank you!

**Comment by lebensterben** [comment]
@fab6 
You can use systemd, for example, to register a service that starts emacs as a background daemon upon system starts.
Then, use "emacslient -a ''" to start the client. The additional option instructs it to start the server if it's not already on. You can create a new .desktop file with this command.

**Comment by fab6** [comment]
ok, thank you very much! I will check you I can get it to run with macos.. it seems that that the gui is not started from iterm, but the terminal emacs version.

**Comment by fab6** [comment]
and it looks actually here https://emacs.stackexchange.com/questions/18507/os-x-and-daemon-mode that this is not so easy to get the middle ground running on macos...

**Comment by lebensterben** [comment]
@fab6 
it's just a one time set-up.

**Comment by fab6** [comment]
@lebensterben yes, that would not be the problem but I understood this part
![image](https://user-images.githubusercontent.com/3047695/108604360-b51c4f80-73ad-11eb-8931-1139f4df5d6c.png)
that it might not even possible to get this running on macos without be plainly using gui... but maybe I misunderstood it

**Comment by lebensterben** [comment]
Best solution is to use Linux. bugOS is hard to use.

**Comment by fab6** [comment]
yes, that's right...
