### ISSUE TITLE
configuration-layer//get-package-directory doesn't work with org-plus-contrib

### ISSUE THREAD

**Issue by jynnantonix** [syl20bnr/spacemacs#891]
I have a private config layer that uses the org-plus-contrib package from the [org-mode elpa repository](http://orgmode.org/elpa.html).  The version scheme for that package doesn't match the version scheme that spacemacs appears to expect:  the package directory looks like org-plus-contrib-20150316/.  This causes a problem when updating because the backup step complains that there is no file or directory named `/home/jynnantonix/.emacs.d/elpa/org-plus-contrib-20150316.nil`.  This is the offending code:

```
(defun configuration-layer//get-package-directory (pkg)
  "Return the directory path for PKG."
  (let ((pkg-desc (assq pkg package-alist)))
    (cond
     ((version< emacs-version "24.3.50")
      (let* ((version (aref (cdr pkg-desc) 0))
             (elpa-dir (concat user-emacs-directory "elpa/"))
             (pkg-dir-name (format "%s-%s.%s"
                                   (symbol-name pkg)
                                   (car version)
                                   (cadr version))))
        (expand-file-name (concat elpa-dir pkg-dir-name))))
     (t (package-desc-dir (cadr pkg-desc))))))
```
I have emacs version 24.3.1 (since that's the latest available on ubuntu trusty) and there is no `(cadr version)` so this function is returning a directory with a `nil` at the end.

**Comment by syl20bnr** [comment]
We can backport this function in the file: https://github.com/syl20bnr/spacemacs/blob/master/core/core-emacs-backports.el

**Comment by StreakyCobra** [comment]
This is an old issue without update for nearly one year. As we are also going to remove Emacs 24.3 support, I'm closing it.
