### ISSUE TITLE
Snippets with multiple identical $ fields are not expanded correctly

### ISSUE THREAD

**Issue by iesahin** [syl20bnr/spacemacs#8910]
#### Description :octocat:
Snippets with multiple identical $ fields are not expanded correctly

#### Reproduction guide :beetle:
- Start Emacs
- Create a new snippet with `SPC SPC yas-new-snippet` similar to following
```
# -*- mode: snippet -*-
# name: print-var
# key: ppp
# --
print("$1: {}\n".format($1))
$0
```
- Save and load the snippet
- Expand in a buffer using `SPC i s ppp` or `M-/ ppp`
- Write "abcd" to fill $1
*Observed behaviour:* :eyes: :broken_heart:
It produces something like
```
print("abcd: {}\n".format())
```
*Expected behaviour:* :heart: :smile:
It should produce something like
```
print("abcd: {}\n".format(abcd))
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html haskell helm auto-completion emacs-lisp git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control c-c   python spotify elfeed dash finance syntax-checking spell-checking semantic mu4e games emoji shell-scripts osx speed-reading pandoc
      (elfeed :variables rmh-elfeed-org-files
              (list "~/.spacemacs.d/elfeed1.org"))
      colors themes-megapack cscope gtags
      (wakatime :variables wakatime-api-key "xxxxxx" wakatime-cli-path "/home/iesahin/.local/bin/wakatime" wakatime-python-bin "/usr/bin/python"))
```

#### Backtrace :paw_prints:
```

```

**Comment by swaroopch** [comment]
I'm on develop branch and I have 2 different snippets with the same kind of expansion (just called `pp`) and both of those work...

**Comment by iesahin** [comment]
@swaroopch yep, thanks. it looks so, but `master` branch has this bug still and I cannot discover the cause.
