### ISSUE TITLE
how to use paredit key bindings

### ISSUE THREAD

**Issue by bmabey** [syl20bnr/spacemacs#8913]
I would like to use `paredit` key bindings when editing lisp code. I have tried using `(sp-use-paredit-bindings)`and disabling `evil-lisp-state` (by putting it in `dotspacemacs-excluded-packages`) but neither of those work. I have tried to set some keybindings for particular modes (related to clojure)  by putting the following in my `dotspacemacs/user-config`:
```elisp
  (dolist (m '(clojure-mode
               clojurec-mode
               clojurescript-mode
               clojurex-mode
               cider-repl-mode
               cider-clojure-interaction-mode))

             (evil-define-key 'normal m
               "M-<up>" 'sp-splice-sexp-killing-backward
               "C-<right>" 'sp-forward-barf-sexp
               "C-k" 'sp-kill-sexp
               "C-<left>" 'sp-forward-barf-sexp))
```

The above has no effect though. Even if it did work it is less than ideal since I would like these bindings for all lisp modes. 

Any tips on how to get `paredit` key bindings? I know about the `SPC k` menu for `evil-lisp-state` and would like to keep that but have the original keybindings as well.

**Comment by swaroopch** [comment]
How about going into insert mode and use emacs (holy mode) style bindings there?

**Comment by robbyoconnor** [comment]
Please ask on the gitter chat and not here. GitHub issues are not meant to be used as a mailing list. Please close this to prevent clutter.
