### ISSUE TITLE
how to custom docstring in elixir/python ?

### ISSUE THREAD

**Issue by mydearxym** [syl20bnr/spacemacs#8916]
now spacemacs treat docstring highlight the same as string,  and their is no option in `customize-face`, is there a way to customize docstring colors in  elixir/python files ?

![](http://opu2sbfbt.bkt.clouddn.com/17-5-17/41710561-file_1494994387425_11f97.png)

**Comment by CeleritasCelery** [comment]
Not unless you want to modify the major-mode code.
