### ISSUE TITLE
Finance layer does not install ledger

### ISSUE THREAD

**Issue by legalcodes** [syl20bnr/spacemacs#8922]
#### Description :octocat:
Finance layer does not install ledger dependency

#### Reproduction guide :beetle:
- Start Emacs
- Add 'finance' to dotspacemacs-configuration-layers
- Open any .ledger file

*Observed behaviour:* :eyes: :broken_heart:
Error thrown: `File mode specification error: (file-error Searching for program No such file or directory ledger)`
Now install ledger manually (brew install ledger) and observe successful ledger-mode behavior.

*Expected behaviour:* :heart: :smile:
.ledger file should successfully trigger ledger-mode and make its features available

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(finance helm emacs-lisp)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by sdwolf** [comment]
I belive you should install any external dependencies and packages yourself. Maybe the docs should mention this.

**Comment by legalcodes** [comment]
Thanks. Opened https://github.com/syl20bnr/spacemacs/pull/8926/ to address this.
