### ISSUE TITLE
Inconsistently incorrect "d" key behavior in the emacs mode

### ISSUE THREAD

**Issue by HoverHell** [syl20bnr/spacemacs#8923]
#### Description :octocat:

In dotspacemacs-editing-style emacs, key 'd' sometimes deletes the previous
character rather than placing a 'd' character.

It appears to be a timing problem, i.e. it reproduces most consistently when
pasting into an emacs instance inside a terminal emulator.

#### Reproduction guide :beetle:

- Start spacemacs, clean install, the Holy Tower mode.
- Input "afdfdfdfdfdfdfdfd" quickly (e.g. by pasting in the terminal).

*Observed behaviour:* :eyes: :broken_heart:

Only 'a' remains.

*Expected behaviour:* :heart: :smile:

The entire "afdfdfdfdfdfdfdfd" should be entered.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: nil
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XWIDGETS

**Comment by CeleritasCelery** [comment]
This is because of `evil-escape-mode` Which uses `fd` as the default escape sequence. I toggled holy mode on and I am seeing the same behavior. Looks like this is a bug. In the meantime you can use `(evil-escape-mode -1)` to disable it.

**Comment by Miciah** [comment]
Looks like the same issue as #10667.

**Comment by renatomassaro** [comment]
I'm on develop (HEAD 5b2e969b3b22bb5518a3bc32edcf4db9318d24b5) and this issue remains.

No need to paste; entering insert mode and quickly typing `df` triggers the problem.
