### ISSUE TITLE
Custom Github URL does not load PR's

### ISSUE THREAD

**Issue by romariolopezc** [syl20bnr/spacemacs#8925]
#### Description :octocat:
Github layer doesn't fetch PR's (I have the repo hosted at a different url, not github.com).
I tried using ssh and https, but no result

#### Reproduction guide :beetle:
- Start Emacs
- Open project
- `SPC g s`
- `# g`
- Doesn't load PR's and displays this error: `Remote repository is not configured or incorrect.`

*Observed behaviour:* :eyes: :broken_heart:
Doesn't load PR's

*Expected behaviour:* :heart: :smile:
Loads and display PR's

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(markdown ivy auto-completion better-defaults emacs-lisp git markdown games
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          spell-checking syntax-checking version-control github osx javascript elixir react
          (elm :variables elm-sort-imports-on-save t elm-format-on-save t)
          themes-megapack
          (ranger :variables ranger-show-preview t))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by CeleritasCelery** [comment]
Report upstream at [magit/magit](https://github.com/magit/magit)
