### ISSUE TITLE
Any idea about download package through spacemacs and delay the compile?

### ISSUE THREAD

**Issue by myme5261314** [syl20bnr/spacemacs#8929]
I'm facing this embarrass situation that I have a offline server which does not have internet connection at all and with redhat linux.
I wan to use spacemacs on it. But just use the .emacs.d compiled from my normal Ubuntu won't work since the `el` files are compiled on different environment.
Any idea about that we can just download what our self-defined `.spacemacs.d` required (including from melpa and github, etc.al) but not compile them and compile until I copy these files to the offline server?

**Comment by myme5261314** [comment]
For now, I use docker to setup a `centos` container and setup similar environment compared to offline `redhat` server. Download and compile packages and then copy the `.emacs.d` directory to the offline server.

**Comment by CeleritasCelery** [comment]
you can download all Spacemacs melpa packages from [syl20bnr/spacemacs-elpa-mirror](https://github.com/syl20bnr/spacemacs-elpa-mirror)

**Comment by longtomjr** [comment]
Please consider closing the issue if your question have been answered Thanks :).

**Comment by myme5261314** [comment]
@CeleritasCelery This seems good, but the remaining issue is how to use this mirror under the environment lack of internet, and not covering some packages located out of melpa (such as github, et.al)

@longtomjr Maybe we can discuss out better solution than my `docker` one?

**Comment by CeleritasCelery** [comment]
@myme5261314 download it (along with any github packages) and copy them to your internet-less machine. Add this line pointing to your local copy.
```elisp
  (setq configuration-layer--elpa-archives
        `(("melpa" . ,(expand-file-name "<path>/elpa-mirror/spacemacs-elpa-mirror-latest/melpa"))
          ("org"   . ,(expand-file-name "<path>/elpa-mirror/spacemacs-elpa-mirror-latest/org"))
          ("gnu"   . ,(expand-file-name "<path>/elpa-mirror/spacemacs-elpa-mirror-latest/gnu"))))
```

**Comment by myme5261314** [comment]
@CeleritasCelery  Seems to be the best solution. Closing it.
