### ISSUE TITLE
How to make Tab function for both 'cycle and 'complete in autocompletion layer?

### ISSUE THREAD

**Issue by cmatzenbach** [syl20bnr/spacemacs#8934]
So I've been asking around on the spacemacs chat for help with this, but no one seems to know.  Is there a way to set TAB to function as both 'complete and 'cycle for the autocompletion layer?  Here's the goal: start typing, autocompletion suggestion window pops up, pressing Tab completes the first selection, pressing Tab again completes the second, on and on until you've reached the suggestion you want, then you just resume typing.  Is there a way to do this?

**Comment by robbyoconnor** [comment]
In an effort to make things more tidy -- plwase close this and instead ask this on the gitter chat.

**Comment by cmatzenbach** [comment]
For any similar issues see [#526](https://github.com/company-mode/company-mode/issues/526)
