### ISSUE TITLE
Can't turn off search result highlighting.

### ISSUE THREAD

**Issue by deech** [syl20bnr/spacemacs#8935]
#### Description :octocat:
Setting `(global-evil-search-highlight-persist nil)` in `(defun dotspacemacs/user-config ...)` keeps highlighting on search results even after point leaves them.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.91.2
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(go csv d javascript html yaml nim python markdown erlang ocaml scala auto-completion org git shell rust ivy)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by feng-qi** [comment]
Have you tried `SPC s c`? I think it's a convenient way to turn off the highlight.

**Comment by deech** [comment]
That's what I always do. I want it to turn off on it's own.

**Comment by longtomjr** [comment]
note in the documentation: `Setting this variable directly does not take effect;`

**Comment by longtomjr** [comment]
To disable hlsearch, uninstall the evil-search-highlight-persist package.

You can do this by adding it to the `dotspacemacs-excluded-packages` list in your dotfile under `dotspacemacs/init`.

It should look like this when done: `dotspacemacs-excluded-packages '( evil-search-highlight-persist)`

**Comment by deech** [comment]
Yes, thanks!

**Comment by xged** [comment]
Issue persists!
`dotspacemacs-excluded-packages '( evil-search-highlight-persist)` does not help.

**Comment by am** [comment]
Any update on this? As stated by @xged and 6 other this is still an issue. @gilch I can confirm the same behavior.

**Comment by stephenkraemer** [comment]
``` lisp
(setq evil-ex-search-highlight-all nil)
```
works for me (emacs 26.2, develop 09af9fc)

**Comment by mcp292** [comment]
> ```lisp
> (setq evil-ex-search-highlight-all nil)
> ```
> 
> works for me (emacs 26.2, develop [09af9fc](https://github.com/syl20bnr/spacemacs/commit/09af9fc40b695a22cb6a3f59d61b3c23aed6fa79))

This works for me, but not as expected. `/{string} RET` clears highlighting on `RET`, but if I hit `n` the highlighting is back and I am forced to issue `SPC s c` to clear it.

I was hoping highlighting would remain off as I cycle through with `n` and `N` as in standard vim.

**Comment by lebensterben** [comment]
@mcp292 works for me. try to restart emacs after setting this.

**Comment by mcp292** [comment]
> @mcp292 works for me. try to restart emacs after setting this.

Yes that worked, thank you. 

The behavior I observed was attributed to `evil-ex-search-persistent-highlight` set to `nil`.
