### ISSUE TITLE
save-buffer breaks the `.` command

### ISSUE THREAD

**Issue by MaikKlein** [syl20bnr/spacemacs#8937]
#### Description :octocat:
save-buffer breaks the `.` command

#### Reproduction guide :beetle:
- Start Emacs
- See: http://i.imgur.com/DN73zwt.gif
- Try to use `.` after you have saved the buffer

*Observed behaviour:* :eyes: :broken_heart:
`.` command doesn't do anything.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html javascript
      (rcirc :variables rcirc-enable-authinfo-support t)
      (shell :variables shell-default-term-shell "/bin/zsh")
      rust yaml markdown shaders helm
      (auto-completion :variables auto-completion-complete-with-key-sequence "C-SPC" auto-completion-complete-with-key-sequence-delay 0.0 auto-completion-enable-sort-by-usage nil auto-completion-private-snippets-directory "~/src/yasnippet-snippets" auto-completion-enable-help-tooltip nil)
      emacs-lisp git themes-megapack syntax-checking nixos)
```

**Comment by JAremko** [comment]
You probably should create issue at https://github.com/emacs-evil/evil

**Comment by Miciah** [comment]
@MaikKlein, can you still reproduce this issue? I cannot.

**Comment by MaikKlein** [comment]
No, this issue can be closed.
