### ISSUE TITLE
Moving .spacemacs to .spacemacs.d/init.el results in layer directory warning

### ISSUE THREAD

**Issue by sindikat** [syl20bnr/spacemacs#8940]
#### Description :octocat:
Moving .spacemacs to .spacemacs.d/init.el results in layer directory warning

#### Reproduction guide :beetle:
- Move `.spacemacs` file to `.spacemacs.d/init.el`
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
In welcome buffer you see this:

    Warnings:
        - Layer directory "/home/sindikat/.spacemacs.d/layers/" not found. Ignoring it.      

*Expected behaviour:* :heart: :smile:
This warning shouldn't exist, as the behaviour documented in Spacemacs documentation is that moving `.spacemacs` to `.spacemacs.d/init.el` is a trivial operation and shouldn't change the behavior of anything.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. c1cfb65e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp/mu4e/" mu4e-maildir "~/mail")
 org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking themes-megapack version-control asm coq elm emacs-lisp graphviz
 (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "johan-tibell")
 html latex octave python racket rust vimscript markdown yaml sindikat-gnus)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by robbyoconnor** [comment]
Create the directory ;)

**Comment by JAremko** [comment]
@syl20bnr  We probably shouldn't warn user about it in [`configuration-layer/discover-layers`](https://github.com/syl20bnr/spacemacs/blob/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/core/core-configuration-layer.el#L1108) or may be create the folder automatically?

**Comment by thyeme** [comment]
> Create the directory -- or even better update the docs!

@robbyoconnor what do you mean by "update the docs"?

**Comment by robbyoconnor** [comment]
> @robbyoconnor what do you mean by "update the docs"?

@thyeme use `develop` branch -- since it has been fixed. I have no idea what I meant by that...it was over 2 years ago.
