### ISSUE TITLE
Use Zenburn as default theme

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#895]
The reasons:

- It looks nicer with Spacemacs logo. The dark background makes Spacemacs logo standout because of the contrast. Here is how it look likes:

![zenburn-spacemacs](https://cloud.githubusercontent.com/assets/4818719/6764079/fecff082-cfd0-11e4-8f62-293d62bebeb6.gif)

- Well support for many packages, and this is important. Until now, I only see `Zenburn` and `Monokai` and `Tomorrow` themes support Helm properly and make it look nice. Especially `Zenburn`, since it is the default of Prelude, it receives support for things Prelude includes. Here is an example of `Info+`:

![info -spacemacs](https://cloud.githubusercontent.com/assets/4818719/6764114/c096120e-cfd2-11e4-973e-e05a9d6f67fe.gif)

- The theme looks pleasant in general.

**Comment by tuhdo** [comment]
Btw, why Spacemacs doesn't use the text `spacemacs_` like the logo in the homepage? I think the text looks nice and goes with the logo.

**Comment by CestDiego** [comment]
I second this. I actually use zenburn as a default. But I think leuven theme is even more beautiful ;_; it just lacks a good dark version.

**Comment by syl20bnr** [comment]
I'm in the same boat as you, I don't use the default Spacemacs theme but it is not zenburn.

Zenburn is already in the cycle list so it very easy to reach it from the stock configuration of spacemacs. 

Since colors and tastes are a user preference I won't change the default theme.

**Comment by tuhdo** [comment]
But if we talk about functionality, then `solarized` does not look support Helm well in terminal while `Zenburn` still looks the same as GUI version. And imo, `solarized` look is not comfortable in terminal

**Comment by tuhdo** [comment]
You can take a look at [this issue](https://github.com/purcell/color-theme-sanityinc-solarized/issues/16) that also links to [this issue](https://github.com/bbatsov/solarized-emacs/issues/18). And people suggest to use Zenburn (or if you find something equivalent, that's fine).

**Comment by syl20bnr** [comment]
I am aware of this issue, it is for the dark variant which is not the
default, solarized light is a good theme with as many people liking it as
people liking zenburn.

As I said I don't use solarized light as my theme and I won't change the
default of Spacemacs because of this, it is easily changeable in the
dotfile.

I will repeat myself but themes are user preferences, no matter the default
it cannot please everybody.

Le samedi 21 mars 2015, Tu Do <notifications@github.com> a écrit :

> You can take a look at this issue
> <https://github.com/purcell/color-theme-sanityinc-solarized/issues/16>
> that also links to this issue
> <https://github.com/bbatsov/solarized-emacs/issues/18>. And people
> suggest to use Zenburn (or if you find something equivalent, that's fine).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/895#issuecomment-84375978>.
>


-- 
-syl20bnr-

**Comment by tuhdo** [comment]
Alright then.

**Comment by syl20bnr** [comment]
For the spacemacs logo, the logo on the readme has a white background.

**Comment by Funnnny** [comment]
can I bump this issue?
There's some reason to switch away:
- Solarized is a popular theme, there's a lot of implement which has a same package name and different features.
- Most solarized theme has problem with 256 color terminal, having a built-in theme makes it harder to install other theme.
- We have to manually update the theme.

**Comment by ifesdjeen** [comment]
+1, built-in solarized scheme is broken for 256 color terminal

**Comment by TheBB** [comment]
We aren't using solarized as default any more, so this seems moot.

**Comment by ifesdjeen** [comment]
:fireworks: awesome! then i only need to upgrade
