### ISSUE TITLE
React Layer indentation for components passed as props

### ISSUE THREAD

**Issue by dre-hh** [syl20bnr/spacemacs#8954]
#### Description :octocat:
React Layer indentation for components passed as props

#### Reproduction guide :beetle:
- Start Spacemacs with react layer
- Edit a jsx file 
```jsx
<Foo 
  someLongValue='x'
  text={
    <Text>text</Text>
  } 
}/>
```
- Go into insert mode and add new line before the word `text`

*Observed behaviour:* :eyes: :broken_heart:
 text is aligned to the value of previous attribute
```jsx
<Foo 
  someLongValue='x'
  text={
    <Text>
                 text
    </Text>
  } 
}/>
```

*Expected behaviour:* :heart: :smile:
Text should be aligned according normal indent rules

```
<Foo 
  someLongValue='x'
  text={
    <Text>
       text
    </Text>
  } 
}/>
```

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git html javascript markdown org osx syntax-checking react ruby version-control yaml
                 (org :variables org-enable-reveal-js-support t))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:

**Comment by robbyoconnor** [comment]
Should probably report upstream...

**Comment by dre-hh** [comment]
Do you mean to the package repo the react layer is using? But which one would it be? web-mode?

**Comment by robbyoconnor** [comment]
Well yes. Report to `web-mode` as we don't do anything special.

**Comment by robbyoconnor** [comment]
This has been fixed upstream. Please close @dre-hh.
