### ISSUE TITLE
TypeScript Layer - jump-to-definition not working

### ISSUE THREAD

**Issue by mattnedrich** [syl20bnr/spacemacs#8963]
I have noticed that the `jump-to-definition` (`SPC m g g`) behavior has changed and works less often that it did previously. It used to jump to definitions in other files with high success. It now seems to work much less reliably and only jumps to import statements.

**Comment by JAremko** [comment]
Probably related https://github.com/ananthakumaran/tide/issues/154

**Comment by jeremyjh** [comment]
It really doesn't work at all for me now, it just jumps around in the same file. I guess it started after the most recent tide update. ananthakumaran/tide#154 really does not describe the problem I'm seeing, it does not work regardless of the type of import and I do not see any errors in my logs.

**Comment by mattnedrich** [comment]
Thanks for sharing @jeremyjh. Glad to hear I'm not the only one observing this. It's really frustrating - it used to work pretty well.

**Comment by syl20bnr** [comment]
May be fixed in develop.

**Comment by garrettm** [comment]
@syl20bnr seems to work in develop for me, thank you so much for this

**Comment by piq9117** [comment]
Thank you for working on this. Will it be merged soon? Or should I just get from develop?
