### ISSUE TITLE
Emacs 26 hangs consuming 99% of CPU after M-x (or SPC SPC)

### ISSUE THREAD

**Issue by istinspring** [syl20bnr/spacemacs#8964]
#### Description :octocat:

Tried to dodge segfault problem described at #8844 installing the --HEAD 
version of emacs. Segfault is gone indeed. But another one problem raised.

```
Auto-evilification could not remap these functions in map ‘edebug-mode-map’:
   - ‘edebug-Go-nonstop-mode’ originally mapped on ‘G’
```

#### Reproduction guide :beetle:
- Start Emacs
- Work a bit
- hit SPC SPC or M-x
- profit!

*Observed behaviour:* :eyes: :broken_heart:
99% of CPU consumed.

*Expected behaviour:* :heart: :smile:
helm up

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(osx better-defaults vim-powerline helm auto-completion
     (shell :variables shell-default-shell 'eshell shell-default-term-shell "/bin/zsh -i" shell-default-position 'bottom shell-default-height 34)
     (org :variables org-enable-github-support t org-projectile-file "todos.org")
     syntax-checking emacs-lisp javascript
     (python :variables python-test-runner 'pytest)
     html yaml markdown docker
     (wakatime :variables wakatime-api-key "****" wakatime-cli-path "/usr/local/bin/wakatime"))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:

```
Auto-evilification could not remap these functions in map ‘edebug-mode-map’:
   - ‘edebug-Go-nonstop-mode’ originally mapped on ‘G’
```

**Comment by istinspring** [comment]
duplicate of #8654

**Comment by JAremko** [comment]
Since it is a duplicate I'll close the issue. Thx for reporting anyway  :+1:
