### ISSUE TITLE
`C-c C-c` in Markdown mode is flaky (?)

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#8967]
#### Description :octocat:

I've been using https://github.com/alpha22jp/atomic-chrome (I think it's much better than Edit-With-Emacs),
recently I changed the default format to markdown (used to use Org), and suddenly noticed: when I'm done editing and press `C-c C-c` sometimes it just hangs Emacs. 

I spent hours trying to figure out why that's happening. Apparently this does not affect master branch, it's broken only in develop. 

If someone could shed some light or suggested what have may causing it, it'd be great! 

I noticed when `C-c C-c` is pressed in a markdown buffer (not connected to atomic-chrome), although doesn't hang Emacs, it throws some `Wrong type argument error`. Does that have anything to do with this issue?

I'm trying to locate responsible commit (may take awhile)

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. d4b00443)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((org :variables org-enable-reveal-js-support t org-enable-bootstrap-support t org-enable-github-support t :packages
      (not org-present))
 csv yaml emacs-lisp clojure haskell lua javascript
 (html :packages
       (not pug-mode slim-mode))
 (markdown :variables markdown-live-preview-engine 'vmd)
 (shell-scripts :packages
                (not fish-mode))
 (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 syntax-checking spell-checking helm fasd osx restclient emoji search-engine imenu-list docker
 (shell :variables shell-enable-smart-eshell t comint-scroll-show-maximum-output nil comint-move-point-for-output nil)
 (ibuffer :variables ibuffer-old-time 8)
 git
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 (github :packages
         (not magit-gh-pulls)
         :variables gist-view-gist t)
 ag-dired ag-general ag-synonyms ag-org ag-clojure ag-web)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by agzam** [comment]
ok, this is the commit I think that broke things for me: https://github.com/syl20bnr/spacemacs/commit/8aa42a071930b1c81da302c852ad8a303ccc53f0

**Comment by agzam** [comment]
So, logical (yet not ideal) work-around would be something like this:

    (defun ag/switch-focus-to-emacs-frame ()
      (when (eq system-type 'darwin)
        (shell-command "open -a \"Emacs\""))
      (orgtbl-mode -1))
      
    (add-hook 'atomic-chrome-edit-mode-hook #'ag/switch-focus-to-emacs-frame)
    
That will disable, `C-c C-c` biding for tables. Ideally of course it should be smart-enough and still recognize when `C-c C-c` is pressed when within the table.

However, the point is: that hook (in https://github.com/syl20bnr/spacemacs/commit/8aa42a071930b1c81da302c852ad8a303ccc53f0) may have broken other things too.

**Comment by agzam** [comment]
dammit... the snippet above did not fix my problem ;(

**Comment by agzam** [comment]
This fixes it nicely, and the tables work too:

    (defun atomic-start-edit ()
      (remove-hook 'after-save-hook 'cleanup-org-tables)
      (when (eq system-type 'darwin)
        (shell-command "open -a \"Emacs\"")))

    (defun atomic-edit-done ()
      (add-hook 'after-save-hook 'cleanup-org-tables  nil 'make-it-local)
      (when (eq system-type 'darwin)
        (shell-command "open -a \"Google Chrome\"")))

    (add-hook 'atomic-chrome-edit-mode-hook #'atomic-start-edit)
    (add-hook 'atomic-chrome-edit-done-hook #'atomic-edit-done)

**Comment by agzam** [comment]
something seems to be doing wonky stuff, I suspect mmm mode, I can't find a way to disable it. Locally.

**Comment by jsab** [comment]
@agzam's workaround worked for me:

```emacs
  (add-hook 'atomic-chrome-edit-mode-hook
            (lambda ()
              (remove-hook 'markdown-mode-hook 'spacemacs/activate-mmm-mode)
              (remove-hook 'markdown-mode-hook 'spacemacs//cleanup-org-tables-on-save)))
```

**Comment by jsab** [comment]
Is this fixed? Can we remove the workaround?
