### ISSUE TITLE
How to change the initial view of org files?

### ISSUE THREAD

**Issue by zhixing2017** [syl20bnr/spacemacs#8972]
I want to open the org files with the view of `fold`.
I created a layer: zx-org, there was 1 files: config.el
In config.el, the codes below were used.

``` emacs-lisp
(with-eval-after-load 'org
  (setq org-agenda-files (list (concat doc "Files/")
                               (concat doc "Files/Experiments/")))
  (setq diary-file (concat doc "Files/Misc/diary"))
  (setq org-default-notes-file (concat doc "Files/Notes.org"))
  (setq bookmark-default-file (concat doc "Files/Misc/bookmarks"))

  (setq org-download-heading-lvl nil)
  (setq org-download-annotate-function 'ignore)
)
```
The setup of `org-agenda-files` led to the initial view of org files into `showeverything`.
If I commented the code, the initial view is `fold`.

If I want to set the `org-agenda-files`, where should I put the code?

emacs-version is "25.2.1"
org-version is "9.0.7"
spacemacs-version is "0.200.9"

**Comment by fiveNinePlusR** [comment]
this is more of a question for either gitter chat, freenode irc #emacs or the org-mode mailing list. i'd suggest closing this and asking in those places.

**Comment by zhixing2017** [comment]
ok, I will try. Thanks

**Comment by zhixing2017** [comment]
I have fonud the reason. 
If I add agenda item to startup-lists in `.spacemacs`, it will lead to the error.
I do not it is =a but or what=. 
Maybe this option lead to the conflict between the org in original emacs and the newer org package downloaded.
``` emacs-lisp
dotspacemacs-startup-lists '((agenda . 4)
                                )
```
