### ISSUE TITLE
undo does not work in calc

### ISSUE THREAD

**Issue by neic** [syl20bnr/spacemacs#8975]
#### Description :octocat:
`undo` does not work in `calc`.

#### Reproduction guide :beetle:
- Start Emacs
- Open `calc` with `SPC a c`.
- Do some action. E.g press `3` and `enter`.
- `undo` with `C-_`.

*Observed behaviour:* :eyes: :broken_heart:
The `undo` does not happen and the message `Buffer is read-only: #<buffer *Calculator*>` appears.

*Expected behaviour:* :heart: :smile:
It should undo the action. This works in emacs without spacemacs.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. c812c5be)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(
;; erc config removed for issue

 spell-checking syntax-checking auto-completion helm better-defaults org ibuffer django csv emacs-lisp fsharp go html javascript
 (latex :variables TeX-save-query nil TeX-error-overview-open-after-TeX-run t)
 markdown php
 (python :variables python-shell-interpreter "python3" flycheck-python-pycompile-executable "python3")
 yaml osx git version-control)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by vatrat** [comment]
Not sure if this answers your question, but undo in emacs calc is `U`, and redo is `C-r`

**Comment by vatrat** [comment]
Whoops, didn't see that you said `C-_` works in vanilla emacs.

**Comment by neic** [comment]
After updating to `emacs-25.3.1-mac-6.8` and updating all the packages to the current versions as of now, it seem to work again 😄

**Comment by vatrat** [comment]
Oh, great! Thanks for closing the issue.
