### ISSUE TITLE
Themes not showing up after install

### ISSUE THREAD

**Issue by flyingfisch** [syl20bnr/spacemacs#898]
I added this to my `.spacemacs`, and watched it download and presumably install all the packages, but only 19 show up when I do `<SPC> T h`.

```
(setq-default dotspacemacs-configuration-layers '(themes-megapack))
```

Here is my full `.spacemacs`: https://gist.github.com/flyingfisch/d8e260afae4a5bde1e66

**Comment by syl20bnr** [comment]
This is a known regression after the new use-package 2.0, I will fix it very soon.

**Comment by flyingfisch** [comment]
Cool, thanks! Thought I was doing something wrong lol.

**Comment by syl20bnr** [comment]
Should be ok in develop branch.

**Comment by kjsebastian** [comment]
If anyone wants to have the functionality while this gets merged use the below workaround.
```
(-each
   (-map
      (lambda (item)
      (format "~/.emacs.d/elpa/%s" item))
   (-filter
      (lambda (item) (s-contains? "theme" item))
      (directory-files "~/.emacs.d/elpa/")))
   (lambda (item)
      (add-to-list 'custom-theme-load-path item)))
```
from http://stackoverflow.com/questions/9840558/why-cant-emacs-24-find-a-custom-theme-i-added
