### ISSUE TITLE
Pass: describe and other functions doesn't work untill I run init store

### ISSUE THREAD

**Issue by kepi** [syl20bnr/spacemacs#8981]
`SPC A p ?` leads to `completing-read: Symbol’s function definition is void: password-store-list` error. When I first run i.e. `SPC A p y` and then `SPC A p ?` everything works fine.

It seams to me that there is some problem with autoload of some functions, maybe because pass-describe is added from Spacemacs. My lips-fu is not good enough to decipher this.

**Comment by slyfr** [comment]
I have exactly the same behavior.
