### ISSUE TITLE
Emacs 25 dependencies in haskell and github layers

### ISSUE THREAD

**Issue by kini** [syl20bnr/spacemacs#8985]
#### Description :octocat:
The current MELPA versions of the packages `dante` (required by the
haskell layer) and `magithub` (required by the github layer) require
Emacs 25.1 and Emacs 25 respectively.

#### Reproduction guide :beetle:
- Have haskell layer and github layer enabled in your `~/.spacemacs`
- Start Emacs 24.5
- Update packages

*Observed behaviour:* :eyes: :broken_heart:
Updater fails to install dante and magithub due to unsatisfied dependencies on emacs-25.1 and emacs-25.

*Expected behaviour:* :heart: :smile:
Updater suceeds

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 8c230bfb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(jabber javascript elm csv github gnus graphviz haskell html python rust helm better-defaults emacs-lisp git markdown org
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        (spell-checking :variables spell-checking-enable-by-default nil)
        syntax-checking version-control)
```

**Comment by JAremko** [comment]
Yeah looks like so https://github.com/jyp/dante/blob/master/dante.el#L15

**Comment by JAremko** [comment]
I don't think that there's anything we can do about it. So you probably should ask the `dante` authors to add Emacs 24.x support

**Comment by JAremko** [comment]
Meanwhile documentation PR's are welcome.  At least we can mention that dante  requires Emacs 25

**Comment by JAremko** [comment]
I think I'm done adding tags to this :smile:

**Comment by kini** [comment]
>I don't think that there's anything we can do about it. So you probably should ask the `dante` authors to add Emacs 24.x support

Hmm, I would have thought that if spacemacs aims to support Emacs 24.4, then we should avoid requiring packages that don't work on Emacs 24.4 in our layers.  So the resolution to this bug would be to change the Haskell layer so that it doesn't require the dante package to be installed, perhaps unless the user explicitly indicates that she wants this by setting a layer variable.

As far as I understand from the Haskell layer documentation, dante is not even used unless one explicitly sets `haskell-completion-backend` to `'dante`, so there doesn't seem to be a reason that spacemacs needs to be installing dante by default.

**Comment by JAremko** [comment]
@kini  I think we can mention in documentation that `dante` requires Emacs25 and simple disable the package otherwise.

**Comment by JAremko** [comment]
For now you can try simply [excluding package](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#exclusion)

**Comment by JAremko** [comment]
Should be ok now.  Also I asked `dante` devs if they can add Emacs24 support.  No harm in asking :wink:

**Comment by kini** [comment]
Thanks!

**Comment by JAremko** [comment]
Thanks for reporting :heart:
