### ISSUE TITLE
PYTHON LAYER NOT AUTO COMPLETING

### ISSUE THREAD

**Issue by martinffx** [syl20bnr/spacemacs#8986]
#### Description :octocat:
When I start editing a python file I'm not getting autocomplete suggestions. `company-mode` is not enabled automatically? `anaconda-mode` starts without an issue. When I manually enable company mode no suggestions pop up while typing, I have to manually invoke `M-x company-complete`

#### Reproduction guide :beetle:
- Start Emacs
- open python file

*Observed behaviour:* :eyes: :broken_heart:
- file opened in with python mode
- `company-mode` not automatically activated
- when I manually activate `company-mode`. `company-complete` not being run as I type.

*Expected behaviour:* :heart: :smile:
- `company-mode` to be activated with python mode
- suggestions to appear as I type

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(shell-scripts elm ruby nginx docker yaml elixir
               (javascript :variables tern-command
                           '("node" "/usr/local/bin/tern"))
               sql html rust markdown
               (python :variables python-test-runner 'nose python-enable-yapf-format-on-save t)
               helm emacs-lisp)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by rakyi** [comment]
You need to enable `auto-completion` layer by adding it to `dotspacemacs-configuration-layers` list in your `.spacemacs` file.

**Comment by martinffx** [comment]
Awesome! Thanks that sorted it.
