### ISSUE TITLE
New Eclim functionality

### ISSUE THREAD

**Issue by gabrielps** [syl20bnr/spacemacs#8987]
Could anyone add a shortcut in java layer of this new emacs-eclim functionality?
I don't know if this is the right place to ask for this, I would make a pull request, but I have 0 experience coding lisp.

https://github.com/emacs-eclim/emacs-eclim/issues/57#issuecomment-297521282
https://github.com/nloyola/emacs-eclim/commit/50ea6c5f6b2fb084a5a61ac882740557f29a19cc

**Comment by Beta1440** [comment]
I'll submit a pull request for this issue.
