### ISSUE TITLE
Smartparens is not documented anywhere

### ISSUE THREAD

**Issue by achikin** [syl20bnr/spacemacs#8988]
I personally got used to parinfer, but there is no layer for it, so I gave a try to the default spacemacs solution - smartparens. But I can't find any information on how to use smartparens inside spacemacs and standard keybindings do not work. How should I approach smartparens inside spacemacs?
![screen shot 2017-05-29 at 15 42 09](https://cloud.githubusercontent.com/assets/611419/26552007/fb553b72-448d-11e7-8fc1-18ad17318dfb.png)

**Comment by rakyi** [comment]
What are you trying to do? There is [lisp state](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#editing-lisp-code), [evil-surround](https://github.com/timcharper/evil-surround) and `%` to navigate between pairs in evil. Parinfer layer was added in develop lately.

I use smartparens only for automatic pair inserting. Also this kind of request/question is better suited for Gitter chat.

**Comment by achikin** [comment]
I was trying to use slurp/barf. Nevermind, I managed to set up parinfer from development branch, thank you.
