### ISSUE TITLE
`helm-jump-in-buffer` in react mode does not find any methods to jump to.

### ISSUE THREAD

**Issue by dre-hh** [syl20bnr/spacemacs#8989]
#### Description :octocat:
`helm-jump-in-buffer` in react mode does not find any methods to jump to.

#### Reproduction guide :beetle:
- Start Emacs
- enable react layer 
- create a jsx class component with several functions
(example copied frorm a redux guide below)
- run `helm-jump-in-buffer (SPC s j)` 

```jsx
import React from 'react'
import DayPicker, { DateUtils } from 'react-day-picker'
import {connect} from 'react-redux'
import {bindActionCreators} from 'redux'
import * as attendanceRecordActions from '../../actions/attendanceRecordActions'

class ScheduleContainer extends React.Component {
  componentDidMount() {
    if (this.props.attendanceRecords.length == 0) {
      this.props.actions.fetchAttendanceRecords()
    }
  }

  render() {
    return (
      < DayPicker
      locale='us'
      selectedDays={day => {
        DateUtils.isSameDay(new Date())
      }} />
    )
  }
}

function mapStateToProps(state, ownProps) {
  return {attendanceRecords: state.attendanceRecords}
}

function mapDispatchToProps(dispatch) {
  return {actions: bindActionCreators(attendanceRecordActions, dispatch)
}

export default connect(mapStateToProps, mapDispatchToProps)(ScheduleContainer)
```

*Observed behaviour:* :eyes: :broken_heart:
there is no outline lit of found functions

*Expected behaviour:* :heart: :smile:
In order to see the expected behaviour

- switch major mode to js2-mode
- run `helm-jump-in-buffer`

js2-mode finds the functions within the class and also the functions outside of it

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git html javascript markdown org osx syntax-checking react ruby version-control yaml
                 (org :variables org-enable-reveal-js-support t))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by JAremko** [comment]
[Imenu](https://github.com/syl20bnr/spacemacs/tree/develop/layers/+tools/imenu-list) (`b` `i`) doesn't work eather

helm-jump-in-buffer under the hood uses `helm-semantic-or-imenu`

```
Preconfigured helm for ‘semantic’ or ‘imenu’.
If ARG is supplied, pre-select symbol at point instead of current
semantic tag in scope.

If ‘semantic-mode’ is active in the current buffer, then use
semantic for generating tags, otherwise fall back to ‘imenu’.
Fill in the symbol at point by default.
```

You can request  better integration at `https://github.com/fxbois/web-mode`  

Alternatively you can use [`rjsx-mode`](https://github.com/felipeochoa/rjsx-mode) 

```
dotspacemacs-additional-packages '(rjsx-mode)
```
