### ISSUE TITLE
How to set multi-notes with helm-bibtex?

### ISSUE THREAD

**Issue by RanTaimu** [syl20bnr/spacemacs#8991]
Emacs 25.1.1, Ubuntu 16.04.2 LTS

I set the bibtex layer and followed the instruction of helm-bibtex:
```lisp
; bibtex layer
  (setq org-ref-default-bibliography '("~/Documents/Bibliography/references.bib")
        org-ref-pdf-directory "~/Documents/Bibliography/pdf/"
        ; The folder holds all the notes.
        org-ref-bibliography-notes "~/Documents/Bibliography/notes")

  (setq bibtex-completion-notes-path "~/Documents/Bibliography/notes")
  (setq bibtex-completion-notes-extension ".org")
  (setq bibtex-completion-library-path '("~/Documents/Bibliography/pdf"))
  (setq bibtex-completion-bibliography '("~/Documents/Bibliography/references.bib"))
```

But when I want to open a note w.r.t. a certain paper, it just open the 'notes' folder, rather than open a note in this folder automatically (The name of the note file is same as the Custom_ID of the paper).

**Comment by robbyoconnor** [comment]
Please close this and ask in the Gitter chat please. We have a cluttered issue tracker.

**Comment by robbyoconnor** [comment]
The issue tracker is not a forum.
