### ISSUE TITLE
key map is not restored after exit evil-evilified-state

### ISSUE THREAD

**Issue by enzochiau** [syl20bnr/spacemacs#8992]
Use 0.200.9025.1.8 with Emacs 25.2  (vim mode)

When exit edebug-mode, it should back to `evil-normal-state` from `evil-evilified-state`, but the keymap is not restarted which the `ESC` is still binded to `evil-evilified-state`. 

Reproduce:
1. Instruct any elisp function for edebug
2. Trigger edebug-mode
3. quit edebug-mode (goes to `evil-normal-state`)
4. press `ESC` (goes to `evil-evilified-state`, which should stay at `evil-normal-state`)

I think the `evilified-state-restore-normal-state-keymap` should be added to the state exit hook.

**Comment by Miciah** [comment]
Duplicate of #1874 and #7766.
