### ISSUE TITLE
Org-model M-S-Up & M-S-Down can't work well!

### ISSUE THREAD

**Issue by xushaobo** [syl20bnr/spacemacs#8996]
Can't swap with previous or next subtree of same level,in my spacemacs it just move line by  line up and down.

**Comment by swaroopch** [comment]
m-s-right & m-s-left is used for promoting or demoting the level of a heading.
m-up and m-down are used for moving up and down (swapping with next or previous subtree of same level).

Can you confirm the same?

**Comment by xushaobo** [comment]
Thanks for pointing out! Yes, indeed it's M-S-Up & M-S-Down I've fixed the issue's title.Can'you run the command correctly? For me it can't swap  the subtree of same level,instead it just move the line up or down,just acts like the command in normal mode "dd p"or "dd P".
