### ISSUE TITLE
Error enabling Flyspell mode

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#9]
Take care of the absence of `aspell`.

**Comment by Profpatsch** [comment]
If `aspell` is not installed in PATH, there is a startup lag of a few seconds.

**Comment by robbyoconnor** [comment]
I think it's a safe assumption people understand the basics of configuring PATH -- which is a **user** variable....so if `aspell` is not in the PATH -- add it...

**Comment by syl20bnr** [comment]
I believe it should be fixed in develop, we don't enforce aspell anymore.

**Comment by Profpatsch** [comment]
@robbyoconnor Yes, but I don’t want it.

**Comment by robbyoconnor** [comment]
@Profpatsch, see [this comment](https://github.com/syl20bnr/spacemacs/issues/9#issuecomment-136360694)

**Comment by Profpatsch** [comment]
Seems to be fixed after my last update.
