### ISSUE TITLE
Minibuffer is large (~10 lines) when set to maximize on start

### ISSUE THREAD

**Issue by shaunpatel** [syl20bnr/spacemacs#9000]
#### Description :octocat:
After updating to the latest version of spacemacs, spacemacs open with the minibuffer size ~10 lines instead of the usual 1. This appears to be related to the 'maximize on start' setting. If I remove this setting, or set it to full-screen on start, the minibuffer appears normally.

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Minibuffer is larger (~10 lines)

*Expected behaviour:* :heart: :smile:
Minibuffer is one line.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-private-snippets-directory nil auto-completion-enable-help-tooltip t)
 better-defaults csv dash emacs-lisp ess extra-langs evernote ibuffer ipython-notebook
 (latex :variables latex-enable-auto-fill nil :variables latex-enable-folding t)
 git markdown org osx pandoc
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 python ranger semantic speed-reading spell-checking syntax-checking themes-megapack version-control)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by JAremko** [comment]
@shaunpatel   Do you have the issue with the develop branch?
