### ISSUE TITLE
`cider` layer does not work as expected due to missing dependency

### ISSUE THREAD

**Issue by otwieracz** [syl20bnr/spacemacs#9001]
#### Description :octocat:

`clj-refactor` needed by `clojure` layer requires `seq-25` which is not available.

#### Reproduction guide :beetle:
- Add `clojure` layer
- Start Emacs
- Try `clojure-jack-in`

*Observed behaviour:* :eyes: :broken_heart:

```
Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "seq-25")
  require(seq-25)
  (if (fboundp (quote seq-map-indexed)) nil (require (quote seq-25)))
  eval-buffer(#<buffer  *load*> nil "/home/otwieracz/.emacs.d/elpa/clj-refactor-20170520.323/clj-refactor.el" nil t)  ; Reading at buffer position 1675
  load-with-code-conversion("/home/otwieracz/.emacs.d/elpa/clj-refactor-20170520.323/clj-refactor.el" "/home/otwieracz/.emacs.d/elpa/clj-refactor-20170520.323/clj-refactor.el" nil t)
  require(clj-refactor)
  eval((require (quote clj-refactor)) nil)
  eval-expression((require (quote clj-refactor)) nil)
  funcall-interactively(eval-expression (require (quote clj-refactor)) nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

I've opened issue here: https://github.com/clojure-emacs/clj-refactor.el/issues/379 but author suggests that `seq.el` included with `emacs-25.2` is still too old and I should reinstall: https://github.com/NicolasPetton/seq.el.

Possible solution: Add this seq.el to list of required packages to make `(require 'seq-25)` available in Spacemacs.

*Expected behaviour:* :heart: :smile:

Cider starts fine.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(csv better-defaults emacs-lisp git org
     (shell :variables shell-default-term-shell "/bin/bash" shell-enable-smart-eshell t shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
     version-control common-lisp clojure erlang themes-megapack theming syntax-checking javascript react latex restclient ess
     (ruby :variables ruby-enable-enh-ruby-mode t)
     (c-c++ :variables c-default-style "bsd" c-basic-offset 4)
     (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
     imenu-list github)
```
- System configuration features: XPM JPEG TIFF GIF PNG NOTIFY ACL GNUTLS FREETYPE XFT ZLIB X11

**Comment by JAremko** [comment]
Hmm @syl20bnr  should we have Emacs 25.2 tag? Or mb Emacs 25? :thinking:

**Comment by fmjrey** [comment]
I think I'm hit by this one, since upgrading to emacs 25.
Is there a fix/workaround I can apply to my setup, other than reverting to a previous emacs version?

**Comment by akaivola** [comment]
Workaround this issue by opening up clj-refactor.el from /elpa/clj-refactor-20180316.1000/clj-refactor.el and replace these lines:
```
(unless (fboundp 'seq-map-indexed)
  (require 'seq-25))
```

with the seq-map-indexed function lifted from seq-25.el:
```
(defun seq-map-indexed (function sequence)
  "Return the result of applying FUNCTION to each element of SEQUENCE.
Unlike `seq-map', FUNCTION takes two arguments: the element of
the sequence, and its index within the sequence."
  (let ((index 0))
    (seq-map (lambda (elt)
               (prog1
                   (funcall function elt index)
                 (setq index (1+ index))))
             sequence)))
```

**Comment by eallik** [comment]
for the rookies (such as myself): you also need to delete the compiled `.elc` files in that directory.

**Comment by kommen** [comment]
The upstream issue has been closed: https://github.com/clojure-emacs/clj-refactor.el/issues/379

I think this issue also can be closed.
