### ISSUE TITLE
Bad theming in terminal clients (server/client)

### ISSUE THREAD

**Issue by y-usuzumi** [syl20bnr/spacemacs#9002]
#### Description :octocat:
Start the server in terminal. Now starting clients in terminal works fine.
However, after starting a client in GUI mode, subsequent terminal clients receive bad theming. See screenshots below.

#### Reproduction guide :beetle:
- (I'm using material theme)
- Run `emac --daemon` in gnome-terminal.
- Run `emacsclient -t` in gnome-terminal (Now everything works fine, as in the following screenshot).
![2017-05-31 17-29-21](https://cloud.githubusercontent.com/assets/1560189/26625460/c738325e-45b9-11e7-927b-8f59ac756148.png)

- Run `emacsclient -c`.
- Can observe a blink between terminal theming and GUI theming (they do have subtle differences instrinsically). Eventually looks as follows:
![2017-05-31 17-31-15](https://cloud.githubusercontent.com/assets/1560189/26625655/673f1e52-45ba-11e7-8a82-824aa1e2fb71.png)

- Now run `emacsclient -t` in gnome-terminal.

*Observed behaviour:* :eyes: :broken_heart:
![2017-05-31 17-31-33](https://cloud.githubusercontent.com/assets/1560189/26625674/724848be-45ba-11e7-8d5c-b49d485219b9.png)

*Expected behaviour:* :heart: :smile:
![2017-05-31 17-29-21](https://cloud.githubusercontent.com/assets/1560189/26625732/9ef42626-45ba-11e7-9c26-492f9672c4e1.png)

OR

![2017-05-31 17-35-39](https://cloud.githubusercontent.com/assets/1560189/26625736/a45c7d5c-45ba-11e7-98f3-338c838f5947.png)

Either one, as I'm not sure.

#### Backtrace :paw_prints:
```
Nothing

**Comment by LdBeth** [comment]
Do you have multiple Emacs installed?

**Comment by y-usuzumi** [comment]
@LdBeth No. This Emacs comes from Gentoo portage, version 25.2

**Comment by y-usuzumi** [comment]
@LdBeth 小伙emacs-china的啊，可以说中文_(:з」∠)_

**Comment by LdBeth** [comment]
It seems `create-new-frame` command would do some "destructive" configs to the UI.

有一些针对图形界面的设置钩在了新建图形界面窗口上，你在 `emacsclient -c` 的时候导致这些配置生效，再次从终端连接界面就不一样了。

**Comment by y-usuzumi** [comment]
@LdBeth I see. That's sad. Maybe I'll checkout if it's plausible to start two servers and connect terminal/GUI clients to either one.

**Comment by planigan** [comment]
I start two named daemons for this reason.
```
emacs --daemon=gui
emacs --daemon=term
```
Then I connect with either `emacsclient -s gui -c` or `emacsclient -s term -t`.

**Comment by y-usuzumi** [comment]
@planigan That's a neat solution thank you!
