### ISSUE TITLE
can't get rid of error window on boot up

### ISSUE THREAD

**Issue by vigilancetech-com** [syl20bnr/spacemacs#9003]
#### Description :octocat:
if there are errors when starting you can't get rid of the error window
#### Reproduction guide :beetle:
- Start Emacs
- position cursor in error window
- hit C-x 1 or SPC w m and it says: "Cannot make side window the only window" in the mini-buffer
- position cursor in another window (e.g. the SE "home" buffer) and try it again and nothing happens
*Observed behaviour:* :eyes: :broken_heart:
error window doesn't disappear and two behaviors described above are observed
*Expected behaviour:* :heart: :smile:
window cursor is in becomes only one visible
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm themes-megapack auto-completion better-defaults emacs-lisp git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control)
```

#### Backtrace :paw_prints:

**Comment by JAremko** [comment]
If you get error while starting up you are pretty much screwed anyway :thinking:
