### ISSUE TITLE
Spacemacs not loading properly

### ISSUE THREAD

**Issue by Vm900** [syl20bnr/spacemacs#9005]
Hi,
Just installed spacemacs and this is what i'm getting:

![spacemacemacserror](https://cloud.githubusercontent.com/assets/9399631/26648495/91981c46-463a-11e7-8609-b37053f3fd21.PNG)

What could've possibly gone wrong?
Help.
Thanks

**Comment by bsvercl** [comment]
Do you have the Source Code Pro font installed? Spacemacs uses it by default.

**Comment by Vm900** [comment]
Yes i installed the fonts prior to installing spacemacs

**Comment by Vm900** [comment]
I have a screen-shot of the fonts on my system:

![fontsinstalled](https://cloud.githubusercontent.com/assets/9399631/26689725/929081a6-46ee-11e7-879e-0b002971f7f0.PNG)

**Comment by Vm900** [comment]
Solved it by installing the ones from here https://github.com/adobe-fonts/source-code-pro/releases/tag/2.010R-ro%2F1.030R-it

Cheerios
