### ISSUE TITLE
[Severe] OSX Layer Breaks Page Up/Down!

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#9006]
#### Description :octocat:
Function + up/downarrow to do Page up/page down doesn't work AT ALL when the "osx" layer is enabled.

#### Reproduction guide :beetle:
- Enable the "osx" layer on latest develop
- Start Emacs on macOS (I'm using the Railwaycat port).
- Press fn+up/down (for page up/page down)

*Observed behaviour:* :eyes: :broken_heart:
The regular downarrow/uparrow gets triggered and just moves a single line.

*Expected behaviour:* :heart: :smile:
It should obviously move a whole page (since the keys are page up/page down). If I disable the "osx" layer, the page up/page down keys work again. This bug was added pretty recently (I just updated Spacemacs and ALL packages for the first time in a few months).

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 0e0e90e5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asm c-c++ csv emacs-lisp html javascript lua markdown org php python shell-scripts sql vimscript windows-scripts helm
     (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-help-tooltip nil auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory
                      '("~/.spacemacs.d/snippets/" "~/.spacemacs.d/snippets-default/"))
     ibuffer imenu-list
     (git :variables git-magit-status-fullscreen t)
     (colors :variables colors-colorize-identifiers 'all colors-default-rainbow-identifiers-sat 50 colors-default-rainbow-identifiers-light 65)
     (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/bin/bash" shell-default-height 30 shell-default-position 'bottom)
     semantic syntax-checking)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by SteveJobzniak** [comment]
I found the exact bug commit:

https://github.com/syl20bnr/spacemacs/commit/5ff0fbe6d9caa07796d40d066a74e5230e46d33d

It adds some code which `(defvar osx-function-as 'none`, which in turn gets mapped to the real internal variable `(osx-function-as      . mac-function-modifier)`... The problem is, `'none` is literally telling the Emacs binary to UNBIND the function key so that it does NOTHING.

So fn + uparrow/downarrow to trigger pageup/pagedown actually does a regular uparrow/downarrow, since the code above DISABLES the fn key COMPLETELY.

The correct value for keeping function behavior as-is, is `(setq mac-function-modifier nil)`... So whatever you need to do to fix that in this layer package will fix it. I guess making it default to nil or something...

This is a critical bug. It totally breaks the FN key.

**Comment by SteveJobzniak** [comment]
A lot of other things in that diff look VERY suspicious.

For example:

```emacs-lisp
+(defvar osx-right-control-as 'left
 +  "Sets the key binding of the `RIGHT CONTROL' key on OSX.
 +   Possible values are `super' `meta' `hyper' `alt' `left' `none'.
 +   Default: `left'.")
 +(defvar osx-right-command-as 'left
 +  "Sets the key binding of the `RIGHT COMMAND' key on OSX.
 +   Possible values are `super' `meta' `hyper' `alt' `left' `none'.
 +   Default: `left'.")
 +(defvar osx-right-option-as 'left
 +  "Sets the key binding of the `RIGHT OPTION' key on OSX.
 +   Possible values are `super' `meta' `hyper' `alt' `left' `none'.
 +   Default: `left'.")
```

What's it doing defining the control keys etc as "left"? Huh?

**Comment by SteveJobzniak** [comment]
For my personal config I fixed it and restored function behaviors like this:

```emacs-lisp
     (osx :variables
          osx-command-as 'super
          osx-option-as 'meta
          osx-control-as 'control
          osx-function-as nil)
```

That last line is the important part. The "nil" means "leave the key alone as its default GUI Emacs behavior, which preserves the function key.

So I guess the necessary fix is changing the osx-function-as variable default to nil.

**Comment by JAremko** [comment]
@syl20bnr probably uses this layer so he should know.
