### ISSUE TITLE
s/a/b/g doesn't use "g" flag to substitute all

### ISSUE THREAD

**Issue by psprint** [syl20bnr/spacemacs#9008]
#### Description :octocat:
If I have in source e.g.:
static char *type_names[7] = { "invalid", "string", "list", "set", "sorted-set", "hash", "error" };

and do:
- :%s/set/myset/g
- select line with V (visual mode), do :s/set/myset/g

Then in first case: only first match in whole buffer is replaced
In second case: only first match in selected line is replaced

#### Reproduction guide :beetle:
- Start Emacs
- paste: static char *type_names[7] = { "invalid", "string", "list", "set", "sorted-set", "hash", "error" };
- do :%s/set/myset/g

*Observed behaviour:* :eyes: :broken_heart:
First match is replaced, and replace ends. This happens only in normal run, if I use --terminal /dev/tty, I get correct behavior.

*Expected behaviour:* :heart: :smile:
All matches should be replaced because of "g" flag. Also, without the flag, whole buffer should be processed, doing single match per line. Observed is single match per buffer.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(themes-megapack c-c++ helm auto-completion emacs-lisp git markdown)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Stebalien** [comment]
What's the value of your `dotspacemacs-ex-substitute-global` setting? If it's non-nil, the meaning of `g` is inverted.
