### ISSUE TITLE
Enable Ido for M-x

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#901]
It's odd to see that `C-x C-f` has Ido enabled but not `M-x`. We should set it to use Ido by default (not `smex` unless a user add).

**Comment by syl20bnr** [comment]
Smex is used even when the layer is not added ?

**Comment by tuhdo** [comment]
No, it is not used.

**Comment by syl20bnr** [comment]
Oh I see, you are right. What is needed to use Ido for `M-x` ?

**Comment by syl20bnr** [comment]
mmmh I think it should be helm for `M-x` by default.

**Comment by tuhdo** [comment]
Agreed. We should bind `helm-M-x` to `M-x` to avoid external dependencies. Either `helm-M-x` or `smex` is a better replacement for stock `M-x`.

**Comment by syl20bnr** [comment]
After the last commits in develop we have:
- by default everything default to `helm-M-x`
- if a user adds the smex layer then it will be Ido + smex instead (there was a bug previously where the smex layer did not work :-( )

**Comment by tuhdo** [comment]
Nice.
