### ISSUE TITLE
when my git repo very large， open the file very slow

### ISSUE THREAD

**Issue by xianyo** [syl20bnr/spacemacs#9019]
I have a project，very large.  with the git,  then spacemacs open the file very slow.

when in my project. i move the .git to .git_bak.  then spacemacs open the file fast.

**Comment by JAremko** [comment]
Can you elaborate? Also do `SPC` `h` `I` and post the report here.

**Comment by xianyo** [comment]
ok for this 

(setq vc-handled-backends ())

https://stackoverflow.com/questions/5748814/how-does-one-disable-vc-git-in-emacs
