### ISSUE TITLE
Rust autocompletion

### ISSUE THREAD

**Issue by jvillasante** [syl20bnr/spacemacs#9023]
I'm having some trouble making the rust layer work. I installed racer, added the path variables, tried it on the terminal and it works, however, emacs is not auto-completing. Here's a simple use case:
```
let arr = [1, 2, 3, 4, 5];
println!("length={}", arr.l[only get snippets completion here, not the len() I'm looking for]);
```

Just trying Rust for the first time, maybe I'm missing something?

**Comment by swaroopch** [comment]
Please use `SPC h I` to provide full bug report and system info, so that the community can help you.

**Comment by jvillasante** [comment]
#### Description :octocat:
rust layer auto completion doesn't seem to work correctly.

#### Reproduction guide :beetle:
- Start Emacs
- Create a rust file (test.rs) and enter the following:
```
  let arr = [1, 2, 3, 4, 5];
  println!("length={}", arr.l);
```

*Observed behaviour:* :eyes: :broken_heart:
When I type `arr.l` I would expect the completion to show `len()`.

*Expected behaviour:* :heart: :smile:
I only see completion candidates for snippets not related to the array.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :variables auto-completion-return-key-behavior 'nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory "~/.spacemacs.d/snippets" auto-completion-enable-help-tooltip 'manual auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t :disabled-for org erc git markdown eshell ledger text)
 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary nil)
 syntax-checking nlinum emacs-lisp
 (git :variables git-use-magit-next t git-enable-github-support t)
 version-control
 (org :variables org-enable-github-support t)
 (markdown :variables markdown-italic-underscore t)
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 (shell :variables shell-default-term-shell "/bin/zsh" shell-default-shell 'ansi-term shell-default-position 'bottom shell-default-height 30)
 shell-scripts search-engine evil-commentary
 (html :variables css-indent-offset 2 web-mode-code-indent-offset 2 web-mode-markup-indent-offset 2 web-mode-css-indent-offset 2)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 rust common-lisp csv deft
 (elfeed :variables rmh-elfeed-org-files
         (list
          (concat my-dropbox-path "/Personal/elfeed/elfeed.org")))
 (mu4e :variables mu4e-installation-path my-mu4e-path mu4e-enable-notifications nil mu4e-enable-mode-line t mu4e-alert-interesting-mail-query "")
 slack jv jv-cpp jv-deft jv-dired jv-elfeed jv-ivy jv-lisp jv-magit jv-mu4e jv-org jv-slack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES


#### Backtrace :paw_prints:

**Comment by letheed** [comment]
AFAIK, this is a limitation of racer, not a problem with the layer.
Racer can have trouble discovering methods provided through `Deref` or coercions and related to literal types, probably because this is part of the language and not just declared in the stdlib as with most code. Some of it has been fixed (like `str` methods on `String` I think) but not all of it.

This issue should be closed.

**Comment by jvillasante** [comment]
Yeah, that's what I've gathered! Thanks!
