### ISSUE TITLE
"SPC sf" no longer works

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#9025]
#### Description :octocat:

`SPC sf` no longer works.

#### Reproduction guide :beetle:
- Start Emacs
- Open a file, type `SPC sf`, choose a directory you'd like to search in, and
  type some search terms that should be present in some of the files in the
  directory. 
  
Seems to be any recent version of spacemacs, I can observe the behavior even on
the web based spacemacs on http://spacemacs.org.  

This used to work, so is a regression somewhere.

*Observed behaviour:* :eyes: :broken_heart:
Search results are blank.

*Expected behaviour:* :heart: :smile:
Search results are search results.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv lua nginx sql auto-completion emacs-lisp git yaml javascript html markdown extra-langs python org osx python ipython-notebook django syntax-checking spell-checking colors spacemacs-layouts vimscript helm
     (version-control :variables version-control-diff-tool 'diff-hl)
     (c-c   :variables c-c  -enable-clang-support t)
     (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by JAremko** [comment]
@synic  I seems to work as intended [spacemacs/helm-files-smart-do-search ](https://github.com/syl20bnr/spacemacs/blob/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/layers/%2Bcompletion/helm/packages.el#L246)
```
Search in opened buffers using `dotspacemacs-search-tools'.
Search for a search tool in the order provided by `dotspacemacs-search-tools'
If DEFAULT-INPUTP is non nil then the current region or symbol at point
are used as default input.
```
It successfully finds patterns in open buffers.

- - - - - -

I will mark it as `as expected :P` until proven otherwise :smile:

**Comment by synic** [comment]
@JAremko Then what is this supposed to be doing differently?  https://github.com/syl20bnr/spacemacs/blob/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/layers/%2Bcompletion/helm/packages.el#L298

`SPC sb` should be search open buffers.

**Comment by JAremko** [comment]
[`spacemacs/helm-buffers-smart-do-search `](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+completion/helm/packages.el#L327)
```
Search in opened buffers using `dotspacemacs-search-tools'.
Search for a search tool in the order provided by `dotspacemacs-search-tools'
If DEFAULT-INPUTP is non nil then the current region or symbol at point
are used as default input.
```

[`spacemacs/helm-files-smart-do-search`](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+completion/helm/packages.el#L261)
```
Search in opened buffers using `dotspacemacs-search-tools'.
Search for a search tool in the order provided by `dotspacemacs-search-tools'
If DEFAULT-INPUTP is non nil then the current region or symbol at point
are used as default input.
```

@synic  Definitely looks like a severe case of copy-paste :thinking:

**Comment by JAremko** [comment]
@justbur  What is going on in there?

**Comment by JAremko** [comment]
I'll mark it as a bug because at least doc-strings should not be the same for the two different functions

**Comment by rakyi** [comment]
Works as intended for me using `ag`:  `SPC s f` in files, `SPC s b` in buffers. Seems that only the docstring is wrong.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior nil auto-completion-enable-help-tooltip 'manual)
 c-c++ csv docker
 (elm :variables elm-format-on-save t elm-sort-imports-on-save t)
 emacs-lisp finance git gtags
 (haskell :variables haskell-enable-hindent-style "johan-tibell" haskell-process-type 'stack-ghci haskell-completion-backend 'ghci)
 helm html javascript latex
 (markdown :variables markdown-live-preview-engine 'vmd)
 org php python
 (ranger :variables ranger-show-preview t)
 semantic
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts spell-checking syntax-checking version-control yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by JAremko** [comment]
@synic  On Linux it seems to use `grep` and works fine with folders.  Mb you are missing a search tool? 

@rakyi  thx.  

Someone need to fix the docstring. :roll_eyes:

**Comment by synic** [comment]
I have my search util set to `ag`, and it works fine for searching the project.  Just not dirs.

**Comment by JAremko** [comment]
@synic  Try asking at [Gitter](https://gitter.im/syl20bnr/spacemacs). Mb someone with MacOS had similar problems :thinking:

**Comment by synic** [comment]
Did you try using it on the online editor?  It happens there, I'm fairly sure that's not MacOS.

**Comment by JAremko** [comment]
@synic  online editor has strange BusyBox grep:

![](http://i.imgur.com/FLxjVfH.png)

You may need some king of  GNU/Grep executable for Mac OS. Have no idea :thinking:

**Comment by synic** [comment]
I'll see what I can find, thanks!

**Comment by zhexuany** [comment]
`brew install grep --with-default-names` did the trick. So, we should probably update README somehow in case of people running into this issue again and again.

**Comment by duianto** [comment]
The following PR is now on the `develop` branch:
Add a note on grep prerequisite in the README #11685
