### ISSUE TITLE
Add new use-package keywords `:evil` and `:holy`

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#903]
use-package will support keyword extension in a near future. We will be able to add new keywords:
- `:evil-init` and `:evil-config`
- `:holy-init` and `:holy-config`

It will make the code easier to understand and navigate.

**Comment by StreakyCobra** [comment]
@syl20bnr Any news on this?

**Comment by TheBB** [comment]
Use-package already supports this so it's just up to us now.

**Comment by CarlQLange** [comment]
I added a PR with these changes: #9587. I have no idea if this is still desired or useful, but hey! Maybe it is!

**Comment by syl20bnr** [comment]
This request is out-date, @CarlQLange I'm sorry it stayed open for so long.
