### ISSUE TITLE
How to jump to error indicated by “Semantic Issue: use of undeclared identifier”?

### ISSUE THREAD

**Issue by tddsg** [syl20bnr/spacemacs#9039]
Hi,

When writing C++ code, I notice that Spacemacs can notify undeclared variables, by a message like `Semantic Issue: use of undeclared identifier...`

For example, for the following code, there will be an error indication at y, and the message `Semantic Issue: use of undeclared identifier "y"`.

```
void foo() {
   int x = y;  // <-- error indication at 'y'
}

```

So, I'd like to ask how can I quickly jump to the location of `y`? What is the shortcut key or the function of Emacs to do this job?

Thanks for spending time looking at my issue.

**Comment by JAremko** [comment]
Have you tried `SPC` `e` `n` ? Also  `SPC` `e` `L` can be really helpful.

**Comment by tddsg** [comment]
I tried both `flycheck-next-error` and `next-error` but they don't work.
Maybe it relates to the `semantic` mode?

**Comment by robbyoconnor** [comment]
We need to make it such that it's crystal clear people don't use this as a replacement for visiting the chat...

**Comment by JAremko** [comment]
Posting questions here is ok (that is why we have forum tag) When @syl20bnr 's community portal will be done we may be able to simply export and close issues marked as `forum` or `discussion` (this is my guess) and clean up Github tracker

**Comment by robbyoconnor** [comment]
So long as you're not having issues -- Why don't we deploy Discourse?

**Comment by JAremko** [comment]
@robbyoconnor  @syl20bnr  has a plan. And it is secret. We only know that he has one :shipit:

**Comment by tddsg** [comment]
Just a quick update for the error “Semantic Issue: use of undeclared identifier”, I found out that it was reported by [Rtags](https://github.com/Andersbakken/rtags)

**Comment by Miciah** [comment]
@tddsg, does `M-x` `rtags-cycle-through-diagnostics` perform the desired action?

`rtags-cycle-through-diagnostics` is the new name for `rtags-cycle-through-overlays-on-screen`.  Spacemacs still binds `SPC m g Y` to the old name, but once #11026 merges, you should be able to use `SPC m g Y` to perform this command.

**Comment by Miciah** [comment]
Update: #11026 has been merged, so `SPC m g Y` should work.
