### ISSUE TITLE
Haskell mode cannot find ghci

### ISSUE THREAD

**Issue by raventid** [syl20bnr/spacemacs#9040]
#### Description :octocat:
I'm trying to start a repl in haskell mode and constantly get an error message -> `No such file or directory, ghci`
My haskell setup consist of a `stack` and I have not installed `ghc` or `ghci` directly.

I've tried to leave a hint for a haskell mode to use `stack ghci` as described in readme for this mode, later I've tried to  alias `stack ghci` -> `ghci` and neither helped.

I've tried to use both `master` and `develop` branches.

#### Reproduction guide :beetle:
- Start Emacs
- Create plain haskell file with simple content:
  ```
  module Print where

  main :: IO ()
  main = putStrLn "Hello world!"
  ```
- Try to call any repl command with `SPC m s *`

*Observed behaviour:* :eyes: :broken_heart:
`No such file or directory, ghci`
After this emacs becomes irresponsive and shows a message -> The Haskell process `haskell` has died. Restart?(...)
`y,n` or any other option lead to this message again.

*Expected behaviour:* :heart: :smile:
See running REPL

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(haskell clojure html ruby rust helm emacs-lisp)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB

#### Backtrace :paw_prints:
```
---
```

**Comment by JAremko** [comment]
@raventid  mb this will help you https://github.com/serras/emacs-haskell-tutorial/issues/51 (close the issue if it helped)

**Comment by raventid** [comment]
@JAremko thank you for this link. I'll try to find a solution and will report it here asap.

**Comment by raventid** [comment]
I found the solution in this issue -> https://github.com/haskell/haskell-mode/issues/953

I don't completely understand every line of that config, but it's nice)) My problem was that haskell-mode didn't understand that I'm using stack, this helped.

Closing this.
