### ISSUE TITLE
Is it possible to source another file in my .spacemacs?

### ISSUE THREAD

**Issue by Azphreal** [syl20bnr/spacemacs#9043]
I was wondering if it's possible to segment my .spacemacs a bit to make it slightly more readable. For example, I currently have six or seven functions defined for org-mode macros and they take up a decent amount of space. I want to be able to move them to, say, `org-macros.el` or something, and have my .spacemacs call that file during user-config. Is this possible?

Sorry if this seems like an obvious answer, never used Lisp or Emacs before having used Spacemacs.

**Comment by JAremko** [comment]
I can use [~/.spacemacs.d](https://github.com/syl20bnr/spacemacs/blob/master/doc/QUICK_START.org#dotdirectory-spacemacsd) for this. Put your stuff there in files and [load them](https://www.emacswiki.org/emacs/LoadingLispFiles)

[I recommend  you reading this article](http://thume.ca/howto/2015/03/07/configuring-spacemacs-a-tutorial/)

**Comment by Azphreal** [comment]
Thanks, that's exactly what I was looking for.

**Comment by JAremko** [comment]
@Azphreal  nice example https://github.com/aaronjensen/spacemacs.d
