### ISSUE TITLE
Don't add node_modules automatically to the `exec-path`

### ISSUE THREAD

**Issue by houli** [syl20bnr/spacemacs#9047]
A recent commit https://github.com/syl20bnr/spacemacs/commit/09ce56df3defd20374040642ce8df43438d79b3 enabled adding `node_modules` to `$PATH` automatically. While it does solve the problem of npm binaries it also introduces security risks.
[This SO comment](https://stackoverflow.com/questions/9679932/how-to-use-package-installed-locally-in-node-modules#comment33532258_9683472) probably explains the risk enough.

**Comment by JAremko** [comment]
@jupl  @TheBB  :thinking:

**Comment by jupl** [comment]
- Currently it can be disabled by adding `add-node-modules-path` to `dotspacemacs-excluded-packages` to address it right now.
- I can rewrite it so there can be some kind of flag with it disabled by default. I would just need to be pointed in the right direction to do that that follows Spacemacs conventions. It would be ideal to have a single option to turn it on or off.

**Comment by TheBB** [comment]
We can add a layer variable to enable it that defaults to nil. Should be reported upstream though.

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/commit/65f639d8c4ca528d101b3e55d11ef7c5ded5514c

**Comment by tko** [comment]
FWIW I tried more focused approach in https://github.com/tko/spacemacs/commit/1e66dfc0138c6a5337d3d9fb89466bb6dbe5573a, something one might be comfortable enough to enable by default.

**Comment by deb0ch** [comment]
@tko what differentiates your approach from `add-node-modules-path`'s, and what makes it more secure ?

Beside that your implementation looks more concise from afar, I don't see any fundamental differences by just looking at it quickly.

**Comment by deb0ch** [comment]
Using `npm bin` seems like the cleanest, most secure option. On my computer running the command from a terminal takes 0.21s to 0.24s. Didn't time `add-node-modules-path` though.

**Comment by deb0ch** [comment]
I would also like to point out that it was somewhat troublesome getting eslint ready after activating the javascript layer, as I would have expected it to be active right away like in any decent IDE. 

It is true that I hadn't read the docs carefully enough at first, but in other IDEs there is no need to read any docs to get such a thing ready.

**Comment by deb0ch** [comment]
Update: reported upstream

**Comment by tko** [comment]
@deb0ch the main difference is that where `add-node-modules-path` modifies `PATH` so that _everything_ in node_modules/bin gets precedence -- not only when running flycheck/eslint but anything and everything(?) started by emacs from there on (probably bad if there's a `cp`, `ls`, or something like that in node_modules) -- I'm _only_ modifying `flycheck-javascript-eslint-executable` (and similar) variables so _only_ flycheck is affected and _only_ when it's running `eslint`

It should be safer as only flycheck/eslint is affected; not dired (ls), not tramp (ssh?), and _every_ emacs feature that relies on running executables.

**Comment by kreedz** [comment]
@tko, I've looked at tko@1e66dfc, can you make separate package for that?

**Comment by tko** [comment]
@kreedz I've no clue how to make melpa packages, and my engagement with elisp is seldom and random at best and I'd rather not pretend otherwise.
