### ISSUE TITLE
Remap org-attach

### ISSUE THREAD

**Issue by Stebalien** [syl20bnr/spacemacs#9050]
The `org-attach` menu is currently mapped to `,ia` (mnemonic "insert attachment"). However, the `org-attach` menu is used for:

* Inserting attachments
* Opening attachments
* Deleting attachments

etc...

Therefore, it should probably go under `,A` (or maybe `,f` ("org file")?). Unfortunately, `,a` is taken by `org-agenda`.

**Comment by phss** [comment]
Looks like `,A` is taken as well, by `org-archive-subtree`. Any suggestions for an alternative binding? Unless `org-archive-subtree` could be moved somewhere else.

**Comment by Beta1440** [comment]
`org-archive-subtree` should be moved to `,Sa` (subtree archive) so that `org-attach` can be `,A`.

**Comment by Stebalien** [comment]
`org-archive-subtree` was remapped to `,sa` in 4898644a954f2883a134a1ef7327c0ba32d98bed.

**Comment by Stebalien** [comment]
Fixed.
