### ISSUE TITLE
Error installing package (wrong-type-argument number-or-marker-p nil)

### ISSUE THREAD

**Issue by Azphreal** [syl20bnr/spacemacs#9052]
#### Description :octocat:
Unable to install packages using custom `init.el`

#### Reproduction guide :beetle:
- Create new virtual machine for testing and install Emacs 25.2.1
- Link existing `spacemacs.d` directory to `.spacemacs.d` containing `init.el`, some defined functions and yas-snippets
- Start Emacs
- Spacemacs attempts to install packages
- Most packages fail with (error: (wrong-type-argument number-or-marker-p nil))
- Messages buffer shows these failed packages with "Installing..." but no extracting or writing afterwards, since they throw an error

*Observed behaviour:* :eyes: :broken_heart:
Packages don't install, and Spacemacs throws numerous errors about the missing packages (e.g., symbol function definitions are void because the package doesn't exist). Packages don't seem to have any consistency; include org-mode, magit, git-gutter, flycheck, color-identifiers. Most user config fails.

*Expected behaviour:* :heart: :smile:
Packages should install normally.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm better-defaults syntax-checking version-control auto-completion git markdown org emacs-lisp rust pandoc latex bibtex
      (latex :variables latex-enable-auto-fill t)
      (colors :variables colors-colorize-identifiers 'variables))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

**Comment by CeleritasCelery** [comment]
You shouldn't change `init.el`. If you want to add new packages use `dotspacemacs-additional-packages`

**Comment by Azphreal** [comment]
Should specify that its full path is `$HOME/.spacemacs.d/init.el`. I asked a few days ago on fragmenting my `.spacemacs` and was told that this method was recommended. It works completely fine on another machine, it's only when it has to bulk install (100+ packages) that this seems to happen.

**Comment by JAremko** [comment]
@Azphreal Can you upload your .spacemacs.d to GitHub?

**Comment by JAremko** [comment]
You can use https://github.com/aaronjensen/spacemacs.d as an example

**Comment by Azphreal** [comment]
Uploaded [here](https://github.com/Azphreal/spacemacs.d).

**Comment by JAremko** [comment]
@Azphreal  Your [`dotspacemacs/init`](https://github.com/Azphreal/spacemacs.d/blob/master/init.el#L43) seems to me busted.  You can get proper one from  [`.spacemacs.template`](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/.spacemacs.template#L70) It should work then.

**Comment by Azphreal** [comment]
I'd only changed a few variables. I set most of them back to default, so I'm not sure what the actual issue is. I can install packages again, but now I'm also getting #9009.

**Comment by JAremko** [comment]
@Azphreal  Welp. I replaced your `dotspacemacs/init` with the default one and it worked.  You can try doing this and then narrow down.

**Comment by Azphreal** [comment]
Worked out why I was getting a theme issue. One of the colour schemes had set a `custom-faces` at the end of my init and was obviously overriding everything. Everything's good now.
