### ISSUE TITLE
Dired `open-file-or-directory-in-extern` on `.` (current dir) returns `No file on this line` occasionally

### ISSUE THREAD

**Issue by spacegoing** [syl20bnr/spacemacs#9058]
<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-c C-c` TO SUBMIT>>
#### Description :octocat:
Dired `open-file-or-directory-in-extern` on `.` (current dir) 
returns `No file on this line` occasionally

#### Reproduction guide :beetle:

*Observed behaviour:* :eyes: :broken_heart:
- Open a dir in `dired`
- move cursor on `.`  (current dir) 
- strike `SPC-f-o`
- sometimes it warns `No file on this line`

*Expected behaviour:* :heart: :smile:

Open this dir in finder

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby yaml octave auto-completion better-defaults emacs-lisp git semantic github sql c-c++ python html javascript org docker php markdown
      (markdown :variables markdown-live-preview-engine 'vmd)
      pandoc latex
      (latex :variables latex-enable-auto-fill t)
      (latex :variables latex-build-command "LaTeX")
      (latex :variables latex-enable-folding t)
      spell-checking syntax-checking)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by bmag** [comment]
This error message comes from built-in `dired-get-file-for-visit` directly, so we can't fix it in Spacemacs. It has to be fixed upstream in Emacs. They will probably need more details about when the error does happen and when it doesn't. I could not reproduce the error myself.
