### ISSUE TITLE
unable to delete orphaned package notmuch system package in debian

### ISSUE THREAD

**Issue by bhuvankrishna** [syl20bnr/spacemacs#9061]
While installing spacemacs on debian sid which already had notmuch i get this error.

Warning (initialization): An error occurred while loading ‘/home/user/.emacs.d/init.el’:

error: Package ‘notmuch-0.23.7’ is a system package, not deleting

when I start emacs with --debug-init i get this screen

![screenshot from 2017-06-09 20-48-59](https://user-images.githubusercontent.com/592449/26982211-4a5cdd22-4d55-11e7-8770-6e638838860d.png)

**Comment by bhuvankrishna** [comment]
I installed spacemacs with Emacs 24 and notmuch already installed. Then I purge removed both and installed Emacs 25 with an empty .emacs.d directory and cloned spacemacs into it. Also removed any config files of notmuch even then I get this error.

**Comment by LdBeth** [comment]
Locate notmuch.el and manually revome those packages.

**Comment by bhuvankrishna** [comment]
there is no file called notmuch.el and as I was saying I removed everything related to notmuch from my system including config files.

**Comment by bhuvankrishna** [comment]
I found the solution. the problem was with elpa-notmuch package which was installed because of it notmuch was in /usr/share/emacs/site-lisp/elsp-src/ and I think spacemac was found this as a problem. When I remove the package elpa-notmuch spacemac worked.

**Comment by arinbasu** [comment]
I had the same problem with ESS. Removing ESS from elsp-src worked for me too. This is a good solution, Bhuvankrishna.

**Comment by schmudde** [comment]
I got this error in my working Spacemacs after installing **notmuch**. The solution worked, but it has changed just slightly. I had to remove: `/usr/share/emacs/site-lisp/elpa-src/` which includes `notmuch-0.28.3`.
