### ISSUE TITLE
Uncaught Exception in Sierra Beta

### ISSUE THREAD

**Issue by pbontrager** [syl20bnr/spacemacs#9063]
#### Description :octocat:
I'm running the latest version of Spacemacs on macOS Sierra 10.12.6 beta. The program is very unstable. It frequently crashes within less than 20 minutes of opening it.

#### Reproduction guide :beetle:
- Start Emacs
The exact way to make it crash is unclear to me. If my laptop goes to sleep it will often crash on wakeup. Other times it just crashes during regular use.

*Observed behaviour:* :eyes: :broken_heart:
It usually crashes in two parts (except in the case where the computer was asleep and I cannot observe this). First, for unkown reasons, I will get the following error in terminal;

“Emacs[7435:2251417] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffa0ad82cb __exceptionPreprocess   171
	1   libobjc.A.dylib                     0x00007fffb58e648d objc_exception_throw   48
	2   AppKit                              0x00007fff9ecc3e82 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]   4480
	3   Emacs                               0x000000010016d5b6 ns_send_appdefined   103
	4   Emacs                               0x000000010016fcdc -[EmacsApp fd_handler:]   718
	5   Foundation                          0x00007fffa24718ed __NSThread__start__   1243
	6   libsystem_pthread.dylib             0x00000001010e893b _pthread_body   180
	7   libsystem_pthread.dylib             0x00000001010e8887 _pthread_body   0
	8   libsystem_pthread.dylib             0x00000001010e808d thread_start   13
)
libc  abi.dylib: terminating with uncaught exception of type NSException”

The application will continue to run, but the interactive displays will become buggy. If I press SPC the usual popup with commands to press will not appear unless I wave my mouse over the area. Eventually it will completely crash, and an additional error line will be added in terminal.

“Fatal error 6: Abort trapAbort trap: 6”

*Expected behaviour:* :heart: :smile:
I expect it not to crash.

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm emacs-lisp markdown org osx deft bibtex pandoc)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by swaroopch** [comment]
This looks like an Emacs issue, not a Spacemacs issue? Try compiling Emacs?

**Comment by LdBeth** [comment]
Or try to reproduce the problem without loading Spacemacs

**Comment by pbontrager** [comment]
I re-downloaded emacs and the problem hasn't resurfaced for the last 24 hours.
