### ISSUE TITLE
Custom prompt for Eshell

### ISSUE THREAD

**Issue by ReneFroger** [syl20bnr/spacemacs#9077]
Could anyone add the configurations which are posted here: https://www.reddit.com/r/emacs/comments/6f0rkz/my_fancy_eshell_prompt/

to the Spacemacs layer of Eshell?

For example:

![](http://i.imgur.com/iBttk5T.png)

The above is more usable than the current Eshell in Spacemacs.

**Comment by beta1440** [comment]
What makes that Eshell theme more usable than the default Spacemacs Eshell theme?
