### ISSUE TITLE
Add persp-projectile

### ISSUE THREAD

**Issue by Yamakaky** [syl20bnr/spacemacs#9078]
https://github.com/bbatsov/persp-projectile does projectile integration with perspective. One is installed [here](https://github.com/syl20bnr/spacemacs/blob/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/layers/%2Bspacemacs/spacemacs-layouts/packages.el#L16) and the other one [here](https://github.com/syl20bnr/spacemacs/blob/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/layers/%2Bdistributions/spacemacs-base/packages.el#L44). Where should I add persp-projectile?

**Comment by nixmaniack** [comment]
Spacemacs does have this functionality in core. It's called [layouts](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#project-layouts). 

IMO, if `persp-projectile` has more features than what Spacemacs already provides then only it would make sense to add it.

**Comment by Yamakaky** [comment]
Oh, right, didn't see them. They work great except NeoTree which doesn't update when switching projects. I'll try and see if it's better with persp-projectile.

**Comment by Yamakaky** [comment]
Hum, it doesn't seem to work, maybe a conflict with spacemacs layers.
