### ISSUE TITLE
Magit switches are not selected with `-`

### ISSUE THREAD

**Issue by rpglover64** [syl20bnr/spacemacs#9082]
#### Description :octocat:
Magit switches are not selected with `-` (on master and on develop)

#### Reproduction guide :beetle:
- Start Emacs
- Open magit-status (e.g. `SPC b s`)
- Open a popup (e.g. "push" with `p`)
- Attempt to set a switch (e.g. "force-with-lease" with `-f`)

*Observed behaviour:* :eyes: :broken_heart:

Minibuffer displays "- isn’t bound to any action"

*Expected behaviour:* :heart: :smile:

Switch is selected

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 11356be1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(html python csv markdown yaml sql
      (auto-completion :variables auto-completion-return-key-behavior 'nil auto-completion-tab-key-behavior 'cycle)
      better-defaults haskell emacs-lisp git github ivy emacs-lisp
      (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
      org agda deft spell-checking
      (syntax-checking :variables syntax-checking-enable-tooltips 'nil))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by et2010** [comment]
I can confirm this.

**Comment by TheBB** [comment]
Rollback evil-magit for now.

**Comment by justbur** [comment]
Thanks, fixed with https://github.com/emacs-evil/evil-magit/commit/91c96e6ffdc6e7d5e49fd9b0ffb7df8794f0f2db

**Comment by duianto** [comment]
Just tested the fix, and it works 👍
