### ISSUE TITLE
Spacemacs assumes theme names, which is wrong

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#9084]
I want to use doom themes: https://github.com/hlissner/emacs-doom-themes

The name is `doom-tomorrow-night`. However, Spacemacs assumes that the theme package name is `doom-tomorrow-night-them`, and could not be loaded properly no matter what.

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/blob/develop/core/core-themes-support.el#L125-L126

This is very simple to PR. :-)

**Comment by Azphreal** [comment]
So that's where those are stored. Good to know.
