### ISSUE TITLE
adoc layer is obsolete

### ISSUE THREAD

**Issue by gabrielps** [syl20bnr/spacemacs#9085]
#### Description :octocat:
asciidoc layer has weird behaviours and is really slow. I understand this issue should be open in adoc-mode's git, but the project seems to be abandoned (issues without comments for more than 6 months https://github.com/sensorflo/adoc-mode/issues/28)

#### Reproduction guide :beetle:
- Start Emacs
- Open a .adoc file
- Play with it for some time.

*Observed behaviour:* :eyes: :broken_heart:
- Some highlights are not working (i.e. title level 5)
- Text input has lag

*Expected behaviour:* :heart: :smile:
- Highlights working
- No lag

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asciidoc html sql java javascript emacs-lisp restclient ranger git syntax-checking
          (auto-completion :variables auto-completion-enable-sort-by-usage t)
          org themes-megapack)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by zane** [comment]
This issue is definitely still valid.

**Comment by sdwolfz** [comment]
So what would the action be? Replace `adoc-mode` with something else, remove the layer completely, or fork and fix it ourselves?

**Comment by 00krishna** [comment]
@zane @sdwolfz Yes, it really would be nice to have a functioning Asciidoc mode. Something that inserted code blocks and pass through blocks, as well as the rest. Is anyone thinking of an update? I am not really 
a lisp programmer but I could help in some way if others are on board.

**Comment by FlorianFranzen** [comment]
There is some effort to revive the mode: [emacsorphanage/adoc-mode](https://github.com/emacsorphanage/adoc-mode)

**Comment by lebensterben** [comment]
`melpa` has already updated the repo URL to the maintained one.

If there's still issue regarding this package, comment below and I'll reopen this.

**Comment by bluedogtwo** [comment]
I installed spacemacs today and adoc files has bad palette.
