### ISSUE TITLE
Spacemacs crash when opening file. 

### ISSUE THREAD

**Issue by sandersantema** [syl20bnr/spacemacs#9086]
#### Description :octocat:
Spacemacs crashes when opening a file from finder.
#### Reproduction guide :beetle:
- Start Emacs
- Open file x in Spacemacs.
- Open file y from finder.
- File y opens itself in a new tab which looks like the native tabs from Mac OS. Like you see in finder or in safari. 
- Spacemacs crashes shortly after.

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs crashes. 

*Expected behaviour:* :heart: :smile:
Opening of file in a new tab or split window. I don't exactly now what supposed to happen except for the fact that spacemacs isn't supposed to crash. 

#### System Info :computer:
- OS: darwin (mac OS 10.12.4)
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil auto-completion-enable-sort-by-usage t)
 (spell-checking :variables enable-flyspell-auto-completion t spell-checking-enable-auto-dictionary t)
 (syntax-checking :variables syntax-checking-enable-tooltips t syntax-checking-enable-by-default t)
 bibtex emacs-lisp games ivy javascript latex org osx semantic spotify syntax-checking version-control xkcd)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by sandersantema** [comment]
I hope my bug report is correct and contained sufficient info since this is the first issue I've ever opened. If not please tell me what I should change.

**Comment by sdwolf** [comment]
See this link on how to debug segfaults: https://github.com/syl20bnr/spacemacs/wiki/Debugging#debugging-segmentation-faults-with-gdb. 
You might need to open an issue in the emacs mailing list.

**Comment by sandersantema** [comment]
I'm currently to busy to figure out how to debug segmentation faults since I would have to figure it all out, I'm not knowledgeable at all in this area of computing. I hope someone else would be able to do it for me, the bug isn't hard at all to reproduce if it's not a problem specific to my system. I would want to open the issue on the emacs mailing list however again I'm not knowledgeable at all in this subject so my bug report might not be that useful. Anyways thanks for the tips.

**Comment by beta1440** [comment]
@sandersantema you've included the `syntax-checking` layer twice. Trying removing the second one.

**Comment by d12frosted** [comment]
@sandersantema I am sorry to hear that Emacs crashes with segmentation fault. Since there is no one reporting similar symptoms and you are currently busy with other stuff, I am going to close this issue. But let us know if once you have more information. Cheers.
