### ISSUE TITLE
Clean install is broken

### ISSUE THREAD

**Issue by Dietr1ch** [syl20bnr/spacemacs#9089]
I wanted to convert a vim user to spacemacs, but he couldn't try out spacemacs.
It seems that the order of the packages might be broken, I got the following after doing a clean install on a temporal user.
I'm not sure what is going wrong, without vi-bindings I'm lost :(

I'll look at the --debug-init flag later

```
0.200.9@25.2.1 (spacemacs\|Warning (initialization): An error occurred while loading ‘/tmp/fake_home/.emacs.d/init.el’:

File error: Cannot open load file, No such file or directory, ido-completing-read+
```

**Comment by TheBB** [comment]
I can't reproduce this on master or develop with Emacs 25.1.

**Comment by Dietr1ch** [comment]
I tried to replicate it at home and it works fine (Manjaro; emacs 25.2.1) (=
I also checked another machine at uni (Ubuntu; emacs 24.5.1) and it's also fine.

There must be something weird with the environment at work. I'll look onto that and ask on irc/gitter later.

**Comment by Dietr1ch** [comment]
It's definitely a problem with the environment at work, requiring our config before loading spacemacs makes it work.

**Comment by maxweber** [comment]
I had a similar problem after switching from ido to ivy in Doom Emacs. This helped to resolve the issue:

```
rm -rf ~/.emacs.d/.local/
doom clean && doom sync && doom build
```

I found both hints here: https://github.com/doomemacs/doomemacs/issues/2483
