### ISSUE TITLE
Cannot open Org Mode major mode menu (previously `M-m m`)

### ISSUE THREAD

**Issue by teodorlu** [syl20bnr/spacemacs#9095]
#### Description :octocat:
I can no longer open my Org Mode major mode menu (previously `M-m m`). I use holy mode.

My .spacemacs is here: https://github.com/teodorlu/dotfiles/blob/master/.spacemacs

I'm happy to provide more debug information. I'd also like to hear if any others are able to reproduce this.

#### Reproduction guide :beetle:
- Start Emacs
- Open an Org Mode file
- Try to open major mode menu with `M-m m`

*Observed behaviour:* :eyes: :broken_heart:
- Message file says `M-m m is undefined`

*Expected behaviour:* :heart: :smile:
- Finding that lovely Org Mode menu!

*Perhaps useful other behavior:*
- Press `C-M-m` at the end of a list item
- Org inserts new list item! This normally happens with `M-<enter>`. Perhaps a key binding conflict?

#### System Info :computer:
- OS: gnu/linux
- Ubuntu 17.04
- Emacs: 25.1.1 (from Ubuntu repositories)
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(csv yaml lua javascript windows-scripts octave sql elm html haskell python clojure ivy
     (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete)
     emacs-lisp git markdown ranger spell-checking syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by Beta1440** [comment]
This is a key binding conflict. You have to change your `dotspacemacs-emacs-leader-key` variable in your `.spacemacs` file. its `M-m` by default.

**Comment by teodorlu** [comment]
Are you sure? It works fine on Windows. Also, `M-m` works as expected, showing the menu and all, but `M-m m` does nothing, neither does `C-M-m`.

Any suggestions?

**Comment by Beta1440** [comment]
It looks like you don't have the `org` layer in your `.spacemacs`. Try adding it to see if it makes a difference.

**Comment by teodorlu** [comment]
You were right! Silly me. Thanks!
