### ISSUE TITLE
key bindings ess mode

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#9096]
I propose the following keybinding for `ess-mode`, they are simply all the keybinding that are accessible by `C-x`, I am not sure about spacemacs conventions on this, but they don't clash. Using the key maps gives the additional advantage of having a nice description in `which-key`.

```elisp
(spacemacs/set-leader-keys-for-major-mode 'ess-mode
    ;; More REPL
    "z"  'ess-switch-to-inferior-or-script-buffer
    "ss" 'ess-switch-process
    "sf" 'ess-eval-function
    "sF" 'ess-eval-function-and-go
    ;; ESS doc map
    "d" 'ess-doc-map
    ;; "dd" 'ess-display-help-on-object
    ;; "de" 'ess-describe-object-at-point
    ;; "dm" 'ess-manual-lookup
    ;; "do" 'ess-display-demos
    ;; "dr" 'ess-reference-lookup
    ;; "dw" 'ess-help-web-search
    ;; "dv" 'ess-display-vignettes
    ;; "di" 'ess-display-index
    ;; "da" 'ess-display-help-apropos
    ;; ESS extra map
    "e" 'ess-extra-map
    ;; "e TAB" 'ess-install-library
    ;; "e/"    'ess-set-working-directory
    ;; "ed"    'ess-dump-object-into-edit-buffer
    ;; "ee"    'ess-execute
    ;; "ei"    'ess-install-library
    ;; "el"    'ess-load-library
    ;; "er"    'inferior-ess-reload
    ;; "es"    'ess-set-style
    ;; "et"    'ess-build-tags-for-directory
    ;; "ew"    'ess-execute-screen-options
    ;; R devtools
    "w" 'ess-r-package-dev-map
    ;; "w TAB" 'ess-r-devtools-install-package
    ;; "wa"    'ess-r-devtools-ask
    ;; "wc"    'ess-r-devtools-check-package
    ;; "wd"    'ess-r-devtools-document-package
    ;; "wi"    'ess-r-devtools-install-package
    ;; "wl"    'ess-r-devtools-load-package
    ;; "ws"    'ess-r-package-set-package
    ;; "wt"    'ess-r-devtools-test-package
    ;; "wu"    'ess-r-devtools-unload-package
    ;; "wr"    'ess-r-devtools-revdep-check-package
    ;; ess dev map
    "t" 'ess-dev-map
    ;; "t?" 'ess-tracebug-show-help
    ;; "t`" 'ess-show-traceback
    ;; "t~" 'ess-show-call-stack
    ;; "tb" 'ess-bp-set
    ;; "tB" 'ess-bp-set-conditional
    ;; "td" 'ess-debug-flag-for-debugging
    ;; "te" 'ess-debug-toggle-error-action
    ;; "ti" 'ess-debug-goto-input-event-marker
    ;; "tk" 'ess-bp-kill
    ;; "tK" 'ess-bp-kill-all
    ;; "tl" 'ess-bp-set-logger
    ;; "tn" 'ess-bp-next
    ;; "tN" 'ess-bp-previous
    ;; "to" 'ess-bp-toggle-state
    ;; "tp" 'ess-bp-previous
    ;; "ts" 'ess-r-set-evaluation-env
    ;; "tt" 'ess-toggle-tracebug
    ;; "tu" 'ess-debug-unflag-for-debugging
    ;; "tw" 'ess-watch
    )
(spacemacs/set-leader-keys-for-major-mode 'ess-julia-mode
    ;; REPL
    "sB" 'ess-eval-buffer-and-go
    "sb" 'ess-eval-buffer
    "sD" 'ess-eval-function-or-paragraph-and-step
    "sd" 'ess-eval-region-or-line-and-step
    "sL" 'ess-eval-line-and-go
    "sl" 'ess-eval-line
    "sR" 'ess-eval-region-and-go
    "sr" 'ess-eval-region
    "sF" 'ess-eval-function-and-go
    "sf" 'ess-eval-function
    ;; ESS doc map
    "d" 'ess-doc-map
    ;; "dd" 'ess-display-help-on-object
    ;; "de" 'ess-describe-object-at-point
    ;; "dm" 'ess-manual-lookup
    ;; "do" 'ess-display-demos
    ;; "dr" 'ess-reference-lookup
    ;; "dw" 'ess-help-web-search
    ;; "dv" 'ess-display-vignettes
    ;; "di" 'ess-display-index
    ;; "da" 'ess-display-help-apropos
    ;; (spacemacs/declare-prefix-for-mode mode "mh" "help")
    )

```

**Comment by TheBB** [comment]
> I am not sure about spacemacs conventions

https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.org

In particular, `SPC m e` is for evaluation, and `SPC m s` is for shells. You seem to have a lot of eval bindings on `s` and I don't know what else on `e`.

**Comment by gdkrmr** [comment]
What is the exact difference between sending code and evaluating? I am not sure if in ESS there is a difference, I think in the end everything is copied to the repl anyways.

**Comment by gdkrmr** [comment]
btw. the julia bindings that start with `s` are mostly just copied from `ess-mode` which are already present in spacemacs.

**Comment by TheBB** [comment]
If the command focuses or pops up the REPL, it should be under `s`.

**Comment by gdkrmr** [comment]
ESS does not seem to fit entirely into this scheme:

- The functions that en with `-and-go` will pop up and focus the REPL, 
- The ones that end with `-and-step` will pop up the REPL if it not visible in a window but will not focus it, instead they will move the cursor to the next line of source code. 
- The rest will only pop up a REPL if there is none associated with the current buffer.

So am I correct if `-and-go` and `-and-step` functions should go under `m s` and the rest under `m e`?

what is currently bound to `m s i` (`ess-start-repl`) will always start a new process, what fits the description better is `ess-switch-to-inferior-or-script-buffer`, this is a very handy shortcut and should be bound to something very convenient like `m '` instead of `ess-start-repl`.

There is also a function that lets you change the process that is associated with a buffer, it shows a list with running REPLS and has the option to start a new one, I think this one should be bound to `m s i` because it is more flexible than `ess-start-repl`.

**Comment by gdkrmr** [comment]
btw: there is no mention of `m '` in the CONVENTIONS.org

**Comment by bmag** [comment]
@gdkrmr hey, I see this suggestion got buried, but I'd like to get these bindings into Spacemacs (as much of them as makes sense). Are you still up for it? Also, a bit related, can you give your opinion on https://github.com/syl20bnr/spacemacs/pull/9694#issuecomment-336690883 please?

> So am I correct if `-and-go` and `-and-step` functions should go under `m s` and the rest under `m e`?

Seems like the most correct approach, yes.

Not sure if it says so, but `m'` is supposed to be the same as `msi` as far as I remember. Looking in other layers, it has become an undocumented convention that if there is more than one "get to repl" command, `msi` starts a new repl or switches to an existing one, and `mss` switches to an existing one. (examples: Ruby and Clojure layers) Does `ess-switch-to-inferior-or-script-buffer` start a new REPL if no one exists? (I see it's bound to `C-c C-z`, so I assume it does)

That said, I propose this:
- `mss` bound to `ess-switch-to-inferior-or-script-buffer`
- `msS` bound to the "function that lets you change the process that is associated with a buffer"
- `msi` bound to `ess-start-repl`, OR `msi` bound to `ess-switch-to-inferior-or-script-buffer` and `msI` bound to `ess-start-repl` (assuming `ess-switch-to-inferior-or-script-buffer` can start a new repl)
- `m'` bound to the same thing as `msi`

> Also: ESS has the super useful (bound to `C-c C-c`) `ess-eval-region-or-function-or-paragraph-and-step` what would that be bound to? I personally would prefer `m ,`.

I'm ok with that.

Also, as per the conventions:
- `d`: debugging (including what you put under `t`)
- `h`: help and documentation (including what you put under `d`)
- `t`: test functions (don't seem to be much of these)

Not sure what to do with devtools, guess `w` is good.

**Comment by gdkrmr** [comment]
I am glad that someone cares about this. I took a stab at  the key bindings for R, comments on conflicts and other stuff are in the code:
```elisp
(spacemacs/set-leader-keys-for-major-mode 'ess-mode
  ;; This does what C-c C-c does in ESS:
  ","  'ess-eval-region-or-function-or-paragraph-and-step

  "'"  'spacemacs/ess-start-repl
  "si" 'spacemacs/ess-start-repl
  ;; REPL
  "sb" 'ess-eval-buffer-and-go
  "eb" 'ess-eval-buffer

  "sd" 'ess-eval-function-or-paragraph-and-step
  "sD" 'ess-eval-region-or-line-and-step

  "sl" 'ess-eval-line-and-go
  "el" 'ess-eval-line

  "sr" 'ess-eval-region-and-go
  "er" 'ess-eval-region

  "sf" 'ess-eval-function-and-go
  "ef" 'ess-eval-function

  "sS" 'ess-switch-process
  "ss"  'ess-switch-to-inferior-or-script-buffer
  ;; ESS doc map
  "h" 'ess-doc-map
  ;; "hd" 'ess-display-help-on-object
  ;; "he" 'ess-describe-object-at-point
  ;; "hm" 'ess-manual-lookup
  ;; "ho" 'ess-display-demos
  ;; "hr" 'ess-reference-lookup
  ;; "hw" 'ess-help-web-search
  ;; "hv" 'ess-display-vignettes
  ;; "hi" 'ess-display-index
  ;; "ha" 'ess-display-help-apropos
  ;; R helpers

  ;; TODO: conflict
  "hd" 'ess-R-dv-pprint

  ;; TODO: this one got removed but will probably be replaced so there will be a
  ;; conflict:
  ;; "hi" 'ess-R-object-popup

  "ht" 'ess-R-dv-ctable

  ;; ESS extra map
  "e" 'ess-extra-map
  ;; "e TAB" 'ess-install-library
  ;; "e/"    'ess-set-working-directory
  ;; "ed"    'ess-dump-object-into-edit-buffer
  ;; "ee"    'ess-execute
  ;; "ei"    'ess-install-library
  ;; "el"    'ess-load-library
  ;; "er"    'inferior-ess-reload
  ;; "es"    'ess-set-style
  ;; "et"    'ess-build-tags-for-directory
  ;; "ew"    'ess-execute-screen-options
  ;; R devtools
  "w" 'ess-r-package-dev-map
  ;; "w TAB" 'ess-r-devtools-install-package
  ;; "wa"    'ess-r-devtools-ask
  ;; "wc"    'ess-r-devtools-check-package
  ;; "wd"    'ess-r-devtools-document-package
  ;; "wi"    'ess-r-devtools-install-package
  ;; "wl"    'ess-r-devtools-load-package
  ;; "ws"    'ess-r-package-set-package
  ;; "wt"    'ess-r-devtools-test-package
  ;; "wu"    'ess-r-devtools-unload-package
  ;; "wr"    'ess-r-devtools-revdep-check-package
  ;; ess dev map
  "d" 'ess-dev-map
  ;; "d?" 'ess-tracebug-show-help
  ;; "d`" 'ess-show-traceback
  ;; "d~" 'ess-show-call-stack
  ;; "db" 'ess-bp-set
  ;; "dB" 'ess-bp-set-conditional
  ;; "dd" 'ess-debug-flag-for-debugging
  ;; "de" 'ess-debug-toggle-error-action
  ;; "di" 'ess-debug-goto-input-event-marker
  ;; "dk" 'ess-bp-kill
  ;; "dK" 'ess-bp-kill-all
  ;; "dl" 'ess-bp-set-logger
  ;; "dn" 'ess-bp-next
  ;; "dN" 'ess-bp-previous
  ;; "do" 'ess-bp-toggle-state
  ;; "dp" 'ess-bp-previous
  ;; "ds" 'ess-r-set-evaluation-env
  ;; "dt" 'ess-toggle-tracebug
  ;; "du" 'ess-debug-unflag-for-debugging
  ;; "dw" 'ess-watch

  ;; noweb
  ;; TODO: these probably don't fit the scheme either
  "cC" 'ess-eval-chunk-and-go
  "cc" 'ess-eval-chunk
  "cd" 'ess-eval-chunk-and-step
  "cm" 'ess-noweb-mark-chunk
  "cN" 'ess-noweb-previous-chunk
  "cn" 'ess-noweb-next-chunk
  )

```

**Comment by bmag** [comment]
Looks reasonable. For conflicts, we can solve them with upper-casing a binding. For example, one of the `"hd"` bindings can move to `"hD"`. You'll make a PR?

By the way, I found an old PR for improving ESS key-bindings and more stuff at #4176. Some of the bindings go against what we discussed here (e.g. debugging under `b` prefix), but I think the decisions from this issue should override #4176 where they conflict. Last comment is from June, but last change by the author is from December 2015, so it seems the PR is abandoned. I'm not sure about all that's going on in that PR, but if you want to complete it you're welcome (it can happen after PR-ing the keybindings)

**Comment by gdkrmr** [comment]
great, I can make a PR, I think that the julia-mode bindings have to be set separately, I will investigate that before making the PR.

**Comment by gdkrmr** [comment]
I checked #4176 and because I don't know much about the ESS internals I am not sure about many of these changes; Also @TheBB made a comment about the company integration of the PR and I don't know what this is about. Some comment about this would be helpful.

**Comment by gdkrmr** [comment]
where to put the `ess-extra-map`? I put it under `,e` but now it has quite a lot of conflicts.

**Comment by gdkrmr** [comment]
you can find the changes here:
https://github.com/gdkrmr/spacemacs/tree/ess-keybinding
I will use them for a week or so and see if everything works.

**Comment by gdkrmr** [comment]
what would be spacemacs key sequence to go to the beginning or end of a function?

**Comment by gdkrmr** [comment]
what would be a good key sequence to put point at the beginning and mark at the end of a function?

**Comment by bmag** [comment]
> what would be spacemacs key sequence to go to the beginning or end of a function?

Emacs has standard bindings for those `C-M-a` and `C-M-e` (`beginning-of-defun`, `end-of-defun`). I'm not sure we need additional Spacemacs bindings, but you can put them on `,gb` and `,ge` if you think they're needed.

> what would be a good key sequence to put point at the beginning and mark at the end of a function?

Emacs has a standard bindings for that: `C-M-h` (`mark-defun`). Again, I'm not sure we need an additional binding, but maybe `,mf` (for "mark function") or `,vf` ("visual function") are ok.

**Comment by gdkrmr** [comment]
in ess the standard bindings work for that, if there is no spacemacs standard, i'll probably leave it be for now

**Comment by gdkrmr** [comment]
I opened a second pull request for julia keybindings and nicer prefixes #9920

**Comment by bmag** [comment]
@gdkrmr now that #9920 is merged, we took care of everything in this issue, right?

**Comment by jackkamm** [comment]
@bmag @gdkrmr just noticed the new keybindings, and I think some of the changes violate CONVENTIONS.org. In particular,
`SPC m s b` should send buffer without switching to REPL, `SPC m s B` should be the command to send and switch to REPL. Similarly for `SPC m s r/R`, etc. These were correctly following the spacemacs convention before the PR but now it's been changed so that `SPC m s b` switches to REPL and `SPC m e b` sends buffer without switching.

Otherwise the new bindings for help, markdown, etc look cool and useful, just the ones for sending to the shell are messed up. Can we revert the `SPC m s` bindings to follow CONVENTIONS.org? I am happy to submit a PR if that helps.

**Comment by jackkamm** [comment]
OK I see higher in the thread that `ess-eval-buffer` got moved to `SPC m e b` because of a comment by @TheBB higher in the thread. Likewise for `ess-eval-region` etc. I don't think this is right.  `ess-eval-buffer` is exactly analogous to `python-shell-send-buffer` in python layer which is bound to `SPC m s b` not `SPC m e b`.

I rely on consistent keybindings across R and Python for some of my personal macros, and anyways the consistent keybindings across modes are supposed to be a feature of spacemacs. So I think either the R binding should be moved back to `SPC m s b` or the Python binding should be moved to `SPC m e b`. I think the Python binding is right. But it is indeed very confusing that there is a distinction between "Evaluation" and "REPL" in CONVENTIONS.org.

**Comment by dangom** [comment]
Just started learning R and got surprised that Spacemacs keybindings for Python and ESS differ. Should consider harmonising them?

**Comment by gdkrmr** [comment]
> Just started learning R and got surprised that Spacemacs keybindings for Python and ESS differ. Should consider harmonising them?

I don't know how many other layers use a REPL, e.g. the `julia` layer and  they should probably all be harmonized. There are official guidelines [here](https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONVENTIONS.org#key-bindings-conventions).
