### ISSUE TITLE
center buffer around cursor when searching

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#9097]
Currently, when searching with `/` or `*` and the buffer has to scroll when jumping to the next occurrence the cursor ends up on the last line of the buffer. 
In vim standard behavior is to center the buffer around the cursor, which IMHO should be standard behavior for spacemacs, too.

Edit:
The same happens when jumping to marks (set mark with `m a`, go somewhere else in the file, jump back with `' a`, the cursor will end up at the bottom or top of the buffer.

**Comment by braham-snyder** [comment]
you may want to set `scroll-conservatively` to `scroll-margin`'s value

seems to me as well like it might be a sensible default (though it could also go into `evil`? or does `evil` generally avoid going that far?)

**Comment by fiveNinePlusR** [comment]
I'd like this to extend to `n` and `N` and other search commands.

**Comment by gdkrmr** [comment]
ok, thanks, I set `scroll-margins` and `scroll-conservatively` to 0, which seem to be sensible defaults for me and this extends this to `n` and `N` as well.
