### ISSUE TITLE
Haskell-Mode Insert Template Not Working

### ISSUE THREAD

**Issue by IQubic** [syl20bnr/spacemacs#9098]
So, I have a function in a Haskell file that lacks a type signature. Now, I know I can type it in manually, but I don't want to. The Haskell help files say that `SPC M M T` will insert a template, but that's not working.

 I move the point to the name of the function that lacks a function and type `SPC M M T` and the words "Nothing to do" show up in the status bar. Not sure why this isn't working.

**Comment by CeleritasCelery** [comment]
This isn't a Spacemacs problem. You will need to address if with the maintainers of the `ghc` package.

**Comment by Miciah** [comment]
This looks like the same issue as #9336.
