### ISSUE TITLE
Error: Completion needs an inferior Python process running

### ISSUE THREAD

**Issue by Zundrium** [syl20bnr/spacemacs#9099]
#### Description :octocat:
I'm trying to use python auto-completion but with no success.

#### Reproduction guide :beetle:
- Install Emacs with `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`.
- Add `auto-completion` and `python` to the `dotspacemacs-configuration-layers`.
- Ran `pip install --upgrade "jedi>=0.9.0" "json-rpc>=1.8.1" "service_factory>=0.1.5"` and `sudo pip install flake8` in a terminal.
- Restart Emacs.
- Open a `.py` file.
- Try the complete function.

*Observed behaviour:* :eyes: :broken_heart:
The status bar gives an error `Completion needs an inferior Python process running`.

*Expected behaviour:* :heart: :smile:
The completion suggests possible snippets / functions in a drop-down.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm auto-completion emacs-lisp)
```

**Comment by TheBB** [comment]
> Try the complete function.

Please be more specific.

**Comment by Zundrium** [comment]
Alright: type `ipdb` and press `TAB`. If I missed any kind of information please let me know. My fingers are itching to try spacemacs 👍

**Comment by TheBB** [comment]
By pressing tab you are launching Emacs' own built-in completion, which does indeed need an inferior python process running. The company/anaconda completion doesn't, and should just pop up whenever it can.

So if I type in an empty python file (`|` denoting the cursor)

```python
import ip|
```

I do get a popup that suggests, among other things, `ipdb`. And if I type


```python
import ipdb
ipdb.
```

I get a popup with members of the `ipdb` module. However if I type (as you suggest), just

```python
ipdb
```

there are no completions available, as there shouldn't be.

**Comment by Zundrium** [comment]
Thanks for the help guys, I guess I'm mixing up autocompletion with snippets. How can I easily enable a default list of snippets?

**Comment by Crazy-Owl** [comment]
I have to say that TAB-based completion does not work for me either, nor do popups from anaconda. In fact, I don't see no sign of anaconda anywhere, including error messages buffer.

I've actually used spacemacs for python with proper anaconda autocompletion (TAB key worked as intended, i.e. used anaconda suggestions), but that was about a year ago, and since then python autocompletion is broken for me (event tried a fresh install according to all instructions, dependencies and whatnot) and I can't get it to work.
