### ISSUE TITLE
[RFE] Space f m: magit-find-file

### ISSUE THREAD

**Issue by dparalen** [syl20bnr/spacemacs#9101]
Hello dear Spacemacs!

I'd like to suggest a shortcut to magit-find-file through: Space f m

<3
milan

PS: sorry for my ignorance if such a shortcut already exists

**Comment by phenix-factory** [comment]
Hello,

There is a file section already, in `SPC m f`.
Since it's a magit command, isn't better to use `SPC m f f` ?

**Comment by duianto** [comment]
The develop branch has the `magit-find-file` command in the following section:
`SPC` Spacemacs root
`g` +git/version-control
`f` +file
`f` magit-find-file
in other words `SPC g f f`

**Comment by dparalen** [comment]
Thanks for the answers!

I then realised that `m' would refer to a particular revision system implementation, unsure what's the policy on that. But SPC g f f (or SPC m f f) makes sense.

Cheers,
milan

PS: I guess this is closed based on the previous response

**Comment by duianto** [comment]
I don't think `SPC m` will work, because it shows major modes specific key bindings. And the magit buffer doesn't have a binding for `SPC m`.

`SPC g` seems to be a global binding, that can be accessed in most if not all modes.
