### ISSUE TITLE
Stars reached 12,000! please record!

### ISSUE THREAD

**Issue by lhrkkk** [syl20bnr/spacemacs#9103]
Congratulations!

**Comment by TheBB** [comment]
Was it @harrifeng?

**Comment by duianto** [comment]
Looks like it, at least if the gitter chat activity is correct, currently it shows, 12,002 stars, and the last 3 people that starred was: 
alanlgardner
shaunak-amura
harrifeng

**Comment by harrifeng** [comment]
I am the NO. 12000 ? haha!

**Comment by NJBS** [comment]
@harrifeng Welcome to the ⭐️ club 😄 !

http://develop.spacemacs.org/doc/DOCUMENTATION.html#stars-forks-and-watchers
