### ISSUE TITLE
Spacemacs display python traceback message when i open django tutorial project.

### ISSUE THREAD

**Issue by petrewoo** [syl20bnr/spacemacs#9106]
#### Description :octocat:
Spacemacs display python traceback message when i open django tutorial project.

#### Reproduction guide :beetle:
- Start Emacs
- Using [SPC p l] open django tutorial project
- Using [SPC p f] open example python file(polls/view.py)
- Moving cursor by pressing [j, k] (evil-mode)

*Observed behaviour:* :eyes: :broken_heart:
1. Display python traceback message in a new window
2. Display message "can not create ~/.emacs.d/.cache/anaconda-mode/0.1.8 directory"
   at the bottom of spacemacs

*Expected behaviour:* :heart: :smile:
Everything works right.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml javascript vimscript helm auto-completion ycmd emacs-lisp git markdown org
      (shell :variables shell-default-term-shell ansi-term shell-default-height 50 shell-default-position 'bottom)
      spell-checking syntax-checking
      (version-control :variables version-control-global-margin t version-control-diff-tool 'diff-hl)
      python django
      (ranger :variables ranger-show-preview t)
      osx
      (go :variables gofmt-command "goimports")
      (c-c   :variables c-c  -default-mode-for-headers 'c  -mode))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 62, in <module>
    import os
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 49, in <module>
    import posixpath as path
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 15, in <module>
    import stat
  File "stat.py", line 5, in <module>
    import argparse
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 92, in <module>
    from gettext import gettext as _
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gettext.py", line 60, in <module>
    _default_localedir = os.path.join(sys.prefix, 'share', 'locale')
AttributeError: 'module' object has no attribute 'path'
```

**Comment by NJBS** [comment]
This seems like an issue with your python installation and/or anaconda-mode, can you report your issue upstream to them? https://github.com/proofit404/anaconda-mode/issues

**Comment by petrewoo** [comment]
Ok,  thank you very much.
