### ISSUE TITLE
[dev] `php` layer is not show code-completion any more.

### ISSUE THREAD

**Issue by wdy1184** [syl20bnr/spacemacs#9115]
#### Description :octocat:
`php` layer in develop branch is not show code-completion any more.

#### Reproduction guide :beetle:
- Checkout `develop` branch 
- Start Emacs
- Open a php file
- Type some code

*Observed behaviour:* :eyes: :broken_heart:
There is no code completion below cursor.

*Expected behaviour:* :heart: :smile:
Show `company` completion below cursor when I type.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. d8c00ffd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(ibuffer yaml vimscript sql html python go javascript emacs-lisp common-lisp helm git org markdown syntax-checking better-defaults imenu-list dash
         (chinese :variables chinese-enable-fcitx nil)
         (gtags :variables gtags-enable-by-default t)
         (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t :disabled-for markdown org)
         (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t version-control-diff-side 'left)
         php)
```
- System configuration features: JPEG IMAGEMAGICK NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by TheBB** [comment]
Works here if I trigger manually. Have you tried that?

**Comment by wdy1184** [comment]
@TheBB How can I turn it on?

**Comment by wdy1184** [comment]
I trigger by using `company-complete`, but it just show `function` completion.

**Comment by beta1440** [comment]
@wdy1184 Do you have `company-mode` enabled when editing PHP files? Try enabling `company-mode` manually to see if that helps.

**Comment by wdy1184** [comment]
@beta1440 Yes, I opened it, but I must open it every time I want to complete my code.

**Comment by beta1440** [comment]
For some reason in the PHP layer [packages.el](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/php/packages.el#L74) file, `company-minimum-prefix-length` is set to 1000. You have to type at least 1000 characters to get autocompletion working. This variable shouldn't be set in the PHP layer if there's no compelling reason. Below is the relevant code snippet from the PHP layer `packages.el`.

```emacs-lisp
(defun php/init-company-php ()
  (use-package company-php
    :defer t
    :init
    (progn
      (push 'ac-php-find-symbol-at-point spacemacs-jump-handlers-php-mode)
      (add-hook 'php-mode-hook 'ac-php-core-eldoc-setup)
      (spacemacs|add-company-backends
        :modes php-mode
        :variables
        company-minimum-prefix-length 1000
        :backends company-ac-php-backend))))
```

**Comment by beta1440** [comment]
@d12frosted this issue should have the `PHP` tag instead of the `Python` tag.

**Comment by beta1440** [comment]
@wdy1184 It looks like this issue has been fixed in develop.

**Comment by wdy1184** [comment]
@beta1440 Yes, it works. Thanks a lot.

**Comment by NerdsvilleCEO** [comment]
@beta1440 @wdy1184 how can I get completion for methods working? It seems to only complete functions
