### ISSUE TITLE
Error in scala-mode upgrading to v0.100.1

### ISSUE THREAD

**Issue by codygman** [syl20bnr/spacemacs#912]
After removing ~/.emacs.d/elpa and opening spacemacs again:

    Warning (emacs): Unable to activate package `sbt-mode'.
    Required package `scala-mode2-0.22' is unavailable
    Error (use-package): company-anaconda :init: Symbol's function definition is void: company-mode/backend-with-yas

upon opening a scala file:

    Error (use-package): scala-mode2 :config: Cannot open load file: noflet

**Comment by chrisbarrett** [comment]
@syl20bnr `noflet` is being installed in `.../spacemacs/packages.el`. Is there any reason why it would not be available? (e.g. `package-initialise` isn't called)

**Comment by syl20bnr** [comment]
If this is an activation issue then it should be fixed in develop.

**Comment by syl20bnr** [comment]
Confirmed by @BrianHicks to be OK in `develop`
