### ISSUE TITLE
org-mode keybindings missing on develop [regression]

### ISSUE THREAD

**Issue by JonathanReeve** [syl20bnr/spacemacs#9122]
#### Description :octocat:
Org-mode keybindings are missing. The org-mode layer documentation claims that `t` will cycle through todo-states, as it does on the master branch, but it doesn't seem to be bound on develop. 

Here's the output of `describe-key t` on master: 

```
t runs the command org-todo, which is an interactive compiled Lisp function in
‘org.el’.

It is bound to t, <normal-state> t, C-c C-t, <menu-bar> <Org> <TODO Lists>
<TODO/DONE/->.

(org-todo &optional ARG)

Change the TODO state of an item.
```

Now here's the output of `describe-key t` on develop: 

```
t runs the command evil-find-char-to (found in evil-motion-state-map), which is
an interactive Lisp function in ‘evil-commands.el’.

It is bound to t.

(evil-find-char-to &optional COUNT CHAR)

Move before the next COUNT’th occurrence of CHAR.
```

#### Reproduction guide :beetle:
- Start Emacs
- Get on the develop branch of Spacemacs
- Open an org file
- Move cursor to a header
- Try to cycle through todo items with `t`. 
- Notice it doesn't work. 

*Observed behaviour:* :eyes: :broken_heart:
`t` and probably other keybindings are unbound. 

*Expected behaviour:* :heart: :smile:
`t` should be bound to org-todo. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 07eb1050)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript yaml html helm haskell
            (auto-completion :variables spacemacs-default-company-backends
                             '(company-files company-capf ein:company-backend))
            emacs-lisp google-calendar bibtex ipython-notebook
            (mu4e :variables mu4e-account-alist t)
            (elfeed :variables rmh-elfeed-org-files
                    (list "~/Dropbox/Org/RSS.org"))
            git markdown python pdf-tools org
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            themes-megapack spell-checking syntax-checking vinegar)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES LIBSYSTEMD

**Comment by JonathanReeve** [comment]
Damn, just saw [this other bug](https://github.com/syl20bnr/spacemacs/issues/8640). Closing as duplicate.

**Comment by planigan** [comment]
Another relevant thread at #9041.
