### ISSUE TITLE
How to completely disable purpose or window-dedicated mode in Spacemacs

### ISSUE THREAD

**Issue by tddsg** [syl20bnr/spacemacs#9124]
Hi,

Recently, I notice that Spacemacs is equipped with a feature that automatically set a buffer/window to be dedicated after opening it for a while.

I don't get familiar with this feature since I normally need to switch between many buffers.

Could you advise how to disable this feature completely?
I tried to disable `purpose-mode` but it didn't work.

Thanks!

**Comment by TheBB** [comment]
Exclude the `window-purpose` package.

**Comment by tddsg** [comment]
Thanks for the answer. However, if I exclude the `window-purpose` package, then the `popwin` feature, which is enabled by `pupo`, is impacted. Is there another way to do it?

**Comment by TheBB** [comment]
It should not, the popwin package is configured in Spacemacs separately from window-purpose.

https://github.com/syl20bnr/spacemacs/blob/develop/layers/+spacemacs/spacemacs-visual/packages.el#L66

**Comment by bmag** [comment]
Might want to exclude `spacemacs-purpose-popwin` package as well and disable popwin for `spacemacs-purpose` layer (don't remember if we can disable a package for a certain layer, though). spacemacs-purpose layer adds an advice for `popwin` that depends on `window-purpose`. (see [here](https://github.com/syl20bnr/spacemacs/blob/08561d8631153cee93c7348adb515aa217b5df7f/layers/%2Bspacemacs/spacemacs-purpose/packages.el#L78))

**Comment by tddsg** [comment]
Oh, the thing is that I still want to use `spacemacs-purpose-popwin`. I just don't want Emacs automatically set a window to be dedicated after a while. Is there any reasonable way to do it?

**Comment by bmag** [comment]
> Emacs automatically set a window to be dedicated after a while.

Not sure what you mean by that. Do you mean dedicated to a buffer or dedicated to a purpose? (when `purpose-mode` is enabled, a "!" next to the window's purpose in the mode-line indicates purpose-dedicated, and "#" indicates buffer-dedicated)
Besides, windows aren't supposed to automatically become dedicated, except for the popup windows, as far as I remember.

Anyway, you don't need `spacemacs-purpose-popwin` when `purpose-mode` is disabled. It's just meant to replicate popwin's popup windows in way more compatible with `window-purpose`. Is there something specific you're trying to accomplish?

**Comment by tddsg** [comment]
Hi, thank you for your response.

By the following

> Emacs automatically set a window to be dedicated after a while.

I mean that when I open a buffer, edit it, and keep it open on a window for a long time (a few hours), and then try switch to another buffer, Emacs reports errors like:

```
previous-buffer: Window is strongly dedicated to its buffer
next-buffer: Window is strongly dedicated to its buffer

```

Basically, I cannot open any other buffer on that window.

I customized the spaceline and could not see characters `!` or `#`. Are they enabled by default?

**Comment by bmag** [comment]
Spacemacs isn't supposed to make a window buffer-dedicated just because it's open for a long time. Something else is triggering it, possibly a bug or a bad configuration. Keep in mind that it isn't necessarily caused by window-purpose.

Anyway, you should be able to exclude `window-purpose` and `spacemacs-purpose-popwin` and use plain old popwin instead.

> Are they enabled by default?

Yes, if your spaceline has the "purpose" segment. If you want to keep using window-purpose (and spacemacs-purpose-popwin), please add this segment to your spaceline. It will help you find out what causes the window to become buffer-dedicated and provide us with better data to understand the problem.

**Comment by tddsg** [comment]
Thank you for the suggestion. I monitor the issue to find out the root cause.

**Comment by et2010** [comment]
Do you guys notice the performance impact caused by purpose? Sometimes It makes company completion barely usable so I have to disable it.

**Comment by tddsg** [comment]
I don't encounter such issue. But does the problem with company completion happen with all major modes or in only some specific modes?
