### ISSUE TITLE
avy-with

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#9129]
(defun xged/avy-goto-word-0-in-line (arg) (interactive "P")
       (avy-with avy-goto-word-0 (avy--generic-jump avy-goto-word-0-regexp arg avy-style
                                                    (line-beginning-position) (line-end-position))))

After recent Spacemacs update-pkg&pull (month?) function above does not work: `xged/avy-goto-word-0-in-line: Symbol’s function definition is void: avy-with
`

**Comment by TheBB** [comment]
https://github.com/abo-abo/avy/blob/master/avy.el#L496-L511

It's a macro, and it's not autoloaded. Probably you are using your function before avy is loaded.

**Comment by xged** [comment]
Function works only (?) after another `avy` command is called (like `SPC jj`).

**Comment by TheBB** [comment]
Yeah that's what I'm saying. `avy-with` is only available after avy is loaded. You're running your function before avy is loaded. Cue error.

**Comment by xged** [comment]
How to load `avy-with`? (likely a newb question)

**Comment by TheBB** [comment]
`(require 'avy)`
