### ISSUE TITLE
Go layer not working and error on startup in develop branch

### ISSUE THREAD

**Issue by horrorvacui** [syl20bnr/spacemacs#913]
Using develop branch leaves me with missing go layer bindings and the following error on startup:
```
An error occurred while initializing go-oracle (error: (void-variable company-backends))
```

**Comment by Funnnny** [comment]
I have proposed a PR with this fixed. Can you test?

**Comment by horrorvacui** [comment]
It's fixed. Thanks alot @Funnnny.
