### ISSUE TITLE
Smartparens feature that highlights sibling paren not working in normal mode

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#9131]
#### Description :octocat:
Smartparens feature that highlights sibling paren not working in normal mode

#### Reproduction guide :beetle:
- Start Emacs
- `SPC f e d` - or open any lisp mode file (Clojure/Emacs lisp)
- In evil-normal-mode, navigate cursor to any (balanced) s-exp,
- Notice that when cursor is at opening paren it highlights the closing paren
- Navigate to a closing paren

*Observed behaviour:* :eyes: :broken_heart:
- Sibling (opening) paren is some cases is not being highlighted 

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. a38d7178)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((org :variables org-enable-reveal-js-support t org-enable-bootstrap-support t org-enable-github-support t :packages
      (not org-present))
 csv yaml emacs-lisp clojure haskell lua javascript
 (html :packages
       (not pug-mode slim-mode))
 (markdown :packages
           (not mmm-mode)
           :variables markdown-live-preview-engine 'vmd)
 (shell-scripts :packages
                (not fish-mode))
 (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 syntax-checking spell-checking helm fasd osx restclient emoji search-engine imenu-list docker
 (shell :variables shell-enable-smart-eshell t comint-scroll-show-maximum-output nil comint-move-point-for-output nil)
 (ibuffer :variables ibuffer-old-time 8)
 git
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 (github :packages
         (not magit-gh-pulls)
         :variables gist-view-gist t magithub-api-timeout 5)
 ag-dired ag-general ag-synonyms ag-org ag-clojure ag-web)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by agzam** [comment]
https://github.com/Fuco1/smartparens/issues/758 Might be related

**Comment by Fuco1** [comment]
I have made some changes to the code 3-4 days ago, it was probably caused by that change.  I will look into it and/or revert the change to get back to the working state.

**Comment by agzam** [comment]
@Fuco1 what's the status on this? this is fairly critical for many users. Would it be safe to provide a workaround by pinning the previous version of the package?

**Comment by Fuco1** [comment]
I have no idea how spacemacs packaging works, but if you install 1.10.1 you will get a version that works.

I'm just about to start working on the issue, I have about an hour of time but that should be sufficient.

**Comment by agzam** [comment]
@Fuco1 I apologize for rushing you into fixing it.
@TheBB can you please advice how to pin a specific version of smartparens (`1.10.1`), I tried by using `:location (recipe :fetcher github` etc. in `dotspacemacs-additional-packages` but that didn't seem to work, some other packages throwing warnings

**Comment by agzam** [comment]
I can't find a way to pin down specific version: https://emacs.stackexchange.com/questions/33742/pinning-version-of-a-core-package

**Comment by Fuco1** [comment]
@agzam No worries, I literally just opened github at that minute to check the issue and found a notification from you.

**Comment by Fuco1** [comment]
Should be fixed in master, please try it out!

**Comment by duianto** [comment]
It works now, ty @Fuco1 👍

**Comment by agzam** [comment]
yup, it works, thanks @Fuco1!
