### ISSUE TITLE
Adding tests for #9073

### ISSUE THREAD

**Issue by lazywithclass** [syl20bnr/spacemacs#9132]
I am adding tests for this https://github.com/syl20bnr/spacemacs/pull/9073 I think I've added enough unit tests, now I'm trying to add functional tests, so that the behaviour of the functionality is preserved.

I am having a few problems realising how to use the kill ring, previously I was used to

 * `yy` - put a line in the kil ring
 * `p` followed by a `C-j` or `C-k` if I wanted to move up or down in the ring

What was happening was that the old line was being overwritten by the new one, now `C-j` and `C-k` just have another behaviour entirely. `C-p` and `C-n` kind of work but the text is appended, not replaced.

`  dotspacemacs-enable-paste-transient-state` is set to `nil`.

So... all of this to say that I need to understand the feature to properly test it :D any help in this direction would be highly appreciated.

**Comment by duianto** [comment]
The pasted text doesn't get appended for me.

## On both the latest master and develop branches:
After pasting with `p` or `P`, then `C-n` and `C-p` replaces the pasted text with the next/previous item on the kill ring `SPC h d v` `kill-ring` `RET`. 

### With the paste transient state enabled: 
`dotspacemacs-enable-paste-transient-state t`

Right after pasting with either `p` or `P`, then `C-j` and `C-k` replaces the previously pasted text, until a key other than `p`, `P`, `C-j` or `C-k` is pressed. `C-n` and `C-p` still works the same way as they did before enabling the paste transient state.

These are bound to the same commands in all 4 cases:
`C-j` `electric-newline-and-maybe-indent`
`C-k` `kill-line`

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145) and
- Spacemacs branch: develop (rev. cd3aa05f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey colors emacs-lisp git helm markdown
                 (org :variables org-agenda-files
                      '("c:/Users/Username/Documents/"))
                 version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by lazywithclass** [comment]
@duianto sorry I didn't get your reply, I thought the bug was fixed in #9073, isn't this the case?

**Comment by duianto** [comment]
>What was happening was that the old line was being overwritten by the new one, now C-j and C-k just have another behaviour entirely. C-p and C-n kind of work but the text is appended, not replaced.

>I need to understand the feature to properly test it :D any help in this direction would be highly appreciated.

I must have misunderstood, I thought you were saying that the key bindings didn't work as expected. So I explained what was happening when I use them.

The #9073 issue has been fixed, `C-n` and `C-p` now cycles through the kill-ring as expected.

**Comment by lazywithclass** [comment]
Ah I see sorry, so I get that now I should be using `C-n` and `C-p`, but how can I make it so that lines are replaced and not appended?

BTW, why is it that we use `n` and `p` instead of `j` and `k`? I thought the latter where the default concepts for down and up.

**Comment by duianto** [comment]
The previously pasted text seems to be replaced by default, could it be a custom configuration on your end?

Your right it might be more consistent to use `C-j` and `C-k`, since they also are used in the paste transient state.

It might just be inertia, `C-n` and `C-p` has been used for a couple of years. 

This seems to be the commit (Mar 18, 2011) in the evil package when they key bindings were added:
`` Add `evil-paste-pop' and `evil-paste-pop-next' `` https://github.com/emacs-evil/evil/commit/72631b9a27901e54e0ccde9d7946a1270e74daeb

**Comment by duianto** [comment]
I just tested it in Ubuntu 16.10 running in VirtualBox with Windows 10 as host, and `C-n` and `C-p` also replaces the pasted text.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. cd3aa05)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp git markdown org version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS LIBSYSTEMD

**Comment by lazywithclass** [comment]
Then it is just me, well thank you for the much appreciated help nonetheless! I will proceed to test this on a different environment.
