### ISSUE TITLE
Recommending different Emacs port for macOS

### ISSUE THREAD

**Issue by 0xCMP** [syl20bnr/spacemacs#9137]
I personally use this port: https://github.com/railwaycat/homebrew-emacsmacport

It's maintained at https://bitbucket.org/mituharu/emacs-mac/overview

It has a lot of good improvements for macOS such as sub-pixel scrolling and I think it should be the recommended Emacs port.

Thoughts?

**Comment by achikin** [comment]
I've tried this one and found it's integration with MacOSX worse than my current one downloaded from here https://emacsformacosx.com/ . There are some small issues like railwaycat version tends to run text version of emacs when started from the terminal. It's not crucial but very annoying for me. Yes, railwaycat version looks better "on paper" but the overall experience was not so pleasant for me.

**Comment by 0xCMP** [comment]
Oh yeah, that's an issue I have too. I usually use `emacs_client -n` to open stuff from the terminal, but it'd be way nicer to be able to start emacs from the terminal for debugging.

I really love the subpixel scrolling because it makes everything feel very fluid. Does that version support things like that and improved text rendering?

**Comment by achikin** [comment]
> Does that version support things like that and improved text rendering?
I couldn't eyeball any real difference in text rendering. Smooth scrolling either does not exist or I don't know how to turn it on.

**Comment by LdBeth** [comment]
In the bitbucket repo you can find a list about the improvements.
I don't think terminal users would like this port. Most improvements are for GUI users.

> Smooth scrolling either does not exist or I don't know how to turn it on.

By default sub-pixel smooth scrolling is on, and I believe the smooth scrolling in that reddit thread is not the same thing.

**Comment by dangom** [comment]
Sub-pixel smooth scrolling [has been implemented in Elisp](https://github.com/emacs-mirror/emacs/blob/78fe5abc11c9ff237615d6884aed159229377cc5/lisp/pixel-scroll.el) and is [already available at the master branch of Emacs](https://github.com/emacs-mirror/emacs/blob/1886246f6f40b8c376467f71605141035959cae0/etc/NEWS#L907). If waiting for Emacs 26 is too much, you can always load the file and activate the minor mode.

**Comment by 0xCMP** [comment]
Interesting, yea I do not use Emacs much in the terminal. Mainly via the GUI provided by the railway port.

Nice that there is a minor mode now which gets the pixel scrolling.

**Comment by nixmaniack** [comment]
Spacemacs used to recommend railwaycat's port but it was changed in [this commit](https://github.com/syl20bnr/spacemacs/commit/fa5e66c799e74325fbd513cdfa9348b53e023491) based on discussion [here](https://github.com/syl20bnr/spacemacs/issues/4955).

I don't see that opinion changing.

**Comment by LdBeth** [comment]
Mituharu's mac port do fix some issue for me, like the crash on closing a tab, and the RGB color display (remember the ugly Spaceline separator?).
It also support `org-protocol` natively and can perfectly get env var for shell.
