### ISSUE TITLE
Merge conflicts...  core/info/release-notes/0.200.txt

### ISSUE THREAD

**Issue by usharf** [syl20bnr/spacemacs#9139]
What's the best way to deal with this --rebase attempt... no local changes were made...

```sh
Applying: Autumnal cleanup finished
Using index info to reconstruct a base tree...
M	core/info/release-notes/0.200.txt
Falling back to patching base and 3-way merge...
Auto-merging core/info/release-notes/0.200.txt
CONFLICT (content): Merge conflict in core/info/release-notes/0.200.txt
error: Failed to merge in the changes.
Patch failed at 0025 Autumnal cleanup finished
The copy of the patch that failed is found in: .git/rebase-apply/patch
```

**Comment by TheBB** [comment]
Best way (only way?) to deal with conflicts is to resolve then manually. Hard to say more since I don't know what you are rebasing, why, or what the conflict looks like.

**Comment by robbyoconnor** [comment]
There really shouldn't be conflicts -- don't try to rebase `develop` onto `master` -- or vice versa...unless you like pain.

**Comment by usharf** [comment]
Yes. That's what I mean . Didn't understand why I was seeing conflicts. Maybe I did accidentally merge into master.... solved manually. 
Thanks for the tip I'll consider that next rebase.

**Comment by robbyoconnor** [comment]
If you're on `master`, only rebase against `upstream/master` and similarly for `develop`.
