### ISSUE TITLE
Opening d file freezes Emacs

### ISSUE THREAD

**Issue by TeddyDD** [syl20bnr/spacemacs#9143]
#### Description :octocat:
When I open dlang file Emacs freezes

#### Reproduction guide :beetle:
- Start Emacs
- install d layer
- open any file with .d extension

*Observed behaviour:* :eyes: :broken_heart:

Emacs stops responding to any input. Line on the bottom of screen shows
`Loading /home/user/.emacs.d/.cache/company-statistic-cache.el (source)... done`

After about one minute Emacs unfreezes and shows following error messange
```
Mon Jun 26 10:31:29 2017
"dcd-client --port 9166 -I/usr/include/dlang/dmd" failed.
Error type is: Unable to connect socket : Connection timed out
```

I have `dcd` `dmd` and `gdc` installed.

*Expected behaviour:* :heart: :smile:

Emacs should open file quickly.

#### System Info :computer:
- OS: gnu/linux - Arch
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(d javascript
   (erc :variables erc-server-list
        '(("irc.freenode.net" :port "6697" :ssl t :nick "TeddyDD"))
        erc-autojoin-channels-alist
        '(("freenode.net" "#emacs" "#godotengine" "#kobuge")))
   shell-scripts
   (c-c   :variables c-c  -enable-clang-support t)
   clojure emoji spotify
   (python :variables python-enable-yapf-format-on-save t)
   (go :variables gofmt-command "goimports" go-use-gometalinter nil)
   html helm
   (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
   emacs-lisp git
   (markdown :variables markdown-live-preview-engine 'vmd)
   (org :variables org-enable-bootstrap-support t org-enable-reveal-js-support t)
   spell-checking syntax-checking latex)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by CeleritasCelery** [comment]
what happens if you disable the autocomplete layer?

**Comment by TeddyDD** [comment]
I can open file without issue.
