### ISSUE TITLE
typescript: File mode specification error: (void-function company-mode-on)

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#9145]
#### Description :octocat:
Opening `.tsx` file prints error
```
File mode specification error: (void-function company-mode-on)
```
No such problem from `.ts` files.

#### Reproduction guide :beetle:
- Start Emacs
- open `file.tsx`

There seems to be some difference whether `.ts` or `.tsx` file was opened first.

*Observed behaviour:* :eyes: :broken_heart:
`(void-function company-mode-on)` error.

*Expected behaviour:* :heart: :smile:
No errors.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.8
- Spacemacs branch: master (rev. bd7ef98e4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv emacs-lisp
     (auto-completion :variables auto-completion-enable-help-tooltip t)
     colors dash git html imenu-list javascript markdown org
     (osx :variables osx-use-option-as-meta nil)
     puppet python react restclient syntax-checking typescript version-control yaml)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-function company-mode-on)
  (company-mode-on)
  (progn (company-mode-on))
  (if (configuration-layer/package-usedp (quote company)) (progn (company-mode-on)))
  (progn (tide-setup) (flycheck-mode 1) (eldoc-mode 1) (if (configuration-layer/package-usedp (quote company)) (progn (company-mode-on))))
  (if (and (buffer-file-name) (string-equal "tsx" (file-name-extension (buffer-file-name)))) (progn (tide-setup) (flycheck-mode 1) (eldoc-mode 1) (if (configuration-layer/package-usedp (quote company)) (progn (company-mode-on)))))
  (lambda nil (if (and (buffer-file-name) (string-equal "tsx" (file-name-extension (buffer-file-name)))) (progn (tide-setup) (flycheck-mode 1) (eldoc-mode 1) (if (configuration-layer/package-usedp (quote company)) (progn (company-mode-on))))))()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook web-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook web-mode-hook))
  run-mode-hooks(web-mode-ho
```

**Comment by aaronjensen** [comment]
@tko can you double check this again on latest develop please?

**Comment by tko** [comment]
Seems working on develop (0fa3658cd8e283825dcd0a54ce1579dec55eb568)

**Comment by aaronjensen** [comment]
Great! @syl20bnr fixed on develop

**Comment by rgtk** [comment]
0.200.13 and problem still persists.

**Comment by aaronjensen** [comment]
@rgtk Yeah, it's fixed in develop. It can sometimes take a year or more for develop to be merged into master, so I tend to recommend people use develop.

**Comment by rgtk** [comment]
Oh, I didn't know that cycles are that long. Thank you.
