### ISSUE TITLE
The layer graphviz keeps installing the package graphviz-dot-mode on startup

### ISSUE THREAD

**Issue by magnetophon** [syl20bnr/spacemacs#9147]
#### Description :octocat:
The layer ``graphviz`` keeps installing the package ``graphviz-dot-mode`` on startup

#### Reproduction guide :beetle:
- add layer ``graphviz``
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
- see package being installed at every subsequent start of Emacs.

*Expected behaviour:* :heart: :smile:
No packages being installed after the first install

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 907306a1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python html vimscript clojure helm
        (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
        better-defaults emacs-lisp
        (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
        faust git graphviz markdown nixos org shell semantic spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by CeleritasCelery** [comment]
I am experiencing the same thing.
