### ISSUE TITLE
typescript: should not require/expect globally installed tslint

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#9148]
While the typescript layer documentation does state <sub>(that should be just one command IMO)</sub>
> If you want linting run: `npm install -g typescript` `npm install -g tslint`

global installation of typescript/tslint should not be required.

Instead the project-local version should be used. In addition to _not_ requiring any additional manual steps it has the benefit of applying the exact same rules as when the project is built, no deviations due to global installation being newer/older than what the project expects.

I believe there's `add-node-modules-path` that helps with making use of project-local executables.

**Comment by Miciah** [comment]
@tko, it looks like #8621 added the functionality that you describe.  Is the desired functionality in place, and does this issue concern the documentation only?

**Comment by tko** [comment]
Yes and no, kind of. It doesn't work out of the box. And while it's possible tweak an option, that workaround has security problems (#9047, which explains not being enabled by default.)
