### ISSUE TITLE
cpu always top to 100% !

### ISSUE THREAD

**Issue by chenyangguang** [syl20bnr/spacemacs#9150]
If you are posting about a *bug* please close this issue and open a new one
using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs. If the
bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template)
You can delete this message to start typing.

I have use spacemacs about 10 months. It always take up  cpu 100% ! why ? 

(1) Os: `Linux v 3.13.0-110-generic #157-Ubuntu SMP Mon Feb 20 11:54:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
(2) emacs version: 
```
> ➜ ✗ emacs --version
> GNU Emacs 25.1.1
> Copyright (C) 2016 Free Software Foundation, Inc.
> GNU Emacs comes with ABSOLUTELY NO WARRANTY.
> You may redistribute copies of GNU Emacs
> under the terms of the GNU General Public License.
> For more information about these matters, see the file named COPYING.
```
(3) spacemacs branch: master 
git log 
``` 
> commit 8e1af145480d53e8d32cdff2c83291889903164b
> Author: syl20bnr <sylvain.benner@gmail.com>
> Date:   Thu Apr 6 23:12:47 2017 -0400
> 
>     Fix typo in release note
> 
> commit fcc551fa38ad87388e4baafcf40f3cb5f6c17ef9
> Author: syl20bnr <sylvain.benner@gmail.com>
> Date:   Thu Apr 6 23:07:36 2017 -0400
> 
>     Bump version to 0.200.9 and add release note
> 
```

Any one have the same problem like me ?

**Comment by CeleritasCelery** [comment]
This has been a common problem for some users, including me. Take a look at #8462. a lot of people have found that `(setq dotspacemacs-mode-line-unicode-symbols nil)` works as fix, if not that then disabling the spaceline package should work.
