### ISSUE TITLE
Not responding after pressing & in normal mode.

### ISSUE THREAD

**Issue by danielstaleiny** [syl20bnr/spacemacs#9152]
#### Description :octocat:
Spacemacs freeze when I am in normal mode and it doesn't respond to anything. 
#### Reproduction guide :beetle:
- Start Emacs
normal mode in evil-mode and press shift+& (shift+7) which results to &.
*Observed behaviour:* :eyes: :broken_heart:
 Emacs freezes and you curser turns to processing circle.  Only option is to kill app. 
*Expected behaviour:* :heart: :smile:
Not freeze..
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown html helm auto-completion better-defaults emacs-lisp git github latex react docker ranger javascript org
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          syntax-checking restclient version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by CeleritasCelery** [comment]
works fine for me. What does `describe-key` tell you that `&` is bound too?

**Comment by danielstaleiny** [comment]
It seems that it does happen only in **org-mode**.  I press & and then arrow down/up  and it freezes.
