### ISSUE TITLE
How to disable evil search highlighting?

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#9154]
`dotspacemacs-excluded-packages '(evil-search-highlight-persist)` does not work.

**Comment by CeleritasCelery** [comment]
i know you can use `SPC s c` to get rid of it when you want, but that won't disable it.

**Comment by kemalbuyukkaya** [comment]
Alternatively, you can use :noh ( or :nohlsearch) to clear the current search highlights. However, if you want to disable it completely, @CeleritasCelery's solution should work.

**Comment by xged** [comment]
`(setq global-evil-search-highlight-persist nil)` does not work for me as well. I will create a bug report later (if I am the only one).

**Comment by xged** [comment]
Solved it for me: `(setq-default evil-ex-search-highlight-all nil)`

**Comment by CeleritasCelery** [comment]
I tested it and `(setq global-evil-search-highlight-persist nil)` didn't seem to work for me either. However `dotspacemacs-excluded-packages '(evil-search-highlight-persist)` works fine. Verify that it is removed by looking in the package list.
