### ISSUE TITLE
Mouse-1 clicking on file link in home buffer inserts part of org capture template into opened file.

### ISSUE THREAD

**Issue by zaript** [syl20bnr/spacemacs#9158]
#### Description :octocat:
When I open any file by mouse-1 click on its link in recent files in *spacemacs* buffer part of my org todo capture template gets inserted into the file.
There is no such problem, if I open the file by RET on the file link.

#### Reproduction guide :beetle:
- Start Emacs
- Have org layer installed.
- Add capture template to user configuration:
  ```elisp
    (setq org-capture-templates
          '(("t" "Todo" entry (file org-default-notes-file)
            "* TODO %?\n:PROPERTIES:\n:CREATED: %U\n:FROM: %a\n:END:\n")
            ("n" "Notes" entry (file org-default-notes-file)
            "* %? :NOTE:\n:PROPERTIES:\n:CREATED: %U\n:FROM: %a\n:END:\n")))
  ```
- Open *spacemacs* buffer (have projects, recents, agenda, todos enabled in config).
- Mouse-1 click on any recent file link.

*Observed behaviour:* :eyes: :broken_heart:
File is opened and string "?\n:PROPERTIES:\n:CREATED: %U\n:FROM: %a\n:END:\n" get inserted at point.

*Expected behaviour:* :heart: :smile:
File is opened.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(evil-commentary evil-cleverparens evil-snipe vinegar themes-megapack
                 (c-c++ :variables c-c++-enable-clang-support t)
                 python csv bibtex latex pdf-tools fasd racket
                 (ranger :variables ranger-override-dired t)
                 finance shell-scripts helm ibuffer
                 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-help-tooltip 'manual-entry auto-completion-enable-sort-by-usage t :disabled-for org erc)
                 better-defaults emacs-lisp git version-control markdown org
                 (spell-checking :variables spell-checking-enable-by-default nil)
                 (syntax-checking :variables syntax-checking-enable-by-default nil))
```
- System configuration features: JPEG NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
This seems to be a duplicate of this issue:
**Auto paste into the files opened by mouse-click the item below Recent Files in Spacemacs buffer** #5435

This https://github.com/syl20bnr/spacemacs/issues/5435#issuecomment-195862080 seems to be the current solution.

**Comment by zaript** [comment]
Thank you, this is indeed the duplicate. Sorry for not discovering the original issue.
