### ISSUE TITLE
Slack settings cannot be loaded: void-function slack-register-team

### ISSUE THREAD

**Issue by mapolone** [syl20bnr/spacemacs#9159]
#### Description :octocat:
Slack configuration in ~/.spacemacs cannot be loaded due to the following error:
Error loading .spacemacs: (void-function slack-register-team)

#### Reproduction guide :beetle:
- Start Emacs
- Add slack layer under dotspacemacs/layers
- Add configuration snippet under dotspacemacs/user-config as per related page, changing settings as necessary:
  https://github.com/syl20bnr/spacemacs/tree/master/layers/+chat/slack
- Restart Emacs in order to install necessary package(s)

*Observed behaviour:* :eyes: :broken_heart:
- During Emacs restart, a configuration error is shown

*Expected behaviour:* :heart: :smile:
- Restart and connect successfully to Slack team

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm mu4e auto-completion python shell-scripts markdown git slack
      (elfeed :variables rmh-elfeed-org-files
              (list "~/.emacs.d/private/elfeed.org"))
      (org :variables org-projectile-file "~/.emacs.d/private/TODO.org")
      (erc :variables erc-server-list
           '(("chat.freenode.net" :port "6697" :ssl t :nick "mapolo")))
      (shell :variables shell-default-shell 'term shell-default-term-shell "/bin/bash" shell-default-height 45 shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
None required.
```

**Comment by jsoo1** [comment]
I'm not experiencing this, exactly, but I do have load-order issues with the slack layer as well.  For me `slack-ws-close` is nil when calling `load-file` from `user-config`.  I believe that either the documentation needs to change or the layer needs to be updated to deal with lazy-loading properly.

**Comment by jsoo1** [comment]
Does using `with-eval-after-load` help? Like:
```elisp
(with-eval-after-load 'slack (load-file "~/.emacs.d/private/slack-config.el"))
```

**Comment by mapolone** [comment]
I'll try it as soon as possible, thanks!
