### ISSUE TITLE
Symbol’s function definition is void: spacemacs|add-company-backends

### ISSUE THREAD

**Issue by jackkamm** [syl20bnr/spacemacs#9160]
#### Description :octocat:
On startup with auto-completion layer disabled, I get several Error/Warning messages from `use-package` saying that `Symbol’s function definition is void: spacemacs|add-company-backends`

This error appeared after commit https://github.com/syl20bnr/spacemacs/commit/08561d8631153cee93c7348adb515aa217b5df7f

#### Reproduction guide :beetle:
- Disable auto-completion layer
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
```
Error (use-package): company-anaconda :init: Symbol’s function definition is void: spacemacs|add-company-backends
Error (use-package): company-auctex :init: Symbol’s function definition is void: spacemacs|add-company-backends
Error (use-package): company-shell :init: Symbol’s function definition is void: spacemacs|add-company-backends
```

*Expected behaviour:* :heart: :smile:
No error/warning messages

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 07272cc7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(csv yaml javascript markdown bibtex latex octave
     (ess :variables ess-enable-smart-equals t)
     ipython-notebook python shell-scripts
     (shell :variables shell-default-shell 'multi-term)
     org emacs-lisp git helm ibabel my-spacemacs-layer)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by sound2gd** [comment]
I have the save issue 
![image](https://user-images.githubusercontent.com/10735388/28000018-9ba9faee-6555-11e7-93c0-8cd1fbef51a0.png)

**Comment by jackkamm** [comment]
After recently updating develop branch I no longer have this issue anymore so I am closing

**Comment by jiahut** [comment]
when encounter  ` Symbol’s function definition is void:  xxx ` problem 

> `cd ~/.emacs.d/elpa/`
> `rm -rf *xxx*`

restart

**Comment by tomtsang** [comment]
@sound2gd 
Have you solved this problem? 
`Symbol’s function definition is void: spacemacs|add-company-backends`

**Comment by jukkaaro** [comment]
The master branch is still broken (tested with emacs 25.3.2) while checking out the develop branch seems to fix the issue. *Please* could someone aware of the changes made on the develop branch bring the changes that fixes this issue also the master branch? This is most annoying, there might be users around for whom the develop branch is not an option.

**Comment by ashrasmun** [comment]
Error (use-package): company-rtags/:init: Symbol’s function definition is void: spacemacs|add-company-backends
Error (use-package): flycheck-rtags/:init: Symbol’s value as variable is void: c-c++-mode-hooks

:broken_heart:

GNU Emacs 26.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8) of 2019-04-12
Spacemacs 0.200.13@26.2
Company version: 0.9.10
Flycheck version: 32snapshot (package: 20190619.1410)

**Comment by duianto** [comment]
@ashrasmun It seems from two of the comments above, that it's working on the `develop` branch. Therefore it will most likely work on the `master` branch when the next major version is released (I don't have any insight into when that is).
