### ISSUE TITLE
Ivy/Helm results have a line full of terminal escape codes

### ISSUE THREAD

**Issue by mkaito** [syl20bnr/spacemacs#9161]
#### Description :octocat:
Artifacts in helm/ivy. See screenshot.

![2017-06-29-163648_1920x1057_scrot](https://user-images.githubusercontent.com/20434/27696602-f927e8a8-5ce9-11e7-8b40-cb86b00271ef.png)

#### Reproduction guide :beetle:
- Start Emacs
- Navigate to a project
- Press [SPC /] or [SPC p f] and type something

*Observed behaviour:* :eyes: :broken_heart:
There is always one line full of what looks to be terminal color escape
sequences. Trying to "open" it results in emacs visiting a nonexistent file (of
course).

This happens with both helm and ivy.

This happens for both finding files or searching via grep.

This happens after clearing the cache.

Executing the underlying command (ag/rg, or git ls-files) outside of emacs does
not display such a thing.

*Expected behaviour:* :heart: :smile:
The result list to contain only actual files or matched lines.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 907306a11)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((org :variables org-projectile-file "~/notes/projects.org")
 (ruby :variables ruby-version-manager 'rbenv ruby-test-runner 'rspec)
 (shell :variables shell-default-shell 'eshell shell-default-height 35)
 (syntax-checking :variables syntax-checking-enable-tooltips nil)
 (auto-completion :variables auto-completion-private-snippets-directory "~/dev/dotfiles/spacemacs-snippets" auto-completion-complete-with-key-sequence "kj")
 ansible emacs-lisp evil-commentary floobits git html ivy javascript markdown my-eshell my-org nevermore nginx shell-scripts version-control vinegar yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
Not relevant. No errors shown anywhere.

**Comment by CeleritasCelery** [comment]
does this happen with stock Emacs + helm?

**Comment by mkaito** [comment]
Sorry, work being crazy right now. Will do some debugging soon.
