### ISSUE TITLE
Cannot build haskell files using Stack.

### ISSUE THREAD

**Issue by randre03** [syl20bnr/spacemacs#9165]
#### Description :octocat:
Haskell: Using Stack and when I execute `haskell-process-cabal-build` (keyboard shortcut `,cb`) it indicates it cannot find the .cabal file (which exists).

#### Reproduction guide :beetle:
- Start Emacs
- create a haskell project with Stack from command line
- open haskell file in emacs
- run haskell-process-cabal-build

*Observed behaviour:* :eyes: :broken_heart:
The following message appears in new window:

`Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
cabal: No cabal file found.
Please create a package description file <pkgname>.cabal`

Note: I can sucessfully build the project with stack from command line.

*Expected behaviour:* :heart: :smile:
Stack should be used to build the project.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 0f85e60c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence nil auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 better-defaults
 (clojure :variables clojure-enable-fancify-symbols t)
 emacs-lisp git github
 (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "fundamental" haskell-process-type 'stack-ghci)
 (ibuffer :variables ibuffer-group-buffers-by 'modes)
 idris ivy java org osx parinfer rust scala semantic
 (shell :variables shell-default-shell 'shell shell-default-height 50 shell-default-position 'bottom)
 spell-checking sql
 (syntax-checking :variables syntax-checking-enable-tooltips nil flycheck-scalastylerc
                  (expand-file-name "/Users/randre03/scalastyle_config.xml"))
 version-control yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by arianvp** [comment]
I got the same issue with my cabal project
