### ISSUE TITLE
Wrong key bindings for Holy Mode in Git interactive rebase buffer

### ISSUE THREAD

**Issue by dsedivec** [syl20bnr/spacemacs#9169]
#### Description :octocat:

Git interactive rebase buffer comments give incorrect key bindings in Holy Mode.

#### Reproduction guide :beetle:
- Start Emacs with Spacemacs in Holy Mode
- Start an interactive rebase in Magit (e.g. `M-x magit-status RET l l`, move down a few commits, `r i`)

*Observed behaviour:* :eyes: :broken_heart:

Comments about key bindings in the rebase buffer:

```
# Commands:
# p        pick = use commit
# r        reword = use commit, but edit the commit message
# e        edit = use commit, but stop for amending
# s        squash = use commit, but meld into previous commit
# f        fixup = like "squash", but discard this commit's log message
# x        exec = run command (the rest of the line) using shell
# d        drop = remove commit
# u        undo last change
# C-c C-c  tell Git to make it happen
# C-c C-k  tell Git that you changed your mind, i.e. abort
# k        move point to previous line
# j        move point to next line
# M-k      move the commit at point up
# M-j      move the commit at point down
# RET      show the commit at point in another buffer
```

Some of these are incorrect.  For example, `p` moves to the previous commit, it does not "pick" a commit.  `M-k` does not move a commit up.  Others may also be wrong.

*Expected behaviour:* :heart: :smile:

Normally these comments are added/corrected by `git-rebase-mode-show-keybindings`, but merely loading evil-magit removes this function from `git-rebase-mode-hook`.  If you either don't load evil-magit or else restore this function as in

```
;; This is the hook that evil-magit adds.
(remove-hook 'git-rebase-mode-hook 'evil-magit-add-rebase-messages)
(add-hook 'git-rebase-mode-hook 'git-rebase-mode-show-keybindings t)
```

then a rebase buffer will explain the correct key bindings:

```
# Commands:
# C-c C-c  tell Git to make it happen
# C-c C-k  tell Git that you changed your mind, i.e. abort
# p        move point to previous line
# n        move point to next line
# M-p      move the commit at point up
# M-n      move the commit at point down
# SPC      show the commit at point in another buffer
# RET      show the commit at point in another buffer and select its window
# C-_      undo last change
# k        drop the commit at point
# y        insert a line for an arbitrary commit
# z        add noop action at point
# <normal-state> p, c pick = use commit
# <normal-state> r, r, w reword = use commit, but edit the commit message
# <normal-state> e, e, m edit = use commit, but stop for amending
# <normal-state> s, s squash = use commit, but meld into previous commit
# <normal-state> f, f fixup = like "squash", but discard this commit's log message
# <normal-state> x, x exec = run command (the rest of the line) using shell
```

I'm not sure if it would be better to not load evil-magit if the user is in Holy Mode, or if there's something evil-magit should do to leave the default comments alone.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.50.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 907306a1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :variables auto-completion-enable-sort-by-usage t)
 better-defaults emacs-lisp git markdown org spell-checking syntax-checking version-control c-c   chrome clojure common-lisp csv dash deft html javascript latex
 (osx :variables osx-command-as 'super osx-option-as 'meta osx-right-option-as 'none)
 pandoc python restructuredtext ruby shell shell-scripts sql yaml)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by lyallcooper** [comment]
This seems to still be an issue on the latest `develop` branch.

Another solution is to add `evil-collection` (which is the source of the `evil-collection-magit-add-rebase-messages` function) to `dotspacemacs-excluded-packages` in the `.spacemacs` file.

I'm going to see if I can put a fix in the git layer itself.
