### ISSUE TITLE
Emacs leader key is not set in holy-mode

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#917]
The new key binding `M-n` is not set when `holy-mode` is activated. Also, this key binding is used by `magit` (and possibly other modes) to go  to next section of the same level. To solve this problem, I propose that we should use `M-m` for Emacs leader key (since it is bound by default, it's likely that most packages avoid it) and `C-c m` for major mode leader key, since `C-c m` is free by default, and `C-c` + <key> is reserved for users by Emacs convention.

**Comment by tuhdo** [comment]
As far as I know, the only conflict is in `magit` and if we can bind it to another key, then we are fine with current key bindings i.e. changes `M-n` and `M-p` to `C-n` and `C-p` because these two bind to the default `next-line` and `previous-line`.

**Comment by syl20bnr** [comment]
Update you dotfile to define the new variables, see the template in `core/template/.spacemacs.template`.

I'll think again about the default key bindings. I want the limit as much as possible a domino effect.

**Comment by tuhdo** [comment]
You have a few choices:

- `C-<return>` is empty.
- `M-RET` is empty.
- `C-j` is almost redundant with `RET`
- `C-m` is redundant with `RET`. 
- `M-m`, which is replaceable.
- `M-n`, free by default but `magit` uses it.
- `M-p`, free by default, but `magit` uses it.
- `M-[` and `M-]`, free.
- `M-o` binds to a fairly useless command for setting faces that are not usable in any mode that defines its own highlighting rules.

If anything, you should prefer key bindings that are closer to the home row and not `M-<number>`.  Of all choices above, I think `C-RET` and `M-RET` are suitable for global leader key and major mode leader keys and easy to remember (share the same `RET` key).

**Comment by tuhdo** [comment]
`C-RET` is actually `C-j` in terminal so I think another combination is to use `M-RET` for global leader and `M-m` for major mode leader. `M-RET` works in terminal

**Comment by syl20bnr** [comment]
Thank you for the list, indeed the closer to the home row, the better.
`C-m` and `M-m` are appealing, it is the same location on qwerty, dvorak and colemak.

**Comment by tuhdo** [comment]
Actually `C-m` is treated as `RET` in both GUI and terminal. So, probably we only have `M-RET` and `M-m` left.

**Comment by syl20bnr** [comment]
RET is an awful keys to set as default for a lot reasons:
- train a muscle memory to hit `RET` for something other than validation is dangerous.
- using the pinky on one of the biggest key of the keyboard might not be very healthy in the long run.

For now I'm back on `M-1` and `M-0`, not as efficient they are symmetrical and they can be performed without changing the angle of the wrist (i.e. only a translation is required, the thumb and the index keep a `C` or inverted `C` shape).

**Comment by tuhdo** [comment]
So how about `M-m` or other keys I listed. It should not require wrist bending either.

**Comment by syl20bnr** [comment]
The better alternative of all for me is still `M-n` and `M-m`. Let's see how to make a rule for this `M-n`.

**Comment by tuhdo** [comment]
I think that global leader key is important and you should give it `M-m`, Guaranteed not to clash with anything since it's the default. Prelude also replaces some standard key bindings and people seem to love it (given it has many stars). `M-m` is fairly useless if we have smart `C-a`. As for major mode leader key, I'm fine with whatever you choose.

**Comment by syl20bnr** [comment]
Indeed the major leader is a shortcut.
I just realized that your proposal of `M-RET` can be performed with `C-M-m` !

:-)

**Comment by tuhdo** [comment]
Oh yes totally forgot about it. That's perfect.

**Comment by syl20bnr** [comment]
So we have your pair of keys, yes !

:+1:

**Comment by tuhdo** [comment]
Since we replace `M-m`, shouldn't we enable  `better-default` layer by default?
