### ISSUE TITLE
Completion suggestions in Haskell repl are not good

### ISSUE THREAD

**Issue by sholland1** [syl20bnr/spacemacs#9173]
#### Description :octocat:
Outside of Spacemacs, pressing TAB in ghci suggests any functions that are in scope. Within Spacemacs, I would expect either the exact same thing to happen, or an auto-completion window to pop up with the same suggestions after typing a few characters.

However, when I press TAB, two spaces are inserted with no suggestions. When I type "ma", auto-completion pops up, but the suggestions are not good. I expect `map` to be a suggestion, but it isn't. 

Within Spacemacs:
![after_typing_ma_in_spacemacs](https://user-images.githubusercontent.com/2286322/27766933-5d39c004-5ea8-11e7-8ecd-99d40e4fefce.png)

Outside Spacemacs:
![after_typing_ma_in_cmd](https://user-images.githubusercontent.com/2286322/27766934-633630d2-5ea8-11e7-8e20-bc72ea8a09f1.png)

#### Reproduction guide :beetle:
- Start Emacs
- Open a file within a Haskell(stack) project.
- Open the repl. (SPC m s b)
- Press the TAB key.

*Observed behaviour:* :eyes: :broken_heart:
The repl loads normally. Pressing TAB inserts two spaces.

*Expected behaviour:* :heart: :smile:
The repl should display something like this:
`Display all ### possibilities? (y or n)`

#### System Info :computer:
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp
 (haskell :variables haskell-completion-backend 'intero haskell-process-type 'stack-ghci)
 markdown org yaml auto-completion git ranger
 (shell :variables shell-default-term-shell 'eshell)
 search-engine spacemacs-layouts
 (syntax-checking :variables syntax-checking-enable-tooltips nil))
```

**Comment by GregorySchwartz** [comment]
Looks like company is pulling from an inappropriate source. I have this issue when editing Haskell source files as well -- I never get function completion (the issue here) nor filepath completion.
