### ISSUE TITLE
Symbol’s function definition is void: make-mu4e-context

### ISSUE THREAD

**Issue by carmenbianca** [syl20bnr/spacemacs#9176]
#### Description :octocat:

When using `make-mu4e-context` in dotspacemacs/user-config, Emacs shows an error
during startup explaining that the symbol's function definition is void.
Strangely, it does *not* complain when you do `SPC f e R` after startup.
Because mu4e is a system-installed package, I am guessing that Spacemacs hadn't
imported mu4e before running user-config?  I'm not really an expert, honestly.

#### Reproduction guide :beetle:

- Put this in your dotspacemacs/user-config (or something similar, but this is
  what I've got for accuracy's sake):

```
  (setq mu4e-contexts
    `( ,(make-mu4e-context
          :name "Personal"
          :enter-func (lambda () (mu4e-message "Entering Personal context"))
          :leave-func (lambda () (mu4e-message "Leaving Personal context"))
          :match-func (lambda (msg)
                        (when msg
                          (string= (mu4e-message-field msg :maildir) "/Personal")))
          :vars '( ( user-mail-address . "carmen@carmenbianca.eu" )
                   ( mail-reply-to . "carmen@carmenbianca.eu" )
                   ( mu4e-trash-folder . "/Personal/Trash" )
                   ( mu4e-refile-folder . "/Personal/Archive" )
                   ( mu4e-sent-folder . "/Personal/Sent" )
                   ( mu4e-drafts-folder . "/Personal/Drafts" )
                   ( smtpmail-smtp-server . "smtp.kolabnow.com" )
                   ( smtpmail-smtp-service . 587 )
                   ( mu4e-compose-signature .
                     (concat
                       "Carmen Bianca Bakker <carmen@carmenbianca.eu>\n"
                       "PGP: 2A09 F627 39F6 DEC8 CFFC  A216 CD0A 90F1 C5CA 0C92\n"))))
       ,(make-mu4e-context
          :name "School"
          :enter-func (lambda () (mu4e-message "Entering School context"))
          :leave-func (lambda () (mu4e-message "Leaving School context"))
          :match-func (lambda (msg)
                        (when msg
                          (string= (mu4e-message-field msg :maildir) "/School")))
          :vars '( ( user-mail-address . "bakk1302@student.nhl.nl" )
                   ( mail-reply-to . "bakk1302@student.nhl.nl" )
                   ( mu4e-trash-folder . "/School/[Gmail].Prullenbak" )
                   ( mu4e-sent-folder . "/School/[Gmail].Verzonden berichten" )
                   ( mu4e-drafts-folder . "/School/[Gmail].Concepten" )
                   ( smtpmail-smtp-server . "smtp.gmail.com" )
                   ( smtpmail-smtp-service . 587 )
                   ;; don't save messages to Sent Messages, Gmail/IMAP takes care of this
                   ( mu4e-sent-messages-behavior 'delete )
                   ( mu4e-compose-signature  .
                     (concat
                       "Carmen Bianca Bakker <bakk1302@student.nhl.nl>\n"
                       "PGP: 2A09 F627 39F6 DEC8 CFFC  A216 CD0A 90F1 C5CA 0C92\n"))))))
```
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:

`Error in dotspacemacs/user-config: Symbol's function definition is void: make-mu4e-context`

This does not occur when doing `SPC f e R` immediately afterwards.

*Expected behaviour:* :heart: :smile:

No error, preferably!

#### System Info :computer:
- OS: Debian 9 (Stretch)
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: nil (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html markdown yaml helm auto-completion emacs-lisp git org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking
      (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp" mu4e-enable-notifications t mu4e-enable-mode-line t)
      ruby
      (python :variables python-test-runner 'pytest))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by fiveNinePlusR** [comment]
typically you want to wrap any configurations for packages inside an `(eval-after-load 'packagename (all your configs))``` to prevent that error from happening.

**Comment by carmenbianca** [comment]
@fiveNinePlusR You're right, that did fix it. Thank you very much! I guess that should close this issue.

**Comment by paynito** [comment]
Mine worked with

    (with-eval-after-load 'packagename 
            (all your configs))

**Comment by baljeet** [comment]
I am still facing the issue after adding the setq lines inside an
`(eval-after-load 'packagename (all your configs))`

Any advice?

**Comment by improve100** [comment]
(with-eval-after-load 'packagename  
packagename no replace
