### ISSUE TITLE
[theming] show a specific example of `theming-modifications` var in README

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#9184]
Additionally: *This layer allows for a simple way of modifying themes.* - (how) is it simpler then `custom-theme-set-faces`?

**Comment by TheBB** [comment]
There's an example in the develop version of the readme.

**Comment by jaspertravers** [comment]
Specifically https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bthemes/theming#example
