### ISSUE TITLE
Helm problem

### ISSUE THREAD

**Issue by fasddag** [syl20bnr/spacemacs#919]
space :, space f h or space T h don't work and return an error:
byte-code: Symbol's function definition is void: eieio-defclass-internal 

Error messages on start up:
error in process sentinel: async-handle-result: Searching for program: no such file or directory, git
error in process sentinel: Searching for program: no such file or directory, git

Compile log:
~/.emacs.d/core/core-themes-support.el:Warning: assignment to free variable
    `spacemacs--cur-theme'
~/.emacs.d/init.el:Warning: reference to free variable
    `smartparens-strict-mode'

My system:
win 8.1
emacs-bin-w64-24.4.91
helm 20150222.2156
helm themes 20141117.740
eieio 1.4 built-in

**Comment by tuhdo** [comment]
Probably you should try Emacs 24.4 instead of Emacs 25 (which is 24.4.91) or latest build of Emacs, since this issue was fixed a while ago.

**Comment by fasddag** [comment]
I have just tried 24.4 (says it's 24.4.1 on start up) from http://sourceforge.net/projects/emacsbinw64/files/release/ and got the same error. Reinstalling spacemacs, just in case, right now.

**Comment by fasddag** [comment]
tuhdo, you are an agent of light, justice and joy! It words now, thank you. =)

**Comment by tuhdo** [comment]
> tuhdo, you are an agent of light, justice and joy! It works now, thank you. =)

lol thanks. Glad it helped!
