### ISSUE TITLE
Why don't use company of lua ?

### ISSUE THREAD

**Issue by ReimuXMX** [syl20bnr/spacemacs#9192]
Why don't you use company-lua for Lua ?

**Comment by nixmaniack** [comment]
We do, [check here](https://github.com/syl20bnr/spacemacs/blob/d89f2dcf822cbaa7d0e06c0d1688f005b3588a6b/layers/+lang/lua/packages.el#L15).

**Comment by ReimuXMX** [comment]
Thank you! I hope you will go to the master branch as soon as possible
