### ISSUE TITLE
org-brain usage possible in spacemacs?

### ISSUE THREAD

**Issue by poulpoulsen** [syl20bnr/spacemacs#9195]
hello,
just a question:
i read about org-brain and that it is installable from melpa.
yesterday i found it, installed it, but after restarting my spacemacs-emacs all related packages are deleted automatically.
Because i`m not a programmer, i need some help to use it inside spacemacs.
Or is it not possible until now?

Regards
Poul

**Comment by TheBB** [comment]
http://spacemacs.org/doc/FAQ.html#why-are-packages-installed-with-package-install-automatically-deleted-by-spacemacs-when-it-boots

**Comment by poulpoulsen** [comment]
Yes thank you!
I edit my .spacemacs and after restart it works.
Will check if org-brain works and come back with other problems :-)

Regards
Poul

**Comment by ngm** [comment]
I've been using it for a couple of days and it's working OK.  

One thing is that when you're in `org-brain-visualize-mode` the keybindings do not work if you're using evil.  You can press <kbd>Ctrl-Z</kbd> to temporarily switch to emacs bindings, or I made a basic layer that automatically switches to emacs bindings for `org-brain-visualise-mode`: https://gist.github.com/ngm/646f5a1e958920c1c0f31cc3b51a8762

(I'm quite new to spacemacs (and emacs :) ) so there may be better ways of doing this.)
