### ISSUE TITLE
Counsel M-x runs with an intial input

### ISSUE THREAD

**Issue by harindu95** [syl20bnr/spacemacs#9197]
#### Description :octocat:
Pressing SPC SPC or M-x runs counsel-M-x with an intial input of "^".
running (counsel-M-x) doesn't provide this behaviour.

#### Reproduction guide :beetle:
- Start Emacs
- install ivy
press M-x or SPC SPC

*Observed behaviour:* :eyes: :broken_heart:
counsel-M-x runs with an initial input

*Expected behaviour:* :heart: :smile:
counsel-M-x runs without an initial inpu

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion emacs-lisp c-c   git)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```

```

**Comment by patrl** [comment]
This is intended behaviour upstream (see, e.g., [this issue](https://github.com/abo-abo/swiper/issues/588)). The input to Counsel-M-x is a regular expression, and the caret is a regexp anchor marking the beginning of the string. You can get rid of it by setting the following variable, although I'm not sure why you would want to.

`(with-eval-after-load 'ivy
setq ivy-initial-inputs-alist nil)
)`

**Comment by harindu95** [comment]
I know it's a regex. But for me it would be harder to search because you have to type the phrase from the beginning.
