### ISSUE TITLE
Creating files from neotree opens them at / instead of the dir chosen

### ISSUE THREAD

**Issue by mathpunk** [syl20bnr/spacemacs#9199]
#### Description :octocat:
Creating a file from a neotree directory instead creates the file at root.

#### Reproduction guide :beetle:
- Start Emacs
- Open neotree and navigate your cursor to a directory
- Use SPC-f-f to open the Find File minibuffer
- There's no slash after that directory, so you type a slash and then your filename...

*Observed behaviour:* :eyes: :broken_heart:
...but, instead of opening the file /home/$USER/whatever/your-file.txt, opens a file at /your-file.txt, receiving complaints about it being read-only and so forth when the buffer opens.

*Expected behaviour:* :heart: :smile:
A buffer is opened at /home/$USER/whatever/your-file.txt instead.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. efef3905)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(own ivy better-defaults
     (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-space-key-behavior 'reject auto-completion-return-key-behavior 'reject auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.3)
     (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/usr/bin/fish" shell-default-height 30 shell-default-position 'bottom)
     shell-scripts
     (org :variables org-enable-reveal-js-support t org-enable-org-journal-support t)
     yaml csv sql ranger html restclient react emacs-lisp javascript clojure python syntax-checking git github fasd markdown deft latex themes-megapack typography emoji)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by ZarsBranchkin** [comment]
Managed to reproduce, seems to be an issue with ivy(works fine with helm). 

I'll see if I can fix this, but it seems that a better way to create new files in neotree is by using `c` key binding. It also adds the missing `/`, that you mentioned and creates the file properly.

**Comment by mathpunk** [comment]
Thank you, I'll adjust my habit. It might still be worth fixing for
'principle of least surprise' reasons.

**Comment by ZarsBranchkin** [comment]
Managed to locate the issue. The problem was in neotree incorrectly updating `default-directory` variable. 

Here is the relevant PR: https://github.com/jaypei/emacs-neotree/pull/260
