### ISSUE TITLE
New evilify macro suggestion

### ISSUE THREAD

**Issue by jcpetkovich** [syl20bnr/spacemacs#920]
Currently, when evaluated using an interactive command, such as `eval-last-sexp` macro expansion happens eagerly, and results in an error. For example:

    (evilify mu4e-main-mode mu4e-main-mode-map)

Causes an error since `evil-define-key` requires at least one key definition in its body, *and* it's being expanded in FULL during evaluation, regardless of the unless. It is expanded no matter what.

In my opinion, your `evilify` macro should actually conditionally add that statement, rather than create a condition for executing it, like so:

    (defmacro evilify (mode map &rest body)
      "Set `evilified state' as default for MODE.
    
    BODY is a list of additional key bindings to apply for the given MAP in
    `evilified state'."
      `(progn (unless (memq ',mode evil-evilified-state--modes)
                (push ',mode evil-evilified-state--modes))
              (unless (or (bound-and-true-p holy-mode)
                          (memq ',mode evil-evilified-state-modes))
                (delq ',mode evil-emacs-state-modes)
                (push ',mode evil-evilified-state-modes))
              ,(unless (null body)
                `(evil-define-key 'evilified ,map ,@body))))

Here we never add the `evil-define-key` statement unless it's actually going to be valid.

What do you think?

**Comment by syl20bnr** [comment]
Thank you for the report and the proposal. While your proposal works perfectly, it evaluates the `evil-define-key` at expansion time.
I pushed a version which does the evaluation at evaluation time (see commit above) which is a less suprising behavior.
