### ISSUE TITLE
Company-semantic problem

### ISSUE THREAD

**Issue by joaopaulo23** [syl20bnr/spacemacs#9201]
I'm using Windows 10, and getting this anoying bug, when i activate company-semantic.

Spacemacs version :0.200.9
Emacs version : 25.2.2
Core i7 2620qm 
I'm using emacs with all packages installed, this version is found at GitHub. 

 [command major-mode company-semantic-modes arg prefix context eql interactive company-begin-backend company-semantic featurep semantic semantic-active-p company-semantic--prefix stop candidates print argssao 1args delete  mapcar semantic-tag-name company-semantic-completions-raw (error) nil semantic-analyze-current-context semantic-analyze-possible-completions no-unique all-completions meta assoc annotation company-semantic-annotation doc-buffer company-semantic-doc-buffer no-cache duplicates t location buffer-live-p semantic-tag-buffer semantic-tag-start post-completion company-template-c-like-templatify completion-ignore-case company-semantic--current-tags company-semantic-metadata-function tag anno company-semantic-insert-arguments] 5 (c:/Users/joaopaulo/AppData/Roaming/.emacs.d/elpa/company-20170617.1502/company-semantic.elc . 3742) (list (quote interactive))] 0

I can use the company-semantic, but at some point it happens, freezes spacemacs and them it Works again. i tried to edit the lisp code, but i'aint no good on lisp at all.

I think the error is at this part of code on company-semantics.el

(candidates (if (and (equal arg "")
                         (not (looking-back "->\\|\\." (- (point) 2))))
                    (company-semantic-completions-raw arg)
                  (company-semantic-completions arg)))
    (meta (funcall company-semantic-metadata-function
                   (assoc arg company-semantic--current-tags)))
    (annotation (company-semantic-annotation arg
                                             company-semantic--current-tags))

And the funcs tha predecessor it is:

(defun company-semantic-completions-raw (prefix)
  (setq company-semantic--current-tags nil)
  (dolist (tag (semantic-analyze-find-tags-by-prefix prefix))
    (unless (eq (semantic-tag-class tag) 'include)
      (push tag company-semantic--current-tags)))
  (delete "" (mapcar 'semantic-tag-name company-semantic--current-tags)))

(defun company-semantic-annotation (argument tags)
  (let* ((tag (assq argument tags))
         (kind (when tag (elt tag 1))))
    (cl-case kind
      (function (let* ((prototype (semantic-format-tag-prototype tag nil nil))
                       (par-pos (string-match "(" prototype)))
                  (when par-pos (substring prototype par-pos)))))))

(defun company-semantic--prefix ()
  (if company-semantic-begin-after-member-access
      (company-grab-symbol-cons "\\.\\|->\\|::" 2)
    (company-grab-symbol)))

Sorry for asking to edit it to me, but have no time to learn elisp until next month.

**Comment by CeleritasCelery** [comment]
sounds like a company mode bug. You should report upstream at [company-mode/company-mode](https://github.com/company-mode/company-mode)
