### ISSUE TITLE
`describe-input-method` does not show shortcuts

### ISSUE THREAD

**Issue by mwillsey** [syl20bnr/spacemacs#9203]
#### Description :octocat:
`describe-input-method` is not showing the possible shortcuts.

#### Reproduction guide :beetle:
- Start Emacs
- run `describe-input-method`
- pick an input method (like `TeX`)

*Observed behaviour:* :eyes: :broken_heart:
There's no listing of the shortcuts.

*Expected behaviour:* :heart: :smile:
There should be listing of shortcuts provided by the input method.
`emacs -q` does this.

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers: (bug also shows up with no active layers)
```elisp
((shell :variables shell-default-shell 'eshell)
 osx emacs-lisp helm org git github vagrant graphviz
 (auto-completion :disabled-for emacs-lisp org latex)
 syntax-checking spell-checking bibtex
 (latex :variables latex-enable-auto-fill nil latex-enable-folding t)
 (c-c   :variables c-c  -enable-clang-support t)
 semantic gtags html markdown
 (haskell :variables haskell-completion-backend 'intero)
 racket idris python go yaml javascript lean)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by anka-213** [comment]
Does anyone have a workaround for this? It is a very crippling bug when working with agda where almost everything you write requires writing unicode.
