### ISSUE TITLE
Expand region changes behaviour of C-a on visual mode

### ISSUE THREAD

**Issue by henriquenj** [syl20bnr/spacemacs#9207]
#### Description :octocat:
After using <kbd>SPC v</kbd> at least once in a buffer, using <kbd>C-SPC C-a</kbd> to select a line to its beginning will not work. Closing the buffer and opening again will make <kbd>C-SPC C-a</kbd> work again as expected. Pressing <kbd>C-SPC</kbd> and <kbd>C-a</kbd> SEPARETELY (releasing control between <kbd>SPC</kbd> and <kbd>a</kbd>) will sometimes make it work again.

The bug also occurs if the user press <kbd>v</kbd> to enter visual mode.

#### Reproduction guide :beetle:
On a fresh install of spacemacs
- Start Emacs
- Visit any file (tested with an Elisp file)
- Move the cursor to the end of a line
- Use <kbd>C-SPC</kbd> to enter visual mode followed by <kbd>C-a</kbd> to select the entire line
- Exit visual mode
- On the same buffer, select any text using <kbd>SPC v</kbd> (expand region)
- Exit expand region
- Again try to perform selection of a line using <kbd>C-SPC C-a</kbd>. From now on <kbd>C-a</kbd> will exit visual mode, whereas prior using expand region it wouldn't.

*Observed behaviour:* :eyes: :broken_heart:
<kbd>C-a</kbd> exits visual mode.

*Expected behaviour:* :heart: :smile:
<kbd>C-a</kbd> should not exit visual mode, as before of using <kbd>SPC v</kbd>

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

I removed my dotspacemacs and ran `git clean -fdx` on `.emacs.d` directory to reproduce this bug.

My configuration uses <kbd>C-a</kbd> and <kbd>C-e</kbd> like vanilla Emacs, and the same behaviour happens with <kbd>C-e</kbd>. I usually use this sequence of keys to select a line.

<kbd>$</kbd> and <kbd>^</kbd> seems to be working fine. As a workaround I could bind their commands to <kbd>C-a</kbd> and <kbd>C-e</kbd>

**Comment by duianto** [comment]
Confirmed
#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 7e57b1f3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey emacs-lisp git helm markdown
                 (org :variables org-agenda-files
                      '("c:/Users/Username/Documents/"))
                 version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by planigan** [comment]
Confirmed on gnu/linux as well:

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 74ca54ad)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python octave helm
        (auto-completion :variables auto-completion-enable-snippets-in-popup t)
        better-defaults emacs-lisp git github org pandoc deft
        (ranger :variables ranger-show-preview t)
        (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/bin/bash" shell-default-height 30 shell-default-position 'bottom)
        spell-checking syntax-checking
        (version-control :variables version-control-diff-side 'left)
        github themes-megapack theming emoji html colors markdown aj-javascript
        (ruby :variables ruby-version-manager 'rvm)
        ruby-on-rails
        (gtags :variables gtags-enable-by-default t)
        yaml go
        (sql :variables sql-capitalize-keywords t)
        vimscript shell-scripts)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by henriquenj** [comment]
If more people are bothered by this behaviour, this code binds <kbd>C-a</kbd> and <kbd>C-e</kbd> to the evil versions, so it works mostly the same. You should add it to `dotspacemacs/user-config`

```emacs-lisp
  (define-key evil-motion-state-map (kbd "C-e") 'evil-end-of-line)
  (define-key evil-motion-state-map (kbd "C-a") 'evil-first-non-blank)
  (define-key evil-insert-state-map (kbd "C-e") 'evil-end-of-visual-line)
  (define-key evil-insert-state-map (kbd "C-a") 'evil-first-non-blank)
```
If you want <kbd>C-a</kbd> to go to the first column even if it's a blank line, I think you can use `evil-digit-argument-or-evil-beginning-of-line` instead of `evil-first-non-blank`. But I haven't tested.

I found out that this setup works better when using multiple cursors, since vanilla <kbd>C-a</kbd> works only for one cursor (this might be a separeted bug)

**Comment by henriquenj** [comment]
Bug still present on develop, tested on e09385d29ef2c95cef14b992028ca85da142dad7

**Comment by henriquenj** [comment]
I don't see this behaviour anymore as of commit 27178f23e912d740ad77c0864122604a04576415. I think it can be closed.

**Comment by duianto** [comment]
Fell free to close any issue that you've opened, where you're unable to reproduce it on the latest `develop` branch.
