### ISSUE TITLE
Package let-alist is no longer available?

### ISSUE THREAD

**Issue by marten** [syl20bnr/spacemacs#921]
I have a fresh checkout of spacemacs master (fadc7bae3f81610ed82b5360c034086fa27a5ed0). Never used spacemacs before. Upon startup, it failed to install two packages. I tried restarting, which didn't fix the issue (it did try installing again though).

```
Found 3 new package(s) to install...
--> fetching new package repository indexes...
--> installing (spacemacs):flycheck... [1/3]An error occurred while installing flycheck (error: (error Package `let-alist-1.0.1' is unavailable))
--> installing (spacemacs):let-alist... [2/3]
Package let-alist is unavailable. Is the package name misspelled?
--> installing (spacemacs spacemacs):paradox... [3/3]An error occurred while installing paradox (error: (error Package `let-alist-1.0.3' is unavailable))
```

![_spacemacs_](https://cloud.githubusercontent.com/assets/277/6784952/0b3b199c-d183-11e4-8148-5bbb49b29024.png)

Just in case it's relevant, my Emacs version is "GNU Emacs 24.4.50.1 (x86_64-apple-darwin, NS apple-appkit-1038.36) of 2014-05-10 on bob.porkrind.org"

**Comment by syl20bnr** [comment]
I cannot reproduce it with a fresh clone of the repo. Do you still have the issue ?
Can you try [this version](https://github.com/syl20bnr/spacemacs#os-x) via homebrew ?

PS: funny `(spacemacs spacemacs):paradox`, I will have to look into that.

**Comment by marten** [comment]
I don't have the issue anymore, without updating anything. Maybe a strange issue where the let-alist package temporarily fell out of elpa?

**Comment by smypf** [comment]
I was experiencing something similar to this as well.

Adding additional package archives to ~/.spacemacs was required to prevent this error for me.

(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("marmalade" . "https://marmalade-repo.org/packages/")
                         ("melpa" . "http://melpa.org/packages/")))

**Comment by usharf** [comment]
I'm seeing it again now. Spacemacs 0.101.2.

```emacs-lisp
Found 13 new package(s) to install...
--> fetching new package repository indexes...
--> installing (javascript):company-tern... [1/13]
Package company-tern is unavailable. Is the package name misspelled?
--> installing (html):emmet-mode... [2/13]
Package emmet-mode is unavailable. Is the package name misspelled?
--> installing (html):haml-mode... [3/13]
Package haml-mode is unavailable. Is the package name misspelled?
--> installing (html):helm-css-scss... [4/13]
Package helm-css-scss is unavailable. Is the package name misspelled?
--> installing (javascript):js2-refactor... [5/13]
Package js2-refactor is unavailable. Is the package name misspelled?
--> installing (javascript):json-mode... [6/13]
Package json-mode is unavailable. Is the package name misspelled?
--> installing (html):less-css-mode... [7/13]
Package less-css-mode is unavailable. Is the package name misspelled?
--> installing (html):sass-mode... [8/13]
Package sass-mode is unavailable. Is the package name misspelled?
--> installing (html):scss-mode... [9/13]
Package scss-mode is unavailable. Is the package name misspelled?
--> installing (html):slim-mode... [10/13]
Package slim-mode is unavailable. Is the package name misspelled?
--> installing (html):tagedit... [11/13]
Package tagedit is unavailable. Is the package name misspelled?
--> installing (javascript):tern... [12/13]
Package tern is unavailable. Is the package name misspelled?
--> installing (html):web-mode... [13/13]
Package web-mode is unavailable. Is the package name misspelled?

[167 packages loaded in 5.273s]
```

**Comment by BlinkD** [comment]
sympf's code works for me
![screenshot from 2015-04-26 20 18 47](https://cloud.githubusercontent.com/assets/8343797/7337160/8018737a-ec51-11e4-8f7c-c8365b359b51.png)

**Comment by santiagobasulto** [comment]
This worked for me too. Thanks

**Comment by liujoey** [comment]
Recently installed spacemacs on a iMac, sympf's code works for me. let-alist package was missing before I added his code.

**Comment by kRITZCREEK** [comment]
thx for the fix! had the same problem

**Comment by ctjhoa** [comment]
Same problem on windows and same fix.

**Comment by jdpopkin** [comment]
smypf's code solved a similar problem for me.
