### ISSUE TITLE
ESS-Layer is incompatible with Org-Layer

### ISSUE THREAD

**Issue by Isimoro** [syl20bnr/spacemacs#9211]
#### Description :octocat:
ESS-Layer is incompatible with Org-Layer, probably because the ESS-Layer
loads the org-version that ships with emacs.

If both ess- and org-layer are enabled, trying to reload the dotfile via ` SPC f e R`  fails immediately dumping `byte-code: Invalid function: org-babel-header-args-safe-fn` into *Messages*. The same Error is issued everytime org-mode is started.
Quick google search suggests this is related to the incompatible
org-versions mentioned in the org-layer documentation.

Tested this with my own dotfile as well as the default one.

#### Reproduction guide :beetle:
- Start Emacs
- enable ess and org layers in `dotspacemacs-configuration-layers`
-  `SPC f e R`
- try again

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(chrome python helm shell-scripts bibtex pdf-tools ibuffer imenu-list auto-completion latex emacs-lisp ranger
        (org :variables org-projectile "proj-TODOs.org")
        (spell-checking :variables spell-checking-enable-by-default nil enable-flyspell-auto-completion t)
        syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
This is not a problem of the ESS-layer but rather an upstream bug in org mode see this post for details #4618.

> This is an upstream bug in org-mode, see http://comments.gmane.org/gmane.emacs.orgmode/99644 and https://www.mail-archive.com/emacs-orgmode@gnu.org/msg98762.html. I think this issue should be closed and an upstream bug reported to org-mode.

To make a long story short there is an easy workaround for this, this is simply remove `ob-R.elc` in your elpa directory. Then recompile it via `spc spc emacs-lisp-byte-compile`.

If this does not work you can try below workaround.

> It usually happens in spacemacs that you end up with both org and org-plus-contrib package, making it harder to know where the broken ob-R.elc file is. Start package manager with M-x paradox, delete org and org-plus-contrib, then install only prg-plus-contrib. This usually works for me.
