### ISSUE TITLE
In python-mode, using `:wa` has unwanted side effect

### ISSUE THREAD

**Issue by osdf** [syl20bnr/spacemacs#9213]
#### Description :octocat:
When using `:wa` (vim command for save-all) in a
python buffer, point jumps to line 29 (if point is
after line 29) after all files are saved. This
does not happen in other modes it seems.

This does not happen when using `:w`.

First idea was that the problem is related to `smartparens`.
Excluding this package did not help.

#### Reproduction guide :beetle:
- Start Emacs
- Open python file with more than 29 lines
- Edit somewhere > line 29
- Save using `:wa`.

*Observed behaviour:* :eyes: :broken_heart:
- Point jumps to beginning of line 29.

*Expected behaviour:* :heart: :smile:
- Point stays where it was when `:wa` is issued.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion better-defaults emacs-lisp
     (clojure :variables clojure-enable-fancify-symbols t)
     (git :variables git-magit-status-fullscreen t)
     (latex :variables latex-enable-auto-fill nil)
     html javascript markdown org gtags
     (python :variables python-enable-yapf-format-on-save t)
     (c-c   :variables c-c  -enable-clang-support t c-c  -default-mode-for-headers 'c  -mode)
     semantic syntax-checking themes-megapack version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by Somelauw** [comment]
Does this also happen when python-enable-yapf-format-on-save is set to nil?

**Comment by osdf** [comment]
Ohhh, I didn't think of it! Setting it to `nil` + restart resolves the described problem!

**Comment by osdf** [comment]
Thank you very much @Somelauw !!
