### ISSUE TITLE
LaTeX compilation does not work in `centered-buffer-mode`

### ISSUE THREAD

**Issue by dschrempf** [syl20bnr/spacemacs#9214]
When editing LaTeX files in `centered-buffer-mode`, compilation gives an error

    ! I can't find file `<none>.tex'.
    <*> \input <none>.tex

This may be related to #8653, although I am using the `develop` branch.

Also, when `centered-buffer-mode` is activated, two buffers are pointing to the
same file (one is the non-centered buffer, the other is the centered buffer). In
my opinion (of course this is open for debate), `centered-buffer-mode` should
work like a toggle or switch (on or off, one buffer, no confusion).

Thanks a lot,
Dominik

**Comment by oleorhagen** [comment]
I was just about to report on the same issue (kinda), as when `centered-buffer-mode` is enabled `buffer-file-name` is nil. Which is unfortunate with a lot of packages.

**Comment by TheBB** [comment]
@JAremko

**Comment by JAremko** [comment]
Should be fixed in #9219

**Comment by JAremko** [comment]
@dschrempf  @olejorgenb  try now.

**Comment by dschrempf** [comment]
Hi!

Thank you, compilation works perfect now. The original buffer name has now a `*` in front of its name. Was this your intention? Anyways, now it is possible to distinguish between the two!

Thanks a lot,
Dominik

**Comment by JAremko** [comment]
@dschrempf  Yeah buffer with `*` won't be selected when you switch between next and previous buffers. For example *Message* buffer
