### ISSUE TITLE
[python] Smartparens (sp-) does not recognize whitespace (identation-level) separated sexps

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#9215]

**Comment by Somelauw** [comment]
Can you tell us the steps to reproduce?

**Comment by xged** [comment]
@Somelauw  Not exact steps, but e.g. `sp-end-of-sexp`, `sp-beginning-of-sexp` does not move cursor if its, lets say, in function definition and not inside a pair.

**Comment by Somelauw** [comment]
These functions only work in (parameter) lists that looks like this:
```python
(a, b, c)
```

But this is more of an [upstream](https://github.com/Fuco1/smartparens) issue.
