### ISSUE TITLE
toggle-visual-line-navigation doesn't fully disabled

### ISSUE THREAD

**Issue by bobpaul** [syl20bnr/spacemacs#9218]
#### Description :octocat:
toggle-visual-line-navigation doesn't fully disabled

#### Reproduction guide :beetle:
- Start Emacs
- open a document with long lines. Notice they wrap (but not on word boundaries and no indentation is added).
- [SPC t L] to enable visual line mode. Notice everything is fine; lines are wrapped on word boundaries and indentation is added to make it visually appealing where long lines are indented.
- [SPC t L] to disable visual line mode. 

*Observed behavior:* :eyes: :broken_heart:
Notice lines are no longer wrapping on word boundaries, but the extra indentation remains.

*Expected behavior:* :heart: :smile:
when lines wrap the text should start at the window border, just as it did when the document was initially opened.

This seems to occur on a per-buffer basis. Opening a fresh buffer provides the expected, default wrapping behavior.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python markdown windows-scripts gtags helm emacs-lisp git)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Compro-Prasad** [comment]
Can you please provide a screenshot? I don't understand the `indent` part.
