### ISSUE TITLE
Freeze while searching in file using /

### ISSUE THREAD

**Issue by achikin** [syl20bnr/spacemacs#9220]
#### Description :octocat:
Emacs freezes while searching in file using /

#### Reproduction guide 🐞
- Start Emacs
- Open quite big file (200+  lines)
- Press `/`
- Type in one letter

Observed behaviour: 👀 💔
- Emacs takes up 96% CPU and freezes

Expected behaviour: ❤️ 😄
- Emacs searches for the letter

#### System Info 💻
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 7e57b1f3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql helm auto-completion syntax-checking better-defaults emacs-lisp git clojure html markdown parinfer)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace 🐾
```
```

**Comment by TinySong** [comment]
There is too little information to diagnose the problem, you can use profiler-start command to check where stacked

**Comment by beta1440** [comment]
@achikin Do you get this issue when using the Spacemacs `master` branch?

**Comment by braham-snyder** [comment]
does excluding the `spaceline' package (add it to `dotspacemacs-excluded-packages`, which should be in a `setq` in your init file) circumvent the issue? if so, may be:

https://github.com/TheBB/spaceline/issues/123#issuecomment-302835168

if not, the `pkill -USR2` bit in there may still help you diagnose your issue

**Comment by mathpunk** [comment]
I thought the recommendation to disable unicode in powerline here  https://github.com/TheBB/spaceline/issues/123#issuecomment-302835168 fixed my issue, but, it just happened again. I will try `pkill -USR2` next time it happens.

**Comment by braham-snyder** [comment]
Did you set it in `dotspacemacs/init`? For what it's worth, if you set it in `dotspacemacs/user-config` (and possibly even in `dotspacemacs/user-init`), it won't actually be set in time to take effect.

**Comment by mathpunk** [comment]
I did not! I've kept away from that expression entirely. I have now set it in dotspacemacs/init, after the setq-default expression. Thanks, I'll see how it goes.

**Comment by carloscheddar** [comment]
I'm running the latest `develop` changes and this issue is still happening even after I added `(setq dotspacemacs-mode-line-unicode-symbols nil)` to `dotspacemacs/init`. I can search a few times but after 6 or 7 times it hangs.

**Comment by carloscheddar** [comment]
Quick update: Excluding the `spaceline` package definitely fixes the issue. I also removed the `(setq dotspacemacs-mode-line-unicode-symbols nil)` line and everything works correctly.

**Comment by braham-snyder** [comment]
@carloscheddar that's odd -- but just to double check: a line already exists in the default `.spacemacs` file as: `(setq dotspacemacs-mode-line-unicode-symbols t)` within `dotspacemacs/init` (not within `dotspacemacs/user-init`). Does changing that line to use `nil` and restarting (`SPC q r`) still not work? 

If not, when the freeze occurs, you might want to triple check your modeline for any unicode characters: I suspect I initially ran into trouble partly because the only unicode symbols I used on my modeline were the workspace numbers, which are frequently hidden (so I didn't notice that I hadn't successfully turned them off).

**Comment by carloscheddar** [comment]
@braham-snyder After verifying my config I finally found what was causing the hang. 
I had added this line to the `user-config` from a suggestion on the mac section of the readme:
```lisp
(setq powerline-default-separator 'utf-8)
```
After removing it everything works as expected even with `dotspacemacs-mode-line-unicode-symbols` set to `t`.

**Comment by jonathanj** [comment]
My `powerline-default-separator` is set to `'slant` and I still have this hanging, with the same trace as in #9595. I'm going to try @braham-snyder's suggestion regarding `dotspacemacs-mode-line-unicode-symbols`.

**Comment by x-ji** [comment]
It also doesn't work for me. I'm not even using spaceline. I'm using `vim-powerline`. Is there a way to just disable this instant search behavior and only search when I hit enter?

**Comment by JonathanReeve** [comment]
This bug is driving me nuts. It will lock up my emacs for about 30s-1m, at times, when I search for anything in a large file. Is there a way to disable this instant search until at least three or four characters have been typed?

**Comment by duianto** [comment]
@JonathanReeve 
It might help to try another search tool.

It's chosen from the `.spacemacs` variable: `dotspacemacs-search-tools`

On the `develop` branch there's also support for `rg`:
https://github.com/BurntSushi/ripgrep

The default value is:
` '("rg" "ag" "pt" "ack" "grep")`

It uses the first tool it finds, as the comment above the variable says:
>   ;; List of search tool executable names. Spacemacs uses the first installed
   ;; tool of the list. Supported tools are \`rg', \`ag', \`pt', \`ack' and \`grep'.

**Comment by JonathanReeve** [comment]
It doesn't seem to matter which tool you use. I've tried it with `ag` and `grep` both, but the problem persists. In fact, I'm writing this comment now while waiting for a search to finish highlighting on a large org file. It's been about a minute or two.

Once spacemacs gets started with searching and highlighting single letters, it can't be stopped: not with Ctrl+G, not with Esc, or by trying to close Emacs.

I'll echo @x-ji's question above and ask: is there a way to disable typeahead search? From there it should be possible to disable it for large files.

**Comment by duianto** [comment]
These variables might be what your looking for:
- `helm-grep-input-idle-delay`
>Same as ‘helm-input-idle-delay’ but for grep commands.
It have a higher value than ‘helm-input-idle-delay’ to avoid
flickering when updating.

- `helm-input-idle-delay`
>Idle time before updating, specified in seconds.

**Comment by JonathanReeve** [comment]
Apparently when you set those values to a higher number, say, 1.0, it still has the issue. To reproduce, try doing this: 

 - Get a large org mode file (or probably any other type with syntax highlighting). A 500k file would be fine. 
 - Search the file for something. Say, `abc`. 
 - Notice that emacs totally freezes up after typing `a`, and insists on highlighting every single instance of the letter `a` in your file. Notice that the freeze lasts about a minute.

**Comment by gberenfield** [comment]
Unfortunately none of the above helped. I did my trick usual of commenting out large chunks of config and found that disabling smooth scrolling fixed it for me.

`dotspacemacs-smooth-scrolling  f`

HTH
Greg

**Comment by JonathanReeve** [comment]
I don't see what scrolling has to do with it. I'm not even scrolling when this is happening. But anyway, I've had smooth scrolling disabled this whole time, so that doesn't help.

**Comment by gberenfield** [comment]
Well neither do I but it seemingly worked. Today, not so well (froze again).

So in debugging, the last line before freezing is
`command-execute(evil-ex-search-forward)`

This is in evil-commands.el in the base evil package. Looking there, I found this bug
https://github.com/emacs-evil/evil/issues/1101

Testing 'search-invisible' set to nil and will see if that works...

**Comment by TheBB** [comment]
This should have been fixed in Evil.
