### ISSUE TITLE
Python: Add `elpy` Backend

### ISSUE THREAD

**Issue by beta1440** [syl20bnr/spacemacs#9222]
We should have the option of using `elpy` as a backend. According to the `anaconda-mode` [ repo](https://github.com/proofit404/anaconda-mode#supported-python-versions), it only supports Python 2.7–3.4. I've been using `elpy` and it works with newer versions of Python. Here's the `elpy` [repo](https://github.com/jorgenschaefer/elpy).

**Comment by ntcong** [comment]
anaconda-mode uses jedi and it does support 3.5. The doc might be outdated

**Comment by beta1440** [comment]
I was able to get `anaconda-mode` working for Python 3.5 as you suggested.
