### ISSUE TITLE
Add C-w q to close current window

### ISSUE THREAD

**Issue by madanh** [syl20bnr/spacemacs#9228]
Since C-w o works as in vim this is also expected to work. Would add to consistent experience for vim converts.

This is somewhat related to  #8071

**Comment by madanh** [comment]
Now closing current window is is bound to C-x 0 BTW

**Comment by duianto** [comment]
This probably is an upstream suggestion for the emacs-evil package: https://github.com/emacs-evil/evil

Here's where the current window commands are defined: https://github.com/emacs-evil/evil/blob/master/evil-maps.el#L112

**Comment by duianto** [comment]
This issue has been fixed upstream by hkgit03:
[Map <C-w> q to evil-quit #888](https://github.com/emacs-evil/evil/pull/888)

**Comment by madanh** [comment]
Confirmed! Works after updating packages.
