### ISSUE TITLE
No syntax checkers in elm-mode

### ISSUE THREAD

**Issue by bigardone** [syl20bnr/spacemacs#9232]
#### Description :octocat:
flycheck-elm has stopped working. No more syntax errors are displayed in the buffer. If I run `flycheck-verify-setup` this is what it shows:

```
Syntax checkers for buffer Main.elm in elm-mode:

There are no syntax checkers for this buffer!

Flycheck Mode is disabled. Use SPC u M-x flycheck-disable-checker to enable
disabled checkers.

--------------------

Flycheck version: 31snapshot (package: 20170713.903)
Emacs version:    25.1.1
System:           x86_64-apple-darwin16.4.0
Window system:    ns
```

#### Reproduction guide :beetle:
- Start Emacs
- Go to an Elm file
- Run `flycheck-verify-setup`

*Observed behaviour:* :eyes: :broken_heart:
No syntax errors are displayed anymore. Everything else related to the `elm-layer` seems to be working fine.

*Expected behaviour:* :heart: :smile:
Syntax errors should be highlighted.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(gtags elm php yaml vimscript helm
       (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
       better-defaults emacs-lisp git markdown org
       (shell :variables shell-default-height 30 shell-default-position 'bottom)
       version-control erlang
       (elixir :variables elixir-enable-compilation-checking t)
       html colors javascript themes-megapack
       (ibuffer :variables ibuffer-group-buffers-by 'projects)
       (shell :variables shell-default-shell 'shell)
       markdown
       (ranger :variables ranger-show-preview t)
       github dash purescript spell-checking)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by beta1440** [comment]
Make sure to enable the `syntax-checking` layer.

**Comment by bigardone** [comment]
@beta1440 that did the trick, thanks you so much :)
