### ISSUE TITLE
wrong project definition location in scala layer and how to correct it

### ISSUE THREAD

**Issue by csfreebird** [syl20bnr/spacemacs#9234]
when I use scala layer to format my code with M-m m r f (emacs style for ensime-format-source)
I got error message, and there shows wrong project location:

 Set current project to dean (in build file:/home/dean/)

But my real proejct is located at ~/work/gitlab/gitlab.com/.../hellostb

How to correct the location?

**Comment by csfreebird** [comment]
I try this function in eshell, got wrong path:

```
(sbt:find-root)
~/
```
But My project folder has following correct stuff
```

λ tree -L 2
.
├── build.sbt
├── project
│   ├── build.properties
│   ├── Dependencies.scala
│   └── target
├── src
│   ├── main
│   └── test
└── target
    ├── resolution-cache
    ├── scala-2.11
    └── streams
```

**Comment by mdedetrich** [comment]
I am also experiencing the same problem, willing to make a PR to fix the problem (does anyone know where to point me in the right place?)
