### ISSUE TITLE
feature request: find serializer in ruby on rails

### ISSUE THREAD

**Issue by intuxicated** [syl20bnr/spacemacs#9239]
its nice to have `find serializer` in rails api application.

**Comment by d12frosted** [comment]
Could you please add more information on your feature request?

Sorry if sounds dumb, but I am not using ruby, so don't understand what you mean.

**Comment by intuxicated** [comment]
We have `find controller` which looks at `app/controllers` by default to find a controller file.
It's nice to have `find serializer` command which should look at `app/serializers` by default to find serializer file.
Only rails API application has sterilizers file. So if you could search for directory first and if the directory exists then add the command to spacemacs, it would be awesome! _not sure is it possible at all_
> Sorry if sounds dumb, but I am not using Ruby, so don't understand what you mean.
I'm glad you are trying to help :+1:

**Comment by d12frosted** [comment]
@intuxicated Ok, now I understand. Please see #9310 for a fix. I will merge it eventually, hopefully after someone tests it.

**Comment by d12frosted** [comment]
@intuxicated that feature is in develop now, feel free to use
