### ISSUE TITLE
Find all string (pattern) occurrences in all the diffs of a git repository?

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#9241]

**Comment by CeleritasCelery** [comment]
You ask this at over at [magit](https://github.com/magit/magit)

**Comment by xged** [comment]
Yes, it could be solved in both Magit or Spacemacs (or even Helm, Ivy-counsel) scope. Is it a bad thing?

**Comment by d12frosted** [comment]
While I like the idea, I think it's out of the scope of Spacemacs. Spacemacs could use such a functionality, yes 😸 

If you want this functionality, try contacting `magit` developers or ask about it on reddit.
