### ISSUE TITLE
Layers not loaded when opening file with SPC f l

### ISSUE THREAD

**Issue by Hespian** [syl20bnr/spacemacs#9242]
#### Description :octocat:
When opening a file with `SPC f l`, the corresponding layer is not loaded.

#### Reproduction guide :beetle:
- Start Emacs
- press `SPC f l` and navigate to an existing file with an extension that belongs to a layer that you have installed (tried .tex, .h, .cpp)

*Observed behaviour:* :eyes: :broken_heart:
Major mode shows "Fundamental" instead of the right major mode. There is no syntax highlighting and no support for any language-specific features.

*Expected behaviour:* :heart: :smile:
Correct layer is loaded.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14) - also tried on develop (rev. c2fe26d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml html python helm auto-completion better-defaults emacs-lisp git
      (c-c   :variables c-c  -default-mode-for-headers 'c  -mode)
      markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control latex shell-scripts)
```

#### Backtrace :paw_prints:
```
```

**Comment by duianto** [comment]
That seems to be how the `find-file-literally` command works.
Here's it's help documentation `SPC h d k SPC f l`:

> SPC f l runs the command find-file-literally (found in
> evil-normal-state-local-map), which is an interactive compiled Lisp function in
> ‘files.el’.
> 
> It is bound to SPC f l, M-m f l.
> 
> (find-file-literally FILENAME)
> 
> Visit file FILENAME with no conversion of any kind.
> Format conversion and character code conversion are both disabled,
> and multibyte characters are disabled in the resulting buffer.
> The major mode used is Fundamental mode regardless of the file name,
> and local variable specifications in the file are ignored.
> Automatic uncompression and adding a newline at the end of the
> file due to ‘require-final-newline’ is also disabled.
> 
> You cannot absolutely rely on this function to result in
> visiting the file literally.  If Emacs already has a buffer
> which is visiting the file, you get the existing buffer,
> regardless of whether it was created literally or not.
> 
> In a Lisp program, if you want to be sure of accessing a file’s
> contents literally, you should create a temporary buffer and then read
> the file contents into it using ‘insert-file-contents-literally’.

And here's the Emacs manuals description of the command:

> If you wish to edit a file as a sequence of ASCII characters with no special encoding or conversion, use the M-x find-file-literally command. This visits a file, like C-x C-f, but does not do format conversion (see Format Conversion), character code conversion (see Coding Systems), or automatic uncompression (see Compressed Files), and does not add a final newline because of require-final-newline (see Customize Save). If you have already visited the same file in the usual (non-literal) manner, this command asks you whether to visit it literally instead.

source (4th paragraph from the bottom): http://www.gnu.org/software/emacs/manual/html_node/emacs/Visiting.html

A quick search seems to indicate that the `find-file-literally` command is used to reduce slow down when opening large files.

`SPC f f` is the "normal" file open key binding. It loads the packages/modes/configs for the current file type.

**Comment by bmag** [comment]
As @duianto wrote, this is a feature, not a bug. To open a file normally, use `SPC f f`.
