### ISSUE TITLE
https://spacemacs.org has an invalid TLS certificate (cert is for github.com/github.io)

### ISSUE THREAD

**Issue by beatgammit** [syl20bnr/spacemacs#9244]
It appears this is being used with `gh-pages` or something because when I go to https://spacemacs.org, I get an invalid TLS certificate error (NET::ERR_CERT_COMMON_NAME_INVALID).

[Here's an example of doing this](https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc) with [cloudflare](https://support.cloudflare.com/hc/en-us) ([free](https://www.cloudflare.com/plans/), though I haven't used it, so not sure if you can use a custom domain name), or the website can be moved to a low-cost VPS ([Vultr base instances are $2.50/month](https://www.vultr.com/pricing/), other options like [Linode](https://www.linode.com/) and [Digital Ocean](https://www.digitalocean.com/) start at $5) and done manually with [Let's Encrypt](https://letsencrypt.org/).

There may be other options for HTTPS with github pages, but I'm not an expert (I typically host at the VPS I own).

**Comment by benjamreynolds** [comment]
I would guess that https://github.com/syl20bnr/spacemacs.org would be a better place to log this.

**Comment by d12frosted** [comment]
@beatgammit thanks for noticing it! I have opened an issue in relevant repository. Closing this one.
