### ISSUE TITLE
Something strange with git-gutter and git-gutter+

### ISSUE THREAD

**Issue by simendsjo** [syl20bnr/spacemacs#9245]
I have a hidpi display, and I cannot get git-gutter og git-gutter+ to render large enough text.

This is the icon size when I turn it on:
![2017-07-18-172138_261x198_scrot](https://user-images.githubusercontent.com/351519/28325307-c14ed128-6bdd-11e7-9606-ad1602731053.png)

If I turn it off using `git-gutter+-toggle-fringe`, suddenly the symbols is rendered correctly. The fringe is turned off though, so adding new lines won't update the fringe.

![2017-07-18-172206_284x202_scrot](https://user-images.githubusercontent.com/351519/28325314-c8269486-6bdd-11e7-9c4f-ba6dfb798209.png)

I've also tried `diff-hl`, which only renders a bar (of a somewhat larger size), but it only updates when I save the buffer.

Any idea what what I can to do fix this issue? I cannot see anything obvious in the layer, but I really have no idea what to look for.

**Comment by whirm** [comment]
Bump
