### ISSUE TITLE
Project layouts should name the layout after the project name (not project root)

### ISSUE THREAD

**Issue by marienz** [syl20bnr/spacemacs#9247]
The perspectives created by `SPC p l` are named after the project root directory, not the project name. This doesn't work quite right if `projectile-project-name-function` is customized.

By default, the project name generated by projectile is the final component in the path (see `projectile-default-project-name`). And by default, spaceline displays the final component in the path on the modeline if the perspective name is a directory (see `spaceline-define-segment persp-name` in `spaceline-segments.el`). So by default, naming the perspective after the project root works pretty well.

But I have an environment in which the final component in the path is always the same, while the component before that is unique (they are paths that look a bit like `~/branches/$branchname/fixed-name`, the "fixed-name" bit has to stay the same to support some other tools I do not control, and using `~/branches/$branchname` as project root would be less convenient). So I customized `projectile-default-project-name` to detect those paths and name the project after the branch.

Now if I use `SPC p l` to create a project layout, the name on the modeline is still always "fixed-name", which is not very useful.

This happens because `spacemacs/ivy-persp-switch-project` (and the helm equivalent) create the perspective from the directory first, and only then switch projects (using the poorly named `projectile-switch-project-by-name`, which actually uses its argument as a directory).

It would be nice if Spacemacs supported this configuration.

I suspect the least brittle way of doing this is to first create the perspective the way it does now, then switch projects, and then try to rename the perspective to the project name (which probably needs to check if that perspective already exists...). Projectile only provides a function to get the project name for the current project (`projectile-project-name`), so figuring out the name before switching would require duplicating some projectile logic. And I'm guessing switching projects first puts the first buffer in the wrong perspective.

**Comment by d12frosted** [comment]
Wow. I didn't know about `projectile-project-name-function`. TIL 😸 

I see your point and I agree that `SPS p l` should respect value of `projectile-project-name-function`. As I usually say - PR is welcome 😸

**Comment by marienz** [comment]
Turns out just renaming at the end of `spacemacs/ivy-persp-switch-project` doesn't work, as that runs on the wrong buffer (?). I have something that works, but involves let-binding a hook variable to add a temporary hook that renames the perspective, which is terrible enough I wouldn't want my name on a PR with that code in it :)

I'll see if I can come up with something simple and robust enough for Spacemacs to use.

**Comment by beta1440** [comment]
@marienz could you post the code for your current solution to this issue?

**Comment by marienz** [comment]
This seems to work (it's using advice because it's in my `.spacemacs`, you obviously don't need that if you patch Spacemacs itself, and it's using Emacs 25.1's new form of advice but should work with `defadvice` too):

```lisp
(define-advice spacemacs/ivy-persp-switch-project
      (:around (func &rest args) my-name)
    "Use the project name, not root, as layout name."
    ;; Simply running the rename using :after advice does not seem to work.
    ;; Use a hook to get the right current buffer.
    ;; Make sure the hook variable actually exists first.
    (require 'projectile)
    (let ((projectile-find-file-hook
           (cons (lambda () (persp-rename (projectile-project-name)))
                 projectile-find-file-hook)))
      (apply func args)))
```

I think a slightly better approach is to let-bind `projectile-switch-project-action`, especially since my current approach relies on `projectile-switch-project-action` being (or at least calling) `projectile-find-file` anyway. And we can probably move the call to `persp-switch` in there as well, instead of creating it with the wrong name first.

**Comment by marienz** [comment]
Might still be valid, but I'm no longer using this combination of features, so I'll close this. I never found a nice way of making this work, but both Spacemacs and projectile have changed since I last tried, so it might be easier now...
