### ISSUE TITLE
Java layer on develop tries to default to meghanada if java-backend is not set

### ISSUE THREAD

**Issue by pschwartz** [syl20bnr/spacemacs#9248]
I currently have develop at c2fe26dd83a50b0f602155afd46639c108ae0e37 (current develop HEAD as of 07-19-17 9:30am est).

When starting a java project with the java layer enabled without a java-backed specified in the `dotspacemacs-configuration-layers` config block, meghanada is started instead of ecllim which is the listed default.

**Comment by pschwartz** [comment]
adding `java-backend 'eclim` forces it back to eclim.

**Comment by sdwolf** [comment]
I belive this is the correct behaviour since `meghanada` was made default on develop. Maybe you are reading the documentation for master, where `eclim` was once the default. Anyway, your fix is the correct way to handle it.

**Comment by AitBits** [comment]
Don't forget to switch to develop before reading docs if you are using spacemacs on develop branch!

**Comment by d12frosted** [comment]
Hey @pschwartz,

It looks like what you described is a correct behaviour. `java-backend` is set to `meghanada` by default. As [documentation](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/java/README.org#choosing-a-backend) suggests, just set it to whatever supported value you want.

Closing this issue. But feel free to continue discussion on this topic. If you think that default value should be changed, open up another issue, but please provide reasoning 😸 Thanks in advance.
