### ISSUE TITLE
[haskell-layer] [Feature request] Hoogle lookup with descriptions

### ISSUE THREAD

**Issue by tsoernes** [syl20bnr/spacemacs#9249]
I would really appreciate hoogle lookup with function descriptions inside the editor.
Currently, either you only get the function name or you are redirected to the browser.

Here's the functionality at display in Vim with the vim-hoogle extension:
![screenshot_20170719_231146](https://user-images.githubusercontent.com/6782404/28389865-1d8ba0ec-6cd8-11e7-8de9-3141d7515b37.png)

**Comment by d12frosted** [comment]
I bet you are using `helm-hoogle`. Try using `hoogle` (or `haskell-hoogle`) function instead. Though you might want to tune it a little bit.

<img width="688" alt="screenshot 2017-07-25 22 07 36" src="https://user-images.githubusercontent.com/6507913/28589183-b18caa50-7185-11e7-984d-4b2a1f93f344.png">

1. You need to install `hoogle` utility. And make sure that it works from terminal.
2. Set `haskell-hoogle-command` to `"hoogle"` or `"hoogle -i"` (if you wish to include extended information about input, e. g. documentation).
3. `M-x hoogle <ret> query <ret>`

P. S. Bind it and call on any symbol you wish to know about a little bit more. It takes symbol under the cursor 😸

**Comment by tsoernes** [comment]
Wonderful!

In my default spacemacs, that window opened to the right side, which was a bit awkward. To get it to open below, add this to `dotspacemacs/user-config`
```
(push '("*hoogle*" :dedicated t :position bottom :stick t :noselect t :height 0.4) popwin:special-display-config)
```
And if you want it NOT to be selected after searching hoogle add this:
```
(setq help-window-select nil)
```
