### ISSUE TITLE
Can't open shell after opening NeoTree

### ISSUE THREAD

**Issue by Iulian7** [syl20bnr/spacemacs#9251]
#### Description :octocat:
Cannot open multi-term shell with [SPC p '] after opening NeoTree. Message says: "Cannot split side window or parent of side window". 

#### Reproduction guide :beetle:
- Start Emacs
- Open a projectile project [SPC p p]
- Open NeoTree [SPC p t]
- Open multi-term shell [SPC p ']

*Observed behaviour:* :eyes: :broken_heart:
"Cannot split side window or parent of side window"

*Expected behaviour:* :heart: :smile:
Shell opens.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml helm osx auto-completion themes-megapack emacs-lisp elixir erlang
      (go :variables go-use-gometalinter nil gofmt-command "goimports")
      git markdown
      (shell :variables shell-default-term-shell "/usr/local/bin/zsh" shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom)
      syntax-checking version-control)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by henrymazza** [comment]
Are you using Neotree at right side?

**Comment by Iulian7** [comment]
No. I am using it on the left side.

**Comment by henrymazza** [comment]
I found another ticket open, looks like it’s an issue with shell-pop.


On 24 July 2017 at 17:00:38, Iulian7 (notifications@github.com) wrote:

No. I am using it on the left side.

**Comment by d12frosted** [comment]
@henrymazza could you please share the ticket?

**Comment by henrymazza** [comment]
So sorry, my bad. I was referring to #7446

**Comment by d12frosted** [comment]
Oh right, it seems that this issue is a duplicate. Closing in favour of #7446. 

Thanks for noticing 😸
