### ISSUE TITLE
Colors layer's variables colorization not working

### ISSUE THREAD

**Issue by finiteprods** [syl20bnr/spacemacs#9254]
#### Description :octocat:
In the Colors layer, configuring `colors-colorize-identifiers` to `variables` does not work.

#### Reproduction guide :beetle:
- Start Emacs
- Open source code file e.g. a Python file
- Toggle colors-identifiers-mode with `SPC t C v`

*Observed behaviour:* :eyes: :broken_heart:
Toggle has no effect

*Expected behaviour:* :heart: :smile:
Variable identifiers colorized  

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip 'manual)
 (colors :variables colors-enable-rainbow-identifiers 'variables colors-enable-nyan-cat-progress-bar t)
 emacs-lisp git github
 (haskell :variables haskell-completion-backend 'intero)
 erlang elixir python org
 (spell-checking :variables spell-checking-enable-by-default nil enable-flyspell-auto-completion nil)
 syntax-checking bibtex
 (latex :variables latex-enable-auto-fill t latex-enable-folding t latex-build-command "Make")
 rcirc)
```

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-function font-lock-ensure)
  font-lock-ensure(1 1391)
  color-identifiers:python-get-declarations()
  color-identifiers:list-identifiers()
  color-identifiers:refresh()
  color-identifiers-mode()
  (progn (if (and (boundp (quote rainbow-identifiers-mode)) rainbow-identifiers-mode) (progn (rainbow-identifiers-mode -1))) (color-identifiers-mode))
  (if (spacemacs/toggle-color-identifiers-mode-p) (progn (color-identifiers-mode -1) (if (called-interactively-p (quote any)) (progn (message "color-identifiers-mode disabled.")))) (progn (if (and (boundp (quote rainbow-identifiers-mode)) rainbow-identifiers-mode) (progn (rainbow-identifiers-mode -1))) (color-identifiers-mode)) (if (called-interactively-p (quote any)) (progn (message "color-identifiers-mode enabled."))))
  (if (or (null (quote nil)) (and (or (and (symbolp (quote nil)) (boundp (quote nil))) (listp (quote nil))) nil)) (if (spacemacs/toggle-color-identifiers-mode-p) (progn (color-identifiers-mode -1) (if (called-interactively-p (quote any)) (progn (message "color-identifiers-mode disabled.")))) (progn (if (and (boundp (quote rainbow-identifiers-mode)) rainbow-identifiers-mode) (progn (rainbow-identifiers-mode -1))) (color-identifiers-mode)) (if (called-interactively-p (quote any)) (progn (message "color-identifiers-mode enabled.")))) (message "This toggle is not supported."))
  spacemacs/toggle-color-identifiers-mode()
  call-interactively(spacemacs/toggle-color-identifiers-mode nil nil)
  command-execute(spacemacs/toggle-color-identifiers-mode)
```

**Comment by duianto** [comment]
It's working for me in both the latest develop and master branches.

![emacs_2017-07-21_21-48-00](https://user-images.githubusercontent.com/13420573/28479811-5c19e2c4-6e5e-11e7-8e7e-64821ea583db.png)

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. c2fe26dd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip 'manual)
 autohotkey colors emacs-lisp git helm markdown
 (org :variables org-agenda-files
      '("c:/Users/Username/Documents/"))
 python version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by d12frosted** [comment]
@finiteprods I see you have configured `colors-enable-rainbow-identifiers` to `'variables` inside of `dotspacemacs-configuration-layers`. But you should configure `colors-colorize-identifiers`.

Could you please share relevant code that does the configuration of `colors-colorize-identifiers`? 😸

**Comment by finiteprods** [comment]
@duianto That is indeed a typo in my .spacemacs config, thanks for pointing that out! That _should_ enable it globally...

- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip 'manual)
 (colors :variables colors-colorize-identifiers 'variables colors-enable-nyan-cat-progress-bar t)
 emacs-lisp git github
 (haskell :variables haskell-completion-backend 'intero)
 erlang elixir python org
 (spell-checking :variables spell-checking-enable-by-default nil enable-flyspell-auto-completion nil)
 syntax-checking bibtex
 (latex :variables latex-enable-auto-fill t latex-enable-folding t latex-build-command "Make")
 rcirc)
```

Hence to reproduce the error now, it's enough to open any Python file (without needing to toggle `SPC t C v` as before).

```
Debugger entered--Lisp error: (void-function font-lock-ensure)
  font-lock-ensure(1 920)
  color-identifiers:python-get-declarations()
  color-identifiers:list-identifiers()
  color-identifiers:refresh()
  color-identifiers-mode(1)
  color-identifiers-mode-maybe()
  global-color-identifiers-mode-enable-in-buffers()
  run-hooks(after-change-major-mode-hook)
  run-mode-hooks(python-mode-hook)
  python-mode()
  ...
```
I wonder whether this is due to a [recent change in color identifiers mode](https://github.com/ankurdave/color-identifiers-mode/commit/d57e162c2dcb926291ded21cbe46b98ad0ca32c8), and that `font-lock-ensure` appears to not be defined in emacs 24, e.g. [this issue](https://github.com/Malabarba/latex-extra/issues/7).

**Comment by d12frosted** [comment]
We have two options:

- Ask upstream to avoid using Emacs 25 only features or at least have a fallback.
- Drop support of `color-identifiers-mode` on Emacs 24.

I will understand upstream maintainer refusal to support Emacs 24.

**Comment by finiteprods** [comment]
The offending commit was reverted upstream, can confirm now working for me.

**Comment by d12frosted** [comment]
Thanks for reporting back ❤️
