### ISSUE TITLE
enhancement - Provide spacemacs logo as .icns

### ISSUE THREAD

**Issue by mheider** [syl20bnr/spacemacs#926]
I think it would be a great idea to change to provide the spacemacs logo (https://github.com/syl20bnr/spacemacs/raw/master/doc/img/title2.png) as .icns to change the symbol of emacs in your dock, if you want.

**Comment by mheider** [comment]
Is the Logo available as .psd (or anything like that)? Then I could create the .icns-File.

**Comment by syl20bnr** [comment]
Here it is: https://github.com/nashamri/spacemacs-logo

**Comment by mheider** [comment]
Thanks!
