### ISSUE TITLE
How to make popup buffers always reuse current window?

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#9261]
How to tell Spacemacs to not (automatically) create (split) new windows at all?

Bonus if you can specify exceptions to this rule.

I tried changing settings `split-height-threshold` & `split-width-threshold`, few ones from Popwin, Window-purpose as well as the the following:

    same-window-regexps ".*"
    pop-up-windows nil
    split-window-preferred-function nil

.. but it had no seeming effect.

**Comment by d12frosted** [comment]
@bmag do you have any ideas? 😸

**Comment by bmag** [comment]
I'm assuming you are talking about popup windows such as the help buffer, that popup in the bottom of the frame. Try configuring `popwin:special-display-config` in `user-config`. The variables `split-height-threshold`, `split-width-threshold`, `pop-up-windows` and `split-window-preferred-function` have nothing to do with it.

If you're talking about generally preventing Emacs from ever splitting that frame, then it's a different story.

**Comment by xged** [comment]
@bmag `(setq-default popwin:popup-window-height 100)` does not work :/

**Comment by bmag** [comment]
I don't know what you're trying to do, nor what branch you're using.

**Comment by xged** [comment]
@bmag To make popup windows to be full screen by default.

**Comment by bmag** [comment]
If you mean something like:

Repro steps:
- start with an emacs frame that has 1 window, and that window displays some editable buffer (e.g. `~/.spacemacs.d/init.el`)
- show documentation for some function, e.g. `SPC h d f display-buffer RET`

Observed behavior: the window is split into 2 windows, the lower one displays the help buffer (`*Help*`).

Desired behavior: no new split, the original window remains the only window and displays the help buffer.

I'm not sure it's possible (within reason), but before looking further:
- what is your system information? (`SPC h d s`)
- if you start with 2 windows open side-by-side, e.g. `~/.spacemacs.d/init.el` on the left and `~/.emacs.d/init.el` on the right, then press `SPC h d f display-buffer RET`, what is the desired behavior?

**Comment by xged** [comment]
@bmag
1) 
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 66f7b9dda)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy
 (ivy :variables ivy-initial-inputs-alist nil)
 auto-completion emacs-lisp git markdown multiple-cursors treemacs org shell
 (shell :variables shell-default-height 100 shell-default-full-span nil)
 spell-checking
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking version-control python typescript haskell java
 (java :variables eclim-eclipse-dirs
       '("~/.eclipse")
       eclim-executable "~.eclipse/eclim")
 github ranger colors html)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

2) Reuse the focused window. I don't work with multi-window setup though (unless its like a special diffing mode).

(Manipulating buffers is effortless in my setup, I would like to use my whole screen estate and not bother with windows.)

**Comment by bmag** [comment]
The following code should do what you want. Add it to `user-config`:
```elisp
(with-eval-after-load 'window-purpose
  ;; remove bottom split popup
  (setq purpose-special-action-sequences
            (delete '(pupo/display-condition pupo/display-function)
                    purpose-special-action-sequences))
  ;; make popup reuse current window
  (add-to-list 'purpose-special-action-sequences
               '(pupo/display-condition display-buffer-same-window
                                        display-buffer-use-some-window)))
```

We now use a custom solution for popup windows that relies on window-purpose but understand `popwin:special-display-config` (enough for how Spacemacs handles popup window, at least), so that's why the snippet uses window-purpose and not popwin. It might still have quirks, especially if using dedicated windows, but I'm hoping that isn't a problem in your use-case.

That might still have problems due to loading order, so if it doesn't work please post the value of `purpose-spcial-action-sequences` (can be seen by `SPC h d v`) after a fresh start of Spacemacs.

**Comment by xged** [comment]
@bmag Works with *Help* buffers. Does not effect something like `magit-log-current`.

**Comment by bmag** [comment]
No, that one isn't a popup buffer. For magit buffers you'd want to customize `magit-display-buffer-function`.

**Comment by xged** [comment]
@bmag I just checked `magit-display-buffer-function` via `C-h-v` - this *Help* buffer is fullscreen, then entered `magit-mode.el` link - this *Help* buffer SPLIT the screen. :/

**Comment by xged** [comment]
@bmag Setting magit-display-buffer-function to 'magit-display-buffer-same-window-except-diff-v1 solved it in magit department, thanks.

**Comment by bmag** [comment]
Here's an extreme idea. I don't know what issues it may have, but theoretically it causes all buffers to display in the current window, except for buffers that have their own configuration (e.g. which-key, treemacs) or commands that explicitly prohibit the current window (e.g. `switch-to-buffer-other-window`). It seemed to work nicely for the 5 minutes I tried it.

```elisp
(defun always-true (&rest _args)
  "Function that always return true."
  t)
(setq display-buffer-base-action '(display-buffer-same-window))
(with-eval-after-load 'window-purpose
  (add-to-list 'purpose-special-action-sequences
               '(always-true display-buffer-same-window)
               'append))
```

**Comment by xged** [comment]
@bmag It works on magit. It does not work on *Help*, shell, counsel, ivy, helm, swiper.

**Comment by bmag** [comment]
popup buffers (Help) have their own config and can be treated as I wrote above (excluding `spacemacs-purpose-popwin` package may also work). If shell means shell-pop (`SPC '`) then it does its own thing. Ivy uses the minibuffer so can't be a regular a window, Helm has its own config. Counsel uses Ivy, Swiper uses Helm. Besides, Ivy and Helm are meant to be better prompts, don't make sense if they hide the original buffer and even won't work correctly.

**Comment by xged** [comment]
@bmag When it comes to mini-buffers, I agree, just checking if the snippet does what it suppose to. What about that "magit-mode.el" case (a link in *Help* buffer)?

**Comment by bmag** [comment]
> What about that "magit-mode.el" case (a link in Help buffer)?

Don't know, works for me.

**Comment by xged** [comment]
I see. I close as my current cases are more or less solved, but a feature to control all 'windowing' (splitting) from one place is to be desired.
