### ISSUE TITLE
"yapfify-buffer" command resets buffer scroll in other windows.

### ISSUE THREAD

**Issue by KelSolaar** [syl20bnr/spacemacs#9263]
#### Description :octocat:
"yapfify-buffer" command resets buffer scroll in other windows.

#### Reproduction guide :beetle:
- Start Emacs
- Load Python file
- Scroll middle of the file
- Create new window, e.g. `SPC w /`
- Issue `yapfify-buffer` with `, =` 
 
*Observed behaviour:* :eyes: :broken_heart:
The current window buffer scroll position is preserved while other windows are scrolled to top as illustrated by this screencast: https://www.screencast.com/t/S33hONBT

*Expected behaviour:* :heart: :smile:
All the windows scroll position should be preserved.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: nil (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm html imenu-list javascript markdown python spell-checking syntax-checking windows-scripts yaml
                 (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by d12frosted** [comment]
I wonder if it's an upstream issue 😄
