### ISSUE TITLE
Powerline disappears when dotspacemacs-display-default-layout is set to t

### ISSUE THREAD

**Issue by ZaenChou** [syl20bnr/spacemacs#9264]
#### Description :octocat:
Powerline goes weird after setting dotspacemacs-display-default-layout to true

#### Reproduction guide :beetle:
- Start Emacs
- Open .spacemacs file
- Set dotspacemacs-display-default-layout to t
- Save and load the .spacemacs file
- Close the frame and re-open one

*Observed behaviour:* :eyes: :broken_heart:
- At startup, with the \*spacemacs\* buffer, the powerline disappears. The bar is still there, but the contents are gone. (Not sure if the language makes sense, see the image)
- The interesting part is, as there are two frames opened, when the pointer is in the first frame, the bar on the second frame suddenly becomes functional (the powerline emerges), and vice versa. On both occasions, the powerline shows the information about their own frames, not about where the pointers are at.
*Expected behaviour:* :heart: :smile:
  The default layer name (mine set to "master") is displayed just like those other layouts' names, and of course without the powerline going weird.

#### System Info :computer:
- OS: gnu/linux (Arch btw)
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers: (so many lol)
```elisp
(ruby ruby-on-rails python lua windows-scripts emacs-lisp common-lisp scheme latex markdown go elixir php html javascript shell-scripts
      (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
      rust sql ipython-notebook chinese systemd version-control git github helm
      (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
      spell-checking syntax-checking better-defaults
      (colors :variables color-colorize-identifiers 'all colors-enable-nyan-cat-progress-bar t)
      themes-megapack theming spacemacs-layouts
      (org :variables org-enable-github-support org-enable-org-journal-support)
      games twitter slack chrome finance pdf-tools pandoc ranger
      (shell :variables shell-default-shell 'multi-term)
     ))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by ZaenChou** [comment]
Hmm, it is very hard to say one minute after issuing this, but I just found the problem...
Error during redisplay: (eval (spaceline-ml-main)) signaled (wrong-type-argument stringp Master) [2 times]
The argument type!
Sorry guys.
PS: Wondering if it's better to delete this issue altogether, if so, please tell me how. Thanks

**Comment by ZaenChou** [comment]
Oh yes, the images
![screenshot_20170723_104501](https://user-images.githubusercontent.com/13728568/28495786-ecc8c4d4-6f94-11e7-839c-8e5a68e89445.png)
![screenshot_20170723_104518](https://user-images.githubusercontent.com/13728568/28495787-f1eec5da-6f94-11e7-84af-dd361b1a88f7.png)
![screenshot_20170723_104618](https://user-images.githubusercontent.com/13728568/28495788-f5d83b22-6f94-11e7-9180-e6ce93091f56.png)

**Comment by bmag** [comment]
So, you have set `dotspacemacs-default-layout-name` to `'Master`, which caused problems because `dotspacemacs-default-layout-name` is supposed to be a string, then you changed the value to `"Master"` and all the issues are gone and everything is good now?

**Comment by ZaenChou** [comment]
Yes sir, exactly. I thought double quotes were for comments ! (Seriously)

**Comment by bmag** [comment]
@ZaenChou thanks for the confirmation, the problem has been solved so I'm closing the issue. No need to delete the issue (I'm not sure if that's even possible)
