### ISSUE TITLE
org-wiki package; how to install under spacemacs

### ISSUE THREAD

**Issue by poulpoulsen** [syl20bnr/spacemacs#9269]
hello,
i want to use org-wiki with spacemacs.
Because there is no layer and unfortunately no installation available from elpa/melpa i have to use the instructions from developer:
Method 1 - Bootstrap installer

Evaluate this code in the scratch buffer that will install all dependencies and this package. The scratch buffer can be evaluated with M-x eval-buffer.

(let ((url "https://raw.githubusercontent.com/caiorss/org-wiki/master/org-wiki.el"))     
      (with-current-buffer (url-retrieve-synchronously url)
	(goto-char (point-min))
	(re-search-forward "^$")
	(delete-region (point) (point-min))
	(kill-whole-line)
	(package-install-from-buffer)))
this works.
But then i have to insert (require 'org-wiki) into .emacs or init.el.
Because spacemacs dont use .emacs i have to insert it into init.el.
Now every start spacemacs couldnt find the package, because it is not available in elpa/melpa.
I think, that it could be possible to insert it into .spacemacs file. 
But in which section?

Any help appreciate
Poul

**Comment by bmag** [comment]
These instructions won't work. Spacemacs will delete the package during startup. I recommend to install the as an additional package (see `dotspacemacs-additional-packages`) with a location recipe. See the documentation for more info, and Spacemacs source for examples of how to use a location recipe (e.g. `hoon-mode` is a simple example).

**Comment by ngm** [comment]
There's a pull request for an org-wiki layer here: https://github.com/syl20bnr/spacemacs/pull/8447/files

Given the way the org stuff is organised at the moment in develop - i.e. everything is maintained in the org layer itself (including e.g. org-brain) (see https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bemacs/org/packages.el) I'd guess that that PR might not be pulled in as it is.

So what I did was just copy the orgwiki layer code from that repo and add it as my own private layer:

```
$ cd ~/Code
$ git clone https://github.com/swaroopch/spacemacs spacemacs-org-wiki-layer
$ cd spacemacs-org-wiki-layer 
$ git checkout orgwiki-layer
$ cp -r spacemacs-org-wiki-layer/layers/+emacs/orgwiki ~/.emacs.d/private
```

Then add `orgwiki` as a layer in your `.spacemacs` file.

**Comment by bmag** [comment]
Great! It seems the issue has been solved, so I'm closing it.

**Comment by poulpoulsen** [comment]
hello,
i tried it, but unfortunately emacs throws an error.
what can i do?

Regards
Poul

Warning (initialization): An error occurred while loading ‘c:/Users/Held/.emacs.d/init.el’:

Symbol's value as variable is void: org-wiki-packages

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

**Comment by bmag** [comment]
@poulpoulsen oh sorry, I didn't notice the previous comment wasn't from you. I'll re-open the issue.

If you tried to follow the steps that @ngm wrote, then you probably misnamed the layer's directory. Try renaming the directory from `org-wiki` to `orgwiki`. You can read the documentation for writing layers to understand why the directory name matters.

**Comment by poulpoulsen** [comment]
hello,
ok another try:
during update this message pops up.

Failed to verify signature org-20170724.tar.sig:
Bad signature from 474F05837FBDEF9B GNU ELPA Signing Agent <elpasign@elpa.gnu.org>

Command output:
gpg: Signature made 07/24/17 11:10:02 Mitteleurop ische Sommerzeit using DSA key ID 7FBDEF9B
gpg: BAD signature from "GNU ELPA Signing Agent <elpasign@elpa.gnu.org>" [unknown]

Regards
Poul

**Comment by bmag** [comment]
My guess: there was a problem downloading the tar archive (part of package installation process), so the file was corrupted and thus verification failed.
Suggestion: try installing again

**Comment by poulpoulsen** [comment]
hello,
you are right.
Now it is installing, but something isnt correct.
The function to create a menu for org-wiki is not working.
And something with org package is not ok.

Regards
Poul
Loading c:/Users/Held/.emacs.d/core/core-load-paths.el (source)...done
Loading c:/Users/Held/.spacemacs...done
(Spacemacs) Error in dotspacemacs/user-init: Symbol’s function definition is void: org-wiki-make-menu

Setting the font...
PNG warning: Interlace handling should be turned on when using png_read_image
Loading c:/Users/Held/.emacs.d/layers/+completion/helm/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+tools/pandoc/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+lang/emacs-lisp/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+vim/evil-commentary/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+lang/markdown/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+emacs/org/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+tools/deft/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/private/orgwiki/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/private/orgwiki/layers.el (source)...
Loading c:/Users/Held/.emacs.d/layers/+emacs/org/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/private/orgwiki/layers.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+checkers/syntax-checking/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+source-control/version-control/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+vim/vinegar/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+distributions/spacemacs/layers.el (source)...
Loading c:/Users/Held/.emacs.d/layers/+distributions/spacemacs-base/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-completion/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-layouts/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-editing/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-editing-visual/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-evil/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-language/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-misc/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-ui/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-ui-visual/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-org/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+distributions/spacemacs/layers.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+distributions/spacemacs-bootstrap/packages.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+distributions/spacemacs-bootstrap/funcs.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-ui-visual/funcs.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-evil/funcs.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-editing/funcs.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-layouts/funcs.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-completion/funcs.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+distributions/spacemacs-base/funcs.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+completion/helm/funcs.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+tools/pandoc/funcs.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+lang/emacs-lisp/funcs.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+lang/markdown/funcs.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+emacs/org/funcs.el (source)...done
Loading c:/Users/Held/.emacs.d/private/orgwiki/funcs.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+checkers/syntax-checking/funcs.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+source-control/version-control/funcs.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+vim/vinegar/funcs.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+distributions/spacemacs-bootstrap/config.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-ui-visual/config.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-layouts/config.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+spacemacs/spacemacs-completion/config.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+distributions/spacemacs-base/config.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+lang/emacs-lisp/config.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+lang/markdown/config.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+emacs/org/config.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+checkers/syntax-checking/config.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+source-control/version-control/config.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+vim/vinegar/config.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/auto-layer.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+distributions/spacemacs-base/keybindings.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+source-control/version-control/keybindings.el (source)...done
Loading c:/Users/Held/.emacs.d/layers/+vim/vinegar/keybindings.el (source)...done
Loading c:/Users/Held/.emacs.d/.cache/spacemacs-buffer.el (source)...done
Spacemacs is ready.
Loading c:/Users/Held/.emacs.d/.cache/recentf...done
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-next-line’ originally mapped on ‘C-n’
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-toggle-time-grid’ originally mapped on ‘G’
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-filter-remove-all’ originally mapped on ‘|’
Open the quickhelp.
Skipping check for new version (reason: dotfile)

**Comment by bmag** [comment]
Somewhere the function `org-wiki-make-menu` is used before it was defined. There is either a problem in the layer, your configuration, or the installed package. I guess you need to fix it.

**Comment by poulpoulsen** [comment]
ok, but i cannot do that.
Because the implemented org-wiki commands work if i strike them, we can close this ticket.
Regards
Poul
