### ISSUE TITLE
Continuosly getting ‘invalid face reference: t‘ message in the message buffer

### ISSUE THREAD

**Issue by yalu** [syl20bnr/spacemacs#9271]
#### Description :octocat:
Continuosly getting ‘invalid face reference: t‘ message in the message buffer

#### Reproduction guide :beetle:
- Start Emacs with clojure layer turned on and (setq clojure-enable-fancify-symbols t) in spacemacs configuration.
- open any clj or cljs file
- switch to message buffer or have both buffers open side-by-side to observe the messages.

*Observed behaviour:* :eyes: :broken_heart:
Continuosly getting ‘invalid face reference: t‘ message in the message buffer

*Expected behaviour:* :heart: :smile:
No such messages

If I disable ‘clojure-enable-fancify-symbols messages go away.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: nil (rev. 9825606c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(nginx php sql
       (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle :disabled-for org erc)
       (org :variables org-enable-github-support t)
       (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
       (spell-checking :variables spell-checking-enable-by-default nil)
       (version-control :variables version-control-diff-tool 'diff-hl)
       (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
       (typography :variables typography-enable-typographic-editing t)
       (colors :variables colors-enable-rainbow-identifiers nil colors-enable-nyan-cat-progress-bar
               (display-graphic-p))
       better-defaults ranger emacs-lisp common-lisp erc git markdown syntax-checking evil-cleverparens vinegar extra-langs semantic tmux gtags fasd clojure parinfer html java
       (javascript :variables javascript-disable-tern-port-files nil)
       react python ruby shell-scripts yaml speedtype theming)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by neolee** [comment]
Same here. Toggling on clojure-enable-fancify-symbols causes continuously getting ‘invalid face reference: t‘ message in the message buffer.

**Comment by Miciah** [comment]
Does #11032 resolve the issue?

**Comment by jr0cket** [comment]
@syl20bnr suggest closing this Clojure issue as no issues have been reported since #11032
Thank you.

**Comment by duianto** [comment]
Thanks for the suggestion.
