### ISSUE TITLE
Alternate language layer for Common Lisp

### ISSUE THREAD

**Issue by mfiano** [syl20bnr/spacemacs#9274]
The current Common Lisp layer uses the SLIME IDE. There also exists a more modern, more featureful IDE known as Sly. This is a separate layer which adds support for Sly and contributing packages, because implementing this as a configuration option to a single language layer would not work that great. Please include this into the main repository. Thanks

https://github.com/mfiano/common-lisp-sly

Thank you

**Comment by mfiano** [comment]
@d12frosted, @syl20bnr Any input on this? Quite a few Lispers have been waiting patiently for half a year with no response.

**Comment by gcentauri** [comment]
I'm interested in trying to help get this going again. @mfiano - i noticed your layer repo has been archived, were you just done maintaining it?

**Comment by xanlsh** [comment]
@mfiano Normally I'd open this on the `common-lisp-sly` repo, but that's been archived.

If I clone the layer to `~/.emacs.d/private/` and add `common-lisp-sly` to my list of layers, the following error occurs, and much of spacemacs' startup (such as setting up evil-mode, other keybindings, etc) fails:

```
Warning (initialization): an error occurred while loading init.el

Symbol's function definition is void: configuration-layer/package-used-p
```

The offending code seems to be line 13 in `common-lisp-sly/funcs.el`

I'm also interested in getting this into main spacemacs, let me know if I can do anything to help

**Comment by gcentauri** [comment]
@xanlsh - I was able to install it and it appears to load fine, so you may have something wrong with your init setup? 

I do get a few errors when loading

```
Auto-evilification could not remap these functions in map ‘archive-mode-map’:
   - ‘archive-chgrp-entry’ originally mapped on ‘G’
Auto-evilification could not remap these functions in map ‘tar-mode-map’:
   - ‘tar-chgrp-entry’ originally mapped on ‘G’
Toggle: evil-safe-lisp-structural-editing
This toggle is not supported.
```

But i'm not sure if they're related.  So far so good for me though, I will explore a bit more.

**Comment by mfiano** [comment]
It's been broken for months according to reports I've seen. Sadly, I moved to a custom config with `straight.el` to prevent frequent breakage of Spacemacs. As such, I don't maintain `common-lisp-sly` anymore, and the other contributers have also moved away from Spacemacs. I'm afraid the future of that repository is in the hands of anyone who wants to fork it.
