### ISSUE TITLE
org-wiki package; how to install under spacemacs

### ISSUE THREAD

**Issue by poulpoulsen** [syl20bnr/spacemacs#9276]
hello,
under #9269 it seems, that a result occur.

Unfortunately after i follow the lins emacs throws the following error:
 
 Warning (initialization): An error occurred while loading ‘c:/Users/Held/.emacs.d/init.el’:

Symbol's value as variable is void: org-wiki-packages

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

I' m not a programmer.
What can i do now?
Any clues?

Regards
Poul

**Comment by bmag** [comment]
I re-opened #9269, please keep the discussion there.
