### ISSUE TITLE
-SPC P P- doesn't show the right project's files after first execution

### ISSUE THREAD

**Issue by mirubiri** [syl20bnr/spacemacs#9277]
#### Description :octocat:
-SPC P P- is not working as expected, it will only switch to a project once.

#### Reproduction guide :beetle:
- Start Emacs
- Hit -SPC P P- (default behavior)
- Select a project and press enter
- Hit enter again to see the project's file list
- Select a file and press enter
- Hit -SPC P P- again
- Select a different project and press enter

*Observed behaviour:* :eyes: :broken_heart:
After switching to a second project, helm still shows a list for the previously selected project.

*Expected behaviour:* :heart: :smile:
After switching to a second project, I expect to see the list of files for that project.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp dash git github yaml markdown org themes-megapack syntax-checking
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 (version-control :variables version-control-diff-tool 'diff-hl version-control-diff-side 'left version-control-global-margin 't)
                 html
                 (ruby :variables ruby-version-manager 'rbenv)
                 ruby-on-rails javascript typescript yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
```

**Comment by zer09** [comment]
Projectile has a new update today, it seems it already fixed. I don't experience the issue again.

**Comment by mirubiri** [comment]
I have updated projectile, and I still can reproduce the issue with Helm, Ivy seems to work like charm.

**Comment by vlymar** [comment]
Same - Upgraded to projectile `Version: 20170727.602` today and I'm still seeing this issue.

**Comment by zer09** [comment]
It is working on Ivy now, I don't know about Helm.

**Comment by mirubiri** [comment]
Helm still doesn't work

**Comment by bjarkevad** [comment]
I'm encountering this issue as well, but only when the `ruby-on-rails` layer is installed.

**Comment by mirubiri** [comment]
Yep, I can confirm I'm using rails layer too

**Comment by zakvdm** [comment]
I had the same issue, and removing the `ruby-on-rails` layer has fixed it.

This issue is actually super annoying and broke one of my main emacs workflows (switch to new project and pick a file). Unfortunately, my elisp isn't good enough to track this down. How can we get a fix for this? I'm not even sure if we should rather be opening an issue in the `projectile-rails` repo?

**Comment by asok** [comment]
@zakvdm I'm a maintainer of `projectile-rails`. Lets try to track this down here. What version of `projectile-rails` and `spacemacs` are you using?

**Comment by asok** [comment]
Also do you have any project on a remote machine (via tramp) in your projects list?

**Comment by asok** [comment]
Good news - I can reproduce it. Funny enough it only happens when I use helm. With `ivy` layer it works fine.

**Comment by asok** [comment]
After much debugging I've found out that `projectile-cached-project-root` is set to the current projects and this causes [here](https://github.com/bbatsov/helm-projectile/blob/4466adbcada8be19ec97b9dba52e12b8da3da849/helm-projectile.el#L505) for the files to be from another project.
I still need to discover why this bug happens only with `projectile-rails` turned on, and not with `ivy`.

**Comment by asok** [comment]
OK it looks like it used to be the same for `ivy`: https://github.com/ericdanan/counsel-projectile/issues/32

**Comment by asok** [comment]
I've pushed a fix. If anyone is using unstable melpa please update `projectile-rails` and let me know if it helped.

**Comment by bjarkevad** [comment]
Just tried out the latest version, and it seems to have fixed the issue! Awesome work @asok, thank you so much! 👍

**Comment by asok** [comment]
I've pushed version 0.16.1 to the stable melpa.

**Comment by vlymar** [comment]
can confirm pulling the stable update fixed this issue for me.

thank you!

**Comment by natsumi** [comment]
I'm  on the develop version of Spacemacs (0.300.0) and its setup to use its version of stable elpa at https://github.com/syl20bnr/spacelpa    
Which seems to have version 0.15.0 of proejctile-rails.

How do I just update that one package to the version 0.16.1 that is on stable melpa?

Thanks.

**Comment by asok** [comment]
@natsumi you could call `paradox-list-packages` locate the package and hit `I` (that is a capital `i`) followed by `x`.

@mirubiri I think you can close this issue.

**Comment by mirubiri** [comment]
This issue is solved. Thank you all!
