### ISSUE TITLE
Confluence layer support Atlassian Confluence 5.10.2?

### ISSUE THREAD

**Issue by flychen50** [syl20bnr/spacemacs#9280]
Confluence layer support Atlassian Confluence 5.10.2?

**Comment by flychen50** [comment]
i use the confluence layer to create page in confluence 5.1.2 ,but only tilte no content

**Comment by d12frosted** [comment]
Did you try against 5.10.2?

**Comment by flychen50** [comment]
sorry,spelling mistake @d12frosted

**Comment by d12frosted** [comment]
Ah I see. So you create page and fill title with content, but on the confluence page you only see title without content, right?

**Comment by flychen50** [comment]
yes

**Comment by d12frosted** [comment]
I see.

Have you updated your packages? If no, please do so and try again, otherwise it should be reported upstream as Spacemacs doesn't do much with confluence rather then just configure existing package.
