### ISSUE TITLE
how can i access diff-hl-flydiff-mode?

### ISSUE THREAD

**Issue by poulpoulsen** [syl20bnr/spacemacs#9281]
hello,
i try to use this mode.
First i activate layer version-control.
But how can i switch into this mode?
I can see Ediff and several commands, but nothing about diff-hl-flydiff-mode.
Perhaps i need another package...

Regards
Poul

**Comment by gustavopch** [comment]
This question was asked in reddit and I'm pasting here the solution that worked for me given by a use called mirubiri:

> Put this in your spacemacs-configuration-layers
> 
>     (version-control :variables
>                      version-control-diff-tool 'diff-hl
>                      version-control-diff-side 'left
>                      version-control-global-margin 't)
> 
> And this in your dotspacemacs/user-config
> 
>     (diff-hl-flydiff-mode '(:global t))

Source: https://www.reddit.com/r/spacemacs/comments/6q9qu9/how_can_i_use_diffhlflydiffmode/

**Comment by CeleritasCelery** [comment]
Feel free to close this if you have found the answer

**Comment by poulpoulsen** [comment]
hello,
for me it is not clear how this is a solution.
i put this in restart emacs and there was no error. thats good.
But how could i access it? I only want to diff two files, no projects or anything else.
How will this be possible?

Regards
Poul

**Comment by CeleritasCelery** [comment]
If you want to diff 2 files, just use `ediff-files`. `diff-hl-flydiff-mode` is just a global minor mode so there is no "accessing it". It just change the behavior of `diff-hl` which shows the git diff in the fringe. If you want to diff a file across comits, use `magit-diff`.

**Comment by poulpoulsen** [comment]
could be closed.
i dont use spacemacs anymore.
