### ISSUE TITLE
Integrating the spacemacs Elixir layer with Mix Format

### ISSUE THREAD

**Issue by johnhamelink** [syl20bnr/spacemacs#9284]
It'd be amazing if the `=` reformatting hotkey could be rebound to use `mix format` inside the Elixir layer. There seems to be work being done in order to make it as easy as possible to implement the formatter from Emacs and IDEs in general:

https://elixir-lang.org/blog/2018/01/17/elixir-v1-6-0-released/
https://github.com/anildigital/mix-format.el

**Comment by pdawczak** [comment]
On similar note, it would be nice, if there was a way of configuring triggering `mix format` on current buffer (eg. when saving the file?)

**Comment by johnhamelink** [comment]
@pdawczak yes! I updated the issue.

**Comment by magiccookie** [comment]
bump

**Comment by shanesveller** [comment]
As an elisp amateur and someone poking around with [straight.el](https://github.com/raxod502/straight.el) this is what I've had in place and working mostly as intended, via a community member's [mix-format.el package](https://github.com/anildigital/mix-format.el):

```elisp
(require 'f)

(use-package mix-format
  :straight (:host github
                   :repo "anildigital/mix-format.el"
                   :branch "master")
  :init
  (setq mixfmt-elixir (f-expand "~/.asdf/shims/elixir")
        mixfmt-mix (f-expand "~/.asdf/shims/mix"))
  (add-hook 'elixir-mode-hook
            (lambda () (add-hook 'before-save-hook 'mix-format-before-save)))
  (add-hook 'mix-format-hook '(lambda ()
                                (if (projectile-project-p)
                                    (setq mixfmt-args (list "--dot-formatter" (concat (projectile-project-root) "/.formatter.exs")))
                                  (setq mixfmt-args nil))))
  )
```

Very receptive to feedback and optimizations! Also, I see now on the `mix-format.el` package's README that it's been rolled into `elixir-mode`. 😴

**Comment by Mayeu** [comment]
`mix-format.el` has been merged into [elixir-emacs](https://github.com/elixir-editors/emacs-elixir), thus you can simply add the following hook to your Spacemacs config:
```emacs
;; Create a buffer-local hook to run elixir-format on save, only when we enable elixir-mode.
(add-hook 'elixir-mode-hook
          (lambda () (add-hook 'before-save-hook 'elixir-format nil t)))
```
See [the README](https://github.com/elixir-editors/emacs-elixir#add-elixir-mode-hook-to-run-elixir-format-on-file-save).

With this, I believe we can close this ticket?

**Comment by wzin** [comment]
I can confirm that latest spacemacs with updated packages does the trick of automatic on-write formatting after adding abovementioned hook to user-config.
