### ISSUE TITLE
git status: "API call resulted in error; go offline?"

### ISSUE THREAD

**Issue by mathpunk** [syl20bnr/spacemacs#9288]
#### Description :octocat:
magit tells me I'm 'offline' and I'm not sure what that means or why it is happening.

#### Reproduction guide :beetle:
- Start Emacs
- Navigate to a repo directory
- Check git status, with `SPC g s`

*Observed behaviour:* :eyes: :broken_heart:

"API call resulted in error; go offline? (y or n)"

When I run `git config --global user.name`, for example, it is configured as I'm expecting. I'm inferring that github.user, then, is something different that I don't know how to set.

*Expected behaviour:* :heart: :smile:
Open the magit status window with no complaints.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. e09385d2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(own ivy better-defaults
     (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-space-key-behavior 'reject auto-completion-return-key-behavior 'reject auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.3)
     (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/usr/bin/zsh" shell-default-height 40 shell-default-position 'bottom)
     shell-scripts
     (org :variables org-enable-reveal-js-support t org-enable-org-journal-support t)
     yaml csv sql ranger html restclient react emacs-lisp javascript clojure
     (ruby :variables ruby-test-runner 'rspec)
     python syntax-checking git github fasd markdown deft latex themes-megapack typography emoji)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
debug-on-error enabled.
SPC g s
magithub: (34:00.657) checking if the API is available
magithub: (34:00.658) retrieving new value for api-available-p
magithub: (34:00.658) ghub--request("GET" "/rate_limit" nil nil nil)
magithub: (34:00.659) new value retrieved for api-available-p
magithub: (34:00.659) (ghub-auth-error "github.user is undefined")
```

**Comment by mathpunk** [comment]
Also note, I can't actually tell if I should care! For instance, I get told, I'm using cached data that was fetched just now.

**Comment by d12frosted** [comment]
I am experiencing the same behaviour. Haven't looked into it yet.

**Comment by nickanderson** [comment]
I also started seeing this recently. I updated my develop branch to 9a9d9a0feb28e1e42f2a8328f99ded8d0d83635b and the issue went away.

**Comment by d12frosted** [comment]
I am not sure what we are going to do with this issue, but in case someone hates that message - just exclude `magithub`. More info in [FAQ](http://spacemacs.org/doc/FAQ.html#disable-a-package-completely).

**Comment by braham-snyder** [comment]
https://github.com/vermiculus/magithub/issues/107

**Comment by d12frosted** [comment]
Thanks for the link. 

Interestingly, I have switched to using `ghub` instead of `gh` several days ago and so I have configured authentication for `ghub`, which automatically fixed this issue for me. But I didn't connect these two events (configuration and missing issue) 😸

**Comment by vermiculus** [comment]
Upstream here.

This should be fixed now.

**Comment by agzam** [comment]
@d12frosted Can someone enable the package back? Thanks!

**Comment by braham-snyder** [comment]
@agzam you might want to read the issue linked just above referencing this issue -- sounds like it's on hold for the time being

**Comment by agzam** [comment]
@braham-snyder all that I see that all upstream issues are closed, this supposed to be fixed, why not add it back in the layer?

**Comment by vermiculus** [comment]
@braham-snyder magithub is fairly stable now – the only instability will be when ghub#25 goes through (where I'll quickly be pushing a compatible magithub). Is there another reason it should be disabled?

Alternatively, is there a way spacemacs users can re-enable magithub themselves?

**Comment by braham-snyder** [comment]
@agzam I meant the open `magit` issue "referencing" this one, linked just above ("*ERROR*: Auth Error: "Token not found" while committing") -- which isn't technically upstream for this issue, but has relevant discussion re: `magithub` and its status within Spacemacs

@vermiculus I don't happen to know of any issues other than that one -- I was just going off of what @syl20bnr said in https://github.com/magit/magit/issues/3154:

> That's great news! I disabled the package for now, don't hesitate to warn us when you think the package is stable enough and we will activate it back.

I think his interpretation of your earlier comments in that same issue was that `magithub` would be relatively stable *after* magit/ghub#25.

I was just trying to relay that info, but I may have misread it.

**Comment by agzam** [comment]
Once again, the package is fixed, it works. The upstream issue was resolved. It is a one-liner to enable it back. We don't really need a PR for it, do we?
