### ISSUE TITLE
layer go: go major mode: parse `go test` line numbers

### ISSUE THREAD

**Issue by Julio-Guerra** [syl20bnr/spacemacs#9290]
The output of `go test` (called through the go major mode using `SPC-m-t-p`) is not parsed as a `file:line` hint. Thus preventing from using the usual "next error" shortcuts, or clicking on them.

For example:

<img width="733" alt="go test output" src="https://user-images.githubusercontent.com/172303/28661041-a7528dee-72b5-11e7-8bf9-05b90772b2ff.png">

**Comment by oleorhagen** [comment]
One could probably do something similar to go-guru, and have it be a compilation mode?
