### ISSUE TITLE
cscope layer README should mention that the c-c++layer needs to be enabled

### ISSUE THREAD

**Issue by MasonAsh** [syl20bnr/spacemacs#9294]
Title says it all. I was trying to use the cscope layer and was confused as to why the documented key bindings were not working, only to find out after exploring the source code that the c-c++ layer needs to be enabled first.

**Comment by d12frosted** [comment]
Thanks for letting us know. I've updated readme, so others won't struggle. Let me know if you think that there is something else we should improve regarding your issue.
