### ISSUE TITLE
Line Highlights

### ISSUE THREAD

**Issue by cinjon** [syl20bnr/spacemacs#9296]
How do I remove the [green] line highlight?

**Comment by d12frosted** [comment]
Are you talking about current line highlight?

Try adding `(global-hl-line-mode nil)` to `dotspacemacs/user-config` function.

**Comment by cinjon** [comment]
Thanks!

**Comment by bbarker** [comment]
This does not seem to work for me :-(

![image](https://user-images.githubusercontent.com/916366/54149348-476af900-440c-11e9-89f5-6a37e60bf575.png)

Yes, I restarted emacs after adding that line.

**Comment by hlmtre** [comment]
![image](https://user-images.githubusercontent.com/447257/56474626-22b56880-6431-11e9-9c0b-6ddc5574bb70.png)

Unfortunately, also not working for me either.

**Comment by duianto** [comment]
Either of the following commands, disable the hl-line for me:
```
(global-hl-line-mode -1)
(global-hl-line-mode 0)
```
And these enable it:
```
    (global-hl-line-mode)
    (global-hl-line-mode t)
    (global-hl-line-mode 1)
    (global-hl-line-mode nil)
```

It doesn't seem like `nil` should enable it, but this is what the docstring says:

The docstring says:
>Toggle line highlighting in all buffers (Global Hl-Line mode).
With a prefix argument ARG, enable Global Hl-Line mode if ARG is
positive, and disable it otherwise.  If called from Lisp, enable
the mode if ARG is omitted or nil.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3e37a359b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey helm auto-completion emacs-lisp emoji git github multiple-cursors org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by hlmtre** [comment]
I have `(global-hl-line-mode -1)` in my user-config(), which didn't turn it off. Ultimately SPC-f and stepping through the highlight options to disable it _did_ turn it off, but I can't find where in the configs it saved that that actually worked.

**Comment by duianto** [comment]
Could you post your system information, press `SPC h d s` (it will be copied to your clipboard).

```
    (global-hl-line-mode -1)
```
also works for me in the `user-config` section on the `master` branch.

You can also try:
```
    (spacemacs/toggle-highlight-current-line-globally-off)
```
but It seems to do the same thing by setting the mode to `-1`.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey helm auto-completion emacs-lisp emoji git github multiple-cursors org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by hlmtre** [comment]
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. `132ed8fa4`)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm emacs-lisp git themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by duianto** [comment]
Strange that it isn't working for you, we're on similar systems.

It still works for me when I installed the same layers as you:
```
python
helm
emacs-lisp
git
themes-megapack
```

And it's working from the command prompt `cmd.exe` and `powershell.exe`:
```
emacs -nw
```

I even tried it in Ubuntu 18.04.02 and the line highlight is hidden there as well.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3e37a359b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp emoji git multiple-cursors treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP
