### ISSUE TITLE
Need a way to disable paste micro-state

### ISSUE THREAD

**Issue by bazzargh** [syl20bnr/spacemacs#930]
My finger memory expects pasting again to paste the same thing, again. This has been driving me nuts since the behaviour changed, now I've read what it's up to I can see that I can work around it with p-up-down-p (or equivalent, any navigation should at least get me out of the state), but I'd really like to turn it off entirely.

**Comment by syl20bnr** [comment]
This is not yet documented, it is only documented in develop branch for now: https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.md#paste-text

Set `dotspacemacs-enable-paste-micro-state` to `nil` in your dotfile.

**Comment by bazzargh** [comment]
Thanks, also I should have read what was going on down in the echo area, it was telling me that I could have just pressed '.' to repeat the paste. Since you've given me both a workaround and a fix I'll close this - thanks again!
