### ISSUE TITLE
Change the default terminal when pressing SPC '

### ISSUE THREAD

**Issue by pspencil** [syl20bnr/spacemacs#9302]
When pressing `SPC '`, emacs will detect if there is any terminal window. If there is one, it will automatically inject a `cd xxx` to your current path. When multiple terminals are available, it seems to always use the newest created one. Is it possible to tie it to a particular one so that I can use different default terminals in different perspective?

I tried looking up the source of the invoke shell function but it seems to be defined in `init.el` (i guess in C)

**Comment by CeleritasCelery** [comment]
Several people have asked about this same functionality. There is not currently a way to do this. Someone would have write the functionality and submit a PR.

**Comment by Ps-Pencil** [comment]
I inspected the [shell-pop package code ](https://github.com/kyagi/shell-pop-el/blob/master/shell-pop.el) and there doesn't seem to be an easy way to integrate that with other packages. I have another suggestion is to let `SPC '` bind to a function that detects if the current layout contains a terminal/shell buffer. If it does, do not invoke the `shell-pop-default-shell` function but instead send a `cd $CWD` to the terminal.

**Comment by CeleritasCelery** [comment]
I like that idea. If you are comfortable in lisp you could submit a PR to the shell layer.

**Comment by Ps-Pencil** [comment]
I would really love to, even for my own sake, but I really do not have any experience in emacs lisp. Still trying to learn it.

**Comment by Ps-Pencil** [comment]
I explored the code of `shell-pop` once more and we could actually control the default buffer to open by changing the variable `shell-pop-last-shell-buffer-index`. However, I don't know how to inspect the list of buffers in the current layout and how to add a hook everytime we switch perspective.

**Comment by Ps-Pencil** [comment]
I found the function `persp-buffers` which returns a list of buffers. I am not sure how to operate on buffers though. Also, finding a shell buffer in all the buffers in a perspective might pose some performance overhead, which I am not experienced enough to evaluate.

However, I do find a workaround that works for me for now. If we add `(setq shell-pop-last-shell-buffer-index ,i)` to `layers/+spacemacs/spacemacs-layouts/funcs.el` inside the function that produces `spacemacs/persp-switch-to-X` (do a search on that and you will find the location) just below the `(interactive)` call, we could achieve a effect that an independent terminal is associated with each perspective. 

If you find that helpful, I can submit a PR. (but it is very hacky)

If you have a way to achieve that effect from within `.spacemacs` rather than modifying the layouts source code, please let me know. That way I can make sure I do not lose the change after upgrades.

**Comment by Ps-Pencil** [comment]
It doesn't work when you use `SPC l Tab` because it does not call that function. I am still looking for ways to get a layout's number from its name.

**Comment by CeleritasCelery** [comment]
@aaronjensen open #8185 with the same request. I looked into the code to try and find a solution but I have run into some of the same problems as you. This is bad solution, but it looks like you could iterate over `(nth pos (persp-names-current-frame-fast-ordered))` by changing `pos` and that will give you a mapping of numbers to names. So that will work great if you have the number and need the name but you would have to loop over it if you have the name but want the number.

**Comment by Ps-Pencil** [comment]
@CeleritasCelery Sure. I will try to implement correct behaviour for `SPC TAB`. Thanks.

**Comment by Ps-Pencil** [comment]
Got it. In the same file, `spacemacs/jump-to-last-layout` function, before the last `persp-switch xxx`, add the following:

    (loop for persp in (persp-names-current-frame-fast-ordered) and i from 1
          when (string= persp spacemacs--last-selected-layout)
          do (progn (setq shell-pop-last-shell-buffer-index i) (return)))

**Comment by CeleritasCelery** [comment]
nice! It sounds like it might be even better to make this an advice around `persp-switch` so it will cover all cases. My guess is that your current implementation still doesn't support `spacemacs/layout-goto-default`.

**Comment by Ps-Pencil** [comment]
True. I think it should be simple. Just move the code. I am investigating `eval-after-load` such that we could overwrite the `persp-switch` function such that we can put this into configuration file. However, I am not sure what to put for `FILE` in `eval-after-load FILE FORM`

**Comment by CeleritasCelery** [comment]
`(with-eval-after-load "persp-mode" FORM)`

**Comment by Ps-Pencil** [comment]
@CeleritasCelery Awesome!

**Comment by Ps-Pencil** [comment]
Put the following in `user-config` and you will have a shell per layout! 
(There are two types of `persp-switch`: `persp-frame-switch` and `persp-window-switch`. I am not sure what the latter does but redefining the former seems to do the trick.)
```
  (with-eval-after-load "persp-mode"
    '(defun* persp-frame-switch (name &optional (frame (selected-frame)))
      (interactive "i")
      (unless name
        (setq name (persp-read-persp "to switch(in frame)" nil nil nil nil t)))
      (unless (memq frame persp-inhibit-switch-for)
        (run-hook-with-args 'persp-before-switch-functions name frame)
        (let ((persp-inhibit-switch-for (cons frame persp-inhibit-switch-for)))
          (persp-activate (persp-add-new name) frame)))
      (loop for persp in (persp-names-current-frame-fast-ordered) and i from 1
            when (string= persp name)
            do (progn (setq shell-pop-last-shell-buffer-index i) (return)))
      name))

```

**Comment by CeleritasCelery** [comment]
@Ps-Pencil looks nice. Though I think it will be more reusable as an advice instead of overloading the function.

**Comment by Ps-Pencil** [comment]
That sounds good. However, after playing around with advice for a bit, I still cannot get it to work inside `with-eval-after-load`. But it works if I execute them separately after I loaded everything. Do you spot any mistakes? 

```
  (with-eval-after-load "persp-mode"
    '(progn
       (message "Advice loaded")
       (defun set-persp-specific-shell (arg)
         "Make each perspective use its own shell/term"
         (progn
           (message "Advice run")
           (loop for persp in (persp-names-current-frame-fast-ordered) and i from 1
                 when (string= persp arg)
                 do (progn (setq shell-pop-last-shell-buffer-index i) (return)))))
       (advice-add 'persp-switch :after #'set-persp-specific-shell)))
```

**Comment by vibrys** [comment]
if current buffer is remote one (tramp visit), then emacs opens shell on remote machine, which is very useful. Is this fix compatible with this remote shells?

**Comment by Ps-Pencil** [comment]
@vibrys This fix only changes the index variable. It does not affect the working of shells so in theory it shouldn't affect that behaviour. 

The fix has not been finalised btw. I am having problems with `with-eval-after-load` with advices.

**Comment by CeleritasCelery** [comment]
@Ps-Pencil put this in your `dotspacemacs/user-config` and see if that works (untested)

``` emacs-lisp
  (defun persp-frame-switch-pop-shell ()
    (cl-loop for persp in (persp-names-current-frame-fast-ordered) and i from 1
             when (string= persp spacemacs--last-selected-layout)
             do (progn (setq shell-pop-last-shell-buffer-index i)
                       (return))))

  (advice-add 'persp-frame-switch :after #'persp-frame-switch-pop-shell)
```

**Comment by Ps-Pencil** [comment]
@CeleritasCelery Without `with-eval-after-load`? My previous advice implementation also works if I remove `with-eval-after-load`. I am just worried if this would cause flaky behaviour.

**Comment by Ps-Pencil** [comment]
This is my current setting. Not sure if it will be unstable due to the lack of `with-eval-after-load`. 
```
(defun set-persp-specific-shell (arg)
    "Make each perspective use its own shell/term"
    (progn
      (loop for persp in (persp-names-current-frame-fast-ordered) and i from 1
            when (string= persp arg)
            do (progn (setq shell-pop-last-shell-buffer-index i) (return)))))
  (defun switch-to-X-advice (arg)
    (setq shell-pop-last-shell-buffer-index (+ 1 arg)))
  (advice-add 'persp-switch :after #'set-persp-specific-shell)
  (advice-add 'spacemacs/layout-switch-by-pos :after #'switch-to-X-advice)
```

**Comment by CeleritasCelery** [comment]
with spacemac,s you can guarantee that `persp` will be loaded by  the time `dotspacemacs/user-config` is called. So you don't need the `with-eval-after-load`

**Comment by Ps-Pencil** [comment]
@CeleritasCelery Good. Then I think my config works. I added the case when creating new layouts. It calls `persp-switch nil` and thus is not covered by the fix.

**Comment by CeleritasCelery** [comment]
awesome! if this seems like it is working well you should open a PR against the `spacemacs-layouts` layer. You should add a variable to the config that will enable this functionality when set. The default for this variable should be `nil` and you could call it something like `spacemacs-layouts-unique-shell-per-layout` etc

**Comment by Ps-Pencil** [comment]
@CeleritasCelery And if I open a PR, just modify the functions instead of using advice? 
Also, currently, if I delete a layout, the default shell of the later layouts will change by 1. Is there any workaround for this?

**Comment by CeleritasCelery** [comment]
hmm, that does make things complicated. The only thing I can think of is maintaining a mapping table that is updated when a layout is deleted and then pop the shell indicated in the mapping. 

As far as the PR goes, you need to use the advices and not functions because both `perspective` and `pop-shell` are packages and shouldn't be directly modified.

**Comment by Ps-Pencil** [comment]
@CeleritasCelery Where should I define the advice and add them?

**Comment by CeleritasCelery** [comment]
define all functions in [layers/+spacemacs/spacemacs-layouts/funcs.el](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bspacemacs/spacemacs-layouts/funcs.el) and all variables in [layers/+spacemacs/spacemacs-layouts/config.el](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bspacemacs/spacemacs-layouts/config.el). Make sure that this functionality is disabled by default but can be enabled by using a variable in config.el.

**Comment by Ps-Pencil** [comment]
@CeleritasCelery Sure. But where should the `advice-add` be called? `packages.el`?

**Comment by CeleritasCelery** [comment]
In the `spacemacs/init-persp-mode` in `packages.el` check for your variable and `(configuration-layer/package-usedp 'shell-pop)` if both are true you should add your advices.

**Comment by Ps-Pencil** [comment]
#9386 done.

**Comment by duianto** [comment]
The following PRs changes have been applied to the develop branch:
Local shell pop #13556
