### ISSUE TITLE
emacs-ipython-notebook fails to compile when adding ipython-notebook layer

### ISSUE THREAD

**Issue by non-Jedi** [syl20bnr/spacemacs#9303]
#### Description :octocat:

ein from the ipython-notebook layer fails to compile. See
https://github.com/millejoh/emacs-ipython-notebook/issues/218

#### Reproduction guide :beetle:

- Enable ipython-notebook layer and make sure ein is deleted from elpa/ directory
- Restart emacs

*Observed behaviour:* :eyes: :broken_heart:

ein fails to compile with the errors seen in the linked issue

*Expected behaviour:* :heart: :smile:

ein compiles normally

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(html javascript yaml latex vimscript shell python ipython-notebook nim nlinum ivy auto-completion emacs-lisp git markdown org spell-checking)
```

#### Backtrace :paw_prints:
```

Compiling file /home/adam/.emacs.d/elpa/ein-20170725.1457/debug-ein.el at Fri Jul 28 17:49:09 2017
Entering directory `/home/adam/.emacs.d/elpa/ein-20170725.1457/'
debug-ein.el:30:1:Error: Symbol's function definition is void: cl-defmethod

Compiling file /home/adam/.emacs.d/elpa/ein-20170725.1457/ein-ac.el at Fri Jul 28 17:49:10 2017
ein-ac.el:33:28:Error: Symbol's function definition is void: cl-defmethod

Compiling file /home/adam/.emacs.d/elpa/ein-20170725.1457/ein-cell-edit.el at Fri Jul 28 17:49:10 2017
ein-cell-edit.el:27:1:Error: Symbol's function definition is void: cl-defmethod

Compiling file /home/adam/.emacs.d/elpa/ein-20170725.1457/ein-cell-output.el at Fri Jul 28 17:49:10 2017
ein-cell-output.el:29:1:Error: Symbol's function definition is void: cl-defmethod

```

**Comment by non-Jedi** [comment]
So I realize that this is a bug upstream is already aware of, but are there workarounds we can use? Is there some way to use MELPA stable instead?

**Comment by d12frosted** [comment]
In that thread owner of `emacs-ipython-notebook` suggests trying latest stable release. That sounds like a possible 'workaround'. Another 'workaround' is to use latest stable Emacs release - 25.2. 

Note that since that package is broken for Emacs 24, it's possible that we will put constraint on it and disable it for Emacs 24 users.

**Comment by millejoh** [comment]
Recent commits to ein should have reintroduced compatibility with Emacs 24. I've checked using a local installation of emacs 24.3 and it looks to be okay, but it would be nice if someone else could confirm it also works for them.

**Comment by non-Jedi** [comment]
@millejoh ein now works with emacs 24.5.1 for me.
