### ISSUE TITLE
An error occurred while installing org-projectile (error: (error Package `emacs-25' is unavailable))

### ISSUE THREAD

**Issue by Pastafarianist** [syl20bnr/spacemacs#9304]
#### Description :octocat:
`org` layer fails to install.

#### Reproduction guide :beetle:
- Start Emacs
- Edit `.spacemacs` and uncomment `org` under `dotspacemacs-configuration-layers`
- Save & restart

*Observed behaviour:* :eyes: :broken_heart:
The following message appears on splash screen:

```
Found 1 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: org-projectile@org... [1/1]
Package emacs is unavailable. Is the package name misspelled?

An error occurred while installing org-projectile (error: (error Package `emacs-25' is unavailable))
```

*Expected behaviour:* :heart: :smile:
No errors.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml helm emacs-lisp git org)
```

Also, `C-c C-c` doesn't work in the issue editing mode (`C-c C-c is undefined`), contrary to what the first line suggests (`<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-c C-c` TO SUBMIT>>`), so I had to manually copy-paste the text in a browser.

**Comment by d12frosted** [comment]
Hey, it seems that `org-projectile` now doesn't support Emacs 24. As temporary workaround, add `org-projectile` to the list of excluded packages. More info in the [FAQ](http://spacemacs.org/doc/FAQ.html#disable-a-package-completely).

**Comment by d12frosted** [comment]
@IvanMalison could you please share you thoughts on supporting Emacs 24? 😸 

P. S. 💯 for explicitly stating dependency on Emacs 25 stuff.

**Comment by IvanMalison** [comment]
@d12frosted It wouldn't be impossible. I can't remember exactly why I decided that I didn't wan't to bother supporting emacs24 anymore. let me look in to it.

**Comment by IvanMalison** [comment]
@d12frosted @Pastafarianist I removed the requirement, but I'm pretty sure it was there for a reason, but I didn't want to deal with installing a different version of emacs to figure out why.

**Comment by d12frosted** [comment]
@IvanMalison thank you!

@Pastafarianist could you please try using the latest version of `org-projectile` on emacs 24 after new version get's to melpa?

**Comment by IvanMalison** [comment]
This was not actually fixed until just now with https://github.com/IvanMalison/org-projectile/commit/634d148033ea9de7f8dffc4dece69820541e8bcf
