### ISSUE TITLE
`C-c C-c` does not submit a bug report

### ISSUE THREAD

**Issue by dniku** [syl20bnr/spacemacs#9307]
#### Description :octocat:
`C-c C-c` does not submit a bug report.

#### Reproduction guide :beetle:
- Start Emacs
- Hit `SPC h I`
- See a template that says "`C-c C-c` TO SUBMIT"
- Enter something, press `C-c C-c`

*Observed behaviour:* :eyes: :broken_heart:
`C-c C-c is undefined` in the status bar.

*Expected behaviour:* :heart: :smile:
The issue should be submitted to Github.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml helm emacs-lisp git org)

**Comment by d12frosted** [comment]
Indeed, it doesn't work on `master`, but was fixed on `develop`. Though I can't find exact commit / issue right now.

**Comment by duianto** [comment]
Since it's a bit hard to find, here's the PR where the possible cause of this issue was found / solved, on the develop branch: Better reporting #9130
