### ISSUE TITLE
"Large file, open literally to avoid performance issues" message always display at startup

### ISSUE THREAD

**Issue by pcesar22** [syl20bnr/spacemacs#9314]
I've opened a ".mat" file (large matlab binary) in the emacs editor once in my life, and now it always prompts me to open literally upon start-up.

emacs version 25.1
spacemacs 0.200.9

I think it is some information stored in .cache that triggers this message, but it is really annoying to hunt that down.

**Comment by d12frosted** [comment]
It's not related to the cache. Checkout `dotspacemacs-large-file-size`, which is by default is set to 1 MB and is included in your `.spacemacs` file.

```
Size (in MB) above which spacemacs will prompt to open the large file
literally to avoid performance issues. Opening a file literally means that
no major mode or minor modes are active.
```

This is what makes Spacemacs to prompt you.

You could just increase the value of this variable, but that doesn't look like viable solution. Instead, take a look at `spacemacs-large-file-modes-list`. In case there a major mode for matlab binary, it't better to add that mode to `spacemacs-large-file-modes-list`, so it will never prompt you when opening that file.

**Comment by pcesar22** [comment]
Thanks for the info!
Just to clarify, this message does not only happen when I open the file.
It happens all the time at startup, even if the file has long been closed. I would like for it to prompt me only when I open the file, not every single time I open emacs.

**Comment by deuill** [comment]
Is it possible that the buffer is still open? If your `dotspacemacs-auto-resume-layouts` configuration value is set to `t`, Spacemacs will restore your layouts and buffers on startup.

I've found this annoying in the past, but resorted to killing the buffer in question until I needed it again. Maybe lazy-loading (*ala* Firefox tabs) is the answer?

**Comment by mohamedalsherif** [comment]
i found the file .emacs.d/.cache/.emacs.desktop and deleted the entry (desktop-create-buffer .. ) that contains the path of my large file and it solved the issue
