### ISSUE TITLE
ace-window binding

### ISSUE THREAD

**Issue by mfiano** [syl20bnr/spacemacs#9315]
The binding for `ace-window` in the `SPC w` prefix makes little sense, and only adds an extra key / hand strain (shift modifier) for such a common task. `ace-window` is bound to `W` instead of `w`. `other-window` is already called by `ace-window` when only 2 windows exist, so it makes little sense. `ace-window` should be bound to `SPC w w`, and in the case of 2 windows, it will behave like `other-window`, and 3+ will allow you to choose the window to jump to. I believe it is less common to use `other-window` to cycle around more than 2 windows, so the bindings for `ace-window` and `other-window` should be swapped.

`ace-window`: `SPC w w`
`other-window`: `SPC w W`

**Comment by d12frosted** [comment]
Sounds good to me. Though it may break workflow for some people. When you work with REPLs you usually have more than two windows. Though I doubt that suing `other-window` several times is more efficient than `ace-window`. Seriously.

P. S. I have bound it to ⌘\`, so it imitates window switching in macOS. I must say, it's fancy! :smile_cat:
