### ISSUE TITLE
Spacemacs starts python shell instead of IPython with SPC-m-s-i

### ISSUE THREAD

**Issue by hilman-dayo** [syl20bnr/spacemacs#9321]
Hello everyone.
I am a quite novice in these emacs things and I would be happy if someone can help me.

I am using [`pyenv`](https://github.com/pyenv/pyenv) and [`pyenv-virtualenv`](https://github.com/pyenv/pyenv-virtualenv) to handle my python versions. From inside spacemacs, I've activated one of my virtual environment using `SPC-m-V-a`. Fair enough, I have managed to activate the virtual environment. However, when I press `SPC-m-s-i`, spacemacs only open the normal Python terminal and not the IPython which is already installed in the virtual environment. How can I solve this?

I am using macOS Sierra 10.12.6, GNU Emacs 25.2.1 and Spacemacs 0.200.9.

**Comment by songpeng** [comment]
Do you add 
```
(when (executable-find "ipython")
(setq python-shell-interpreter "ipython"))
 ```
in your user config?

**Comment by hilman-dayo** [comment]
Did a quick repair but still can't call the IPython. 
Can `pyenv` and `pyenv-virtualenv` be the reasons this problem occurred (maybe it didn't play nice with Spacemacs)? Since I have an Ubuntu machine that just use `virtualenv` and `virtualenvwrapper` (no `pyenv`) and I could call the IPython just fine.

It could also be that I am setting my Spacemacs and `pyenv` in my Mac in a wrong way though. But man, I don't really have time to debug my setting right now...

**Comment by songpeng** [comment]
I use `virtualenv`,  not `pyenv` on my MacOS.  
Can you open ipython directly in your terminal when you set up your pyenv? It might be the path for ipython cannot be recognized by Emacs.

**Comment by hilman-dayo** [comment]
Yup, I can. If I open the terminal within Spacemacs with `SPC-'`, I can use the Ipython. But it is a terrible experience to operate the Ipython from there. 

I do believe this problem has something to do with the path. How can I try to debug/check this?

**Comment by songpeng** [comment]
Sorry, I am new for Emacs.
BTW, 
a. I use spacemacs `develop` version.
b. maybe update the packages in Emacs ? I don't know whether it's the old version bug.

**Comment by cpaulik** [comment]
What does `(spacemacs/pyenv-executable-find "ipython")` return after you activated the environment?

**Comment by songpeng** [comment]
@hilman-dayo 
It means that you install ipython before you construct the pyvenv, which may cause some libraries cannot be found by ipython although you install them with pyvenv-specific pip. I face this problem when I want to use tensorflow library. And fix it by reinstalling a specific ipython under the pyvenv.

**Comment by hilman-dayo** [comment]
@songpeng 
Hmm, I believe I've installed the ipython after construct the virtual environment.
What do you mean by "reinstalling specific ipython"?

**Comment by songpeng** [comment]
@hilman-dayo ,
I face this problem when I have installed ipython before entering a specific python env, which causes my ipython cannot found load some libraries normally. 
Like this link [ipython installed within virtualenv](https://github.com/ipython/ipython/issues/3018/).
But if it works great for you, I think you can ignore it.

**Comment by hilman-dayo** [comment]
@cpaulik 
No... The ipython wouldn't show up again. Hm... How can I start debugging this? I basically has zero knowledge in emacs.

**Comment by deoPlanGrid** [comment]
Any progress on this? I'm having no luck starting an ipython shell either.

**Comment by nizish** [comment]
I use poetry and faced the same problem. The fix is do `poetry add ipython` and `, v o t` to toggle the virtual environment one or two times. And now `, '` works!

**Comment by nizish** [comment]
That's `SPC m v o t` and `SPC m s i` to be clearer.
