### ISSUE TITLE
Question: How to simplify the powerline ?

### ISSUE THREAD

**Issue by azer** [syl20bnr/spacemacs#9323]
Although the powerline is amazing, I'd like to keep it as simple as possible. One thing I'd love is hiding everything except the filename, and making it simple, straight color without any fancy borders. I only find the filename useful in there. How would we configure spacemacs for this purpose ? 

This is how it looks currently; 
![](https://cldup.com/DcCqYGnDXr.png)

Unfortunately it doesn't look as pretty as it looks in OSX. The mode icons don't appear even though I got the fonts installed.

**Comment by CeleritasCelery** [comment]
you should ask this over at [TheBB/spaceline](https://github.com/TheBB/spaceline)

**Comment by d12frosted** [comment]
For mode icons you'll need [spaceline-all-the-icons](https://github.com/domtronn/spaceline-all-the-icons.el). For different sections checkout spaceline [documentation](https://github.com/TheBB/spaceline#turning-segments-on-and-off).
