### ISSUE TITLE
Remote Emacs and Font

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#9325]
connecting via `ssh -Y server` and running emacs does not set the font properly, also, when I set it in `dotspacemacs/user-config` with `set-frame-font`.

What works is running `set-frame-font` after loading.

I think the reason for this is that emacs tries to set the font before having created any frames and therefore the method does not exist or has no effect. In the `*Message*` buffer, I get no warning.

A workaround is something like:
```elisp
(defun dotspacemacs/user-config ()
  ...
  (run-at-time "5" nil (lambda () (set-frame-font "-bitstream-Bitstream Vera Sans Mono-normal-normal-normal-*-14-*-*-*-m-0-iso10646-1")))
  ...
  )
```

**Comment by d12frosted** [comment]
Instead of using `run-at-time` you could try using `spacemacs/defer-until-after-user-config`, e. g.

```emacs-lisp
(spacemacs/defer-until-after-user-config (lambda () (set-frame-font "-bitstream-Bitstream Vera Sans Mono-normal-normal-normal-*-14-*-*-*-m-0-iso10646-1")))
```

Regarding your issue - don't have anything to say except for 'dunno why' 😸 😿

**Comment by gdkrmr** [comment]
there is probably some hook for frame creation, where setting the font could go.

**Comment by gdkrmr** [comment]
There is an interesting comment [here](https://github.com/syl20bnr/spacemacs/blob/master/core/core-spacemacs.el#L114) that might have something to do with it. I can see the message when I use remote spacemacs.
