### ISSUE TITLE
support sage layer?

### ISSUE THREAD

**Issue by iromise** [syl20bnr/spacemacs#9326]
Possible to support math sage?

**Comment by bmag** [comment]
If Emacs can support it, then Spacemacs can support it.

**Comment by iromise** [comment]
Thanks a lot, and I am wondering will you spend time developing this layer?

**Comment by bmag** [comment]
Personally I'm not planning to write a layer for Sage. If someone writes a layer and submits a PR, I'd be happy to merge it.

**Comment by iromise** [comment]
Ok, thanks.
