### ISSUE TITLE
Support for org-trello

### ISSUE THREAD

**Issue by ageekymonk** [syl20bnr/spacemacs#9328]
Can Org-trello support be added in org layer? It could be a feature toggle as it will not be used by everyone who uses org mode.

**Comment by d12frosted** [comment]
Once we had it and [then it got removed](https://github.com/syl20bnr/spacemacs/commit/5544451946c48e66bb35b3b3f0f2bff2611b2a86).

**Comment by Miciah** [comment]
The referenced commit that removed org-trello (https://github.com/syl20bnr/spacemacs/commit/5544451946c48e66bb35b3b3f0f2bff2611b2a86) was made before the `:toggle` option for packages was added to the layers system.  Any reason not to restore org-trello with a `:toggle` qualifier?

**Comment by sdwolfz** [comment]
I have no problem with that, we already have stuff like `org-enable-hugo-support` or `org-enable-org-journal-support`. You can make a PR that adds it like those do, with a `org-enable-trello-support` variable.

**Comment by magthe** [comment]
I found `org-trello` today, which led me here. Would something like this work?

https://github.com/magthe/spacemacs/commit/8b77c2b34731e064953f644912838407905db709

**Comment by sdwolfz** [comment]
@magthe seems right, you might want to try deffering that package, or adding in some keybindings. Open up a PR and maybe someone else in the community will be able to suggest further improvements.

**Comment by CodeStar8** [comment]
Have you tried installing org-trello for emacs only? Since Spacemacs runs on top of emacs

**Comment by CodeStar8** [comment]
I realized that Spacemacs is deleting the emacs package. This other github ticket talks about it...

https://github.com/syl20bnr/spacemacs/issues/9269

**Comment by undergroundquizscene** [comment]
Should this issue be closed, as `org-trello` is already included in `develop` via magthe's PR above?
