### ISSUE TITLE
org-brain-open shortcut does not map to an available command

### ISSUE THREAD

**Issue by sonnius** [syl20bnr/spacemacs#9329]
#### Description :octocat:
org-brain-open is defined in org layer but it's not part of the org-brain package as installed

#### Reproduction guide :beetle:
- Start Emacs
- SPC a o b

*Observed behaviour:* :eyes: :broken_heart:
 The referenced command does not exist

*Expected behaviour:* :heart: :smile:
The command should exist

Please note that there's a fork of org-brain that includes this command: https://github.com/pidu/org-brain

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. d5ae3a6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(html restclient python lua ivy dash emacs-lisp markdown org orgwiki osx spell-checking syntax-checking)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by d12frosted** [comment]
Indeed it's not defined anymore. Release 0.4 is backwards incompatible, sooooo... take a look at #9332

**Comment by sonnius** [comment]
Boris, this looks good and should be committed.

Thanks!
Rob

**Comment by d12frosted** [comment]
@sonnius that commit is in develop now, feel free to use 😸
