### ISSUE TITLE
'f' no longer fetches in magit-status

### ISSUE THREAD

**Issue by gwydirsam** [syl20bnr/spacemacs#933]
As of 0f4cae5, when in a magit-status buffer, f no longer works.

Work around:

> 13:21 < syl20bnr> [edit] this is because I introduced a new evil state
>                   `evilified` which is by default yellow
> 13:22 < syl20bnr> you can `SPC : evil-emacs-state`

**Comment by syl20bnr** [comment]
This is fixed in evil-escape version 2.15. Will be available in MELPA in a few hours.

**Comment by ralesi** [comment]
Confirm that update fixes issue
