### ISSUE TITLE
How to bind C-g to evil-escape?

### ISSUE THREAD

**Issue by abcdw** [syl20bnr/spacemacs#9330]
I tried many variants and all have the same problem. For example `(define-key evil-insert-state-map (kbd "C-g") 'evil-escape)`

From normal mode `i` `C-g` and I'm in normal mode again, it's good, but if I type something in insert mode it is necessary to press `C-g` three times. `i` `somephrase` `C-g` `C-g` `C-g`.

**Comment by abcdw** [comment]
@hlissner did it in his config and it works like a charm. https://github.com/hlissner/.emacs.d

**Comment by hlissner** [comment]
To save anyone the trouble of digging through my config, the relevant lines are from [modules/feature/evil/config.el lines 230-241](https://github.com/hlissner/.emacs.d/blob/master/modules/feature/evil/config.el#L230):

Here are the relevant lines with custom macros/hook removed:

```emacs-lisp
(use-package evil-escape
  :commands evil-escape-mode
  :init
  (setq evil-escape-excluded-states '(normal visual multiedit emacs motion)
        evil-escape-excluded-major-modes '(neotree-mode)
        evil-escape-key-sequence "jk"
        evil-escape-delay 0.25)
  (add-hook 'after-init-hook #'evil-escape-mode)
  :config
  ;; no `evil-escape' in minibuffer
  (cl-pushnew #'minibufferp evil-escape-inhibit-functions :test #'eq)

  (define-key evil-insert-state-map  (kbd "C-g") #'evil-escape)
  (define-key evil-replace-state-map (kbd "C-g") #'evil-escape)
  (define-key evil-visual-state-map  (kbd "C-g") #'evil-escape)
  (define-key evil-operator-state-map (kbd "C-g") #'evil-escape))
```

**Comment by abcdw** [comment]
Thanks a lot, @hlissner. It seems working for me.
@d12frosted probably it will be good to add this to documentation?
