### ISSUE TITLE
"SPC r r is undefined" with Ivy installed

### ISSUE THREAD

**Issue by wolfv6** [syl20bnr/spacemacs#9331]
#### Description :octocat:
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#registers
says, "SPC r r 	show helm register" (helm-all-mark-rings)
I installed Spacemacs with Ivy, so I expect "SPC r r" would be bound to counsel-mark-ring.
But when I hit "SPC r r", minibuffer says "SPC r r is undefined".

Similar for "SPC r m", minibuffer says "SPC r m is undefined".

#### Reproduction guide :beetle:
- Start Emacs
install Spacemacs with Ivy
hit "SPC r r"

*Observed behaviour:* :eyes: :broken_heart:
minibuffer says "SPC r r is undefined".

*Expected behaviour:* :heart: :smile:
run counsel-mark-ring

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp org spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

**Comment by d12frosted** [comment]
Does `counsel-mark-ring` work with evil marks? I suspect helm registers to work differently compared to `counsel-mark-ring`.

P. S. `counsel-mark-ring` is bound to `SPC r m` and works on develop via 9e2da0037c7c634eefca4377185cf14a255e666e, but it's not on master yet.

**Comment by wolfv6** [comment]
Thanks d12frosted, good to know.
