### ISSUE TITLE
zone out should end when emacs comes to the front

### ISSUE THREAD

**Issue by JoshRagem** [syl20bnr/spacemacs#9333]
if I leave emacs and interact with some other program for long enough that emacs zones out, when I come back to emacs I am ready to act but I get tripped up because the first key press (`SPC`) kills the zone but is consumed by that action. I then mash a few keys and vim does whatever it thinks is right for that. Example:

1. return to emacs
2. `SPC`
3. `p p`

now my file is full of whatever garbage I last copied. I do it all by reflex so sometimes I have halfway into the project name I want before I can stop and fix what has happened.

I would like 'zone out' to stop when emacs becomes active.

_extra info:_
I use [stumpwm](https://stumpwm.github.io/) on ubuntu so I can't count on mouse movement or clicking to trigger anything.

**Comment by d12frosted** [comment]
I tried to use `zone` via `SPC T Z` and when I exit zone using `M-m` - nothing gets consumed. I'll try with vim editing style later.

Since you are using `vim` editing style - you could just hit `ESC` whenever you back to Emacs 😸 Just a workaround.
