### ISSUE TITLE
keyboard-layout does not initialize correctly twittering-mode

### ISSUE THREAD

**Issue by JulienDlq** [syl20bnr/spacemacs#9335]
#### Description :octocat:
I think there is an issue in packages.el from keyboard layout about twittering-mode.
When activating bepo layout, there is a warning on spacemacs startup about twittering-mode not initialized.
Looking at packages.el line 469 the function is kl/pre-init-twittering-mode instead of keyboard-layout/pre-init-twittering-mode.
Changing it and restart spacemacs resolve the issue.

Nota: this should happen also using dvorak.

#### Reproduction guide :beetle:
- Start Emacs
- Open .spacemacs and add (keyboard-layout :variables kl-layout 'bepo) in dotspacemacs-configuration-layers
- Restart Emacs

Nota: this should happen also using dvorak.

*Observed behaviour:* :eyes: :broken_heart:
A warning about twittering-mode not initialized.

*Expected behaviour:* :heart: :smile:
No warning.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(semantic helm imenu-list auto-completion emacs-lisp git
		  (version-control :variables)
		  yaml markdown csv syntax-checking evil-commentary shell-scripts c-c   gtags
		  (keyboard-layout :variables kl-layout 'bepo)
		  ooka-perl)
```
- System configuration features: XPM JPEG TIFF GIF PNG IMAGEMAGICK SOUND NOTIFY ACL GNUTLS FREETYPE XFT ZLIB GTK3 X11

#### Backtrace :paw_prints:
```
Warnings:
- package twittering-mode not initialized in layer keyboard-layout, you may
 consider removing this package from the package list or use the :toggle keyword
 instead of a `when' form.
```

**Comment by d12frosted** [comment]
Pull request is welcome 😸

**Comment by JulienDlq** [comment]
Actually a fix exists in develop branch: 635dde29c839cc9083ba2c16dd35f6e18c5236d3.

**Comment by d12frosted** [comment]
Oh, didn't notice that you are on master. Thanks for checking develop branch 😸

**Comment by bepolymathe** [comment]
I still have the problem in 2019. How to solve?
Thanks guys

**Comment by duianto** [comment]
Your best bet is probably to switch to the develop branch, there has been a lot of changes there.
https://github.com/syl20bnr/spacemacs/blob/develop/CHANGELOG.develop

It's stable. But it's always good to make a backup of your current working setup, before updating. Then you'll be able to restore it quickly if something doesn't work as you expect.

The develop branch `.spacemacs` has some new variables, so backup your current file and let Spacemacs create a new one. Then move over your current user settings manually.

**Comment by bepolymathe** [comment]
Honestly, I'm in the middle of learning spacemacs and I don't really want to move into the development branch right now. I can live with this permanent error message. It's just that I thought it had been integrated since 2017. 
Thank you for the answer.

**Comment by kotchwane** [comment]
I had this problem as a bépo user. Not only did I have the error message, but also the key remapping did not work as described.
Switching to the development branch was finally very easy (see https://www.reddit.com/r/spacemacs/comments/79xkfa/how_do_i_switch_to_the_dev_branch/dp5javt/) and solved the issue :-)
