### ISSUE TITLE
Haskell layer - Ghc-mod type signature insertion does not work

### ISSUE THREAD

**Issue by liarokapisv** [syl20bnr/spacemacs#9336]
#### Description :octocat:
Ghc-mod does not insert missing type signatures when pressing SPC m m t

#### Reproduction guide :beetle:
Have the haskell and syntax checking layers enabled.
- Start Emacs
- Open a haskell source file
- Write a function without providing a signature
- A warning should pop up
- Press SPC m m t

*Observed behaviour:* :eyes: :broken_heart:
"Nothing to do" apears in the powerline.

*Expected behaviour:* :heart: :smile:
The type signature specified in the warning overlay should be inserted.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml
 (haskell :variables haskell-process-type 'stack-ghci haskell-completion-backend 'ghc-mod haskell-enable-hindent-style "johan-tibell")
 c-c++ sml clojure helm auto-completion emacs-lisp git spell-checking
 (shell :variables shell-default-height 30 shell-default-shell 'eshell shell-default-position 'bottom)
 syntax-checking)
```

**Comment by liarokapisv** [comment]
It appears that ghc-mod attempts to retrieve information from the overlay and then parse it in order to retrieve the type information. Unfortunately it queries the overlay expecting it to have ghc-* properties. Instead the overlay contains flycheck-* properties and the queries fail.

**Comment by d12frosted** [comment]
Upstream issue: https://github.com/DanielG/ghc-mod/issues/628
