### ISSUE TITLE
How to add a package to existing layer?

### ISSUE THREAD

**Issue by vanjadevs** [syl20bnr/spacemacs#9338]
Normally I installed edts package to find out that it gets orphaned on restared. This is INTENDED BEHAVIOR, I understand... What I tried then is to add edts to the already existing erlang layer (to create a custom layer just for 1 package sounds like an overhead)... I added edts package to erlang layer packages.el, and restarded emacs but the package still doesn't appear to be installed... Moreover when I installed it manually it get orphaned anyway. Thanks for the help in advance!

**Comment by bmag** [comment]
How to install a package: http://spacemacs.org/doc/FAQ.html#install-a-package-not-provided-by-a-layer
Tips for writing a layer: http://spacemacs.org/doc/LAYERS.html
(these documents are also available from within Spacemacs, see `SPC h SPC`)

I recommend against modifying an existing layer, since it may cause problems when upgrading to a newer version of Spacemacs. If you still want to use a layer, you can write a (small) private layer.

**Comment by vanjadevs** [comment]
@bmag Thank you for the reply! I already checked these docs tho...

My motivation is following:
If I already have an erlang layer, it seems logical to put all erlang packages in that layer... Since you advise against modifying an existing layer then what should be the closest solution to this 'modifying an erlang layer' so I have all my packages grouped up nicely?

**Comment by bmag** [comment]
Closest solution: write a private layer that declares a dependency on erlang layer, see `layers.el` in `+distribution/spacemacs` for an example (spacemacs layer declares dependencies on various `spacemacs-*` layers). Is it important to you that all Erlang-related packages be configured in the same `packages.el` file?

**Comment by vanjadevs** [comment]
@bmag Was thinking so also... 

> Is it important to you that all Erlang-related packages be configured in the same packages.el file?

Well I'm not sure, basically I want to avoid clutter and have all settings related to erlang in one place, so I would answer yes to your question... anyway what are my options?

**Comment by bmag** [comment]
If that's the case then you can modify the existing erlang layer and just deal with upgrade problems when they happen, or make a copy of the erlang layer, change the layer's name (means renaming the directory name in renaming layer's functions and variables), and then you can do whatever you want with your own erlang layer. Good luck to you.

**Comment by vanjadevs** [comment]
@bmag Think I get it... Thank you very much for help!

**Comment by d12frosted** [comment]
Closing this issue as the question was answered. Though feel free to continue discussion if you have anything to say 😸

**Comment by zixuan75** [comment]
Found same problem on Emacs: [Emacs Stack Exchange problem](https://emacs.stackexchange.com/questions/57739/cannot-add-package-to-an-existing-layer/57742)
