### ISSUE TITLE
SPC f e R not working as described in the Quick start.

### ISSUE THREAD

**Issue by wolfv6** [syl20bnr/spacemacs#9342]
#### Description :octocat:
SPC f e R not working as described in the "Quick start".

From http://spacemacs.org/doc/QUICK_START.html
At anytime you can apply the changes made to the dotfile or layers without restarting Spacemacs by pressing SPC f e R.

From my experience changing org-todo-keywords in ~/.spacemacs
    (setq org-todo-keywords '((sequence "TODO" "IN_PROGRESS" "WAITING" "DONE")))
SPC f e R (dotspacemacs/sync-configuration-layers) does not update org-todo-keywords, but restarting emacs does.

Other users have similar experiences.

From https://stackoverflow.com/questions/31614316/how-can-i-reload-spacemacs-file-after-editing-without-restart-emacs > Mandar Vaze
But "SPC f e R" does not reflect the change. Quitting and starting spacemacs works.

From https://www.reddit.com/r/spacemacs/comments/6lk90o/best_practice_of_restarting_spacemacs/ > naught-me
SPC f e R
Though, I've never had luck with it. It always seems to screw something up, so I give up and just close Spacemacs and re-open it.

Maybe the "Quick start" description is wrong. The built in manual says something different.
From SPC h d k Describe key: SPC f e R:
- dotspacemacs/sync-configuration-layers
- Synchronize declared layers in dotfile with spacemacs.

#### Reproduction guide :beetle:
- Start Emacs
- change org-todo-keywords in ~/.spacemacs
    (setq org-todo-keywords '((sequence "TODO" "IN_PROGRESS" "WAITING" "DONE")))
- press SPC f e R (dotspacemacs/sync-configuration-layers)

*Observed behaviour:* :eyes: :broken_heart:
SPC f e R does not update org-todo-keywords, but restarting emacs does.

*Expected behaviour:* :heart: :smile:
SPC f e R does updates org-todo-keywords

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp org spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
none
```

**Comment by d12frosted** [comment]
Works for me. I've put it in `dotspacemacs/user-config` function and after `SPC f e R` completes I see new value of `org-todo-keywords`.

Several points to consider:

1. Are you sure there are no errors when you `SPC f e R`? Please check your `*Messages*` buffer (`SPC b m`).
2. Are you sure that `SPC f e R` is the best solution for evaluating single sexp? What about `, e e` (`eval-last-sexp`)?

**Comment by wolfv6** [comment]
@d12frosted No errors in *Messages* buffer.

This is what happened:
SPC f e R was working, but it was not apparent until the org file was reloaded with SPC b R (revert-buffer).

Thanks for checking.
