### ISSUE TITLE
emacs --deamon and emacsclient not evaluating user-config

### ISSUE THREAD

**Issue by feigaoxyz** [syl20bnr/spacemacs#9347]
#### Description :octocat:
`emacs --daemon` and `emacsclient` does not evaluate my user-config

#### Reproduction guide :beetle:
- Set key binding 

```elisp
(defun dotspacemacs/user-config() (
  (spacemacs/set-leader-keys-for-major-mode 'haskell-mode "f" 'hindent-reformat-buffer)
  ))
```

- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
- Start Emacs with `emacs foo.hs`, the key binding `, f` for `hindent-reformat-buffer` works
- Start Emacs with `emacs --daemon` then `emacsclient foo.hs`, the key binding `, f` for `hindent-reformat-buffer` not working (fall back to default binded function `hindent-reforamt-decl`)
- Start Emacs with `emacs --daemon` then `emacsclient foo.hs` then re-evaluate with `SPC f e R`, the key binding `, f` for `hindent-reformat-buffer` works again

*Expected behaviour:* :heart: :smile:
- emacs daemon and client honors my settings inside `user-config`

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((haskell :variables haskell-process-type 'stack-ghci haskell-enable-hindent-style "johan-tibell" haskell-stylish-on-save t)
 (python :variables python-enable-yapf-format-on-save t)
 helm auto-completion emacs-lisp markdown syntax-checking)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by CeleritasCelery** [comment]
connecting to an existing Emacs process shouldn't load your user-config, so that is expected. If you want to load it you can restart your Emacs server or just evaluate the code in your user-config by putting your cursor on the last paren and use `, e e`

**Comment by jmshelby** [comment]
I'm having the same problem ... been searching, can't find a solution.

**Comment by lromor** [comment]
Same issue here

**Comment by Ginner** [comment]
Same issue.  0.300.0@26.2

**Comment by duianto** [comment]
A possible solution might be to call the user configurations from an `after-make-frame-functions` hook:
```elisp
(add-hook 'after-make-frame-functions
           (lambda (frame)
             (select-frame frame)
             (spacemacs//set-monospaced-font "Hack" "文泉驿等宽微米黑" 13 16)))
```
As suggested in a comment https://github.com/syl20bnr/spacemacs/issues/4365#issuecomment-202812771 in this possibly duplicate issue:
emacs --deamon and emacsclient not evaluating user-config #9347

If I understood it correctly from a quick reading of some of the comments in that issue, at least any Gui configurations will be applied to the daemon which has no effect, therefore they won't be loaded when a new frame is created.
