### ISSUE TITLE
install Spacemacs-Purpose layer Not working?

### ISSUE THREAD

**Issue by MilooHub** [syl20bnr/spacemacs#9357]
I tried add `spacemacs-purpose` to the existing `dotspacemacs-configuration-layers` of my `~/.spacemacs`, restart Spacemacs, but nothing happens(No layer files downloading, No files installation prompt, nothing at all).

My Spacemacs is 0.200.8@25.1.1 

Please offer assistance what the problem is?

Thanks in advance.

**Comment by MilooHub** [comment]
BTW, I am on macOS 10.12.6

**Comment by bmag** [comment]
That layer doesn't exist in version 0.200, so adding it to the list doesn't do anything, except maybe some error or warning message. The layer only exists in develop branch for now, and is part of the default distribution. It will be part of the next major release.

**Comment by MilooHub** [comment]
Thank you for your response.

I am thinking about switching from `master` branch to `develop`, since word around the town keeps mentioning that **develop branch is actually as stable as develp and way more powerful than develpe. Is this true?**

Plus, **what is the best practice/instructions to do to switch from `master` to `develop` branch?** 

**Could one keep both branch so I would switch back from `develop` to `master` in case some major bugs happens in `develop` branch.**

Thanks in advance.

**Comment by bmag** [comment]
Dude, what's with all the bold text? Anyway:

Stability: develop branch is stable. The amount of daily changes is small, and usually nothing breaks.

How to switch from master to develop: It's just another branch in a Git repository. Checkout the develop branch, update your dotspacemacs according to the template from develop (see `core/templates/.spacemacs.template`). Check what other layer changes affect you and change your config accordingly. There's a changelog for develop branch too help you, but it isn't always up to date.

How to keep both master and develop branches: How about you tell me how you're planning to achieve that, and I'll tell if I think it will work? But I really think it will be easier to go to an older version of develop branch, if an update breaks develop branch. We do have a rollback feature, don't forget that.
