### ISSUE TITLE
C-u and C-d are scrolling too much

### ISSUE THREAD

**Issue by wolfv6** [syl20bnr/spacemacs#9366]
#### Description :octocat:
C-u and C-d are scrolling too much.
Was also tested on a clean Emacs environment with org-mode installed; results are posted on https://github.com/emacs-evil/evil/issues/890#issuecomment-319572765

#### Reproduction guide :beetle:
- Start Evil Spacemacs with org-mode
- open [example org file with many headings](https://drive.google.com/open?id=0B6rxjFGf59mbdU1FNzB5STNlMWs)
- fold all the headings
- adjust window height to 10 lines
- scroll using C-u and C-d

*Observed behaviour:* :eyes: :broken_heart:
- scroll 3/4 to 1 screen up & down

*Expected behaviour:* :heart: :smile:
- scroll half screen up & down

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp org spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
none
```

**Comment by wolfv6** [comment]
This may have something to do with universal argument C-u.

**Comment by CeleritasCelery** [comment]
what is your value of `evil-want-C-u-scroll`?

**Comment by wolfv6** [comment]
evil-want-C-u-scroll is a variable defined in ‘evil-vars.el’.
Its value is t
Original value was nil

**Comment by Somelauw** [comment]
I can't reproduce on master on the file given. Do you have evil-scroll-count set to a value different from 0?

**Comment by wolfv6** [comment]
evil-scroll-count value is 0
dotspacemacs-smooth-scrolling value is t
scroll-margin value is 0
