### ISSUE TITLE
[REGRESSION] Recent project list and `SPC p l` no longer work immediately after starting

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#9367]
#### Description :octocat:
After 6063466231ce5e209aacd2de612e53390a25c442, the recent project list no
longer shows and `SPC p l` no longer lists projects after startup. If you
manually switch to a persp then `SPC p l` will work

#### Reproduction guide :beetle:
- Ensure you have at least one recent projectile project
- (Re)start Emacs
- `SPC p l`

*Observed behaviour:* :eyes: :broken_heart:
Empty list of projects

*Expected behaviour:* :heart: :smile:
List of projects shows

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. a0cdccac)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(swift php nginx better-defaults spacemacs-layouts ivy
       (markdown :variables markdown-live-preview-engine 'vmd)
       (syntax-checking :variables syntax-checking-enable-tooltips t)
       (auto-completion :variables auto-completion-enable-sort-by-usage nil auto-completion-enable-snippets-in-popup nil)
       git dash pdf-tools html clojure
       (org :variables org-enable-github-support t org-enable-reveal-js-support t org-want-todo-bindings t)
       colors
       (osx :variables osx-command-as 'super)
       github ruby
       (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
       (spell-checking :variables spell-checking-enable-by-default nil)
       ranger version-control rcirc tmux yaml docker elm restclient lua chrome evil-little-word aj-elixir aj-emacs-lisp aj-javascript aj-typescript auto-correct contextual-menubar fix-git-autorevert flow frame-geometry match-indent shift-number)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by duianto** [comment]
Confirmed

The projects list appears in the `*spacemacs*` buffer and in the HELM Projectile buffer `SPC p p`, if a file in any project is opened.

This issue in the projectile repository seems to be related:
[strange behavior when I put `projectile-bookmarks.eld` in a different dir. #989](https://github.com/bbatsov/projectile/issues/989)

It mentions the `projectile-known-projects-file` variable. That made me look at the values of three similarly named variables before and after opening a project file.

Before:
1. `projectile-known-projects` is `nil`
2. `projectile-known-projects-file` is
"c:/Users/Username/AppData/Roaming/.emacs.d/.cache/projectile-bookmarks.eld"
Original value was 
"c:/Users/Username/AppData/Roaming/.emacs.d/projectile-bookmarks.eld"
3. `projectile-known-projects-on-file`  is `nil`

After:
1. `projectile-known-projects` now lists the project paths that are listed in `projectile-bookmarks.eld`
2. `projectile-known-projects-file` has not changed it still lists the path to the `projectile-bookmarks.eld` file.
3. `projectile-known-projects-on-file` now also lists the project paths that are listed in `projectile-bookmarks.eld`

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. a0cdccac)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip 'manual)
 colors emacs-lisp git haskell helm markdown org spell-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by magthe** [comment]
The fix by @aaronjensen works like a charm :)
