### ISSUE TITLE
org-projectile is not working correctly

### ISSUE THREAD

**Issue by RomanKapitonov** [syl20bnr/spacemacs#9368]
#### Description
Org-projectile fails to open project specific todo list due to missing functions.

#### Reproduction guide
- Start Emacs
- Open a project (SPC-p-p)
- Try to open TODO list for specific project with SPC-a-o-p

*Observed behaviour:*
An error is printed to *Messages* buffer saying the following:
```
if: Symbol’s function definition is void: org-projectile:capture-for-current-project
```
Org mode is not enabled

*Expected behaviour:*
A project specific TODO list is opened and org mode is enabled.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((haskell :variables haskell-process-type 'stack-ghci haskell-completion-backend 'company-ghci)
 yaml helm sql osx org javascript
 (version-control :variables version-control-diff-side 'left)
 git github
 (shell :variables shell-default-shell 'eshell)
 html
 (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rvm ruby-test-runner 'rspec)
 emacs-lisp markdown auto-completion
 (spell-checking :variables spell-checking-enable-by-default nil)
 rkapitonov)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace
```
if: Symbol’s function definition is void: org-projectile:capture-for-current-project
```

**Comment by CeleritasCelery** [comment]
it's working for me. Can you confirm that you have the `org-projectile` package installed and loaded?

**Comment by Awesomecase** [comment]
I'm having the same problem. Org-projectile and org-projectile-helm are installed.

**Comment by Awesomecase** [comment]
There was recently a large refactoring of org-projectile where org-projectile-per-repo was removed. When attempting org-projectile goto-todos it appears to call org-projectile-per-repo, and throws the error.

**Comment by d12frosted** [comment]
It was [fixed](https://github.com/syl20bnr/spacemacs/pull/9312) in `develop`.

**Comment by aaronjensen** [comment]
@d12frosted fyi, the fix caused a regression. https://github.com/syl20bnr/spacemacs/pull/9380 fixes that.

**Comment by hliebert** [comment]
I am getting the message `Wrong number of arguments: (1 . 1), 2` after `SPC p o` and `Invalid function: org-babel-header-args-safe-fn` after `SPC a o p`. After deleting the `elpa/org-plus-contrib` folder (as suggested in some older issue as a fix for the latter message) and restarting spacemacs, the messsage following `SPC a o p` changes to `Wrong type argument: stringp, nil`. I am using the `develop` branch.

The following layers are enabled:

``dotspacemacs-configuration-layers '(helm auto-completion better-defaults emacs-lisp git markdown (org :variables org-projectile-file "todo.org") shell spell-checking syntax-checking version-control ess (latex :variables latex-enable-auto-fill t) bibtex python shell-scripts html pdf-tools pandoc vimscript evil-snipe vim-powerline)``

**Comment by aaronjensen** [comment]
@hliebert could you please open a new issue following the issue template and include a stack trace

**Comment by O-Zone-Guy** [comment]
Since it is fixed in `devel`, any ETA on when it will reach stable? Because I am still facing the same issue. Unless there is a fix I am not aware of.
