### ISSUE TITLE
Symbol's function definition is void: org-projectile-per-project

### ISSUE THREAD

**Issue by lsytj0413** [syl20bnr/spacemacs#9374]
#### Description :octocat:
Error (use-package): org-projectile :config: Symbol's function definition is void: org-projectile-per-project

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
in the *Warnings* buffer shows:
Error (use-package): org-projectile :config: Symbol's function definition is void: org-projectile-per-project

*Expected behaviour:* :heart: :smile:

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. a0cdcca)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-sort-by-usage t)
 (better-defaults :variables better-defaults-move-to-end-of-code-first t)
 emacs-lisp git markdown org
 (shell :variables shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 asm
 (python :variables python-sort-imports-on-save t)
 javascript github semantic
 (go :variables go-tab-width 4 go-use-gometalinter t)
 ranger gtags ibuffer sql
 (colors :variables colors-enable-nyan-cat-progress-bar t colors-enable-rainbow-identifiers t)
 (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
 graphviz plantuml docker
 (syntax-checking :variables syntax-checking-enable-by-default t)
 liter ycmd)
```

#### Backtrace :paw_prints:
```
```

**Comment by dre-hh** [comment]
had same issue, but newest spacemacs pull from develop and package update solved the issue

**Comment by lsytj0413** [comment]
@dre-hh 
I have pull from develop branch since the commit #98ff30, and the problem is still exsit.

**Comment by dre-hh** [comment]
@lsytj0413 but what about updating emacs packages?

**Comment by yatesco** [comment]
It seems this `org-projectile` has undergone some significant internal redesign with some breaking changes. The front page (https://github.com/IvanMalison/org-projectile) gives more info, as does this issue: https://github.com/IvanMalison/org-projectile/issues/31

**Comment by incandescentman** [comment]
Same issue here. Switched to develop and it seems to be fixed for now.

    org-projectile:per-repo)
     (org-projectile:per-repo)
     (if (file-name-absolute-p org-projectile-file) (progn (setq...

**Comment by lsytj0413** [comment]
@dre-hh @incandescentman 
I use the develop branch and update all packages, but the issue is still exsit.
BUT when i switch to MASTER branch then the issue has gone.

**Comment by d12frosted** [comment]
`org-projectile-per-project` is defined in latest `org-projectile`.

**Comment by lsytj0413** [comment]
I update org-projectile to:
> org-projectile-20170803.634

and when i start spacemacs, there is a warning:
> Error (use-package): org-projectile :init: Symbol's value as variable is void: occ-get-categories

**Comment by bnicenboim** [comment]
Hi, I've just installed spacemacs (never used emacs or vim before, just sublime). Is there a workaround? I've actually installed spacemacs to use org-mode.

**Comment by lsytj0413** [comment]
@bnicenboim 
the newest version has solve this problem, you can update org-projectile package to the newest version.
Other way, you can add org-projectile to the **dotspacemacs-exclude-packages** list.

**Comment by Voleking** [comment]
Same issue here. I use the develop branch and update all packages, but the issue is still exsit.

**Comment by FrostedPenguin** [comment]
@lsytj0413 
I've installed the newest version but it still has same problem. I'm using master branch of spacemacs.

**Comment by lsytj0413** [comment]
@FrostedPenguin 
I'm using the **develop** branch

**Comment by channingwalton** [comment]
Hi, any further updates on this issue?

**Comment by lsytj0413** [comment]
@channingwalton 
No updates.

**Comment by peterhoeg** [comment]
Isn't it a bit premature to close the issue as it persists?

**Comment by yatesco** [comment]
Any idea when this will make it to the `master` branch?

**Comment by yatesco** [comment]
Thanks @lsytj0413 - I realise I could exclude it :-), but I was hoping there would be a fix. The more I read about `org` in `spacemacs` the more I appreciate the complexities involved otherwise I guess a simple `cherry-pick` would be possible.

In this case a `git checkout develop` is the answer I think.

**Comment by jonathanunderwood** [comment]
Still seeing this today - I am confused as to why the issue was closed without a solution?

**Comment by chriskaukis** [comment]
Experiencing this same error. Fresh install from master to confirm.

**Comment by prajnak** [comment]
also confirming the same error on a fresh install from master

**Comment by bricewge** [comment]
As said before, this issue is fixed in `develop`. If you want to stay on `0.200.9` you can cherry-pick 6063466231; it fix the issue.

**Comment by jonathanunderwood** [comment]
Why not make a fixed release from master, rather than leaving this broken?

**Comment by Kingpatzer** [comment]
I'm a brand new user to spacemacs and I'd like to understand how to fix this issue. Note: I don't want to run the development branch because I don't want other things breaking and I don't know what "cherry picking" that bricwge is mentioning means -- but it looks like he is suggesting hand coding a bunch of changes to files -- which for someone who's using Emacs and org mode for doing papers and running a few python data scripts is really asking a lot. 

How does a normal, everyday non-hacker fix this problem on the main release? 

I've deleted the package from ~/.emacs.d/elpa  and let spacemacs re-install, but that doesn't seem to do it.

**Comment by peterhoeg** [comment]
@Kingpatzer, you can add ```org-projectile``` to ```dotspacemacs-excluded-packages``` on your ```$HOME/.spacemacs/init.el``` file as mentioned in https://github.com/syl20bnr/spacemacs/issues/9374#issuecomment-325238803.

**Comment by cypa** [comment]
issue persists

**Comment by jonathanunderwood** [comment]
Still broken on the release (master) branch today. Again: why not backport the fix to master so it's released to end users?

**Comment by 00krishna** [comment]
I ran into the same exact issue, with this error showing up on startup. I am on the MASTER branch and here is what worked for me. 

0. Close emacs. I use version 25.3
1. I went into the ~/.emacs.d/elpa directory
2. Searched for org-projectile
3. Deleted the org-projectile-xxx folder
4. Then restart emacs and it will download org-projectile again.

So this helped fix my issue. I had to try this a couple of times before it finally worked. 
Hope this helps.

**Comment by stevexyc** [comment]
To fix this issue, I went into 
1. cd ~/.emacs.d/elpa/org-projectile-XXXX
2. git fetch
3. restart emacs
Should solve the problem

**Comment by jgubmll** [comment]
Fresh install of spacemacs today, and hit this problem. What's blocking a fix for this being pushed to master?

**Comment by macbem** [comment]
Issue persists

**Comment by rebcabin** [comment]
find ~/.emacs.d -name "*.elc" -delete

restart emacs

**Comment by kylegentle** [comment]
Issue still present on a fresh install.

**Comment by nocksock** [comment]
I still have this exact same issue. Has it been solved?

**Comment by sfalcon** [comment]
Just had this same issue today as well. Using @stevexyc 's git fetch suggestion worked for me

**Comment by SwenChan** [comment]
Same issue, and thx to @stevexyc 's suggestion, it work for me, too.
But curiously, why?

**Comment by kelanwu** [comment]
This issue still persists in master(0.200.13), but has fixed in develop branch.
I'd like to stay in master branch, and I solved this by @bricewge 's suggestion.

**Comment by nocksock** [comment]
Tried @bricewge's suggestion and it worked for me too. In a nutshell: `git cherry-pick 6063466231ce5e209aacd2de612e53390a25c442`

**Comment by scadu** [comment]
@syl20bnr could we reopen this issue? I hope it wouldn't be a problem to merge this, especially when a part of core functionality is broken in a master branch.

**Comment by frankjonen** [comment]
Hmm, not quite. Going into `~/.emacs.d` and executing `git cherry-pick 6063466231ce5e209aacd2de612e53390a25c442` yields:

`error: could not apply 60634662... Make `org-projectile` integration compatible with its new version
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'`

The only result I got was that the start screen stopped listing my projects and I have to reinstall now.

**Comment by ginhton** [comment]
I solved this problem by using following solutions (in evil mode):

1. `SPC h SPC`, input "org" , and then select layer -> org. press `Enter`.
2. `SPC f j`, select "package.el" and press `Enter` to open that file.
3. `/org-projectile:per-repo`, find that line and `g c c` or just comment this line.
4. restart spacemacs.

[original link - Chinese](https://emacs-china.org/t/topic/4353/6)

**Comment by rlcintra** [comment]
Please reopen this issue since it still affects the master branch (release 0.200.13.x).

**Comment by jbhannah** [comment]
There are multiple function calls in Spacemacs' org integration that have been renamed in org-projectile, e.g. `org-projectile:per-repo` is now `org-projectile-per-project`, in both the MELPA stable and MELPA latest releases. I'm planning on going through and fixing these references and opening a PR.

**Comment by MrMic** [comment]
Same issue today, with a new install of spacemacs.

**Comment by elatomo** [comment]
I also faced this issue today after updating all packages.

`find ~/.emacs.d/elpa -name "*elc" -delete` and restarting fixed it.

**Comment by gavinrogers** [comment]
```Error (use-package): org-projectile/:config: Symbol’s function definition is void: org-projectile:per-repo```

Still happening on master. I switched to dev yesterday which didn't fix it, but following the directions given by @stevexyc  [above](https://github.com/syl20bnr/spacemacs/issues/9374#issuecomment-352092838) seemed to work but today I'm seeing the error again.

**Comment by AGollapalli** [comment]
'''    (require 'org-projectile)
    (setq org-agenda-files (append org-agenda-files (org-projectile-todo-files)))
'''
in my config seems to fix it on develop. The symbols in the org layer are outdated on master.

**Comment by Ryuk03** [comment]
I download the last master, when emacs start, get a new error as below:
Error (use-package): projectile/:config: Symbol’s function definition is void: projectile-global-mode

**Comment by sdwolfz** [comment]
@Ryuk03 Your issue is fixed on develop. You can either switch to that branch or enable spacepla in your `.spacemacs` so that you get an older/stable version of projectile.

**Comment by colonelrascals** [comment]
This is still affects the master branch correct?

**Comment by sdwolfz** [comment]
@colonelrascals yes, it's still present here: https://github.com/syl20bnr/spacemacs/blob/master/layers/+distributions/spacemacs-base/packages.el#L364 and will be fixed once we release the next version. But unfortunately I have to ETA for that, so your best bet is to enable spacepla (or switch to develop).

**Comment by colonelrascals** [comment]
Switch to develop...thanks

**Comment by xircon** [comment]
https://github.com/bbatsov/projectile/issues/1254
```
ag projectile-global-mode ~/.ihsec                     
/home/steve/.ihsec/spacemacs/layers/+distributions/spacemacs-base/packages.el
364:      (projectile-global-mode)
```
Edit line 364 to projectile-global

**Comment by Vanarill** [comment]
@stevexyc thanks a lot, your suggestion fixed it for me

**Comment by fmjrey** [comment]
To those wondering what `spacepla` is: it's a typo, search for `spacelpa` instead.
It's a new feature in develop branch that allows the freezing of elpa dependencies to version known to work.
Definitely something needed as demonstrated by this very frustrating issue. 
See this [reddit](https://www.reddit.com/r/spacemacs/comments/7yvbqz/is_it_worth_to_use_develop_branch_instead_of/dujw8ca) thread for instructions.

**Comment by TyOverby** [comment]
This still effects master

**Comment by brorbw** [comment]
I can verify that this is still an issue

**Comment by laurierloi** [comment]
Just had the same issue today. Using @stevexyc git fetch fixed the problem

**Comment by vegai** [comment]
Same issue in a fresh spacemacs (0.200.13@26.1). @stevexyc's git fetch does not fix the problem, and neither does deleting the org-projectile elpa directory.

**Comment by vegai** [comment]
None of the suggested fixes worked for me, so I went to develop branch & spacelpa. That did.

**Comment by vonpupp** [comment]
I confirm that moving to the develop branch seems to work fine. As many sugested, I also think the master branch need more frequent merges. Congratulations on the project, it is an awesome tool.

**Comment by Benjmhart** [comment]
any chance of this fix getting moved to master any time soon?

**Comment by sdwolfz** [comment]
We're working exclusively on the release, see: https://github.com/syl20bnr/spacemacs/issues/11741. Please feel free to lend a hand if you want to have this faster.

**Comment by maverickdas** [comment]
Still facing this issue in master branch. Deleting *.elc from ~/.emacs.d/elpa/org-projectile-20190130.1439 solved it for me.

**Comment by gmoneymagna** [comment]
> I also faced this issue today after updating all packages.
> 
> `find ~/.emacs.d/elpa -name "*elc" -delete` and restarting fixed it.

Omg thank you so much this solved my capture refile problem in org mode. I had tried many similar options, then broke my install and reinstalled and still didn't work. I did this and it works now. Thanks!

**Comment by gcantieni** [comment]
Out of curiosity, what does deleting the `elc` files do?

**Comment by laurierloi** [comment]
If I remember correctly the *elc contain the byte compiled emac-lisp code.
I think this bug is caused at compile time, so they just say trash the
compiled items and emacs will rebuild them for you

**Comment by jkanche** [comment]
> > I also faced this issue today after updating all packages.
> > `find ~/.emacs.d/elpa -name "*elc" -delete` and restarting fixed it.
> 
> Omg thank you so much this solved my capture refile problem in org mode. I had tried many similar options, then broke my install and reinstalled and still didn't work. I did this and it works now. Thanks!

This did not work for me, using the `develop` branch did

**Comment by vegai** [comment]
@syl20bnr is "use the develop branch" a valid work-around, though?

**Comment by hyiltiz** [comment]
@AGollapalli 's workaround above that replaces the require line in the config still works for me.

**Comment by hyiltiz** [comment]
Can't believe I had to do it once again just after 2 weeks (or every two weeks for the last 3 years?)

**Comment by mjburling** [comment]
@hyiltiz I'm experiencing this issue as of a fresh install this morning. I've never been sure of the utility on commenting on closed issues like this one. Shouldn't we just open another?

**Comment by hyiltiz** [comment]
@mjburling Can't you solve your issue using one of the solutions provided in this thread?

**Comment by lazaruslarue** [comment]
@vegai the work-around is to delete the `.elc` files in the org-projectile folder

**Comment by dzintars** [comment]
Same issue there. I just installed Spacemacs first time in my life, went to configuration and enabled `auto-completion`, `git`, `markdown` and `org`. Saved. Closed emacs. Opened emacs. Plugin installation was started. This error appeared.

Fedora 31

**Comment by syl20bnr** [comment]
Use the develop branch. We are getting close to a release but I have still several things to finish first.

**Comment by naldoco** [comment]
Where can I get the develop branch?
I tried this:
git clone https://github.com/emacs-mirror/emacs.git

**Comment by MrMic** [comment]
> Where can I get the develop branch?
> I tried this:
> git clone https://github.com/emacs-mirror/emacs.git

You have to go to:
.emacs.d directory 
then:
git checkout develop
and then:
git pull

Have fun :)

**Comment by AnikaSU** [comment]
version Release 0.200.13.x, still seeing the issue

**Comment by duianto** [comment]
The `develop` branch is the recommended branch until the next version is released (I have no insight into when that is).

#### To try the `develop` branch:
Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

**Comment by aahutsal** [comment]
as stated on [org-projectile homepage](https://github.com/IvanMalison/org-projectile) I've added this to `.spacemacs`
```
(use-package org-projectile
  :bind (("C-c n p" . org-projectile-project-todo-completing-read)
         ("C-c c" . org-capture))
  :config
  (progn
    (setq org-projectile-projects-file
          "/your/path/to/an/org/file/for/storing/projects.org")
    (setq org-agenda-files (append org-agenda-files (org-projectile-todo-files)))
    (push (org-projectile-project-todo-entry) org-capture-templates))
  :ensure t)
```

and works
