### ISSUE TITLE
evil-insert-line-above sometimes adds lines *below* the cursor

### ISSUE THREAD

**Issue by terrycloth** [syl20bnr/spacemacs#9377]
#### Description :octocat:
Evil's insert-line-above command seems to do the same as insert-line-below when the line is empty, or when the cursor is at the first column.

I thought of reporting this to the Evil repository, but the actual command is `spacemacs/evil-insert-line-above`, so I'm guessing this is a special Spacemacs feature. Correct me if I'm wrong.

Possibly related to issue #8204?

#### Reproduction guide :beetle:
- Start Emacs with Spacemacs configured for Evil mode.
- Open a file and navigate to a line with text.
- Execute the `spacemacs/evil-insert-line-above` command (<kbd>SPC i k</kbd>).

The issue happens for me both in an X window, and in gnome-terminal and terminology (terminal by Enlightenment project).

*Observed behaviour:* :eyes: :broken_heart:
When the cursor is in the middle of a line that has text, the cursor stays in its position in the text and the current line shifts downward, relatively, as blank lines appear above the current line. This is what we want, right?

But when the cursor is in a blank line, it seems to stay in place, but blank lines appear *beneath* the current line.

And when the cursor is in a line containing text *and positioned at the first column*, the cursor *moves into* a new blank line above its previous position, and then repeats of the command acts like on a blank line, where blank lines appear *below* the cursor.

*Expected behaviour:* :heart: :smile:
The insert-line-above command should always insert lines *above* the cursor, regardless of whether the current line has any text content.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript shell-scripts markdown helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

**Comment by CeleritasCelery** [comment]
I can confirm that I am seeing the same behavior.

 What makes `spacemacs/evil-insert-line-above`  different then`evil-unimpaired/insert-space-above` (which is bound to `[ SPC`) aside from the fact that the later works as expected?

**Comment by d12frosted** [comment]
I summon @TheBB 😸
