### ISSUE TITLE
Vi indent "<<" and ">>" commands are not working for org-mode files

### ISSUE THREAD

**Issue by wolfv6** [syl20bnr/spacemacs#9385]
#### Description :octocat:
Vi indent "<<" and ">>" commands are not working for org-mode files (Evil Spacemacs).
If that is by design, what is the reason?

In visual mode, < (shift left) and > (shift right) work as in vim.

#### Reproduction guide :beetle:
- Start Emacs
- Open an org file
- move point to body of text under a header
- from normal mode, type ">>"

*Observed behaviour:* :eyes: :broken_heart:
nothing happens

*Expected behaviour:* :heart: :smile:
line indents

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy evil-snipe emacs-lisp org spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

**Comment by Somelauw** [comment]
This should be fixed in develop, which uses evil-org from melpa.

**Comment by duianto** [comment]
`>>` and `<<` does work on the develop branch where:
`>` calls `evil-org-promote-or-dedent` and `<` calls `evil-org-demote-or-indent`, whether there's a selection or not.

They don't work on the contents under a heading on the master branch where:
`>` calls `org-metaright` and `<` calls `org-metaleft`, they seem to target a heading, list item or table, according to the first line of the `org-metaright` doc string:
>  "Demote heading, list item at point or move table column right.

When there's a selection on the master branch, then a macro is called:
```elisp
(lambda nil (interactive) (progn (call-interactively (quote evil-shift-right)) (execute-kbd-macro "gv")))
```
it works on the text under a heading, but it also adds spaces in front of the headings stars `*`, which causes the heading to break.

**Comment by wolfv6** [comment]
Thanks @duianto.   So I guess I should close this issue.
