### ISSUE TITLE
auctex ignores company-minimum-prefix-length

### ISSUE THREAD

**Issue by fredRos** [syl20bnr/spacemacs#9388]
#### Description :octocat:
Auctex auto-completion triggers on single character and ignores setting 

```lisp
(defun dotspacemacs/user-config ()
  (setq company-minimum-prefix-length 2)
)

```
This setting is respected for example in elisp-mode and other editing modes but not with auctex. This is annoying when typesetting math with the usual single-character symbols like `i` or `n`.

#### Reproduction guide :beetle:
- Start Emacs
- add latex and  auto-completion layers
- open a tex file, enter a single character like `n`

*Observed behaviour:* :eyes: :broken_heart:
the menu pops for a single character, the content depends on what other files are open and yield keywords to the completion suggestions. 

*Expected behaviour:* :heart: :smile:
The menu should pop up only if two characters are entered

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python html windows-scripts javascript
        (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
        better-defaults bibtex c-c   emacs-lisp extra-langs git helm latex markdown php semantic yaml)
```

**Comment by d12frosted** [comment]
Are you sure that the problem is related to `company-minimum-prefix-length`? That value is set to `2` in `auto-completion` layer and is not being changed by tex layer.

**Comment by fredRos** [comment]
That's the point, in auctex the completion ignores my setting of `company-minimum-prefix-length`. Or is there a different way to set it? Is company not used by auctex?

**Comment by CeleritasCelery** [comment]
It uses `company-auctex`. However the company backend writer can override the `company-minimum-prefix-length` test and have it always trigger on certain symbols or locations. You should forward your issue to [company-auctex](https://github.com/alexeyr/company-auctex) and see what they say.

**Comment by jonatanlinden** [comment]
I think the problem is that company-auctex requires tex-mode (reason unknown), and in auctex/tex.el (version 11.91.0) this piece of gold can be found:

```
;; By default, company completions kick in after a prefix of 3 chars has
;; been typed.  Since we don't have too many completions, that's too
;; much.
(set (make-local-variable 'company-minimum-prefix-length) 1)))
```

Could you verify the value of company-minimum-prefix-length after tex/company-auctex has been loaded? Probably you should forward your issue to auctex.

**Comment by fredRos** [comment]
Thanks @jonatanlinden I think you pinpointed the cause of the trouble.

```
company-minimum-prefix-length is a variable defined in ‘company.el’.
Its value is 1
Original value was 3
Local in buffer tardis-short.tex; global value is 2
```

I will forward the issue. For the meantime, do you know a workaround? I tried to set the local variable again at the bottom of my tex file

```
% Local Variables:
% company-minimum-prefix-length:2
% End:
```

but then emacs ask me to confirm because it thinks it's an unsafe variable. This is also annoying.

**Comment by CeleritasCelery** [comment]
You can declare a variable safe by adding it to `safe-local-variable-values`

**Comment by tsdh** [comment]
I'm guilty, I added that code to auctex. :-)

But really, isn't that tweak reasonable?  I mean, in the common cases of stuff like \alpha, \beta, \cite, \ref, \label, etc. after having typed three characters (the \ doesn't count), there's only one candidate left over so it's too late for a completion popup (whose main purpose is to foster explorability, IMHO).

I can easily remove that code but I wonder how many people like the current behavior (like me).

**Comment by brabalan** [comment]
@tsdh This combined with the company-auctex-prefix bug (see my comment on https://github.com/alexeyr/company-auctex/issues/18) makes it unusable for me.

**Comment by jonatanlinden** [comment]
The setting is customisable, so I believe it should only be tweaked by the end user.
I respect that you want your minimum prefix to be 1, but I prefer my minimum prefix length otherwise. :-)
And if someone uses multiple company-backends (like company-files for example), why should the behaviour of them change depending on the buffer type?

**Comment by tsdh** [comment]
@jonatanlinden Ok, I see that this setting isn't appropriate when you use things like the dabbrev backend which generates too many matches.  I'll remove it.

**Comment by tsdh** [comment]
Fixed in Git: http://git.savannah.gnu.org/cgit/auctex.git/commit/?id=b2571b6048928882903204553716b9ec19d3e15b

**Comment by fredRos** [comment]
For reference from https://github.com/alexeyr/company-auctex/issues/18#issuecomment-346548427

> As a workaround for the prefix length, I have this in my configuration.

  ```
(eval-after-load "latex"
    '(add-hook 'LaTeX-mode-hook
               (lambda ()
                 (setq company-minimum-prefix-length 4))))
```
