### ISSUE TITLE
IELM buffers override minor mode keys and duplicate menus

### ISSUE THREAD

**Issue by dsedivec** [syl20bnr/spacemacs#9391]
#### Description :octocat:
IELM buffers get all their menus doubled, and keys in `ielm-map` cannot be overridden by minor modes such as paredit.

#### Reproduction guide :beetle:
- Do a brand new installation of the Spacemacs develop branch
- Start Emacs
- Select "holy mode" but use all other defaults (helm, etc.)
- `M-x ielm RET` to enter a new IELM buffer

*Observed behaviour:* :eyes: :broken_heart:
* The "IELM" menu has two duplicate "IELM" options under it.
* The "Complete," "Signals," and "In/Out" menus are similarly duplicated.
* Keys in `ielm-map` cannot be overridden.  While you can, for example, enable `paredit-mode` in the buffer, backspace will still be `backward-delete-char-untabify` from `ielm-map`.

*Expected behaviour:* :heart: :smile:
* No duplicated menus.
* Bindings from minor modes such as `paredit-mode` take precedence over bindings in the major mode's map, `ielm-map` (AKA `inferior-emacs-lisp-mode-map`).

Something is putting `ielm-map` into `evil-mode-map-alist` like `(cons t ielm-map)` in IELM buffers.  `evil-mode-map-alist`, in turn, is always in `emulation-mode-map-alists` in Spacemacs (AFAIK), which means `ielm-map` bindings always override minor mode maps in IELM buffers.

I have not observed this change in `evil-mode-map-alist` in other modes so far.  When editing an Emacs Lisp file, or even in the `spacemacs/report-issue-mode` buffer where I am typing this bug report, `evil-mode-map-alist` is simply (and remember that I'm in holy mode):

```elisp
((evil-emacs-state-local-minor-mode keymap)
 (evil-emacs-state-minor-mode keymap
                              (26 . evil-exit-emacs-state)))
```

I cannot figure out what is putting `ielm-map` in `evil-mode-map-alist`.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.50.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 98ff30f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by bmag** [comment]
Seeing the same in other comint-derived modes: `inferior-python-mode` and `shell-mode`. (on develop branch, hybrid editing style)

**Comment by bmag** [comment]
This is an old upstream bug in Evil: https://github.com/emacs-evil/evil/issues/344

**Comment by montag451** [comment]
I use this piece of code to fix the problem, it's not ideal but at least it lets me use paredit in IELM buffer:
```elisp
(defun my/fix-evil-hiding-minor-mode-map (&rest _args)
  "See `https://github.com/syl20bnr/spacemacs/issues/9391'"
  (let ((mjm-keymap (intern-soft (format "%s-map" major-mode))))
    (when mjm-keymap
      (setq evil-mode-map-alist
	    (cl-loop for (c . k) in evil-mode-map-alist
		     unless (and (eq c t) (eq k (symbol-value mjm-keymap)))
		     collect (cons c k))))))
(advice-add 'evil-normalize-keymaps :after #'my/fix-evil-hiding-minor-mode-map)
```
Hope it helps !
