### ISSUE TITLE
org-version function returns wrong org-mode version

### ISSUE THREAD

**Issue by wolfv6** [syl20bnr/spacemacs#9392]
#### Description :octocat:
org-version function returns org-mode version that does not exist (yet).

#### Reproduction guide :beetle:
- Start Emacs
- SPC SPC org-version

*Observed behaviour:* :eyes: :broken_heart:
org mode version 9.0.9

*Expected behaviour:* :heart: :smile:
org mode version 2.4.7

From my ~/.emacs.d/elpa/org-plus-contrib-20170717/org-drill.el :   Version: 2.4.7

Newest version is on BitBucket:  Version: 2.6.1
https://bitbucket.org/eeeickythump/org-drill/raw/01b05cd7561ad69e5ec9c1200414d4fa128c9a17/org-drill.el

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy evil-snipe emacs-lisp org spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by phaer** [comment]
I think it works as designed and you are confusing the version of `org-mode` itself (9.0.9) with the version of `org-drill`, a contributed extension (2.4.7.).

**Comment by wolfv6** [comment]
@phaer, you'er right.  My mistake, Sorry.
