### ISSUE TITLE
Golang layer autocomplete suggestions incomplete

### ISSUE THREAD

**Issue by mrmagooey** [syl20bnr/spacemacs#9393]
#### Description :octocat:
The golang layer doesn't appear to have autocomplete suggestions for packages within the repository.

Autocomplete suggestions work fine for external packages, and any references within the current package, but not for other packages in the same repository. 

NB Manually turning on auto-complete-mode (and turning company-mode off) suggests items from the internal package, but will also suggest inappropriate completions.

#### Reproduction guide :beetle:
- Start Emacs
- Open a go project with a project structure like:

    .
    ├── blah/
    │   └── blah.go
    ├── main.go
    └── asdf.go

    
    // blah/blah.go
    package blah
    func Foo() {}
    func Bar() {}
    
    // main.go
    import "import/path/blah"                  // repository package
    import "fmt"                               // golang system package
    import "github.com/fsnotify/fsnotify"      // randomly chosen external package

    func main (){
       // try autocompletions here
    }
    func myFunc(){}
    
    // asdf.go
    func anotherFunc(){}

- Try to get appropriate autocompletions to work in the main.main() function for the `blah` package (Foo and Bar).

*Observed behaviour:* :eyes: :broken_heart:
User packages in the repository will not have auto-completion suggestions:

- In main.go main(), start referring to `blah.F` or `blah.B`
- The autocomplete popup will not appear or suggest Foo or Bar

Other files in the package will have auto-completion:
- In main.go main(), start referring to `myFunc()` or `anotherFunc()`
- The autocomplete popup will appear and correctly suggest completions

External packages such as Golang system packages or other third-party packages will have correct auto-completion suggestions:

- In main.go main(), start referring to either `fmt.` or `fsnotify.` 
- The autocomplete popup will appear and suggest appropriate package completions

The autocomplete system does seem to sometimes get suggestions from internal packages, but then doesn't seem to update these when the package contents are updated, so the behaviour is a bit hard to nail down.

*Expected behaviour:* :heart: :smile:
The autocomplete suggestions will work the same for packages either internal or external to the repository being worked on.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af1454)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(csv go yaml auto-completion better-defaults emacs-lisp git markdown org python react javascript latex
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     syntax-checking version-control docker myLayer)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by CeleritasCelery** [comment]
What are you using to provide suggestions to autocomplete? When I look at the layer I only see `company-go` and you said you are not using company.

**Comment by mrmagooey** [comment]
I'm using company, I just manually tried the auto-complete-mode to test its behaviour. The layer is being used as it is supplied with spacemacs, I'm not doing any configuration on it in my .spacemacs file.

**Comment by CeleritasCelery** [comment]
What is the behavior with stock emacs and `company-go`?

**Comment by mrmagooey** [comment]
So with spacemacs uninstalled and the best barebones `.emacs` file I could muster, looking like: 

    (require 'package)
    (package-initialize)
    (setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                             ("marmalade" . "https://marmalade-repo.org/packages/")
                             ("melpa" . "https://melpa.org/packages/")))
    (package-refresh-contents)
    (package-install 'go-mode)
    (package-install 'company)
    (package-install 'company-go)
    (package-install 'exec-path-from-shell)
    
    (require 'company)
    (require 'company-go)
    
    (add-hook 'after-init-hook 'global-company-mode)
    
    (add-hook 'go-mode-hook (lambda ()
                              (set (make-local-variable 'company-backends) '(company-go))
                              (company-mode)))
    
    (when (memq window-system '(mac ns x))
      (exec-path-from-shell-initialize))

I still get the same behaviour as described originally, i.e. no autocompletion for packages in the repository. I assume I should open an issue in https://github.com/nsf/gocode/ ?

**Comment by CeleritasCelery** [comment]
Seems like it. Thank you for taking the time to source this. Open an issue upstream then report back here what you find.

**Comment by mrmagooey** [comment]
So the issue appears to be that gocode doesn't actually read source code when making auto-completion suggestions, it reads `.a` files in GOPATH/pkg. So, if you are working on a project with multiple packages, you will potentially need to go into each package directory and run `go install` in order to generate (or renew) a package object which gocode will then inspect and produce auto-completion suggestions form. The same thing holds for the vendor packages.
