### ISSUE TITLE
Frozen emacs SPC-p-f from scratch buffer

### ISSUE THREAD

**Issue by shaiguitar** [syl20bnr/spacemacs#9394]
#### Description

Emacs freezes if projectile find is launched when in the `*scratch*` buffer.

#### Reproduction guide :beetle:
- Start Emacs
- Open the `*scratch*` buffer.
- Type [SPC p f]

*Observed behaviour:* :eyes: :broken_heart:

- Frozen emacs.

*Expected behaviour:* :heart: :smile:

- Maybe a message saying "cannot projectile from scratch buffer. please use SPC-p-p"

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af1454)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

```elisp
(ruby swift auto-completion terraform csv better-defaults org-jira evil-commentary
      (git :variables git-gutter-use-fringe t)
      (haskell :variables haskell-enable-shm-support t)
      extra-langs perspectives restclient slime clojure go html javascript racket
      (shell :variables shell-default-term-shell "/bin/zsh")
      shell-scripts markdown evil-snipe xkcd org python3 cb-core emacs-lisp syntax-checking yaml scala)
```

#### Backtrace :paw_prints:

No backtrace, just frozen emacs.

**Comment by d12frosted** [comment]
Can't reproduce. In my case it says 'projectile-project-root: You're not in a project'. 

Could you please update all your packages and check again?
