### ISSUE TITLE
Setting up RVM for use with Ruby layer is unclear

### ISSUE THREAD

**Issue by mathpunk** [syl20bnr/spacemacs#9395]
#### Description :octocat:
It's unclear how to set up my environment correctly to use the Ruby layer. (Was: #9351)

#### Reproduction guide :beetle:
- Start Emacs with ruby layer enabled
- Open a ruby file
- `, s i` to start the ruby repl (or, `, t a` to run tests)

*Observed behaviour:* :eyes: :broken_heart:
"Searching for program: No such file or directory, bundle"

*Expected behaviour:* :heart: :smile:
The repl opens without error or the tests run.

*Also note:* :microscope:
Last week I managed to monkey around with zsh in ansi-term, and with .zshrc and .zshenv, until I got this layer kind of working, although the repl would open with a lot of complaints about not being able to find `pry`. Unfortunately, I can't remember what I did, and the changes did not persist through a power cycle of the computer.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 2ef2303)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(own ivy better-defaults
     (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-space-key-behavior 'reject auto-completion-return-key-behavior 'reject auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-complete-with-key-sequence "df" auto-completion-complete-with-key-sequence-delay 0.3)
     (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/usr/bin/zsh" shell-default-height 40 shell-default-position 'bottom)
     shell-scripts
     (org :variables org-enable-reveal-js-support t org-enable-org-journal-support t)
     yaml csv html restclient emacs-lisp clojure
     (ruby :variables ruby-test-runner 'rspec ruby-version-manager 'rvm)
     syntax-checking git github markdown deft latex themes-megapack typography emoji)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (file-error "Searching for program" "No such file or directory" "bundle")
  make-process(:name "bundle console" :buffer #<buffer *bundle console*<5>> :command ("bundle" "console"))
  apply(make-process (:name "bundle console" :buffer #<buffer *bundle console*<5>> :command ("bundle" "console")))
  start-process("bundle console" #<buffer *bundle console*<5>> "bundle" "console")
  apply(start-process "bundle console" #<buffer *bundle console*<5>> "bundle" "console")
  #[899 "\301\302\"\211\203\303\302&\202#\303\304%\207" [default-directory find-file-name-handler start-file-process apply start-process] 12 2369300]("bundle console" #<buffer *bundle console*<5>> "bundle" "console")
  apply(#[899 "\301\302\"\211\203\303\302&\202#\303\304%\207" [default-directory find-file-name-handler start-file-process apply start-process] 12 2369300] "bundle console" #<buffer *bundle console*<5>> "bundle" "console")
  start-file-process--with-editor-process-filter(#[899 "\301\302\"\211\203\303\302&\202#\303\304%\207" [default-directory find-file-name-handler start-file-process apply start-process] 12 2369300] "bundle console" #<buffer *bundle console*<5>> "bundle" "console")
  apply(start-file-process--with-editor-process-filter #[899 "\301\302\"\211\203\303\302&\202#\303\304%\207" [default-directory find-file-name-handler start-file-process apply start-process] 12 2369300] ("bundle console" #<buffer *bundle console*<5>> "bundle" "console"))
  start-file-process("bundle console" #<buffer *bundle console*<5>> "bundle" "console")
  apply(start-file-process "bundle console" #<buffer *bundle console*<5>> "bundle" "console")
  comint-exec-1("bundle console" #<buffer *bundle console*<5>> "bundle" ("console"))
  comint-exec(#<buffer *bundle console*<5>> "bundle console" "bundle" nil ("console"))
  make-comint-in-buffer("bundle console" "*bundle console*<5>" "bundle" nil "console")
  apply(make-comint-in-buffer "bundle console" "*bundle console*<5>" "bundle" nil "console")
  run-ruby("bundle console" "bundle console")
  run-ruby-or-pop-to-buffer("bundle console" "bundle console" nil)
  inf-ruby-console-run("bundle console" "bundle console")
  inf-ruby-console-default("~/work/projects/game-of-life/")
  inf-ruby-console-auto()
  robe-start(nil)
  funcall-interactively(robe-start nil)
  call-interactively(robe-start nil nil)
  command-execute(robe-start)
```

**Comment by mathpunk** [comment]
Here's how I fixed my issues:
- Add these three gems https://github.com/dgutov/robe#dependencies to my project's Gemfile
- Install chruby and ruby-install, and use these instead of rvm to install and use the version of Ruby I want
- `gem install bundler`
- `bundle install` in my project
- Add to my .spacemacs 
     (ruby :variables
           ruby-version-manager 'chruby
           ruby-enable-enh-ruby-mode t)

Could the documentation use more explicitness, or did I fail to RTFM of the various moving pieces here? I could see arguments either way.

**Comment by fiveNinePlusR** [comment]
I think the docs could probably be a bit more explicit here for the various ways to configure ruby.

**Comment by d12frosted** [comment]
Documentation PRs are welcome 😸
