### ISSUE TITLE
Working with rsync and firestarter from spacemacs.

### ISSUE THREAD

**Issue by anmoljagetia** [syl20bnr/spacemacs#9398]
Hey,

I recently read this awesome article by @CestDiego, and got inspired to achieve soemthing like this for my setup as well.

I added firestarter to `dotspacemacs-additional-packages` and then created a new test directory in my home folder on macOS Sierra.

In the folder, I added [this code](http://www.diegoberrocal.com/blog/2015/12/04/using-rsync-when-tramp-is-too-much/), but nothing seems to work. I am looking for rsync logs or ssh logs, but I can't see anything. I can confirm that I have ssh and rsync installed.

**Comment by anmoljagetia** [comment]
@joehillen On gitter suggested I use the following, which also didn't seem to work :(

1. load this [file](https://gist.github.com/l3msh0/5006645#file-auto-rsync-el-L8) in my user-config() method.
2. Add a .dir-local.el in the root of the project I want to sync.
3.  Added the following code in the `.dir-local.el` file, in the root of the directory.
```elisp 
(setq auto-rsync-dir-alist
  '("/Users/anmol.j/test/" . "/Users/anmol.j/test2/"))
``` 

Can anyone please help with this? Looks like a trivial problem, but my lack of experience with elisp is kinda holding me back :(

All help is greatly appreciated.

**Comment by joehillen** [comment]
That wasn't what I meant. Unfortunately, I don't have time or motivation to hold your hand.

I'm sorry to say, but you're going to have to learn some more elisp and emacs to get what you want. 

This should help get you started: https://gist.github.com/TheBB/367096660b203952c162

I also recommend hitting `C-h i` and clicking on `Emacs Lisp Intro`. It's a fantastic introduction to the basics.
