### ISSUE TITLE
Update Emacs25.2 and The Recent Project is hidden, even spacemacs open last buffer by defaults.

### ISSUE THREAD

**Issue by lsytj0413** [syl20bnr/spacemacs#9405]
#### Description :octocat:
Update Emacs25.2 and The Recent Project is hidden, even spacemacs open last buffer by defaults.

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
in the *spacemacs* buffer, the recent project doesn't show, and the spacemacs open all the buffer when last quite emacs doesn't closed, behaviour like SPC q r.

*Expected behaviour:* :heart: :smile:

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 98ff30f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-sort-by-usage t)
 (better-defaults :variables better-defaults-move-to-end-of-code-first t)
 emacs-lisp git markdown org
 (shell :variables shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 asm
 (python :variables python-sort-imports-on-save t)
 semantic
 (go :variables go-tab-width 4 go-use-gometalinter t)
 ranger gtags ibuffer sql
 (colors :variables colors-enable-nyan-cat-progress-bar t colors-enable-rainbow-identifiers t)
 (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
 graphviz plantuml docker
 (syntax-checking :variables syntax-checking-enable-by-default t)
 liter ycmd)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
```

**Comment by duianto** [comment]
Pull the latest develop branch.

This recent commit: Load org-projectile lazily, after org-capture https://github.com/syl20bnr/spacemacs/commit/459268f52649d808a183f5fa4efa7e7c33c9264b
solved the issue where the projects did not appear on startup.

**Comment by lsytj0413** [comment]
@duianto 
Thank you very much, it works. Anyway, do you know the other question's solution?

**Comment by duianto** [comment]
>the spacemacs open all the buffer when last quite emacs doesn't closed, behaviour like SPC q r.

I don't understand the "doesn't closed" part, but the rest sounds like you want to restore the previous sessions files the next time you start Spacemacs.

I haven't tried that, I just open previous files from the Helm Recentf list `SPC f r`.

These links might be helpful:
https://stackoverflow.com/questions/803812/emacs-reopen-buffers-from-last-session-on-startup

And here's someone that had been using `desktop-mode` for 10 years, but switched to using projectile:
https://www.reddit.com/r/emacs/comments/4lymig/how_do_you_persist_buffers_and_save_your_window/

**Comment by lsytj0413** [comment]
I mean that the spacemacs variable *dotspacemacs-auto-resume-layouts* is not work, when i set it to *nil*,
the last auto saved layouts are resume automatically upon start always.

**Comment by duianto** [comment]
It seems to be working for me.

When `dotspacemacs-auto-resume-layouts` is set to `nil` (default), and I restart without resuming layouts
`SPC q R` or quit `SPC q q` and start Spacemacs, then the default layout opens.

Setting it to `t` remembers the layouts after `SPC q R` and `SPC q q`.

When I set it to back to `nil` and quit/start, then only the default layout opens again, as expected.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 0fb17fa9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip 'manual)
 colors emacs-lisp git haskell helm markdown org spell-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by lsytj0413** [comment]
It not working for me. :worried:

**Comment by duianto** [comment]
Could it be related to this line in your layers config?
`(spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)`

**Comment by lsytj0413** [comment]
I tried delete *spacemacs-layouts* layer, but the problem is still exist.

**Comment by lsytj0413** [comment]
If i exclude the *persp-mode* package, the problem has gone, but *SPC q r* can't resume layouts too.:tired_face:

**Comment by lsytj0413** [comment]
I found the resume layouts reason. Because i start emacs with ubuntu launcher, and my emacs.desktop config the emacs start with --resume-layouts option, so emacs always resume layouts when it is up.

the solution is, edit emacs.desktop file, set the Exec equals "/usr/bin/emacs %F" solve the problem.
