### ISSUE TITLE
org-capture Error: Symbol's value as variable is void: occ-get-categories

### ISSUE THREAD

**Issue by RaT0M** [syl20bnr/spacemacs#9407]
#### Description :octocat:
There are already many issues relating to the changes in **org-projectile** (*should be the error source!?*) that have been solved. Still I cannot get this to work.

**Error** : cannot use `org capture`.
**Message** : require: Symbol's value as variable is void: occ-get-categories

related to:
https://github.com/syl20bnr/spacemacs/issues/9374
https://github.com/syl20bnr/spacemacs/pull/9368
https://github.com/IvanMalison/org-projectile#breaking-changes

Also the integration should be fixed as of https://github.com/syl20bnr/spacemacs/pull/9380

org-mode setup:

```
  (with-eval-after-load 'org (
    setq org-agenda-files
      '("~/personal_todo.org" "~/work_todo.org" "~/notes.org"))
  ;; org refile targets
    (setq org-refile-targets
        '((nil :maxlevel . 5)
          (org-agenda-files :maxlevel . 3)))
    (setq org-outline-path-complete-in-steps nil)         ; Refile in a single go
    (setq org-refile-use-outline-path t)                  ; Show full paths for refiling

    (setq org-todo-keywords
          '((sequence "TODO" "NEXT" "WAITING" "SOMETIME" "|" "DONE")))
  ;; TAGS
    (setq org-tag-alist '((:startgroup . nil)
                          ("WORK" . ?w) ("HOME" . ?h)
                          ("NFH" . ?n)
                          (:endgroup . nil)
                          ("laptop" . ?l) ("phone" . ?p)))
  ;; ORG REF/ BIBTEX
    (setq reftex-default-bibliography '("~/Documents/Literature/Masterbase.bib"))
    (setq org-ref-default-bibliography '("~/Documents/Literature/Masterbase.bib")
          org-ref-pdf-directory "~/Documents/Literature/"
          org-ref-bibliography-notes "~/Documents/Literature/notes.org") 

    (setq bibtex-completion-library-path "~/Documents/Literature/")
    ;; (setq bibtex-completion-pdf-field "file")

    ;; (defun my/org-ref-open-pdf-at-point ()
    ;;   "Open the pdf for bibtex key under point if it exists."
    ;;   (interactive)
    ;;   (let* ((results (org-ref-get-bibtex-key-and-file))
    ;;          (key (car results))
    ;;          (pdf-file (car (bibtex-completion-find-pdf key))))
    ;;     (if (file-exists-p pdf-file)
    ;;         (org-open-file pdf-file)
    ;;       (message "No PDF found for %s" key))))

    ;; (setq org-ref-open-pdf-function 'my/org-ref-open-pdf-at-point)
    ;; (setq org-ref-open-pdf-function
    ;;       (lambda (fpath)
    ;;         (start-process ("xreader" "*helm-bibtex-xreader*" "/usr/bin/xreader" fpath))))

  ;; ORG CAPTURE
    (setq org-capture-templates
          '(("w" "Work Todo" entry (file+headline "~/work_todo.org" "Inbox")
             "* TODO %? :WORK:\n  %i\n  %a")
            ("p" "Personal Todo" entry (file+headline "~/personal_todo.org" "Inbox")
              "* TODO %? :Personal:\n  %i\n  %a")
            ("n" "Note" entry (file+headline "~/notes.org" "Inbox")
             "* %?\nEntered on %U\n  %i\n  %a")
            ("j" "Journal entry" plain (file+datetree+prompt "~/journal.org")
             "%K - %a\n%i\n%?\n")))))
```

#### Reproduction guide :beetle:
- Start Emacs
- hit C-c c / SPC a o c / .. 

*Observed behaviour:* :eyes: :broken_heart:
Mini buffer shows: Symbol's value as variable is void: occ-get-categories

*Expected behaviour:* :heart: :smile:
start filing an org-capture..

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 0fb17fa)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 bibtex csv emacs-lisp git helm html ibuffer markdown
 (org :variables org-enable-bootstrap-support t org-enable-github-support t org-enable-reveal-js-support t)
 pandoc python ranger semantic themes-megapack
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (spell-checking :variables spell-checking-enable-by-default nil)
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 version-control yaml)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

Maybe it is just personal inabilities concerning the setup.. :confused: but still can be a but not being encountered by other users. if not so, sorry for taking your time.

**Comment by sjsrey** [comment]
I, too, am encountering the `Symbol's value as variable is void: occ-get-categories` after trying `C-c -c`. I thought it must have been due to a change in trying to setup **org-pomodoro**. However, I've now gone back to a fresh install of spacemacs via git and a clean .spacemacs file and get the same error.

`
~ » uname -a
Linux cody 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
`
Emacs 24.5.1

**Comment by nikolaiam** [comment]
The same problem here.

**Comment by IvanMalison** [comment]
@nikolaiam @sjsrey @RaT0M  a backtrace would be super helpful here. have you updated org-category-capture?

**Comment by Awesomecase** [comment]
@IvanMalison The most recent org-projectile update fixed my occ-category-capture problems. Good work! I appreciate it.

**Comment by IvanMalison** [comment]
ahh @sjsrey The problem was that up until https://github.com/IvanMalison/org-projectile/commit/634d148033ea9de7f8dffc4dece69820541e8bcf emacs24 incompatible calls to cl-defmethod were being used.

**Comment by IvanMalison** [comment]
This can be closed now, I believe

**Comment by sjsrey** [comment]
@IvanMalison yes, updating org-projectile has fixed the issue on my side. Thanks!

**Comment by RaT0M** [comment]
@IvanMalison same here. problem solved. Thank you!
