### ISSUE TITLE
macOS beta breaks emacs - "unknown color"

### ISSUE THREAD

**Issue by mkleehammer** [syl20bnr/spacemacs#9416]
macOS 10.13 Beta (17A330h) has broken emacs on 2 machines so far.  I thought I'd post the solution here in case anyone hits it now, but also it may be a mass problem in the near future if it isn't just a beta bug.

@dkleehammer investigated and found that vanilla emacs works, but anything using colors or themes will render emacs unusable.  Almost every key / command fails with an "unknown color" error.  I couldn't get any more detail because I couldn't even switch to the Messages buffer.

Fortunately he also found the solution here: https://apple.stackexchange.com/questions/84685/how-can-i-fix-a-missing-color-in-emacs

Simply delete the file `~/Library/Colors/Emacs.clr` and restart emacs.  Apparently this file is created on startup if necessary.

Does anyone have a better understanding of what this file actually does?  Is there some way to detect this and recreate the file on startup?

**Comment by CeleritasCelery** [comment]
Does it only break Spacemacs or is Stock Emacs as well?
