### ISSUE TITLE
Python mode doesn't display right signature of functions

### ISSUE THREAD

**Issue by zarzen** [syl20bnr/spacemacs#9427]
#### Description :octocat:
Python mode doesn't display right signature of the function

#### Reproduction guide :beetle:
- Start Emacs
- Open a python file with python layer enabled
- Using one builtin function

*Observed behaviour:* :eyes: :broken_heart:
The signature of the function displayed at mini buffer is not right.
Every parameter name will lose several characters of the beginning.
e.g. a function has signature `some_func(self, learning_rate, use_locking=False)` 
will be displayed as `somefunc(ng_rate, cking=False)`
class function: ![image](https://user-images.githubusercontent.com/1150493/29256551-4a98003a-8079-11e7-919a-572c8501166d.png)    
mini buffer: 
![image](https://user-images.githubusercontent.com/1150493/29256567-618096c2-8079-11e7-9ef6-352e8a059a6d.png)

*Expected behaviour:* :heart: :smile:
It should display right signature of the function

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm auto-completion better-defaults emacs-lisp git markdown org
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        spell-checking version-control scala)
```

**Comment by CeleritasCelery** [comment]
What company backend are you using?

**Comment by zarzen** [comment]
@CeleritasCelery I just enabled `auto-completion` layer. Not sure which `company` backend. Here you mean `ivy` or `helm`? If yes, I am using `helm`

**Comment by CeleritasCelery** [comment]
If you using the default then you are using [anaconda](https://github.com/proofit404/anaconda-mode). I would ask your question at their repo as Spacemacs has nothing to do with the completion candidates.

**Comment by zarzen** [comment]
@CeleritasCelery Yes, I am using `anaconda-mode`. Thanks!

**Comment by zarzen** [comment]
Upgrade `anaconda-mode` package through `pip install --upgrade anaconda-mode` solves my problem. If this not work, try `pip install --upgrade jedi json-rpc service_factory` manually upgrade `anaconda-mode` dependencies. 
And not use `python3.6`, which causes issues under `syntax-checking` with `pylint`.
