### ISSUE TITLE
The Agda layer needs to be added to 'spacemacs-indent-sensitive-modes

### ISSUE THREAD

**Issue by glguy** [syl20bnr/spacemacs#9429]
#### Description :octocat:
The Agda layer needs to be added to 'spacemacs-indent-sensitive-modes
This language is layout sensitive and currently indentation is being
lost on paste.

This can be fixed by adding this line to the packages.el after the use-package line:

    (add-to-list 'spacemacs-indent-sensitive-modes 'agda2-mode)

#### Reproduction guide :beetle:
- Start Emacs
- Edit Agda source files
- Paste some code

*Observed behaviour:* :eyes: :broken_heart:
Indentation lost

*Expected behaviour:* :heart: :smile:
Indentation not lost

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. f11f9274)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(coq agda helm emacs-lisp auto-completion
     (haskell :variables haskell-completion-backend 'dante))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
The following PRs changes are now on the `develop` branch:
[agda] Fix #9429: Make agda layer retain indentation on paste. #12771
