### ISSUE TITLE
semantic layer plus auto-completion layer: "Nothing to complete" errors after spaces in elisp

### ISSUE THREAD

**Issue by braham-snyder** [syl20bnr/spacemacs#9438]
#### Description
Relatively benign but very frequent error with `semantic` and `auto-completion`.

#### Reproduction guide
- Fresh Spacemacs installation, master or develop branch
- Install the `semantic` and `auto-completion` layers
- Open a buffer in `emacs-lisp-mode`
- Insert ` ` (a literal space) and wait a second or two

*Observed behaviour:*
- Error, with `*Messages*`:
```
Company: An error occurred in auto-begin
Nothing to complete
```

*Expected behaviour:*

No error thrown.

Biggest issue is probably just that, unhandled, it makes `toggle-debug-on-error`
quite unwieldy for other uses.

Possibly but not necessarily related:
https://github.com/company-mode/company-mode/issues/614
https://github.com/abo-abo/lispy/issues/313

#### System Info
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(python ivy auto-completion semantic emacs-lisp)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace
```
Debugger entered--Lisp error: (error "Nothing to complete")
  signal(error ("Nothing to complete"))
  error("Nothing to complete")
  semantic-analyze-possible-completions(nil)
  semantic-analyze-completion-at-point-function()
  completion--capf-wrapper(semantic-analyze-completion-at-point-function optimist)
  run-hook-wrapped(completion--capf-wrapper semantic-analyze-completion-at-point-function optimist)
  company--capf-data-real()
  company--capf-data()
  company-capf(prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer .spacemacs> #<window 3 on .spacemacs> 294 2032)
  apply(company-idle-begin (#<buffer .spacemacs> #<window 3 on .spacemacs> 294 2032))
  timer-event-handler([t 22930 29496 132020 nil company-idle-begin (#<buffer .spacemacs> #<window 3 on .spacemacs> 294 2032) nil 0])
```

**Comment by CeleritasCelery** [comment]
Can you replicate this with stock Emacs, company, and sematic?

**Comment by braham-snyder** [comment]
> Can you replicate this with stock Emacs, company, and sematic?

I cannot. No error with:

1. `spacemacs/restart-stock-emacs-with-packages` `company,semantic`
2. `M-x` `company-mode`
3. `M-x` `semantic-mode`
4. Insert ` `

Are you unable to replicate it with Spacemacs?

**Comment by CeleritasCelery** [comment]
No, I can't reproduce your error following the steps you outlined above. Perhaps reinstall the packages?

**Comment by braham-snyder** [comment]
this is what I meant by "fresh installation" (`fish` script -- incidentally, I just tried reopening with `zsh` as `$SHELL` just to see, but same deal):

```
function reinstall_and_open_fresh_spcm
  trash ~/fresh-spcm
  mkdir ~/fresh-spcm
  git clone https://github.com/syl20bnr/spacemacs.git ~/fresh-spcm/.emacs.d
  cd ~/fresh-spcm/.emacs.d
  git checkout develop
  env HOME=$HOME/fresh-spcm/ emacs
end
```
