### ISSUE TITLE
Add key binding to disable flycheck automatic

### ISSUE THREAD

**Issue by maxigit** [syl20bnr/spacemacs#9441]
Flycheck automatically checks the syntax on different events depending on the value of `flycheck-check-syntax-automatically`. It will be nice to enable/disable those event from a quickly. This will allow for example to temporarily disable checking on buffer change.

I propose to extend the current `SPC t s` to

   - `SPC t s s` actual `SPC t s`
   - `SPC t s b` buffer save 
   - `SPC t s i` buffer changed and idle
   - `SPC t s l` new line inserted

Or equivalent. If the request is accepted, I might be able to have a go and submit and PR.

**Comment by CeleritasCelery** [comment]
honestly I don't see the value in making these toggles. If you want to changes the flycheck triggers just add them to your `dotspacemacs/user-config`

**Comment by maxigit** [comment]
Well, that's true for every key bindings isn't it ?

**Comment by CeleritasCelery** [comment]
Not really. Moving lines, commenting code, narrowing, searching, etc. are pretty useless without keybindings. 

The toggles we have now are mostly to enable/disable minor modes. Any specific configuration is better served as part of the config. Though nothing is stopping you from creating these toggles for yourself.

**Comment by maxigit** [comment]
I agree, there are not necessarily the best key bindings possible, and I'm open to discussion.  I don't see how it would hurt to have some key new key bindings especially, if they just increase the actual "tree".
At the moment, there is key binding to disable flycheck. The problem with is it is:  it clears the error window making this toggle pretty useless. When I need to disable flycheck is generaly because, I have an error I want to fix, but modifying the code trigger flychek in the middle of my modification, when the file is invalid resulting in useless errors. I don't think I am the only one having this problem and thought everybody could benefit of such toggles. I am obviously wrong.

**Comment by CeleritasCelery** [comment]
That makes more sense. Though I can see this causing a lot of confusion, especially for new users. One may toggle off a check event and then not realize it and wonder why errors are not updating. When I am editing I generally ignore spurious errors while typing, but I can see what your saying about not having to worry about that. I just feel like this would be rarely used as one of the appeals of flycheck is that it "just works" without any babysitting. But that is just my take on it.

**Comment by maxigit** [comment]
I mainly use Spacemacs to program in Haskell. Error messages can be quite
complex (and long) and usefull. Trying to fix an error which disappears at
the second you start doing the modification can be really difficult. I
agree with you that maybe not all of the toggle are necessary, but one to
freeze flycheck would be usefull.
