### ISSUE TITLE
How do I adjust font size from .Xresources?

### ISSUE THREAD

**Issue by Poetastrophe** [syl20bnr/spacemacs#9442]
I have attempted to comment out the 'dotspacemacs-default-font' setting and even tried to omit the 'size' variable  but to no avail.
In my .Xresources file I have written
`emacs*font: Dejavu Sans Mono-50`
spacemacs seems to register it, since the first few seconds after startup it shows a window with fontsize as specified in the Xresources, but then it quickly reverts back to a small font I haven't defined anywhere. How can I get spacemacs to just use Xresources for font settings?

Update: It seems like a problem with --daemon mode. As emacs adjusts fonts size just fine according to Xresoucres when running emacs normally

**Comment by Compro-Prasad** [comment]
AFAIK I can set font in `~/.spacemacs`
