### ISSUE TITLE
How to adjust font size based on screen resolution in emacs

### ISSUE THREAD

**Issue by Poetastrophe** [syl20bnr/spacemacs#9445]
I tried to put this code in the spacemacs dotfile (in user init first, then user config) to adjust font for a HiDPI screen. But it does not seem to work.

`(when (> (x-display-pixel-width) 2560)
    (setq-default dotspacemacs-default-font '("DejaVu Sans Mono"
                                              :size 35
                                              :weight normal
                                              :width normal
                                              :powerline-scale 1.1)))
`
and I also ran the `(x-display-pixel-width)` in eshell and it returned 3840. 

UPDATE: It seems to be related to when emacs starts up in daemon mode in is unable to run the command (x-display-pixel-width) successfully.

**Comment by jasondf** [comment]
Oh, I just finished my work on this. Here is my solution:

    (defun set-font (english chinese english-size chinese-size)
      (set-face-attribute 'default nil :font
                          (format   "%s:pixelsize=%d"  english english-size))
      (dolist (charset '(kana han symbol cjk-misc bopomofo))
        (set-fontset-font (frame-parameter nil 'font) charset
                          (font-spec :family chinese :size chinese-size))))

    (when window-system
      (if (> (x-display-pixel-width) 1600) 
          (set-font "Monaco" "STFangSong" 16 20)
        (set-font "Monaco" "STFangSong" 14 16)))`

Please notice that: "x-display-pixel-width" is the later value of display resolution, like 2280 * 1800.
In my case, I'm trying to set emacs font size between macbook pro 13"(2560 * 1600) and 15"(2880 * 1800), so I set x-display-pixel-width to compare with 1600.
Hope it works for you.

**Comment by lulin** [comment]
> Oh, I just finished my work on this. Here is my solution:
> 
> ```
> (defun set-font (english chinese english-size chinese-size)
>   (set-face-attribute 'default nil :font
>                       (format   "%s:pixelsize=%d"  english english-size))
>   (dolist (charset '(kana han symbol cjk-misc bopomofo))
>     (set-fontset-font (frame-parameter nil 'font) charset
>                       (font-spec :family chinese :size chinese-size))))
> 
> (when window-system
>   (if (> (x-display-pixel-width) 1600) 
>       (set-font "Monaco" "STFangSong" 16 20)
>     (set-font "Monaco" "STFangSong" 14 16)))`
> ```
> 
> Please notice that: "x-display-pixel-width" is the later value of display resolution, like 2280 * 1800. In my case, I'm trying to set emacs font size between macbook pro 13"(2560 * 1600) and 15"(2880 * 1800), so I set x-display-pixel-width to compare with 1600. Hope it works for you.

Where should I put this code in my .spacemacs?

**Comment by fnussbaum** [comment]
This looks like it should go into `dotspacemacs/user-config`, but I would recommend to instead just include a condition in the `dotspacemacs-default-font`-setting in `dotspacemacs/init`. In my configuration I have the following to set a different font size on my laptop:
```elisp
   ;; Default font or prioritized list of fonts. This setting has no effect when
   ;; running Emacs in terminal. The font set here will be used for default and
   ;; fixed-pitch faces. The `:size' can be specified as
   ;; a non-negative integer (pixel size), or a floating-point (point size).
   ;; Point size is recommended, because it's device independent. (default 10.0)
   dotspacemacs-default-font `("Source Code Pro"
                               :size ,(if (string-equal (system-name) "laptopf")
                                          22
                                        16)
                               :weight normal
                               :width normal)
```

Conditioning on the system name is a simpler solution if your screen resolution is constant for each system. Crucially for me, it also works when starting emacs as a daemon, which the code posted above does not seem to do. Also, `window-system` as a predicate is deprecated now.
