### ISSUE TITLE
ocaml layer asked about abbreviations when trying to save a file

### ISSUE THREAD

**Issue by cdepillabout** [syl20bnr/spacemacs#9450]
#### Description :octocat:

After installing the OCaml layer, if I open an OCaml file and then try to exit with `:q`, I get a message in the bottom bar asking about saving abbreviations:

> Save abbrevs in /home/user/.emacs.d/.cache/abbrev_defs? (y or n)

I'm not sure why this is happening.  It doesn't appear to be related to related to OCaml. However, it started happening after installing the OCaml layer.  It doesn't seem to happen for any other file types.

I think the OCaml layer should be changed so this doesn't happen by default.

This could be a problem with the Tuareg mode:

https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1371&group_id=43&atid=255

Maybe @Chris00 could help clear this up.

#### Reproduction guide :beetle:
- Start Emacs
- Enable ocaml layer
- Open an OCaml `.ml` file
- Try to close the file

*Observed behaviour:* :eyes: :broken_heart:

I get asked the following question:

"Save abbrevs in /home/user/.emacs.d/.cache/abbrev_defs? (y or n)"

*Expected behaviour:* :heart: :smile:

Emacs closes without asking me any questions about abbreviations.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion colors docker emacs-lisp git
                 (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "fundamental")
                 helm html idris markdown ocaml
                 (org :variables org-enable-github-support t)
                 python
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 (spell-checking :variables spell-checking-enable-by-default nil)
                 syntax-checking version-control yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by cdepillabout** [comment]
This might just be an emacs feature and not have anything to do with ocaml or spacemacs:

https://github.com/emacs-mirror/emacs/blob/master/lisp/files.el#L5265

**Comment by bschommer** [comment]
I observed a similar behavior and it only occurred after a package update which update tuareg.

**Comment by Chris00** [comment]
I do not observe this behavior on my machine.  It would be helpful if you could bisect the [git history](https://github.com/ocaml/tuareg) to point out the problem.  By default `tuareg-use-abbrev-mode` is set to `nil` so abbrev mode should not be used.

**Comment by bschommer** [comment]
I did a quick diff between the last working version for me and the current one and it there were no changes regarding abbrevs. I suspect the problem lies somewhere else.

**Comment by Chris00** [comment]
Would it be linked to the enabling by default of SMIE?

**Comment by bschommer** [comment]
There also seems to be no diff concerning SMIE.

**Comment by Chris00** [comment]
So what is the commit after which the problem starts?

**Comment by bschommer** [comment]
I'm not sure, I suspect that it is not only tuareg because the changes started after a larger package update I did yesterday. I will try and reinstall spacemacs from scratch to see if that helps.

**Comment by bschommer** [comment]
Nope, with spacemacs from scratch it is the same.

**Comment by leviroth** [comment]
Is this still happening? I remember having similar issues a while back, which have now stopped. Unfortunately, I can't remember if I changed anything in the interim. :/

**Comment by LdBeth** [comment]
`(setq save-abbrev 'silently)` should prevent it ask you about it.

**Comment by Chris00** [comment]
Tuareg in MELPA should not cause any problem anymore.
