### ISSUE TITLE
emacs-plus HEAD does not work with the spacemacs config

### ISSUE THREAD

**Issue by johnhamelink** [syl20bnr/spacemacs#9457]
#### Description :octocat:
The spacemacs README mentions using emacs-plus from HEAD in order to have the title bar match the background colour. This version of emacs-plus is not able to run the `emacs.d/init.el` file. Downgrading to the regular emacs-plus release fixes this.

#### Reproduction guide :beetle:
```
$ brew tap d12frosted/emacs-plus
$ brew install emacs-plus --HEAD --with-natural-title-bars
$ brew linkapps emacs-plus
$ git clone https://github.com/syl20bnr/spacemacs.git ~/.emacs.d
$ /Applications/Emacs.app/Contents/MacOS/Emacs --debug-init
```

*Observed behaviour:* :eyes: :broken_heart:
Emacs fails to finish interpreting the `emacs.d/init.el` file and returns the following error:

```
Format specifier doesn't match argument type
```

*Expected behaviour:* :heart: :smile:
Emacs boots up and begins pulling down dependencies from the .spacemacs file as usual.

**Comment by bmag** [comment]
@johnhamelink what about the backtrace? (look for `*backtrace*` buffer)

**Comment by ggiraldez** [comment]
I tracked the error down to [here](https://github.com/syl20bnr/spacemacs/blob/master/core/core-spacemacs-buffer.el#L204). `image-size` is the built-in function that raises the error. It may be an Emacs bug or a backward incompatible change, since emacs-plus HEAD is currently installing 26.0.50 (built locally from source). The same code works fine with 25.2.1 (bottled).

**Comment by CarlQLange** [comment]
It works fine for me on --HEAD from last week…
By the way, you no longer need the natural-title-bars patch - setting something like

```
  (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
```

in your user-config will work.

**Comment by duianto** [comment]
The Emacs Plus repository has removed the `--natural-title-bar` command.

Therefore the Spacemacs develop branch readme also removed it:
https://github.com/syl20bnr/spacemacs/blob/develop/README.md#macos

The Emacs Plus repository has instructions for duplicating that flags behavior:
https://github.com/d12frosted/homebrew-emacs-plus#upgrade-from-emacs-25x

The Spacemacs master branch readme will be updated when the next version is released
(I don't have any insight into when that is)
