### ISSUE TITLE
Wakatime layer configuration not working! 

### ISSUE THREAD

**Issue by fakeid30** [syl20bnr/spacemacs#9460]
I configured wakatime layer as per http://spacemacs.org/layers/+web-services/wakatime/README.html but I can't see emacs show up in wakatime.com 

Here is my relevant .spacemacs file : https://pastebin.com/EM5P3yrS

I also enabled wakatime-global-mode .

What am I doing wrong?

**Comment by luochen1990** [comment]
@fakeid30 Have you solved this problem?  I have the same problem and still not find a workaround.

**Comment by yihuajack** [comment]
> @fakeid30 Have you solved this problem? I have the same problem and still not find a workaround.

Add `wakatime-mode` to `dotspacemacs-additional-packages` in `.spacemacs`.
Add
```
'(global-wakatime-mode t)
'(package-selected-packages
 '(wakatime-mode))
'(wakatime-api-key "your-api-key")
'(wakatime-cli-path "your-python-path/Scripts/wakatime.exe"))
```
to `custom-set-variables` in `.spacemacs`.
