### ISSUE TITLE
how to uninstall spacemacs from OSX? 

### ISSUE THREAD

**Issue by buuug7** [syl20bnr/spacemacs#9461]
how to uninstall spacemacs from OSX, the startup time of emacs is growth more and more, it takes two minutes. emacs wasted much of my youth, it time to give it up and switch to aweome IDE.

**Comment by bmag** [comment]
just delete `~/.emacs.d`

**Comment by buuug7** [comment]
@bmag ok, it works

**Comment by dijonkitchen** [comment]
Seems like this has been asked a few times (e.g., #1349). Is it in the documentation somewhere?

**Comment by bmag** [comment]
Don't know if it's in the docs, but we can add it to the FAQ.

**Comment by d12frosted** [comment]
@dijonkitchen regarding uninstallation instructions - PRs are welcome.

Regarding installation instructions, `master` is too far behind :( If you think that something should be improved on the `develop` branch - PRs are welcome ;)

**Comment by dijonkitchen** [comment]
@d12frosted when is the `develop` branch going to be merged into `master` as stable?

**Comment by d12frosted** [comment]
@dijonkitchen I can't say the exact date, but soon™. @syl20bnr knows better.

**Comment by haxn8** [comment]
Paste this in your CLI
rm -fr ~/.emacs.d ~/.spacemacs

I got it from here:
https://www.reddit.com/r/spacemacs/comments/5f2o9h/how_do_you_uninstall_spacemacs_and_remove/

**Comment by jeroenvandijk** [comment]
If above doesn't work, also check the `~/.config/` dir for emacs entries
