### ISSUE TITLE
Two packages are not found (ess and haskell)

### ISSUE THREAD

**Issue by dschrempf** [syl20bnr/spacemacs#9464]
I am on the develop branch, commit 06301b22128dcb24eddae3374f5fb023d63524f3

When activating the ess layer, I get:
    --> installing package: ess-R-object-popup@ess... [1/2]
    Package ess-R-object-popup is unavailable. Is the package name misspelled?

When activating the haskell layer, I get:
    --> installing package: hlint-refactor@haskell... [2/2]
    Package hlint-refactor is unavailable. Is the package name misspelled?

Could it be that there is a problem on my side? Or are those packages no more available?
Thanks!

**Comment by francioshu** [comment]
Is the problem solved? I also encountered this problem.

**Comment by jeffhertzler** [comment]
MELPA just purged a ton of packages where the licenses weren't GPLv3 compatible. See: https://github.com/melpa/melpa/commit/cf92ce1a2bc92c73071d157e7e223982bbd3f818. Was having similar issues with the haskell layer and some of the themes in the megapack. Some are slowly being added back as the packages update their licenses.

**Comment by LouisAsh** [comment]
I also having this problem with `ess-R-object-popup`, which is slowing down initialization of Spacemacs.

**Comment by LouisAsh** [comment]
@dschrempf While a better solution to this does not show up, here is what I did to circumvent the problem. I simply included the package `ess-R-object-popup` in the list of excluded packages in my `.spacemacs` file:

`dotspacemacs-excluded-packages '(ess-R-object-popup)`

Although a dirty of way of handling it, it indeed make my initialization much faster sine now I don't have anything pending for installation every time I open Spacemacs.

**Comment by dschrempf** [comment]
Thank you. At the moment I deactivated the `ess` layer completely, but if I need it, I will come back to this solution.

I also saw that there is an issue about this at the GitHub repo of `ess-R-object-popul.el`: myuhe/ess-R-object-popup.el#3 but nobody seems to care about it, so maybe it is better to include the code here at spacemacs?

**Comment by LouisAsh** [comment]
@dschrempf Thanks for calling my attention to that ESS issue ticket. I will keep an eye on it (hopefully ESS author(s) are still working on it).

**Comment by htc502** [comment]
up for the same problem encountered. by the way, disabling this el will make r code autocompletion unavailable?
