### ISSUE TITLE
Copying from ansi-term/multi-term includes extra newlines.

### ISSUE THREAD

**Issue by pspencil** [syl20bnr/spacemacs#9465]
I am not sure if this is a problem of spacemacs/shell-mode/evil mode so I am posting here. 

When I am using terminal, if I were to copy some command output to another buffer, they would contain extra new line characters at the end of each "visual line". This behaviour changes with the width of the shell window (since that changes the number of lines).

Is there a fix for this?

**Comment by CeleritasCelery** [comment]
Does this happen with the stock Emacs?

**Comment by Ps-Pencil** [comment]
@CeleritasCelery I tried `emacs -q`. `M-w` works in shell buffer and no extra newlines are added. However, `M-w` does not copy at all in ansi-term. I believe the power to copy from ansi-term might come from other packages like evil.

**Comment by CeleritasCelery** [comment]
You can use `c-x c-j` to put ansi-term in line mode then you should be able to copy out with `m-w`. Then use `c-c c-k` to switch back to character mode.

**Comment by Ps-Pencil** [comment]
Yes this happens with stock emacs as well.
