### ISSUE TITLE
s in Visual mode works differently from Vim

### ISSUE THREAD

**Issue by Pastafarianist** [syl20bnr/spacemacs#9467]
#### Description :octocat:
`s` in Visual mode works differently from Vim.

#### Reproduction guide :beetle:
- Start Emacs
- Open any buffer
- Type some words, like `type some words`
- Place your cursor at the beginning of some word, like `some`
- Press `ves`

*Observed behaviour:* :eyes: :broken_heart:
Status bar says `s-`; the selection remains in place. Typing another character surrounds the selection with that character.

*Expected behaviour:* :heart: :smile:
The selected word should be removed and the mode should be switched to Insert, like in Vim. In Spacemacs, this can be achieved with the `c` command instead of `s`.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(purescript
 (haskell :variables haskell-enable-hindent-style "fundamental")
 yaml helm auto-completion
 (haskell :variables haskell-completion-backend 'company-ghci)
 emacs-lisp git markdown org)
```

---

I admit that surrounding the selection with a character might be something someone would need, and `c` and `s` are (completely?) equivalent in Visual mode. However, muscle memory from Vim is still there, and it's inconvenient that the defaults are different.

**Comment by bmag** [comment]
We use `evil-surround`, which mimics Vim's `surround` plugin. It does work differently than vanilla Vim, but that's intentional. You can try excluding the `evil-surround` package and see what happens.

**Comment by duianto** [comment]
This seems to be why it was decided to use `s` for surround:
https://github.com/emacs-evil/evil-surround/pull/48#issuecomment-67258416
