### ISSUE TITLE
Making helm able to add empty lines

### ISSUE THREAD

**Issue by Poetastrophe** [syl20bnr/spacemacs#9468]
I use spacemacs with evil-mode and according to this exchange [https://lists.gnu.org/archive/html/help-gnu-emacs/2015-01/msg00462.html](url) one should be able to search for empty lines using helm, by inserting a "empty value" through `C-RET` but I cannot seem to find how to insert the "empty value" as when I press the specified modifier shortcut I get `<C-return> is undefined`. How does one define an empty value to `C-RET?`

**Comment by bmag** [comment]
I don't understand the problem. Which Helm commands are we talking about? Precise repro steps would be appreciated.

**Comment by scrathat** [comment]
Works for me but only for commands using `completing-read`.
https://github.com/emacs-helm/helm/issues/700
