### ISSUE TITLE
Python autocompletion messes up indentation

### ISSUE THREAD

**Issue by lockie** [syl20bnr/spacemacs#9472]
#### Description :octocat:
Hello. Former vimer here, trying to switch to Spacemacs. I've been using [Supertab](https://github.com/ervandew/supertab) in Vim for years, and compared to it the default autocompletion for Python in Spacemacs is somewhat bizzare.

#### Reproduction guide :beetle:
- Start Emacs
- Open a python file
- Type the code:
```python
def test(): pass
def main():
    i = t
```
- When your cursor is at last letter 't', hit TAB

*Observed behaviour:* :eyes: :broken_heart:
- After first TAB hit, nothing happens.
- After second TAB hit, Spacemacs all of a sudden unindents the whole line.

*Expected behaviour:* :heart: :smile:
- After TAB hit
  1. if there is no possible completions, nothing should happen at all.
  2. if there is only one possible completion, it should be inserted into edit buffer.
  3. if there are several completion options, the list should be shown, and ideally, the first one should be inserted in edit buffer. Subsequent TAB hits should cycle through the list.
- Under no circumstances it should mess up with my indentaion (there are some difficulties in Python with that :sweat_smile:)

How do I acheive that? I don't even know where to start looking, or which emacs package is responsible.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp git
      (shell :variables shell-default-shell 'multi-term shell-default-position 'right)
      (syntax-checking :variables syntax-checking-enable-tooltips nil)
      version-control
      (c-c++ :variables c-c++-enable-clang-support t)
      python html
      (javascript :variables javascript-disable-tern-port-files nil)
      latex lua racket shell-scripts vimscript yaml semantic cscope imenu-list nginx
      (wakatime :variables wakatime-cli-path "~/.local/bin/wakatime")
      emoji colors)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by lockie** [comment]
I've been able to fix it with
```elisp
(add-hook 'python-mode-hook
    (lambda () (setq indent-line-function 'python-indent-line)))
```

**Comment by braham-snyder** [comment]
you might instead just want to set `tab-always-indent` to `t`

**Comment by lockie** [comment]
@braham-snyder nope, that just returns the default behavior.
