### ISSUE TITLE
Possible bug report

### ISSUE THREAD

**Issue by qm1900** [syl20bnr/spacemacs#9475]
I am coding a FORTRAN code with latest Spacemacs in F90 mode, and I directly copy a block of comments from `https://people.sc.fsu.edu/~jburkardt/f_src/jacobi_eigenvalue/jacobi_eigenvalue.f90` in Chrome
and paste to my codes.

The comments are as follows, `!*****************************************************************************80
!
!! JACOBI_EIGENVALUE carries out the Jacobi eigenvalue iteration.
!
!  Discussion:
!
!    This function computes the eigenvalues and eigenvectors of a
!    real symmetric matrix, using Rutishauser's modfications of the classical
!    Jacobi rotation method with threshold pivoting. 
!
!  Licensing:
!
!    This code is distributed under the GNU LGPL license.
!
!  Modified:
!
!    17 September 2013
!
!  Author:
!
!    FORTRAN90 version by John Burkardt
.........`

When I hit return at the end of any line of these comments, Spacemacs will not work anymore.

Platform: macOS 10.12

**Comment by CeleritasCelery** [comment]
Can you replicate this with stock emacs and f90 mode?
