### ISSUE TITLE
spacemacs/smart-closing-parenthesis closes more parenthesis than are actually opened

### ISSUE THREAD

**Issue by kassick** [syl20bnr/spacemacs#9477]
#### Description :octocat:
Closing a parenthesis right beside a question-mark, exclamation, space, #, among others, causes spacemacs to insert two closing parenthesis instead of one if dotspacemacs-smart-closing-parenthesis is non-nil

The issue does not occur with with dotspacemacs-smart-closing-parenthesis set to nil (default setting)

smart-closing-parenthesis itselt only inserts one parenthesis, but sp-up-exp ends up inserting another one before (insert ?\)) is called.

Tested with a clean spacemacs install, same issue.

#### Reproduction guide :beetle:
- Set dotspacemacs-smart-closing-parenthesis to t
- Start Emacs
- Open some text file (e.g. org-mode) that won't auto enable smartparens-mode
- start typing something such as

  this is some (test within parenthesis!

- Press ")" (closing parenthesis)

*Observed behaviour:* :eyes: :broken_heart:

two parenthesis are inserted and the resulting text is

```
  this is some (test within parenthesis)!)
```

*Expected behaviour:* :heart: :smile:

Exactly one parenthesis is inserted and the resulting text would be

```
  this is some (test within parenthesis!)
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript helm
            (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip 'manual)
            emacs-lisp git ranger html markdown org
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            (syntax-checking :variables syntax-checking-enable-by-default t)
            (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary t)
            ycmd python c-c   fsharp csharp java antlr graphviz
            (latex :variables latex-enable-folding t latex-enable-auto-fill nil)
            markdown pandoc pdf-tools shell-scripts semantic
            (ibuffer :variables ibuffer-group-buffers-by 'projects)
            themes-megapack theming kzk-visual-editing kzk-helm kzk-company)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
```

**Comment by duianto** [comment]
Confirmed on both the latest master and develop branches.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f8ecf0cb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
 emacs-lisp git haskell helm html markdown org treemacs spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by Miciah** [comment]
Does #11042 resolve the issue for you?

**Comment by kassick** [comment]
Yes, it seems like #11042 fixes the issue.
