### ISSUE TITLE
themes-megapack is missing 4 packages

### ISSUE THREAD

**Issue by DWShuo** [syl20bnr/spacemacs#9478]
Fresh install of themes megapack show 4 themes are missing 

Installing package: firebelly-theme@themes-megapack... [1/4]
Package firebelly-theme is unavailable. Is the package name misspelled?
--> installing package: niflheim-theme@themes-megapack... [2/4]
Package niflheim-theme is unavailable. Is the package name misspelled?
--> installing package: pastels-on-dark-theme@themes-megapack... [3/4]
Package pastels-on-dark-theme is unavailable. Is the package name misspelled?
--> installing package: tronesque-theme@themes-megapack... [4/4]
Package tronesque-theme is unavailable. Is the package name misspelled?

**Comment by duianto** [comment]
The package repository: https://melpa.org/
where packages are loaded from, has removed packages that don't have an up to date license.

There's a PR pending, for removing 3 of the themes mentioned above.
[Remove themes that were deleted from Melpa #9470](https://github.com/syl20bnr/spacemacs/pull/9470)
