### ISSUE TITLE
Project files list in select are the one of the previous project I worked on.

### ISSUE THREAD

**Issue by Electron-libre** [syl20bnr/spacemacs#9480]
#### Description :octocat:
When using `<SPACE >P l`  to or `<SPACE> P f` , the file list exposed in the selection buffer is the one of the previous project I worked on/selected.

Yet to be able to select a file from the current project/layer I have to hit `<SPACE> p l` once , ESC , then `<SPACE> p l` once again to get the current project file list.

#### Reproduction guide :beetle:
- Start Emacs
- `<SPACE> p l` to select a project and open in a new layer
- Select a file from the project file list
- `<SPACE> p l` to select a another project and open in a new layer

*Observed behaviour:* :eyes: :broken_heart:
The files in the project list to select are the one of the previous project i selected.

*Expected behaviour:* :heart: :smile:
The files in the project list should be the on of the project I just selected with `<SPACE> p l`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. df7af0ad)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 rust better-defaults emacs-lisp git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-tooltips nil ispell-dictionary "english")
 csv javascript nginx docker elixir elm html ruby ruby-on-rails
 (haskell :variables haskell-enable-hindent-style "chris-done" haskell-completion-backend 'ghc-mode)
 sql shell-scripts yaml themes-megapack
 (keyboard-layout :variables kl-layout 'bepo)
 erc ansible floobits)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
```

**Comment by 0robustus1** [comment]
I'm experiencing the same problem on Mac OS X with Emacs *25.2.1* and spacemacs *0.200.9* on release. I however updated my packages this morning.

I would also suggest that this is related to the helm implementation, after switching to ivy (just to try it out) i don't have the problem.

**Comment by Electron-libre** [comment]
You are right I switched to ivy and it works.
I think the issue has been ther fore 2 or 3 weeks, I was on 0.200.9. Then I switched to develop, but the issue still there in develop branch.
