### ISSUE TITLE
`fd` breaks indentation in ruby mode

### ISSUE THREAD

**Issue by ankitrg** [syl20bnr/spacemacs#9482]
#### Description :octocat:
`fd` breaks the indentation in ruby mode for paranthesis
<<DESCRIPTION OF THE PROBLEM>>

#### Reproduction guide :beetle:
- Start Emacs
- create a scratch file
- change to ruby mode
- type the following code in the observed section
- when cursor on the closing `(` use `fd`

*Observed behaviour:* :eyes: :broken_heart:
```
Method.call(
  )
```
*Expected behaviour:* :heart: :smile:
```
Method.call(
)
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml markdown javascript ruby react helm emacs-lisp git org syntax-checking version-control)
```

> NOTE: Also there is no method described to submit this from the evil mode C-x C-x didn't work, so copying this here

**Comment by CeleritasCelery** [comment]
Can confirm. When I exit insert state with `<ESC>` or calling `evil-escape` interactively I don't see the problem. I am not seeing this in other major modes so it looks like it has something specifically to do with ruby and typing the escape sequence.

**Comment by ankitsinghaniyaz** [comment]
Is there a way to fix this now?

**Comment by Miciah** [comment]
This issue looks like a duplicate of #5313 and #5261.  Does the suggested workaround (https://github.com/syl20bnr/spacemacs/issues/5261#issuecomment-189655480) resolve the issue for you?
```emacs-lisp
  (add-hook 'evil-insert-state-exit-hook 'indent-according-to-mode)
```
