### ISSUE TITLE
OCaml Layer:  Should be using flycheck for error checking

### ISSUE THREAD

**Issue by rgrinberg** [syl20bnr/spacemacs#9489]
The OCaml layer is using merlin's own error reporting ability. Which is inferior to what https://github.com/flycheck/flycheck-ocaml provides. spacemacs should switch to use this package instead.

**Comment by CeleritasCelery** [comment]
you should open a PR

**Comment by jpathy** [comment]
To enable flycheck-mode you need to uncomment the 2 lines in ocaml-packages. The rest of the setup is already in place. You do need to enable syntax-checking layer and enable flycheck in files(SPC t s). 

I guess by inferior merlin error reporting, you mean it doesn't report errors on-fly, rather on save.

**Comment by jeremyjh** [comment]
@jpathy I have syntax-checking enabled and use flycheck in many other layers. But un-commenting those package names in the ocaml layer does not make flycheck available. Instead I see this warning when Spacemacs starts:

```
            - package flycheck not initialized in layer ocaml, you may consider removing this
              package from the package list or use the :toggle keyword instead of a `when'
              form.      
```

Toggling syntax-checking does nothing.

**Comment by jpathy** [comment]
@jeremyjh The problem seems to be : 
if you have syntax-checking package ordered after ocaml, then 
https://github.com/syl20bnr/spacemacs/blob/3208cc94f2bf3ea448805f0d66b003b2b2574022/layers/%2Blang/ocaml/packages.el#L34
prevents it from evaluating the necessary defs. You can change the order and it will download `flycheck-ocaml` and load it.

No other package seems to be doing this, so i removed the test. Also it seems like adding a minor-mode to `flycheck-global-modes` doesn't work(auto enable on buffer). So i had to change to `(spacemacs/enable-flycheck 'tuareg-mode)` .

**Comment by jeremyjh** [comment]
@jpathy That was it - moving the syntax-checking earlier resolved it for me, thanks!

**Comment by CeleritasCelery** [comment]
Feel free to close this if you feel that your question has been answered.

**Comment by MarcusE1W** [comment]
Hi I am new to Sacemacs and am not quite sure about the result of the issue discussion. Is there an intention to updat the official ocaml layer or is the reccomendation to update some scripts manually ?

**Comment by MarcusE1W** [comment]
Short update. I have followed the above instructions and it works fine.

Is there an intention to make this the default function, or maybe with a toggle?

In the meantime, if there is a layer update, will that overwrite the manual changes?

**Comment by dagnachewa** [comment]
@jeremyjh I have this 
error on startup :init: Symbol’s value as variable is void: company-backends-merlin-mode
can you paste me your packages.el from the ocaml layer please

**Comment by jeremyjh** [comment]
@dagnachewa Its been awhile and I haven't been using OCaml but I think all I did was move the `syntax-checking` layer before the `ocaml` layer in my .spacemacs 
`dotspacemacs-configuration-layers` list

**Comment by designgeef** [comment]
> @dagnachewa Its been awhile and I haven't been using OCaml but I think all I did was move the `syntax-checking` layer before the `ocaml` layer in my .spacemacs
> `dotspacemacs-configuration-layers` list

That worked for me!

**Comment by Blaisorblade** [comment]
> Its been awhile and I haven't been using OCaml but I think all I did was move the `syntax-checking` layer before the `ocaml` layer in my .spacemacs

That helped! I didn't have `syntax-checking`, and I got these warnings (on `develop`). Enabling `syntax-checking` myself (before `ocaml`) avoids the warnings. Maybe there is still an issue to fix tho?

```
    - package flycheck not initialized in layer ocaml, you may consider removing this
      package from the package list or use the :toggle keyword instead of a `when'
      form.      
    - package flycheck-ocaml not initialized in layer ocaml, you may consider removing
      this package from the package list or use the :toggle keyword instead of a
      `when' form.      
```

Looking at @jpathy's [comment](https://github.com/syl20bnr/spacemacs/issues/9489#issuecomment-326817068) and at the [updated code](https://github.com/syl20bnr/spacemacs/blob/a3cac69fb4bb20cb854ce83451f25e44f5190464/layers/%2Blang/ocaml/packages.el#L12-L35), one could try making `ocaml- packages` conditional on `(configuration-layer/layer-used-p 'syntax-checking)`?
