### ISSUE TITLE
Racket Layer: Spacemacs crashing when running file in REPL

### ISSUE THREAD

**Issue by pvomelveny** [syl20bnr/spacemacs#9493]
#### Description :octocat:
Racket Layer, after calling racket-run, causes all spacemacs commands to stop functioning (or maybe all emacs functions) and keeps opening the racket file in new buffers until emacs crashes. Seems like it may be an issue with the company completion, but I'm not totally sure how to check that that's definitly the case.

#### Reproduction guide :beetle:
- Start Emacs
- Open a .rkt file with the racket layer
- Start the REPL and run the .rkt buffer [SPC m s b]
- Try and use any other SPC prefixed functions

*Observed behaviour:* :eyes: :broken_heart:
Once you call `racket-run` all commands stop working. Any you try result in the error `(wrong-type-argument integer-or-marker-p nil)`, and each time that appears a new buffer with the .rkt file opens up. 

*Expected behaviour:* :heart: :smile:
For the file to be run in the DrRacket buffer and then for commands to continue to work as normal.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy osx auto-completion better-defaults org git github version-control syntax-checking pandoc tmux colors themes-megapack c-c  
     (clojure :variables clojure-enable-fancify-symbols t)
     common-lisp emacs-lisp erlang go
     (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "johan-tibell")
     html idris java javascript latex markdown purescript
     (python :variables python-test-runner 'pytest)
     racket rust scala scheme swift yaml evil-cleverparens vim-empty-lines)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
Example Debugger output, not sure how much help this is. Other than the first line, the debug output isn't always the same stack, I cut it off after the first few lines because it was too long to upload with <C-c C-c>, but I can add the rest in an edit if it would be useful:
```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  move-overlay(#<overlay in no buffer> nil nil)
  #[nil "\302	\211#\207" [vim-empty-lines-overlay p move-overlay] 4]()
  ad-Advice-vertical-motion(#<subr vertical-motion> 4 nil)
  apply(ad-Advice-vertical-motion #<subr vertical-motion> (4 nil))
  vertical-motion(4 nil)
  (1  (vertical-motion (or max (buffer-size)) window))
  (save-restriction (widen) (narrow-to-region (min beg end) (if (and (not count-final-newline) (= 10 (char-before (max beg end)))) (1- (max beg end)) (max beg end))) (goto-char (point-min)) (1  (vertical-motion (or max (buffer-size)) window)))
  (save-excursion (save-restriction (widen) (narrow-to-region (min beg end) (if (and (not count-final-newline) (= 10 (char-before (max beg end)))) (1- (max beg end)) (max beg end))) (goto-char (point-min)) (1  (vertical-motion (or max (buffer-size)) window))))

...
```

**Comment by duianto** [comment]
It seems to be working on the `develop` branch for me.

I installed drracket 7.6.
Enabled the Spacemacs `racket` layer.
Restarted Spacemacs.
Created a new file: `example.rkt`
```racket
#lang slideshow
(define c (circle 10))
(define r (rectangle 10 20))
```
Tried to open the REPL: `SPC m '`
>racket--version: Searching for program: No such file or directory, Racket.exe

Tried adding the racket.exe directory path: `C:\Program Files\Racket`
to the Windows `PATH` environment variable and restarted Spacemacs.
But the same error message as above is shown.

Found the variable `racket-program` here: https://www.racket-mode.com/#Configure

Added the following to the `dotspacemacs/user-config` section:
```elisp
(setq racket-program "c:/Program Files/Racket/Racket.exe")
```
Restart Spacemacs.
Opened `example.rkt`
Opened the REPL: `SPC m '`
Switched back up to the `example.rkt` buffer: `SPC w k`
Ran the file: `SPC m s b`
The REPL inserted a new prompt in the REPL:
```
; On-demand, one-time instantiation of racket/gui/base.
example.rkt>
```
Switched back down to the `*Racket REPL*` buffer: `SPC w j`
Entered insert state and evaluated the `c` definition: `i` `c` `RET`
A circle was inserted.

Evaluated `r` `RET`
A rectangle was inserted.

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 884afe138)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion c-c++ command-log emacs-lisp git github
            (gnus :variables gnus-summary-thread-gathering-function 'gnus-gather-threads-by-subject)
            go helm imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors org pdf python racket
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>
