### ISSUE TITLE
How to update a package included by a layer?

### ISSUE THREAD

**Issue by pdilyard** [syl20bnr/spacemacs#9506]
The `elixir` layer includes the `elixir-mode` package: https://github.com/elixir-editors/emacs-elixir

There are several features that have been added (way back in January 2017) but I haven't seen them show up in spacemacs.

The latest tagged release on `emacs-elixir` is pretty old; there has been 40 commits to master since then.

Is there a way I can force spacemacs to use the master branch of this package instead of the stable version?

**Comment by pdilyard** [comment]
I tried to include `elixir-mode` in `dotspacemacs-additional-packages` but nothing changed

**Comment by sdwolf** [comment]
Try `M-x configuration-layer/update-packages`.

**Comment by pdilyard** [comment]
@sdwolf That did update over 100 packages, but unfortunately I'm still not seeing the changes from `emacs-elixir` master

**Comment by fiveNinePlusR** [comment]
If you want to absolutely make sure you can blow out the cache for the elixir-mode package or verify that the elixir mode is the correct version of 20170102.942 

the folder should be `~/.emacs.d/elpa/elixir-mode-20170102.942` if it's at the latest version. If you delete whatever is there, emacs will download the latest the next time you start.

**Comment by pdilyard** [comment]
Ah - looks like it is at the latest version, but the feature(s) I'm looking for don't seem to be there. My mistake.

**Comment by fiveNinePlusR** [comment]
That's odd. which features are not there?

**Comment by pdilyard** [comment]
Looks like they were all along - I was looking for some syntax highlighting changes, and they were there, but my theme did not customize the correct font face. I added this to my user-config function and I'm golden:

```elisp
  (custom-theme-set-faces
   'molokai
   '(font-lock-doc-face ((t (:foreground "#465457")))))
```
