### ISSUE TITLE
[Feature Request] Add evil-goggles package to spacemacs

### ISSUE THREAD

**Issue by fiveNinePlusR** [syl20bnr/spacemacs#9511]
The [evil goggles](https://github.com/edkolev/evil-goggles) package is an unobtrusive package to highlight your vim actions such as yank, cut, delete, etc....

When I heard about it I thought that it would be a gimmick but, after using it for months, now I am convinced that it's an essential package to have on as it just makes your actions more transparent and gives me a nice feeling that emacs/evil did what I wanted it to do.  It's a subtle nice thing that I would not want to be without. 

I have the beginnings of a layer here https://gist.github.com/fiveNinePlusR/73216d90d2562963ad0a311bd0578807 but it's not ready for prime time as the toggle doesn't work due to it not really being made for toggling as best I can tell. 

If there is interest from the maintainers I can turn this into a proper layer or add it directly to the spacemacs core.

**Comment by fiveNinePlusR** [comment]
also, the gif does not show it but using the diff faces with `(evil-goggles-use-diff-faces)` makes it much less obtrusive and is how I use it.

**Comment by agzam** [comment]
@fiveNinePlusR Although it is indeed an awesome feature, I personally would probably vote against of anything to be added to the core. Let this thing to be a layer on its own.
Spacemacs has reached maturity, adding more stuff to its core would potentially make things unstable. I really don't want to see huge population of experienced users migrating to `spacemacs-base` or even worse, building their own configs inspired by "once very stable" Spacemacs.

**Comment by CarlQLange** [comment]
I think this package would be great to add to core - I think it really fits into Spacemacs well. ¯\_(ツ)_/¯
