### ISSUE TITLE
Wrong Ruby version used during rspec-mode test invocation with Rbenv + ZSH

### ISSUE THREAD

**Issue by Dangeranger** [syl20bnr/spacemacs#9512]
#### Description :octocat:
When invoking rspec-verify-all from within any spec file using the keybinding CTRL c , ,, a instead of using the Ruby binary version specified in the .ruby-version located at the project root, rspec-mode is invoking rspec with the default system ruby instead.

#### Reproduction guide :beetle:
- Start Emacs
- Open a Ruby-on-Rails project with a .ruby-version
- Invoke tests with <kbd>M</kbd>+<kbd>x</kbd> `rspec-verify-all` OR <kbd>SPC</kbd>, <kbd>m</kbd>, <kbd>t</kbd>, <kbd>a</kbd>

*Observed behaviour:* :eyes: :broken_heart:

Instead of using the Ruby version installed using ruby-build and managed with Rbenv the rspec-mode uses the system installed default ruby as if the .ruby-version file didn't exist and no other Ruby versions were installed.

```
-*- mode: rspec-compilation; default-directory: "~/Dev/projects/project/" -*-
RSpec Compilation started at Tue Aug 29 14:23:10

bundle exec rspec --options /Users/username/Dev/projects/project/.rspec /Users/username/Dev/projects/project/spec/models/webdyn_sun_site_spec.rb:30
/Library/Ruby/Site/2.0.0/rubygems.rb:243:in `bin_path': can't find gem bundler (>= 0) (Gem::GemNotFoundException)
	from ./bin/bundle:3:in `<main>'

RSpec Compilation exited abnormally with code 1 at Tue Aug 29 14:23:11

```
*Expected behaviour:* :heart: :smile:

rspec-mode was expected to invoke rspec with the Ruby version installed via ruby-build at /Users/username/.rbenv/versions/2.2.3/bin/ruby.

*Additional Information:*  

Invoking `bin/rspec` or `rspec` from within in inferior shell such as `ansi-shell` uses the correct Ruby version as specified by the .ruby-version or RUBY_VERSION env variable.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asm auto-completion better-defaults clojure colors crystal csv dash deft docker elixir
     (elm :variables elm-format-command "elm-format-0.18" elm-format-on-save t elm-sort-imports-on-save t elm-reactor-port "8000" elm-reactor-address "127.0.0.1")
     emacs-lisp erlang games git github
     (haskell :variables haskell-completion-backend 'intero)
     html javascript markdown org osx
     (ruby :variables ruby-version-manager 'rbenv ruby-test-runner 'rspec)
     ruby-on-rails slack semantic
     (shell :variables shell-default-term-shell 'bottom shell-default-height 40 shell-default-term-shell "/usr/local/bin/zsh" shell-default-shell 'ansi-term)
     shell-scripts syntax-checking version-control
     wakatime
     xkcd yaml)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace :paw_prints:
```
-*- mode: rspec-compilation; default-directory: "~/Dev/projects/project/" -*-
RSpec Compilation started at Tue Aug 29 14:23:10

bundle exec rspec --options /Users/username/Dev/projects/project/.rspec /Users/username/Dev/projects/project/spec/models/webdyn_sun_site_spec.rb:30
/Library/Ruby/Site/2.0.0/rubygems.rb:243:in `bin_path': can't find gem bundler (>= 0) (Gem::GemNotFoundException)
	from ./bin/bundle:3:in `<main>'

RSpec Compilation exited abnormally with code 1 at Tue Aug 29 14:23:11
```

**Comment by Dangeranger** [comment]
M-x getenv PATH =>
/Users/username/.rbenv/bin:/Users/username/.rbenv/shims:..rest of path

The two entries for .rbenv are first and second place respectively.

M-x describe-variable exec-path =>

exec-path is a variable defined in ‘C source code’.
Its value is
("/Users/username/.rbenv/bin" "/Users/username/.rbenv/shims" ... rest of path)

Original value was 
("/Users/username/.rbenv/bin" "/Users/username/.rbenv/shims" ... rest of path)

  This variable may be risky if used as a file-local variable.

Documentation:
List of directories to search programs to run in subprocesses.
Each element is a string (directory name) or nil (try default directory).

By default the last element of this list is ‘exec-directory’. The
last element is not always used, for example in shell completion
(‘shell-dynamic-complete-command’).

You can customize this variable.

**Comment by asok** [comment]
I had the same issue yesterday. I'm using chruby on OSX. In my case I have `source ~/.profile` in `~/.bashrc`. There when I comment out the line `ssh-add -A` the bug disappears.

**Comment by Dangeranger** [comment]
### Found a fix, solution below:

## Solution: 

Within my `.zshrc` I had initialized `rbenv` with

```
# Within ~/.zshrc

# Setup rbenv shims, completion, and path
eval "$(rbenv init -)"
```

After moving this into my `~/.zshenv` instead, restarting my shell, and restarting Spacemacs, `rspec-mode` found the correct Ruby version managed by `rbenv` and invoked the tests as expected.

```
# Within ~/.zshenv

## Default PATH foundation
PATH=/usr/local/bin:/usr/local/sbin:...lots-more-dirs-here...$PATH;
export PATH

# Setup rbenv shims, completion, and path
eval "$(rbenv init -)"
```

Thanks for the idea of checking my shell config and setup files @asok.
