### ISSUE TITLE
No Gui?

### ISSUE THREAD

**Issue by cinjon** [syl20bnr/spacemacs#9515]
How do I open spacemacs in the terminal so that it doesn't open the GUI as well? I am trying to use it alongside screen and so I just want to have `emacs foo.py` open in the screen window rather than open a whole GUI outside of the screen.

**Comment by lsytj0413** [comment]
@cinjon 
use this command:
`emacs -nw foo.py`

**Comment by cinjon** [comment]
Awesome, thanks, that worked.
