### ISSUE TITLE
What is "Magit auto-complete"?

### ISSUE THREAD

**Issue by joehillen** [syl20bnr/spacemacs#9518]
The git layer docs seem to refer to a feature that might not exist anymore. https://github.com/syl20bnr/spacemacs/blob/develop/layers/+source-control/git/README.org#magit-auto-complete

It's not clear what this feature is and searching for "Magit auto-complete" in google just links to this docs.

I suspect that it's referring to [repository listing](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+source-control/git/README.org#repository-list) and if so, then the other section is redundant.

**Comment by CeleritasCelery** [comment]
Magit-autocomplete completes refs such as branches names and remotes
