### ISSUE TITLE
Strange behavior of `projectile-find-file`

### ISSUE THREAD

**Issue by bixuanzju** [syl20bnr/spacemacs#9527]
#### Description :octocat:
`projectile-find-file` list files that are ignored by version control

#### Reproduction guide :beetle:
- Start Emacs
- Go to any git-controlled project
- Visit a file that is ignored by .gitignore
- Invoke `projectile-find-file`

*Observed behaviour:* :eyes: :broken_heart:
The particular file appears in the list

*Expected behaviour:* :heart: :smile:
It should not appear, according to the manual of projectile.

One strange thing is that, if you never visit a file that is ignored, that file
will not appear when invoking the command. But once you visit that file, it will
appear all the time.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. e32acfbf)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-private-snippets-directory "~/dotfile/emacs/snippets/")
 emacs-lisp
 (git :variables git-magit-status-fullscreen t)
 (markdown :variables markdown-live-preview-engine 'vmd)
 org
 (shell :variables shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-tooltips nil syntax-checking-use-original-bitmaps t)
 version-control osx idris rust
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 (haskell :variables haskell-completion-backend 'dante)
 latex bibtex ocaml lua sml yaml html agda csv coq ruby java racket python evil-commentary parinfer)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by CeleritasCelery** [comment]
You should report this upstream at projectile
