### ISSUE TITLE
Org mode gnuplot missing?

### ISSUE THREAD

**Issue by DWShuo** [syl20bnr/spacemacs#9530]
Is gnuplot a separate install? when i try to use gnuplot it says " Searching for program no such file or directory: gnuplot", the org layer documentation was kinda vague.
EDIT: when i run gnuplot-version its show gnuplot-mode 0.7 beta so it seems like its installed but not found by spacemacs?

**Comment by DWShuo** [comment]
running sudo apt install gnuplot or sudo pacman -S gnuplot fixed the issue

**Comment by yyao93** [comment]
Where did you run the sudo* command? In the terminal or somewhere in spacemacs? Thanks!

**Comment by DWShuo** [comment]
@yyao93 in terminal
