### ISSUE TITLE
Possible bug: errors in previewing LaTeX files ("wrong type argument: arrayp, nil" or "wrong type argument: number-or-marker-p, nil")

### ISSUE THREAD

**Issue by LouisAsh** [syl20bnr/spacemacs#9532]
#### Description
I can't preview LaTeX documents (i.e. to see in PDF format inside one of Spacemac's  buffer windows). Two different error messages are displayed depending on whether I choose to cache preambules or not.

More specifically, with the most recent version of Spacemacs, under Windows 10 64bits, I am trying to preview entire LaTeX documents in a PDF that resides in one of the Spacemac's  buffers. However, when I try to preview LaTeX files, if say yes to the question "Cache preambule?", then I get the error:

`"error in process sentinel: wrong type argument: arrayp, nil"`

If I say no to the question "Cache preambule", then I get the error:

`"error in process sentinel: wrong type argument: number-or-marker-p, nil"`

#### Reproduction guide
- Be sure to have the LaTeX layer "latex" properly installed.
- Start Emacs
- Open a .tex file via SPC f t.
- Try to preview the full document with SPC m p d.
- Type "y" when asked "Cache preambule? (y or n)"
- The following error shows up: `"error in process sentinel: wrong type argument: arrayp, nil"`
- Now, reopen Spacemacs, repeat all the above, with the exception of typing "no" when asked "Cahce preambule? (y or n)".
- The following error shows up: `"error in process sentinel: wrong type argument: number-or-marker-p, nil, nil"`
- All the above happens also if I try to preview the buffer with with SPC m p b.

*Observed behaviour:*
No previews of .tex files in PDF format are displayed. Instead there is one of the following error messages in the bottom console: `"error in process sentinel: wrong type argument: arrayp, nil"` or `"error in process sentinel: wrong type argument: number-or-marker-p, nil, nil"`, depending on whether I choose to cache the preambules or not.

*Expected behaviour:*
I expect to have my .tex file previewed in a Spacemacs window.

#### System Info
- OS: windows-nt
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm auto-completion better-defaults emacs-lisp spell-checking syntax-checking ess ipython-notebook latex)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  signal(wrong-type-argument (arrayp nil))
  preview-reraise-error(#<process Preview-PDF2DSC>)
  preview-pdf2dsc-sentinel(#<process Preview-PDF2DSC> "Preview-PDF2DSC" t)
  (lambda (process command) (preview-pdf2dsc-sentinel process command t))(#<process Preview-PDF2DSC> "Preview-PDF2DSC")
  TeX-command-sentinel(#<process Preview-PDF2DSC> "finished\n")

**Comment by smile13241324** [comment]
Well the first thing would be to edit your issue report to match the official issue form.

You can do so within spacemacs with `SPC h d I` I think. In there you should add all the information asked from you in the template and move this into your existing issue.

In addition please add a stacktrace to the issue template. You can make one by activating `debug-on-error` and run the failing command again.

I am sure somebody will then find the time to have a look into this.

**Comment by LouisAsh** [comment]
@smile13241324 Thanks for the reply and sorry for not having done that in the first place. I fully edited the issue description above. Does it conform to what is expected now, in order for this bub to be better handled?

**Comment by smile13241324** [comment]
@LouisAsh yep, now its pretty fine 👍

**Comment by smile13241324** [comment]
@LouisAsh Finally found some time to have a look at your issue. I have fetched below default latex file from wikipedia and tried to generate a preview on my linux PC on develop.

This worked pretty fine though. Would you mind checking whether you are able to preview the document with spacemacs on the develop branch?

If this doesn't work please post the preview ghostscript output which you can see with `C-c C-l`.

```
\documentclass{article}
\usepackage{amsmath}
\title{\LaTeX}

\begin{document}
\maketitle
\LaTeX{} is a document preparation system for the \TeX{} typesetting program. It
offers programmable desktop publishing features and extensive facilities for
automating most aspects of typesetting and desktop publishing, including
numbering and cross-referencing, tables and figures, page layout,
bibliographies, and much more. \LaTeX{} was originally written in 1984 by Leslie
Lamport and has become the dominant method for using \TeX; few people write in
plain \TeX{} anymore. The current version is \LaTeXe.

% This is a comment, not shown in final output. The following shows typesetting
% power of LaTeX:
\begin{align}
  E_0 &= mc^2 \\
  E &= \frac{mc^2}{\sqrt{1-\frac{v^2}{c^2}}}
\end{align}
\end{document}
```
