### ISSUE TITLE
For certain files I always have to run `editorconfig-apply` — not sure why

### ISSUE THREAD

**Issue by terrycloth** [syl20bnr/spacemacs#9533]
#### Description :octocat:
When working on a file that does not belong to a project with its own .editorconfig file, EditorConfig Mode sometimes does not apply the default `.editorconfig` settings from my home directory to the current buffer, unless or until I run `editorconfig-apply`.

#### Reproduction guide :beetle:

I have a default `.editorconfig` file in my home directory, but most of my data is on a separate hard drive mounted under `/mnt/`. So I symlinked to my home .editorconfig file in `/mnt/` _and_ `/`, so that EditorConfig could always find my defaults if the current project doesn't include its own configuration.

I have the `editorconfig` command in my system `$PATH`, compiled to `~/.local/` from the EditorConfig C Core repository. I have added `editorconfig` to the `dotspacemacs-additional-packages` block in my Spacemacs dotfile. I also added `(editorconfig-mode t)` to my `dotspacemacs/user-config` block.

Even when EditorConfig Mode doesn't work as it should, I do still see "EditorConfig" in the modeline. And `editorconfig-find-current-editorconfig` correctly finds (the symlink to) my home `.editorconfig` file. However, `editorconfig-display-current-properties` reports "Properties are not applied to current buffer yet." If I manually run `editorconfig-apply`, then suddenly everything works the way it's supposed to.

...This is not a proper reproduction guide because I can't tell what exactly triggers the problem. Files in certain directories always have this issue, 100% of the time, and others never have this issue. I'm not sure what the difference is. I keep thinking the problem directories don't have any `.editorconfig` file anywhere in its ancestor directories, but they always do when I check. I created that symlink at `/.editorconfig` just to be safe, but it hasn't helped.

#### System Info :computer:

- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- EditorConfig C Core 0.12.1 (compiled from source repo to `~/.local/bin/editorconfig`)
- EditorConfig Mode `editorconfig-20170802.238` (installed with `package-install` Emacs command)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers: `(html vimscript javascript shell-scripts markdown helm emacs-lisp)`
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:

Output from `*Messages*` when I launch Emacs, and open one of the files which consistently does _not_ automatically load my home EditorConfig settings. Doesn't seem like there's anything pertinent here...

```
Loading /usr/share/emacs/site-lisp/site-start.d/cmake-init.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/desktop-entry-mode-init.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/git-init.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/mercurial-site-start.el (source)...done
Loading /usr/share/emacs/site-lisp/site-start.d/rpmdev-init.el (source)...done
Loading /home/terrycloth/.emacs.d/core/core-load-paths.el (source)...done
Loading /home/terrycloth/.spacemacs...
Loading linum...done
Loading avoid...done
Loading paren...done
Loading xt-mouse...done
Loading /home/terrycloth/.spacemacs...done
Setting the font...
PNG warning: Interlace handling should be turned on when using png_read_image
Open the quickhelp.
Loading /home/terrycloth/.emacs.d/layers/+lang/html/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+lang/vimscript/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+lang/javascript/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+lang/shell-scripts/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+lang/markdown/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+completion/helm/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+lang/emacs-lisp/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+distributions/spacemacs/layers.el (source)...
Loading /home/terrycloth/.emacs.d/layers/+distributions/spacemacs-base/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-completion/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-layouts/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-editing/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-editing-visual/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-evil/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-language/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-misc/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-ui/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-ui-visual/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-org/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+distributions/spacemacs/layers.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+distributions/spacemacs-bootstrap/packages.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+distributions/spacemacs-bootstrap/funcs.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-ui-visual/funcs.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-evil/funcs.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-editing/funcs.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-layouts/funcs.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-completion/funcs.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+distributions/spacemacs-base/funcs.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+lang/html/funcs.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+lang/javascript/funcs.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+lang/shell-scripts/funcs.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+lang/markdown/funcs.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+completion/helm/funcs.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+lang/emacs-lisp/funcs.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+distributions/spacemacs-bootstrap/config.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-ui-visual/config.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-layouts/config.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+spacemacs/spacemacs-completion/config.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+distributions/spacemacs-base/config.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+lang/html/config.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+lang/vimscript/config.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+lang/javascript/config.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+lang/shell-scripts/config.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+lang/markdown/config.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+lang/emacs-lisp/config.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/auto-layer.el (source)...done
Loading /home/terrycloth/.emacs.d/layers/+distributions/spacemacs-base/keybindings.el (source)...done
Loading /home/terrycloth/.emacs.d/.cache/spacemacs-buffer.el (source)...done
Starting new Ispell process /usr/bin/hunspell with default dictionary...
Spacemacs is ready.
Loading /home/terrycloth/.emacs.d/.cache/recentf...done
Open the quickhelp.
Skipping check for new version (reason: dotfile)
Unable to load color "Transparent" [2 times]
Auto-evilification could not remap these functions in map `edebug-mode-map`:
   - `edebug-Go-nonstop-mode` originally mapped on `G`
Quit
```

**Comment by aroig** [comment]
Most probably this is caused by some hook that runs later than the editorconfig-apply hook overrides the settings.

Note that since editorconfig/editorconfig-emacs@99bb6882d8ac708a066a9977cc4fa23f86c6b8f6 the editorconfig hook runs earlier, so it is more likely that its settings are overriden by an other hook or file local config.

**Comment by lawrsp** [comment]
Is there solution for this ? I also have this problem
