### ISSUE TITLE
Spacemacs close unexpected

### ISSUE THREAD

**Issue by nuhakan** [syl20bnr/spacemacs#9534]
#### Description :octocat:
Spacemacs with a split-window. C-x 3
C-x C-f **|close|** 

#### Reproduction guide :beetle:
- Start Emacs
- C-x C-f (search file)
- C-x 3
- C-x C-f (search file)
- I have 2 Files
- I work... 
- C-x C-f (closed)

*Observed behaviour:* :eyes: :broken_heart:
Normally work i with .py, .html and .txt

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(html python markdown helm auto-completion emacs-lisp)
```
- System configuration features: GPM DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB

In console:

> Fatal error 11: Segmentation fault
Backtrace:
emacs[0x4af092]
emacs[0x497109]
emacs[0x4adf7e]
emacs[0x4ae183]
emacs[0x4ae1ef]
/lib/libpthread.so.0(+0x11910)[0x7f576b56c910]
emacs[0x480100]
emacs[0x48431a]
emacs[0x40e219]
emacs[0x40f89e]
emacs[0x410ed8]
emacs[0x4367a4]
emacs[0x4a0aeb]
emacs[0x4a318a]
emacs[0x4a4d46]
emacs[0x506a42]
emacs[0x49753c]
emacs[0x5069e3]
emacs[0x4974a0]
emacs[0x49b742]
emacs[0x4c29df]
emacs[0x4c313f]
emacs[0x5081ed]
emacs[0x53aa83]
emacs[0x50808b]
emacs[0x53aa83]
emacs[0x50808b]
emacs[0x5093b0]
emacs[0x508179]
emacs[0x53aa83]
emacs[0x50808b]
emacs[0x5093b0]
emacs[0x508179]
emacs[0x53aa83]
emacs[0x50808b]
emacs[0x53aa83]
emacs[0x507170]
emacs[0x5074ca]
emacs[0x50a29d]
emacs[0x5076a1]
emacs[0x507e25]
...
Segmentation fault (core dumped)
[user@Computer ~]$

**Comment by sdwolf** [comment]
Please use the guide below debug your problem:
https://github.com/syl20bnr/spacemacs/wiki/Debugging#debugging-segmentation-faults-with-gdb

Also, I have a feeling this is a problem that's been solved on emacs master, so you could try installing from source directly and try to reproduce.
