### ISSUE TITLE
Restoring programming language interpreters together with Spacemacs Layouts

### ISSUE THREAD

**Issue by LouisAsh** [syl20bnr/spacemacs#9538]
Here is what I would like to have in Spacemacs. Whenever I am working with R (using ESS) or IPython and I close Supermacs, next time I open it the layout is restored and the .r and .py scripts are correctly opened and in the correct places. However, the R and IPython interpreters are gone. They got replaced by the "scratch" buffer and it forces me to re-open interpreters every time.

Would it be possible to configure Spacemacs such that it can be able to also restore (I mean, automatically open; nothing fancier than that) R and IPython interpreters? Similar to what package Workgroups2 can do (https://github.com/pashinin/workgroups2/issues/8).

**Comment by CeleritasCelery** [comment]
> Would it be possible to configure Spacemacs such that it can be able to also restore R and IPython interpreters

of course, but someone would need to create the code and open a PR.
