### ISSUE TITLE
configuration-layer/get-elpa-package-install-directory returns nil on packages installed system-wide

### ISSUE THREAD

**Issue by peterhoeg** [syl20bnr/spacemacs#9551]
#### Description :octocat:
haskell-snippets breaks yasnippet loading if haskell-snippets is installed system-wide as 

```el
(configuration-layer/get-elpa-package-install-directory 'haskell-snippets)
```

returns ```nil```

#### Reproduction guide :beetle:
- Install haskell-snippets system-wide
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:

- Emacs will then try to load ```snippets``` in the current directory as the overridden haskell-snippets-dir is nil and blow up since the directory cannot be found

Specifically this line: https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/haskell/packages.el#L254

*Expected behaviour:* :heart: :smile:

- Emacs not to blow up!

I have tried simply removing the overridden ```haskell-snippets-dir``` and things seem to work fine.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: peter (rev. 126c53db)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((auto-completion :variables auto-completion-complete-with-key-sequence "jk" auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete)
 (dash :variables helm-dash-docset-newpath
       (expand-file-name "~/.local/share/Zeal/Zeal/docsets"))
 evil-commentary
 (finance :variables ledger-use-iso-dates t)
 graphviz ivy nlinum
 (mu4e :variables mu4e-async nil mu4e-accounts-list nil mu4e-mu-home "~/.cache/mu" mu4e-maildir "~/.cache/mail" mu4e-view-prefer-html t mu4e-view-show-images t mu4e-view-show-addresses t mu4e-headers-include-related t mu4e-headers-skip-duplicates t mu4e-change-filenames-when-moving t mu4e-update-internal 60 mu4e-html2text-command
       (expand-file-name "~/.local/bin/dump_html.sh"))
 pandoc pdf-tools
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (git :variables git-magit-status-fullscreen t)
 (spell-checking :variables enable-flyspell-auto-completion nil ispell-program-name "/run/current-system/sw/bin/aspell" ispell-really-aspell t spell-checking-enable-auto-dictionary nil)
 version-control ansible terraform c-c++
 (elm :variables elm-format-command "elm-format-0.18" elm-format-on-save t elm-sort-imports-on-save t)
 emacs-lisp ess
 (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "fundamental" haskell-process-type 'stack-ghci haskell-stylish-on-save t)
 (java :variables eclimd-autostart t)
 javascript nixos
 (php :variables c-basic-offset 2)
 (python :variables python-enable-yapf-format-on-save t)
 (ruby :variables ruby-version-manager nil ruby-test-runner 'ruby-test)
 salesforce shell-scripts sql typescript vimscript windows-scripts ruby-on-rails gtags syntax-checking csv html markdown
 (org :variables org-export-backends
      '(ascii html icalendar latex md)
      org-enable-reveal-js-support t)
 speed-reading vagrant
 (speartail :variables speartail-auto-save-interval nil)
 nix peter)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by Rotaerk** [comment]
I don't believe I have haskell-snippets installed system-wide, but I am facing a problem where every time I start emacs, it re-extracts yasnippet, and then deletes it.  Is this the same issue?

It does appear to be due to that (configuration-layer/get-elpa-package-install-directory 'haskell-snippets) call returning nil.  However, I can't simply remove the override; I get an error indicating that haskell-snippets-dir is void, and spacemacs fails to load.  To correct _that_ I can explicitly set haskell-snippets-dir to the directory of my choice in .spacemacs, but simply setting it to ~/ doesn't resolve the problem (it goes back to the original behavior of extracting and then deleting yasnippet).

**Comment by peterhoeg** [comment]
This issue really isn't just about ```haskell-snippets``` as it can easily be replicated with any other package.

```configuration-layer/get-elpa-package-install-directory``` simply ignores packages installed system-wide.

```
(configuration-layer/get-elpa-package-install-directory 'cmake-mode)
"/home/peter/.emacs.d/elpa/25.2.1/cmake-mode-20160928.505/"
```
vs
```
(configuration-layer/get-elpa-package-install-directory 'haskell-snippets)
nil
```
