### ISSUE TITLE
Spacemacs freezes immediately in GUI mode

### ISSUE THREAD

**Issue by TrakJohnson** [syl20bnr/spacemacs#9554]
#### Description :octocat:
Spacemacs freezes immediately after being started in GUI mode. 

#### Reproduction guide :beetle:
- Fresh install
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
- spacemacs loads the background color and then freezes
![image](https://user-images.githubusercontent.com/9513815/30176485-e3117232-9402-11e7-9dae-0f845073d675.png)

*Expected behaviour:* :heart: :smile:
Spacemacs doesn't freeze

*System info*
Windows 10 1703 64-bit
Spacemacs master branch 
Emacs 25.2 64-bit

#### Backtrace :paw_prints:
Can't get anything... is there a logfile somewhere ?

---

I've tried the proposed [solution in the FAQ, ](https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#why-is-spacemacs-hanging-on-startup) with no success. 

  - Emacs on its own works fine in GUI mode. 
  - Spacemancs works fine on the command line (`emacs --no-window`)

Is there anywhere I could get logfiles to get more info ?

**Comment by CeleritasCelery** [comment]
Does stock Emacs freeze in GUI mode?

**Comment by TrakJohnson** [comment]
@CeleritasCelery No, stock emacs works fine in GUI mode

**Comment by CeleritasCelery** [comment]
take a look at #4730 and see if some of the suggestions there help. specifically,   `dotspacemacs-mode-line-unicode-symbols nil`

**Comment by Alexander-Miller** [comment]
Can windows send a SIGUSR2 to emacs? That will break the current elisp loop and make emacs show you a backtrace of what its been doing.

**Comment by syl20bnr** [comment]
Check your bash/shell profiles to see if you something that could block Emacs.

**Comment by TrakJohnson** [comment]
@Alexander-Miller I did some research and it seems that sadly windows doesn't have an equivalent for this kill signal

@syl20bnr I'm confused, are there shell profiles on windows too ? I'm using the windows command line, not bash.

**Comment by CeleritasCelery** [comment]
try reinstalling (even in a separate directory) using `spacemacs-base` and see if the issue persists.

**Comment by TrakJohnson** [comment]
@CeleritasCelery Thanks ! I reinstalled in a seperate directory, entered no-window-mode and selected spacemacs-base, that seems to have solved it. Is there a way to install the missing packages - maybe a list so that I can install them one by one (if that's feasible) and see if the problem gets reproduced ?

**Comment by CeleritasCelery** [comment]
You can find a list of missing layers [here](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bdistributions/spacemacs/layers.el). That should allow you to bifurcate where the problem lies.

**Comment by TrakJohnson** [comment]
@CeleritasCelery Is there anywhere specific I should put these ? I tried in `dotspacemacs-configuration-layers` in `.spacemacs` but I get `Unknown layer neotree declared in dotfile.`

**Comment by CeleritasCelery** [comment]
Hmm. You may need to add them to `configuration-layer/declare-layers`. Not sure where though. Seems like there should be an official way to do this. You could also switch distributions to `spacemacs` but comment out all the layers and add them back in slowly.

**Comment by TrakJohnson** [comment]
@CeleritasCelery So finally I reinstalled the full spacemacs, and it mysteriously works now. If I find more clues for reproducing it I'll post them here, but for now I think this issue can be closed. Thanks for the help !
