### ISSUE TITLE
Going down/up logical lines when line wrapping is enabled

### ISSUE THREAD

**Issue by andrewSteer** [syl20bnr/spacemacs#9557]
One of my main purposes with Emacs and now Spacemacs is to edit latex files. However, I am not being able to get a basic functionality working. I have line-wrapping enabled, which is of course a sensible necessary thing when working with text. The problem is that, then, there are logical lines and numerical lines.

And while I would obviously want to have a way to go down/up logical lines, the arrow-keys or j/k keys only jump to previous/next numerical line. Obviously, the natural thing to change that would be to set `dotspacemacs-visual-line-move-text t`. Which I did. To my surprise, that did not change anything. I also tried:

```
  (add-hook 'text-mode-hook 'turn-on-visual-line-mode)
  (add-hook 'text-mode-hook 'spacemacs/toggle-visual-line-navigation-on)
```

Still nothing happens. I don't get what am I doing wrong. I found plenty posts online about this issue, but rather old. So I imagine that such a basic thing is now solved, but I could not find the solution. Without being able to move wrapped lines down/up instead of just going to previous/next numerical lines, I don't how one could use Supermacs to write pieces in latex.

If needed, I could provide more technical details like what I do have in my `.spacemacs`, etc. Thanks for any help!

**Comment by braham-snyder** [comment]
press `SPC h f` to search the Spacemacs FAQ, which answers this question

**Comment by andrewSteer** [comment]
@braham-snyder If you are talking about this:

```
  ;; Make evil-mode up/down operate in screen lines instead of logical lines
  (define-key evil-motion-state-map "j" 'evil-next-visual-line)
  (define-key evil-motion-state-map "k" 'evil-previous-visual-line)
  ;; Also in visual mode
  (define-key evil-visual-state-map "j" 'evil-next-visual-line)
  (define-key evil-visual-state-map "k" 'evil-previous-visual-line)
```

It does not work. Cursor still jumps from numbered line to numbered line. It does not go through visible lines.

**Comment by braham-snyder** [comment]
That's odd -- unless `SPC h d k j` from normal state does not show `evil-next-visual-line`, I'm not sure what the issue is.

You might try to `edebug` (or `debug` if you like it better) `evil-next-visual-line` if you haven't already.

**Comment by andrewSteer** [comment]
@braham-snyder Hmm, `SPC h d k j` shows `evil-next-line &optional COUNT`, so no `evil-next-visual-line`. But this is also odd since, as I described, I have `otspacemacs-visual-line-move-text t`.

**Comment by Somelauw** [comment]
I don't know from the top of my head, but I think `dotspacemacs-visual-line-move-text` changes your J and K keys to move text.
Instead you can use the new [evil-respect-visual-line-mode](https://github.com/emacs-evil/evil/pull/902), but the remappings you posted above should also do the job.
Check *messages* that you don't have an error somewhere that is preventing that code from being executed.

**Comment by andrewSteer** [comment]
@Somelauw I can't migrate to the developer version right now, but indeed that link pointed me in the right direction. Here are the keybindins that worked for me:

```
  (define-key evil-normal-state-map (kbd "<down>") 'evil-next-visual-line)
  (define-key evil-normal-state-map (kbd "<up>") 'evil-previous-visual-line)
```
