### ISSUE TITLE
org-projectile :config: Symbol's function definition is void: org-projectile:per-repo

### ISSUE THREAD

**Issue by miraclemore** [syl20bnr/spacemacs#9560]
#### Description :octocat:
Error (use-package): org-projectile :config: Symbol's function definition is void: org-projectile:per-repo
I already set dotspacemacs-elpa-https to nil by reading FAQ

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
In the error buffer, it will show
Error (use-package): org-projectile :config: Symbol's function definition is void: org-projectile:per-repo

*Expected behaviour:* :heart: :smile:
No error when we start Emacs

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion better-defaults emacs-lisp git markdown org spell-checking syntax-checking)
```

#### Backtrace :paw_prints:
```
```

**Comment by miraclemore** [comment]
After I restart emacs, the symptom is disappear. I will keep to monitor that if I reproduce the issue.

**Comment by IvanMalison** [comment]
See all the issues in https://github.com/syl20bnr/spacemacs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20org-projectile%3Aper-repo

This has to do with refactoring in org-projectile
