### ISSUE TITLE
This buffer can't use 'imenu-default-create-function 

### ISSUE THREAD

**Issue by miraclemore** [syl20bnr/spacemacs#9561]
#### Description :octocat:
Imeu can't work on asm-mode

#### Reproduction guide :beetle:
- Start Emacs
- Open asm files in linux kernel, for instance, head.S

*Observed behaviour:* :eyes: :broken_heart:
This buffer can't use 'imenu-default-create-function 

*Expected behaviour:* :heart: :smile:
imenu(SPC s j) can work on those buffers

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion better-defaults colors emacs-lisp git markdown org asm c-c   gtags python spell-checking syntax-checking)
```
![screenshot from 2017-09-08 18-16-03](https://user-images.githubusercontent.com/3292065/30207530-70f349e4-94c2-11e7-837c-4cfc66354783.png)

#### Backtrace :paw_prints:
```
```

**Comment by miraclemore** [comment]
Is there anyone can help that ?

**Comment by bmag** [comment]
Looks to me that `asm-mode` doesn't have Imenu support, and that is an upstream issue (`asm-mode` is built-in Emacs). Note that `nasm-mode` does support Imenu, but I don't know what's the difference between them is.
