### ISSUE TITLE
Rainbow-mode does not work in web-mode.

### ISSUE THREAD

**Issue by magneticrose** [syl20bnr/spacemacs#9562]
Rainbow-mode does not work in web-mode.

I have enabled rainbow-mode with SPC t C c, but it works regardless of web-mode.

The hex color and the rgb color are expressed even in the inactive state.

It does not recognize html code such as black, red, and rgba transparency is not applicable.

The transparency is not applied even if it is tested in css mode.

Looking at rainbow-mode.el, the rgba value seems to be parsed.

That part is like the snapshot below.
<img width="206" alt="web-mode html file" src="https://user-images.githubusercontent.com/3222022/30210968-e43ff282-94d9-11e7-80c3-72bcc64c02df.png">
web-mode can't show html code color.

<img width="230" alt="css-mode css file" src="https://user-images.githubusercontent.com/3222022/30211047-46de7f76-94da-11e7-8b43-5cc95cbca2be.png">
css-mode can't show transparency in rgba color

**Comment by CeleritasCelery** [comment]
You should report this upstream at rainbow-mode

**Comment by grauschnabel** [comment]
the problem seems more to be that emacs font-lock does not have a alpha channel.
So the alpha must be calculated into the r g b values by using the current background color, which is not implemented in rainbow mode.
