### ISSUE TITLE
tramp-methods is void!

### ISSUE THREAD

**Issue by magthe** [syl20bnr/spacemacs#9563]
#### Description :octocat:
Can't open files in a project using 'SPC p f'.

#### Reproduction guide :beetle:
- Start Emacs
- Jump to a project using 'SPC p p', open the project folder using 'Ctrl-d'
- Try to open a file using 'SPC p f'

*Observed behaviour:* :eyes: :broken_heart:
Error "Symbol's value as variable is void: tramp-methods"

*Expected behaviour:* :heart: :smile:
A dialogue letting me search for a file and opening it.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: c-c++-add-irony (rev. 95afcae6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 dash evil-commentary evil-snipe git gtags helm mu4e syntax-checking vim-powerline
 (c-c++ :variables c-c++-enable-clang-support t c-c++-enable-irony-support t)
 clojure emacs-lisp python
 (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "johan-tibell")
 html latex markdown org pandoc yaml archlinux clipboard-fix)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:

Not relevant.

**Comment by magthe** [comment]
I should add that yes, I have tested this on a clean dev branch, i.e. don't be confused by the mention of `c-c++-enable-irony-support`.

**Comment by wizmer** [comment]
I've tried reproducing it but can't. 
Are you trying to access the project through ssh ?

**Comment by magthe** [comment]
No, all projects are local, no remote access at all.

I still get this on my system. I should add that it's only when I use `SPC p f` from a dired buffer. If I open a file in the project I can use `SPC p f` when in that file, if I close it, or just switch back to dired, I get the error again.

**Comment by sandos** [comment]
I can attest that I am seeing the exact same behaviour. After selecting a git project, (dired) doing SPC p f gives the tramp-methods error message. I started using spacemacs today so it is a clean install. Doing SPC p f from *scratch* works.

**Comment by rhruiz** [comment]
Mine started showing this behaviour after upgrading packages today.  Rolling back the updates fixed the problem. Is there any way that I can obtain the list of packages/versions updated to help finding the problem?

**Comment by rhruiz** [comment]
Just updated the packages again today and the issue is gone 🎉

**Comment by phenix-factory** [comment]
I have this problem for time to time.
I nuked Elpa, but it come back, i just wait a bit and the problem is gone. I really dont understand, some background process fill tramp-method ?

**Comment by kirill-gerasimenko** [comment]
I have the same issue on Windows 10 after updating packages today.

**Comment by magthe** [comment]
It's a constant for me by now. I update packages daily and have had this behaviour since the creation of this issue 😢

**Comment by rhruiz** [comment]
Seeing suggestions for other issues, adding

`(require 'tramp)`

to `dotspacemacs/user-config` seems to fix the issue

**Comment by phenix-factory** [comment]
> Seeing suggestions for other issues, adding
> 
> (require 'tramp)
> 
> to dotspacemacs/user-config seems to fix the issue

Isn't Spacemacs Jobs to initialize Tramp ?

**Comment by giodamelio** [comment]
I'm getting the same issue on the latest develop (a363f85d).

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript clojure rust python racket markdown asciidoc html common-lisp elixir lua sql shell-scripts terraform elm helm auto-completion better-defaults emacs-lisp git dash syntax-checking parinfer
            (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t))
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by magthe** [comment]
There seems to be some commonality between this ticket at #9826.

**Comment by magthe** [comment]
Issue seems gone so I'm closing.

**Comment by dqdinh** [comment]
FWIW - I'm seeing this issue again with "SPC p f" after updating deps. I'm on the stable branch. Used workaround in https://github.com/syl20bnr/spacemacs/issues/9563#issuecomment-330905391 and it worked. Probably might resolve itself after the new dependency update. Thanks for the workaround.

**Comment by igoodrich** [comment]
I am also suddenly seeing the issue again after an upgrade and after > 1 year of total stability

**Comment by proteusvacuum** [comment]
I also started seeing this after upgrading. Adding `(require 'tramp)` to dotspacemacs/user-config seems to mitigate the issue.

**Comment by c-garcia** [comment]
I am not sure it is an issue with spacemacs. I am just experiencing the same issue and I am not using it. My `init.el` is based on `use-package`.
I hope this helps.

**Comment by tbille** [comment]
I am also getting this error. Like others: `(require 'tramp)` to `dotspacemacs/user-config` fixed the issue

I am using the `vanilla`configuration if it helps and on this commit: d46eacd83842815b24afcb2e1fee5c80c38187c5
