### ISSUE TITLE
M-backspace does not effectively delete words in ansi-term

### ISSUE THREAD

**Issue by wizmer** [syl20bnr/spacemacs#9564]
#### Description :octocat:
M-backspace visually delete a word in ansi-term but when Enter is pressed the deleted word is still part of the command.

#### Reproduction guide :beetle:
- Start Emacs
- M-x ansi-term
- Type "ls"
- Delete it using M-backspace
- press Enter

*Observed behaviour:* :eyes: :broken_heart:
The "ls" command is performed even it had been deleted

*Expected behaviour:* :heart: :smile:
The "ls" command should not be performed.
The problem is that M-backspace is overriden by clean-aindent-mode and set to (clean-aindent--bsunindent ARG)

*Resolution:* :heart: :smile:
Disable clean-aindent-mode in term-mode
In my init.el I put the following hook:
`(add-hook 'term-mode-hook (lambda () (clean-aindent-mode -1)))`

But I think this should be enabled by default, or at least when the shell layer is activated (which is not the case either).
Unfortunatly I don't know about spacemacs internals to provide a PR.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm emacs-lisp)
```

**Comment by CeleritasCelery** [comment]
Can you reproduce this with stock emacs?

**Comment by wizmer** [comment]
In stock emacs M-backspace works as expected. The key is mapped to (term-send-raw-meta) as it should be, and not (clean-aindent-mode -1).

**Comment by CeleritasCelery** [comment]
if you disable `clean-aindent-mode` it should work. Or override `M-backspace` in `term-raw-map`.

**Comment by wizmer** [comment]
Yes that's what I use. But this is only a work around.
The reality is that spacemacs is breaking a functionality provided by vanilla emacs.
What I'm saying is that `clean-aindent-mode` should be disabled for term mode by default as it makes no sense for this mode. Or at least when people activate the 'shell' layer I guess.

**Comment by CeleritasCelery** [comment]
While I agree with you that `clean-aindent-mode` shouldn't break functionality in `term-mode`, this is not a Spacemacs problem, this is a clean aindent mode problem. Spacemacs is not responsible for the behavior of hundreds of 3rd party packages, it just provides them. 

I have looked into a way to disable this mode in terminals, but unfortunately it is a global minor mode. There may still be a way but I have not found it. In reality where this issue belongs is with the `clean-aident-mode` package itself.

**Comment by wizmer** [comment]
I understand. I'll will open in [clean-aindent](https://github.com/pmarinov/clean-aindent-mode).
Hence I am closing it there.
