### ISSUE TITLE
Opening spacemacs clients (i.e. with emacsclient -a '') with restored sessions and layouts?

### ISSUE THREAD

**Issue by Millani** [syl20bnr/spacemacs#9566]
I love Spacemacs and have been using it for a while. Currently, for the first time I felt the need of actually using via daemon/client. I can successfully start a daemon and clients. However, when I start Spacemacs with `emacsclient -a '' '$@'`, it does not recover last session and layouts.

Although it works perfectly with non-server Spacemacs (i.e. called directly with `emacs.exe`). Is there a way to make clients recover sessions and layouts?

**Comment by CeleritasCelery** [comment]
try `dotspacemacs-auto-resume-layouts t` in `dotspacemacs/init`
