### ISSUE TITLE
Storing and restoring zoom level together with layouts

### ISSUE THREAD

**Issue by vasselai** [syl20bnr/spacemacs#9567]
I was wondering if there is a way to have Spacemacs store and then automatically restore zoom-level of files with my layouts.

After I open Emacs, the very first single thing that I always have to do is zooming in the files to have a big enough font to fit well with my given layout design (that is, the size of the inner windows of a given layout design). Simply defining a default given bigger font size does not solve the issue, because obviously the zoom factor has to be different depending on how many windows and on their positions.

Therefore, it would be really great to have zoom level of files saved and automatically restored together with layouts. Is there a way to accomplish that? If not, here it goes a feature request.
:)

**Comment by CeleritasCelery** [comment]
There is not currently a way
