### ISSUE TITLE
Dired 'h' help not accessible

### ISSUE THREAD

**Issue by wolfv6** [syl20bnr/spacemacs#9569]
#### Description :octocat:
Dired 'h' help not accessible because 'h' is evil move cursor left
Similar for INFO dir 'h' primer for first-timers.

#### Reproduction guide :beetle:
- Start Emacs
- SPC SPC a d
- enter Dired
- enter '?' to display a list of Dired commands
- enter 'h' (help command)

*Observed behaviour:* :eyes: :broken_heart:
cursor moves left

*Expected behaviour:* :heart: :smile:
open Dired help

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy evil-snipe emacs-lisp org spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### comment
originally posted on https://github.com/emacs-evil/evil/issues/921#issuecomment-328572969

Maybe a good way to get Dired help is to use '?' instead of 'h'.

**Comment by CeleritasCelery** [comment]
I don't think `?` is good replacement because it already provides useful functionality.

**Comment by wolfv6** [comment]
@CeleritasCelery I didn't know because I don't have access to Dired help ;)

**Comment by CeleritasCelery** [comment]
Just run `help`

**Comment by wolfv6** [comment]
@CeleritasCelery, How to run "help" ?

**Comment by CeleritasCelery** [comment]
`M-x help`

**Comment by wolfv6** [comment]
@CeleritasCelery, Sorry I don't see the Dired help.
Which option under M-x help?

**Comment by smile13241324** [comment]
@wolfv6 you can simply use the default emacs bindings that is `f1 m` or `C-h m` this shows the standard emacs mode help which documents the major mode with all keybindings. If you need a more detailed documentation you can also read the info nodes about dired with `C-h i`.

If you only want to know the keybindings please note that the default spacemacs way is almost always more user friendly than the emacs alternative. This is press `SPC h k` and page through the available commands. Or you press `SPC SPC` and just search for the command with dired used as prefix i.e. `SPC SPC dired copy` returns `dired-do-copy` as well as two other copy commands. As a bonus you also see the keybinding if available. Also notice that not always all commands are bound to keys per default so it makes always sense to use the search function when you explore commands.

**Comment by wolfv6** [comment]
@smile13241324 
Do your "C-h m" and "C-h i" have Dired help?  I am not finding it.
"C-h m" *Help* has projectile-dired, but not Dired help.
"C-h i" INFO dir has Dired-X, but not Dired help.

**Comment by smile13241324** [comment]
@wolfv6 not sure what the original help content was I just assumed it was the one from the major mode documentation. 

So when you want to see the original content of dired help why don't you just change the editing style in your .spacemacs file from vim to emacs based? There is a documented variable for this in your dot file which you can reach via `SPC f e d`. Then evil is not loaded and the bindings proposed in the original emacs documentation all work.

**Comment by wolfv6** [comment]
Thanks for all your help @smile13241324.
I copied the Dired help into another file for easy access.
This is how to copy Dired help:

    SPC t E e   switch to Emacs editing style (blue)
    C-x d Ent   run dired
    ?  h        dired help
    M-w         copy
    M-m t E e   switch to Spacemacs editing style (purple)

So is this a Spacemacs bug, or should this issue be closed?:

    Dired 'h' help not accessible from Spacemacs editing style because evil 'h' is move cursor left.
    Similar for INFO dir 'h' primer for first-timers.

**Comment by smile13241324** [comment]
@wolfv6 Just keep it open, I think there should be a way to access the original help though one is using the evil bindings.
