### ISSUE TITLE
Magit describe key, shows duplicate buffers and leaves behind a window

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#9570]
#### Description :octocat:
Magit describe key, shows the `magit-dispatch-popup` window twice, and closing them,
leaves behind an extra window.

#### Reproduction guide :beetle:
- Start Emacs
- Open the scratch buffer: `SPC b s` (make sure that it's the only window)
- Show the `magit-dispatch-popup` buffer: `SPC g m`
the frame splits into two windows.
- Show the "describe key:" prompt: `?`
- Press `g` to describe the `magit-refresh` command

*Observed behaviour:* :eyes: :broken_heart:
##### Describing a key
The frame splits into three windows, the top two windows show the same
`magit-dispatch-popup` buffer, and the bottom window shows the help info for
`magit-refresh`.

![emacs_2017-09-11_20-30-00](https://user-images.githubusercontent.com/13420573/30290546-0a9cf7c4-9730-11e7-8879-9a3ecbfc9178.png)

##### Closing the help and dispatch buffer
The top `magit-dispatch-popup` window has focus. When `q` is pressed, then one
window, and the `magit-dispatch-popup` buffer closes, but it leaves behind an
extra window.

![emacs_2017-09-11_20-31-09](https://user-images.githubusercontent.com/13420573/30290591-2dacff16-9730-11e7-9a28-6f8b51b142f4.png)

*Expected behaviour:* :heart: :smile:
##### Describing a key
To match the behaviour, when a key is described, with just Emacs and Magit
(see the notes section below), then only two windows should be shown.

Since Spacemacs seems to show the help window, at the bottom of the frame by
default, then the `magit-dispatch-popup` buffer, should be shown at the top, and
the help window at the bottom.

##### Closing the help and dispatch buffer
The bottom help window should have focus, and when `q` is pressed, then the
frame should return to it's previous state, with the `magit-dispatch-popup`
buffer in the bottom window and the `*scratch*` buffer in the top window.

The bottom `magit-dispatch-popup` window should have focus, and pressing `q`,
should return to the state the frame was in, before the key was described, in
this case, only the `*scratch*` buffer should be shown in a single window.

#### Notes
Starting Emacs without any configurations and loading the Spacemacs packages:
- `emacs --quick`
- `M-x` `package-initialize`
- `M-x` `magit-dispatch-popup` 
the frame splits into two windows.
- Show the "describe key:" prompt: `?`
- Press `g` to describe the `magit-refresh` command

Then the help buffer is shown in the top window, and the `magit-dispatch-popup`
buffer is shown in the bottom window.

The top window has focus, and pressing `q`, returns to the previous state, where
the top window shows the `*scratch*` buffer, and the bottom window still shows
the `magit-dispatch-popup` buffer.

The bottom window has focus, and pressing `q`, closes the `magit-dispatch-popup`
window, returning the frame to the state it was in, before the magit key was
described.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 84751cbc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion colors emacs-lisp git helm markdown org spell-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by CeleritasCelery** [comment]
are you saying it works correctly with stock Emacs and magit?

**Comment by duianto** [comment]
Yes, it only opens two windows, and pressing `q` twice, closes them in reverse order. That returns the frame to the state it was in, before the `magit-dispatch-popup` window was opened.

**Comment by bmag** [comment]
Here's some code to add to user-config as a work-around until this is fixed upstream:

```elisp
(defun fix-magit-popup-describe-function (oldfun &rest args)
  (let ((purpose--active-p nil)
        (help-window-select nil))
    (apply oldfun args)))

(advice-add 'magit-popup-describe-function :around 'fix-magit-popup-describe-function)
```

The function `magit-popup-describe-function` implicitly assumes `help-window-select` is nil, which is problematic because it later uses `other-window` to control the selected window and gets it wrong in Spacemacs, because we set `help-window-select` to `t`.

`magit-popup-describe-function` also doesn't locally override `display-buffer-overriding-action`, despite overriding `display-buffer-alist`. Not sure if it's intentional or not, but it clashes with `window-purpose` that uses `display-buffer-overriding-action` (I do plan to change that sometime).

**Comment by bmag** [comment]
Fixed upstream, closing 😄
