### ISSUE TITLE
Error entering newlines in OCaml

### ISSUE THREAD

**Issue by IanConnolly** [syl20bnr/spacemacs#9573]
#### Description :octocat:

Can't enter newlines in Ocaml :(

#### Reproduction guide :beetle:
- Start Emacs
- Open any Ocaml file
- Try and insert a newline in insert mode with enter

*Observed behaviour:* :eyes: :broken_heart:

Error thrown :(

Looks like the issue comes from this mapping in tuareg-mode: https://github.com/ocaml/tuareg/blob/master/tuareg.el#L1088

This points to a function deleted in this commit/diff: https://github.com/ocaml/tuareg/commit/b2ad75f3d5d21b4309433715fb0bccd5868dac04#diff-ae77a4767c632544ed4f575e40498f1fL1717

I'm not sure if this mapping is generally harmless and only a problem in Spacemacs or means tuareg-mode is broken for anyone who doesn't wrap `newline-and-indent` manually themselves as my elisp isn't great.

Tagging @Chris00 from the above commits in case this is just a tuareg-mode thing and doesn't have anything to do with Spacemacs

*Expected behaviour:* :heart: :smile:

Newline entered, with cursor indented on the new line.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv sql vimscript javascript helm
     (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
     better-defaults emacs-lisp
     (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
     git
     (go :variables go-tab-width 2)
     haskell html markdown
     (ruby :variables ruby-test-runner 'rspec ruby-version-manager 'chruby)
     ruby-on-rails rust ocaml org osx
     (scala :variables scala-enable-eldoc t)
     (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
     syntax-checking twitter themes-megapack
     (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
     vinegar yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument commandp tuareg-newline-and-indent)
  call-interactively(tuareg-newline-and-indent nil nil)
  command-execute(tuareg-newline-and-indent)

```

**Comment by Chris00** [comment]
Fixed in the above commit (this is due to the removal of old indentation functions).

**Comment by IanConnolly** [comment]
Awesome, thanks @Chris00 -- updated all packages and can confirm I can insert newlines once again. Much appreciated.
