### ISSUE TITLE
The `org-mime.el` is missing

### ISSUE THREAD

**Issue by elandx** [syl20bnr/spacemacs#9576]
#### Description :octocat:
The `org-mime.el` is missing

#### Reproduction guide :beetle:
- Just enter to the `org-plus-contrib` directory, and you can not find
  `org-mime.el` in it

*Observed behaviour:* :eyes: :broken_heart:
Starting from the org's Version 9.1 `org-ebib.el`, `org-bullets.el` and `org-mime.el` have been deleted from the `contrib/` directory.  But in the spacemacs' org layer the `org-mime` is listed as built-in (`(org-mime :location built-in)`).  I have tried to install `org-mime` package by adding it to the additional packages list but without success. May be due to the fact that it is already present in the org's layer packages list, but as built-in. 

*Expected behaviour:* :heart: :smile:
installable `org-mime` package

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 84751cbc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(python typography vimscript html helm auto-completion
        (org :variables org-enable-reveal-js-support t org-enable-github-support t)
        (shell :variables shell-default-term-shell "/bin/zsh" shell-default-height 30 shell-default-position 'bottom)
        (spell-checking :variables spell-checking-enable-by-default nil)
        emacs-lisp
        (latex :variables latex-enable-folding t latex-enable-auto-fill t)
        (mu4e :variables)
        asciidoc markdown lua pdf-tools csv systemd pandoc bibtex graphviz
        (ess-R :variables ess-enable-smart-equals nil)
        google-calendar helm-add xah-math writeroom no-mouse langtool wcheck djvu ebib multiple-cursors)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by CeleritasCelery** [comment]
It's there for me `.emacs.d/elpa/org-plus-contrib-20170606/org-mime.el`. Maybe try to re download?

**Comment by elandx** [comment]
Thank you very much for your help.

But you use old version of org-plus-contrib, current version is 20170911. I
`fixed` the issue by downloading org-mime.el from git and byte-compiling
it. But i would like a real `fix` happens, maybe change in the list of org
layers packages.

**Comment by CeleritasCelery** [comment]
wonder if #9541 is relevant.

**Comment by elandx** [comment]
@CeleritasCelery,
I think that I have a different situation than in [#9541](https://github.com/syl20bnr/spacemacs/pull/9541). For me `org-mime` package works. Simply, it is absent from the current `org-plus-contrib`, and i can't install the `org-mime` package from MELPA by the standard spacemacs' means (as i wrote in the report).

**Comment by CeleritasCelery** [comment]
That's what #9541 is about. Have you tried applying that patch and see if that works?

**Comment by elandx** [comment]
@CeleritasCelery,
sorry i don't see where is the patch you are talking about...

**Comment by nickanderson** [comment]
The patch in #9541  worked for me.

**Comment by elandx** [comment]
Obviously, string "`(org-mime :location built-in)`" must be replaced with "`org-mime`" (as i wrote in initial message). My point is: it should be done by the author of spacemacs's org layer, not by me or you.

**Comment by CeleritasCelery** [comment]
That's what the PR is for 🙂

**Comment by mandarvaze** [comment]
@CeleritasCelery The change from this patch is **not** working for me.

After the patch, `org-mime` is  found, but when I use `org-mime-htmlize`, I get some search error (I have reversed the "patch" - so I don't have exact error text)

**Comment by mandarvaze** [comment]
@CeleritasCelery May be unrelated. But the fact remains that "earlier" it was working (when installed from spacemacs' org-contrib-plus repo) Now it doesn't.

**Comment by CeleritasCelery** [comment]
Then open a new issue. Your issue is not “org-mime.el is missing”.

**Comment by mandarvaze** [comment]
Yes. it is not "org-mime.el is missing"
But is related to how spacemacs provided (and now it doesn't) org-mime.

I'll open an issue with org-mime git repo.

**Comment by mandarvaze** [comment]
Turns out org-mime fixed this issue, while I was reporting the issue here.
See https://github.com/org-mime/org-mime/commit/f1175e3faba25d3f862a43392b69854cdd18be9d

I verified by installing latest `org-mime` package from MELPA, that I can indeed send HTML emails via `mu4e` using org-mode

**Comment by everiori** [comment]
it seems that the https://github.com/syl20bnr/spacemacs/pull/9541/commits/3d9be4b19313e48ce5d19c18c0b20c542bc0b2e6 patch fixed the problem, but it get reverted somehow, the current code is still (org-mime :location built-in), not org-mime, should I open another new issue about it?

**Comment by mandarvaze** [comment]
@everiori #9541 has the same change

**Comment by Miciah** [comment]
Since #9541 / https://github.com/syl20bnr/spacemacs/commit/f3d4bdb366c2d6d204616ebee25b6530e8295cef has been merged in Spacemacs's develop branch to resolve the original issue (and https://github.com/org-mime/org-mime/commit/f1175e3faba25d3f862a43392b69854cdd18be9d has been merged in org-mime to resolve the subsequent issue with `org-mime-htmlize`), can this issue be labeled as "Fixed in develop"?
