### ISSUE TITLE
indentation not same in haskell-layer between using `evil-ret` in insert mode and `evil-open-below` in normal mode

### ISSUE THREAD

**Issue by cdepillabout** [syl20bnr/spacemacs#9577]
#### Description :octocat:

Indentation is not the same in haskell-layer between using `evil-ret` in insert mode and `evil-open-below` in normal mode.

I posted a [question](https://emacs.stackexchange.com/questions/35431/how-to-get-correct-indentation-after-pressing-o-in-haskell-mode-using-evil-mod) about this on the emacs stack exchange.  One of the commenters suggested I create an issue about it on the spacemacs issue tracker.

Imagine I want to write the following Haskell file:

```haskell
module Foo where

foo :: Int
foo = 3
```

However, I've only written the following.  I haven't yet created the function body for the `foo` function:

```haskell
module Foo where

foo :: Int
```

If I am in insert mode and have my cursor after the "t" in `Int` and press <kbd>Enter</kbd> (which I believe runs `evil-ret`), the cursor goes to the next line in the first column, directly under the "f" in "foo".  Using an underscore (`_`) for the cursor position, it looks like this:

```haskell
module Foo where

foo :: Int
_
```

This is correct.

However, if I am in normal mode and have my cursor anywhere in the line with "foo" and press <kbd>o</kbd> (which I belive runs `evil-open-below`), the cursor goes to the next line in the *third* column.  It looks like this:

```haskell
module Foo where

foo :: Int
  _
```

This is incorrect.  I have to press <kbd>Backspace</kbd> twice to put the cursor in the first column before I can start writing the definition of `foo`.

It seems like indentation rules are getting messed up.  The indentation should not be different between `evil-ret` and `evil-open-below`.

Here is my current [`.spacemacs`](https://github.com/cdepillabout/docs/blob/d8dfbca8c12a0ea911527cc7ffc418486dd0d18d/dot_files/dot_spacemacs) config file.  To my knowledge, I don't have any settings set that effect indentation.

#### Reproduction guide :beetle:
-   Start Emacs
-   Enable the Haskell layer.
-   Create a Haskell file that looks like this:

    ```haskell
    module Foo where

    foo :: Int
    ```
-   Go into insert mode and put the cursor after the "t" in `Int`.  Press <kbd>Enter</kbd>.  The cursor should be on the next line in the first column.  This is the correct behavior.
-   Now go back to the `foo :: Int` line and go into normal mode.  Press <kbd>o</kbd>.  The cursor should be on the next line in the third column.  This is the incorrect behavior.

*Observed behaviour:* :eyes: :broken_heart:

Indentation different depending on whether <kbd>Enter</kbd> or <kbd>o</kbd> is used.

*Expected behaviour:* :heart: :smile:

The indentation is the same.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion colors docker emacs-lisp git
                 (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "fundamental")
                 helm html idris markdown ocaml
                 (org :variables org-enable-github-support t)
                 python
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 (spell-checking :variables spell-checking-enable-by-default nil)
                 sql syntax-checking version-control yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by CeleritasCelery** [comment]
How does stock emacs behave?

**Comment by cdepillabout** [comment]
@CeleritasCelery I'm not sure how stock emacs behaves.  I'm relatively new to emacs and spacemacs.  I don't know enough about emacs to be able to setup the various haskell-related plugins along with evil-mode without using spacemacs.

But if someone else knows a good guide, or wants to try to set it up, I would be very interested in whether this is a problem caused by spacemacs, evil-mode, or one of the haskell-plugins installed by the haskell layer.

**Comment by cdepillabout** [comment]
This seems to be a problem with the interaction between evil and haskell-mode, so it not necessarily a spacemacs problem.  

Here are some related issues:

https://github.com/syl20bnr/spacemacs/issues/5010

https://github.com/haskell/haskell-mode/issues/1265

Since this is not a problem with Spacemacs, I will close this issue.
