### ISSUE TITLE
C/C++ layer incomplete documentation

### ISSUE THREAD

**Issue by wolfv6** [syl20bnr/spacemacs#9578]
#### Description :octocat:

The "C/C++ layer" README on
https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/c-c%2B%2B#key-bindings
says:

    SPC m g a | open matching file (e.g. switch between .cpp and .h)

Would be nice if it also said, "this is a projectile function, so it only works from inside a project."

Also, the Spacemacs online help is missing "bound to SPC m g a".

#### Reproduction guide :beetle:
- Start Spacemacs
- M-x h d k
- Describe key: SPC m g a

*Observed behaviour:* :eyes: :broken_heart:
It is bound to C-c p a, M-RET g a, M-m m g a, and many ordinary text characters.

(projectile-find-other-file &optional FLEX-MATCHING)

*Expected behaviour:* :heart: :smile:
It is bound to SPC m g a

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(c-c++ emacs-lisp evil-snipe ivy org spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

**Comment by CeleritasCelery** [comment]
You should report this upstream at projectile.

**Comment by wolfv6** [comment]
@CeleritasCelery, thanks for your feedback.  I updated the issue to be more Spacemacs centric.  I don't think it's anything that projectile can fix.

**Comment by wolfv6** [comment]
@CeleritasCelery that's right.

**Comment by CeleritasCelery** [comment]
Go ahead and open a PR. This will be a great way for you to contribute to the project 😄 !

**Comment by wolfv6** [comment]
OK.  I will submit a PR next year, after I learn more about editing Emacs.

**Comment by CeleritasCelery** [comment]
This is just documentation, so no elisp required. Just Org mode.

**Comment by smile13241324** [comment]
Tried to reproduce your issue on develop. 

Looks like `SPC m g a` is documented now in `C++-mode`.

As to your first point yes you are right you actually need to be in a project to run `show other file` successfully. I also think this should be documented, though I think that most people won't notice as the first thing one normally does is to make a git repo anyway.

**Comment by wolfv6** [comment]
@smile13241324  Thanks.   Now I see "SPC m g a" on the first line in help:
    "SPC m g a runs the command projectile-find-other-file"
Maybe it was there the whole time.

Normally I learn Emacs features outside of a git repo.
I was frustrated until I figured out that SPC m g a needed a git project.

**Comment by smile13241324** [comment]
@wolfv6 You don't necessarily need a git repo to have a projectile project, you can also simply make a .projectile file in your wished projects root folder. This will make that folder a project. I do the same with my GTD folder so that I can search within the folder recursively using projectiles find functions.

**Comment by wolfv6** [comment]
@smile13241324, The "SPC m g a" \*help\* says:
"SPC m g a runs the command projectile-find-other-file"
So that's enough documentation after all.
Time for me to learn projectile.
Thank you  for your patience.
