### ISSUE TITLE
`g q l` (evil-fill-and-move) doesn't format a long list item

### ISSUE THREAD

**Issue by concretevitamin** [syl20bnr/spacemacs#9579]
Repro:
Under an orgmode headline, `SPC i l p` (for spacemacs; but otherwise any long line of text that goes beyond the current screen width would do) but don't format it. `S-i` to the line beginning then add `- ` (a minus sign, then a space) at the beginning of this long line. Then `g q l` failed.

This is unfortunately distinct from vim behavior.  In vim, the first line has the leading `- `(2 chars), and the subsequent lines are nicely formatted to have 2-char indent as well.

This [comment](https://github.com/Somelauw/evil-org-mode/issues/18#issuecomment-329021847) shows that this might be due to Spacemacs, not the underlying `evil-mode` or `evil-org-mode`.

Posting my system info:
#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html yaml auto-completion better-defaults emacs-lisp markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      syntax-checking version-control python osx)
```

**Comment by Somelauw** [comment]
Can you describe what the result looks like when `gq` doesn't work?

**Comment by duianto** [comment]
@Somelauw When concretevitamin mentioned the issue in the spacemacs gitter chat:
https://gitter.im/syl20bnr/spacemacs?at=59b86950b59d55b823eb6aeb

Then nothing happened to the line below the headline, when `gql` was pressed, but `M-q` worked as expected.

However, now when I try to reproduce it, then `gql` also work as expected on both the master and develop branches.

**Comment by concretevitamin** [comment]
I just tried and couldn't reproduce it either.  Weird.  Commit 9341e1d7
from develop branch didn't change.

**Comment by smile13241324** [comment]
Worked also for me on current develop and emacs 25.3.1.
