### ISSUE TITLE
What is your preferred editing style?

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [syl20bnr/spacemacs#9580]
There is no "Recommended" Tag for the very first question that pops up, after installing spacemacs: "What is your preferred editing style?"

Pressing up or down, changes the ordering, making it impossible without crashing emacs and restarting it, to get back to the option it defaulted to.

Some people are not apart of the VIM/EMACS war, so either give a Recommended option, or a third option that says, I don't care.

**Comment by RefinedSoftwareLLC** [comment]
Also, you need to state if this choice can be changed at any time, or if you have to reinstall to change this choice.

**Comment by RefinedSoftwareLLC** [comment]
Note to anyone who pulls this up by an internet search: "Vim" seams to be the correct answer, because the documentation will show the "Vim" way.

**Comment by duianto** [comment]
This seems to be where the questions are defined:
https://github.com/syl20bnr/spacemacs/blob/9341e1d7511067f06fbae6cc7d1af00d42c80f99/core/core-dotspacemacs.el#L575

**Comment by CeleritasCelery** [comment]
I don't know if this should have a "recommended" tag because this really is just personal preference. However you are right that Spacemacs tends to be evil centric.

**Comment by vibrys** [comment]
if You choose emacs editing style, please consider defining SPC as Alt+<spc>. Seems to be convenient.

**Comment by oldgaro** [comment]
I still think that Vim is the ultimate perfect editor. So I chose to be Evil haha

**Comment by fiveNinePlusR** [comment]
I mean the docs are pretty clear about which way is the preferred way:

> A community-driven Emacs distribution - The best editor is neither Emacs nor Vim, it's Emacs *and* Vim!

that strongly implies that vim bindings are a central tenet of spacemacs.

**Comment by smile13241324** [comment]
I have also tried both Vim and vanilla Emacs and after a short period of getting used to I find vim much more easier to use so I prefer evil.

Nevertheless as to the wished `I don't care option` there is one it is called `hybrid style` and is also a proposed choice.
