### ISSUE TITLE
Making custom urls clickable and browsable

### ISSUE THREAD

**Issue by AshKash** [syl20bnr/spacemacs#9581]
I deal with custom urls of the form: rdar://problem/12345 and spacemacs does not recognize them. I looked at documentation and code for browse-url.el and ffap.el but nothing seems to work. I also tried to change ffap-url-regexp:
```
 (setq ffap-url-regexp
   (concat
    "\\("
    "news\\(post\\)?:\\|mailto:\\|file:" ; no host ok
    "\\|"
    "\\(ftp\\|https?\\|rdar\\|www\\)://" ; needs host
    "\\)"))
  ```
While ffap-next recognizes it as a link and can open it, Spacemacs itself does not underline the link and open on hitting enter on it.

Any ideas how to make it work?

Spacemacs is awesome, I use it in holy mode and it gets 99% of the defaults right!

**Comment by CeleritasCelery** [comment]
Have you tried `re-builder`? That should let you test your regex for correctness.

**Comment by AshKash** [comment]
Turns out thingatpt is the one responsible for doing this.

http://tess.oconnor.cx/config/.emacs

```
(defun ted-thingatpt-install-apple-uri-schemes ()
  (let ((schemes '("rdar://" "adir://" "afp://" "message:")))
    (mapc (lambda (scheme)
            (add-to-list 'thing-at-point-uri-schemes scheme))
          schemes))
  (setq thing-at-point-url-regexp
        (concat "\\<\\(" (mapconcat 'identity thing-at-point-uri-schemes
                                    "\\|") "\\)"
                thing-at-point-url-path-regexp)))
```
