### ISSUE TITLE
SPC 0 is undefined

### ISSUE THREAD

**Issue by kirillshevch** [syl20bnr/spacemacs#9584]
It just doesn't work
https://github.com/syl20bnr/spacemacs/blob/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/doc/DOCUMENTATION.org#window-manipulation
Emacs 25.2
Spacemacs 0.200.8

**Comment by duianto** [comment]
`SPC 0` selects the `SPC f t` neotree window when it's open, on both the latest master and develop branches.

Could you include your system info? That might narrow down the issue. Press `SPC h d s` and the clipboard will contain your info.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 9341e1d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion colors emacs-lisp git helm markdown org spell-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by kirillshevch** [comment]
@duianto `SPC h d s` also is undefined

**Comment by duianto** [comment]
Do you get any error messages on startup?

One solution is probably to start over with a fresh install, if you have any custom configurations, then make a backup of your current `.spacemacs` file, and the `.emacs.d` folder. You can add back your configurations one by one, and see if any of them are causing the issue.

**Comment by kirillshevch** [comment]
Warning (initialization): An error occurred while loading ‘/Users/kirill/.emacs.d/init.el’:

error: Required feature ‘pcre2el’ was not provided

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

**Comment by duianto** [comment]
If you haven't edited the init.el file, then it's probably something in your `.spacemacs` file.
Could you paste the `.spacemacs` files content, as a github gist, or on some other pasteing service, and post the link here.

**Comment by duianto** [comment]
Another option is, if you have another application where you can compare two files, then you can compare your `.spacemacs` file to `.emacs.d/core/templates/.spacemacs.template`.

**Comment by kirillshevch** [comment]
https://github.com/kirillshevch/dotfiles/blob/master/.spacemacs

**Comment by duianto** [comment]
A quick check shows these issues:

on line 56:
`   ruby-insert-encoding-magic-comment nil))`
this should not be here.

from line 67 to 75:
```
;; js2-mode
   js2-basic-offset 2
   ;; web-mode
   css-indent-offset 2
   js-indent-level 2
   web-mode-markup-indent-offset 2
   web-mode-css-indent-offset 2
   web-mode-code-indent-offset 2
   web-mode-attr-indent-offset 2
```
they should also not be there.

on line 251:
`   (setq ruby-insert-encoding-magic-comment nil)`
this should also not be there.

All of them should probably be in your `spacemacs/user-config` or in the `spacemacs/user-init` section if they need to run before the layer configuration.

The sections above `spacemacs/user-init`, should not contain user code, only the variables values should be changed there.

**Comment by duianto** [comment]
I just remembered that Emacs comes with `ediff`, so you can compare files with just Emacs.

If you start Emacs with `emacs -q`, then Emacs starts without loading any Spacemacs.

Press `M-x` and type `ediff`, and press `RET`, now you'll get asked for a file A, then for a file B.
When they open, then a small Emacs window with the text "Type ? for help", also opens, and when it has focus, then you can cycle through the differences between the two files by pressing `n` for next or `p` for previous.
To copy a difference from file A to file B, press `a`, and the other way around with `b`.
(just make sure you copy from the template file, you don't want to modify the template, although you can get the current template file from the Spacemacs Github repo if you overwrite it by accident)
To restore the previous change, press `ra` or rb` to restore the previous difference.
To save a file, press `wa` or `wb`.
To quick press `q`, and press `y` to answer yes.

One issue I've run into recently is that the whole file gets marked as a difference, the only solution I know of currently is to press `!` which updates the diff regions.

**Comment by bmag** [comment]
@kirillshevch next time, you should also include in your report:
- reproduction steps
- observed behavior vs. expected behavior
- a backtrace (only when relevant - this time it was relevant)

I understand that you reinstalled Spacemacs and now there's a different error (the one about pcre2e). Sounds like maybe there was an installation problem with pcre2el (perhaps corrupt download) - I suggest looking at pcre2el's sub-directory in elpa directory, you might need to delete it (only pcre2el) and let Spacemacs reinstall the package. Good luck.

**Comment by kirillshevch** [comment]
@bmag thanks, I'll try

**Comment by kirillshevch** [comment]
@bmag @duianto thanks for support. 
Just reinstalled emacs and spacemacs.
