### ISSUE TITLE
Super/Hyper or any modifier key as dotspacemacs-emacs-leader-key

### ISSUE THREAD

**Issue by sadhu89** [syl20bnr/spacemacs#9590]
How can I use `<super>` as `dotspacemacs-emacs-leader-key`? I am on Linux.

**Comment by bmag** [comment]
Set `dotspacemacs-emacs-leader-key` to `"<super>"`, and  make sure that pressing `<super>` (without pressing another key simultaneously) is passed to Emacs and isn't swallowed by your desktop environment, window manager, etc.

**Comment by sadhu89** [comment]
I just have tried with "H" (Hyper) and I have the same problem. Reading 
https://github.com/syl20bnr/spacemacs/issues/5102#issuecomment-185607230 I realized the problem is that I am trying to use a modifier key as leader key.
Is there any way to use a modifier key as the emacs leader key?
```
...if your diamond is really a modifier, I'm not really sure you can bind it as a normal key to use it as a leader.
```
