### ISSUE TITLE
Can't install elm layer

### ISSUE THREAD

**Issue by achikin** [syl20bnr/spacemacs#9592]
#### Description :octocat:
Error After adding elm layer to dotspacemacs-configuration-layers and restarting emacs
#### Reproduction guide :beetle:
- Start Emacs
- SPC f e d to open config
- add `elm` to dotspacemacs-configuration-layers
- Save configuration file
- Restart emacs

*Observed behaviour:* :eyes: :broken_heart:
Error in dotspacemacs/user-config: Symbol's function definition is void: elm
*Expected behaviour:* :heart: :smile:
Emacs starts without errors

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html go sql elm javascript helm auto-completion better-defaults emacs-lisp git clojure evil-cleverparens)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by achikin** [comment]
It's a configuration error rather than spacemacs error. Please ignore this ticket.

**Comment by mikos** [comment]
@achikin I'm experiencing the same error. Can you remember what you did to fix this?
