### ISSUE TITLE
evil-ex-search problem

### ISSUE THREAD

**Issue by jajpater** [syl20bnr/spacemacs#9595]
#### Description :octocat:
evil-ex-search problem

#### Reproduction guide :beetle:

 SPC l [spacemacs/layouts-transient-state/body]
 1 [spacemacs/layouts-transient-state/spacemacs/persp-switch-to-1-and-exit]
 SPC f e d [spacemacs/find-dotfile]
 / [evil-ex-search-forward]
 e [self-insert-command]
 e [debugger-eval-expression]   <---- ???
 n [self-insert-command]
 <down> [next-line-or-history-element]
 <backspace> [delete-backward-char]
 <backspace> [delete-backward-char]
 <backspace> [delete-backward-char]
 <backspace> [delete-backward-char]
 <backspace> [delete-backward-char]
 <backspace> [delete-backward-char]
 <backspace> [delete-backward-char]
 <backspace> [delete-backward-char]
 <backspace> [delete-backward-char]
 <backspace> [delete-backward-char]

*Observed behaviour:* :eyes: :broken_heart:
- Emacs becomming unresponsive
- CPU spinning to 100%

*Expected behaviour:* :heart: :smile:
String found in file 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. ca28bde0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv vimscript helm html auto-completion emacs-lisp git markdown org spell-checking latex deft mu4e typography
     (typography :variables typography-enable-typographic-editing t)
     pandoc search-engine dash pdf-tools csv)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
Debugger entered--entering a function:
* command-error-default-function((quit) "" nil)
  recursive-edit()
  debug(error (quit))
  redisplay_internal\ \(C\ function\)()
  read-string("/" #("40" 0 2 (face shadow)) evil-ex-search-history)
  evil-ex-start-search(forward nil)
  evil-ex-search-forward(nil)
  funcall-interactively(evil-ex-search-forward nil)
  call-interactively(evil-ex-search-forward nil nil)
  command-execute(evil-ex-search-forward)
```

#### Backtrace 2 :paw_prints:
```
Debugger entered--entering a function:
* command-error-default-function((quit) "" nil)
  recursive-edit()
  debug(error (quit))
  redisplay_internal\ \(C\ function\)()
  read-string("/" #("40" 0 2 (face shadow)) evil-ex-search-history)
  evil-ex-start-search(forward nil)
  evil-ex-search-forward(nil)
  funcall-interactively(evil-ex-search-forward nil)
  call-interactively(evil-ex-search-forward nil nil)
  command-execute(evil-ex-search-forward)
```

#### Backtrace 3 :paw_prints:

[Backtrace.txt](https://github.com/syl20bnr/spacemacs/files/1323838/Backtrace.txt)

I can't copy and paste the preceding Backtrace into this message, so I uploaded it as a file.

**Comment by bmag** [comment]
Can't repro with latest develop and packages. Maybe add a minimal latex file where the bug happens?

**Comment by jajpater** [comment]
I had this happen a couple of times yesterday. At the moment I can't reproduce it myself. Don't know why this happened. I had a lot of other buffers open yesterday. I will update the reproduction guide when this happens again. Is there an emacs commando that shows what input In have given emacs? Something like the history command in bash?

**Comment by braham-snyder** [comment]
`M-x view-lossage` shows command history

that said, this looks a lot like https://github.com/syl20bnr/spacemacs/issues/9220

**Comment by jajpater** [comment]
I had it happening to me again. I have pasted the relevant bit of view-lossage to the reproduction guide.
The string I was searching was "een"  and than emacs crashed on me. Wonder why 'view-lossage' gives the second 'e' is not a "self-insert-command" but a "debugger-eval-expression"

**Comment by jajpater** [comment]
It happened again while editing my `.spacemacs`  So this certainly  isn't a LaTeX problem. That tag can be removed. I uploaded another Backtrace. This time in my `Messages` buffer it said: `evil-ex-start-search: Search failed: "Yate"`
(I was searching for the string Yatemplate but when comming to the 'e' Emacs crashed on me.)

**Comment by braham-snyder** [comment]
did you already try the solutions in the issue I linked?

**Comment by jajpater** [comment]
@braham-snyder  Indeed, it might well be a poweline issue. I seems that this issue started since I changed `dotspacemacs-default-font '(` [..] `:size 18`  I did not change the `:powerline-scale` however. Maybe that is necessary? I have now excluded spaceline from my config by setting `dotspacemacs-excluded-packages '(spaceline)` I hope this solves the issue. I'll keep you informed.

**Comment by jajpater** [comment]
Since I disabled spaceline I haven't had this issue. So I guess you are right @braham-snyder. I'm closing this issue since #9220 is probably the same and still open.
