### ISSUE TITLE
cannot enter org-mode since upgrade

### ISSUE THREAD

**Issue by vv111y** [syl20bnr/spacemacs#9596]
#### Description :octocat:
Cannot enter org-mode

#### Reproduction guide :beetle:
- Start Emacs
- load an org file, or try to change buffer to org-mode

*Observed behaviour:* :eyes: :broken_heart:
gives error: Symbol’s function definition is void: evil-org-set-key-theme

*Expected behaviour:* :heart: :smile:
able to get org-mode

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. ca28bde0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 ansible better-defaults bibtex
 (c-c++ :variables c-c++-enable-clang-support t)
 chrome
 (clojure :variables clojure-enable-fancify-symbols t)
 command-log common-lisp coq cscope csv dash deft docker emacs-lisp erc ess fasd finance git github go haskell html ibuffer imenu-list ipython-notebook java javascript
 (latex :variables latex-enable-folding t latex-enable-auto-fill t latex-build-command "LatexMk")
 lua
 (markdown :variables markdown-live-preview-engine 'vmd)
 nim
 (osx :variables osx-use-option-as-meta t)
 (org :variables org-enable-github-support t org-enable-reveal-js-support t org-enable-bootstrap-support t org-startup-indented t org-startup-folded t)
 pandoc pdf-tools php python racket ranger
 (scala :variables scala-auto-insert-asterisk-in-comments t scala-enable-eldoc t scala-indent:use-javadoc-style t)
 search-engine semantic
 (spell-checking :variables spell-checking-enable-by-default nil)
 sql syntax-checking
 (shell :variables shell-default-height 30 shell-default-position 'right)
 themes-megapack tmux vagrant version-control zotero)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-function evil-org-set-key-theme)
  (evil-org-set-key-theme (quote (textobjects insert navigation additional shift todo heading)))
  (lambda nil (add-hook (quote org-mode-hook) (function (lambda nil (spacemacs/toggle-line-numbers-off))) (quote append)) (add-hook (quote org-mode-hook) (function (lambda nil (setq truncate-lines 0)))) (evil-org-set-key-theme (quote (textobjects insert navigation additional shift todo heading))) (setq org-agenda-files (quote ("~/documents/1text"))) (setq org-agenda-span 14) (setq org-agenda-text-search-extra-files org-agenda-skip-archived-trees) (setq org-agenda-skip-deadline-if-done t) (setq org-agenda-skip-scheduled-if-done t) (setq org-agenda-include-diary t) (setq org-refile-targets (quote ((nil :maxlevel . 2) (org-agenda-files :maxlevel . 2)))) (setq org-outline-path-complete-in-steps nil) (setq org-refile-use-outline-path t) (add-hook (quote after-init-hook) (quote org-agenda-list)) (setq org-confirm-babel-evaluate
```

**Comment by bmag** [comment]
Cause of bug: autoload was removed in https://github.com/Somelauw/evil-org-mode/commit/fe4e335f4d099cfb6470239e7840ca9bd31728ea

Solution: either ask upstream to restore the autoload or add an autoload to your config. I can't find in Spacemacs the lambda from the backtrace or where we call `evil-org-set-key-theme`, so I'm assuming it's part of your configuration.

**Comment by Somelauw** [comment]
The reason for removing the autoload was that `evil-org-set-key-theme` doesn't make sense without `evil-org-mode` enabled. Without the autoload, `evil-org-set-key-theme` becomes available after you have started `evil-org-mode`, so something like the following should work:
```emacs-lisp
(add-hook 'evil-org-mode-hook
            (lambda ()
              (evil-org-set-key-theme (textobjects insert navigation additional shift todo heading))))
```

Let me know whether this works for you or if you have a setup that requires it to be autoloadable anyway.

**Comment by vv111y** [comment]
Sorry for delay,
@Somelauw  the hook does work. Everything is okay now. Yes, l had a call to it in my user-config thanks @bmag , @Somelauw
