### ISSUE TITLE
is there any way to search word under the cursor in buffer when we use emacs style?

### ISSUE THREAD

**Issue by ChenXiyu** [syl20bnr/spacemacs#9597]
as I know,
`<leader>-/` is use to search word under the cursor in whole project,
 and in vim styles, `#` is used to search word under cursor in buffer,
 is there any way to do that in emacs style?

**Comment by bmag** [comment]
Yes, see section "Searching" in DOCUMENTATION.org. You're looking for `<leader> s S`.

**Comment by ChenXiyu** [comment]
@bmag  thank you!
that’s what I want. I should read that document more carefully.
thanks
