### ISSUE TITLE
ox-twbs doesn't work automatically

### ISSUE THREAD

**Issue by amosbird** [syl20bnr/spacemacs#9598]
#### Description :octocat:
ox-twbs isn't in load-path

#### Reproduction guide :beetle:
- Start Emacs
- Enable ox-twbs via `(org :variables org-enable-bootstrap-support t)`
- Open an org file
- Press `Ctrl-c Ctrl-e` and there isn't a twb entry

*Observed behaviour:* :eyes: :broken_heart:
twb entry appears in org-export-dispatch.

*Expected behaviour:* :heart: :smile:
twb entry doesn't appear in org-export-dispatch.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 804498b4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((mu4e :variables mu4e-installation-path "~/share/emacs/site-lisp/mu4e")
 blog-admin ipython-notebook pdf-tools bibtex latex perl5 go rust csv colors command-log javascript dash docker sql nginx vimscript html shell-scripts markdown yaml helm
 (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior nil auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-enable-sort-by-usage t auto-completion-private-snippets-directory nil)
 better-defaults
 (org :variables org-enable-bootstrap-support t)
 (ranger :variables ranger-override-dired t)
 emacs-lisp git
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
 (gtags :variables gtags-enable-by-default nil)
 (python :variables python-test-runner
         '(nose pytest))
 ycmd syntax-checking ab-package)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by DWShuo** [comment]
where is (org :variables org-enable-bootstrap-support t) placed? i just tried it on my install and it works

**Comment by amosbird** [comment]
in `   dotspacemacs-configuration-layers `

**Comment by smile13241324** [comment]
I was able to reproduce this with my config on develop. `ox-twbs` is not loaded until `org-twbs-export-to-html` is executed manually, then twbs exports are shown in export dispatch menu.

I have the following config parameters set in my .spacemacs file:
`(org :variables
          org-want-todo-bindings t
          org-enable-github-support t
          org-enable-bootstrap-support t
          org-enable-reveal-js-support t)`

**Comment by smile13241324** [comment]
I was able to reproduce this with my config on develop. `ox-twbs` is not loaded until `org-twbs-export-to-html` is executed manually, then twbs exports are shown in export dispatch menu.

I have the following config parameters set in my .spacemacs file:
`(org :variables
          org-want-todo-bindings t
          org-enable-github-support t
          org-enable-bootstrap-support t
          org-enable-reveal-js-support t)`

**Comment by kaushalmodi** [comment]
I am not a Spacemacs user, but even I can replicate this issue from a fresh Spacemacs installation. I came across this while trying to provide support for `ox-hugo` for Spacemacs.. See if this issue can be resolved using a similar approach as I did in my PR https://github.com/syl20bnr/spacemacs/pull/9705#issuecomment-334547709

**Comment by smile13241324** [comment]
The issue is related to the lazy loading procedure applied by spacemacs, we need to make sure that the export packages are loaded when `org-export` is called the first time currently this seems not to be done.

@amosbird For a quick workaround you can simply invoke one of the export functions manually this will trigger the loading procedure and subsequently add ox-twbs to the org-export menu. For example just do `SPC SPC org-twbs-export-as-html`.

**Comment by amosbird** [comment]
@kaushalmodi I cannot get your PR working.  @smile13241324 Yeah, that's what I use now.

**Comment by kaushalmodi** [comment]
@amosbird This is the best I could do.. [detailed instructions on how to try that PR without modifying your spacemacs setup][1]. If you works, you need to debug your config.

[1]: https://github.com/syl20bnr/spacemacs/pull/9705#issuecomment-334813354
