### ISSUE TITLE
Updating packages shows error

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#9599]
#### Description :octocat:

I cannot update packages, instead I get this after hitting `y` to update:

```
copy-directory: Opening output file: No such file or directory, /Users/aaronjensen/.emacs.d/.cache/.rollback/26.0/17-09-17_10.28.45/cider-20170905.1037/cider-apropos.el
```

#### Reproduction guide :beetle:

- Start Emacs
- Update packages

*Observed behaviour:* :eyes: :broken_heart:

This error:

```
copy-directory: Opening output file: No such file or directory,
/Users/aaronjensen/.emacs.d/.cache/.rollback/26.0/17-09-17_10.28.45/cider-20170905.1037/cider-apropos.el
```

*Expected behaviour:* :heart: :smile:

No Error

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. ca28bde0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(swift php nginx better-defaults spacemacs-layouts ivy
       (markdown :variables markdown-live-preview-engine 'vmd)
       (syntax-checking :variables syntax-checking-enable-tooltips t)
       (auto-completion :variables auto-completion-enable-sort-by-usage nil auto-completion-enable-snippets-in-popup nil)
       git dash pdf-tools html clojure
       (org :variables org-enable-github-support t org-enable-reveal-js-support t org-want-todo-bindings t)
       colors
       (osx :variables osx-command-as 'super)
       github ruby
       (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
       (spell-checking :variables spell-checking-enable-by-default nil)
       ranger version-control rcirc tmux yaml docker elm restclient lua chrome
       (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
       evil-little-word aj-elixir aj-emacs-lisp aj-javascript aj-typescript auto-correct cleverparens-lispy flow match-indent shift-number writing)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by aaronjensen** [comment]
This was a recent regression in emacs 26:

https://github.com/emacs-mirror/emacs/commit/e22794867d878d53675fcc91d2ef1ad2494a2ff2#diff-725cb3c0ff9b6d12e3ace616eb5b0d0d

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=28483

**Comment by aaronjensen** [comment]
This was fixed upstream http://git.savannah.gnu.org/cgit/emacs.git/commit/?h=emacs-26&id=37b5e661d298cbfe51422cd515b6696a1cdaa868

**Comment by robbyoconnor** [comment]
@aaronjensen thank you!
