### ISSUE TITLE
Automatically set major mode according to buffer extension

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#960]
We should add a hook when creating new buffer, set major mode according to extension. Currently, all new buffers created are all in `fundamental-mode`.

**Comment by syl20bnr** [comment]
This is not the behavior I have, create `foo.py` open a new buffer in `python` mode.

**Comment by tuhdo** [comment]
But when creating a buffer with `.el`, I got `fundamental-mode`.

**Comment by syl20bnr** [comment]
There is something in your config that modify the normal behavior, check the value of `auto-mode-alist`.

**Comment by tuhdo** [comment]
It's stock Spacemacs on `develop` branch.

**Comment by tuhdo** [comment]
Maybe you are talking about creating new files. What I meant is creating new buffers with `switch-to-buffer` or `helm-mini`. There are a few solutions in this [Emacs SE question](http://emacs.stackexchange.com/questions/2497/how-to-get-buffers-not-just-files-to-honor-auto-mode-alist).

**Comment by syl20bnr** [comment]
errrr what is the difference ?
I do `SPC f f` type my name then `RET RET`. This is a new buffer and there is no file created until I save.

**Comment by syl20bnr** [comment]
See the answer of the same question you posted ;-)

**Comment by tuhdo** [comment]
Yes I know the accepted answers but we could make it better. It's just convenient when I switch to a buffer and create a new one on spot when I have sudden need. Besides, it's easier to create a new buffer when switching buffer because when trying to create with `find-file`, you will have to avoid all the names in current directory.

**Comment by syl20bnr** [comment]
We could add a whole new feature in spacemacs then. A command to quickly create temp files in `.cache` with a given major mode.
The list of proposed major modes would depend on a customizable list.
The command would popup a list with `numbers` say from 0 to 9.
If elisp is 0 then I type `SPC f T 0` (T for temporary).
This has the advantage to combine quick major mode specific scratch with persistency.

**Comment by syl20bnr** [comment]
with a universal argument it could wipe out the file.

In fact it should be a package.

**Comment by tuhdo** [comment]
[open-junk-file](http://www.emacswiki.org/emacs/open-junk-file.el) already does that. I am using it. Btw, I reported this to Helm so it can be added to `helm-mini`. As for this issue, yes, probably about `open-junk-file` integration.

**Comment by syl20bnr** [comment]
:+1: for `helm-mini`
`open-junk-file` does not seems to have the quick major mode selection, does it ?

**Comment by tuhdo** [comment]
You don't need to. When running the command `open-junk-file`, it creates a temporary file name in a `junk` directory (default is `~/junk`) and leave the cursor at the end of the prompt for you to enter file extension. After that, appropriate major mode is set according to the supplied extension.

**Comment by syl20bnr** [comment]
Ok, prefect. It can be added to spacemacs layer.

**Comment by tuhdo** [comment]
It is updated on Helm side. Now we only needs to integrate `open-junk-file`.

**Comment by syl20bnr** [comment]
Great, thank you for the heads up.
