### ISSUE TITLE
Pandoc freeze on exporting from Org

### ISSUE THREAD

**Issue by pfaure** [syl20bnr/spacemacs#9602]
#### Description :octocat:
Pandoc freeze on exporting from Org

#### Reproduction guide :beetle:
- Start Emacs
- Open an org file
- SPC P /
- Choose any output
- In my case I used pdf (latex installed)

*Observed behaviour:* :eyes: :broken_heart:
- No file (in my case PDF, true for other formats) generated
- SPC a p
- Process hangs : pandoc-process  run      *Pandoc out... /dev/ttys000 pandoc --read=org --write=latex --output=**/pro/notes//general.pdf

*Expected behaviour:* :heart: :smile:
A PDF created in the same folder.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(html javascript auto-completion asciidoc csv emacs-lisp git ivy markdown org
      (osx :variables mac-right-option-modifier nil osx-dictionary-dictionary-choice "French")
      pandoc
      (shell :variables shell-default-height 30 shell-default-shell 'ansi-term shell-default-term-shell "/usr/local/bin/zsh" shell-default-position 'bottom)
      spell-checking spotify syntax-checking twitter themes-megapack version-control)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by pfaure** [comment]
seems like a pathing issue as SPC a p gives : 
`--output=**/pro/notes//general.pdf`

**Comment by pfaure** [comment]
I'd appreciate any input, as I'm at my wit's end regarding this double trailing '/' problem

**Comment by hliebert** [comment]
I have the same issue.

**Comment by pfaure** [comment]
As a workaround SPC-m-e-e gives org-export-dispatch which allows for pandoc export. It works through here.
