### ISSUE TITLE
M-RET broken in org-mode

### ISSUE THREAD

**Issue by brabalan** [syl20bnr/spacemacs#9603]
#### Description :octocat:
M-RET no longer bound to `org-meta-return` in org-mode. This is probably a consequence of the recent org-mode change of binding M-RET to `org-meta-return` instead of M-return.

#### Reproduction guide :beetle:
- Start Emacs
- Switch to Org Mode
- start a list
- type M-RET

*Observed behaviour:* :eyes: :broken_heart:
The menu for `M-m m` is shown.

*Expected behaviour:* :heart: :smile:
An entry is added to the list.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t company-minimum-prefix-length 4)
 bibtex
 (coq :variables proof-general-path "~/src/PG/generic/proof-site.el" proof-splash-enable nil)
 csv dash
 (elfeed :variables rmh-elfeed-org-files
         (list "~/.spacemacs.d/elfeedconfig.org")
         elfeed-use-curl t elfeed-sort-order 'ascending)
 emacs-lisp erc finance git gnus html ivy javascript
 (latex :variables latex-build-command "LatexMk" latex-enable-auto-fill t)
 markdown python ocaml org ruby
 (shell :variables shell-default-shell 'eshell)
 spell-checking themes-megapack
 (twitter :variables twittering-use-master-password t)
 yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by duckdodger** [comment]
Came here to make this exact issue. I'm experiencing this problem too.

**Comment by brabalan** [comment]
As additional information, here is what changed in org-mode.
Before:
``` emacs-lisp
  (org-defkey org-mode-map [(meta return)] 'org-meta-return)
```
After
``` emacs-lisp
  (org-defkey org-mode-map (kbd "M-RET") #'org-meta-return)
```

**Comment by dindom999** [comment]
It drop me crazy. I spend a half day to find out reason, now pop out a menu...
![_001](https://user-images.githubusercontent.com/5274818/30676437-c3e9b110-9eb8-11e7-816f-f865b4fabcc3.png)

**Comment by duckdodger** [comment]
Is there any temporary fix for this? I use Emacs mainly for Org-mode and this issue really makes it quite cumbersome.

**Comment by ddxgz** [comment]
Ctrl-RET does add an entry to list, could use it temporary @duckdodger .

**Comment by brabalan** [comment]
@ddxgz Not here, it calls `org-insert-heading-respect-content` which inserts an entry, not a list item.

**Comment by weitzjb** [comment]
Also struggling with this. Use this feature about 50 times per day. Anyone else got a quick fix?

**Comment by weitzjb** [comment]
tried this solution but doesn't work. [https://github.com/syl20bnr/spacemacs/issues/1200#issuecomment-93699328](url)

**Comment by figurehe4d** [comment]
This is also affecting me. Difficult, because it's a very often used macro in org mode! Hopefully there's a straightfoward fix. I'm new to emacs lisp and org mode (~2months) otherwise I'd try to troubleshoot the issue myself!

**Comment by dabro** [comment]
FWIW, adding the following to my .spacemacs seemed to work:
```
  (define-key evil-insert-state-map (kbd "M-RET") 'org-meta-return)
  (define-key evil-insert-state-map (kbd "<return>") 'org-return)
```

**Comment by milanmitrovic** [comment]
I have the same problem and none of the proposed solutions helped.

**Comment by slhoavmeelen** [comment]
add 
`(org-defkey org-mode-map [(meta return)] 'org-meta-return)`
into
`(defun dotspacemacs/user-config () )`
works for me

**Comment by brabalan** [comment]
@slhoavmeelen Great tip, thanks!

**Comment by weitzjb** [comment]
@slhoavmeelen you are a lifesaver thank you!

**Comment by figurehe4d** [comment]
so far no posted solutions have worked for me. :(

**Comment by darkfeline** [comment]
This is due to `dotspacemacs-major-mode-emacs-leader-key` being `C-M-m` `C-m` is `RET`, so everything and their cousins are getting bound to `M-RET ...`, overriding the `org-mode` binding.

Solution is to bind `M-<return>` in Spacemacs since this is not an upstream problem of Org mode.

**Comment by dsedivec** [comment]
To me it seems like what we want to do here is tell Spacemacs either "don't use my normal Emacs state leader key in org-mode" or "use a different Emacs state leader key in org-mode."  I don't see a nice way to do that, such as overriding `dotspacemacs-major-mode-emacs-leader-key` for a single mode.

FWIW I solved this with something akin to

```
(use-package org
  :bind (:map spacemacs-org-mode-map-root-map ("M-RET" . nil)))
```

**Comment by humanfactors** [comment]
I don't understand why this issue has just come up now. Surely we can revert to the default previous behaviour without changing out .spacemacs

**Comment by brabalan** [comment]
@humanfactors this issue is a consequence of a recent change in org mode.

**Comment by agzam** [comment]
As a matter of fact, instead of trying to find a workaround can we actually maybe make it better? Can we take this idea: http://kitchingroup.cheme.cmu.edu/blog/2017/04/09/A-better-return-in-org-mode and implement it? I think that would be utterly cool.

**Comment by Somelauw** [comment]
@agzam I'm also working on something like that https://github.com/Somelauw/evil-org-mode/issues/21

**Comment by syl20bnr** [comment]
`M-RET` is a core Spacemacs key binding and also a limitation of it, in the terminal it is impossible to differentiate the `C-m` and `RET`.

What other key binding could we set for `org-meta-return` ?

What pops out of my mind is to add `RET` key bindings to org-mode major leasder key so `org-meta-return` would `M-C-m C-m` or `M-RET RET`.

**Comment by syl20bnr** [comment]
I pushed a commit to add `M-RET` under major mode leader key so `org-meta-return` can be triggered with `M-RET M-RET`.
This is not an ideal solution but this is a dead end as in terminal `C-m` is `RET`.

**Comment by LanternD** [comment]
I can create a new list entry by first placing the cursor on a current list item in `normal-mode`  and then pressing `o` (insert a new line below).

**Comment by grbdeveaux** [comment]
Building on @dabro 's answer with the following to cover evil's insert state as well:

`  (add-hook 'org-mode-hook (lambda()
                             (define-key
                               evil-normal-state-local-map
                               (kbd "M-RET")
                               #'org-meta-return)
                             (define-key
                               evil-insert-state-local-map
                               (kbd "M-RET")
                               #'org-meta-return)))
`

**Comment by HomeLH** [comment]
C-RET works well.

**Comment by Gooseus** [comment]
I'm super new to emacs and org-mode (coming from SublimeText with VIntage mode and vanilla vim) so there are probably a lot of fundamental things I'm missing.  I'm also on OSX using the osx key-bindings layer.

I ran into this issue and adding @dogweather's fix didn't seem to do anything:
```
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration.
This is the place where most of your configurations should be done. Unless it is
explicitly specified that a variable should be set before a package is loaded,
you should place your code here."
(with-eval-after-load 'org
    ;; here goes your Org config :)
    ;; ....
    (setq org-agenda-files '("~/Documents/Orgs"))
    (org-defkey org-mode-map [(meta return)] 'org-meta-return)  ;; The actual fix
    )
...
```
I reloaded with `SPC f e R` and restarted Spacemacs, but when I hit `M-RET` (option+return on my mac) I still get the same behavior:

![image](https://user-images.githubusercontent.com/39137/55907258-199fde00-5b8b-11e9-9368-f0d959c1398b.png)

I'm not sure if `(meta return)` means something different than `M-RET`?  or if I need another layer (or to remove osx)?

I did look in `M-x` for `org-meta-return` and it seems to be bound by to `C-c C-x RET` which did do what I expected, so I suppose I'll use just use that for now.

**Comment by lkmokadam** [comment]
What to do if I want to set "M-RET i i" for org-insert-item?

**Comment by bebound** [comment]
I'm using latest spaceman dev with org 9.1.9

In org mode, the `M_RET` is no longer same as `,` key, it will add new headlines instead.
In other mode, it is same as `,`, has this feature changed?

**Comment by h12345jack** [comment]
> I'm super new to emacs and org-mode (coming from SublimeText with VIntage mode and vanilla vim) so there are probably a lot of fundamental things I'm missing. I'm also on OSX using the osx key-bindings layer.
> 
> I ran into this issue and adding @dogweather's fix didn't seem to do anything:
> 
> ```
> (defun dotspacemacs/user-config ()
>   "Configuration function for user code.
> This function is called at the very end of Spacemacs initialization after
> layers configuration.
> This is the place where most of your configurations should be done. Unless it is
> explicitly specified that a variable should be set before a package is loaded,
> you should place your code here."
> (with-eval-after-load 'org
>     ;; here goes your Org config :)
>     ;; ....
>     (setq org-agenda-files '("~/Documents/Orgs"))
>     (org-defkey org-mode-map [(meta return)] 'org-meta-return)  ;; The actual fix
>     )
> ...
> ```
> 
> I reloaded with `SPC f e R` and restarted Spacemacs, but when I hit `M-RET` (option+return on my mac) I still get the same behavior:
> 
> ![image](https://user-images.githubusercontent.com/39137/55907258-199fde00-5b8b-11e9-9368-f0d959c1398b.png)
> 
> I'm not sure if `(meta return)` means something different than `M-RET`? or if I need another layer (or to remove osx)?
> 
> I did look in `M-x` for `org-meta-return` and it seems to be bound by to `C-c C-x RET` which did do what I expected, so I suppose I'll use just use that for now.

Same to you, the solution can't map `M-RET` to the original one.
Hope some solutions for it.
Before that, I use `M-RET` twice...

**Comment by bshanks** [comment]
I think a workaround is to put the following into your user-config:

(evil-define-key '(normal insert) evil-org-mode-map (kbd "M-<return>") 'org-meta-return)

**Comment by roganjoshua** [comment]
So, so far nothing works for me I have tried all the suggestions here.

Anyone found a solution, I am pretty much running vanilla here

**Comment by duianto** [comment]
@roganjoshua Are you on the `master` branch?

`M-RET M-RET` calls `org-meta-return` for me on the `develop` branch.

syl20bnr said in a comment above: https://github.com/syl20bnr/spacemacs/issues/9603#issuecomment-336721310
>M-RET is a core Spacemacs key binding and also a limitation of it, in the terminal it is impossible to differentiate C-m and RET.
>
>What other key binding could we set for org-meta-return ?
>
>What pops out of my mind is to add RET key bindings to org-mode major leasder key so org-meta-return would be M-C-m C-m or M-RET RET.

and: https://github.com/syl20bnr/spacemacs/issues/9603#issuecomment-336722177
>I pushed a commit to add M-RET under major mode leader key so org-meta-return can be triggered with M-RET M-RET.
This is not an ideal solution but this is a dead end as in terminal C-m is RET.

---

The `develop` branch is the recommended branch until the next version is released (I have no insight into when that is).

#### To try the `develop` branch:
Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

**Comment by jakebox** [comment]
Just in case someone with less experience runs into this like I did -- to get back M-RET the way it was before (I was using master branch rather than develop) in the `.spacemacs` I changed this on line 260

`dotspacemacs-major-mode-emacs-leader-key (if window-system "<M-return>" "C-M-m")`
to
`dotspacemacs-major-mode-emacs-leader-key "C-M-m"`

and it was back to 'normal'. Yes, it doesn't work right in the terminal, but I only use GUI so no issue there.
