### ISSUE TITLE
gtags layer advertised keys missing

### ISSUE THREAD

**Issue by vigilancetech-com** [syl20bnr/spacemacs#9604]
#### Description :octocat:
gtags layer advertised keys missing

#### Reproduction guide :beetle:
- install emacs
- install spacemacs
- enable gtags in layers
- restart spacemacs
- look for keys (SPC ?) as found:

https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Btags/gtags#key-bindings

*Observed behaviour:* :eyes: :broken_heart:

not there (e.g. SPC m g c )

*Expected behaviour:* :heart: :smile:

key bindings should be there

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 3208cc9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(clojure html helm themes-megapack auto-completion better-defaults emacs-lisp git gtags spacemacs-ui ranger finance markdown org
         (shell :variables shell-default-height 30 shell-default-position 'bottom)
         spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XWIDGETS

#### Backtrace :paw_prints:
```

```

**Comment by smile13241324** [comment]
Can you tell me for which programming mode you are missing the gtags jump commands? I have just tried that for `clojure-mode` and it worked as expected. I have also had a look at `elisp-mode` and also there were the respective gtags commands bound.

Do you have any errors in the message buffer when spacemacs is started? This could cause some missed bindings.

**Comment by nishadsabnis** [comment]
Just wanted to say I am seeing the exact same problem too,
 I am on OS-X and using the master branch. 

 I cannot see the keybindings when in `c-mode`.  gtags layer documentation suggests that `c-mode` should be supported by default?
I can confirm that in `elisp-mode` the key bindings do show up.

Maybe I am missing something, I am quite new to spacemacs. I can create another issue if that is preferred but since this one seemed similar I thought I should give my input here before I create another one. Thanks!

**Comment by smile13241324** [comment]
@nishadsabnis @vigilancetech-com The problem you are having is that you are missing the `C-C++` layer in your dotfile if this is missing only standard emacs `C-mode` stuff is defined which does not include the `gtags` or a `major-mode` menu.

Without it you only have standard emacs stuff defined.

**Comment by nishadsabnis** [comment]
Thanks @smile13241324 that resolves the issue for me. I can now see the keybindings after adding `c-c++` to my layers. I'm sure this was in the documentation somewhere and I just missed it.  

Either ways, I am really enjoying the consistency using spacemacs coming over from emacs and evil-mode with a shoddy config that was not maintainable. Thanks!

**Comment by smile13241324** [comment]
@vigilancetech-com does that solve your issue too? In this case please consider closing this ticket.

@nishadsabnis your welcome :)

**Comment by vinurs** [comment]
Hi, i'am using the dev branch, and enable the c-c++ layer, but the keybindings seems missing

**Comment by vinurs** [comment]
it seems that it should add (spacemacs/helm-gtags-define-keys-for-mode 'c-mode)  in the user-config section

**Comment by vinurs** [comment]
sorry, there is a misspell, c/c++ should be c-c++ layer
