### ISSUE TITLE
gtags layer doesn't find tags file global creates by default

### ISSUE THREAD

**Issue by vigilancetech-com** [syl20bnr/spacemacs#9605]
#### Description :octocat:
gtags layer doesn't find tags file global creates by default

#### Reproduction guide :beetle:
- install gnu global
- Start Emacs
- install spacemacs
- enable gtags layer
- restart Emacs
- execute ggtags-create-tags with M-x
- navigate to the head of the source tree you want to tag and hit enter
- answer "n" to use ctags
- load up a source file in that tree
- position on a symbol and hit M-.
- when it asks for tags table, navigate to directory at the head of the source tree above
- hit enter

*Observed behaviour:* :eyes: :broken_heart:
can't find TAGS in that directory

*Expected behaviour:* :heart: :smile:
should find GTAGS or whatever is appropriate for GNU global.   In other words,
default name should be changed if gtags layer is installed.   GNU global
installs 3 files purportedly to enable super fast searches.   Maybe the M-.
mechanism should be changed to issue shell commands to global to take advantage
of that instead of what may be a brute force search mechanism inside spacemacs?

Either way it seems its a bit confusing to newcomers since this layer is supposed to be
an interface to GNU global (rather than the normal old emacs tags mechanism).

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 3208cc9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(clojure html helm themes-megapack auto-completion better-defaults emacs-lisp git gtags spacemacs-ui ranger finance markdown org
         (shell :variables shell-default-height 30 shell-default-position 'bottom)
         spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XWIDGETS

#### Backtrace :paw_prints:
```

```

**Comment by CeleritasCelery** [comment]
Can you reproduce the issue with stock emacs and `ggtags`?
