### ISSUE TITLE
`SPC SPC` is undefined

### ISSUE THREAD

**Issue by qleguennec** [syl20bnr/spacemacs#9612]
#### Description :octocat:
`SPC SPC` is undefined

#### Reproduction guide :beetle:
- Start Emacs
- Press `SPC SPC`

*Observed behaviour:* :eyes: :broken_heart:
- message: `SPC SPC` is undefined

*Expected behaviour:* :heart: :smile:
- `M-x` menu should pop. `M-x` menu pops fine with `M-x`. Not sure if that makes sense.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 9341e1d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion clojure command-log emacs-lisp git helm html javascript markdown org parinfer racket search-engine syntax-checking themes-megapack version-control
                 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
                 (shell :variables shell-default-shell 'eshell shell-default-position 'right shell-default-term-shell "/bin/mksh" shell-default-height 10))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
Not able to reproduce on develop. Do you have any kind of errors during start up in your message buffer? Especially void variable/function errors?

If any of these happen during loading a hook the process will be aborted and you will experience all kinds of malfunctions including missing keybindings.

**Comment by humanfactors** [comment]
I was able to reproduce on Develop. To anyone else experiencing this same issue, the solution (until we know the specifics) is to clear `auto-generate custom variable definition`. A method for doing so and also confirming you don't have any other issues in your configuration:

1. `SPC-f-e-D`
2. hit `n` until you get to the code block `;; Do not write anything past this comment. This is where Emacs will auto-generate custom variable definitions.`
3. Note any custom set variables you may wish to save.
4. Hit `b` to clear

Of course you could also just go in and clear it, but it's a worthwhile step going through and cleaning up your .spacemacs every now and then regardless.

**Comment by smile13241324** [comment]
Hmm good point I don't use the customise interface and normally end up deleting any entry that is added automatically. So this would explain why I was not able to reproduce it.

**Comment by smile13241324** [comment]
@qleguennec do you still have that issue after clearing your custom config? Just want to either close the ticket or have another look.

**Comment by carlosnsr** [comment]
Was able to reproduce on `master` commit c7a103a7
I followed the steps suggested by @humanfactors (thank you) 

1.  cleared `auto-generate custom variable definition`
2. restarted spacemacs
3. pressed `SPC SPC` => Still got `SPC SPC is undefined`

Suggestions?

**Comment by humanfactors** [comment]
@carlosnsr what is your [System Info](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)? Have you tried updating your dotspacemacs to the template `SPACE -  f e D` and checked there were no issues with the dotfiles (or tried with a completely clean init?).

**Comment by achikin** [comment]
I see this again after updating to Emacs 26.1

**Comment by smile13241324** [comment]
@achikin would you mind posting your dotfile? Just to make sure that this is not caused by any failing config steps.

When you say you experience it again after an emacs update does that mean you don't had that problem on an older emacs and that the problem disappears when you downgrade again?

Btw on which OS are you running emacs?

**Comment by gdkrmr** [comment]
#11263 may be related?

**Comment by dariusbdockery** [comment]
> In my case having org agenda reference in custom-set-variables with a missing file caused this. Deleting this line fixed 'SPC SPC'.

I had a similar issue where I was originally getting an error `[yas] Check your `yas-snippet-dirs': c:/Users/username/.emacs.d/elpa/yasnippet-20190502.2214/snippets is not a directory`. I tried to fix this by redefining the yas-snippet-dirs variable to this: `(setq yas-snippet-dirs "c:/Users/username/.emacs.d/private/snippets")`. 

After resetting the variable I lost my SPC SPC (M-x) command. Looking at the *Messages* buffer, it read `yas-reload-all: Wrong type argument: listp, "c:/Users/username/.emacs.d/private/snippets"`. 

Once I commented this line out, my SPC SPC key was available as M-x once again. I think I will try to change it through the customization menu for now. 

I am not sure if this is useful, but hopefully it can help with identifying the solution.

**Comment by duianto** [comment]
Thanks for posting your findings, they could be helpful for someone else with the same or a similar issue.

The yasnippet issue has been fixed on the develop branch.
There's more info in this issue:
yas-snippet-dirs does not exist after each upgrade, causing warning #10316

**Comment by MoHKale** [comment]
I got the same problem when setting projectile-project-search-path to a directory which doesn't exist. (because I use the same config on both my linux and windows computer, but never use my user home folder on windows). Regardless, I fixed it by just making that folder.

**Comment by mattiaslundberg** [comment]
@MoHKale Thank you so much for sharing your solution! It solved the problem for me.

**Comment by gdkrmr** [comment]
This solved it for me:

> In my case having org agenda reference in custom-set-variables with a missing file caused this. Deleting this line fixed 'SPC SPC'.

**Comment by akraemer007** [comment]
I had to remove my ipythonnotebook package to get mine running

**Comment by gdkrmr** [comment]
I just wanted to leave this here for documentation: I recently installed `spacemacs` on a raspberry pi 4 and ran into this problem, because I copied the config file without the agenda files and could observe that the `which-key` key map for `SPC` (and probably others) took ages (~15s) to show. I have resolved the problem again as described above and `which-key` is performant again. It is kind of weird, that `org-mode` can break a session that way.

**Comment by IgorGee** [comment]
Not sure if I should open a new issue for this, but adding this line:

`(kill-buffer "*scratch*")`

will break `SPC SPC` and cause the aforementioned issue.

**Comment by smile13241324** [comment]
Nope please use the old issue this will prevent the bot from closing it.

As to your issue please check the logs for error messages related to your
command it can be that scratch is not existing at this moment which will
cause an error and subsequently aboard the loading process leaving you with
an non defined emacs spacemacs hybrid.

This should also trigger a warning in your home buffer.

**Comment by IgorGee** [comment]
@smile13241324 

I'm new to emacs and spacemacs so I'm not sure if I'm looking in the right places. But here's what I got from **\*Messages\***:

```
Spacemacs is ready.
save-current-buffer: No buffer named *scratch*
```

I forgot to mention, the `(kill-buffer "*scratch*")` command was put in `dotspacemacs/user-config`.

**Comment by smile13241324** [comment]
The message no buffer named scratch is the text of an elisp error. Thats
the equivalent of an uncatched exception in OOP.

You need to guard your config code not to try to kill the buffer if its not
existing.

Out of curiosity what are you trying to achieve with the failing function?

**Comment by IgorGee** [comment]
Not much. It's a minor OCD thing because I have no use for the "scratch" buffer, so I didn't want to see it when I start up emacs.

**Comment by smile13241324** [comment]
Normally you should not see it when you start spacemacs. Normally you can set spacemacs to resume your config, for me spacemacs always starts on my org project page. I think when you do nothing it just starts in the home buffer. All of this can be done with the preset config values in your dotfile. 

See below from the dotfile template:
```elisp
;; If non-nil then the last auto saved layouts are resumed automatically upon
   ;; start. (default nil)
   dotspacemacs-auto-resume-layouts nil
```

**Comment by IgorGee** [comment]
Ah, when I said "see", I meant that I see it in my list of buffers when I hit `SPC b b`.

I do go to the home buffer upon startup.

**Comment by duianto** [comment]
@IgorGee This might be what your looking for:
https://unix.stackexchange.com/questions/19874/prevent-unwanted-buffers-from-opening

The last answer states that if all buffers are killed then the scratch or messages buffers might be recreated automatically by Emacs.

**Comment by IgorGee** [comment]
@duianto It is!

Thanks a lot!
