### ISSUE TITLE
`search-engine` breaks issue reporting

### ISSUE THREAD

**Issue by qleguennec** [syl20bnr/spacemacs#9613]
#### Description :octocat:
`search-engine` layer breaks issue reporting

#### Reproduction guide :beetle:
- Start Emacs
- report issue: `SPC h I`
- edit issue
- submit `C-c C-c`

*Observed behaviour:* :eyes: :broken_heart:
this message is displayed: `browse-url-generic: No browser defined (‘browse-url-generic-program’)`

*Expected behaviour:* :heart: :smile:
- should open a new tab on github with the issue filled

#### Reproduction guide :beetle:
- Start Emacs
- remove `search-engine` configuration in:
```elisp
(defun dotspacemacs/user-config ()
  (setq browse-url-browser-function 'browse-url-generic
        engine/browser-function 'eww-browse-url))
```
- restart emacs
- edit issue
- submit `C-c C-c`

*Observed behaviour:* :eyes: :broken_heart:
- issue is opened, everything ok

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 9341e1d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion clojure command-log emacs-lisp git helm html javascript markdown org parinfer racket search-engine syntax-checking themes-megapack version-control
                 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
                 (shell :variables shell-default-shell 'eshell shell-default-position 'right shell-default-term-shell "/bin/mksh" shell-default-height 10))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by CeleritasCelery** [comment]
So does this occur only with just the `search-engine` layer installed or do you have to add the configuration you pointed out in the `dotspacemacs/user-config`?

**Comment by qleguennec** [comment]
@CeleritasCelery in the two cases the `search-engine` layer is installed, but on the second case I remove the additional configuration.

**Comment by CeleritasCelery** [comment]
And does removing the additional configuration fix the problem?

**Comment by smile13241324** [comment]
I have tried to reproduce that on my emacs 25.3.1 on develop, but had no issues with my config including `search-engine`. Can you confirm that this issue still appears on latest develop?
