### ISSUE TITLE
Symbol's function definition is void: evil-org-mode in org-mode

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#9618]
#### Description :octocat:
Getting the following when opening `org-mode` files:

`run-hooks: Symbol’s function definition is void: evil-org-mode`

It seems that evil-org-mode is borked.

#### Reproduction guide :beetle:
- Start Emacs
- Open scratch buffer
- enable `org-mode`
- See `Messages` Buffer.

*Observed behaviour:* :eyes: :broken_heart:

`evil-org-mode` is undefined. 
*Expected behaviour:* :heart: :smile:

`evil-org-mode` should be set up.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. bec8280)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(bibtex nginx twitter graphviz ivy asciidoc speed-reading swift plantuml
        (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-show-snippets-in-popup t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets")
        better-defaults emacs-lisp
        (git :variables git-magit-status-fullscreen t)
        github gnus version-control
        (markdown :variables markdown-live-preview-engine 'vmd)
        syntax-checking
        (latex :variables latex-enable-auto-fill t)
        (colors :variables colors-colorize-identifiers 'all colors-enable-nyan-cat-progress-bar t)
        docker
        (ansible :variables ansible-auto-encrypt-decrypt t)
        puppet evil-commentary
        (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
        fasd finance floobits xkcd autohotkey csv nlinum
        (c-c++ :variables c-c++-enable-clang-support t)
        (clojure :variables clojure-enable-fancify-symbols t)
        major-modes go
        (haskell :variables haskell-enable-ghci-ng-support t haskell-enable-shm-support t haskell-enable-hindent-style "andrew-gibiansky")
        html java
        (javascript :variables javascript-disable-tern-port-files t)
        (python :variables python-enable-yapf-format-on-save t python-fill-column 80 python-auto-set-local-pyenv-version 'on-visit python-auto-set-local-pyvenv-virtualenv 'on-visit python-sort-imports-on-save t python-test-runner
                '(nose pytest))
        racket
        (ruby :variables ruby-version-manager `rvm)
        ruby-on-rails
        (rust :variables rust-enable-rustfmt-on-save t)
        scala shell-scripts
        (restclient :variables restclient-use-org t)
        themes-megapack tmux vim-empty-lines spotify pandoc vagrant
        (ibuffer :variables ibuffer-group-buffers-by 'projects)
        semantic deft
        (shell :variables shell-default-shell 'ansi-term shell-default-position 'bottom shell-default-height 30 shell-default-term-shell "/bin/zsh")
        erc chrome d emoji gtags prodigy evernote
        (org :variables org-enable-github-support t org-enable-reveal-js-support t)
        search-engine evil-little-word yaml sql nim ipython-notebook lua scheme purescript sml common-lisp ranger dash spell-checking jabber cscope vinegar rcirc games react php vimscript geolocation idris
        (elm :variables elm-reactor-port "3000" elm-reactor-address "0.0.0.0")
        elixir
        (typography :variables typography-enable-typographic-editing nil)
        evil-cleverparens pdf-tools imenu-list slack systemd command-log
        (terraform :variables terraform-auto-format-on-save t)
        pass parinfer)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS LIBSYSTEMD LCMS2

**Comment by robbyoconnor** [comment]
FYI -- the git revision is bec82803f61c4783da1a8f4c9c0492ee7bba8dcc - I have a small fix from #9600 which I cherry-picked that should not affect this.

**Comment by robbyoconnor** [comment]
FYI -- the git revision is ca28bde0497d5c68ceeb4d943630d91caa79b587 - I have a small fix from #9600 which I cherry-picked that should not affect this.

**Comment by robbyoconnor** [comment]
@Somelauw, should I report this upstream?

**Comment by Somelauw** [comment]
@robbyoconnor I'm not sure what happened, but if this issue occurs without spacemacs, then sure.

**Comment by bmag** [comment]
Definitely an upstream bug. The following produces the same evil-org-mode void-function error on Emacs 25.2:

- assuming evil-org-mode was installed through `M-x package-install` or equivalent
- `emacs -Q`
- evaluate in scratch buffer:
```elisp
(package-initialize)
(add-hook 'org-mode-hook 'evil-org-mode)
```

**Comment by robbyoconnor** [comment]
@bmag  This is apparently Emacs 27 -- I run using the emacs-snapshot ppa and it's tracking `master`

**Comment by robbyoconnor** [comment]
I didn't even realize they upped the version

**Comment by bmag** [comment]
Added new label for 27, even though it's probably a long way off. If someone can figure out if this issue affects 26 or just 27 it'd be nice.

**Comment by robbyoconnor** [comment]
I don't have access to Emacs 26 anymore...so can't check that sadly...

**Comment by kostajh** [comment]
Hmm, I'm seeing the same thing on Emacs 25.2 on MacOS.

**Comment by Somelauw** [comment]
I've just tried it myself on the latest Emacs snapshot with a minimal config and was unable to reproduce.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 07014dee)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(ivy better-defaults emacs-lisp org)
```
- System configuration features: JPEG PNG SOUND DBUS GSETTINGS NOTIFY FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by Somelauw** [comment]
Here are some questions that might help in tracking this bug down:

- Do you get to see any other errors/warnings in \*Messages\*?
- Do you have any additional org-mode configuration in your .spacemacs file?
- What happens if you try to evaluate `(require 'evil-org)` in a scratch buffer (press `C-x C-e`)?
- If that works, what happens if you type `M-x evil-org-mode`?
