### ISSUE TITLE
[Question] how can i update selective packages by spacemacs?

### ISSUE THREAD

**Issue by lsytj0413** [syl20bnr/spacemacs#9622]
such as, when i want update some packages but keep another packages version, how can i do this with spacemacs [Update Packages] button?

**Comment by chasinglogic** [comment]
By adding the packages you don't want to update to the variable 
```
;; A list of packages that cannot be updated.
   dotspacemacs-frozen-packages '()
```

**Comment by lsytj0413** [comment]
3ks @chasinglogic
