### ISSUE TITLE
how can i disable vi-tilde-fringe on start?

### ISSUE THREAD

**Issue by lancelock** [syl20bnr/spacemacs#9625]
as the title

**Comment by zhongke** [comment]
Try to exclude the package "vi_tilde-fringe" in .spacemacs file "dotspacemacs-excluded-packages"

**Comment by lancelock** [comment]
thanks
it works

**Comment by chasinglogic** [comment]
@lancelock You can close this issue to remove it from the bug tracker to help the maintainers out!
