### ISSUE TITLE
Some themes from themes-megapack are missing

### ISSUE THREAD

**Issue by achikin** [syl20bnr/spacemacs#9626]
#### Description :octocat:
Some of the themes in theme-megapack are not installed properly
#### Reproduction guide :beetle:
- Start Emacs
- add themes-megapack to layers list
- restart emacs
- wait for the layer to be installed
- restart emacs

*Observed behaviour:* :eyes: :broken_heart:
The following error shows up on every further emacs start
```
Found 4 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: firebelly-theme@themes-megapack... [1/4]
Package firebelly-theme is unavailable. Is the package name misspelled?
--> installing package: niflheim-theme@themes-megapack... [2/4]
Package niflheim-theme is unavailable. Is the package name misspelled?
--> installing package: pastels-on-dark-theme@themes-megapack... [3/4]
Package pastels-on-dark-theme is unavailable. Is the package name misspelled?
--> installing package: tronesque-theme@themes-megapack... [4/4]
Package tronesque-theme is unavailable. Is the package name misspelled?
```
*Expected behaviour:* :heart: :smile:
No error messages

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html go sql
      (elm :variables elm-format-command "elm-format-0.18")
      javascript helm auto-completion better-defaults emacs-lisp git clojure evil-cleverparens themes-megapack markdown)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by duianto** [comment]
They have been removed from melpa (missing/outdated licenses), and from the Spacemacs develop branch.

There's more info in this PR: Remove themes that were deleted from Melpa #9470

The current solution on the master branch is to exclude them:
```
   dotspacemacs-excluded-packages '(firebelly-theme
                                    niflheim-theme
                                    pastels-on-dark-theme
                                    tronesque-theme)
```

**Comment by achikin** [comment]
@duianto thank you for your help!

**Comment by 9mm** [comment]
So if the issue is closed and the themes are removed, how come we still have to exclude them? (I'm getting the same error)

**Comment by duianto** [comment]
@9mm Spacemacs has two branches, `master` and `develop`, this issue has only been fixed on the `develop` branch.

The next major release of Spacemacs will incorporate changes from the `develop` branch to the `master` branch. I'm guessing that this might be one of them. I have no insight into when the next version will be released.
