### ISSUE TITLE
Issue submission does not work without markdown layer

### ISSUE THREAD

**Issue by achikin** [syl20bnr/spacemacs#9627]
#### Description :octocat:
Can not submit an issue using `SPC h I` if `markdown` layer is not installed

#### Reproduction guide :beetle:
- Start Emacs
- Remove `markdown` layer from the layers list
- Restart Emacs
- Press `SPC h I` to create a new issue report
- Fill the issue report
- Press `C-c C-c` to submit the issue

*Observed behaviour:* :eyes: :broken_heart:
`Symbol's function definition is void: markdown-mode` message uppears in the minibuffer
When you press `C-c C-c` to submit an issue `C-c C-c is undefined` message appears in the minibuffer 

*Expected behaviour:* :heart: :smile:
The browser is opened and issue is submitted to github

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html go sql
      (elm :variables elm-format-command "elm-format-0.18")
      javascript helm auto-completion better-defaults emacs-lisp git clojure evil-cleverparens themes-megapack markdown)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by duianto** [comment]
This issue has been fixed on the develop branch, and the report issue buffer is now using `text-mode` instead of `markdown-mode`, so it should work without the `markdown` layer.
Here's the commit that fixed it: https://github.com/syl20bnr/spacemacs/pull/9130/commits/d5e2ce367573536df3d66fb2045a5ae16ca05b08
