### ISSUE TITLE
cannot choose from helm find-file actions just after emacs is started.

### ISSUE THREAD

**Issue by vibrys** [syl20bnr/spacemacs#9631]
#### Description :octocat:
cannot choose from helm find-file actions just after emacs is started.
I'm running fresh spacemacs (not spacemacs-base).

#### Reproduction guide :beetle:
- Start Emacs
- SPC f f  (helm-find-files)
- display actions for current file (does not matter which file is currently chosen). You'll see all the actions list in separate emacs buffer
- press 's' key

*Observed behaviour:* :eyes: :broken_heart:
following error message is displayed:
Helm issued errors: helm-match-from-candidates in source `Actions': wrong-type-argument (stringp nil)

*Expected behaviour:* :heart: :smile:
actions' list should be narrowed down to those which have 's' in their name.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: nil (rev. ca28bde)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GCONF GSETTINGS NOTIFY GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11

#### Backtrace :paw_prints:
I'm able to display the backtrace, but unfortunatelly cannot copy it, because it dissapears when I'm continuing to press any keys (helm is still in action).

**Comment by vibrys** [comment]
for the sake of completeness, this problem DOES NOT persist with vanilla: emacs + helm.

regards,
Mat

**Comment by bmag** [comment]
Can't repro with latest Spacemacs and Helm. "display actions for current file" means pressing `C-z`?

**Comment by duianto** [comment]
Confirmed on both the latest master and develop branches with all packages updated.

This seems to be a duplicate of this issue:
spacemacs/helm-find-files (SPC f f) not correctly autoloading #7325

The next to last comment on that issue might be describing the source or a clue to what's going on.

That issue explains the behaviour I'm seeing. If the helm find files, helm action buffer, is opened as the first helm buffer, then the issue occurs. But as soon as another helm buffer has been opened. For example helm mini `SPC b b`, then the helm find files, helm action buffer, is able to narrow down the results based on the typed pattern.

The helm find files buffer is always able to narrow down the candidates to the search pattern, without showing the error message. But if helm find files was the first opened helm buffer, then it's possible to switch `C-z` between the helm action buffer and helm find files, and searching works for files but not actions.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 95699ee6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 colors emacs-lisp git helm markdown org spell-checking themes-megapack version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by bmag** [comment]
Thanks for linking the issue. I was able to repro the issue by setting `dotspacemacs-helm-use-fuzzy` to `always` (I usually set it to `source`, but the default is `always`).

**Comment by bmag** [comment]
Probably a consequence of #5001

**Comment by bmag** [comment]
Couldn't copy the backtrace buffer, so here's a screenshot:
![backtrace-screenshot](https://user-images.githubusercontent.com/4334375/30740734-d65ba62c-9f9a-11e7-9024-b72ba0fd5eaf.png)

**Comment by bling** [comment]
so i took a quick look at this and looks like certain sources do not have the `fuzzy-match` property set, which causes `helm--in-fuzzy` to be false, causing the function `helm--fuzzy-match-maybe-set-pattern` to never populate the cache.

one fix is to advise that function so that the flag is always true, but it's probably better to revert my original PR and explicitly set all the variables to `t` instead.

**Comment by smile13241324** [comment]
@vibrys I have merged a fix for your issue, would you mind having a look on latest develop and close your issue if it is fixed.

**Comment by vibrys** [comment]
Yes, I'll do it

**Comment by vibrys** [comment]
that works. Thank You
