### ISSUE TITLE
How to map <escape> to evil-mc-undo-all-cursors?

### ISSUE THREAD

**Issue by elzii** [syl20bnr/spacemacs#9633]
I'm trying to recreate a list of mappings that will be friendly for users coming from sublime text. 

I would like `<escape>` to do what `g r u` does.

I tried:

`(evil-define-key 'normal evil-mc-key-map (kbd "<escape>") 'evil-mc-undo-all-cursors)`

**Comment by elzii** [comment]
Disregard. Had a typo. The above should work!

**Comment by elzii** [comment]
Reopening as this causes some issues after further use. It remaps `<escape>` in normal mode preventing normal behavior (leaving command mode, etc). 

Is there a way to only map this keybind when `evil-mc-mode` is active?

**Comment by CeleritasCelery** [comment]
You should ask this over at evil-mc

**Comment by kandros** [comment]
@elzii I'm using this and it works

(use-package evil-mc
  :ensure t
  :defer t
  :diminish evil-mc-mode "ⓒ"
  :init (global-evil-mc-mode t)
  :init (add-hook 'after-init-hook #'global-evil-mc-mode)
  :bind (:map evil-mc-key-map
              ("C-g" . evil-mc-undo-all-cursors)
              ))
  :config
  (progn
    (evil-define-key 'normal evil-mc-key-map (kbd "<escape>") 'evil-mc-undo-all-cursors))

cannot remember the difference in binding in `:config` or `:bind` at the moment
