### ISSUE TITLE
Search failed. This means there is unmatched expression somewhere or we are at the beginning/end of file

### ISSUE THREAD

**Issue by leolle** [syl20bnr/spacemacs#9634]
Every time I type _(_ at a buffer, emacs will automatically give me _()_.
Then I press C-f to move the cursor forward inside the parentheses, hit C-d to delete the right paretheses, the buffer will freeze for half a minute and show me the message: Search failed. This means there is unmatched expression somewhere or we are at the beginning/end of file.

Can anybody help me to disable this annoying thing? Thank you.

**Comment by chasinglogic** [comment]
This is caused by smartparens mode. https://github.com/Fuco1/smartparens

You can disable the package by adding it to `dotspacemacs-excluded-packages` but I would check the following .spacemacs settings first:

```
   ;; If non-nil smartparens-strict-mode will be enabled in programming modes.
   ;; (default nil)
   dotspacemacs-smartparens-strict-mode nil
   ;; If non-nil pressing the closing parenthesis `)' key in insert mode passes
   ;; over any automatically added closing parenthesis, bracket, quote, etc…
   ;; This can be temporary disabled by pressing `C-q' before `)'. (default nil)
   dotspacemacs-smart-closing-parenthesis nil
```

You may find that if one is one it could be causing the problem. Note that if you disable smartparens they may not auto close and you'll want to investigate other options like electric-pair-mode.

**Comment by leolle** [comment]
@chasinglogic Thanks for response.
My default setting is 
```
   ;; If non-nil smartparens-strict-mode will be enabled in programming modes.
   ;; (default nil)
   dotspacemacs-smartparens-strict-mode nil
   ;; If non-nil pressing the closing parenthesis `)' key in insert mode passes
   ;; over any automatically added closing parenthesis, bracket, quote, etc…
   ;; This can be temporary disabled by pressing `C-q' before `)'. (default nil)
```
I added your last line on my configure and the following message shows up:
```
Search failed. This means there is unmatched expression somewhere or we are at the beginning/end of file.
Error running timer `sp-show--pair-function': (beginning-of-buffer)
```

**Comment by chasinglogic** [comment]
@leolle As a debugging step can you add smartparens to your `dotspacemacs-excluded-packages` ?

I wouldn't recommend leaving it like this but it'd be an easy way to tell if that's the actual performance problem your running into. (I too have smartparens show this message from time to time but don't experience the freezes that you are).

Additionally we can tell exactly what's hanging up using one of two methods:

### 1. Profiling

Emacs has a built in profiler that you can start at any time using `M-x profiler-start`. You can run just cpu profiling or cpu+mem (usually Emacs hang ups are cpu bound not memory bound). If you start it just before triggering the bug that would give us the best info. After the freeze has finished and Emacs is mostly back to normal run `M-x profiler-report` and you'll get a buffer with a bunch of output, if you could post that in the comments that would be helpful. Remember that after you're done to run `M-x profiler-stop` you do take a performance hit for running the profiling.

### 2. Kill Signals

If the freeze is lasting long enough you can actually send the emacs process a special kill signal that  will cause it to crash the current function call and spit out a backtrace. The instructions for doing so are here: https://emacs.stackexchange.com/questions/506/debugging-a-frozen-emacs#answer-649

I've copy and pasted the relevant answer:

`$ kill -SIGUSR2 <emacs_pid_goes_here>`

This will make Emacs attempt to break out of its current loop into the Lisp debugger.

Or use this one liner without typing emacs pid manually:

`$ ps aux | grep -ie emacs | grep -v grep | awk '{print $2}' | xargs kill -SIGUSR2`

Alternatively, if killall is available:

`$ killall -USR2 emacs`

**Comment by leolle** [comment]
@chasinglogic Hi, below is the report content:
'''
- timer-event-handler                                   1,070,720,899  88%
 - byte-code                                            1,070,659,523  88%
  - apply                                               1,070,644,413  88%
   - sp-show--pair-function                             1,027,103,387  85%
    + #<compiled 0x1a01df9>                             1,024,003,361  84%
    - sp--get-allowed-regexp                                  997,820   0%
     - sp--get-allowed-pair-list                              624,112   0%
      + sp--do-action-p                                       618,912   0%
     + sp--strict-regexp-opt                                  359,148   0%
       apply                                                    5,200   0%
       mapcar                                                   4,160   0%
    + sp--get-stringlike-regexp                               801,728   0%
    + sp--get-allowed-pair-list                               636,448   0%
    + sp--get-opening-regexp                                  319,196   0%
    + sp--get-closing-regexp                                  235,280   0%
    + sp--looking-back                                         68,150   0%
   + semantic-idle-scheduler-function                      33,120,622   2%
   + company-idle-begin                                     5,368,070   0%
   + flycheck-handle-idle-change                            3,621,626   0%
   + #<compiled 0x1bca32d>                                  1,416,148   0%
     jit-lock-context-fontify                                   4,160   0%
   + hl-paren-highlight                                         4,144   0%
     auto-revert-buffers                                        1,040   0%
 + timer-activate-when-idle                                    35,360   0%
 + timer-inc-time                                              12,496   0%
 + timer-activate                                               7,280   0%
   timer-until                                                  1,040   0%
+ command-execute                                          83,190,938   6%
+ redisplay_internal (C function)                          47,734,276   3%
+ delete-selection-pre-hook                                 2,333,332   0%
+ xselect-convert-to-string                                   393,392   0%
+ winner-save-old-configurations                              335,008   0%
+ linum-update-current                                        316,070   0%
+ comint-output-filter                                        248,259   0%
+ company-post-command                                        121,604   0%
+ sp--save-pre-command-state                                   90,528   0%
+ flycheck-handle-signal                                       43,940   0%
+ url-http-generic-filter                                      41,454   0%
+ yas--post-command-handler                                    32,384   0%
+ global-hl-line-highlight                                      8,480   0%
+ which-key--hide-popup                                         5,200   0%
+ global-font-lock-mode-check-buffers                           2,080   0%
+ global-evil-search-highlight-persist-check-buffers            2,080   0%
+ global-vi-tilde-fringe-mode-check-buffers                     2,080   0%
  xselect-convert-to-targets                                    2,080   0%
+ hl-paren-initiate-highlight                                   1,056   0%
+ sp--pair-overlay-post-command-handler                           960   0%
+ flycheck-display-error-at-point-soon                            720   0%
  ...                                                               0   0%
'''
If I still want to use smartparent(yes, it does help me a lot), what should I do?

**Comment by chasinglogic** [comment]
So at this point we have great debugging information but it all points to smartparens being the issue not spacemacs. I would recommend taking this info upstream to smartparens. Additionally I would want to know:

- Version of Emacs
- Version of Spacemacs
- Version of Smartparens (maybe you need to update the package)
- Does this happen in all major modes? If not which ones does it effect?

**Comment by leolle** [comment]
# GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8) of 2016-07-01 on weiwu-VirtualBox

# Spacemacs v.0.105.21

smartparens is an installed package.

     Status: Installed in `~/.emacs.d/elpa/smartparens-20160619.322/' (unsigned).
    Archive: n/a
    Version: 20160619.322
   Requires: dash-2.12.1, cl-lib-0.3
    Summary: Automatic insertion, wrapping and paredit-like navigation with user defined pairs.
    Other versions: 20170917.104 (melpa-cn).

[back]

My daily usage of emacs is org mode, python mode and Inferior Python mode, this issue only happens at working on python.

**Comment by jbharat** [comment]
I am getting a similar message when the cursor is on '>' character in '=>' in react-layer.

**Comment by MaskRay** [comment]
Very annoying. When I type a `(` in c++-mode, it shows up every time

**Comment by nfedyashev** [comment]
Can't provide the exact steps to reproduce(yet)
but this message/warning freezes my spacemacs pretty regularly.

Happens only in Clojure mode in my case

**Comment by ozkc** [comment]
This happened to me when I was in rspec mode trying to run tests for the current file. I was able to get rid of this message and run my tests, after I enabled and disabled rspec mode in some another buffer.

**Comment by beyondpie** [comment]
Very annoying for me too.  I notice that it might stop Emacs if the buffer content is quite large.

**Comment by portalreaper** [comment]
This suddenly started happening to me in org mode.

**Comment by Dar-BN** [comment]
I often, when editing in org-mode seem to run in to a pause when I enter the `)` character. When I toggle debug-on-quit, I can see that it is stuck looking for. the matching open parenthesis in `spacemacs/smart-closing-parenthesis`. 

I've tried turning off smartparens, but that doesn't seem to have any effect on this function which seems to always search for a matching open parens.

I wouldn't mind if this was in elisp or something, but when typing in things in org-mode, when I'm taking notes, it is really annoying when it happens, totally ruining the flow of the typing that I'm doing.

If it at least respected the smartparens on or off it that would be OK and I could disable it for the buffer, but it doesn't appear to.

I'm using the latest develop branch and also emacs 28,  but have experienced it for a long time, just put up with it.

Please consider adding some sort of test at the start of the function to check if smartparens is enabled or not, or at least some spacemacs specific variable is set or not. 

I realise now after looking at this that there is an initialization toggle, but that seems to be the wrong level to have it at?
