### ISSUE TITLE
Haml flychecker throws error in every file

### ISSUE THREAD

**Issue by ar1a** [syl20bnr/spacemacs#9635]
#### Description :octocat:
Haml flychecker throws errors all the time about invalid lisp syntax

```
Try installing a more recent version of haml, and please open a bug report if the issue persists in the latest release.  Thanks!
Undo branch point!
Suspicious state from syntax checker haml: Flycheck checker haml returned non-zero exit code 1, but its output contained no errors: Exception on line 341: no implicit conversion of nil into String
  Use --trace for backtrace.
```

#### Reproduction guide :beetle:
- Start Emacs
- Create a haml file (test.html.haml)
- Fill with whatever you want (for example, just a header)
- Observe error

*Observed behaviour:* :eyes: :broken_heart:
No linting, error pops up whenever I stop typing

*Expected behaviour:* :heart: :smile:
Linting

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(windows-scripts lua markdown yaml rust
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
                 better-defaults
                 (c-c   :variables c-c  -enable-clang-support t)
                 react emacs-lisp evil-commentary git helm html javascript org ruby php ruby-on-rails semantic spell-checking syntax-checking themes-megapack erc pandoc)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by CeleritasCelery** [comment]
Doesn't sound like a Spacemacs problem. Sounds like a problem with your hamel installation. You should open an issue at flycheck if anything.

**Comment by Snorflake** [comment]
flycheck/flycheck#1334
