### ISSUE TITLE
The `org-journal' package features cannot be used

### ISSUE THREAD

**Issue by Anth0rx** [syl20bnr/spacemacs#9649]
#### Description :octocat:
The `org-journal` package features cannot be used, albeit being installed by the `org` layer.

#### Reproduction guide :beetle:
- Start Emacs
- Try typing `M-x org-journal-new-entry` or `C-c C-j`

*Observed behaviour:* :eyes: :broken_heart:
The entry won't show up or rather "Command not found" is displayed

*Expected behaviour:* :heart: :smile:
Both commands should create a new file in `org-journal-mode`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 90d3ac1e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python lua
        (latex :variables latex-enable-auto-fill nil latex-build-command "LaTeX")
        major-modes helm auto-completion emacs-lisp git github markdown org
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        syntax-checking)
```
- System configuration features: XPM PNG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB GTK3 X11

**Comment by CeleritasCelery** [comment]
are you sure it's installed?

**Comment by Anth0rx** [comment]
By looking at the `package.el` file in `layers/+emacs/org` it appears to be installed. But doing a manual `M-x package-install org-journal` installs the package, which is properly usable afterwards. Although adding `org-journal` to the `dotspacemacs-additional-packages` list won't install it.

**Comment by simendsjo** [comment]
I'm having the same problem. Even if I install it using package-install and add it to dotspacemacs-additional-packages and restart, spacemacs will delete the orphaned package, and then say that org-journal isn't installed. I'm using emacs 25.3.1 and spacemacs develop 07014deead544c51fa6a826e91fe2ef05bf04323.

**Comment by jonbash** [comment]
Same here. on latest `develop`, Spacemacs keeps deleting `org-journal` on startup.

**Comment by x61** [comment]
Also on 'develop' branch but can't get 'org-journal' to work

**Comment by lepisma** [comment]
Same issue here. Looks like org journal is a _togglable_ feature now so we need to do this while adding org layer:
```emacs-lisp
(org :variables org-enable-org-journal-support t)
```

See [the layer readme](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bemacs/org#org-journal-support) for more details.

**Comment by schmeisers** [comment]
I'm also having this issue even after adding the layer via

    (org :variables org-enable-org-journal-support t)

**Comment by duianto** [comment]
The `org-journal-new-entry` command is available and works for me from the `SPC SPC` HELM M-x buffer, and it lists the key binding `SPC a o j j` which also works.

@jonbash Spacemacs deletes packages as orphans if:
- They aren't part of a layer.
- They aren't listed in the `dotspacemacs-additional-packages` variable.
- The `dotspacemacs-install-packages` is set to the default value: `'used-only`, if it's changed to `'used-but-keep-unused` then they will remain installed.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 692cc886b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm imenu-list
            (javascript :variables javascript-backend 'lsp)
            markdown multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/notes.org")
                 org-enable-org-journal-support t)
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by komali2** [comment]
I have this issue

- Emacs version (`M-x emacs-version`): GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-09-16

Spacemacs v.0.200.13

**Comment by duianto** [comment]
You could try the `develop` branch, it's the recommended branch until the next version is released.

#### To try the `develop` branch:
Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

**Comment by vinaychandranp** [comment]
I also have the same issue, and I'm on the develop branch. I added the lines as specified in the org-journal documentation, and I get `SPC a o j is undefined`. If i try to install with `SPC SPC package-install org-journal`, it get's installed, but Spacemacs deletes it again on restart (even if it's added to the `dotspacemacs-additional-packages`)

`GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.6 (Build 19G73)) of 2020-08-11`

`Spacemacs 0.300.0@27.1 (spacemacs) Commit 39df5e26b6a2c626b25a2ee68904ce02c2dc023d`

**Comment by duianto** [comment]
`SPC a o j` seems to be working for me:

![emacs_2020-09-07_17-49-48](https://user-images.githubusercontent.com/13420573/92403916-b96feb80-f132-11ea-98b1-343b3817b58e.png)

With the `org-enable-org-journal-support` layer variable enabled:
```elisp
(org :variables org-enable-org-journal-support t)
```

in the `dotspacemacs-configuration-layers` list, near the top of `.spacemacs`.

Tested on the latest `develop` branch, with updated packages.

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 59f72709b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey command-log emacs-lisp git haskell helm
            (javascript :variables javascript-backend 'lsp)
            lsp multiple-cursors
            (org :variables org-enable-org-journal-support t)
            (python :variables python-backend 'lsp python-lsp-server 'mspyls)
            shell version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>
