### ISSUE TITLE
[develop] CMake IDE automatic flycheck-buffer raise error when startup

### ISSUE THREAD

**Issue by LukeXuan** [syl20bnr/spacemacs#9650]
#### Description :octocat:
CMake IDE will run flycheck-buffer in all buffers for c/c++, however the spacemacs enable the flycheck-mode in post init stage. Therefore a flycheck error "not enabled" will arise if buffers of c/c++ file are present from startup.

#### Reproduction guide :beetle:
- Start Emacs
- enable c-c++, syntax-checking and related layers, open some c/c++ files.
- restart Emacs

*Observed behaviour:* :eyes: :broken_heart:
In the startup messages it will reflect the error.

*Expected behaviour:* :heart: :smile:
No errors should be raised.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 71a0d418)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(ruby csv go html javascript markdown helm
      (org :variables org-enable-github-support t org-enable-reveal-js-support t)
      (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-tab-key-behavoir 'complete)
      better-defaults osx emacs-lisp git
      (latex :variables latex-build-command "LatexMk")
      (c-c++ :variables c-c++-enable-clang-support t)
      python
      (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
      (spell-checking :variables spell-checking-enable-by-default nil)
      (syntax-checking :variables syntax-checking-enable-by-default t syntax-checking-enable-tooltips t)
      coq)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES
```

**Comment by CeleritasCelery** [comment]
Does this have any effects other then the message?

**Comment by LukeXuan** [comment]
It seems not, too me.
