### ISSUE TITLE
Suspicious state from syntax checker gometalinter (go layer, gometalinter, gometalinter-flycheck)

### ISSUE THREAD

**Issue by Crazy-Owl** [syl20bnr/spacemacs#9654]
#### Description :octocat:

When using gometalinter with spacemacs, I encounter error messages like the following.

> Suspicious state from syntax checker gometalinter: Flycheck checker gometalinter returned non-zero exit code 3, but its output contained no errors: `<?xml version="1.0" encoding="UTF-8"?> <checkstyle version="5.0">`...

And XML follows with warnings description, at least I am able to read them and find mentioned warnings manually, they just aren't shown in status line.

I've also opened an issue in flycheck-gometalinter repo: https://github.com/favadi/flycheck-gometalinter/issues/13

#### Reproduction guide :beetle:
- Start Emacs
- Enable go layer
- Install gometalinter via `go get`
- Open go file with warnings (some variable redefined/shadowed, for example, or any warning that gometalinter picks up)

*Observed behaviour:* :eyes: :broken_heart:
Message buffer appears with messages like

> Suspicious state from syntax checker gometalinter: Flycheck checker gometalinter returned non-zero exit code 3, but its output contained no errors: `<?xml version="1.0" encoding="UTF-8"?> <checkstyle version="5.0">`...

And no indication of warnings in status line. It looks like the provided xml can't be parsed and turned into proper warning messages.

*Expected behaviour:* :heart: :smile:
Message minibuffer does not appear, warnings are indicated in status line and in buffer with code.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(nginx yaml javascript sql csv
       (auto-completion
        (haskell :variables haskell-completion-backend 'intero)
        :disabled-for org git :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete)
       emacs-lisp common-lisp git markdown org
       (shell :variables shell-default-height 30 shell-default-position 'bottom)
       syntax-checking version-control python colors restclient
       (go :variables go-use-gometalinter t flycheck-gometalinter-vendor t flycheck-gometalinter-deadline "10s"))
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11

**Comment by CeleritasCelery** [comment]
You should report this upstream at flycheck.

**Comment by robbyoconnor** [comment]
Yeah -- this isn't something we can fix. It means that flycheck isn't properly parsing the output.

**Comment by dineshbhosale** [comment]
I'm experiencing same issue.

**Comment by dineshbhosale** [comment]
For me the error was gone after removing or extending `flycheck-gometalinter-deadline "10s"` and other deadlines such as 	` (setq flycheck-gometalinter-fast t) ` etc.
