### ISSUE TITLE
Wrong type argument: commandp, spacemacs/presp-perspectives

### ISSUE THREAD

**Issue by rynffoll** [syl20bnr/spacemacs#9655]
#### Description :octocat:
After updating spacemacs I started to get error messages when I'm trying choose layout.

#### Reproduction guide :beetle:
- Start Emacs
- Press SPC l l

*Observed behaviour:* :eyes: :broken_heart:
```
hydra--call-interactively-remap-maybe: Wrong type argument: commandp, spacemacs/presp-perspectives
```

*Expected behaviour:* :heart: :smile:
Showing available layouts

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 71a0d418)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(vimscript asciidoc
           (ansible :variables ansible-auto-encrypt-descrypt t)
           csv autohotkey nginx ivy
           (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
           better-defaults
           (org :variables org-want-todo-bindings t org-enable-github-support t org-enable-bootstrap-support t org-enable-reveal-js-support t)
           (spell-checking :variables spell-checking-enable-by-default nil)
           syntax-checking
           (ibuffer :variables ibuffer-group-buffers-by 'projects)
           git
           (github :packages
                   (not magithub))
           (version-control :variables version-control-diff-tool 'diff-hl)
           (shell :variables shell-default-shell 'eshell)
           docker systemd restclient ranger prodigy emacs-lisp
           (java :variables java-backend 'meghanada)
           groovy
           (clojure :variables clojure-enable-fancify-symbols t)
           javascript typescript shell-scripts windows-scripts sql html yaml markdown react colors erc evil-cleverparens
           (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
           evil-commentary imenu-list command-log search-engine
           (rynffoll :variables rynffoll/projects-directory "~/Projects" rynffoll/org-directory
                     (is-windows "~/OneDrive/Org" "~/Dropbox/Org"))
           (notifications :variables notifications-backend
                          (is-windows 'toaster 'libnotify)))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

**Comment by bmag** [comment]
It's a typo and a mis-named function. See comments in https://github.com/syl20bnr/spacemacs/commit/3bce69aba1dc34b01131b7508b2d79f543245ab2

**Comment by colorwin** [comment]
@bmag 
I have used ivy layer, but that 2 variables still are 'ignore'.
That I set them in `(defun dotspacemacs/user-init ())` manually.
`SPC l b` work fine, while `SPC l l` still not work and throw the same error.

**Comment by bmag** [comment]
@colorwin it's another typo: https://github.com/syl20bnr/spacemacs/commit/3bce69aba1dc34b01131b7508b2d79f543245ab2#commitcomment-24619375

Shouldn't be hard to fix it, but I'll be too busy for the next couple of days.

**Comment by bmag** [comment]
Should be fixed now. @colorwin can you confirm that it's fixed for Ivy users as well?

**Comment by rynffoll** [comment]
I use Ivy and it works for me.
