### ISSUE TITLE
The markdown layer overrides generic M-l binding to `downcase-word`

### ISSUE THREAD

**Issue by Blaisorblade** [syl20bnr/spacemacs#9657]
#### Description :octocat:

The markdown layer overrides the default binding <kbd>M-l</kbd> for `downcase-word` (available in e.g. 
`fundamental-mode` and others), as visible in the following docs and code:

https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/markdown#promotion-demotion
https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/markdown/packages.el#L155

That looks wrong (though I couldn't find guidelines): I'd expect applicable generic keybindings to not be overridden.

Moreover, related bindings <kbd>M-c</kbd> and <kbd>M-u</kbd> for `capitalise-word` and `upcase-word` are still available, creating inconsistency.

#### Reproduction guide :beetle:
- In Spacemacs, open a buffer in Markdown mode (e.g. with extension `.md`).
- Write "Foo" without quotes, go at its beginning
- Use M-l before a word.

*Observed behaviour:* :eyes: :broken_heart:
Error "Nothing to demote at this point" appears in the minibuffer, and no change happens.

*Expected behaviour:* :heart: :smile:
Foo becomes foo.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. ecf6faed)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown yaml csv helm coq agda
          (latex :variables latex-enable-folding t)
          auto-completion better-defaults emacs-lisp git emoji
          (haskell :variables haskell-completion-backend 'intero)
          spell-checking syntax-checking osx)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by Somelauw** [comment]
In vim you can always downcase a word by `guiw`.
I believe the Spacemacs layer overrides `M-l` even in Emacs/holy mode, whereas in my opinion it should only be bound in normal mode.

Spacemacs does have guidelines for that here http://spacemacs.org/doc/CONVENTIONS that say it's okay to override M-l but only in normal mode.

By the way, I was working on my own evil package for markdown that makes stuff like this configurable, but haven't updated in in a while.

**Comment by Blaisorblade** [comment]
Thanks!

> Spacemacs does have guidelines for that here http://spacemacs.org/doc/CONVENTIONS that say it's okay to override M-l but only in normal mode.

Uh, actually I find "Promotion, demotion and movement of headings or list elements (whatever is possible) should be enabled with the following keys in any mode" — after "Movement in normal mode".

Based on that page, closing—I should have looked more closely. (This is still inconsistent but well).

> In vim you can always downcase a word by guiw.

Uh, and even `guw` works (with `gUw` for upcase)! I'd have to add a binding for capitalize... mixed editors and consistency...

> By the way, I was working on my own evil package for markdown that makes stuff like this configurable, but haven't updated in in a while.

Good luck with that!
