### ISSUE TITLE
The Emacs won't auto load the init.el

### ISSUE THREAD

**Issue by BowenWang** [syl20bnr/spacemacs#9659]
Hi all,
I am using Emacs 25.3.1 on openSUSE Tumbleweed. I tried to download the spacemacs using the command:
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

But when I open Emacs after I download the configuration, the Emacs won't load init.el and configure itself.

I tried to load the configuration manuall by: 
M-x load-file ~/.emacs.d/init.el
Emacs will start to configure itself, but the loading bar stalls at 147/149 and won't finish.

Any thoughts? Thanks.

Bowen

**Comment by fiveNinePlusR** [comment]
> Don't forget to backup and remove ~/.emacs file otherwise Spacemacs WILL NOT load since that file prevents Emacs from loading the proper initialization file.

do you have that file there?

**Comment by BowenWang** [comment]
I have tried it as what you said, and it works!! Thanks.

**Comment by CeleritasCelery** [comment]
Feel free to close this issue
