### ISSUE TITLE
You can't type closing parenthesis inside of a quote in insert mode, editing HTML file

### ISSUE THREAD

**Issue by kwojt** [syl20bnr/spacemacs#9660]
#### Description :octocat:
In web mode, when I type opening parethesis, it gives me single parenthesis (without a pair), and when I try to close it, it doesn't write closing parenthesis, but instead my cursor jumps to next '"', ')', ']' or '}', of course if I'm already inside of some kind of block.

#### Reproduction guide :beetle:
- Start Emacs
- Open HTML file
- Type '<button (click)="clickReaction|">y
- Now try to create a pair of parentheses, as if you want 'clickReaction()'
- You now have '<button (click)="clickReaction("|>
- Yep, you can't simply place closing parenthesis there.

*Observed) behaviour:* :eyes: :broken_heart:
Typing parentheses after 'clickReaction':
<button (click)="clickReaction|">
gives:
<button (click)="clickReaction("|>

*Expected) behaviour:* :heart: :smile:
Typing parentheses after 'clickReaction':
<button (click)="clickReaction|">
gives:
<button (click)="clickReaction()|">

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html typescript helm auto-completion emacs-lisp git org evil-commentary)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by CeleritasCelery** [comment]
Thats because smartparens is [disabled](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/html/packages.el#L163) in web-mode
