### ISSUE TITLE
[PR Submitted, Request review] Integrate ox-hugo with Spacemacs

### ISSUE THREAD

**Issue by kaushalmodi** [syl20bnr/spacemacs#9663]
Hello,

I don't use Spacemacs, but in a recent bug report for my package `ox-hugo` https://github.com/kaushalmodi/ox-hugo/issues/82, a Spacemacs user is having trouble getting the `ox-hugo` commands show up in the Org Exporter menu (`C-c C-e`).

If adding that support is similar to https://github.com/syl20bnr/spacemacs/pull/7183/files, you can use a new variable `org-enable-hugo-support` for that.

Many thanks!

@amosbird

**Comment by syl20bnr** [comment]
Excellent, thank you for the PRs !
