### ISSUE TITLE
Shell windows make which-key popup "jumpy" in OSX

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#9664]
#### Description :octocat:
Shell windows in OSX cause which-key and helm popups to be "jumpy". This has been driving me crazy and I can't figure out what's causing it, and if it can be fixed. I don't think I have seen the same behavior in Linux.
Can someone suggest what might be causing this?

#### Reproduction guide :beetle:
- GNU Emacs cocoa GUI app
- try `SPC` and `SPC SPC`/`M-x` - observe that everything is fine
- Open eshell
- Press `SPC` - observe that which-key popup is "jumpy"

![shells-jumpy](https://user-images.githubusercontent.com/1091022/30995689-d22394e0-a470-11e7-9855-a0669d324225.gif)

_In the gif it's hard to notice the difference (even without eshell buffer - it already doesn't look very smooth) - this is due to limited FPS that can be packed in a .gif. Trust me, in real lag is pretty noticeable and very annoying._

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 71a0d418)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv yaml emacs-lisp lua javascript
     (haskell :variables haskell-process-type 'stack-ghci)
     (html :packages
           (not pug-mode slim-mode))
     (markdown :packages
               (not mmm-mode)
               :variables markdown-live-preview-engine 'vmd)
     (shell-scripts :packages
                    (not fish-mode))
     (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
     syntax-checking
     (spell-checking :variables ispell-program-name "aspell")
     helm fasd osx restclient emoji search-engine imenu-list docker pdf-tools
     (shell :variables shell-enable-smart-eshell t)
     git
     (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
     (github :packages
             (not magit-gh-pulls)
             :variables gist-view-gist t magithub-api-timeout 5)
     ag-dired ag-general ag-synonyms ag-clojure ag-web
     (ag-org :variables org-enable-reveal-js-support t org-enable-bootstrap-support t org-enable-github-support t)
     ag-lang-tools)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by agzam** [comment]
Okay, I have removed `shell` layer and that seems fixed this problem for me. Now the question is, what's in `shell` layer might be causing this?

**Comment by sgepigon** [comment]
Disable `em-smart`: `(shell :variables shell-enable-smart-eshell nil)`

When `em-smart` is enabled, Eshell emulates the Plan 9 terminal, so part of that means `SPC` is used to move down a page" and `BACKSPACE` to move up a page.[1] So it conflicts with `SPC` as the leader key.

I ran into the same problem a while ago playing around in Eshell. I couldn't find an easy-to-set config to change how the shell scrolls but maybe someone with better elisp chops can take a look around...

[1] https://www.masteringemacs.org/article/complete-guide-mastering-eshell

**Comment by agzam** [comment]
@sgepigon Thanks, turning off the smart-eshell made it better. I still have disabled some packages from `shell` layer.

**Comment by agzam** [comment]
I going to close this for now
