### ISSUE TITLE
Cannot enable the js-mode with  javascript layer

### ISSUE THREAD

**Issue by eggcaker** [syl20bnr/spacemacs#9665]
#### Description :octocat:
Cannot enable the js-mode after open any .js file 

#### Reproduction guide :beetle: - Start Emacs
- open a .js file 

*Observed behaviour:* :eyes: :broken_heart:

*Expected behaviour:* :heart: :smile:

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 3d0dbf28)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(javascript vimscript python nginx
            (typescript :variables typescript-fmt-on-save t)
            html ruby csv lua osx sql docker
            (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/" auto-completion-complete-with-key-sequence "jj" auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t :disabled-for org erc sh)
            ivy emacs-lisp
            (org :variables org-enable-github-support t org-enable-org-journal-support t org-enable-bootstrap-support t org-enable-reveal-js-support t)
            git
            (markdown :variables markdown-live-preview-engine 'vmd)
            yaml
            (ibuffer :variables ibuffer-group-buffers-by nil)
            (shell :variables shell-default-term-shell "/usr/local/bin/zsh" shell-default-shell 'eshell shell-enable-smart-eshell t shell-default-height 30 shell-protect-eshell-prompt nil shell-default-position 'right)
            shell-scripts syntax-checking version-control javascript restructuredtext docker java
            (python :variables python-fill-column 110 python-sort-imports-on-save t python-enable-yapf-format-on-save t)
            evil-commentary
            (elfeed :variables url-queue-timeout 30 elfeed-enable-web-interface nil rmh-elfeed-org-files
                    (list "~/.spacemacs.d/pelm-feed/feeds.org"))
            (restclient :variables restclient-use-org t)
            imenu-list pelm-misc pelm-org pelm-org-trello pelm-contact)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:

```
Eager macro-expansion failure: (error "Don’t know how to make a localized variable an alias") [2 times]
File mode specification error: (error Don’t know how to make a localized variable an alias)
```

**Comment by CeleritasCelery** [comment]
Why don’t you want the JavaScript layer?

**Comment by mimischi** [comment]
One possible reason would be that `[vue-mode](https://github.com/AdamNiederer/vue-mode)` uses `[mmm-mode](https://github.com/purcell/mmm-mode)` and the latter is not supported by `[js2-mode](https://github.com/mooz/js2-mode)`. Therefore `vue-mode` uses `js-mode`.

**Comment by mimischi** [comment]
One thing I could think of is VueJS. Currently there is only [vue-mode](#abc) and it's using [mmm-mode](https://github.com/purcell/mmm-mode) to display the HTML template, JS and CSS in one `.vue` file. `js2-mode` does not support `mmm-mode` (see [this](https://github.com/mooz/js2-mode/issues/124) `js2-mode` issue) and therefore one needs to use `js-mode`. But I'm currently not sure if having the `javascript` layer enabled even competed with `vue-mode` at all. Need to isolate my configurations and test it out.

**Comment by offbyone** [comment]
I don't know if this will be relevant, but I'm seeing this too, specifically when I try to open a Javascript file *after* opening a Python one. The other order works just fine.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(shell-scripts react lua go nginx csv sql graphviz elixir javascript auto-completion better-defaults emacs-lisp git markdown
               (shell :variables shell-default-height 30 shell-default-shell 'shell shell-default-position 'bottom)
               cr-shell spell-checking syntax-checking version-control yaml html java scala
               (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rbenv)
               emacs-lisp python pandoc docker ansible themes-megapack terraform pdb spacemacs-layouts)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by offbyone** [comment]
I mean... it's stale because nobody on the project has responded :)

IS there more information we, as submitters and commenters, could add?

**Comment by duianto** [comment]
Opening a `.js` seems to work for me on the `develop` branch.

`SPC h d m` (which calls `describe-mode`) shows:
>Javascript-IDE mode defined in ‘js2-mode.el’:
Major mode for editing JavaScript code.

I'm only "strange" message I'm seeing in the messages buffer, is:
>Package iswitchb is obsolete!

But this comment: https://github.com/syl20bnr/spacemacs/issues/2423#issuecomment-140056245
says that `iswitchb` is a deprecated Emacs core package.

I'm not finding any reference to `iswitchb` in Spacemacs, so it's coming from an upstream package.

These are the packages that the `javascript` package uses:
https://github.com/syl20bnr/spacemacs/blob/884afe138bf01f5d0d98555ccf194a6358af1693/layers/%2Blang/javascript/packages.el#L12-L36

There's no error either if a `.py` file is opened before or after the `.js` file.

The only message when opening a `.py` file is:
>Importmagic and/or epc not found. importmagic.el will not be working.

But I'm not sure if imagemagic even is supported in Windows so it's probably expected.

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 884afe138)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion c-c++ command-log emacs-lisp git github
            (gnus :variables gnus-summary-thread-gathering-function 'gnus-gather-threads-by-subject)
            go helm imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors org pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by LoganBarnett** [comment]
@eggcaker Did you close this issue because you found a solution? If so, could you please share it?

**Comment by LoganBarnett** [comment]
@eggcaker disregard - I found your `js2-mode` ticket while researching further. For posterity it can be found [here](https://github.com/mooz/js2-mode/issues/458). This solution doesn't work for me but I have filed https://github.com/mooz/js2-mode/issues/545 in hopes that I might gain more traction there.
