### ISSUE TITLE
using default theme does not work

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#9666]
#### Description :octocat:
adding `default` to `dotspacemacs-themes`
```elisp
dotspacemacs-themes '(default ...)
```
in `.spacemacs` crashes `emacsclient`

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
`emacs --daemon` keeps running `emacsclient` crashes
when I run `emacsclient -c` from commandline it crashes with the following message:
```bash
$ emacsclient -c
Waiting for Emacs...
*ERROR*: Unable to find theme file for ‘default’
```
`emacsclient -c -nw` works, toggling through the themes works, except for loading the default theme, gives an error in `*Message*` buffer:
```
if: Wrong number of arguments: throw, 1
```

loading default theme with `spacemacs/helm-themes` works fine

*Expected behaviour:* :heart: :smile:
normal startup for emacs

#### SYSTEM_INFO :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults
      (c-c++ :variables c-c++-enable-clang-support t)
      chrome csv javascript ranger emacs-lisp ess
      (ess-extra :enabled-for ess)
      games git github haskell html
      (latex :variables TeX-view-program-selection
             '((output-pdf "PDF Tools"))
             TeX-view-program-list
             '(("PDF Tools" TeX-pdf-tools-sync-view))
             TeX-source-correlate-start-server t preview-scale-function 1.5)
      bibtex lua markdown octave
      (org :variables org-format-latex-options
           '(:foreground default :background default :scale 1.5 :html-foreground "Black" :html-background "Transparent" :html-scale 1.0 :matchers
                         ("begin" "$1" "$" "$$" "\\(" "\\[")))
      pdf-tools python
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      shell-scripts spell-checking syntax-checking themes-megapack version-control yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
%BACKTRACE%
```

**Comment by miraclemore** [comment]
There is no `default` theme for spacemacs.
The default theme is spacemacs-dark.
The below is the warning from spacemacs home buffer
```
An error occurred while applying the theme "default", fallback on theme "spacemacs-dark".
Error was: (error Unable to find theme file for ‘default’) 
```

**Comment by gdkrmr** [comment]
yes I know that, but if you run `spacemacs/helm-themes` the standard EMACS theme appears as `default` and it is not possible to add default to `dostspacemacs-themes`.
