### ISSUE TITLE
Where is the helm bookmark and eww bookmark stored

### ISSUE THREAD

**Issue by lijingjiang** [syl20bnr/spacemacs#9667]
It is such a great pleasure to use spacemacs, that's why I install it every where! But could someone tell me where are the helm bookmarks and eww bookmarks stored, so I can share those bookmarks among different machines.

(I use bookmark-set and eww-bookmark-add to add bookmarks.)

Many thanks in advance.

**Comment by miraclemore** [comment]
There is bookmark file under ~/.emacs.d/.cache directory
