### ISSUE TITLE
layers.el loaded after packages.el

### ISSUE THREAD

**Issue by miraclemore** [syl20bnr/spacemacs#9668]
#### Description :octocat:
`layers.el` is loaded after `packages.el` when I add my own layer.
But from layer documentation http://spacemacs.org/doc/LAYERS.html#packagesel
Chapter 4.2 inform that packages.el is loaded after `layers.el`.

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
N/A

*Expected behaviour:* :heart: :smile:
N/A

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion better-defaults colors emacs-lisp git markdown org asm c-c   gtags python spell-checking syntax-checking miraclemore)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
Loading /Users/chuck/.spacemacs.d/layers/miraclemore/packages.el (source)...done
Loading /Users/chuck/.spacemacs.d/layers/miraclemore/layers.el (source)...
Loading /Users/chuck/.spacemacs.d/layers/miraclemore-ui/packages.el (source)...done
Loading /Users/chuck/.spacemacs.d/layers/miraclemore/layers.el (source)...done

layers.el
(configuration-layer/declare-layer '(
                                     miraclemore-ui
                                     miraclemore-programming))

```

**Comment by CeleritasCelery** [comment]
What is the effect of this?

**Comment by miraclemore** [comment]
Currently, there is no side effect on my local.
And if the actual order is that, we need to update documentation for new spacemacs users.
@CeleritasCelery

**Comment by CeleritasCelery** [comment]
How do you know they are being loaded in that order?

**Comment by miraclemore** [comment]
@CeleritasCelery from the *Message* buffer.
As you can see,
```
Loading /Users/chuck/.spacemacs.d/layers/miraclemore/packages.el (source)...done
Loading /Users/chuck/.spacemacs.d/layers/miraclemore/layers.el (source)...
Loading /Users/chuck/.spacemacs.d/layers/miraclemore-ui/packages.el (source)...done
Loading /Users/chuck/.spacemacs.d/layers/miraclemore/layers.el (source)...done
```
packages.el done is shown before layers.el done

And also I define a global variable x,
setq-default x to 1 on layers.el
setq-default x to 2 on packages.el
when Emacs startup, C-h v to show that the value of x is 1.
It means that the value of x is override by layers.el

Due to I am new to elisp programming language, if I am wrong, please feel free to correct me.
thx!
