### ISSUE TITLE
Autocompletion doesn't open automatically when editing `.tsx` files

### ISSUE THREAD

**Issue by TiuSh** [syl20bnr/spacemacs#9669]
#### Description :octocat:

When editing a `.tsx` file, the autocompletion does not open automatically. In the develop branch, manually calling `company-tide` using `M-x` actually works.

#### Reproduction guide :beetle:
- Start Emacs
- Open a `.tsx` file
- Start typing some code that should be autocompleted

*Observed behaviour:* :eyes: :broken_heart:
Nothing happens.

*Expected behaviour:* :heart: :smile:
Autocompletion list opens automatically.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv auto-completion git github javascript helm html markdown org php python ranger react restclient ruby ruby-on-rails semantic
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     syntax-checking typescript version-control yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by CeleritasCelery** [comment]
are `.tsx` files automatically opened in `typescript-mode`?

**Comment by TiuSh** [comment]
No, `tsx` files are opened in `web-mode`. I think this issue is somewhat similar to #8198, as `tsx` files are opened in `web-mode` for some features, but then lacks a lot of features from `typescript-mode`...

**Comment by CeleritasCelery** [comment]
The problem is that `web-mode` is used for more then just Typescript (as I am sure you are aware). Currently the `web-mode` backends are 
```
((company-web-html company-css)
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)
```
Do you think adding `company-tide` to that list is going to effect the behavior for non-typescript languages that use `web-mode`?

**Comment by TiuSh** [comment]
I'm not sure of the impact of this patch on other languages, as I'm quite new to Emacs & Spacemacs... 
But taking a look on other issues related to `.tsx` file format (#9145, #8198, #7344), I think the real issue is to use `web-mode`, as they're (usually) mostly `typescript` files, with a little bit of `HTML`-style code. 
Maybe it would be safer to set `typescript-mode` on `.tsx` files, and add some features from `web-mode` on this filetype ?

**Comment by CeleritasCelery** [comment]
I don't do web development so someone else would have to make that call. However I think I good solution would be to make a new "`jsx-mode`" that is a derived mode of `web-mode`, but then it could have it's own hooks and variables.

**Comment by TiuSh** [comment]
Should I open a new issue dedicated to this "`.tsx` files major-mode issues" discussion ?

**Comment by CeleritasCelery** [comment]
Couldn't hurt. @TheBB even [said](https://github.com/syl20bnr/spacemacs/blob/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/layers/%2Blang/typescript/packages.el#L66) this a poor implementation. You should also mention some of the people that have discussed this in the other issues so they are aware of the conversation.

**Comment by tko** [comment]
Sounds similar to javascript/jsx issue https://github.com/syl20bnr/spacemacs/issues/8206

It seems to me web-mode is the right mode for editing html and/or html-like files (i.e. jsx/tsx blocks) and javascript/typescript mode is right for the actual code. IMO javascript + jsx should be a single spacemacs layer to avoid the duplication / missing features, same with typescript + tsx, possibly even just one for all of them as they're all just tiny variations over javascript at the core.

**Comment by aaronjensen** [comment]
@TiuSh can you double check this again on develop please?

**Comment by TiuSh** [comment]
@aaronjensen 🎉 

It seems to work well ! I'll give it a try for the next few days. 
Thanks a lot !
