### ISSUE TITLE
Allow optionally specifying a search directory when using `SPC s p` or `SPC /`

### ISSUE THREAD

**Issue by jonathanj** [syl20bnr/spacemacs#9670]
From the helm-ag basic usage:
>`helm-ag`: Input search word with ag command. You can change search directory with C-u prefix.

The `C-u` prefix allows specifying the search directory before performing a search, unfortunately it seems this is the only way to specify the directory without physically changing to the directory and using `SPC s d`, which is a bit long-winded.

The `C-u` prefix does not seem to be a common Spacemacs idiom (and even if it were `SPC u SPC s p` doesn't seem to work), so I'm wondering if there is maybe a better way of supporting this?

helm-ag does support `C-l` to ascend to the parent directory, perhaps it could support another command to specify the search directory after invoking `helm-ag`? Would this be something I should report upstream?

**Comment by jonathanj** [comment]
Seems like this is actually `SPC f F`, the name of the command didn't clue me into this fact at all.

**Comment by jonathanj** [comment]
Looks like `SPC f F` worked because of some other weird interaction I can't reproduce, so I'm going to reopen this.

I discovered that this is achievable by `SPC f f C-s` / `SPC p d C-s` to specifically invoke `grep` or `SPC f f M-g a` to specifically invoke `ag`, it would be nice to use the Spacemacs "smart search" infrastructure. I see it's possible to alter the Helm actions for these things in customize but none of the Spacemacs smart search functions obey the directory from the previous step.

**Comment by thekondr** [comment]
Hi @jonathanj ,

Is `SPC s f` what you are looking for? It allows to search either in a file or in a directory, depending on what was highlighted when you pressed `Enter`.

**Comment by jonathanj** [comment]
@thekondr Yes! I ignored it originally because it sounded (according to the function name) and looked (according to the prompts) like it just searched in a specific file but I see you can select a directory too. Perfect. 👌
