### ISSUE TITLE
solarized theme not installed

### ISSUE THREAD

**Issue by fladd** [syl20bnr/spacemacs#9673]
- Added solarized to the themes list:
```
dotspacemacs-themes '(spacemacs-dark
                         spacemacs-light
                         solarized-dark
                         solarized-light)
```
- Restart Spacemacs
- Cycle to solarized with `SPC T n`
- Result is a broken theme:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/2971539/31040702-bd0e9396-a58a-11e7-9343-47d0ba507e9e.png">

**Comment by miraclemore** [comment]
1. Please check the setting custom-set-faces from custom file, if have, you can delete that, and restart emacs
2. Please check your *Message* buffer to check whether you have error during emacs startup

**Comment by fladd** [comment]
Thanks for the answer.

1. I reset it, no change.

2. When switching to the Solarized theme, I get: `if: Wrong number of arguments: throw, 1`

**Comment by bargeruns** [comment]
Having the same issue as @fladd. Here's the bottom of my messages buffer when I load Spacemacs:

```
Loading /Users/sean/.emacs.d/.cache/spacemacs-buffer.el (source)...done
Spacemacs is ready.
Loading /Users/sean/.emacs.d/.cache/recentf...done
Open the quickhelp.
Skipping check for new version (reason: dotfile)
[yas] Prepared just-in-time loading of snippets successfully.
Loading theme spacemacs-light...done
if: Wrong number of arguments: throw, 1
Loading theme spacemacs-dark...done
Saving file /Users/sean/.emacs.d/.cache/recentf...
Wrote /Users/sean/.emacs.d/.cache/recentf
<s-wheel-down> is undefined
<s-double-wheel-down> is undefined
mwheel-scroll: End of buffer [3 times]
Saving file /Users/sean/.emacs.d/.cache/recentf...
Wrote /Users/sean/.emacs.d/.cache/recentf
```

**Comment by miraclemore** [comment]
@fladd @bargeruns 
I only can reproduce that if there is no solarize theme on my local.
If you don't install solarized theme, it will meet that and get "Wrong number of arguments: throw, 1"
please move `solarized-light` to the top one. And have a try.

**Comment by fladd** [comment]
@miraclemore Putting "solarized-dark" or "solarized-light" into "dotspacemacs-themes" should install the theme automatically. At least this is how it used to be. If this has changed, then there should somewhere be an installation instruction on how to install it.

**Comment by fladd** [comment]
@miraclemore Putting "solarized-light" as the first theme in the list did work!

On a related note: The statusbar is slightly broken in the solarized theme.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/2971539/31251712-37ffefb2-aa1f-11e7-8fa0-9e89a493413f.png">

Is there any way to fix this?

**Comment by miraclemore** [comment]
@fladd Yes, spacemacs should install themes which is inside the dotspacemacs-themes.

What is broken in the solarized theme ? It seems that solarized theme works find on my local

**Comment by gnohz** [comment]
@fladd I have a similar issue when I try to use "material" theme. Then I just manually (M-x package install) install "material" theme and it works. Hope works for you too.

**Comment by fladd** [comment]
Stopped working after update again. Now I cannot load any of the Solarized themes. No matter what the order of them is in my .spacemacs file.

**Comment by fladd** [comment]
Reinstalling all packages does not help. It is apparently not possible to install Solarized anymore :-(

**Comment by blakeney** [comment]
I just tried putting `solarized-dark` and `solarized-light` into `dotspacemacs-themes`, and they worked for me including automatic installation.  For what it's worth, I just recently set up Spacemacs for the first time, and I am using the develop branch.

**Comment by vanceism7** [comment]
I've ran into this problem from time to time as well, and am seconding blakeney's suggestion -- Use the develop branch of spacemacs.   
  
When I used master, I was getting this error on random themes, when using develop, everything seems to be working

**Comment by zheli** [comment]
Add "solarized-theme" to  `dotspacemacs-additional-packages` did the trick :)
