### ISSUE TITLE
React mode with autocomplete popup breaks workflow: "error in process filter: quit"

### ISSUE THREAD

**Issue by pbrn46** [syl20bnr/spacemacs#9674]
#### Description :octocat:
When quitting the autocomplete list in react-mode and js2-jsx, the minibuffer spits out `error in process filter: quit`, and freezes for about 3 seconds whilst denying user input of any kind.

This only happens when opening the autocomplete list by pressing `tab`, and closing with 'quit' (`C-g`).

It appears this stops happening if repeated in the same bracket scope, but happens again when the point moves out of the bracket scope and back onto it.

I have tried this on Windows 10 x64 and Ubuntu Linux 16.04 with separate clean installs and .spacemacs.

Interestingly enough, when I set debug-on-error via `SPC SPC toggle-debug-on-error` to see what is happening, the user input is no longer impeded for 2-3 seconds. (Unless that's what debug-on-error does?)

Other modes (such as python) does not exhibit this phenomenon.

#### Reproduction guide :beetle:
- Start Emacs
- Have code such as following:

```
export default class App extends Component {
  render() {
    return (
      <div className="h-100 App">
        <Provider store={store}>
          <CoiApp></CoiApp>
        </Provider>
      </div>
    );
  } // PLACE POINT OVER A BRACKET, BUT NOT IN INSERT MODE, PRESS TAB, THEN C-g to quit
}
```

- Be in react mode or js2-jsx mode.
- Do not enter insert mode
- Place point on top of any closing bracket (not after) and press tab to popup autocomplete list
- Press `C-g` (or `Esc`) to close the list

*Observed behaviour:* :eyes: :broken_heart:
- Error in minibuffer shows `error in process filter: quit`
- User cannot input for 2-3 seconds.

*Expected behaviour:* :heart: :smile:
- Quit Gracefully.
- User can continue typing without disruption to workflow.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 80f6acc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(vimscript php python javascript html ivy
           (auto-completion :variables auto-completion-return-key-behavior nil)
           emacs-lisp git markdown org ranger react
           (shell)
           (spell-checking :variables spell-checking-enable-by-default nil)
           (syntax-checking :variables flycheck-highlighting-mode 'lines)
           themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by CeleritasCelery** [comment]
Can you reproduce without stock emacs and the packages in question?

**Comment by pbrn46** [comment]
@CeleritasCelery Do you mean with _stock_ emacs? Or spacemacs? I'm not sure how to use emacs outside the .spacemacs file, actually 👅... unless somebody can point me to an explanation to install the necessary packages? I can reproduce this in spacemacs fresh off of the master branch and it's been happening before and after package updates via the update packages link on the splash screen since 3 months ago at least.

**Comment by CeleritasCelery** [comment]
What need to determine is if this is a Spacemacs issue or a package issue. You can restart emacs with only certain packages `SPC q D`. Looks like the packages you would need to add would be `react-mode` and what ever you are using for autocomplete, probably some company backend.

**Comment by gone** [comment]
I still see this
