### ISSUE TITLE
anaconda error in spacemacs 

### ISSUE THREAD

**Issue by shnnxn** [syl20bnr/spacemacs#9675]
here is the error message
error in sentinel:setting current directory : No such file or directory /home/username/.emacs.d/.cache/anaconda-mode/0.1.9 
please help me i am new to spacemacs and emacs

**Comment by CeleritasCelery** [comment]
Does `/home/username/.emacs.d/.cache/anaconda-mode/0.1.9` exist?

**Comment by exic** [comment]
Same issue here, the directory does not exist.

**Comment by CeleritasCelery** [comment]
You should open an issue upstream with anaconda mode.

**Comment by exic** [comment]
Nevermind, tried spacemacs develop branch now and it works there :heart: :smiley:
