### ISSUE TITLE
I can't input bracket under lispy-mode

### ISSUE THREAD

**Issue by miraclemore** [syl20bnr/spacemacs#9676]
#### Description :octocat:
Can't input end bracket for progn when I enable lispy-mode

#### Reproduction guide :beetle:
- Start Emacs
- Enable lispy-mode
- Enter below lisp code
```
(progn
  (setq x 10)
  (while (> x 0)
    (print (format "number is %d" x))
    (setq x (- x 1)))
```
*Observed behaviour:* :eyes: :broken_heart:
Can't input the bracket

*Expected behaviour:* :heart: :smile:
Can input the bracket

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion better-defaults colors emacs-lisp git markdown org asm c-c   gtags python spell-checking syntax-checking miraclemore)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```

```

**Comment by CeleritasCelery** [comment]
Can you reproduce with stock Emacs and lispy-mode?

**Comment by miraclemore** [comment]
@CeleritasCelery 
What does stock Emacs mean ?
I try spacemacs both on Macos and ubuntu. Both has the same problem. So I don't regard that emacs distribution make that error.

**Comment by Somelauw** [comment]
In lispy `[` and `]` are defined to bring you into a *special* position.
This is lispy behaviour and Spacemacs doesn't include lispy (yet?).
If you don't want feature, maybe [this](https://github.com/abo-abo/lispy/issues/31) helps.

**Comment by Somelauw** [comment]
@miraclemore Emacs without Spacemacs. (you can test that by running emacs -Q and installing all the packages you need by use-package)
 He/she wanted to know whether the issue is caused by Spacemacs, because if it isn't, the Spacemacs people can't fix it.

**Comment by miraclemore** [comment]
@Somelauw Got it & thx!
lispy-mode is not included by spacemacs. So I `use-package` init that on my layer.
I don't input `[` `]`
As you can see my reference code, sometimes, that I will miss the end parentheses `}` on somewhere.
When I input that to fix the error, there is nothing happen on my screen. I can't input `}` at that place.

**Comment by miraclemore** [comment]
I already try the same behavior on stock emacs.
And I meet the same problem.
I will tracking that to lispy repository
