### ISSUE TITLE
how can i close some mode on start?

### ISSUE THREAD

**Issue by lancelock** [syl20bnr/spacemacs#9679]
such as "show-smartparens-mode" 、"highlight-parentheses-mode"、“toggle-highlight-current-line-globally”

**Comment by duianto** [comment]
Maybe these will work:
```
(spacemacs/toggle-smartparens-globally-off)
(global-highlight-parentheses-mode -1)
(spacemacs/toggle-highlight-current-line-globally-off)
```

**Comment by lancelock** [comment]
the first should be (show-smartparens-global-mode -1)

and the second line does't works, it is strange

**Comment by Alexander-Miller** [comment]
> and the second line does't works, it is strange

It might be added via a mode hook. Check the value of emacs-lisp-mode-hook & prog-mode-hook or whatever modes its active in. There also the nuclear option of adding packages you dont want to `dotspacemacs-excluded-packages`.

**Comment by asciiascetic** [comment]
@lancelock Yup, like what @Alexander-Miller said - I added `highlight-parentheses` to my `dot-spacemacs-excluded-packages` list. That did the trick.
