### ISSUE TITLE
Unable to update packages: copy-directory: Opening output file: No such file or directory

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#9682]
#### Description :octocat:
Unable to update packages: Error on package backup

#### Reproduction guide 🐞 
- Start Emacs
- Click on "Update Packages". Click on "yes" when the prompt is shown.

*Observed behaviour:* :eyes: :broken_heart:
```
Do you want to update 26 package(s) ? y
(Spacemacs) --> performing backup of package(s) to update...

copy-directory: Opening output file: No such file or directory, /Users/jx/.emacs.d/.cache/.rollback/17-10-01_23.09.41/vue-html-mode-20170904.1017/vue-html-mode-autoloads.el
```
Then nothing happens and the packages cannot be updated.

I've tried deleting the whole `.cache` directory and running package updates again but it didn't help.

Not sure if this is related to this particular package (vue-html-mode) or is a more general problem.

EDIT: Doesn't seem to be related to vue.js. After I deleted that package, another package exhibited the same problem in its place while updating packages.

*Expected behaviour:* :heart: :smile:
The package backup succeeds and the update happens

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. a7e30bfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python html helm speed-reading auto-completion better-defaults spell-checking syntax-checking semantic rcirc osx git github version-control
        (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/zsh" shell-enable-smart-eshell t)
        typography chrome dash fasd pandoc colors themes-megapack gtags imenu-list vim-powerline evil-snipe emacs-lisp
        (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "gibiansky")
        elixir org
        (latex :variables latex-enable-auto-fill nil)
        markdown yaml shell-scripts ess)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
Do you want to update 26 package(s) ? y
(Spacemacs) --> performing backup of package(s) to update...

copy-directory: Opening output file: No such file or directory, /Users/jx/.emacs.d/.cache/.rollback/17-10-01_23.09.41/vue-html-mode-20170904.1017/vue-html-mode-autoloads.el
```

**Comment by sgepigon** [comment]
This seems to be a duplicate of #9599—it was fixed upstream so update Emacs itself (`brew reinstall emacs` worked for me last Thursday).

**Comment by x-ji** [comment]
Thanks. Didn't find this issue report with a quick search. Fixed it with `brew reinstall emacs-plus`.
