### ISSUE TITLE
Modeline and theme colour mismatch (e.g. sanityinc-solarized-light)

### ISSUE THREAD

**Issue by dennismayr** [syl20bnr/spacemacs#9686]
Apparently, theme `sanityinc-solarized-light` doesn't play nice with the modeline.
Not sure if it's a theme or spacemacs/emacs problem.
Any ideas?

https://imgur.com/a/iEDFl

**Comment by CeleritasCelery** [comment]
looks like there were also issues with theme mixing in #1216

**Comment by dennismayr** [comment]
Apparently, it's a theme problem.
The modeline colors may not be defined.

I'll contact the author.
