### ISSUE TITLE
In evil-iedit-state, `V`: "command-execute: Wrong type argument: commandp, iedit-toggle-unmatched-lines-visible"

### ISSUE THREAD

**Issue by sgepigon** [syl20bnr/spacemacs#9690]
#### Description :octocat:

iedit renamed `iedit-toggle-unmatched-lines-visible` to `iedit-show/hide-unmatched-lines` upstream in https://github.com/victorhge/iedit/commit/745ea6f81230d6fe0394fdc299c6130971aff86b

I made a pull request to change the key-binding in https://github.com/syl20bnr/evil-iedit-state/pull/19, but I thought I'd report the issue here as evil-iedit-state is really only used in Spacemacs so people might look here first.

In the meantime, users can toss the following in their `dotspacemacs/user-config`:
```
(with-eval-after-load 'evil-iedit-state
    (define-key evil-iedit-state-map "V" 'iedit-show/hide-unmatched-lines))
```

#### Reproduction guide :beetle:
- Start Emacs
- Open any text file, e.g.:
```
This line should be visible.

This line shouldn't.

This line should be visible too.
```
- Place cursor over "visible"
- Press `SPC s e` for `evil-iedit-state`
- Press `V` (Note: it's a capital "V")

*Observed behaviour:* :eyes: :broken_heart:

```
command-execute: Wrong type argument: commandp, iedit-toggle-unmatched-lines-visible
```

*Expected behaviour:* :heart: :smile:

iedit shows only lines that match "visible" and the occurences of "visible" are bold and red:

```
This line should be visible.

...

This line should be visible too.
```

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 0e06bbaf)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 (better-defaults :variables better-defaults-move-to-beginning-of-code-first t better-defaults-move-to-end-of-code-first nil)
 emacs-lisp git markdown
 (org :variables org-enable-github-support nil org-want-todo-bindings t)
 (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell nil)
 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary nil enable-flyspell-auto-completion t)
 (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips t)
 version-control
 (osx :variables osx-command-as 'super osx-option-as 'meta osx-control-as 'control osx-function-as 'nil osx-right-command-as 'hyper osx-right-option-as 'left osx-right-control-as 'left)
 dash evil-cleverparens
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 (clojure :variables clojure-enable-fancify-symbols nil)
 (python :variables python-test-runner
         '(nose pytest)
         python-enable-yapf-format-on-save t)
 ipython-notebook
 (java :variables java-backend 'eclim)
 lua latex pandoc theming evil-goggles)
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

#### Backtrace :paw_prints:
```
```

**Comment by Miciah** [comment]
https://github.com/syl20bnr/evil-iedit-state/pull/19 has been merged; can this issue be labeled as "Fixed upstream" and closed?

**Comment by sgepigon** [comment]
I'm happy to close this issue but I don't think I add the "Fixed upstream" label.

**Comment by Miciah** [comment]
As far as I know, only a maintainer can modify labels.
