### ISSUE TITLE
Inconsistent org mode indentation

### ISSUE THREAD

**Issue by ColonelPhantom** [syl20bnr/spacemacs#9692]
Im not sure if this is a bug, but when I'm in org-mode, and type o on a heading, it indents in a very glitchy way, while when using Enter in insert mode it won't indent regular text. I like the indentation of text, as it contributes to the overview, however I think this would be better as an option rather than something inconsistent and messy.

**Comment by Somelauw** [comment]
What do you mean by glitchy indentation? Can you give us an example?

Also, are you on master or on develop?

**Comment by scheurneus** [comment]
By glitchy I mean for example that a bullet point leads to extra indentation.
I am on master.

**Comment by jb55** [comment]
I've been noticing this recently as well 🤔

**Comment by cmorgan** [comment]
Noticed this as well, it's as if the 'o' behaviour when on a heading is doing the right thing for org-indent-mode (org-indent-mode is off by defualt - which is good), but as this mode is off, it has indented the new line, which is not correct.

**Comment by Somelauw** [comment]
I get:

```org-mode
* heading
  Indented with two spaces.
```

Which is what I would expect. It looks consistent to me, because in vim `o` also auto-indents and it's the same indentation I get when pressing `tab`.

**Comment by jb55** [comment]
I bisected this regression (pressing o from header line leading to indent) to c533605df08bfd60b1c58ce8b9312454bc9c1cc4 /cc @TheBB

**Comment by jb55** [comment]
Looks like c533605df08bfd60b1c58ce8b9312454bc9c1cc4 impacted https://github.com/syl20bnr/spacemacs/pull/9541 as well

**Comment by Somelauw** [comment]
In my opinion, the indent after pressing `o` on a heading is not a bug. It's what evil does by default and is consistent with the behaviour of pressing `o` in other major modes.

If you want to use org-mode without indentation, you can set `org-adapt-indent` to `nil`. This should stop `o` from creating an indent. Let me know if this works for you.

**Comment by jb55** [comment]
> If you want to use org-mode without indentation, you can set `org-adapt-indent` to `nil`. This should stop `o` from creating an indent. Let me know if this works for you.

This fixed it for me. Thanks!
