### ISSUE TITLE
Can't access documentation due to error "Symbol's value as a variable is void: fringe-mode"

### ISSUE THREAD

**Issue by bishopmatthew** [syl20bnr/spacemacs#9693]
#### Description :octocat:
When I try to open the documentation, I get an error message.

#### Reproduction guide :beetle:
- Start Emacs
- Run help command (`SPC-h-SPC`)

*Observed behaviour:* :eyes: :broken_heart:
Error message `Symbol's value as a variable is void: fringe-mode`

*Expected behaviour:* :heart: :smile:
Display help

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp git)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB

**Comment by CeleritasCelery** [comment]
works fine for me. Maybe reinstall `fringe-mode`?

**Comment by bishopmatthew** [comment]
New to spacemacs so I don't fully understand it yet, and I'm not exactly sure what installed it in the first place (I think I just have the default spacemacs config). But I did M-x package-reinstall and the only relevant entry was `vi-tilde-fringe` so I tried to reinstall that and got `Symbol's value as a variable is void: helm-bookmark-map`

**Comment by syl20bnr** [comment]
Can you remove/backup:
- `~/.emacs`
- `~/.spacemacs`
- `~/.emacs.d`

Reclone Spacemacs and restart ? Also give a try to the develop branch.

**Comment by trevor-e** [comment]
I'm running into the same issue. Fresh install of Spacemacs and a first-time user, so not really sure what to do. Was trying to run `SPC h t` (the beginner tutorial?) and it's stuck on this error.

**Comment by duianto** [comment]
`SPC h t` opens the help toggles, which shows:
`Fringe:  Display the fringe in GUI mode. (SPC T f)`
as the first entry.

I'm able to toggle it off/on without issues, when I use the `helm` completion framework, but with the `ivy` framework I get this message:
`assq: Wrong type argument: stringp, (#("(+) Fringe: Display the fringe in GUI mode. (SPC T f)" 0 1 (idx 0) 12 43 (face font-lock-doc-face) 45 52 (face font-lock-keyword-face)) . "fringe")`

Toggling the fringe directly with the keybinding `SPC T f` works as expected, so it might just be an issue with the `ivy-spacemacs-help-toggles` command.

It happens on both the master and develop branches:
- Spacemacs branch: develop (rev. b4b7d63e)


@trevor-e 
The beginner tutorials are accessed with these key bindings:
`SPC h T` opens the Evil tutor that teaches you about the basic vim key bindings,
`C-h t` opens the Emacs tutorial.

It's helpful to include the system info when reporting an issue. This is done by pressing `SPC h d s` which copies the system info to the clipboard. It looks like this when it's pasted here:

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(spell-checking syntax-checking
                (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
                ivy org treemacs git version-control autohotkey emacs-lisp haskell html markdown)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by trevor-e** [comment]
@duianto Thanks so much for the help. My report did feel useless, here's my system info:

```
OS: darwin
Emacs: 25.3.1
Spacemacs: 0.200.10
Spacemacs branch: master (rev. 4bb4cb46)
Graphic display: nil
Distribution: spacemacs
Editing style: vim
Completion: helm
Layers: elisp, (helm emacs-lisp)
System configuration features: NOTIFY ACL LIBXML2 ZLIB
```

Had to type all of that manually even though it said it was copied to the clipboard... Apologies if I'm hijacking this thread, I can create a new issue if needed.

**Comment by duianto** [comment]
@trevor-e Your report wasn't useless, you confirmed that the issue isn't limited to bishopmatthew's machine.

And your not hijacking the thread, your system info shows that both you and bishopmatthew have the same entry:
>Graphic display: nil

Meaning that you both seem to be using a terminal version of Emacs.

According to the question and comments on this page:
https://stackoverflow.com/questions/35865400/why-doesnt-emacs-have-a-fringe-mode-in-terminal
Emacs doesn't have support for fringe mode in terminals.

**Comment by hoosierEE** [comment]
FWIW, I use a terminal version of Emacs and used to see this issue in Spacemacs, but as of version `0.200.9@24.5.1` I no longer see it when calling up help or helm.

Not sure what changed, but I'm happy about it. 👍 

My system is Ubuntu 16.04 cli running on arm64.  Terminal is hterm (chromium html-based terminal).

**Comment by sickcuchulainn** [comment]
Having the same issue here. I put the following inside of ``dotspacemacs/user-config`` and it seems to fix it:

```elisp
(unless window-system
  (set fringe-mode nil))
```

**Comment by arashikou** [comment]
This looks like the same issue as #7546, which was indeed found to be an issue with the lack of `fringe-mode` on terminal Emacs. Even just installing non-terminal Emacs resolved the issue. It should nominally already be fixed in develop, though, by #7571.

**Comment by arashikou** [comment]
FWIW, I no longer see this on `develop` now, only in the latest release.

**Comment by hoosierEE** [comment]
Just want to say this issue reappeared for me in Spacemacs 0.200.13@25.1.1 (emacs25-nox, Debian 9), but the workaround by @close-paren fixed it for me.
