### ISSUE TITLE
Can no longer customize "fill-column" in devel branch

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#9698]
#### Description :octocat:
No longer able to customize `fill-column` in the devel branch.

#### Reproduction guide :beetle:
Add the following code block to your `dotspacemacs/user-config` in your
configuration file:

```elisp
  ;; Python hooks
  (add-hook 'python-mode-hook
            (lambda ()
              ;; Enable fill column indicator
              (fci-mode t)
              ;; Turn on line numbering
              (linum-mode t)
              (setq fill-column 78)
              ;; Set tab-width to 4
              (setq tab-width 4
                    evil-shift-width 4)
              ;; Enable automatic line wrapping at fill column
              (auto-fill-mode t)))
```

*Observed behaviour:* :eyes: :broken_heart:
Open a python file, type `SPC h d v`, search for `fill-column`, observe
that it is set to 80, which isn't correct by any standards.

*Expected behaviour:* :heart: :smile:
It should be set to what you tell it to be set to.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 0e06bbaf)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv lua nginx sql auto-completion emacs-lisp git yaml javascript html markdown major-modes python org osx python ipython-notebook django syntax-checking spell-checking colors spacemacs-layouts vimscript helm
     (version-control :variables version-control-diff-tool 'diff-hl)
     (c-c++ :variables c-c++-enable-clang-support t)
     (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by synic** [comment]
Bump?

**Comment by syl20bnr** [comment]
Is this python specific ?

**Comment by Miciah** [comment]
The python layer adds a hook that sets `fill-column` to `python-fill-column` and `tab-width` to `python-tab-width`:

https://github.com/syl20bnr/spacemacs/blob/f3cbf89b4599ac337439c686d539eeeea881f58c/layers/%2Blang/python/packages.el#L304-L305
https://github.com/syl20bnr/spacemacs/blob/f3cbf89b4599ac337439c686d539eeeea881f58c/layers/%2Blang/python/funcs.el#L92-L96

@synic, to resolve this issue, you can either set `python-fill-column` and `python-tab-width` instead of setting `fill-column` and `tab-width` directly:
```emacs-lisp
  (setq python-fill-column 78)
  (setq python-tab-width 4)
  (add-hook 'python-mode-hook
            (lambda ()
              (fci-mode t)
              (linum-mode t)
              (setq evil-shift-width 4)
              (auto-fill-mode t)))
```
Or you can tell `add-hook` to *append* your hook using the third parameter of `add-hook` so that your hook will run after Spacemacs's hook:
```emacs-lisp
  ;; Python hooks
  (add-hook 'python-mode-hook
            (lambda ()
              ;; Enable fill column indicator
              (fci-mode t)
              ;; Turn on line numbering
              (linum-mode t)
              (setq fill-column 78)
              ;; Set tab-width to 4
              (setq tab-width 4
                    evil-shift-width 4)
              ;; Enable automatic line wrapping at fill column
              (auto-fill-mode t))
            t)
```
Does that resolve the issue?

**Comment by Atemu** [comment]
If anyone comes around here because `setq`'ing `fill-column` doesn't do anything in Spacemacs; use `setq-default`.
