### ISSUE TITLE
Indentation not working in haskell-mode

### ISSUE THREAD

**Issue by meditans** [syl20bnr/spacemacs#970]
When I hit return and go to a new line, `hi2-mode` seems to not work properly.

![output](https://cloud.githubusercontent.com/assets/4641445/6875469/12570a58-d4bf-11e4-9006-d46cb7804274.gif)

Basically the cursor is stuck where `hi2` thinks the indentation should be, and returns there even if I hit backspace, or try to write at the beginning of the line.
In the situation above, I only hit `backspace` to go to the beginning of the line, and then the characters I'm writing.

Additional info:
1) this behavior happens both in master and in develop.
2) is invariant under `.emacs.d/elpa` deletion.
3) is invariant under complete reinstallation.
4) I get this error also with a clean .spacemacs (adding only the haskell layer)

**Comment by fatlazycat** [comment]
Same here after upgrading from elpa on 0.100.1

**Comment by meditans** [comment]
Ok, so I tested this also with `v0.100.0`, in which I had no problems, and I get the error anyway. So this probably is a package problem, among the ones downloaded by elpa. But which one? `hi2`?

**Comment by fatlazycat** [comment]
I believe structure haskell mode works - it's not exhibiting the issue with the other indentation mode.

**Comment by syl20bnr** [comment]
It is always possible to exclude a package with
`dotspacemacs-excluded-packages`

Le vendredi 27 mars 2015, Carlo Nucera <notifications@github.com> a écrit :

> Ok, so I tested this also with v0.100.0, in which I had no problems, and
> I get the error anyway. So this probably is a package problem, among the
> ones downloaded by elpa. But which one? hi2?
>
> @syl20bnr <https://github.com/syl20bnr> @fatlazycat
> <https://github.com/fatlazycat>, how do we get a sane default until this
> problem is solved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/970#issuecomment-87081373>.
>


-- 
-syl20bnr-

**Comment by syl20bnr** [comment]
I just remembered that @jeremyjh had issues with the last release of haskell mode, maybe it is this issue. You can rollback your updated of package with the `[Rollback]` button on the start page provided you updated with `[Update]`.
Otherwise I posted the prior version of haskell-mode here: https://files.gitter.im/syl20bnr/spacemacs/B1zp/haskell-mode-20150317.204.zip

**Comment by jeremyjh** [comment]
@syl20bnr Hi - sorry I should have came back and let you know my outcome. I used the older copy of haskell-mode you linked me to and that didn't solve my problem.

My problem is some going wrong in ghc-merge-keywords in ghc-comp.el (ghc-mod) that broke things like SPC mt.  I just hacked around it for now by removing modkeys from the keywords list; I thought haskell-mode might be implicated because it was the only package in the haskell suite which changed between the time I had it working and when it stopped working but it must be something else.

I also had trouble with indentation working out of the box; using hindent fixes it but for some reason without that I would constantly get errors that no indentation mode had be setup in the haskell-mode hook.

**Comment by alandao** [comment]
Hi, letting you know that I too am having this problem. I installed a clean spacemacs two days ago and only enabled the Haskell layer as well.

**Comment by syl20bnr** [comment]
Do we know if #735 could fix this ?

**Comment by alanz** [comment]
I also have this issue, and to me it looks like the tab stops are being shown twice, once with a wavy underscore, once with a solid one.

If I exit from insert mode the wavy ones go away and the display looks as I would expect. If I press 'i' to go to insert mode the wavy underlines reappear, and the cursor jumps to the right, to be at the boundary between the wavy ones and the solid ones.

So I think it is something to do with evil insert mode.

**Comment by syl20bnr** [comment]
I just pushed the changes in develop to remove hi2, it fixes the issue for me (but I'm not sure I had it before...so well)

Can you test it ?
Be sure to have the last version of haskell-mode from MELPA.

**Comment by alanz** [comment]
just did a 

    git fetch && git checkout -b develop

The problem does goes away. Thanks.

**Comment by meditans** [comment]
Hey, the problem doesn't go away for me :(
I tested this in numerous ways now (for example reinstalling everything from scratch from the develop branch).

Is there anything I'm missing? @fatlazycat, @alandao?

**Comment by syl20bnr** [comment]
Did you try with a clean dotfile with only the haskell layer ?

**Comment by meditans** [comment]
@syl20bnr yep, just did it, still have the same problem!

**Comment by alanz** [comment]
Make sure that hi2 is commented out in ~/.emacs.d/contrib/lang/haskell/packages.el

I had some other issues with the develop branch, so reverted to master (0.100.1), commented out hi2 and it works for me

**Comment by meditans** [comment]
@alanz Thanks, this does the trick! I'm still in develop, but commented out that line, and it's all working now.
@syl20bnr could you patch that in develop?

**Comment by syl20bnr** [comment]
what ? where does hi2 remain ?

**Comment by syl20bnr** [comment]
You don't need to commend hi2, you can use `dotspacemacs-excluded-packages` from the dotfile.
But I removed hi2 in develop...
Are you sure you were in develop branch ?

**Comment by alanz** [comment]
One comment I can still make is that when hi2 was still in and duplicating the markings, it used a wavy line to mark the tab positions, and it now uses a thin underscore. 

I would prefer to use the wavy underscore, as it does not clash with actual underscore characters in the text

**Comment by syl20bnr** [comment]
It should not clash with the underscores and be displayed slightly below an underscore.

**Comment by alanz** [comment]
It is slightly below, and thinner, but visually is is still an underscore.
So when it appears between two normal identifiers you have to look hard to
check that is is a column marker and not an underscore.

**Comment by jeremyjh** [comment]
When I pull develop now, I cannot start haskell-mode because of this error:

```
funcall: Symbol's function definition is void: haskell-indentation-disable-show-indentations
Error in post-command-hook (evil-mode-check-buffers): (void-function haskell-indentation-disable-show-indentations)
```

I have Haskell mode haskell-mode-20150403.1144 installed. I do see this function defined.

**Comment by jeremyjh** [comment]
Do we still need a call to (turn-on-haskell-indentation) ? I still see that defined. If I add it I do not get the above error but still haskell-mode doesn't load correctly; I don't see any error in Messages but there is no syntax highlighting.

**Comment by mlacorte** [comment]
I'm getting the same error as @jeremyjh.

* spacemacs 0.101.0 (master)
* Emacs 24.3.1
* Ubuntu 14.04

**Comment by syl20bnr** [comment]
@mlacorte may be related to #819. Try installing the version 24.4+ of Emacs from source.

**Comment by mlacorte** [comment]
I tried 24.4 and 24.5 and still had the same result.

**Comment by cies** [comment]
This workaround worked for me:

https://github.com/syl20bnr/spacemacs/issues/1136#issuecomment-93078911

No more `Error in post-command-hook (evil-mode-check-buffers): (void-function haskell-indentation-disable-show-indentations)`... Yes.

**Comment by kRITZCREEK** [comment]
Thx for the tipp cies! That workaround worked for me aswell

**Comment by cies** [comment]
You're welcome!
