### ISSUE TITLE
fill-column-indicator breaks magit commit on Emacs 24.5 and earlier

### ISSUE THREAD

**Issue by henriquenj** [syl20bnr/spacemacs#9701]
#### Description :octocat:

An update on `fill-column-indicator` package makes spacemacs break when using it with Emacs 24.5. It's particularly bad when using it with magit to make commits: magit tries to open an emacsclient program and then fails, which render spacemacs useless for making commits. The <kbd>SPC t f</kbd> is also broken, but it does not cause any other major inconvenience other than the error message on the minibuffer.

Two layers depend on this package: `git` and `spacemacs-visual`.

According to spacemacs documentation, spacemacs is suppose to work with Emacs 24.4 or above. The commit on `Fill-Column-Indicator` that breaks the support is alpaker/Fill-Column-Indicator@21df682b7cead38c7962e1f8368d92356f8b219e.

#### Reproduction guide :beetle:
- Start Emacs
- On any magit window, call <kbd>c c</kbd> for commit

*Observed behaviour:* :eyes: :broken_heart:
Magit will throw an error, accessible by pressing <kbd>$</kbd> with the following:

> Waiting for Emacs...
> *ERROR*: Fill-column-indicator requires version 25 or later
> error: There was a problem with the editor '/usr/bin/emacsclient.emacs24 --socket-name=/tmp/emacs1000/server'.
> Please supply the message using either -m or -F option.

*Expected behaviour:* :heart: :smile:
The commit buffer to show up so the user can commit.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 0e06bba)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp git)
```

Tested on a Lubuntu VM, but it should happens on any Emacs older than 25. Issue exists on both master and develop versions.

#### Workaround

* If you notice your `magit-commit` stopped working after performing an update of packages, you can rollback by using the rollback feature of spacemacs, available from the home buffer (<kbd>SPC b h</kbd>). After doing this, you must add `fill-column-indicator` to `dotspacemacs-frozen-packages` list on your `.spacemacs` file, which will enable you to update the other packages.
* If you are performing a fresh install of spacemacs and want your magit-commit working, you must add `fill-column-indicator` to `dotspacemacs-excluded-packages`.

**Comment by syfenx** [comment]
**spacemacs 0.200.10@24.4.1**

I've replaced :
"~/.emacs.d/elpa/fill-column-indicator-20170905.1008/fill-column-indicator.el"
with this pull request, deleted "fill-column-indicator.elc", restarted spacemacs and it's working, thanks!.

**Comment by Kinmarui** [comment]
For what it's worth
one can update to emacs version 25(.3) using unofficial package for ubuntu
```
sudo add-apt-repository ppa:kelleyk/emacs
sudo apt-get update
sudo apt-get install emacs25
```

from https://askubuntu.com/a/851646

just did it (on Windows subsystem for Linux) and and looks good, will come back to edit this if I find any major problems.

**Comment by alexm98** [comment]
This is still happening with emacs 24.5.1 on Debian 9.4. I have tried adding fill-column-indicator to dotspacemacs-excluded-packages without any luck, I still can't commit using magit, still getting the "fill-column-indicator requires version 25 or later"

**Comment by henriquenj** [comment]
@alexm98 `fill-column-indicator` requires at least emacs 25. 

If `dotspacemacs-excluded-packages` does not work. you might need to manually delete the package on `list-packages` as well.

**Comment by alexm98** [comment]
I have been able to upgrade emacs and recompile all the packages, it works now.
