### ISSUE TITLE
Replace `web-mode` for `.tsx` files 

### ISSUE THREAD

**Issue by TiuSh** [syl20bnr/spacemacs#9704]
When editing a Typescript `.tsx` file `web-mode` is used, and lacks most of the interesting features from `typescript-mode` (as described in these issues #9669, #9145, #8198, #7344). As discussed with @CeleritasCelery and @tko, this problem is quite similar to '.jsx' files => #8206. Maybe we should find a new mode, dedicated to these `.tsx` files, that will merge the features from `web-mode` and `typescript-mode`, without risking to break any of them.

@vyorkin, @george-miller, @bmag, @jupl, @TheBB, @NotBrianZach, would you share any thoughts about this ?

**Comment by bpizzi** [comment]
I've +1 on this one but I think it still deserves a quick comment.

A new mode for `.tsx` files with features from both `web` and `typescript` modes really makes sense. When coding React component in Typescript, one frequently needs simultanously html tag autocompletion (from `web-mode`) and React component properties checking/autocompletion (from `typescript-mode`).

**Comment by vyorkin** [comment]
sorry, I don't use spacemacs anymore, so I can't add anything to the discussion

**Comment by TiuSh** [comment]
Still no update ?

Spacemacs is no longer usable on my frontend projects (where I mostly use Typescript with React) because of this issue...

**Comment by CeleritasCelery** [comment]
You can always switch `.tsx` files to `typescript-mode`

**Comment by TiuSh** [comment]
Yes, I tried this solution, but then editing html tags becomes a real pain: messed up indentation, no autocomplation & auto-closing tags, ...

**Comment by CeleritasCelery** [comment]
That’s probably why they set it to `web-mode`. This will require someone to create a new major mode that joins the two feature sets. That is no small task. If you really want this done you you probably have to do it yourself and then open a PR.
