### ISSUE TITLE
DD in Salt-mode doesn't delete line as expected

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#9707]
#### Description :octocat:
In salt-mode  the dd evil key binding to delete line seems to do nothing  I've reloaded and re pulled the salt-mode  and it repeats in salt-mode yet works fine in yaml mode and other I commonly use

#### Reproduction guide :beetle:
- Start Emacs
- have salt layer installed 
- open an sls suffix yaml file  (saltstack files)
- try to delete a line with the   dd keys in normal mode
- see nothing happen  Notice Shift-V d will delete the line but that is a PITA

*Observed behaviour:* :eyes: :broken_heart:
the word Quit will show below the powerline on second d  of dd

*Expected behaviour:* :heart: :smile:
the line to be remove from the buffer

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. b6474ff5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible better-defaults csv dash deft docker emacs-lisp emoji evil-cleverparens evil-commentary evil-snipe fasd finance gtags graphviz helm html imenu-list javascript lua markdown pandoc pdf-tools php python ruby salt search-engine semantic shell-scripts spacemacs-layouts spacemacs-purpose sql systemd typography vim-empty-lines vimscript vinegar xkcd yaml
         (auto-completion
          (spacemacs-ui-visual :packages
                               (not neotree fancy-battery))
          :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil)
         (git :variables magit-revision-show-gravatars t)
         (ibuffer :variables ibuffer-group-buffers-by 'projects)
         (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
         (spell-checking :variables spell-checking-enable-by-default t)
         (syntax-checking :variables syntax-checking-enable-by-default nil)
         (org :variables org-enable-github-support t org-enable-org-journal-support t)
         (ranger :variables ranger-show-previews t)
         (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t version-control-diff-side 'left)
         marty-base marty-org mutt-mode)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>  NOT Relevant
```

**Comment by CeleritasCelery** [comment]
what is `dd` bound to? (`SPC h d k`)

**Comment by MBuchaus** [comment]
d runs the command evil-delete (found in evil-normal-state-map), which is an
interactive compiled Lisp function in ‘evil-commands.el’.

It is bound to d.

(evil-delete BEG END &optional TYPE REGISTER YANK-HANDLER)

Delete text from BEG to END with TYPE.
Save in REGISTER or in the kill-ring with YANK-HANDLER.

**Comment by CeleritasCelery** [comment]
Do any other vim motions with `d` work?

**Comment by OrBaruk** [comment]
Just want to add that `yy` and `gcc` binds also do not work, it seems to be a problem with interacting with lines using evil while in `salt-mode`

**Comment by non-Jedi** [comment]
I'm having the same problem lately with markdown-mode.

**Comment by mbrgm** [comment]
I can confirm the issue with salt-mode and also have the same problem in mmm-mode buffers. Has anyone made any progress towards solving it?

**Comment by cipharius** [comment]
I managed to find the source of this issue. Unfortunately it's an upstream
issue, which is caused by `salt-mode` using `buffer-list-update-hook` to run
some function, which disrupts `evil-mode` temporary key map for handling
repeated keys.

I managed to create a quick fix, that can be placed in your `user-config` section
in `.spacemacs` file. It should keep the previous behavior, but uses a hook that
doesn't conflict with evil:
```elisp
(add-hook 'salt-mode-hook
            (byte-compile
             (lambda ()
               (remove-hook 'buffer-list-update-hook 'salt-mode--set-keywords t)
               (add-hook 'post-command-hook
                         (lambda ()
                           (when (string= major-mode "salt-mode")
                             (salt-mode--set-keywords)))))))
```

Will open a pull request on upstream repository, suggesting to use 
`post-command-hook` instead of `buffer-list-update-hook`.

**Comment by d12frosted** [comment]
@cipharius thank you for your investigation. Once you open a PR, please share a link to it here, so it's easier to track the progress.

**Comment by peterhoeg** [comment]
Like @non-jedi I had this problem in markdown mode (I don't use salt) but it was magically fixed when switching from the latest release to ```develop```.

**Comment by cipharius** [comment]
I'm curious about the `markdown-mode` issue, I would like to check whether the
cause is same as in this issue. I couldn't seem to replicate it, neither on develop
or master.

Is anyone else having similar issues with other modes?

If something like this happens elsewhere and the cause is same, it might be
actually be spacemacs issue.

**Comment by cipharius** [comment]
The discussion on upstream can be found here: https://github.com/glynnforrest/salt-mode/pull/20

**Comment by cipharius** [comment]
This issue has been resolved in upstream. Just tried out `salt` layer on spacemacs, `dd` and the other repeated letter commands work properly now.

To get the newest `salt-mode`, you should run the following command sequence:
`SPC SPC` -> `reinstall-package` -> `salt-mode`

@d12frosted you might want to verify this as well and update the issue status.
