### ISSUE TITLE
Disable flycheck in insert mode

### ISSUE THREAD

**Issue by olafura** [syl20bnr/spacemacs#9708]
It's really distracting having flycheck errors when I haven't finished typing if there is an option or default behaviour only to have it on when we are not in insert mode then I would be happy.

**Comment by CeleritasCelery** [comment]
someone suggested something similar in #9441. 
You could try
```emacs-lisp
(add-hook 'evil-insert-state-entry-hook (lambda () (flycheck-mode -1))
(add-hook 'evil-insert-state-exit-hook  (lambda () (flycheck-mode 1))
```

**Comment by olafura** [comment]
@CeleritasCelery Where do I put those?

**Comment by CeleritasCelery** [comment]
That seems like the right place. Maybe `dotspacemacs/user-init`? Though those functions are not complete because you should probably only enable flycheck in programming buffers.

**Comment by olafura** [comment]
@CeleritasCelery That doesn't work either, also since some people might use the above comment please add missing closing parenthesis ;) You are probably right about the programming buffer but I'm really dumb about buffers or anything emacs related.

**Comment by CeleritasCelery** [comment]
can you see the lambda in the hooks? (`SPC h d v RET evil-insert-state-entry-hook`)

**Comment by olafura** [comment]
@CeleritasCelery Symbol's value as variable is void: helm-bookmark-map

**Comment by olafura** [comment]
both opening it up on a no file and a code file

**Comment by CeleritasCelery** [comment]
What? Can you call `describe-variable`?

**Comment by olafura** [comment]
Same thing

**Comment by CeleritasCelery** [comment]
I'm confused. When you call `describe-variable` you get the error message `symbol's value as variable is void: helm-bookmark-map`?

**Comment by olafura** [comment]
I had to use tab :D

**Comment by olafura** [comment]
(evil-start-track-last-insertion
  (lambda nil
    (flycheck-mode -1)))

**Comment by synic** [comment]
@CeleritasCelery `describe-variable` (and a number of other things that relied on `helm-bookmark-map`) is broken in master.  Fixed in develop.

**Comment by duianto** [comment]
The `Symbol’s value as variable is void: helm-bookmark-map` message is a known issue:
Describe variable fails due to missing definition of "helm-bookmark-map" on develop #9549 

It's been fixed on the develop branch, But the current fix for the master branch is to add:
`(require 'helm-bookmark)`
to the `dotspacemacs/user-config` section in `.spacemacs`.

The issue linked above, mentions that there's a planned hotfix.
