### ISSUE TITLE
package chinese-pyim renamed as pyim

### ISSUE THREAD

**Issue by Linxius** [syl20bnr/spacemacs#9710]
package chinese-pyim renamed as pyim so all the "chinese-pyim" in the layers/+intl/chinese/packages.el should rename as "pyim"

**Comment by leezu** [comment]
This was fixed on develop by 74b8a3460df16cb67c4c7eb44c69a1f607651c52 . @syl20bnr is it possible to apply that commit as well on master?

**Comment by hanjianwei** [comment]
Yes, this commit should be applied to master branch to avoid broken update.
