### ISSUE TITLE
linkapp is deprecated by Homebrew. 

### ISSUE THREAD

**Issue by casouri** [syl20bnr/spacemacs#9711]
Although Homebrew have deprecated linkups command and suggested using cask, the instruction on readme hasn't change.

**Comment by philtothetop** [comment]
Just wondering, what would be the new way to link emacs-plus to Applications if we can no longer use linkapps? As of right now, emacs-plus doesn't seem to have a cask recipe [yet](https://github.com/d12frosted/homebrew-emacs-plus/issues/41).

**Comment by casouri** [comment]
That is true. Sorry for not realizing that issue. I don't use emacs-plus so I didn't notice.

**Comment by dijonkitchen** [comment]
As mentioned in #10578, when you brew install now, the log will have an alternative to `brew linkapps` via `ln`.
