### ISSUE TITLE
cmake-ide makes spacemacs unusuably slow

### ISSUE THREAD

**Issue by gnzlbg** [syl20bnr/spacemacs#9723]
cmake-ide is enabled by default in C++ mode, and for each header file it tries to automatically find a corresponding cpp file. 

Many C++ libraries are, however, header only (e.g. like the C++ standard library, amongst others). 
These libraries are characterized by a lack of an accompanying cpp file to their header files.

Cmake-ide, however, attempts to find cpp files for these libraries header files. Since they do not exist, trying to find them takes a long time and consumes a lot of CPU time, making spacemacs **unusably** slow. Header only libraries have often many small header files, and trying to open one on my machine takes about 10-20 seconds. This is really not acceptable.

I don't know what the fix is here, but probably we should disable cmake-ide by default until they fix this upstream.

**Comment by gnzlbg** [comment]
Seems that it is well known that this is broken: https://github.com/syl20bnr/spacemacs/pull/9432

The question becomes then, if this is broken, why is this enabled by default?

**Comment by myrgy** [comment]
atilaneves/cmake-ide#59

**Comment by dubnde** [comment]
I think we should have a flag to enable cmake-ide. Disabled by default.

**Comment by myrgy** [comment]
sounds reasonable. I'll disable cmake-ide by-default and will add a flag for that.

**Comment by syl20bnr** [comment]
https://github.com/syl20bnr/spacemacs/pull/9955 has been merged to develop branch.
