### ISSUE TITLE
Idea: Add a toggle to auto-close compilation window on success

### ISSUE THREAD

**Issue by jb55** [syl20bnr/spacemacs#9724]
Stolen and slightly modified from [stackoverflow](https://stackoverflow.com/a/11059012/10486):

```elisp
(defun bury-compile-buffer-if-successful (buffer string)
 "Bury a compilation buffer if succeeded without warnings "
 (when (and
         (buffer-live-p buffer)
         (string-match "compilation" (buffer-name buffer))
         (string-match "finished" string)
         (not
          (with-current-buffer buffer
            (goto-char (point-min))
            (search-forward "warning" nil t))))
    (run-with-timer 1 nil
                    (lambda (buf)
                      (bury-buffer buf)
                      (delete-windows-on buf))
                    buffer)))
(add-hook 'compilation-finish-functions 'bury-compile-buffer-if-successful)
```

## Motivation

When rebuilding documents with `SPC c r` most of the time it's a success and I don't care about the compilation result. This hides the window after some timeout.

## Todo

- [ ] Custom timeout
- [ ] Toggle to add/remove the hook

Let me know if this sounds good idea and I'll start on a PR

**Comment by CeleritasCelery** [comment]
What language is this for?

**Comment by jb55** [comment]
this is for the compilation buffer, which is language agnostic

**Comment by CeleritasCelery** [comment]
Well then I think this could make a great PR. Just add some variable to toggle this behavior.

**Comment by shwsun** [comment]
Should I add this to user-config? Seems like it is not working.

**Comment by jb55** [comment]
@shwsun I haven't started started working on this yet, but it's on my radar...

**Comment by shwsun** [comment]
@jb55 thanks! I really like this feature.

I would like to report that it works occasionally :)
