### ISSUE TITLE
[osx layer] cannot type curly brace when enabling osx mode.

### ISSUE THREAD

**Issue by stormpat** [syl20bnr/spacemacs#973]
When enabling the osx layer I cannot type curly braces, typing ```alt-shift + 8/9``` emacs will just spit out parenthesis.

Searching the web, heres a SO question with an accepted answer:
http://stackoverflow.com/questions/3376863/unable-to-type-braces-and-square-braces-in-emacs/3378391#3378391

Heres some additional info about the keyboard layouts (imho Finnish layout === Swedish pro) :
http://apple.stackexchange.com/questions/60831/whats-the-difference-between-the-swedish-and-swedish-pro-keyboard-layouts

Because this was not reported earlier, im quite sure its because of my keyboard layout, im on a Finnish keyboard (same as the Swedish one, with ÅÄÖ keys).

**Comment by syl20bnr** [comment]
Thank you for the report, how would you see this implemented ? As a layer variable ? `osx-swedish-keyboard-layout` or `osx-finnish-keyboard-layout` ? Both with an alias ?

**Comment by stormpat** [comment]
Thats sounds like a plan. So just set some variable in your .spacemacs then? Maybe have something more general like ```osx-scandinavian-keyboard-layout``` because most scandinavian languages have non-english characters, and most likely also have a custom keyboard layout.

**Comment by syl20bnr** [comment]
`osx-scandinavian-keyboard-layout` is perfect.

**Comment by sgraf812** [comment]
It also occurs on my german installation.

**Comment by stormpat** [comment]
:+1:

**Comment by stevematdavies** [comment]
I have a linux laptop with a Scandinavian keyboard, will this work for the osx stuff?
