### ISSUE TITLE
packages not available

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#9733]
I just made a new install of spacemacs with the develop branch and get the following errors: 

```
Found 2 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: ess-R-object-popup@ess... [1/2]
Package ess-R-object-popup is unavailable. Is the package name misspelled?
--> installing package: zonokai-theme@themes-megapack... [2/2]
Package zonokai-theme is unavailable. Is the package name misspelled?
```

searching melpa both packages are missing.

On an existing install I do not get these errors, presumably, because I still have these packages installed.

**Comment by bmag** [comment]
#9694 
#9717

**Comment by gdkrmr** [comment]
sorry for the duplicate issue, I did a quick search before posting this but nothing popped up.
