### ISSUE TITLE
Setting `mmm-mode` global mode to ALWAYS breaks .spacemacs

### ISSUE THREAD

**Issue by dennismayr** [syl20bnr/spacemacs#9736]
Hi,

When I `M-x` `customize-group` and set `mmm-mode` global mode to ALWAYS, it breaks .spacemacs (restart, then white Emacs screen with "choose your editing style" prompt).

**Comment by dennismayr** [comment]
I asked the package maintainer, and there is no problem using plain Emacs, so it's most likely a Spacemacs issue.
[https://github.com/purcell/mmm-mode/issues/77](url)

**Comment by syl20bnr** [comment]
I can reproduce and I think this is a bug with `mmm-mode` coupled with lazy loading, when you tried with plain Emacs, did you use lazy loading as well ?

Error is:

 ```
(Spacemacs) Error in dotspacemacs/emacs-custom-settings: Cannot open load file: No such file or directory, mmm-mode
```

BTW which version of Spacemacs do you use? Master ? I'm on develop and while the error happens it does not prevent to use Spacemacs normally.

**Comment by syl20bnr** [comment]
Happens even when I explicitly require the `mmm-mode` feature.

**Comment by syl20bnr** [comment]
This is the issue: 

```
  ;; Given the loading process of Spacemacs we have no choice but to set the
  ;; custom settings twice:
  ;; - once at the very beginning of startup (here)
  ;; - once at the very end of loading (in `spacemacs/setup-startup-hook')
  ;; The first application of custom settings is to be sure that Emacs knows all
  ;; the defined settings before saving them to a file (otherwise we loose all
  ;; the settings that Emacs does not know of).
  ;; The second application is to override any setting set in dotfile functions
  ;; like `dotspacemacs/user-config`, users expect the custom settings to be the
  ;; effective ones.
  ;; Note: Loading custom-settings twice is not ideal since they can have side
  ;; effects! Maybe an inhibit variable in Emacs can supress these side effects?
```

But in develop branch it does not prevent from using Spacemacs normally. Only the error shows up in the mode-line.

**Comment by syl20bnr** [comment]
I'm puzzled I don't recall why we need to load them twice, I tried to comment the first load and it seems to work right.

Going to submit the comment of this first load and see if we have any regression.

**Comment by syl20bnr** [comment]
Pushed the fix, see referenced commit above, let's see how it goes.

**Comment by dennismayr** [comment]
Sorry about the delay, I always use the master branch.
I'll checkout `develop` and see what happens.
