### ISSUE TITLE
c-c++ layer delete company package and hence auto completion doesn't work

### ISSUE THREAD

**Issue by dhanjit** [syl20bnr/spacemacs#9737]
When c-c++ layer isn't enabled, then autocompletion layer installs company, yasnippet etc.
However when c-c++ layer is enabled, it removes all autocompletion.

```
❯ ls ~/.emacs.d/elpa | grep company
```

**Comment by CeleritasCelery** [comment]
you should use `SPC h l` when submitting issues so we can see your setup.
