### ISSUE TITLE
How to trigger auto complete popup window after close?

### ISSUE THREAD

**Issue by chriskaukis** [syl20bnr/spacemacs#9739]
I have a question, but wasn't sure how to add the proper Question and Forum labels.

How do you get the autocomplete popup window back after it closes? I have attached an image. After it closes I can't figure out how to get it back? I can cycle through the options, but I want the actual popup where I can see the choices again. I can't be the only one? 

<img width="168" alt="screen shot 2017-10-15 at 11 50 42 am" src="https://user-images.githubusercontent.com/455/31587029-9c609100-b19f-11e7-93b0-7b69e4c31be9.png">

If I have to add my own shortcut, can I get an idea of how or an example of an intelligent or proper means to do this type of operation in the future without interfering with other shortcut and key combinations?

**Comment by CeleritasCelery** [comment]
You should be able to call `company-complete` to reenable the pop up.

**Comment by duianto** [comment]
This came up on the gitter chat recently, `company-complete` completes to the next fork among the company candidates.
For example: `mess` completes to `message` and opens the popup.
The command `company-manual-begin` opens the popup without completing.

**Comment by chriskaukis** [comment]
Thanks. Not sure if this is the best way, but I think this accomplishes what I'm looking for in my user-config. In case anyone else is curious or interested. I took this keyboard shortcut from Visual Studio:

`(define-key evil-insert-state-map (kbd "C-j") 'company-manual-begin)`

**Comment by CeleritasCelery** [comment]
This will still be here for people looking for it, but go ahead and close this if you have found your answer.
