### ISSUE TITLE
find-file-at-point and directories with spaces

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#9743]
From here:
https://stackoverflow.com/questions/46661120/emacs-find-file-at-point-how-to-escape-spaces-in-filepath

`gf`: `find-file-at-point` does not work if the path contains spaces.

What should happen:
![screenshot_2017-10-16_16-38-21](https://user-images.githubusercontent.com/12512930/31617894-bc4e0f82-b290-11e7-8504-17209605ae06.png)

What actually happens:
![screenshot_2017-10-16_16-38-51](https://user-images.githubusercontent.com/12512930/31617916-cad8b76e-b290-11e7-84c4-4c5128a72b1b.png)

Also tab complete in the helm buffer does not work:
![screenshot_2017-10-16_16-39-34](https://user-images.githubusercontent.com/12512930/31617934-df184c8a-b290-11e7-9efd-c4e318c17fd6.png)

I am on `develop` and emacs 26.0.90.1 but according to the stackoverflow post more versions are affected.

**Comment by CeleritasCelery** [comment]
that is a Emacs built in so this is not a Spacemacs issue. We could create a function that addresses this, but do you know a good way to detect files with spaces? I can't think of one. At least that is not reliable.

**Comment by gdkrmr** [comment]
bgw, I reported it to the emacs devs, https://debbugs.gnu.org/cgi/bugreport.cgi?bug=28870
