### ISSUE TITLE
Elixir/Alchemist Go To Definition brings "Visit tags table" quickfix

### ISSUE THREAD

**Issue by svileng** [syl20bnr/spacemacs#9756]
#### Description :octocat:
I recently re-installed my OS and got Spacemacs again. I'm using the Elixir layer that includes with Alchemist, that provides things like Go to definition.

Previously (not sure which version I had, sadly) pressing `SPC m g g` would just navigate to the function in whichever Elixir module it is, simple as that, nothing else.

Currently, the same shortcut also brings the Quickfix bottom window with the following text, expecting some input:

```
Visit tags table (default TAGS): ~/Development/.....
```

which just stays there, even after I do `SPC m ,` to go back. The only way to get rid of it is to do `SPC w j` + `Ctrl g`, but If I try to `Ctrl g` while I'm looking at the newly opened buffer, this closes the buffer as well.

#### Reproduction guide :beetle:
- Start Spacemacs
- Open an Elixir file (*.ex)
- `SPC m g g` on a function call to go to function's definition
- Quickfix message above comes up

*Observed behaviour:* :eyes: :broken_heart:
Quickfix comes up with the mentioned annoying message, until dismissed, which dismisses the currently opened buffer as well.

*Expected behaviour:* :heart: :smile:
Quickfix should not be there to bother you.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(markdown html javascript yaml elixir ivy
          (auto-completion :variables auto-completion-enable-snippets-in-popup t)
          emacs-lisp git osx)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
N/A

**Comment by CeleritasCelery** [comment]
You should report this upstream at https://github.com/jacktasia/dumb-jump

**Comment by svileng** [comment]
Thanks @CeleritasCelery! I'm closing this one.

**Comment by svileng** [comment]
@CeleritasCelery According to @jacktasia this is not an issue with the `dumb-jump` package, since it doesn't use tags: jacktasia/dumb-jump/issues/167 . It seems that when I do `SPC h d k SPC m g g` the jump to definition is part of Spacemacs' core. Could you consider reopening this issue? Thanks!

**Comment by CeleritasCelery** [comment]
looks like it was complex then I expected. What is value of `spacemacs-jump-handlers` in an elixir buffer?

**Comment by jeremyjh** [comment]
@CeleritasCelery I respectfully disagree. `alchemist` does not contain a reference to helm or gtags, so I do not think it is responsible for invoking this. 

@svileng I was able to get rid of this by removing the `gtags` layer from my configuration. Of course you may need that for other languages.

**Comment by svileng** [comment]
@jeremyjh Thanks for the tip! I just checked my `.spacemacs` and I don't seem to have `gtags` explicitly added. That's my current list:

```
   '(
     markdown
     html
     javascript
     yaml
     elixir
     ivy
     (auto-completion :variables
                      auto-completion-enable-snippets-in-popup t)
     emacs-lisp
     git
     osx
     )
```
Is it possible, and how can I find out, if one of these packages includes `gtags` behind the scenes?

**Comment by sdwolfz** [comment]
This might be related to #9873 , try adding this to your `dotspacemacs/user-config` and restart:
```emacs-lisp
(setq spacemacs-default-jump-handlers
  (remove 'evil-goto-definition spacemacs-default-jump-handlers))
```

**Comment by svileng** [comment]
@sdwolfz Brilliant, that worked! Cheers 🍻
