### ISSUE TITLE
Exporting to html sometimes ignores export settings

### ISSUE THREAD

**Issue by abellmann** [syl20bnr/spacemacs#9758]
#### Description :octocat:

Exporting from org to html sometimes ignores export settings

#### Reproduction guide :beetle:

- Start Emacs

- Create an org file (i.e. test.org) with the following code

``` org
#+BEGIN_SRC sh :exports none
echo hello

#+END_SRC

#+RESULTS:
: hello

```

- Save the file
- Close the buffer with SPC bd
- reopen with SPC f f 
- The org file is opened in org-mode
- First Export: Export to html with C-c C-e h o 
- Activate org mode with SPC SPC org-mode (although it is already active)
- Second Export: Export to html with C-c C-e h o

*Observed behaviour:* :eyes: :broken_heart:

the first export exports the code and the result.

the second export does not export the code and the result...

I see no error messages in the Messages buffer. 

*Expected behaviour:* :heart: :smile:

both exports should not export code and result

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(asciidoc ruby csv windows-scripts vimscript sql
          (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle :disabled-for org erc)
          ansible confluence clojure deft emacs-lisp git github html
          (ibuffer :variables ibuffer-group-buffers-by nil)
          ivy markdown
          (org :variables org-enable-reveal-js-support t)
          org-ab org-ab-convenience pandoc plantuml prodigy python ranger restclient semantic
          (shell :variables shell-default-shell 'eshell)
          (syntax-checking :variables syntax-checking-enable-by-default nil)
          smex
          (journal :variables org-journal-dir "~/TODO/journal")
          yaml cygwin outlook)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

#### Backtrace :paw_prints:

```


```

**Comment by CeleritasCelery** [comment]
Can you reproduce with stock emacs?

**Comment by abellmann** [comment]
This works fine with stock emacs

**Comment by abellmann** [comment]
I have reset my elpa directory and afterwards this worked. This issue can be closed. Sorry for the bother..
