### ISSUE TITLE
exit insert mode `emacs -nw`

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#9765]
When spacemacs in the terminal (`emacs -nw`) is in insert mode and I press `ESC` to quit it, I always have to wait around 0.3-0.5 sec to actually get into normal mode. If I press any key before that, spacemacs remains in insert mode and simply inserts the keys I pressed. Getting into insert mode is instant (i.e. pressing `o` or `i`).
Is this a known `evil` bug?

**Comment by sdwolf** [comment]
Are you using tmux? If so add this to your `tmux.conf`:
```tmux
set -gs escape-time 10
```

This is not related to `emacs` nor `evil`.

**Comment by gdkrmr** [comment]
thanks for the competent advice, I am glad that I did not start using the elisp profiler :-)
