### ISSUE TITLE
Can not move commits up and down in the magit interactive rebase buffer

### ISSUE THREAD

**Issue by joakim-hove** [syl20bnr/spacemacs#9767]
#### Description :octocat:
Can not move commits up and down when doing interactive rebase with Magit.

When doing interactive rebase I get the following list of commits
in the git-rebase-todo buffer:

pick sha1 Commit message1
pick sha2 Commit message2
pick sha3 fixup! Commit message1

When trying to shift the fixup commit up with M-k nothing happens?

#### Reproduction guide :beetle:
1. Start Emacs
2. Make some commits with magit.
3. Initiate an interactive rebase
4. Try to reorder commits with M-k and M-j - nothing happens. 

*Observed behaviour:* :eyes: :broken_heart:
Can not move commits up and down in the git-rebase buffer.

*Expected behaviour:* :heart: :smile:
Should be able to move commits up and down.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.2
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git markdown c-c   python syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

```

**Comment by Alexander-Miller** [comment]
What does `SPC h d k M-k` say?

What is `M-k` bound to?

Did you globally rebind `M-k` somewhere in your config?

**Comment by joakim-hove** [comment]
>What does SPC h d k M-k say? 

Now this is a bit embarassing; I have just come from regular emacs and maybe I misunderstood `M-k`? I pressed key sequenc `[Esc] k`

Anyway:  `SPC h d k M-k` gives:
```txt
<escape> runs the command evil-force-normal-state, which is an interactive
compiled Lisp function in `evil-commands.el'.

It is bound to <escape>.

(evil-force-normal-state)

Switch to normal state without recording current command.
``` 
I can not enter the final `k`.

> Did you globally rebind M-k somewhere in your config?

No

**Comment by Alexander-Miller** [comment]
> I have just come from regular emacs and maybe I misunderstood M-k?

`M-k` is regular emacs and you did misunderstand it, badly. The M stands for mod, and in most cases means the Alt key (it's a historical name).
I don't know what gave you the idea that M- has anything to do with escape, but you should quickly forget all about it.

**Comment by joakim-hove** [comment]
> M-k is regular emacs and you did misunderstand it, badly. The M stands for mod, and in most cases means the Alt key (it's a historical name).

OK - sorry about. I am on a plain vanilla Ubuntu 16.04 and it seems the windowmanager grabs the `Alt` key? I have tried `[Alt Gr]`, `[Fn]` and "The Windows button" to no avail - so it basically seems I can not enter the `mod` key at all?

>I don't know what gave you the idea that M- has anything to do with escape, but you should quickly forget all about it.

OK - I have got the memo; but I would like to point out that in the normal emacs documentation `M-x run-this-function` the `M-x` key sequence has for as long as I have known been bound to `Esc-x` for; so it was not that illogical?

**Comment by Alexander-Miller** [comment]
> it seems the windowmanager grabs the Alt key?

That's possible. Looks like you need to go dive into Ubuntu's settings. I don't use it, so I can't really help here. [This may be relevant](https://askubuntu.com/questions/122209/how-do-i-modify-or-disable-the-huds-use-of-the-alt-key).

> the M-x key sequence has for as long as I have known been bound to Esc-x by default; so it was not that illogical?

Yeah, my bad, this one's on me. Turns out stock emacs does translate Escape+key to Mod+key. Can't imagine it's pleasant to use, but it does work. Spacemacs is different here, escape means cancel, as it does almost everywhere else. You'll need to get used to Alt, once you've taken it back from Ubuntu.

**Comment by joakim-hove** [comment]
Thank you; the provided link (reposted by me): [Ubuntu: do not grab the Alt key](https://askubuntu.com/questions/122209/how-do-i-modify-or-disable-the-huds-use-of-the-alt-key) solved the issue.
