### ISSUE TITLE
`find_spec_for_exe': can't find gem bundler (>= 0) (Gem::GemNotFoundException)

### ISSUE THREAD

**Issue by grekko** [syl20bnr/spacemacs#9769]
#### Description :octocat:

The ruby layer of my spacemacs installation seems to have a problem with finding/executing bundler.

#### Reproduction guide :beetle:
- Start Emacs
- Load a ruby test file `test/foo_test.rb`
- Type <kbd>SPC</kbd><kbd>m</kbd><kbd>t</kbd><kbd>b</kbd> to run the test file

*Observed behaviour:* :eyes: :broken_heart:
```
Comint started at Sun Oct 22 22:04:13

bundle exec ruby -I'lib:test' /Users/gregoryigelmund/scm/project/test/unit/foo_test.rb
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem bundler (>= 0) (Gem::GemNotFoundException)
  from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems.rb:258:in `bin_path'
  from /Users/gregoryigelmund/scm/project/bin/bundle:3:in `<main>'

Comint exited abnormally with code 1 at Sun Oct 22 22:04:13
```

*Expected behaviour:* :heart: :smile:

When I open a new shell (fish) and copy/paste the command emacs displayed in the comint window

```
$ bundle exec ruby -I'lib:test' /Users/gregoryigelmund/scm/project/test/unit/foo_test.rb
```

The result is:

```
Run options: --seed 53647

# Running:

.......

Finished in 0.388372s, 18.0240 runs/s, 38.6228 assertions/s.
7 runs, 15 assertions, 0 failures, 0 errors, 0 skips
```

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby markdown javascript xkcd ruby-on-rails erlang elixir osx html shell helm auto-completion emacs-lisp git markdown spell-checking syntax-checking version-control)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB

**Comment by ChasManRors** [comment]
I am having a very similar issue.

**Comment by grekko** [comment]
I‘ve recently been able to fix this.

The underlying problem was the way my `fish`-shell initialized rbenv.

I replaced:

```
status --is-interactive; and . (rbenv init -|psub)
```

just with:
```
(rbenv init -|psub)
```

**Comment by grekko** [comment]
- [x] Fixed for me
- [x] Solution published

=> close
