### ISSUE TITLE
Issues using local multi-theme package

### ISSUE THREAD

**Issue by Azphreal** [syl20bnr/spacemacs#9773]
I have a [local theme](https://github.com/Azphreal/emacs-pencil-theme) installed at `~/.emacs.d/private/local/pencil-theme`, containing two themes named `pencil-light` and `pencil-dark`. In my `init.el` I have:

- `dotspacemacs-additional-packages '((pencil-theme :location local))`
- `dotspacemacs-excluded-packages '(pencil-light pencil-dark)`
- `dotspacemacs-themes '(pencil-light pencil-dark)`

all in their default sections as required.

My understanding (or belief) on how this is supposed to be handled:
- folder `pencil-theme` is added to load path;
- `autoload` magic comment is run from `pencil-theme.el`;
- magic comment results in adding the directory to the theme path;
- when Spacemacs goes looking for the `pencil-light` theme, it can find it because `pencil-theme` is in the theme load path.

What actually happens:
- folder `pencil-theme` is added to load path;

I've added `(use-package pencil-theme)` to my `user-config` in `init.el` but I was under the impression that this shouldn't be required. Additionally, because it's sourced so late, Spacemacs starts with the default dark theme, since the `pencil-` themes don't exist when it loads themes.

I've used other themes as a guide on how to set things up, so I'm fairly sure the issue isn't in the theme, it's in how it's handled and my conflicting thoughts.

How am I actually supposed to use it, as part of Spacemacs, without manually specifying `use-package` or `load`?

**Comment by CeleritasCelery** [comment]
As mentioned [here](https://github.com/syl20bnr/spacemacs/issues/7373#issuecomment-276867188) the correct solution would be 
```elisp
(dotspacemacs-themes '((pencil-light :location local) (pencil-dark :location local)))
```
or

```elsip
(dotspacemacs-themes '((pencil-light :location (recipe :fetcher github :repo "Azphreal/emacs-pencil-theme"))))
```
The only thing I am not sure about is if it will still work despite your package name not being the same as your theme name. But you **must** use the theme name.

all the rest of the stuff you did is unnecessary.

**Comment by Azphreal** [comment]
I was basing it on stuff like the Spacemacs theme and Gruvbox, which all handle multi-themes in this way.

Using a local location obviously doesn't work because the package isn't named the same as the themes, hence the workaround attempt.

The second option works for the first theme, but not the second. The following all result in loading `pencil-light` correctly, but fail to load `pencil-dark`. Attempting to switch themes moves to the theme transient state with `pencil-light` loaded, where I can select `pencil-dark`, but it won't do it with just `SPC T n`.

- `(dotspacemacs-themes '((pencil-light :location (recipe :fetcher github :repo "Azphreal/emacs-pencil-theme")) pencil-dark))`
- `(dotspacemacs-themes '((pencil-light :location (recipe :fetcher github :repo "Azphreal/emacs-pencil-theme")) (pencil-dark :location local)))`
- `(dotspacemacs-themes '((pencil-light :location (recipe :fetcher github :repo "Azphreal/emacs-pencil-theme")) (pencil-dark :location (recipe :fetcher github :repo "Azphreal/emacs-pencil-theme"))))`

What did work was using the fetcher in `dotspacemacs-additional-packages` and not specifying in the themes; however, while it correctly loads both themes, it still opens the transient layer.

**Comment by CeleritasCelery** [comment]
> however, while it correctly loads both themes, it still opens the transient layer.

I am not sure I follow

**Comment by Azphreal** [comment]
Apologies. I mean to say that it'll load both `pencil-light` and `pencil-dark` successfully and I can switch between them with `SPC T n`. However, it will also open the transient layer whenever I switch with that shortcut (which I believe is not intended).

**Comment by CeleritasCelery** [comment]
> will also open the transient layer

do you mean transient state? or maybe helm-themes buffer? Not sure what a transient layer is. 😕

**Comment by Azphreal** [comment]
Sorry, I did indeed mean transient state.

**Comment by CeleritasCelery** [comment]
So it looks like you are on develop. I couldn’t find a themed transient state which is why I was confused :smile. Also, based on #9671 that is the correct behavior now.

**Comment by Azphreal** [comment]
Hm, okay. Thanks. I might look at removing that binding then.

**Comment by CeleritasCelery** [comment]
Out of curiosity, why don’t you like the transient state?

**Comment by Azphreal** [comment]
I personally only use two themes at a time, so it's not particularly useful for me, is all. It just potentially disables `n` and `p` immediately after a theme switch.

**Comment by duianto** [comment]
@Azphreal 
The PR:
Enable backward theme cycling and add dedicated transient-state #9671

Opened the themes transient state with: `SPC T N`, leaving: `SPC T n` with the previous behavior of only cycling to the next theme.

But syl20bnr combined them in this commit:
[Remove T N binding and make T n cycle and start the transient state](https://github.com/syl20bnr/spacemacs/commit/037d1367)

One solution might be to add a user variable, that makes it possible to disable the combined behaviour.

It could look something like this:
```elisp
(if themes-transient-state-leader-T-N
    (progn
      (spacemacs/set-leader-keys "Tn" 'spacemacs/cycle-spacemacs-theme)
      (spacemacs/set-leader-keys "TN" 'spacemacs/theme-transient-state/body))
  (spacemacs/set-leader-keys "Tn"
    'spacemacs/theme-transient-state/spacemacs/cycle-spacemacs-theme))
```
and replace these two lines:
https://github.com/syl20bnr/spacemacs/blob/develop/layers/+distributions/spacemacs-base/keybindings.el#L161-L162

I'm don't know where the variable could be defined, and maybe there's a better name for it.
