### ISSUE TITLE
"^" doesn't match start of string in helm regexes

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#9774]
I have `helm-ff-skip-boring-files` set to `t`, but files that should be hidden still appear in the helm find files list.
EDIT: Looks like it might be my `helm-boring-file-regexp-list` at fault. I have `^\\.[^.]+$` to hide files beginning with a dot other than `.` and `..`, but the dot-files still appear in the list.

**Comment by CeleritasCelery** [comment]
I think you want `^\\.[^.]`. Otherwise you will you will still get files like `.foo.rc`

**Comment by beojan** [comment]
First of all, I need something that actually hides the files to begin with. It looks like `helm-boring-files-regexp-list` may be ignored, because other regexes I add to it also seem to be ignored.

**Comment by CeleritasCelery** [comment]
works for me. Whats your value of `helm-boring-files-regexp-list`?

**Comment by beojan** [comment]
```emacs-lisp
("^\\." "\\.hi$" "\\.o$" "~[:digit:]*$" "\\.bin$" "\\.lbin$" "\\.so$" "\\.a$"
"\\.ln$" "\\.blg$" "\\.bbl$" "\\.elc$" "\\.lof$" "\\.glo$" "\\.idx$" "\\.lot$"
"\\.svn/\\|\\.svn$" "\\.hg/\\|\\.hg$" "\\.git/\\|\\.git$" "\\.bzr/\\|\\.bzr$"
"CVS/\\|CVS$" "_darcs/\\|_darcs$" "_MTN/\\|_MTN$" "\\.fmt$" "\\.tfm$"
"\\.class$" "\\.fas$" "\\.lib$" "\\.mem$" "\\.x86f$" "\\.sparcf$" "\\.dfsl$"
"\\.pfsl$" "\\.d64fsl$" "\\.p64fsl$" "\\.lx64fsl$" "\\.lx32fsl$" "\\.dx64fsl$"
"\\.dx32fsl$" "\\.fx64fsl$" "\\.fx32fsl$" "\\.sx64fsl$" "\\.sx32fsl$"
"\\.wx64fsl$" "\\.wx32fsl$" "\\.fasl$" "\\.ufsl$" "\\.fsl$" "\\.dxl$" "\\.lo$"
"\\.la$" "\\.gmo$" "\\.mo$" "\\.toc$" "\\.aux$" "\\.cp$" "\\.fn$" "\\.ky$"
"\\.pg$" "\\.tp$" "\\.vr$" "\\.cps$" "\\.fns$" "\\.kys$" "\\.pgs$" "\\.tps$"
"\\.vrs$" "\\.pyc$" "\\.pyo$" "\\.fls$" "\\.out" "\\.blx\\.bib"
"\\.synctex\\.gz")
```

**Comment by CeleritasCelery** [comment]
I don’t see your regex. How are you adding it?

**Comment by beojan** [comment]
It's the first one. I removed the `[^.]*$` portion.

**Comment by CeleritasCelery** [comment]
`(push "\\.[^.]" helm-boring-file-regexp-list)` excludes dotfiles for me. If it is still not working you should open an issue with helm.

**Comment by beojan** [comment]
I *am* using the `develop` branch of Spacemacs, maybe that has something to do with it.

**Comment by beojan** [comment]
It turns out the problem is that `^` doesn't match the start of a string in a helm-regex. This is only a problem in Spacemacs (doesn't happen with `emacs-helm.sh`).

**Comment by CeleritasCelery** [comment]
try ``\\`\\.[^.]``

**Comment by beojan** [comment]
That doesn't work either (though I don't see why it would).
`^` works correctly with `emacs-helm.sh` so there's a bug in Spacemacs.

**Comment by beojan** [comment]
I also see the bug in the `master` branch.

**Comment by syl20bnr** [comment]
I spend some time to look at it, removed all the helm configuration from spacemacs and it still happens. At first I believed it was because you misstyped the variable name, it is `file` not `files` but even with the right variable it did not work.
I guess this is a package we install besides helm but I have no idea which one it is.

**Comment by beojan** [comment]
> At first I believed it was because you misstyped the variable name, it is `file` not `files` but even with the right variable it did not work.

That was a typo here (corrected now), I had it correct in `.spacemacs`.

**Comment by Miciah** [comment]
Helm compiles the list of regexp strings `helm-ff-boring-file-regexp-list` into a single regexp string `helm-ff--boring-regexp` by appending `$` to each regexp and then joining the list using `|`.  If you examine `helm-ff--boring-regexp`, you'll see that your regexp `"^\\."` appears with a `$` appended: `"^\\.$\\|..."` (where `...` represents the other regexps from `helm-ff-boring-file-regexp-list`).

@beojan, try adding `.*` to your pattern.  For example, put the following in `user-config`:
```emacs-lisp
  (setq helm-ff-skip-boring-files t
        helm-boring-file-regexp-list
        '("^\\..*" "\\.hi$" "\\.o$" "~[:digit:]*$" "\\.bin$" "\\.lbin$" "\\.so$" "\\.a$"
         "\\.ln$" "\\.blg$" "\\.bbl$" "\\.elc$" "\\.lof$" "\\.glo$" "\\.idx$" "\\.lot$"
         "\\.svn/\\|\\.svn$" "\\.hg/\\|\\.hg$" "\\.git/\\|\\.git$" "\\.bzr/\\|\\.bzr$"
         "CVS/\\|CVS$" "_darcs/\\|_darcs$" "_MTN/\\|_MTN$" "\\.fmt$" "\\.tfm$"
         "\\.class$" "\\.fas$" "\\.lib$" "\\.mem$" "\\.x86f$" "\\.sparcf$" "\\.dfsl$"
         "\\.pfsl$" "\\.d64fsl$" "\\.p64fsl$" "\\.lx64fsl$" "\\.lx32fsl$" "\\.dx64fsl$"
         "\\.dx32fsl$" "\\.fx64fsl$" "\\.fx32fsl$" "\\.sx64fsl$" "\\.sx32fsl$"
         "\\.wx64fsl$" "\\.wx32fsl$" "\\.fasl$" "\\.ufsl$" "\\.fsl$" "\\.dxl$" "\\.lo$"
         "\\.la$" "\\.gmo$" "\\.mo$" "\\.toc$" "\\.aux$" "\\.cp$" "\\.fn$" "\\.ky$"
         "\\.pg$" "\\.tp$" "\\.vr$" "\\.cps$" "\\.fns$" "\\.kys$" "\\.pgs$" "\\.tps$"
         "\\.vrs$" "\\.pyc$" "\\.pyo$" "\\.fls$" "\\.out" "\\.blx\\.bib"
         "\\.synctex\\.gz"))
```
Does that resolve the issue for you?
