### ISSUE TITLE
Anaconda code navigation does not work.

### ISSUE THREAD

**Issue by biocyberman** [syl20bnr/spacemacs#9777]
#### Description :octocat:
Code navitation does not work in anaconda-mode

#### Reproduction guide :beetle:
- Start Emacs
- Open a python project
- Move cursor to a function call, hit `SPC m g g` to use `anaconda-mode-find-definition`

*Observed behaviour:* :eyes: :broken_heart:

- `SPC m g g` is bound to `jump-to-definition`
- After completing this key sequence, nothing happens
- Running both `anaconda-mode-find-definition` and `jump-to-definition` gave the same silent result
- Deactivate and reactivate anaconda-mode for the python buffer did not help.

*Expected behaviour:* :heart: :smile:

Cursor should jump to the definition of the function or variable in the following cases:
- In the same source file
- In other source file within the same git repo if the fuction or variable is defined in other file.
- In the source file of the system package that defines the fuction or variable.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af1454)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion c-c++ d django ess org emacs-lisp git github gtags html java javascript latex markdown python ranger ruby php search-engine semantic spacemacs-layouts shell syntax-checking yaml erc)
```
- System configuration features: XAW3D XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11

**Comment by CeleritasCelery** [comment]
Since `anaconda-mode-find-definition` doesn't work, you should report this upstream at anaconda-mode.

**Comment by syl20bnr** [comment]
@biocyberman the upstream ticket is closed, are you ok now ?

**Comment by biocyberman** [comment]
@syl20bnr Thanks for giving me a heads up. I still can't get the thing to work. I am testing a temporary clean setup with only python layer enabled.

**Comment by syl20bnr** [comment]
What's the content of the `*anaconda*` buffer? (buffer may be named slightly differently)

**Comment by biocyberman** [comment]
@syl20bnr I have `*anaconda-mode*` buffer, and it is empty.  

Following are my observation with verbatim installation of spacemacs:

## 1.  Reproduction guide (yes you need a guide for reproduction, you should laugh).
- backup .spacemacs and .emacs.d
- clone spacemacs: git clone https://github.com/syl20bnr/spacemacs.git  ~/.emacs.d
- startup emacs, choose config `spacemacs`, `vim-mode`, and `helm` and then enable `python` layer. I also attached `.spacemacs` file here (file got renamed so I can upload)
[dot.spacemacs.txt](https://github.com/syl20bnr/spacemacs/files/1429966/dot.spacemacs.txt)
- One may need to restart emacs after this because `SPC f e R` does not work (i forgot the error message).
- Rename the attached file `testpython.py.txt` to `testpython.py` and open it with spacemacs.
[testpython.py.txt](https://github.com/syl20bnr/spacemacs/files/1430028/testpython.py.txt)
- Use code naviation feature of `anaconda-mode`: Place cursor at function call of `myfun()`. Hit `g d` or `, g g ` or `SPC m g g`. 

## 2. Observed behaviour:

- Cursor does not jump to function defintion of `myfun` at  `def myfun()`. 
- On the first attempt one may see content of `*anaconda-mode*` buffer like below:
```
Searching for anaconda_mode==0.1.9
Reading https://pypi.python.org/simple/anaconda_mode/
Downloading https://pypi.python.org/packages/a6/f5/a8d433eb628e1584a5f5425a72770cc56d09d99dbc384e08178457cd5d23/anaconda_mode-0.1.9.tar.gz#md5=94c2cd0b72834bd1b1a5a6904dbc774a
Best match: anaconda-mode 0.1.9
Processing anaconda_mode-0.1.9.tar.gz
Writing /tmp/easy_install-5Gtajw/anaconda_mode-0.1.9/setup.cfg
Running anaconda_mode-0.1.9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5Gtajw/anaconda_mode-0.1.9/egg-dist-tmp-3uCeh_
no previously-included directories found matching 'test'
creating /home/user/.emacs.d/.cache/anaconda-mode/0.1.9/anaconda_mode-0.1.9-py2.7.egg
Extracting anaconda_mode-0.1.9-py2.7.egg to /home/user/.emacs.d/.cache/anaconda-mode/0.1.9
Adding anaconda-mode 0.1.9 to easy-install.pth file

Installed /home/user/.emacs.d/.cache/anaconda-mode/0.1.9/anaconda_mode-0.1.9-py2.7.egg
Processing dependencies for anaconda_mode==0.1.9
Searching for service_factory>=0.1.5
Skipping development or system egg: service-factory 0.1.2
Reading https://pypi.python.org/simple/service_factory/
Downloading https://pypi.python.org/packages/d1/32/bacd539bc748af613082f8cf80c82311373a05bb4af2d43bc2ff5bbdcdcc/service_factory-0.1.5.tar.gz#md5=a0dd7745280da2284e8bdc2c03b853e4
Best match: service-factory 0.1.5
Processing service_factory-0.1.5.tar.gz
Writing /tmp/easy_install-vYiifc/service_factory-0.1.5/setup.cfg
Running service_factory-0.1.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-vYiifc/service_factory-0.1.5/egg-dist-tmp-40M_gx
creating /home/user/.emacs.d/.cache/anaconda-mode/0.1.9/service_factory-0.1.5-py2.7.egg
Extracting service_factory-0.1.5-py2.7.egg to /home/user/.emacs.d/.cache/anaconda-mode/0.1.9
Adding service-factory 0.1.5 to easy-install.pth file

Installed /home/user/.emacs.d/.cache/anaconda-mode/0.1.9/service_factory-0.1.5-py2.7.egg
Processing dependencies for service_factory>=0.1.5
Finished processing dependencies for service_factory>=0.1.5
Searching for jedi>=0.11
Skipping development or system egg: jedi 0.8.1
Reading https://pypi.python.org/simple/jedi/
Downloading https://pypi.python.org/packages/08/8d/34b133dfa210b55e7efaa8b09c736a8f4383fcda0b6487fc43a1db3c7ee7/jedi-0.11.0.tar.gz#md5=a948c0903b03bf361c60742947f076a0
Best match: jedi 0.11.0
Processing jedi-0.11.0.tar.gz
Writing /tmp/easy_install-IKUxZD/jedi-0.11.0/setup.cfg
Running jedi-0.11.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-IKUxZD/jedi-0.11.0/egg-dist-tmp-co40I2
warning: no files found matching 'jedi/parser/python/grammar*.txt'
warning: no previously-included files matching '*.pyc' found under directory '*'
zip_safe flag not set; analyzing archive contents...
jedi.__main__: module references __file__
jedi.evaluate.pep0484: module references __file__
jedi.evaluate.representation: module references __file__
jedi.evaluate.sys_path: module references __file__
jedi.evaluate.compiled.__init__: module references __file__
jedi.evaluate.compiled.fake: module references __file__
jedi.evaluate.compiled.mixed: module MAY be using inspect.getsourcefile
creating /home/user/.emacs.d/.cache/anaconda-mode/0.1.9/jedi-0.11.0-py2.7.egg
Extracting jedi-0.11.0-py2.7.egg to /home/user/.emacs.d/.cache/anaconda-mode/0.1.9
Adding jedi 0.11.0 to easy-install.pth file

Installed /home/user/.emacs.d/.cache/anaconda-mode/0.1.9/jedi-0.11.0-py2.7.egg
Processing dependencies for jedi>=0.11
Searching for parso==0.1.0
Reading https://pypi.python.org/simple/parso/
Downloading https://pypi.python.org/packages/32/f4/9f1ee3fc5f7a23aee6454feeadef423ef1aed405208135e81620b4e3ba77/parso-0.1.0.tar.gz#md5=b1713a03af5935d96dfde1e853ccda5a
Best match: parso 0.1.0
Processing parso-0.1.0.tar.gz
Writing /tmp/easy_install-BxGCFL/parso-0.1.0/setup.cfg
Running parso-0.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-BxGCFL/parso-0.1.0/egg-dist-tmp-S_JLy5
warning: no previously-included files matching '*.pyc' found under directory '*'
zip_safe flag not set; analyzing archive contents...
parso.grammar: module references __file__
creating /home/user/.emacs.d/.cache/anaconda-mode/0.1.9/parso-0.1.0-py2.7.egg
Extracting parso-0.1.0-py2.7.egg to /home/user/.emacs.d/.cache/anaconda-mode/0.1.9
Adding parso 0.1.0 to easy-install.pth file

Installed /home/user/.emacs.d/.cache/anaconda-mode/0.1.9/parso-0.1.0-py2.7.egg
Processing dependencies for parso==0.1.0
Finished processing dependencies for parso==0.1.0
Finished processing dependencies for jedi>=0.11
Finished processing dependencies for anaconda_mode==0.1.9

```
- However, on the next attempt, `*anaconda-mode*` buffer is empty.

**Comment by biocyberman** [comment]
I also tried anaconda mode without spacemacs, and it works. Therefore, I think there is something not working with anaconda-mode in spacemacs. 

When anaconda-mode is working on non-spacemacs setup, there is a line at the end of `*anaconda-mode*` buffer: "anaconda_mode port 45143"

**Comment by oliveratutexas** [comment]
Any update on this?

**Comment by biocyberman** [comment]
It may be there is nothing wrong with the layer, except that it is not well documented:
I now can use "go to definition" without a problem. The secret? I have to activate a virtual python environment first:

```bash
# In the shell:
cd </path/to/myrepo>
python -m venv env
#install all dependecies for development
```
After open the python script I want to edit. Hit `SPC m V a` and navigate to the `env` directory, and `ENTER`. Now `g d` at point should work.
