### ISSUE TITLE
org-mode breakage: "cond: symbol's function definition is void: org-element-property"

### ISSUE THREAD

**Issue by coventry** [syl20bnr/spacemacs#9778]
#### Description :octocat:

I'm having a couple of problems using org-mode with spacemacs. Ran into this while attempting a reproduction.

#### Reproduction guide :beetle:

- `docker run -it ubuntu`
- `apt-get update`
- `apt-get install -y emacs git`
- `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`
- `emacs` (Choose emacs keybinding during installation)
- `C-x C-f tst.org <RET>`
- Type `|`, then `<TAB>`.

*Observed behaviour:* :eyes: :broken_heart:

```
Debugger entered--Lisp error: (void-function org-element-property)
  (org-element-property :post-affiliated (org-element-at-point))
  (cond (table-type (org-element-property :post-affiliated (org-element-at-point))) ((save-excursion (and (re-search-backward org-table-border-regexp nil t) (line-beginning-position 2)))) (t (point-min)))
  org-table-begin(any)
  org-at-table\.el-p()
  org-cycle(nil)
  call-interactively(org-cycle nil nil)
  command-execute(org-cycle)
```

*Expected behaviour:* :heart: :smile:

New line, and a new pipe symbol.

This is emacs version 24.5.1, spacemacs v.0.200.9, ubuntu version 16.04.2 LTS.

**Comment by CeleritasCelery** [comment]
Can you reproduce with stock Emacs (`SPC q D`)?

**Comment by coventry** [comment]
Stock emacs behaves as described in the "expected behavior" section.

**Comment by CeleritasCelery** [comment]
Try using Spacemacs org version. Included `org` when you restart with stock emacs.

**Comment by coventry** [comment]
Thanks, was an old org-mode version.

**Comment by coventry** [comment]
[My deleted comment was confused].

Restarting with `org` included during `SPC q D` results in slightly different observed behavior. `<TAB>` takes the buffer from `|` to

```
| |
| |
```

with the cursor between the two pipes. So, not a standalone `org-mode` bug.

**Comment by CeleritasCelery** [comment]
what version of org do you have from elpa?

**Comment by rocaluis** [comment]
@coventry, reproduced same result. 
  `<TAB> |` produces:

```
|   |
|   |
```

**Comment by syl20bnr** [comment]
Reproduced as well with the org layer.
