### ISSUE TITLE
Using 'h' key while being in helm grep always starts helm help

### ISSUE THREAD

**Issue by pprzetacznik** [syl20bnr/spacemacs#9780]
When  I run helm grep with `SPC f g` and I've got results already printed in the helm window I move in results window with emacs shortcuts (h j k l). While `j`, `k` and `l` shortcuts works fine, h shortcut is always broken and pop ups helm help window all the time. Is there a way to disable this shortcut?

**Comment by syl20bnr** [comment]
I cannot reproduce it, can you provide reproductions steps so I'm sure I'm doing the same thing as you ?

**Comment by pprzetacznik** [comment]
This is how I'm reproducing this:
- Spc f g enter// to start searching with helm grep,
- I put sentence I'm searching for and press enter,
- I specify files, eg. *.* and press enter,
- I specify directory and press enter,
- I see results like this
![image](https://user-images.githubusercontent.com/2965785/32145434-f98fa4a4-bcc8-11e7-963f-846ee7bacdf4.png)
- now I can control position of cursor of these results with buttons `j k l` as I do that in vim but when I press `h` button I open such window:
![image](https://user-images.githubusercontent.com/2965785/32145437-0b87e522-bcc9-11e7-9f6d-3bf2e3df4caf.png)

**Comment by syl20bnr** [comment]
Thank you ! Should be fixed in develop.
