### ISSUE TITLE
Translate use-package instruction to spacemacs convention

### ISSUE THREAD

**Issue by nrolland** [syl20bnr/spacemacs#9782]
Many packages have self-contained configuration instructions using `use-package` or similar

```
(use-package dante
  :ensure t
  :after haskell-mode
  :commands 'dante-mode
  :init
  (add-hook 'haskell-mode-hook 'dante-mode)
  (add-hook 'haskell-mode-hook 'flycheck-mode))
```

It does not translate directly into adding an entry to `dotspacemacs-additional-packages`, which seems to be the easy way to add a package without going into the layer business.

What is the simplest translation for the prototypical installation instruction above into spacemacs world ?

**Comment by CeleritasCelery** [comment]
you can add the `use-package` code to your `dotspacemacs/user-config`. `use-package` is used in all the layers. If you have enough packages to config that it would be worth it consider adding your own private layer.

**Comment by syl20bnr** [comment]
As @CeleritasCelery wrote you can put this in the `user-config` function of your dotfile after adding the package to `dotspacemacs-additional-packages`.
