### ISSUE TITLE
Issue with add-hook for web-mode or js2-mode

### ISSUE THREAD

**Issue by ztlevi** [syl20bnr/spacemacs#9785]
#### Description :octocat:
Hello, guys.

I wanna add some hooks to `web-mode` and `js2-mode`, but it doesn't go well.

Here is what I am doing. I wanna to add header line for `web-mode` and `js2-mode` cuz they are derived from `fundamental-mode`. And I have to manually add these modes.

```
(which-function-mode)
;; when editing js file, this feature is very useful
;; (setq-default header-line-format
;;               '((which-func-mode ("" which-func-format " "))))

(defun set-header-line ()
  (setq header-line-format
        '((which-func-mode ("" which-func-format " ")))))
(add-hook 'prog-mode-hook 'set-header-line)
(add-hook 'text-mode-hook 'set-header-line)
(add-hook 'js2-mode-hook 'set-header-line)
(add-hook 'web-mode-hook 'set-header-line)
```

The tricky thing is the function actually works. I put down a simple test like `(add-hook 'web-mode-hook '(message "web-mode hook test"))` and it shows the message. So I guess there must be some kidding things going on when init these modes...

Does anyone have some ideas what's going on here?

Thanks!

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. e2a45e0c)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(helm spacemacs-completion spacemacs-layouts spacemacs-editing spacemacs-editing-visual spacemacs-evil spacemacs-language spacemacs-misc spacemacs-modeline spacemacs-navigation spacemacs-org spacemacs-visual
      (pandoc :variables org-pandoc-options
              '((standalone . t)))
      dash better-defaults ranger colors prodigy search-engine graphviz ivy
      (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips nil)
      (spell-checking :variables spell-checking-enable-by-default nil)
      (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
      (vinegar :variables vinegar-reuse-dired-buffer t)
      (spacemacs-layouts :variables layouts-enable-autosave nil layouts-autosave-delay 300)
      (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
      (ibuffer :variables ibuffer-group-buffers-by 'projects)
      (osx :variables osx-dictionary-dictionary-choice "Simplified Chinese - English" osx-command-as 'super)
      restclient
      (shell :variables shell-default-shell 'ansi-term)
      deft chrome
      (treemacs :variables treemacs-use-filewatch-mode t :variables treemacs-use-follow-mode t)
      react markdown
      (org :variables org-want-todo-bindings t)
      gpu yaml php
      (python :variables python-test-runner
              '(nose pytest))
      html javascript
      (typescript :variables typescript-fmt-on-save nil typescript-fmt-tool 'typescript-formatter)
      emacs-lisp
      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
      ztlevi
      (chinese :packages youdao-dictionary fcitx :variables chinese-enable-fcitx t chinese-enable-youdao-dict t))
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by karmajunkie** [comment]
Having the same issue with the hook not working, i'm using the `develop` branch and prettier-js-mode's hook isn't getting executed in my .js files. Works fine in several other file types like *.graphql and *.css

**Comment by ztlevi** [comment]
I figure out the issue and it's caused by `ranger`. I have switched to `dired` and no problem after using `dired`. I just feel like`ranger` package is not so active and `dired` works for me too. Also I put the issue in the ranger as well. Link's here https://github.com/ralesi/ranger.el/issues/170.

BTW, I tested `treemacs` as well, no issue for header line too.
