### ISSUE TITLE
Spacemacs is frozen when dotspacemacs-persistent-server is enabled

### ISSUE THREAD

**Issue by jack2gs** [syl20bnr/spacemacs#9788]
Hey guys,

Have you met this issue:
When `dotspacemacs-persistent-server` is enabled.  Then I opened a document to have a look.  After that, I closed the window. Then opened Emacs again. But the window was frozen. I could not do any change to the buffer.  That's not correct, I think.

Could anyone give me a hand plz?

*OS*: macOS 10.12.6
*Emacs*: 25.3
*Spacemacs*: 0.200.9.x

Thanks,
Jack

**Comment by CeleritasCelery** [comment]
https://emacs.stackexchange.com/questions/21643/what-do-i-do-when-emacs-is-frozen

**Comment by jack2gs** [comment]
Hi @CeleritasCelery ,

Thanks for your help. But I want to know how to use daemon server correctly. Because I found that in my way mentioned above, it will cause the buffer frozen.

Could you give me some advice plz?

Thanks,
Jack

**Comment by CeleritasCelery** [comment]
You are doing it right. Though generally people leave emacs open the entire session and just send files to it with `emacsclient -n`

**Comment by jack2gs** [comment]
Cool. Got it. Thank you very much！
