### ISSUE TITLE
cmake-font-lock integration with layouts

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#9790]
How can I integrate [this](https://github.com/Lindydancer/cmake-font-lock) package with Spacemacs? I have added it to a list of external packages and the package manager has successfully downloaded it. However, putting
```elisp
  (autoload 'cmake-font-lock-activate "cmake-font-lock" nil t)
  (add-hook 'cmake-mode-hook 'cmake-font-lock-activate)
```
(from the author's README) under `user-config` or `user-init` doesn't highlight a CMake file unless I explicitly run `SPC SPC cmake-font-lock-activate`.  I have `c-c++` layer activated. `cmake-font-lock` also relies on `company-cmake`.

My question is: how should I edit my config?

Also, would it make sense to incorporate it upstream into the `c-c++` layer?

**Comment by light2yellow** [comment]
Okay, so, adding just
```elisp
(add-hook 'cmake-mode-hook 'cmake-font-lock-activate)
```
to `user-init()` helps. Although it doesn't integrate well with
```elisp
dotspacemacs-auto-resume-layouts t
```
The issue is, whenever a layout is restored, only the last active buffer gets highlighted (of course, if it contains a listfile). All other CMake buffers are not highlighted when selected. Any clue?
