### ISSUE TITLE
 Home buffer not recentered on frame un/maximize

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#9793]
### Description
The `*spacemacs*` home buffers contents does not get recentered when the frame is un/maximized by pressing `SPC T M`.

### Steps to reproduce
1. Start Spacemacs
2. Open the `SPC b h` `*spacemacs*` home buffer (if it isn't already open), as the only window.
3. `SPC T M` maximize the frame

### Observed behaviour
On both the latest master and develop branches.
The buffers contents only take up the left half of the frame.

![emacs_2017-10-28_09-37-31](https://user-images.githubusercontent.com/13420573/32132509-533c30a8-bbc5-11e7-830d-1091f999e229.png)

When the `SPC` which-key popup is called, then the buffer gets recentered.

### Expected behaviour
The buffer should be recentered automatically when `SPC T M` un/maximizing the frame.

### Notes
When the frame is maximized, the home buffer is centered, and the cursor is at the start of the top menu (press `m` to move it there). If one now unmaximizes the frame, then the home buffers contents extend outside the frames right edge.

![emacs_2017-10-28_09-37-41](https://user-images.githubusercontent.com/13420573/32132526-75b0ee58-bbc5-11e7-92b0-875a9ab81f3e.png)

### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. e2a45e0c) (the same thing happens on master (rev. 8e1af145))
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
 autohotkey emacs-lisp git haskell helm markdown neotree org spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by syl20bnr** [comment]
I cannot reproduce it on Emacs 25.1 and macOS High Sierra.

**Comment by duianto** [comment]
It seems to be Emacs 26.0.50 related, and not Windows specific, because the home buffer doesn't recenter automatically in Ubuntu 16.10 with Emacs 26.0.50 either (Ubuntu is running as a virtualbox client with windows 10 as host).

And when I just tested it in Windows 10 with Emacs 25.3.1, then the home buffer gets recentered automatically.

Since Emacs 26.0.50 is pre-release. Should this issue should be closed? And only be re-opened if the issue is still present, when the official version 26 is released?

Here are the Ubuntu Spacemacs info:
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 65d5e42)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp git markdown org version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS LIBSYSTEMD

**Comment by syl20bnr** [comment]
I changed the labels and we can keep it opened.

**Comment by kimonoki** [comment]
I got the same behaviour with  0.300.0@26.1 on High Sierra

**Comment by duianto** [comment]
I'm unable to reproduce this issue in Emacs 27.1.

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 780a96cfa)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey emacs-lisp git helm html lsp markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("c:/Users/username/org/"))
                 (rust :variables rust-backend 'lsp)
                 shell spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>
