### ISSUE TITLE
Neotree doesn't open files in the previous window on develop

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#9794]
#### Description
Opening a file from the Neotree window, with `l` (lowercase L) or `RET` on the develop branch, always opens it in window 1, but on the master branch the files open in the previously selected window as described in the documentation:
>By default a file is opened in the last active window.

develop branch docs: https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bfiletree/neotree#opening-files-with-neotree

master branch docs: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#opening-files-with-neotree

#### Steps to reproduce
1. Start Spacemacs
2. Split the window `SPC w s`
3. Open Neotree `SPC f t`
4. Select the second window `SPC 2`
5. Select the Neotree window `SPC 0`
6. Navigate to a file and open it with either `l` (lowercase L) or `RET`

#### Observed behaviour
The file opens in:
- window 1 on develop
- window 2 on master

#### Expected behaviour
The file should also open in window 2 on the develop branch.

#### Notes
Adding a numeric prefix, for example `2 l` (lowercase L) or `2 RET`, opens the file in window 2 on both master and develop.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. e2a45e0c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
 autohotkey emacs-lisp git haskell helm markdown neotree org spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by piotrpalek** [comment]
Relevant discussion on gitter: https://gitter.im/syl20bnr/spacemacs?at=59f67bfe4ff065ac1890571a

**Comment by Cmdv** [comment]
exactly the same issue here 😿

**Comment by syl20bnr** [comment]
Should be fixed in develop.

**Comment by Cmdv** [comment]
thanks a lot @syl20bnr 🎉 🙏 seems to work for `l` but not `enter` 🤔 
Just looked at the code and I can't spot what it might be as `'neotree-enter` looks right to me.

**Comment by jmcmichael** [comment]
Thank you! 🎉

**Comment by andresgutgon** [comment]
Just git pull from develop. Not working for me with `l`. Just with `Enter`

**Comment by ljupchokotev** [comment]
My PR fixes the enter binding, should have the same behaviour as "l".

@andresgutgon pull develop and try again.

**Comment by andresgutgon** [comment]
No, now it doesn't work with `RET` neither with `l` :/

I must be doing something wrong. What I was doing before and worked for me was:
1. Having an spacemacs open with 2 windows. And neotree open.
2. Go to NeoTree `SPACE + 0` 
3. Navigate to a file
4. Press `2 + l` and the file was open on window `2`
![image](https://user-images.githubusercontent.com/49499/40222508-ff3208d4-5a7f-11e8-90f6-006e22962371.png)


That's is not working for me now. If I want to open something from neotree in window 2 I have to go first to window 2, then go to neotree and then press `2 + l`.

If I go from a different window it opens the file in that window. Even if I press `2 + l`

![image](https://user-images.githubusercontent.com/49499/40222581-45497d34-5a80-11e8-9be2-517b57530ab4.png)

**Comment by ljupchokotev** [comment]
What you want is different than what this issue is about. Both `l` and `RET` open the selected file in the most recently used window. 

But I think what you want is a default Neotree behaviour and should be supported in spacemacs. The `'neotree-enter` and `'spacemacs/neotree-expand-or-open` functions will need to be _merged_ in order to support both behaviours.

**Comment by andresgutgon** [comment]
But now it's possible what I want? I thought it was possible before

**Comment by ljupchokotev** [comment]
Fixing this issue as per the documentation
> By default a file is opened in the last active window.
meant that what used to work, isn't working anymore. I will take a look at this and make a PR that supports both behaviours:
1. `RET` and `l` opens the file in the most recently used window.
2. `RET` and `l` should accept a window number to open the file in that window.

**Comment by Cmdv** [comment]
I have a little question which might be controversial!! how can you get the same behaviour as `RET` || `l` with a mouse click? (I know why am I using a mouse 😂)

**Comment by andresgutgon** [comment]
> should accept a window number

So this is not possible? super weird I've being living thinking this was working 😅

**Comment by ljupchokotev** [comment]
@andresgutgon I've created a PR for this #10693. 

The behaviour you are saying was working before when using `RET` but wasn't when using `l`. After my first PR, it stopped working for both keys. In this PR, it works with both `RET` and `l`.
