### ISSUE TITLE
Cache layer index

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#9801]
Spacemacs spends 10 - 15 secs indexing layers at startup. Would it be possible to cache this index to reduce startup time? This would probably require a command line switch to refresh the cache, e.g. if Spacemacs has been updated.

**Comment by JAremko** [comment]
@syl20bnr  May be we can start extra Emacs subprocess at the very beginning of the startup to validate the cache and build a new one if needed then Spacemacs can prompt the user to restart Spacemacs. :thinking:

**Comment by syl20bnr** [comment]
AHAH I thought about it long ago. Yeah this is very good proposition @beojan, at least all the "static" layers shipped with Spacemacs can be cached and loaded instantly. We don't need any switch as we can just ship the up to date cache file directly in the repo, can be stored in the `layers` directory.

**Comment by JAremko** [comment]
@syl20bnr We'll need to make sure that the users are aware of the caching - otherwise tinkering with spacemacs layers code may be confusing. Also it should be disableable for development.

**Comment by syl20bnr** [comment]
Spacemacs repository should be read only, I think this is mentioned in the README. We provide all the extension mechanisms to not have to fork the repository. So the caching should be exceptionally easy in this case... 🤞

**Comment by syl20bnr** [comment]
@JAremko for develop branch you are right:

> If you want to fork Spacemacs safely use the develop branch where you handle the update manually.

**Comment by JAremko** [comment]
@syl20bnr  Since Spacemacs downloads, unpacks and compiles .el files during the first run (install) - I think that the extra time needed for building cache (based on local .spacemacs file) will be negligible. Saving this time IMHO isn't a worthy trade off  for extra complexity in CI and potentially less efficient/more complex layer cache mechanism in Spacemacs. :thinking: 

Also it ill be nice to compile the cache file - to save extra .01 second :stuck_out_tongue_closed_eyes:

**Comment by gan-ainm** [comment]
I have the same issue when starting Spacemacs.  It takes about 30 seconds just for "Indexing layers..." Where would I normally find any file that cashes the indexing result?  Why does it take that long. On a different machine (older, less RAM, and less cores) indexing thakes about 2 seconds.
