### ISSUE TITLE
Starting/Updating develop Spacemacs eats memory

### ISSUE THREAD

**Issue by MD-ThorErik** [syl20bnr/spacemacs#9803]
#### Description :octocat:
When I start Spacemacs after changing branches to develop, it hangs while updating and consumes an abnormal amount of memory (at least 2 GB). I even deleted .spacemacs and .emacs.d.
Opening Spacemacs from the master branch functions as expected.

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
The statusline shows:
Downloading stable ELPA repository: spacelpa... (please wait)
uncompressing publicsuffix.txt.gz...done
And spacemacs hangs, consuming memory.

*Expected behaviour:* :heart: :smile:
Spacemacs starts and updates normally.

System Info 💻
    OS: Arch Linux
    Emacs: 25.3.1
    Spacemacs: (0.300.1@25.3.1)
    Spacemacs branch: develop (d15772fadcb86937522c49cb0819fd36ba5184b6)
    Graphic display: t
    Distribution: spacemacs
    Editing style: vim
    Completion: helm
    Layers: Even with the default layers in .spacemacs happens

**Edit: Content of Messages buffer after runnining emacs with "ulimit -v 1200000; exec emacs --debug-init"**

> Loading /home/me/.emacs.d/core/core-load-paths.el (source)...done
Loading /home/me/.emacs.d/.lock...done
Loading /home/me/.spacemacs...done
(Spacemacs) Calling dotfile init...
(Spacemacs) Calling dotfile user init...
Setting the font...
(Spacemacs) Setting font "Source Code Pro"...
(Spacemacs) Banner: /home/me/.emacs.d/core/banners/img/spacemacs.png
PNG warning: Interlace handling should be turned on when using png_read_image
Open the quickhelp.
Contacting host: github.com:443
uncompressing publicsuffix.txt.gz...done
Memory exhausted--use M-x save-some-buffers then exit and restart Emacs
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [514 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [98 times]
C-x M-x is undefined
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [294 times]
C-x C-g is undefined
Quit [3 times]
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [504 times]
error in process filter: apply: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
read-from-minibuffer: Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [504 times]
error in process filter: url-http-generic-filter: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
completing-read-default: Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [504 times]
error in process filter: url-http-generic-filter: Variable binding depth exceeds max-specpdl-size
error in process filter: Variable binding depth exceeds max-specpdl-size
completing-read-default: Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [294 times]
error in process filter: url-http-generic-filter: Transfer interrupted!
error in process filter: Transfer interrupted!
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [210 times]
completing-read-default: Variable binding depth exceeds max-specpdl-size
Quit
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [516 times]
Variable binding depth exceeds max-specpdl-size
error in process filter: Memory exhausted--use M-x save-some-buffers then exit and restart Emacs [358 times]

**Comment by syl20bnr** [comment]
Is it 100% reproducible ?
has `C-g` any effect ?

**Comment by SadSock** [comment]
I have the same problem。

System Info 💻
OS: Arch Linux
Emacs: 25.3.1
Spacemacs: (0.300.1@25.3.1)
Spacemacs branch: develop (d15772f)
Graphic display: t
Distribution: spacemacs
Editing style: emacs
Completion: helm
Layers: Even with the default layers in .spacemacs happens

**Comment by MD-ThorErik** [comment]
@syl20bnr I tried C-g and the "uncompressing publicsuffix.txt.gz...done" line clears, but the UI is still unresponsive (movement commands, space). The memory consumption persists.

I can still reproduce it in the last revision (0ea72bcde7e72712d858316ff38dbe00ff15ecd1)

**Comment by fishman** [comment]
100% percent reproduceable for me as well. Seems to be related to spacelpa

going to 65d5e42b8ea603abe25cbf3a832a204c15aeedd8h~1 fixes it for me

**Comment by fishman** [comment]
100% reproduceable for me as well anything before (65d5e42b8ea603abe25cbf3a832a204c15aeedd8) works

**Comment by cageyz** [comment]
the same problem on debian testing(emacs 25.2.2)

**Comment by MD-ThorErik** [comment]
@fishman There's something wrong with commit (65d5e42b8ea603abe25cbf3a832a204c15aeedd8).
Line 7 of .lock:
`(("melpa"    . "melpa.org/packages/")
^ that's not a quote...

**Comment by duianto** [comment]
@MD-ThorErik I think it's called a quasiquote, it quotes a list, but allows for evaluating elements following a `,` (comma).
Here's are some pages describing how it works:
http://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html#Backquote
https://emacs.stackexchange.com/questions/7481/how-to-evaluate-the-variables-before-adding-them-to-a-list
https://emacs.stackexchange.com/questions/7602/what-is-the-point-of-quote-with-single-argument-and-comma-quote-arg

**Comment by MD-ThorErik** [comment]
@duianto Yeah, I just found out. Sorry.

**Comment by duianto** [comment]
@MD-ThorErik There's no need to be sorry. You noticed something that looked wrong, and reported it it, that's good. This time it turned out to be intended behaviour, and you learned something new. 👍

**Comment by MarcusE1W** [comment]
@MD-ThorErik @duianto I have the same problem on Archlinux. The comments about quasiquotes are not clear to me. Is it really intended behavious to use more than 3G of memory for the update ?

**Comment by duianto** [comment]
@MarcusE1W The comment about quasiquotes was not related to this:
"Starting/Updating develop Spacemacs eats memory" issue, but about the now deleted comment above mine.

@MD-ThorErik try not to delete comments like these, others might be wondering the same thing, and be glad that someone else already had asked about it. And since the comment was deleted, that made my comment look like it was referring to the main issue instead of your comment. Don't worry about it this time, but it's something to think about in the future

@MarcusE1W The deleted comment was wondering if the backtick at the start of this line:
``  `(("melpa"    . "melpa.org/packages/")`` in the `.lock` file: 
https://github.com/syl20bnr/spacemacs/commit/65d5e42b8ea603abe25cbf3a832a204c15aeedd8#diff-bcb204d3641c12af14185102f2c7c70fR7
was incorrect, and if it should be written with a single quote instead.

The confusion is understandable if one hasn't seen it used like that before, because a single quote is used in front of the identical line:
`'(("melpa"    . "melpa.org/packages/")`, in both the commit message and in the file:
`core/info/release-notes/0.300.txt` here: https://github.com/syl20bnr/spacemacs/commit/65d5e42b8ea603abe25cbf3a832a204c15aeedd8#diff-eaef895cbc0d825185f45c57a2556563R38

The backtick before the start of the list in the `.lock` file, quotes the list just like a single quote would (which means that the following list is returned without it being evaluated first). The backtick makes it possible to selectively evaluate an element in the list before it's returned, by adding a `,` comma before it. In this case the comma is used here:
```
("spacelpa" . ,(concat configuration-layer--stable-elpa-directory
                            "spacelpa-"
                            configuration-layer--stable-elpa-version))))
```
the comma, replaces the following concatination with:
`"c:/Users/Username/AppData/Roaming/.emacs.d/.cache/stable-elpa/26.0.50/spacelpa-0.300"`
it means that the `configuration-layer--elpa-archives` variable will contain this:
```
(("melpa" . "melpa.org/packages/")
 ("org" . "orgmode.org/elpa/")
 ("gnu" . "elpa.gnu.org/packages/")
 ("spacelpa" . "c:/Users/Username/AppData/Roaming/.emacs.d/.cache/stable-elpa/26.0.50/spacelpa-0.300"))
```

**Comment by beojan** [comment]
I also had the same issue when I first updated Spacemacs after the Spacelpa stuff was added. The insane memory use was just the first time, while it downloaded and uncompressed Spacelpa. It *was* high enough that I could only get it to work by running from a VT with no GUI though (with 8 GB of RAM).

**Comment by MarcusE1W** [comment]
Thanks @duianto. Thas nicely clarifies the quasiquotes.

The memory problem is still there for me.

Archlinux (max. 3GM memory, ~120MB used before emacs starts)
Emacs 25.3.1

I have tried to switch to the master branch but have faced the same problem. That makes me think if maybe the new elpa repository is not to blame. As I understand it the new elpa  is only used in the development branch ?

So current my problem description is: I cannot install master nor develop branch due to  memory requirements > 3GB 

Any help would be appreciated.

**Comment by MD-ThorErik** [comment]
@MarcusE1W In my case only the develop branch causes this. Current master works.

**Comment by Alexander-Miller** [comment]
Same here. Just updated to the newest develop and needed to install spacelpa. By the time it was done nearly all 8GB of my ram were taken (with 1.7GB being used without emacs).

**Comment by MD-ThorErik** [comment]
@beojan I could update to latest develop by running emacs from the console too. Now I can't reproduce the bug even if I delete .emacs.d and clone again. I tought all of Spacemacs state was on emacs.d and .spacemacs but it can't be?

**Comment by AnaRobynn** [comment]
Same issue here. Unresponsive after updating develop. However, I'm patient by nature and after 5-10min it started responding again and normal behaviour was restored.

It's weird it takes that long + blocking every other process on Fedora.

**Comment by syl20bnr** [comment]
Can you all post the version of your Emacs and your OS ?

It might be a bug in Emacs, downloading a tarball of 30Mo and uncompress it to 60Mo should not take so much memory. 

I need to find a way to  reproduce it and test it in vanilla Emacs.

**Comment by Alexander-Miller** [comment]
Emacs 25.3 & Linux Antergos.

**Comment by elandx** [comment]
Same here. Emacs 25.3.1 Arch Linux

**Comment by AnaRobynn** [comment]
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a363f85d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm

**Comment by beojan** [comment]
25.3.1 on Arch, develop branch.

**Comment by elfmacs** [comment]
Emacs 25.3.1 & Archlinux & Develop branch

**Comment by kwohlfahrt** [comment]
Chiming in since I have a slightly older emacs version. Can reproduce even after removing `.spacemacs` and running `git clean` in my `.emacs.d`.

Did not happen on my laptop and I think it got the new repo update. Unsure about versions on that but will post them when I have access to it later today.

Emacs: 25.2.2
OS: Debian testing
Spacemacs: a363f85

**Comment by LeartS** [comment]
Same problem, with no swap I can't manage to start emacs because the RAM (8GB) fills up completely and the system hangs.

Ubuntu 17.10
Emacs 25.2.2
Spacemacs develop commit a363f85d33fd8d9d81380926753150d23adf8858

**Comment by andrew-christianson** [comment]
Same here

Fedora 26, kernel 4.13.11, emacs 25.3.1

Also, it seems the fix upthread should be:

(setq configuration-layer-elpa-archives
'(("melpa" . "melpa.org/packages/")
("org" . "orgmode.org/elpa/")
("gnu" . "elpa.gnu.org/packages/")))

The two dash version of that variable doesn’t seem to exist

**Comment by a-schaefers** [comment]
Same on Debian SID vps with 3G of ram. Eats the memory and crashes the vps. Stable works fine.

**Comment by syl20bnr** [comment]
People with the issue, can `M-x system-configuration-features` and tell me what is the output ? Do you have GNUTLS ?

Also can you also write again your OS distribution and version ?

On my system (MacOS) I cannot reproduce it and my output is:

```
system-configuration-features is a variable defined in ‘C source code’.
Its value is
"JPEG RSVG IMAGEMAGICK DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES"
```

I installed emacs with `homebrew` and the `emacs-plus` tap.

Also on develop I made the download of Spacelpa an opt-in so if you update you won't be bother anymore by the problematic download until we fix the problem.

**Comment by LeartS** [comment]
Hey, thanks for making it opt-in, I pulled latest develop and was able to start spacemacs without problems.

This was the output on my machine:
`"XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11"`

**Comment by DiMakss** [comment]
Manjaro there. Cant update packages, emacs --insecure helps for all packages except org-mode Contacting host orgmode.org:80 .... memory exhausted :(

**Comment by jjlee** [comment]
@syl20bnr I saw the problem and have identical `system-configuration-features` to LeartS.  I'm on Ubuntu 17.04 (or similar) and emacs 25.1.1 (the debian package is versioned 46.1ubuntu1 for some reason!).  I'm guessing anybody on Ubuntu 17.04 or 17.10 will see this bug.

`"XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11"`

I would guess you would be able to reproduce it in a vanilla ubuntu 17.04 or 17.10 docker image or VM.

I'm on spacemacs a363f85d from branch devel (actually on my branch off that specifically to fix this issue! -- which is here: https://github.com/syl20bnr/spacemacs/pull/9859)

**Comment by MarcusE1W** [comment]
Hi. I have intalled the develop branch the other day and this time wasn’t facing the  problems I had in Nov. Seems the issue might be solved.

_Archlinux, up,to date
Emacs 25.3.1_

**Comment by felipevolpone** [comment]
I'm facing the same problem. Spacemacs using 2.5 GB of RAM.

Spacemacs v.0.300.0 in develop branch
Fedora 26
Emacs 25.3.1

If it's needed I can post my `.spacemacs`.

**Comment by beojan** [comment]
There seems to be a new (slow) memory leak during use rather than at start
up.

**Comment by altschuler** [comment]
Same issue, fresh arch linux install, emacs 25.3.1, develop branch. It takes <1min for emacs to crash due to memory issues (on laptop with 8gb ram). The following config is taken using master branch, as develop crashes.

> "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES"

**Comment by jjlee** [comment]
spacemacs still reliably hard-locks my ubuntu machine on first startup when fetching the stable ELPA repository tarball.  My machine has to be rebooted, otherwise it becomes unresponsive within a few seconds (unless I'm running an OOM killer).  Applying my patch https://github.com/syl20bnr/spacemacs/pull/9859 still fixes it for me.

I'd like to fix this, but need guidance from a maintainer.  Does the approach in my PR https://github.com/syl20bnr/spacemacs/pull/9859 seem OK?  I'm reluctant to spend effort on it without some feedback, in case the approach is considered wrong.

**Comment by jjlee** [comment]
@syl20bnr seems at least 3 people still see this, maybe you can look at my PR #9859 and indicate if it's the right approach?
