### ISSUE TITLE
Linum-mode is slow

### ISSUE THREAD

**Issue by piotrwalkusz1** [syl20bnr/spacemacs#9808]
#### Description :octocat:
Linum-mode is slow when there are '~' on the screen. I mean if you have just a few lines of code, you have something like that:

int main() {
}
~
~
~
~
~

and after enabling linum-mode if I press j or k, emacs works slow and ' ~ ' are "redrawing".
When I have a long file (there is only one '~' in the last line), emacs works well.

#### Reproduction guide :beetle:
- Start Emacs
- Create and open new .txt in text-mode
- Add e.g. 5 lines of text
- Press SPC t n to enable linum-mode
- Press j or k to move between lines

*Observed behaviour:* :eyes: :broken_heart:
'~' are "redrawing" (refreshing) and emacs works slow

*Expected behaviour:* :heart: :smile:
Spacemacs should work as fast as normal emacs with linum-mode 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

.
EDIT:
If I disable vi-tilde-fringe (SPC T ~), emacs works well.

**Comment by hussein-aitlahcen** [comment]
Having the same problem, especially noticeable on virtual machines

**Comment by syl20bnr** [comment]
As a work around you can add `vi-tilde-fringe` in `dotspacemacs-excluded-packages`.

**Comment by taquangtrung** [comment]
> As a work around you can add `vi-tilde-fringe` in `dotspacemacs-excluded-packages`.

I removed `vi-tilde-fringe` and the cursor moves much faster and smoother.

Just wonder why such tildes (~) are added at the end of the display of each buffer?

**Comment by duianto** [comment]
According to the package description: https://github.com/syl20bnr/vi-tilde-fringe
it mimics the behavior of vi:
>Display tildes on empty lines in the Emacs fringe a la Vi.
