### ISSUE TITLE
Window number visually off by one

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#9809]
The window number appears visually off by one. It seems to be related to Treemacs and the Spacemacs home buffer.

#### Steps to reproduce
1. With the `treemacs` layer enabled
2. Open the Spacemacs home buffer
3. Open the `SPC f t` Treemacs window
Nothing changes the first time, the home buffer shows the correct window number: `1`
5. Close and open the Treemacs window
Every time the Treemacs window is closed and opened after the first, causes the home buffers window number to be shown as: `2` (it's only a visual bug)
7. Try selecting window `2` by pressing `SPC 2`
The minibuffer shows: No window numbered 2
9. Select window `1` by pressing `SPC 1`
The home buffers window gets selected and the window number changes to the correct number `1`.

The frame can also be split in to several windows, and if at least one of them shows the home buffer then the numbers can be displayed in a strange order. I've seen two windows show nr `2`.

This doesn't happen with the Neotree layer enabled. The home buffer seems to show the correct number `1`, every time the Neotree window is opened.

#### Expected behaviour
The window number should show the correct number.

#### Notes
@Alexander-Miller asked on the previous Treemacs issue I posted, if there was a way to get a notification when there's a Treemacs related issue, so here it is 😄

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0ea72bcd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
 autohotkey emacs-lisp git haskell helm markdown treemacs org spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by Alexander-Miller** [comment]
Probably related to [the changes in winum I've introduced](https://github.com/deb0ch/emacs-winum/pull/8#event-1315186851). Can't take care of it right now since I'm busy moving, but the fix should be simple - add `treemacs--window-number-ten` to winum's new function list.

**Comment by duianto** [comment]
This is just a visual bug, moving has higher priority, get settled first before even thinking about returning here 😄. We might even have solved it by then.

This commit: 
Fix neotree and treemacs window number allocation https://github.com/syl20bnr/spacemacs/commit/7717436c7eb4fdbda8b0ab70dfb137988fc26828
added `treemacs--window-number-ten` to the `winum-assign-functions` list in the treemacs layer:
```
(defun treemacs/pre-init-winum ()
  (spacemacs|use-package-add-hook winum
    :post-config
    (add-to-list 'winum-assign-functions #'treemacs--window-number-ten)))
```
https://github.com/syl20bnr/spacemacs/blob/0ea72bcde7e72712d858316ff38dbe00ff15ecd1/layers/%2Bfiletree/treemacs/packages.el#L71-L74

That solved the issue where both the Neotree and Treemacs was assigned window number `1`.

**Comment by duianto** [comment]
The issue might only be occurring with Treemacs, because Treemacs sets the window number to `10`, and Neotree sets it to `0`.

**Comment by duianto** [comment]
I'm unable to reproduce the issue, so it might have been fixed.
