### ISSUE TITLE
Window numbers shown as `<N>` when un-maximizing home buffer

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#9810]
The window numbers on non-home buffer split windows, show `<N>` when un-maximizing the home buffer. (This happens on both master and develop)

#### Steps to reproduce
1. Open the Spacemacs home buffer
2. Split the frame left and right and select the right window `SPC w V`
3. Change the right window to the `SPC b s` scratch buffer
4. Select the left window, that's showing the home buffer `SPC 1`
5. Maximize it `SPC w m`
6. Un-maximize (Restore the previous windows) `SPC w m`
Now the right window shows `<N>` as the window number. It's only a visual bug because `SPC 2` selects the right window and the window number updates to show the correctly number: `2`.

#### Expected behaviour
Un-maximizing the home buffer should show the window number instead of `<N>`.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0ea72bcd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spell-checking syntax-checking
                (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
                helm org treemacs git version-control games autohotkey emacs-lisp haskell markdown)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by duianto** [comment]
`<N>` is the current evil state, because if the cursor is in insert or visual state in the other non-home buffer windows, then the window number segment on the mode line shows: `<I>` and `<V>`. 

I've also seen the home buffer show `<M>` when I opened a new Frame `SPC F n`, but it didn't happen the 2-3 times I tried opening a new frame while I was writing this.

#### Possible cause
The evil-state seems to be shown, instead of the window number, because the `spaceline-spacemacs-theme` function, that's defined in: `.emacs.d/elpa/26.0/develop/spaceline-20171016.157/spaceline-config.el`
https://github.com/TheBB/spaceline/blob/251d92ef77ed4daa798e3300e5c671052870827e/spaceline-config.el#L64
seems to be calling: `           :fallback evil-state` when both the `workspace-number` and the `window-number` return `nil`.

That seems to only happen when the Spacemacs home buffer gets unmaximized. This can be seen by adding this message:
```
    (message "(bound-and-true-p winum-mode) %s, (winum-get-number) %s"
             (bound-and-true-p winum-mode) (winum-get-number))
```
after the last `let*` variable definition `         (str (when num (int-to-string num))))` in the:
`(spaceline-define-segment window-number` macro, that's defined in the file:
`.emacs.d/elpa/26.0/develop/spaceline-20171016.157/spaceline-segments.el`
https://github.com/TheBB/spaceline/blob/251d92ef77ed4daa798e3300e5c671052870827e/spaceline-segments.el#L469

Then the messages buffer shows that `(bound-and-true-p winum-mode)` returns `t`, when un/maximizing any buffer, including the home buffer.
But `(winum-get-number)` returns `nil` for some of the calls, when the home buffer is unmaximized. 

The window number gets returned when unmaximizing a non-home buffer.

#### Steps to reproduce:
1. With the log message (above), added to the `spaceline-define-segment window-number` macro in `spaceline-segments.el`, and Emacs has been restarted.
2. Split the Emacs frame into a home buffer in the left window and the scratch buffer in the right window.
3. Place the cursor is in the top left corner of the home buffer `S-M-,` (also denoted as `M-<`).
4. Pressing `h` shows:
```
(bound-and-true-p winum-mode) t, (winum-get-number) 2
evil-backward-char: Beginning of buffer
(bound-and-true-p winum-mode) t, (winum-get-number) 1
```
this makes it easier to see where the following messages started from.
5. `SPC w m` maximizes the home buffer, and pressing it again, unmaximizes it.
6. `SPC b m` switches to the messages buffer which shows:
```
...
(bound-and-true-p winum-mode) t, (winum-get-number) 2
evil-backward-char: Beginning of buffer
(bound-and-true-p winum-mode) t, (winum-get-number) 1 [4 times]
(bound-and-true-p winum-mode) t, (winum-get-number) nil
(bound-and-true-p winum-mode) t, (winum-get-number) 1 [2 times]
(bound-and-true-p winum-mode) t, (winum-get-number) nil
(bound-and-true-p winum-mode) t, (winum-get-number) 1
```
One of the times the window number returns `nil`, causes the right scratch window to show `<N>` instead of the window number.

Replicating the steps above, but with the `SPC b s` scratch buffer open in the left window instead of the home buffer, results in these messages:
```
...
(bound-and-true-p winum-mode) t, (winum-get-number) 2
evil-backward-char: Beginning of buffer
(bound-and-true-p winum-mode) t, (winum-get-number) 1
(bound-and-true-p winum-mode) t, (winum-get-number) 2
(bound-and-true-p winum-mode) t, (winum-get-number) 1 [2 times]
(bound-and-true-p winum-mode) t, (winum-get-number) 2
```
Since the window number didn't return `nil`, then the right window shows the correct number `2`.

I don't think it's an issue with the Spaceline package, because falling back to showing the evil-state, seems to be by design. 

This seems to be an issue with the Spacemacs home buffer, returning `nil` for the window number.

**Comment by achikin** [comment]
I experience something like this, but SPC 0-9 does not work for me https://github.com/syl20bnr/spacemacs/issues/9851
