### ISSUE TITLE
savehist-mode hogs the CPU

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#9811]
#### Description :octocat:
`savehist-mode` hogs the CPU

#### Reproduction guide :beetle:
This isn't easily reproducible bug, it usually happens on attempt to quit Emacs. I have discovered the issue by inspecting `kill-emacs-hook`, and then running functions on the list one-by-one. Running `(savehist-autosave)` with `savehist-mode` turned on (which I assume is on by default) - freezes Emacs.

This might be a symptom of other places where people reported Emacs hogging the CPU, see: #9559, #9409, #8498, etc.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0ea72bcd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv yaml emacs-lisp lua javascript
     (haskell :variables haskell-process-type 'stack-ghci)
     (html :packages
           (not pug-mode slim-mode))
     (markdown :packages
               (not mmm-mode)
               :variables markdown-live-preview-engine 'vmd)
     (shell-scripts :packages
                    (not fish-mode))
     (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
     syntax-checking
     (spell-checking :variables ispell-program-name "aspell")
     helm fasd osx restclient emoji search-engine imenu-list docker pdf-tools treemacs
     (shell :packages
            (not eshell-prompt-extras eshell-z multi-term xterm-color)
            :variables shell-default-shell 'eshell)
     git
     (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
     (github :packages
             (not magit-gh-pulls)
             :variables gist-view-gist t magithub-api-timeout 5 evil-want-C-u-scroll nil)
     ag-dired ag-general ag-synonyms ag-web ag-lang-tools ag-clojure
     (ag-org :variables org-enable-reveal-js-support t org-enable-bootstrap-support t org-enable-github-support t))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by agzam** [comment]
closing this due to the lack of activity. I have disabled savehist-mode and I'm not experiencing any problems since then. If someone desperately needs savehist-mode and still experiencing same problem can re-open it.

**Comment by zOrg1331** [comment]
The same happened to my setup. The root cause is also not clear.
