### ISSUE TITLE
Missing "PACKAGE DESC" for php-extras

### ISSUE THREAD

**Issue by nedludd** [syl20bnr/spacemacs#9815]
This is working my OCD badly. :-)

Get this error every time when starting emacs (version 0.200.x and 0.300.x, vanilla install, cleared cache, all that):

`An error occurred while installing php-extras (error: (wrong-type-argument package-desc nil))
`
It's part of the php layer. 

I think it's because you're pulling it directly from github.  

Can anything be done about this?

**Comment by CeleritasCelery** [comment]
Is `package-desc` on melpa?
