### ISSUE TITLE
spacelpa develop blew away custom settings

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#9816]
#### Description :octocat:
When upgrading to the latest develop with spacelpa, spacemacs blows away all of
my custom settings in emacs-custom-settings.

#### Reproduction guide :beetle:
- Be on an older develop ref with some custom settings
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
All custom settings are reset

*Expected behaviour:* :heart: :smile:
Custom settings aren't reset

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.90
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0ea72bcd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(octave swift nginx better-defaults spacemacs-layouts ivy
        (markdown :variables markdown-live-preview-engine 'vmd)
        (syntax-checking :variables syntax-checking-enable-tooltips t)
        (auto-completion :variables auto-completion-enable-sort-by-usage nil auto-completion-enable-snippets-in-popup nil spacemacs-default-company-backends
                         '(company-capf
                           (company-dabbrev-code company-keywords)
                           company-files company-dabbrev))
        git dash pdf-tools html
        (org :variables org-enable-github-support t org-enable-reveal-js-support t org-want-todo-bindings t)
        colors
        (osx :variables osx-command-as 'super)
        github ruby ruby-on-rails
        (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
        (spell-checking :variables spell-checking-enable-by-default nil)
        version-control rcirc tmux yaml docker restclient lua chrome
        (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
        emoji evil-little-word aj-elixir aj-emacs-lisp aj-javascript aj-typescript aj-ruby auto-correct cleverparens-lispy flow match-indent shift-number writing)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES LCMS2

**Comment by syl20bnr** [comment]
Pretty sure it is related to https://github.com/syl20bnr/spacemacs/commit/cc73871c :-(
