### ISSUE TITLE
Add gb as a generic keybinding to go back to previous mark. 

### ISSUE THREAD

**Issue by ageekymonk** [syl20bnr/spacemacs#9817]
Right now keybinding  "gd" is used for jump to definition. It would be good to have a complement to that "gb" to go back to previous location from where jump was made. 

Few languages already have this (nim, closure) Can we make gb a generic for all languages ?

**Comment by robbert-vdh** [comment]
What's the difference between `gb` and Vim's `C-o` keybinding?

**Comment by syl20bnr** [comment]
Seems that it is already in the conventions: https://git@github.com/syl20bnr/spacemacs/blob/develop/doc/CONVENTIONS.org#L130

PRs welcome ! :-)

**Comment by syl20bnr** [comment]
mmmh the conventions are at the major-mode level though.

If `C-o` does the same job then I guess we can sae `gb` for something else.

**Comment by sdwolf** [comment]
The `C-o` keybinding does not do the same thing. When you jump to definition, the current location is pushed unto a stack, and when you jump back the stack is poped. `C-o` does not pop the stack.
