### ISSUE TITLE
What is the best way to override any existing keybinding for major mode?

### ISSUE THREAD

**Issue by yejianye** [syl20bnr/spacemacs#9818]
#### Problem
I'm trying to override an existing keybinding for python mode. To be more specific, I'd like to replace `python-start-or-switch-repl` with `my-python-start-or-switch` for key `<leader>'`.

I put the following code in `dotspacemacs/user-config` and thought that was the recommended way to do it

```
(spacemacs/set-leader-keys-for-major-mode 'python-mode
  "'" 'my-python-start-or-switch)
```

But what I observed is that when emacs starts, this code gets executed. But when I open an python file for the first time, the leader keys mapping in `layers/+lang/python/python/packages.el` gets loaded and overrides my config.

So what's the best way to override an existing key binding for a major mode?

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup nil auto-completion-private-snippets-directory "~/toolbox/emacs/snippets")
 markdown python emacs-lisp javascript html ansible yaml org syntax-checking
 (spell-checking :variables spell-checking-enable-by-default nil)
 git better-defaults restclient)
```

**Comment by beta1440** [comment]
It may help to add a hook to `python-mode`. Try adding 
```emacs-lisp
(add-hook 'python-mode-hook
            (lambda()
              (spacemacs/set-leader-keys-for-major-mode 'python-mode
  "'" 'my-python-start-or-switch)))
``` 
to your `.spacemacs`.

**Comment by CeleritasCelery** [comment]
You only need to set the key binding once. 
```elisp 
(spacemacs|use-package-add-hook python 
  :post-config
  (spacemacs/set-leader-keys-for-major-mode 'python-mode
    "'" 'my-python-start-or-switch))
```

**Comment by yejianye** [comment]
Thanks @CeleritasCelery ! That works perfectly.

**Comment by chwrtlprmft** [comment]
This does not work for me. I also tried about any other variant i found on here and stackoverflow, but not one of these bindings work. It just says <M-s-right> is undefined etc.

```
  (spacemacs/set-leader-keys-for-major-mode 'python-mode "M-s-<right>" 'python-indent-shift-right)
  (spacemacs/set-leader-keys-for-major-mode 'python-mode "M-s-<left>" 'python-indent-shift-left)
  (spacemacs|use-package-add-hook python 
    :post-config
    (spacemacs/set-leader-keys-for-major-mode 'python-mode
      "M-s-<right>" 'python-indent-shift-right))
  (with-eval-after-load 'python
    '(define-key python-mode-map (kbd "M-s-<right>") 'python-indent-shift-right)
    '(define-key python-mode-map (kbd "M-s-<left>") 'python-indent-shift-left))
  (add-hook 'Python-mode-hook
		        (lambda () (local-set-key (kbd "M-s-<right>") 'python-indent-shift-right)))
  (add-hook 'Python-mode-hook
		        (lambda () (local-set-key (kbd "M-s-<left>") 'python-indent-shift-left)))
```
