### ISSUE TITLE
Haskell layer (slightly) breaks flycheck

### ISSUE THREAD

**Issue by rpglover64** [syl20bnr/spacemacs#982]
The Haskell layer adds a Haskell-specific flycheck-mode-hook, but it may not be loaded before flycheck is (e.g. a non-Haskell programming mode comes up first); this causes an error in the execution of flycheck-mode-hook s. In my copy, I made my local copy add a haskell-mode-hook instead, but this is a crude solution.

**Comment by rpglover64** [comment]
Potential duplicate of #594; potentially fixed by 2f27a31.
I don't run develop, so I'm not sure.

**Comment by d12frosted** [comment]
I am not experiencing this problem. @rpglover64 Could you verify that 2f27a31 fixed this issue, please? Also, #594 is closed.

**Comment by rpglover64** [comment]
AFAICT, it's fixed.

**Comment by d12frosted** [comment]
Cool, thanks for looking into it!
