### ISSUE TITLE
SPC-f-f (spacemacs/helm-find-files) gives error if invoked too quickly after startup

### ISSUE THREAD

**Issue by jackkamm** [syl20bnr/spacemacs#9826]
#### Description :octocat:

SPC-f-f (spacemacs/helm-find-files) gives an error message if invoked
immediately on startup (within 1 second).

This error can be fixed by adding `helm-current-directory`
to the autoloaded commands when starting up helm.
I can submit a PR for this but wanted to first check whether
this is the appropriate solution, and if anyone else
experiences this error.

#### Reproduction guide :beetle:
- Start Emacs
- Immediately (within 1 second of startup) type "SPC f f"

*Observed behaviour:* :eyes: :broken_heart:
helm-find-files doesn't start, and gives an error message
```
expand-file-name: Symbol’s function definition is void: helm-current-directory
```

*Expected behaviour:* :heart: :smile:
helm-find-files starts correctly

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a363f85d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm major-modes html csv yaml javascript markdown ranger bibtex latex octave
      (ess :variables ess-enable-smart-equals t)
      ipython-notebook python shell-scripts
      (shell :variables shell-default-shell 'multi-term)
      org emacs-lisp auto-completion git my-spacemacs-layer)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by tavurth** [comment]
I have the same issue, it's also reproducible if you run `SPC-p-f` Projectile find-file.

**Comment by tavurth** [comment]
I was able to fix this issue by putting:
```lisp
  ;; Fixes undefined functions at startup 
  (require 'helm)
  (require 'tramp)
```
In the `dotspacemacs/user-config` area.

**Comment by mopsfelder** [comment]
@syl20bnr, I see this was labeled as 'Fixed in develop', but using branch develop at 7c9f612c4f4a1eda7c8a11194ff2bce21ca53ca0, the issue is still present.

The workaround proposed at https://github.com/syl20bnr/spacemacs/issues/9826#issuecomment-344168808 fixed it.

Shall helm be required anywhere else in Spacemacs code?

**Comment by wxjeacen** [comment]
same issue, workaround with #9826(comment)

**Comment by gnzlbg** [comment]
same issue

**Comment by shishirsharma** [comment]
the workaround with https://github.com/syl20bnr/spacemacs/issues/9826#issuecomment-344168808   has increased start time significantly

**Comment by Miciah** [comment]
Can anyone who is still seeing the problem provide a backtrace?

**Comment by cglwn** [comment]
Still seeing this issue, here's a backtrace.

```
  (helm-current-directory)
  (expand-file-name (helm-current-directory))
  (cond ((and (eq major-mode (quote dired-mode)) default-input) (file-name-directory default-input)) ((and (not (string= default-input "")) default-input)) (t (expand-file-name (helm-current-directory))))
  (let* ((hist (and arg helm-ff-history (helm-find-files-history))) (default-input hist) (input (cond ((and (eq major-mode (quote dired-mode)) default-input) (file-name-directory default-input)) ((and (not (string= default-input "")) default-input)) (t (expand-file-name (helm-current-directory)))))) (set-text-properties 0 (length input) nil input) (helm-find-files-1 input))
  spacemacs/helm-find-files(nil)
  funcall-interactively(spacemacs/helm-find-files nil)
  call-interactively(spacemacs/helm-find-files nil nil)
  command-execute(spacemacs/helm-find-files)
```

**Comment by Miciah** [comment]
> Still seeing this issue, here's a backtrace.
> 
> ```
>   (helm-current-directory)
>   (expand-file-name (helm-current-directory))
>   (cond ((and (eq major-mode (quote dired-mode)) default-input) (file-name-directory default-input)) ((and (not (string= default-input "")) default-input)) (t (expand-file-name (helm-current-directory))))
>   (let* ((hist (and arg helm-ff-history (helm-find-files-history))) (default-input hist) (input (cond ((and (eq major-mode (quote dired-mode)) default-input) (file-name-directory default-input)) ((and (not (string= default-input "")) default-input)) (t (expand-file-name (helm-current-directory)))))) (set-text-properties 0 (length input) nil input) (helm-find-files-1 input))
>   spacemacs/helm-find-files(nil)
>   funcall-interactively(spacemacs/helm-find-files nil)
>   call-interactively(spacemacs/helm-find-files nil nil)
>   command-execute(spacemacs/helm-find-files)
> ```

@cglwn, what version of Spacemacs are you using? Since https://github.com/syl20bnr/spacemacs/commit/e24be2186adcbf1bafafd3ca2ea4e31d8919c760, <kbd>SPC f f</kbd> is bound to `lazy-helm/spacemacs/helm-find-files`, which wraps `spacemacs/helm-find-files`, but your backtrace shows that you have executed `spacemacs/helm-find-files` directly.
