### ISSUE TITLE
Error on deveop with package update rollback dir

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#9832]
#### Description :octocat:
Updating package yields error: 

```
mapcar: Opening directory: No such file or directory, /home/rob/.emacs.d/.cache/.rollback/27.0/develop
```
#### Reproduction guide :beetle:
- Start Emacs
- Have some packages to update
- proceed with update process `SPC feU`
- be on `develop` at [a363f8](https://github.com/syl20bnr/spacemacs/commits/a363f85)

*Observed behaviour:* :eyes: :broken_heart:
 
Error with rollback dir

*Expected behaviour:* :heart: :smile:

No error :tada:

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 35cd07c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(bibtex nginx twitter graphviz ivy asciidoc speed-reading swift plantuml
        (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-show-snippets-in-popup t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets")
        better-defaults emacs-lisp
        (git :variables git-magit-status-fullscreen t)
        github gnus version-control
        (markdown :variables markdown-live-preview-engine 'vmd)
        syntax-checking
        (latex :variables latex-enable-auto-fill t)
        (colors :variables colors-colorize-identifiers 'all colors-enable-nyan-cat-progress-bar t)
        docker
        (ansible :variables ansible-auto-encrypt-decrypt t)
        puppet evil-commentary
        (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
        fasd finance floobits xkcd autohotkey csv nlinum
        (c-c++ :variables c-c++-enable-clang-support t)
        (clojure :variables clojure-enable-fancify-symbols t)
        major-modes
        (go :variables gofmt-command "goimports" go-use-gometalinter nil go-use-gocheck-for-testing t go-use-test-args "-race -timeout 10s" go-tab-width 4)
        (haskell :variables haskell-enable-ghci-ng-support t haskell-enable-shm-support t haskell-enable-hindent-style "andrew-gibiansky")
        html java
        (javascript :variables javascript-disable-tern-port-files t)
        (python :variables python-enable-yapf-format-on-save t python-fill-column 80 python-auto-set-local-pyenv-version 'on-visit python-auto-set-local-pyvenv-virtualenv 'on-visit python-sort-imports-on-save t python-test-runner
                '(nose pytest))
        racket
        (ruby :variables ruby-version-manager `rvm)
        ruby-on-rails
        (rust :variables rust-enable-rustfmt-on-save t)
        (scala :variables scala-indent:use-javadoc-style t scala-enable-eldoc t scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-start-ensime t)
        shell-scripts
        (restclient :variables restclient-use-org t)
        themes-megapack tmux vim-empty-lines spotify pandoc vagrant
        (ibuffer :variables ibuffer-group-buffers-by 'projects)
        semantic deft
        (shell :variables shell-default-shell 'ansi-term shell-default-position 'bottom shell-default-height 30 shell-default-term-shell "/bin/zsh")
        erc chrome d emoji gtags prodigy evernote
        (org :variables org-enable-github-support t org-enable-reveal-js-support t org-enable-org-journal-support t org-enable-bootstrap-support t)
        search-engine evil-little-word yaml sql nim ipython-notebook lua scheme purescript sml common-lisp ranger dash spell-checking jabber cscope vinegar rcirc games react php vimscript geolocation idris
        (elm :variables elm-reactor-port "3000" elm-reactor-address "0.0.0.0")
        elixir
        (typography :variables typography-enable-typographic-editing nil)
        evil-cleverparens pdf-tools imenu-list slack systemd command-log
        (terraform :variables terraform-auto-format-on-save t)
        pass parinfer groovy
        (treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t treemacs-use-collapsed-directories 3))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
Confirmed
>mapcar: Opening directory: No such file or directory, c:/Users/Username/AppData/Roaming/.emacs.d/.cache/.rollback/26.0/develop

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a363f85d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spell-checking syntax-checking
                (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
                helm org treemacs git version-control autohotkey emacs-lisp haskell markdown)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by duianto** [comment]
This might have been solved on the latest develop branch:
- Spacemacs branch: develop (rev. 36c15b79)

the `... No such file ...` message didn't appear when I just updated the packages.

**Comment by syl20bnr** [comment]
@robbyoconnor do you confirm this is OK in latest develop branch ?

**Comment by robbyoconnor** [comment]
It does not appear to be the case for me...

**Comment by duianto** [comment]
The error message has returned. I'm on the latest develop branch:
- Spacemacs branch: develop (rev. b4b7d63e)


And it's not a pre-release (26, 27) issue, since it also happens in Emacs 25.3.1.
>mapcar: Opening directory: No such file or directory, c:/Users/Username/AppData/Roaming/.emacs.d/.cache/.rollback/25.3/develop

>mapcar: Opening directory: No such file or directory, c:/Users/Username/AppData/Roaming/.emacs.d/.cache/.rollback/26.0/develop

The message appears after the packages have been deleted. Here's the messages buffer entries after the [Update packages] link has been pressed.
```
(Spacemacs) --> refreshing package archive: melpa... [1/3]
Contacting host: melpa.org:443 [2 times]
Package refresh done
(Spacemacs) --> refreshing package archive: org... [2/3]
Contacting host: orgmode.org:80 [2 times]
Package refresh done
(Spacemacs) --> refreshing package archive: gnu... [3/3]
Contacting host: elpa.gnu.org:443
Package refresh done
Fetcher: file
Source: nil

(Spacemacs) --> Found 7 package(s) to update:

(Spacemacs) bind-key

(Spacemacs) dante

(Spacemacs) evil-unimpaired

(Spacemacs) flycheck

(Spacemacs) helm

(Spacemacs) use-package

(Spacemacs) which-key

Do you want to update 7 package(s) ? (y or n) y
(Spacemacs) --> performing backup of package(s) to update...

(Spacemacs) --> preparing update of package bind-key... [1/7]
Package ‘bind-key-20171204.1521’ deleted.
(Spacemacs) --> preparing update of package flycheck... [2/7]
Package ‘flycheck-20171126.1339’ deleted.
(Spacemacs) --> preparing update of package helm... [3/7]
Package ‘helm-20171204.406’ deleted.
(Spacemacs) --> preparing update of package dante... [4/7]
Package ‘dante-20171204.723’ deleted.
(Spacemacs) --> preparing update of package evil-unimpaired... [5/7]
Package ‘evil-unimpaired-20171203.234948’ deleted.
(Spacemacs) --> preparing update of package use-package... [6/7]
Package ‘use-package-20171204.1321’ deleted.
(Spacemacs) --> preparing update of package which-key... [7/7]
Package ‘which-key-20171114.700’ deleted.
mapcar: Opening directory: No such file or directory, c:/Users/Username/AppData/Roaming/.emacs.d/.cache/.rollback/25.3/develop

```

**Comment by cormacc** [comment]
I'm seeing the same problem on emacs 25.3 on arch linux. When I look in ~/.emacs.d/.cache/.rollback, I see a series of subdirs named according to the pattern
developYY-MM-DD_HH.MM.SS
, where the date/time tokens represent the date/time at which the upgrade was initiated

So looks like this call to mapcar has neglected to include the date time tokens when constructing the rollback dir name?

**Comment by MarcusE1W** [comment]
Same problem here.  Archlinux, Emacs 23.5.1 and develop branch.
Does this error mean that the update failed or is that only a rollback problem ?

**Comment by jackkamm** [comment]
Same problem, and I am also on Archlinux, Emacs 23.5.1, develop. In particular when trying to rollback I get:
> No rollback slot available.

Despite rollbacks working previously and my `.cache/.rollback/` being nonempty.

This caused a problem for me today when a helm update broke spacemacs and I was unable to rollback helm. Luckily I was able to fix the helm problem fairly quickly (see PR https://github.com/syl20bnr/spacemacs/pull/10196). But I guess I won't be updating packages anymore until this is fixed...

**Comment by duianto** [comment]
Yeah this issue should be high priority.
