### ISSUE TITLE
feature request for editing short shell commands.

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#9833]
If you are in a terminal and edit a complicated command you can press `C-x C-e` to bring up `EDITOR`, I have set set `EDITOR` to `emacsclient -a "" -nw` which brings up a new emacs client frame with an empty buffer pointing to a temporary file.
Then I can edit my command as I please in spacemacs and when I save the buffer and kill the frame the command gets executed.
As things are currently this requires a lot of keystrokes: `SPC f s` and `SPC q f`. I can get around this by adding this to my `.spacemacs`:

```elisp
(defun spacemacs/save-buffer-kill-frame ()
  (interactive)
  (save-buffer)
  (delete-frame))
(spacemacs/set-leader-keys "qF" 'spacemacs/save-buffer-kill-frame)
```

There are two more issues which I don't know how to deal with: 1) The buffer that comes up is in `Fundamental` mode, it would be great if it could automatically be in bash mode and 2) the temporary files get added to the recent files.

I will be happy to make a pull request if this is a wanted feature and someone helps me to solve the two issues.

There is also a theming issue if a graphical and terminal frames are opened at the same time, the colors in the terminal frame get messed up but I do not care too much about that.

**Comment by CeleritasCelery** [comment]
As part of your `$EDITOR` variable you could add the `--eval` Flag followed by a sexp to change the major-mode. 

As an aside, have you tried using `ansi-term`?

**Comment by braham-snyder** [comment]
regarding 2), there's a vim (and `evil`) keybinding for that:

```
Z Z runs the command evil-save-modified-and-close (found in
evil-normal-state-map), which is an interactive compiled Lisp function in
`evil-commands.el'.
```
