### ISSUE TITLE
helm-show-kill-ring doesn't replace previous yank

### ISSUE THREAD

**Issue by dbp** [syl20bnr/spacemacs#9836]
#### Description :octocat:
helm-show-kill-ring doesn't replace previous yank

#### Reproduction guide :beetle:
- Start Emacs
- Kill some stuff
- Yank (C-y)
- Run helm-show-ring (SPC r y)
- Pick an alternate

*Observed behaviour:* :eyes: :broken_heart:
The alternate is yanked immediately after the immediately preceding yank, rather
than replacing it (which is the behavior of helm-show-ring in stock emacs).

*Expected behaviour:* :heart: :smile:
The alternate should replace the previous yank.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a363f85d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp neotree)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 LCMS2

**Comment by CeleritasCelery** [comment]
That seems less like a bug and more like a design choice. One less step.

**Comment by dbp** [comment]
Well the documentation of helm-show-kill-ring says it will replace previous yank, and on stock emacs it does, so I’m not sure how this isn’t a spacemacs-related bug...

**Comment by CeleritasCelery** [comment]
Are you using evil?

**Comment by dbp** [comment]
@CeleritasCelery nope!

**Comment by syl20bnr** [comment]
We have a terminology conflict here. in Spacemacs the purpose of `SPC r y` is to show the yank (in the Vim term) registers, so this is what you copied. 

So it is bug in `holy-mode` but not in `evil-mode`.... It amaze me that in Vim and Emacs `yank` means the exact opposite of the other.

So I would put the functionality described here behind `SPC r p` instead. Seems like a cool feature BTW.

**Comment by braineo** [comment]
Right. Disabled evil mode seems to fixed the problem. So evil mode is loaded whether you are using it or not?

**Comment by Miciah** [comment]
Yeah, Spacemacs implements its holy and hybrid modes as Evil mode states, so Evil mode is always loaded. 

The issue here is caused by some advice for `split-window-internal` that Evil mode adds to save the mark when the window is split.  Starting a Helm session splits the window, which causes this advice to run.  Use the following to disable the advice:
```emacs-lisp
(ad-deactivate #'split-window-internal)
```
Does that resolve the issue for you?

Alternatively, Helm can be patched to save and restore the mark:
```diff
diff --git a/helm-ring.el b/helm-ring.el
index f744536b..b9e0b498 100644
--- a/helm-ring.el
+++ b/helm-ring.el
@@ -81,6 +81,7 @@ will not have anymore separators between candidates."
   (helm-build-sync-source "Kill Ring"
     :init (lambda ()
             (helm-attrset 'last-command last-command)
+            (helm-attrset 'mark (mark t))
             (helm-attrset 'multiline helm-kill-ring-max-offset))
     :candidates #'helm-kill-ring-candidates
     :filtered-candidate-transformer #'helm-kill-ring-transformer
@@ -195,6 +196,7 @@ replace with STR as yanked string."
                    ;; When yanking in a helm minibuffer we need a small
                    ;; delay to detect the mark in previous minibuffer. [1]
                    (run-with-timer 0.01 nil yank-fn))
+               (set-marker (mark-marker) (helm-attr 'mark helm-source-kill-ring))
                ;; from `yank-pop'
                (let ((inhibit-read-only t)
                      (before (< (point) (mark t))))
```
However, I think the issue probably should be fixed in Evil.  I'm not sure why it needs to set the mark when the window is split or whether that behavior is unintentional.

**Comment by braineo** [comment]
hi Miciah

Thanks for looking at this issue.

`(ad-deactivate #'split-window-internal)` works for me :)

**Comment by dbp** [comment]
Just a note, for anyone finding this issue later (though I doubt you would), the underlying problem seems to have been fixed, so the workaround `(ad-deactivate #'split-window-internal)` is no longer necessary (and indeed, will error).
