### ISSUE TITLE
Let's bundle smartparens settings with smartparens

### ISSUE THREAD

**Issue by Fuco1** [syl20bnr/spacemacs#9838]
I've noticed there is a bunch of customization in spacemacs configuring smartparens for various languages.  We already try very hard to provide good defaults for popular languages and it makes sense to me to have this in one place, especially for things which aren't spacemacs related.

For example, the rust configuration for lifetime contexts that is in spacemacs has been included in smartparens as well as some additional features which are now unfortunately wiped out by spacemacs overriding the pair (it is to be noted here that smartparens configuration "DSL" is quite stupid in this regard and I'm working on something much better and more flexible for 3rd party extensions).

I would like it very much if you could have some "policy" or whatever to redirect users requesting these changes directly to smartparens so that all users, not just those of spacemacs, can benefit; and also to prevent bit-rot of config code here which is often superseded by core SP enhancements.

**Comment by syl20bnr** [comment]
I'm all for it. If you are OK with using Spacemacs to explore the added smartparens configuration you can `SPC h SPC smartparens`  or `M-m h SPC smartparens` to have a list of all the location where we add smartparens configuration. Select one candidate and press RET to go the configuration location.

**Comment by syl20bnr** [comment]
This is what we have right now, the owner layer is where we configure smartparens and the `post-init` are where we extend its configuration in other layers.

![image](https://user-images.githubusercontent.com/1243537/32701415-d589a2f0-c7a2-11e7-8734-a8e6f5e4c64f.png)

**Comment by Fuco1** [comment]
Thanks for the listing!

I'll try to go through those and see what we can merge upstream.  Recently (this month) I've added markdown setup so that would probably be the first I'd look at.  We also have elixir and ruby but those got a bit neglected as I stopped using those languages.
