### ISSUE TITLE
A way to keep dotspacemacs current.  

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#984]
I have noticed that with all the new features, that my `.spacemacs` file needs a refresh from time to time to make sure that I get my preferred settings for new features. 

Is it possible to create a function that will scan the dotspacemacs file and prompt questions for features that aren't specified?  I am thinking of a workflow like: 

- Update spacemacs
- Restart
- Run a function like `spacemacs/upgrade-preferences`, which prompt for personal preference of unset features, using the doc section of the variable. The response of these will get saved to a section of the `.spacemacs` file so that these no preferences will take hold on the next restart.  

Is something like this possible?

**Comment by tuhdo** [comment]
I've been thinking about this as well. In [this commit](https://github.com/tuhdo/spacemacs/commit/4fa84665c5538426fc01612f6162c509ea3c8f40), I added a template variable in `.spacemacs` template file, and the variable is supposed to be replaced with an actual value. We can do it similarly by adding template variables in places that need to be saved, check if a current `.spacemacs` of a user is available and if so, collect the actual values according to the places defined in the template files. Then, the actual values replaces the template variables in the new file.

**Comment by aminb** [comment]
:+1: +1 I think this would be nice.

**Comment by ralesi** [comment]
Current diff template option seems to work OK for this.
