### ISSUE TITLE
Error of exec-path-from-shell when start up

### ISSUE THREAD

**Issue by lightingghost** [syl20bnr/spacemacs#9840]
The error message is 

`Error (use-package): exec-path-from-shell :init: Searching for program: No such file or directory, /usr/local/bin/fish`

But I am not using a fish shell.

**Comment by yenda** [comment]
I had this package in my exclusions and now I get `Symbol's function definition is void: exec-path-from-shell-copy-env`. If I remove it when spacemacs starts it kills my desktop environment and I get a black screen with a bleeping white undescore

**Comment by Stebalien** [comment]
@yenda I believe your issue is unrelated. Also, that issue (not being able to disable that package) is fixed in develop.

@lightingghost what are the outputs of:

```sh
> which fish
> whereis fish
> cat /etc/shells
```

**Comment by lightingghost** [comment]
@Stebalien Thanks for your help. I found a line in /etc/shells that related to fish shell. It works when I remove that line.
