### ISSUE TITLE
Issue creating a new Layout

### ISSUE THREAD

**Issue by parker789** [syl20bnr/spacemacs#9841]
#### Description :octocat:
I'm unable to create a new layout using SPC l <0-9>

#### Reproduction guide :beetle:
- Start Emacs
- Try to create a second layout using SPC l 2
- Answer "y" to create a perspecitive in this position
- Enter a name for new layout within persp-frame-switch

*Observed behaviour:* :eyes: :broken_heart:
Perspective in this position doesn't exist.
Do you like to create one? (y or n)

*Expected behaviour:* :heart: :smile:
My second layout is created

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(typescript markdown html nginx helm auto-completion emacs-lisp javascript git org gtags)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by parker789** [comment]
I was assisted by a nice person on the Gitter room, and have been instructed to create a new layout using `SPC l l` - which works like a charm. Is there any reason why my initial workflow wasn't working?

**Comment by syl20bnr** [comment]
Your initial workflow should work, this is what I use and it works fine here.

**Comment by parker789** [comment]
hmm. any way i can debug into why things could be failing?

**Comment by duianto** [comment]
@parker789 The system info, shows that your on the previous version 0.200.9, the latest version is: 0.200.10.
There might be an update button (a green up arrow, inside square brackets), on the right side of the mode line: https://github.com/syl20bnr/spacemacs#automatic-update-on-master-branch

**Comment by parker789** [comment]
@duianto You're a hero. Trying this would've been my first line of defense in attempting to resolve the issue myself, but the mode line did *not* display an available update.. I'm not sure if that's an issue in itself. I manually fetched the latest version and updated my packages and now my original layout creation workflow is working fine.

I'll leave this open just to discuss the mode line possible issue, but if you would like to close the ticket now, go ahead.

**Comment by duianto** [comment]
I just stumbled over this issue page a day or two ago and wondered if it could be closed.
No more wondering 😄
