### ISSUE TITLE
ansi-term, vim editing style, ctrl-w and M-backspace not deleting word

### ISSUE THREAD

**Issue by liujoey** [syl20bnr/spacemacs#9844]
#### Description :octocat:
ansi-term, vim-insert mode, ctrl-w and M-backspace not kill word, this is related to #9564

#### Reproduction guide :beetle:
- Start Emacs
- SPC ', to start ansi-term
- type ls, then his ctrl-w or M-backspace to delete the word 'ls'
- hit ENTER key

*Observed behaviour:* :eyes: :broken_heart:
the 'ls' command is still send to the shell

*Expected behaviour:* :heart: :smile:
the 'ls' command should be deleted

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0ea72bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(better-defaults osx
                 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip 'manual)
                 emacs-lisp imenu-list colors
                 (mu4e :variables mu4e-enable-mode-line t mu4e-enable-notifications t)
                 (version-control :variables version-control-diff-tool 'diff-hl)
                 (shell :variables shell-default-shell 'ansi-term)
                 markdown csv gtags yaml git html
                 (go :variables go-use-gometalinter t)
                 (java :variables java-backend 'ensime)
                 (scala :variables scala-use-unicode-arrows t)
                 javascript typescript python django evil-commentary
                 (org :variables org-want-todo-bindings t)
                 syntax-checking restclient docker vinegar evil-snipe)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by liujoey** [comment]
Using vim editing style in an ansi-term buffer, when describe the key ctrl-w, we got:

```
C-w runs the command evil-delete-backward-word (found in evil-insert-state-map),
which is an interactive compiled Lisp function in
‘~/Developer/dotfiles/emacs/emacs.d/elpa/25.3/develop/evil-20171028.503/evil-commands.el’.

It is bound to C-w.

(evil-delete-backward-word)

Delete previous word.
```

When use hybrid editing style, the same key was bind to:

```
C-w runs the command term-send-raw (found in term-raw-map), which is an
interactive compiled Lisp function in ‘term.el’.

It is bound to C-@..C-b, C-d..C-w, C-y..C-z, C-\..DEL, C-c C-x, C-c C-c, C-x
C-x, C-x C-c, SPC..~, ..\377.

(term-send-raw)

Send the last character typed through the terminal-emulator
without any interpretation.
```

This is why in vim insert mode, C-w can even delete the shell prompt.

**Comment by JustAPerson** [comment]
I still run into this frequently. Does anyone know a workaround (besides using eshell or the inferior-shell)?
