### ISSUE TITLE
"SPC sf" open the wrong file path

### ISSUE THREAD

**Issue by bebound** [syl20bnr/spacemacs#9845]
#### Description :octocat:
"SPC sf" open the wrong file path

#### Reproduction guide :beetle:
- Start Emacs
- Edit file `~/Dev/octopus/online_data/urls.py`
- <SPC sf> search in parent directory `~/Dev/octopus/`
- search for sth, try to open `views.py`

*Observed behaviour:* :eyes: :broken_heart:
Press RET and spacemacs opens an empty file named `views.py`

*Expected behaviour:* :heart: :smile:
It tries to open `~/Dev/octopus/online_data/packet/views.py`, but the right path should be `~/Dev/octopus/packet/views.py`

Search in the current directory works as expected.

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(html javascript ivy auto-completion better-defaults emacs-lisp git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control python clojure)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by CeleritasCelery** [comment]
Can you reproduce with [emacs-helm.sh](https://github.com/emacs-helm/helm/blob/master/emacs-helm.sh)?

**Comment by bebound** [comment]
@CeleritasCelery I think it's related to `ivy`, everything works fine after change completion to `helm`.

**Comment by bebound** [comment]
@CeleritasCelery  @syl20bnr 
I made a record:  https://asciinema.org/a/phHs8zLdN366Zs2n4l6TUsxSb
It should open file `~/testbug/folder2/file2.txt` rather than `~/testbug/folder1/folder2/file2.txt`

**Comment by pbrn46** [comment]
I can confirm this on both Ubuntu 16.04 w/ 0.200.10/master0@25.2.2 and Windows 10 Pro 0.200.10/master@25.3.1.

Tested with ag and pt. I'm also using Ivy and haven't tested with just Helm. It seems to also affect project search (SPC s p), but I guess it uses the same underlying function.

It seems it uses the current buffer's visiting file as the working directory, and joins the relative path of the selected search file we want to visit, rather than using the pre-assigned "Start from directory" as the working directory.

**Comment by pbrn46** [comment]
After some searching, this appears to be a duplicate of #9552 and solved by PR #9553. Cherry-picking 84751cbc53514b68b091170b37125a955a7f4fd1 from develop solved this for me.

**Comment by bebound** [comment]
@pbrn46  Thank you.

**Comment by billwanjohi** [comment]
> Cherry-picking 84751cb from develop solved this for me.

FWIW, cherry-picking this same commit onto release 0.200.13 did _not_ work for me, but switching to `develop` branch did. I don't know how to vote for a hotfix, but getting project search fixed for what I presume to be the vast majority of people using the stable releases seems like it should be a higher priority.

**Comment by jakemcarthur** [comment]
This is a very annoying bug. It would be great if this could be released in the short term.
