### ISSUE TITLE
Move . and .. in ido-vertical-mode at the bottom

### ISSUE THREAD

**Issue by chshersh** [syl20bnr/spacemacs#9848]
When I open `ido` with `C-x f` and try to walk through folders I see that `.` and `..` are shown as first options. This is not really convenient :( It stops from just pressing `TAB TAB TAB TAB` to enter first folder or first file on each level. This occurs very often in Haskell programming because module with name `A.B.C.hs` should have path `A/B/C.hs`. But even in not Haskell programming I can't imagine the case where `.` and `..` are reasonable defaults. I think it's better to move `.` and `..` at the bottom of the vertical list with options at least

![screenshot from 2017-11-09 18-08-49](https://user-images.githubusercontent.com/4276606/32612396-411f6698-c579-11e7-923a-81be848a5377.png)

Moreover it's very easy to type `.` and `..` if you really want these folders. But I can't imagine case why you want this. `. . ENTER` is just `C h` and why you need to enter `.`?..

```bash
$ emacs --version
GNU Emacs 24.5.1
$ lsb_release -a
Description:	Ubuntu 16.04.3 LTS
```

Spacemacs version: `0.200.10`

**Comment by CeleritasCelery** [comment]
Ido is not officially supported by Spacemacs. If you use helm (which is the Spacemacs default) you can use this layer to do just that
https://github.com/TheBB/spacemacs-layers/tree/master/layers/no-dots

**Comment by ChShersh** [comment]
@CeleritasCelery Thanks a lot! This does the trick for me. Probably information about this layer should be added into official documentation somewhere... Also, as a Spacemacs beginner, it wasn't obvious for me, what is `helm` responsible for and what is `ido` responsible for.

**Comment by syl20bnr** [comment]
Now we have helm properly configured in its own layer with layer variables, we can add a layer variable to hide the dots and dotdots from Helm buffers.
