### ISSUE TITLE
Possible conflict between org-babel and flycheck ?

### ISSUE THREAD

**Issue by Adrianzo** [syl20bnr/spacemacs#9849]
I don't know how, but it's working now.

```
  (require 'ob-shell)
  (require 'ob-R)
  (require 'ob-python)
  (require 'ob-julia)
  (org-babel-do-load-languages
   'org-babel-load-languages
   '(
     (shell  . t)
     (R      . t)
     (python . t)
     (julia  . t)
    ))
```

**Comment by Adrianzo** [comment]
Forgot to tell two main things.
(1) I'm using base distribution, not full. (With evil & ivy).
(2) ob-shell and ob-julia aren't installed (Looking into it right now)

**Comment by Adrianzo** [comment]
I don't know how, but it's working now. The only difference I've is that I disabled spell checking...

**Comment by CeleritasCelery** [comment]
You can close it
