### ISSUE TITLE
vim mode: f does not function correctly

### ISSUE THREAD

**Issue by svalaskevicius** [syl20bnr/spacemacs#985]
keys
 `F` (move backwards until char including it),
 `T`, (move backwards until char excluding it),
 `t` (move forwards until char excluding it)

work ok.. however `f` doesn't - it should be (move forwards until char including it) but is ineffective both as top level command and as scoping action for the previously typed command (e.g. `c`)

**Comment by syl20bnr** [comment]
Thank you for the report.
Indeed this is a major regression. I'll fix it tomorrow.

**Comment by syl20bnr** [comment]
Fixed in version 2.18 of `evil-escape`. Will be available on MELPA in a few hours.

**Comment by svalaskevicius** [comment]
thanks! its working ok now :)
