### ISSUE TITLE
<N> instead of window numbers, SPC 0-9 does not work correctly

### ISSUE THREAD

**Issue by achikin** [syl20bnr/spacemacs#9851]
#### Description :octocat:
`<N>` is shown instead of window numbers
SPC 1-9 does not switch window 

#### Reproduction guide :beetle:
- Start Emacs
- Look at the window number

*Observed behaviour:* :eyes: :broken_heart:
`<N>` instead of window numbers
SPC 1-9 does not switch windows
*Expected behaviour:* :heart: :smile:
Window numbers are valid digits, SPC 1-9 changes focus to desired window
#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git markdown html go java sql
      (elm :variables elm-format-command "elm-format-0.18")
      javascript clojure evil-cleverparens themes-megapack)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by achikin** [comment]
Btw, I've seen some winum error after updating to the latest spacemacs, but I'm not sure what was it.

**Comment by Alex-Keyes** [comment]
I am having the same error! Glad it's not just me...

**Comment by syl20bnr** [comment]
I think you need to update your packages.

On the home buffer `SPC b h`, press TAB to highlight `[ Update Packages ]` and hit RET.

**Comment by achikin** [comment]
Error (use-package): winum :config: Symbol’s value as variable is void: winum-assign-functions

**Comment by achikin** [comment]
@syl20bnr thank you very much for your help. I had 93(!) outdated packages. That was my bad - I've never paid attention to the menu on the home page and did an update using git pull. However, could you please emphasize somehow that one needs to update package manually after spacemacs update?

**Comment by duianto** [comment]
@achikin On the `SPC b h` Spacemacs home buffer, the bottom of the `[Release Notes]` "ascii frame" says:
>Update your dotfile (SPC f e D) and packages after every update

And the `Update Spacemacs repository` section of the documentation state that:
>There are several methods of updating the core files and layer information for Spacemacs. It is recommended to update the packages first; see the next section.

source: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#update-spacemacs-repository

I don't know if the packages should be updated before or after updating Spacemacs, since they state opposite orders.

**Comment by Alex-Keyes** [comment]
@syl20bnr @achikin I can confirm that updating my packages fixed this problem.
