### ISSUE TITLE
spacemacs//helm-do-ag command completes on filenames rather than file content

### ISSUE THREAD

**Issue by randomizedthinking** [syl20bnr/spacemacs#9853]
#### Description :octocat:
The spacemacs//helm-do-ag command completes on filenames rather than file content.

#### Reproduction guide :beetle:
- Start Emacs at a given directory
- Key in 'M-m s a f'
- The 'HELM FILE COMPLETE' command window appears
- It is to complete filename rather than file content

*Observed behaviour:* :eyes: :broken_heart:
The 'HELM FILE COMPLETE' command window appears. It is to complete filename
rather than file content

*Expected behaviour:* :heart: :smile:
Expect the '*helm ag*' command window appears, and it is to search based on file
contents.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python clojure sql helm emacs-lisp git markdown org spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by syl20bnr** [comment]
`SPC s a f` first ask for a directory where to look the file.

more info here: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#searching-in-files-in-an-arbitrary-directory
