### ISSUE TITLE
The Real Administrator

### ISSUE THREAD

**Issue by jackpot1136** [syl20bnr/spacemacs#9857]
If you are posting about a *bug* please close this issue and open a new one
using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs. If the
bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template)
You can delete this message to start typing.

And I would like to file harrasment and a violation of the code of conduct

**Comment by syl20bnr** [comment]
Please contact me at the email address on my profile.
