### ISSUE TITLE
[RFE] Per-layer :config/:init functions

### ISSUE THREAD

**Issue by Stebalien** [syl20bnr/spacemacs#9860]
So, I've been using the per-layer `:variables` key to group settings applicable to a layer to that layer. However, I'd like to be able to group the rest of my layer configuration with the layer as well instead of splitting it between the user-init and user-config sections. That is,

```elisp
(layer-name
  :disable t ; Allows one to easily turn off a layer completely without blowing away the config.
  :variables
       layer-v1 "value1"
       layer-v2 "value2"
  :init
    ;; Stuff...
  :config ; clearly grouped with the relevant layer.
    (add-hook 'stuff (lambda () nil))
````

This also opens the door for reloading individual layers and their configuration without reloading the rest of the user's config. It also makes it easier to share settings with other users (for cases where custom layers are overkill).

The primary drawback, from my perspective, is that it clutters up the layer list. However, IMO, that should be dealt with by folding (the clutter has to go somewhere...).

Thoughts? An alternative approach would be to allow users to define, e.g., `dotspacemacs/{init,configure}-$layer` functions and automatically call those but I worry that that's a bit too magical (the configure/init function could be defined anywhere or not a tall).

**Comment by CeleritasCelery** [comment]
We already have [use-package-hooks](https://github.com/syl20bnr/spacemacs/blob/master/doc/LAYERS.org#use-package-hooks) which add much finer control and extensibility then "layer hooks" would. Though I can see the appeal of having all your layer config grouped in one place.

 Most of time all you need is `user-config`. You could wrap all relevant config in `configuration-layer/layer-usedp` so it is clear what layer it belongs to.

**Comment by Stebalien** [comment]
Interesting idea. Usually, I just wrap my config in `(with-eval-after-load ...)`. But yeah, the main reason I'd like this is to keep everything in one place (although, with `use-package-hooks`, I could make my own macro and configure everything in `user-init`).
