### ISSUE TITLE
Symbol’s function definition is void: defunð

### ISSUE THREAD

**Issue by phoe** [syl20bnr/spacemacs#9864]
#### Description :octocat:
"Symbol’s function definition is void: defunð" on slime launch

#### Reproduction guide :beetle:
- Start Emacs
- M-x slime
- See the *Messages* buffer for error description

*Observed behaviour:* :eyes: :broken_heart:
Slime does not launch, instead the *Messages* buffer contains the following:
```
Eager macro-expansion failure: (wrong-type-argument listp t°-)
helm-M-x: Symbol’s function definition is void: defunð
```

*Expected behaviour:* :heart: :smile:
Slime launches

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. 36c15b79)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript html sql markdown helm emacs-lisp common-lisp erlang git org
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by CeleritasCelery** [comment]
Can you reproduce with stock Emacs and slime?

**Comment by bmag** [comment]
We need a backtrace to figure out where the defunð typo is. Read the sections "Enable debug" and "Get the backtrace" from [this page](https://github.com/syl20bnr/spacemacs/wiki/Debugging#enable-debug) to learn how it's done. Here's a TL;DR: run `SPC t D` (or `M-x toggle-debug-on-error`) before `M-x slime` and post the backtrace that pops up.

**Comment by phoe** [comment]
I cannot reproduce with stock Emacs and slime. This does not occur on spacemacs version 0.200.

This is weird, but after today's fresh cloning and checking the develop branch, I cannot reproduce this on develop either. Slime opens up just fine.

I will close this issue for now because of this.

Thank you for the support so far. If I see this again, I will reopen.
