### ISSUE TITLE
Pylookup update creates empty database

### ISSUE THREAD

**Issue by shitikanth** [syl20bnr/spacemacs#9866]
#### Description :octocat:
Pylookup update creates empty database. Queries for standard library modules following pylookup update return no matches.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC SPC pylookup-update RET`

*Observed behaviour:* :eyes: :broken_heart:
Generated file `pylookup.db` is empty. Looking up standard library modules like `math`, `array` fails.

*Expected behaviour:* :heart: :smile:
It should create a non-empty database that should be searchable.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a363f85)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown javascript html bibtex auto-completion common-lisp emacs-lisp git helm latex org pdf-tools python
          (shell :variables shell-default-shell 'eshell shell-default-term-shell "/bin/zsh")
          syntax-checking version-control sk-org sk-base16 w3m)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```

```

**Comment by shitikanth** [comment]
Looks like the issue is that sphinx changed their template for genindex.

**Comment by miraclemore** [comment]
@shitikanth  Thx for your help! It helps me to generate the pylookup.db.

**Comment by Miciah** [comment]
Since #9868 / https://github.com/syl20bnr/spacemacs/commit/48032ca787b30f6e3c7291b3138a4012dac11f4f has been merged, can this issue be labeled as "Fixed in develop"?
