### ISSUE TITLE
Add transient state for frame configuration

### ISSUE THREAD

**Issue by rgemulla** [syl20bnr/spacemacs#9872]
Spacemacs has integrated transient states for buffer and window configuration, but it does not have such a state for frame configuration. 

Since I found it tedious to change the frame configuration, I created such a state along with some convenience functions (e.g., to quickly expand the frame with a new window and get rid of this expansion later on). 

I am opening this issue to see whether there is interest to integrate such a state into Spacemacs. If so, I'd be happy to provide a pull request.

The transient state is currently available as a separate layer [here](https://github.com/rgemulla/spacemacs-layers/tree/master/+emacs/frames). The transient state has the following functionality:
```
 Move^^^^             Snap^^^^             Resize^^               Maximize^^        Other^^
 ────^^^^──────────── ─────^^^^─────────── ──────^^── ─────────── ────────^^─────── ──────────────────^^
 [_j_/_k_] down/up    [_J_/_K_] bottom/top [_[_] shrink horiz     [___] horiz       [_n_] create
 [_h_/_l_] left/right [_H_/_L_] left/right [_]_] enlarge horiz    [_v_] verti       [_d_] delete
 ^^^^                 ^^^^                 [_{_] shrink verti     [_m_] both        [_D_] delete other
 ^^^^                 ^^^^                 [_}_] enlarge verti    [_f_] fullscreen  [_q_] quit
 ^^^^                 ^^^^                 [_+_] enlarge+split h. ^^                ^^
 ^^^^                 ^^^^                 [_-_] shrink+delete h. ^^                ^^")
```

**Comment by bmag** [comment]
Sure, go ahead and open a PR. Although, be aware that:
- The functions in `funcs.el` might be good additions to make upstream in frame-cmds, so not only Spacemacs benefits from them. Also, there might be already exist equivalent functions somewhere. I just skimmed the code, didn't take an in-depth look.
- `frame-cmds` should probably be auto-loaded, not required outright.
- the changes might fit as part of an existing layer
- we have a `frame-cmds.el` file in `spacemacs-visual/local/zoom-frm/frame-cmds.el`. I don't know why it's there, but it's a conflict that will need to be resolved.

**Comment by rgemulla** [comment]
Yes, these changes would fit the ```spacemacs-visual``` layer, in my point of view. The frame-cmds.el of that layer is not a conflict, it's the same dependency I am using. I'll do a PR to discuss further, thanks!
