### ISSUE TITLE
Usability issue related to "jump to definition"

### ISSUE THREAD

**Issue by sdwolfz** [syl20bnr/spacemacs#9873]
Starting some time ago I noticed that when I try to jump to definition, I would get prompted to specify a `TAGS` file. This did not happen before, and although I just press enter and get the same result, this is an extra keypress I need to do every time I want to jump. 

It was an annoying thing but I kind of ignored it, I tought it was something wrong with my setup, or some glitch that might be fixed soon. But I noticed that other people had this problem as well, [here](https://www.reddit.com/r/emacs/comments/7cawkm/after_a_week_i_must_begrudgingly_admit_vscode_is/) is one example. I think I saw someone also mentioning it in an issue or PR here as well.

So I poked around a bit to find out why this was. First I inspected spacemacs jump handlers in a ruby file by doing:
```
M-; (pp spacemacs-jump-handlers)
```
Which gave me this result:
```emacs-lisp
(robe-jump evil-goto-definition dumb-jump-go)
```

I expected `robe-jump` to be the first one since it always asks to start a ruby console. I also expected `dumb-jump-go` to be a fallback. But I did not know what the deal was with `evil-goto-definition`, it seemed useless to have it since `dumb-jump` is already here.

Looks like `evil-goto-definition` is added [by this line](https://github.com/syl20bnr/spacemacs/blob/36c15b79f6d490a4733cfca3278c0c837fdc2cff/layers/%2Bdistributions/spacemacs-bootstrap/packages.el#L56). And `dumb-jump` is added at the end of the jump handler list [here](https://github.com/syl20bnr/spacemacs/blob/36c15b79f6d490a4733cfca3278c0c837fdc2cff/layers/%2Bspacemacs/spacemacs-misc/packages.el#L39).

Since this functionality was way older than the time I started getting the `TAGS` prompt, I looked inside `evil` for clues and it led me to [this line](https://github.com/emacs-evil/evil/blob/5337d2b3d2f739b4b5b4a73bc0e66363be6b71f9/evil-commands.el#L2677) which is the right age and everything made sense.

When jumping to definition, `xref-find-definitions` is called before `dubm-jump-go` and this is why the `TAGS` prompt appears. When no `TAGS` file is specified it just falls back to `dumb-jump`, which is the expected functionality, but with an extra step that's both confusing and annoying. 

< rant> 
No wonder people sell their soul to vscode, altough the jump to definition functionality works well in spacemacs, they get prompted to provide who knows what tags file like we're in the stone age or something. 
< /rant>

What I suggest is to either:
- remove the `xref-find-definitions` from `evil`.
- remove `evil-goto-definition` from `spacemacs-default-jump-handlers` and make `dumb-jump` a `spacemacs-bootstrap` package to replace it.
- when `dumb-jump` is available search trough `spacemacs-default-jump-handlers` and remove `evil-goto-definition` if it exists.

I'm ready to submit a PR with any of the changes above, I just need you feedback.
/cc @syl20bnr @TheBB 

Here are some of my setup details in case they are needed (but the problem should be the same in master and develop with latest evil):

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.90
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 36c15b79)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion helm org neotree react c-c++ elixir emacs-lisp erlang groovy html java javascript markdown php python ruby rust shell-scripts sql vimscript windows-scripts yaml git
  (gtags :disabled-for elixir emacs-lisp java ruby)
  ansible docker)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 LIBSYSTEMD LCMS2

**EDIT:** Quick fix
Add the following lines to your `dotspacemacs/user-config`
```emacs-lisp
(setq spacemacs-default-jump-handlers
  (remove 'evil-goto-definition spacemacs-default-jump-handlers))
```

**Comment by dbalatero** [comment]
@sdwolfz Did you ever find a workaround? I'm hitting the same issue over here.

**Comment by aaronjensen** [comment]
Does `(setq xref-backend-functions nil)` help?

**Comment by dbalatero** [comment]
@aaronjensen Unfortunately, I just get:

```
No applicable method: xref-backend-definitions, nil, "PDF::FormAdapter"
```

when the cursor is over a `PDF::FormAdapter` symbol and I hit `ctrl + ]`

**Comment by aaronjensen** [comment]
Oh. I don't ever use `C-]`, which is probably why I'm not seeing what you're seeing. I'm using `g d` which behaves properly for me in that it gets me where I want to go, but I do not believe it uses tags.

**Comment by sdwolfz** [comment]
@dbalatero I did not actually look into this further since I opened the issue, was waiting for feedback. What I did was to comment [this line](https://github.com/syl20bnr/spacemacs/blob/36c15b79f6d490a4733cfca3278c0c837fdc2cff/layers/%2Bdistributions/spacemacs-bootstrap/packages.el#L56) inside `.emacs.d`. But I think this snippet of code should work:
```emacs-lisp
(setq spacemacs-default-jump-handlers
  (remove 'evil-goto-definition spacemacs-default-jump-handlers))
```

**Comment by sdwolfz** [comment]
Closing this as dumb jump and lsp work better now.
