### ISSUE TITLE
`scala-enable-eldoc` variable in scala layer results in eldoc error

### ISSUE THREAD

**Issue by amilkov1** [syl20bnr/spacemacs#9874]
#### Description :octocat:
`scala-enable-eldoc` variable in scala layer results in eldoc error

#### Reproduction guide :beetle:
- Start Emacs
- Open Scala file
- Position cursor over error or some val, for example

*Observed behaviour:* :eyes: :broken_heart:
Cursor over error or, for example, `val` (to check type) results in `eldoc error: (void-function ensime-print-type-at-point)` displayed in the mini-buffer. In addition, `SPC-m-i-i` (to manually check type under the cursor) yields: `Wrong type argument: commandp, ensime-inspect-type-at-point`

*Expected behaviour:* :heart: :smile:
Should show type or error automatically under cursor and type when requested manually

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm better-defaults emacs-lisp git markdown
      (shell :variables shell-default-full-span nil shell-default-height 60 shell-default-shell 'ansi-term shell-default-position 'bottom)
      spell-checking syntax-checking
      (version-control :variables version-control-global-margin t version-control-diff-tool 'diff-hl version-control-diff-side 'left)
      haskell auto-completion
      (haskell :variables haskell-completion-backend 'intero)
      osx yaml shell-scripts
      (scala :variables scala-enable-eldoc t scala-auto-insert-asterisk-in-comments t scala-auto-start-ensime t))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by amilkov1** [comment]
FWIW

Switched func pointed to by `scala-enable-eldoc` i.e.
```emacs
(defun scala/enable-eldoc ()
  (setq-local eldoc-documentation-function
              (lambda ()
                (when (ensime-connected-p)
                  (ensime-print-type-at-point))))
  (eldoc-mode +1))
```
to use `ensime-type-at-point` instead of `ensime-primt-type-at-point` and now things are working, so a solution could be to just do this in the layer itself however the `Wrong type argument: commandp, ensime-inspect-type-at-point` error still stands

**Comment by rgemulla** [comment]
There seems to have been a number of API changes in ensime. I found that many commands of the scala layer are not working (e.g., ```ensime-goto-impl``` under ```SPC m g i``` is an undefined command in ensime; it provides ```ensime-edit-definition``` instead).

**Comment by sa1** [comment]
Should be closed.
https://github.com/syl20bnr/spacemacs/issues/11482

**Comment by duianto** [comment]
@sa1 Thanks
