### ISSUE TITLE
Set up exec-path-from-shell to use Bash in OS X

### ISSUE THREAD

**Issue by jupl** [syl20bnr/spacemacs#988]
I have my OS X setup to use ZSH by default. Unfortunately when I start up Emacs GUI (regardless if it's official or emacs-mac-port) I keep getting a window pop up at the bottom:

```
Error (use-package): exec-path-from-shell :init: Expected printf output from shell, but got: "tput: No value for $TERM and no -T specified
open terminal failed: not a terminal
open terminal failed: not a terminal
"
```

What I've done to remedy that in my personal config is to get `exec-path-from-shell` to use Bash by running this first before initialize in OS X for GUI.

```elisp
(exec-path-from-shell-setenv "SHELL" "/bin/bash")
```

I believe this would need to be done on Spacemacs' part because it's too early to run that from `dotspacemacs/init` and too late from `dotspacemacs/config`.

**Comment by jupl** [comment]
I'll close as I may have a found a personal fix and am not sure if it's worth bringing attention. Luckily I can take advantage of `with-eval-after-load` in `dotspacemacs/init`:

```elisp
(when (and (display-graphic-p) (eq system-type 'darwin))
  (with-eval-after-load 'exec-path-from-shell
    (exec-path-from-shell-setenv "SHELL" "/bin/bash"))))
```

**Comment by davidpelaez** [comment]
FYI for someone googling this in the future. In my case I solved it removing tmux autostart from zshrc (was being handled by zprezto)

**Comment by arnm** [comment]
**~/.zshrc**
```bash
# Do not use autostart, manually start/attach session
# https://github.com/syl20bnr/spacemacs/issues/988
ZSH_TMUX_AUTOSTART=false
[[ $TMUX == "" ]] && tmux new-session -A -s sesh
```
