### ISSUE TITLE
O noes! Donate badge is missing!

### ISSUE THREAD

**Issue by eggsyntax** [syl20bnr/spacemacs#9880]
#### Description :octocat:
O noes! Donate badge is missing!

#### Reproduction guide :beetle:
Visit main github page. At the bottom, "Paypal" link links back up to the top of
the page. Looking at the raw markdown, there's supposed to be a Paypal badge
there, but I can't see it in either Chrome or Firefox (only browsers I've checked).

As a suggestion, it might be worth putting the badge in a couple more places, like
the front page of spacemacs.org -- it took me a while to figure out how to donate.

*Observed behaviour:* :eyes: :broken_heart:
No donate badge to be found.

*Expected behaviour:* :heart: :smile:
A paypal badge so I can contribute like a good user ;)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. e2a45e0c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html markdown helm clojure
      (auto-completion :variables auto-completion-complete-with-key-sequence-delay 0.4 auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
      emacs-lisp git)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
n/a
```

**Comment by CarlQLange** [comment]
It's there for me! Maybe you have an adblock on or something? 
<img width="799" alt="screen shot 2017-11-18 at 11 01 17" src="https://user-images.githubusercontent.com/859820/32979591-da45a68e-cc4f-11e7-94da-68cf5a4652f5.png">

**Comment by LemmingAvalanche** [comment]
The Paypal badge is there for me as well.  Using Firefox.

**Comment by eggsyntax** [comment]
Strange -- I checked both in Chrome (where I have an adblocker installed) and Firefox (where I don't). On most recent Ubuntu, in case that makes a difference.

But whatever's going on, it's clearly on my end :)

Closing. Thanks for checking, y'all!
