### ISSUE TITLE
Pressing undo moves cursor to top of the file

### ISSUE THREAD

**Issue by tsoernes** [syl20bnr/spacemacs#9883]
#### Description :octocat:
Doing undo, that is, pressing 'u' in normal mode takes me to the top of the file.

#### Reproduction guide :beetle:
- Start Emacs
- Make some changes
- Press 'u'

*Observed behaviour:* :eyes: :broken_heart:
All text becomes marked (not visual selection, some other color) and the cursor moves
to the top of the file.

*Expected behaviour:* :heart: :smile:
Not the above ..

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml javascript python
      (haskell :variables haskell-process-type 'stack-ghci)
      helm auto-completion better-defaults emacs-lisp git markdown syntax-checking
      (python :variables python-enable-yapf-format-on-save t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
```

**Comment by Somelauw** [comment]
Maybe this is because of python-enable-yapf-format-on-save t
Does it only happen in Python buffers or does it happen in other buffers too?

**Comment by tsoernes** [comment]
@Somelauw Only happens in Python buffers.  And It only happens if undoing after saving the file.

**Comment by Somelauw** [comment]
Does it happen when you set `python-enable-yapf-format-on-save` to nil?

**Comment by tsoernes** [comment]
No

2018-02-01 21:02 GMT+01:00 Somelauw <notifications@github.com>:
