### ISSUE TITLE
Searching with `/` on a large file freezes Emacs at the first character input

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#9887]
#### Description :octocat:
Emacs hangs at the first character input when searching with `/` on a large file

#### Reproduction guide :beetle:
- Start Emacs
- Open a relatively large file with many lines (e.g. an `org` file with > 6000 lines)
- Hit `/` and try to search for something

*Observed behaviour:* :eyes: :broken_heart:
When the first character input is received by Emacs, it hangs for a long while, sometimes more than 10 seconds, before finally proceeding to accept the whole search term and display it in the document.

*Expected behaviour:* :heart: :smile:
Emacs proceeds to search for this term normally without delay

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f2905650)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python html helm speed-reading auto-completion better-defaults spell-checking syntax-checking semantic rcirc osx git github version-control
        (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/zsh" shell-enable-smart-eshell t)
        typography chrome dash fasd pandoc colors themes-megapack gtags imenu-list vim-powerline evil-snipe emacs-lisp
        (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "gibiansky")
        elixir org
        (latex :variables latex-enable-auto-fill nil)
        markdown yaml shell-scripts javascript ess)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by x-ji** [comment]
I have a hunch that this has something to do with the fact that Emacs tries to highlight all matches in the current buffer. However, since a search term with only one character is bound to occur for extremely many times in a large file, this highlighting freezes Emacs. Maybe if I set Emacs to only highlight matching terms when it's several characters long, this problem would be solved?

**Comment by x-ji** [comment]
I looked at previous issues https://github.com/syl20bnr/spacemacs/issues/9410, https://github.com/syl20bnr/spacemacs/issues/9220 and https://github.com/TheBB/spaceline/issues/123#issuecomment-304696321, but I'm pretty sure this is unrelated since I don't even use `spaceline`. I use `vim-powerline`.

**Comment by sdwolf** [comment]
Try using the documentation from here to debug it: https://github.com/syl20bnr/spacemacs/wiki/Debugging#debug-a-freezing-instance.

**Comment by eggsyntax** [comment]
Just chiming in to say I'm encountering this as well on `develop` (but just switched back to master, so we'll see). My intuition matches @x-ji 's, although it's just a guess.

**Comment by syl20bnr** [comment]
Duplicate of https://github.com/syl20bnr/spacemacs/issues/9220

**Comment by BryceStevenWilley** [comment]
Following @sdwolfz's link on how to debug I get this output (running on `devel`, commit 6b03fefe17ff3ccdadd10cad81cccf525a5f4f19):
```
Debugger entered--Lisp error: (quit)
  redisplay_internal\ \(C\ function\)()
  read-string("/" #("Custom" 0 6 (face shadow)) evil-ex-search-history)
  evil-ex-start-search(forward nil)
  evil-ex-search-forward(nil)
  funcall-interactively(evil-ex-search-forward nil)
  call-interactively(evil-ex-search-forward nil nil)
  command-execute(evil-ex-search-forward)
```
