### ISSUE TITLE
hl-highlight-mode not enabled by default

### ISSUE THREAD

**Issue by rpglover64** [syl20bnr/spacemacs#989]
Although <kbd>SPC h h</kbd> is bound by default, it (confusingly) does nothing, because hl-highlight-mode is not enabled.

Note: this is opposite the behavior of <kbd>SPC s h</kbd> and auto-highlight-symbol-mode.

**Comment by StreakyCobra** [comment]
The `hl-anything` package have been excluded from spacemacs for months now, this issue is not relevant anymore. Feel free to reopen it if this behaviour appears again (if and when the package get re-integrated) :relaxed:
