### ISSUE TITLE
Add centered-point toggle to "Symbol Highlight Transient State"

### ISSUE THREAD

**Issue by vbauerster** [syl20bnr/spacemacs#9890]
When searching word with <kbd>*</kbd> or <kbd>#</kbd>, I often find myself hitting <kbd>z</kbd><kbd>z</kbd> to center the highlight. But hitting <kbd>z</kbd><kbd>z</kbd> dismisses`Symbol Highlight Transient State` preview window.

It would be very helpful if `Symbol Highlight Transient State` will contain let say `[c]` toggle to on/off `centered-point` without exiting state.

[![Screen_Shot_2017-11-19_at_22.43.53.png](https://s25.postimg.cc/gn2k6uvrz/Screen_Shot_2017-11-19_at_22.43.53.png)](https://postimg.cc/image/4l76cpmjf/)

**Comment by duianto** [comment]
This might be related:
