### ISSUE TITLE
Documentation: Go layer: Bad link for oracle

### ISSUE THREAD

**Issue by jrmiller82** [syl20bnr/spacemacs#9891]
`go get -u -v golang.org/x/tools/cmd/oracle`

Is a dead link. Doesn't even exist on the godoc for that link.

**Comment by phss** [comment]
@jrmiller82 I believe this has been already fixed in the `master` branch. Here's the commit that fixes it: https://github.com/syl20bnr/spacemacs/commit/0fd0d7f8e98e7fe3fafd5f5126259844f3016703#diff-9461957b3c790c5c3299cc03bee3e4b1

I suggest updating Spacemacs and having a look again.

**Comment by jrmiller82** [comment]
Hmmm. You're right. I had reached the layer somehow through the main spacemacs documentation page, instead of browsing source of the github repo or internal documentation. And now, of course, I can't find the bad link.

**Comment by smile13241324** [comment]
@jrmiller82 I have found the wrong link, it is in the current version of the spacemacs website, within the layers list. However it is fixed on master already so I think one only had to update the website.

@JAremko can you regenerate the spacemacs website? There are currently some broken links which are already fixed on master.

**Comment by jrmiller82** [comment]
@smile13241324 Thank you! I was thinking I was going crazy. :)

I'll leave this open until someone verifies that they have successfully regenerated the website.

**Comment by JAremko** [comment]
@smile13241324  http://develop.spacemacs.org/ should have all links in order (we have test for 404) spacemacs.org should be updated with the next release :thinking:

**Comment by jrmiller82** [comment]
Please feel free to close the issue as you guys see fit. Thanks again for all your hard work on spacemacs!

**Comment by smile13241324** [comment]
@JAremko you are right the develop page is cool. As to the test do we also check links in source blocks? Cause the issue was a wrong link in the go specific source block containing installation cmds.

Thanks for the quick reply 👍

**Comment by JAremko** [comment]
@smile13241324  Probably not since this is a plain text not a legit link :thinking:
