### ISSUE TITLE
C-r in insert mode should prompt for register to pull from.

### ISSUE THREAD

**Issue by danieljaouen** [syl20bnr/spacemacs#9894]
#### Description :octocat:
C-r in insert mode should prompt for register to pull from.

#### Reproduction guide :beetle:
- Start Emacs
- Open a new line with `o` and type `hello world`
- Save `hello` to register `a` by moving the cursor to the beginning of the word, then pressing `ve"ay`
- Save `world` to register `b` by moving the cursor to the beginning of the word, then pressing `ve"by`
- Enter insert mode and hit C-r

*Observed behaviour:* :eyes: :broken_heart:
The contents of the last register appears.

*Expected behaviour:* :heart: :smile:
Emacs should prompt for a register to pull from.  Note that if you delete the line and then enter insert mode again, the correct behavior occurs.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible auto-completion c-c++ clojure colors common-lisp django elixir emacs-lisp emoji erlang git github go helm html javascript latex markdown nginx org osx php python ruby ruby-on-rails scheme shell-scripts syntax-checking tmux version-control vimscript yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
N/A
```

**Comment by duianto** [comment]
It's working as expected for me.

Type:
```
abc
def
```

1. move the cursor to the `a`
2. press: `"ayiw`, to store the inner word `abc`, in register `a`
3. move the cursor to the `d`
4. press `"byiw`, to store the inner word `def`, in register `b`
5. open a new line below and enter insert state `o`
6. press `C-r`, the `"` sign is shown after the cursor
7. press `a` to insert register `a`
8. press `C-rb`, inserts register `b`

This results in:
```
abc
def
abcdef
```

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spell-checking syntax-checking
                (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
                helm org treemacs git version-control autohotkey emacs-lisp haskell markdown)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by duianto** [comment]
Confirmed on both the latest master and develop branches. And it happens after yanking into only one register.

1. Type: `abc`
2. Press `viw` to select `abc`
3. Press `"ay`, to store `abc` in register `a`
4. Enter insert state on a new line `o` (although it happens anywhere)
5. Press `C-r`

Result:
```
abc
abc
```
The `"` prompt never appeared, `abc` was inserted directly.

If one remains in insert state, then `C-r` continues to insert `abc`.

The issue only seems to be occurring the first time one enters insert state. Because after yanking into the register, and entering insert state, if one exits back to normal state `Esc` and returns to insert state `i`, then `C-r` shows the `"` prompt.

**Comment by Miciah** [comment]
The following resolves the problem for me and not seem to cause any new problems:
```emacs-lisp
(add-hook 'evil-visual-state-exit-hook (lambda () (setq evil-this-register nil)))
```

**Comment by duianto** [comment]
@miciah 's solution shows the `"` prompt again. 👍

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c122eb6a0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey helm emacs-lisp git markdown neotree version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by duianto** [comment]
This doesn't occur in Vim, opened an issue upstream:
C-r doesn't prompt for a register https://github.com/emacs-evil/evil/issues/1285
