### ISSUE TITLE
How do I enable the evil plugin "evil-numbers"?

### ISSUE THREAD

**Issue by hersh-verthun** [syl20bnr/spacemacs#9895]
I want to use this plugin. When I press `SPC h d f` and search for `evil-numbers` it shows as installed. I thought it is a minor mode and I could enable it from `SPC h RET` but couldn't find it there.

I mostly use Spacemacs with **org-mode** and prefer to increment and decrement numbers with this plugin but cannot find a way to enable it. Please help.

**Comment by duianto** [comment]
When the cursor is on a number, then you can press `SPC n =` or `SPC n +` to increment by `1`, or `SPC n -` to decrement by `1`. The Evil Numbers Transient state also opens, which let's you {in,de}crement by `1` without having to press `SPC n` first. If you press one or more number keys first, then you can add or subtract by a larger number, ex: `50 -` subtracts `50`.

source: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#increasedecrease-numbers

**Comment by hersh-verthun** [comment]
@duianto Thank you. Your answer is very clear.
