### ISSUE TITLE
theme-megapack is missing 5 packages

### ISSUE THREAD

**Issue by goFrendiAsgard** [syl20bnr/spacemacs#9896]
```
Found 5 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: firebelly-theme@themes-megapack... [1/5]
Package firebelly-theme is unavailable. Is the package name misspelled?
--> installing package: niflheim-theme@themes-megapack... [2/5]
Package niflheim-theme is unavailable. Is the package name misspelled?
--> installing package: pastels-on-dark-theme@themes-megapack... [3/5]
Package pastels-on-dark-theme is unavailable. Is the package name misspelled?
--> installing package: tronesque-theme@themes-megapack... [4/5]
Package tronesque-theme is unavailable. Is the package name misspelled?
--> installing package: zonokai-theme@themes-megapack... [5/5]
Package zonokai-theme is unavailable. Is the package name misspelled?
```
Probably the issue can be fixed by deleting some packages from theme-megapack

Similar issue: https://github.com/syl20bnr/spacemacs/issues/9478

**Comment by duianto** [comment]
This is a duplicate of: 
Certain theme packages in the 'themes-megapack' layer are unavailable. #9837

It's been fixed on the develop branch, therefore it will get fixed on the master branch, when the next major release occurs (I don't know when that is).

The current solution on the master branch, is to add the removed packages in `.spacemacs` to the variable:
```
   dotspacemacs-excluded-packages '(firebelly-theme
                                    niflheim-theme
                                    pastels-on-dark-theme
                                    tronesque-theme
                                    zonokai-theme)
```

**Comment by vityafx** [comment]
I don't know is it related or not, but I also can't install the `colorsarenice-light` theme because of:

>   Warnings:
>       - An error occurred while applying the theme "colorsarenice-light", fallback on
>         theme "spacemacs-dark". Error was: (error Package `colorsarenice-theme-' is
>         unavailable)      
>       - Please check the value of "dotspacemacs-themes" in your dotfile or open an issue
>          so we can add support for the theme "colorsarenice-light".

**Comment by duianto** [comment]
@vityafx It's unrelated.

The colorsarenice theme seems to have been removed from github, the link:
https://github.com/Fanael/colorsarenice-theme leads to a 404 page.

But the Emacs Themes page: https://emacsthemes.com/themes/colorsarenice-themes.html
has a combined copy of the 3 colorsarenice theme files: https://emacsthemes.com/assets/local-src/colorsarenice-themes-source-code.el

It can be used to load the theme locally, but currently it only works on the Spacemacs develop branch, it probably will start working on the master branch as well when the next major release occurs.

This is what I did to get it working on the develop branch.
I downloaded the file: https://emacsthemes.com/assets/local-src/colorsarenice-themes-source-code.el
And saved the contents from line 1:
`;;; colorsarenice-common.el --- Common stuff for the colorsarenice themes. -*- lexical-binding: t -*-`
to line 93:
`;;; colorsarenice-common.el ends here`
into a file called: `colorsarenice-common.el`

On line 95:
`<pre class="lang:lisp decode:true " title="Colorsarenice Dark">;;; colorsarenice-dark-theme.el --- The dark colorsarenice theme. -*- lexical-binding: t -*-`
I removed: `<pre class="lang:lisp decode:true " title="Colorsarenice Dark">`:
And on line 159:
`;;; colorsarenice-dark-theme.el ends here</pre>`
I removed the last part `</pre>`, and saved the contents from line 95 to 159, in a file called `colorsarenice-dark-theme.el`

On line 161:
`<pre class="lang:lisp decode:true " title="Colorsarenice Light">;;; colorsarenice-light-theme.el --- The light colorsarenice theme. -*- lexical-binding: t -*-`
I removed: `<pre class="lang:lisp decode:true " title="Colorsarenice Light">`
and on line 225:
`;;; colorsarenice-light-theme.el ends here</pre>`
I removed `</pre>` from the end, and saved the contents from line 161 to 225, in a file called `colorsarenice-light-theme.el`

I then created a new directory in `~.emacs.d/private/local/` called `colorsarenice-theme`, and copied the 3 theme files into it:
```
colorsarenice-common.el
colorsarenice-dark-theme.el
colorsarenice-light-theme.el
```

Then in the `.spacemacs` files `dotspacemacs-themes` variable, I added:
`(colorsarenice-light :location local)` as the first entry, saved `.spacemacs` and restarted Emacs.

The Spacemacs-dark (default theme) is shown on startup, but when Spacemacs has loaded, then it switches to the colorsarenice-light theme.

Both the colorsarenice dark and light themes are listed in the `SPC T s` HELM Themes list.

To start Spacemacs with the colorsarenice-dark theme, then just change:
`(colorsarenice-light :location local)`
to
`(colorsarenice-dark :location local)`
in `.spacemacs`.

**Comment by vityafx** [comment]
@duianto thanks for doing such a research!.. However, as I see it needs so much things to be done so I decided it does not worth in my case, I'll just use another theme..

**Comment by goFrendiAsgard** [comment]
Switch to development branch fixed the issue. So, I'm going to use the development version for now. And if this was fixed in development branch, I guess I can close this issue, since it means that the issue is basically already solved.
