### ISSUE TITLE
Question: is there a way to make shift work as in vim in visual mode (it almost duplicates control)

### ISSUE THREAD

**Issue by vityafx** [syl20bnr/spacemacs#9898]
In vim I used to use shift + right/left for jumping across the words while I selecting them, but in spacemacs I can only use `ctrl` for that. Is there a way to make the keys be as in vim?

**Comment by duianto** [comment]
These commands seem to make `shift` + the `right` and `left` arrow keys, work the same way as in Vim.
```
(define-key global-map (kbd "S-<right>") 'evil-forward-word-begin)
(define-key global-map (kbd "S-<left>") 'evil-backward-word-begin)
```
The cursor jumps to the first letter of every word.

**Comment by vityafx** [comment]
Awesome, thanks!
