### ISSUE TITLE
react layer, add support for tslint with react-mode

### ISSUE THREAD

**Issue by xyz5020** [syl20bnr/spacemacs#9902]
currently, i found that react layer is not support for tslint with react-mode. That was not convenient with writing tsx file. So, i add `(flycheck-add-mode 'typescript-tslint 'react-mode)` this to the layer,
and it works fine. Thinking you may can update it. fyi

**Comment by bmag** [comment]
When I wrote in the gitter channel that it's worth an upstream issue/pull request, I meant that it should be reported against Flycheck's repository, not Spacemacs. I'm not saying we can't include it, but this change is useful (probably) to all Flycheck users.

start of gitter conversation: https://gitter.im/syl20bnr/spacemacs?at=5a16a079232e79134dc0f82a
