### ISSUE TITLE
splitbelow and splitright

### ISSUE THREAD

**Issue by meitham** [syl20bnr/spacemacs#9906]
Could we provide a way to do the equivalent of VIM's ``splitbelow`` and ``splitright``?

**Comment by CeleritasCelery** [comment]
You should ask this upstream at evil.

**Comment by meitham** [comment]
According to https://github.com/emacs-evil/evil/issues/467#issuecomment-273753713 there are evil keybindings available to do splitbelow and splitright, they are ``split-window-below-and-focus`` and ``split-window-right-and-focus``.  I would argue though that it should be spacemacs configurations to decide which of the splits is the default.

**Comment by CeleritasCelery** [comment]
Spacemacs already has `SPC w <S s V v>` which are mapped to `split-window-below-and-focus`, `split-window-below`, `split-window-right-and-focus`, and `split-window-right` respectively.  That should cover it.

**Comment by sampablokuper** [comment]
`:splitbelow` gives *[Unknown command]*.

Likewise `:splitright`.

:(

**Comment by goetzc** [comment]
@sampablokuper on the current Spacemacs version, `split-window-below-and-focus` and `split-window-right-and-focus` work as expected. They can be called with the `SPC w S` and `SPC w V` keybinding respectively.

**Comment by sampablokuper** [comment]
@goetzc [wrote](https://github.com/syl20bnr/spacemacs/issues/9906#issuecomment-425598471):
> on the current Spacemacs version, `split-window-below-and-focus` and `split-window-right-and-focus` work as expected. They can be called with the `SPC w S` and `SPC w V` keybinding respectively.

This is true. Thanks.

Even so, it would be nice if `:splitbelow` and `:splitright` worked.
