### ISSUE TITLE
Question: how do I set the font size correctly before start up on HiDPI?

### ISSUE THREAD

**Issue by vityafx** [syl20bnr/spacemacs#9907]
I have tried to set my favourite font with proper DPI size (x 2):

```el
   dotspacemacs-default-font '("Terminus"
                               :size 28
                               :weight normal
                               :width normal
                               :powerline-scale 1.1)
```

However, the font is set to `Terminus` after spacemacs startup, it is very tiny (like it is 14 instead of 28). After that for setting it properly I must go to `menu-set-font`, pick `Terminus` there and choose the size `14`. After that it has normal size. I guess the problem is because of my 4k monitor.

**Comment by harindu95** [comment]
Try doing this.  (set-face-attribute 'default nil 
                               :height 133
                               :family "Monospace")
Which is what you get by menu-set-font.

**Comment by vityafx** [comment]
@harindu95 what is `133` exactly?

**Comment by harindu95** [comment]
I am not exactly sure if it's in pixels or another unit, but it stands for font size.

**Comment by well1791** [comment]
Perhaps [this](https://github.com/syl20bnr/spacemacs/issues/3477#issuecomment-317938575) help

**Comment by vityafx** [comment]
Just to finish this off with something, I am just to use the "menu-set-font" now because nothing else works.
