### ISSUE TITLE
indentation issue

### ISSUE THREAD

**Issue by M-Yudaxia** [syl20bnr/spacemacs#9908]
example:
vector<int> vec = {// at this point , when press ENTER key
------------- |       <---cursor is inserted here
}
expected:
vector<int> vec = {
--|    <---cursor
}

**Comment by CeleritasCelery** [comment]
What major-mode? Most likely this is an emacs setting not a Spacemacs one.

**Comment by M-Yudaxia** [comment]
c++mode this effect will go away if i turn the syntactic indentation off..

**Comment by M-Yudaxia** [comment]
![dec-10-2017 13-09-27](https://user-images.githubusercontent.com/20807817/33802150-6ea63b4c-ddab-11e7-82ce-6ea34fe1b99d.gif)

**Comment by M-Yudaxia** [comment]
![dec-10-2017 13-14-23](https://user-images.githubusercontent.com/20807817/33802187-139f9a62-ddac-11e7-9b75-ced0030812c5.gif)
another problem is invoking functions, the text line will jump ahead unless the statement is closed by  ;

**Comment by M-Yudaxia** [comment]
problem solved by change the indentation style M-x c-set-style from gnu to cc-mode
