### ISSUE TITLE
Option to move flycheck-fringe's bullets to the right gutter

### ISSUE THREAD

**Issue by vbauerster** [syl20bnr/spacemacs#9912]
Is there any option to have flycheck-fringe's bullets on the right side of the gutter?
IMO default settings for gutters (git-gutter on right and flycheck on left) are wrong.
I was able to move git-gutter to the left with help of `version-control-diff-side 'left` option, but didn't find how to move flycheck-gutter to the right. Please help is it even possible?

**Comment by CeleritasCelery** [comment]
You should ask this upstream at flycheck

**Comment by vbauerster** [comment]
Thank you, I've asked.
https://github.com/flycheck/flycheck/issues/1364
