### ISSUE TITLE
Flyspell overwriting correct ispell program name and failing

### ISSUE THREAD

**Issue by karljs** [syl20bnr/spacemacs#9916]
#### Description :octocat:
Flyspell fails to load.  I have aspell installed and correctly on the PATH.  Every time I boot Spacemacs I get the following in messages:

```
Error enabling Flyspell mode:
(Searching for program No such file or directory ispell)
```

Moreover, if I check the value of `ispell-program-name` it seems to be set to "ispell" but says it's value used to be "/usr/local/bin/aspell", which would have been correct.

#### Reproduction guide :beetle:
- Start Emacs
- Have spell checking layer enabled
- Check *messages*

*Observed behaviour:* :eyes: :broken_heart:
Flyspell fails to load because it doesn't correctly find aspell

*Expected behaviour:* :heart: :smile:
Spell checking layer works out of the box with correct dependencies installed.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(agda auto-completion better-defaults bibtex c-c   csv elm emacs-lisp git github haskell helm html idris javascript latex markdown org osx purescript
      (shell :variables shell-default-shell 'eshell)
      spotify spell-checking syntax-checking themes-megapack version-control)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by MarcelloNicoletti** [comment]
I have this issue as well. Interestingly I found that it correctly finds aspell when doing `restart-emacs-resume-layouts` (`<SPC> q r` for me). I haven't done any digging into why this is unfortunately. 

My current workaround for this issue is to start emacs, then immediately restart emacs using `restart-emacs-resume-layouts` and continue like normal.

------

System Info:

* OS: macOS 10.13.3 (darwin)
* Emacs: 25.3.1 (d12frosted/emacs-plus latest)
* Spacemacs: 0.300.0
* Spacemacs branch: develop (rev. 93ec4217)
* Graphic Display: t
* Distribution: spacemacs
* Editing Style: vim
* Completion: helm
* Layers:

``` emacs-lisp
dotspacemacs-configuration-layers '( auto-completion better-defaults clojure csharp c-c++
csv emacs-lisp emoji git helm html java javascript markdown 
(org :variables org-enable-org-journal-support t org-projectile-file "TODOs.org" ) python ruby 
(spell-checking :variables enable-flyspell-auto-completion nil ) 
(syntax-checking :variables :enabled-for javascript python ruby :enabled-for-modes shell-script-mode )  
windows-scripts yaml )
```

**Comment by joech4n** [comment]
I am running into the same issue.

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(yaml javascript python ivy deft emacs-lisp evil-snipe html
      (markdown :variables markdown-live-preview-engine 'vmd)
      (org :variables org-enable-reveal-js-support t org-enable-github-support t)
      spell-checking)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES
