### ISSUE TITLE
Suggestion/question: install private layer from Github

### ISSUE THREAD

**Issue by troglotit** [syl20bnr/spacemacs#9925]
Is there a way to install layers from Github? Something like this? If no, was there some specific reasons?
```elisp
   dotspacemacs-configuration-layers
   '(
     '(my-private-layer :github "troglotit/private-layer")
    )
```

I tried to search for an issue here, excuse me if it's a duplicate issue. Feel free to close issue :v:

**Comment by CeleritasCelery** [comment]
```elisp
dotspacemacs-additional-packages
'(
  (my-private-layer :location (recipe :fetcher github :repo "troglotit/private-layer"))
 )
```

**Comment by troglotit** [comment]
It gives me the warning: 
```
(Spacemacs) Warning: Unknown layer spacemacs-journal declared in dotfile.
```
Using 
```elisp
dotspacemacs-additional-packages
'(
     (spacemacs-journal :location
                        (recipe :fetcher github
                                :repo "borgnix/spacemacs-journal"))
)
```

**Comment by LeaveNhA** [comment]
Yeah, I have the same problem.

**Comment by CeleritasCelery** [comment]
Sorry I misread you wanting to install a layer for wanting to Install a package. 

There is no such layer as `spacemacs-journal`, it's called just `journal`. You could try adding the `:location` code to `dotspacemacs-configuration-layers` but I have never tried that before. So it would be 
```elisp
dotspacemacs-configuration-layers
'(
     (journal :location
                        (recipe :fetcher github
                                :repo "borgnix/spacemacs-journal"))
)
```
I am also using the `journal` layer but I just installed it manually.

**Comment by pataquets** [comment]
Adding another potential use case:
https://github.com/tuh8888/chezmoi.el?tab=readme-ov-file#spacemacs-layer

Since the package already contains a full snippet for a Spacemacs layer, it would be almost the same to have a working Spacemacs layer in some dir which could be installed via a Github fetcher... :disappointed:
