### ISSUE TITLE
dot repeat doesn't work on commands like `10x` `3dw` `5dd`

### ISSUE THREAD

**Issue by jeffmacdonald** [syl20bnr/spacemacs#9928]
#### Description :octocat:
dot repeat doesn't work on commands like `10x` `3dw` `5dd`

#### Reproduction guide :beetle:
- Start Emacs
- Create 5 or 10 lines of text
- Go to the start of one line and hit `10x` (delete 10 characters), then `j` (go down a line) then `.` (delete 10 characters again)

*Observed behaviour:* :eyes: :broken_heart:
When you press dot, it will only do the previous action once. i.e. delete just one character, or just one word or just one line

*Expected behaviour:* :heart: :smile:
In VIM it re does "delete 10 characters"

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql csv yaml html javascript python markdown pandoc emacs-lisp git org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by CeleritasCelery** [comment]
You should open this upstream at evil

**Comment by duianto** [comment]
It doesn't seem to be an evil issue, because it's working fine when Emacs is started with the `--quick` argument, and the evil package is loaded. It's also working on the Spacemacs develop branch.

**Comment by jeffmacdonald** [comment]
Here are my results: 


```abcdefghijklmnopqrstuvwxyz
klmnopqrstuvwxyz
bcdefghijklmnopqrstuvwxyz
bcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz```

**Comment by duianto** [comment]
Have you updated the packages? The `[Update packages]` link on the `SPC b h` Spacemacs home buffer.

Another thing to try is with just Emacs and the Evil package.

1. Start Emacs with the `--quick` argument to not load any configurations
2. `M-x` `package-initialize`
3. `M-:` `(require 'evil)`
4. `M-x` `evil-mode`
5. Copy and `p` paste the sample text into Emacs:

```
abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz
```
6. With the cursor on the `a` on the second line. Delete 10 characters: `10x`
7. Move to the next line and repeat the last command, twice:  `j.j.`

It should result in:
```
abcdefghijklmnopqrstuvwxyz
klmnopqrstuvwxyz
klmnopqrstuvwxyz
klmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz
```

If it works with just Emacs and Evil, then try commenting out all your user settings in `.spacemacs`.
If it works, start uncommenting chunks of the user settings until you find the issue.
Or if it remains broken without your user settings, then backup your current Spacemacs setup (the `.emacs.d` directory and the `.spacemacs` file), and start with a fresh clone/setup.
If it's still broken, then try another Emacs version (either newer or older). the latest official version is 25.3 (https://www.gnu.org/software/emacs/), but there might be pre-release versions of 26 for your OS.

**Comment by jeffmacdonald** [comment]
So because of *reasons* I've started my .spacemacs config all over. This feature now works fine.

I plan on diffing/merging my original file, so if this issue happens again I'll probably be able to find out why. Thanks.
