### ISSUE TITLE
Unable to override builtin package from within dotspacemacs-additional-packages

### ISSUE THREAD

**Issue by mbrt** [syl20bnr/spacemacs#9929]
I added this to my `.spacemacs` configuration:
```
dotspacemacs-additional-packages
'(
  (cc-mode :location (recipe :fetcher github :repo "mbrt/cc-mode" :min-version "1"))
  (modern-cpp-font-lock :location (recipe :fetcher github :repo "ludwigpacifici/modern-cpp-font-lock" :min-version "1"))
  )
```

The second package is correctly installed and works just fine, while the first does not. The only difference between the two is that emacs doesn't come with the `modern-cpp-font-lock` package, while `cc-mode` is present in the base emacs distribution. My idea was to override the default one with an update version sitting in my github repository. Is there a way around this problem? Maybe I'm just abusing this feature.

**Comment by ztlevi** [comment]
You might need to click the `update packages` button or call the corresponding function from the spacemacs home package.

**Comment by mbrt** [comment]
@ztlevi nope, that didn't help. The package is completely ignored, and not even downloaded.

**Comment by duianto** [comment]
I haven't tried fetching packages like that, so I might be mistaken, but could it have to do with that the fact that the `mbrt/cc-mode` package doesn't have any tags?

A quick search didn't show any mention of `:min-version`, but I found this mention of `:version-regexp` in the Recipe Format section of the melpa readme:
>:version-regexp is a regular expression for extracting a version-string from the repository tags. The default matches typical version tags such as 1.0, R16 or v4.3.5, so you should not override it unless necessary. For an unusual tag like "OTP-18.1.5", we might add :version-regexp "[^0-9]*\\(.*\\)" to strip the "OTP-" prefix. The captured portion of the regexp must be parseable by Emacs' version-to-list function.

source: https://github.com/melpa/melpa#recipe-format

**Comment by ztlevi** [comment]
@mbrt Try syntax like this. This works on my machine when I click the `update package` button.

`(doom-themes :location "~/Developer/Github/emacs-doom-themes")`

**Comment by mbrt** [comment]
@ztlevi yes, that one actually works. I'm wondering now why the github fetcher does not. I tried all permutations of the options at https://github.com/melpa/melpa#recipe-format, as @duianto suggested, but nothing worked. Running in debug mode also doesn't provide any debug message.

**Comment by mbrt** [comment]
OK, I was able to fix it with a workaround. I'm not sure how nice this is, but I'll post it for future reference. The trick was to specify another name for the package. It will be automatically picked up at emacs restart (no need to update packages):
```
(cc-mode-recent :location (recipe :fetcher github
                                  :repo "mbrt/cc-mode"
                                  :files ("cc-*.el")))
```

**Comment by duianto** [comment]
> the package is not on MELPA, but on github

That's just where I found a mention of `recipe` and `version`. And since the package without tags didn't work, then I thought that it might be something to investigate.

**Comment by bmag** [comment]
`:min-version` is a keyword of Spacemacs package list, not related to the recipe or Melpa. Should have been:
```elisp
  (cc-mode :location (recipe :fetcher github :repo "mbrt/cc-mode") :min-version "1")
  (modern-cpp-font-lock :location (recipe :fetcher github :repo "ludwigpacifici/modern-cpp-font-lock") :min-version "1")
```

Instead of the original:
```elisp
  (cc-mode :location (recipe :fetcher github :repo "mbrt/cc-mode" :min-version "1"))
  (modern-cpp-font-lock :location (recipe :fetcher github :repo "ludwigpacifici/modern-cpp-font-lock" :min-version "1"))
```

(notice the difference of where the recipe's closing parenthesis is)

**Comment by mbrt** [comment]
@bmag that's right. It appears now to work! Thanks
