### ISSUE TITLE
End of file during parsing evil-commands.el

### ISSUE THREAD

**Issue by pi3r** [syl20bnr/spacemacs#9931]
#### Description :octocat:
Updated packages and now spacemacs fails to start properly because it fails parsing `evil-commands.el`

#### Reproduction guide :beetle:
- Start Emacs with latest packages
- See error in `*Messages*`

#### Backtrace :paw_prints:
```
Loading /Users/pi3r/.emacs.d/layers/auto-layer.el (source)...done
(Spacemacs) No orphan package to delete.
(Spacemacs) + Configuring bootstrap packages...
(Spacemacs) Configuring async...
(Spacemacs)   -> init (spacemacs-bootstrap)...
(Spacemacs) Configuring bind-key...
(Spacemacs)   -> init (spacemacs-bootstrap)...
(Spacemacs) Configuring bind-map...
(Spacemacs)   -> init (spacemacs-bootstrap)...
(Spacemacs) Configuring diminish...
(Spacemacs)   -> init (spacemacs-bootstrap)...
(Spacemacs) Configuring evil...
(Spacemacs)   -> init (spacemacs-bootstrap)...
eval-buffer: End of file during parsing: /Users/pierrenespo/.emacs.d/elpa/evil-20171128.2307/evil-commands.el
```

**Comment by pi3r** [comment]
I know it's probably related to evil but I wasn't able to get spacemacs back to a usable state so far.

**Comment by shenxs** [comment]
same issue here

**Comment by pi3r** [comment]
Probably related to https://github.com/emacs-evil/evil/pull/986. Should be resolved when the new version is available in melpa

**Comment by tkossak** [comment]
Same issue here. How do i revert to older evil?

**Comment by pi3r** [comment]
@tkossak `M-x configuration-layer/rollback`

**Comment by pi3r** [comment]
A working version is back on melpa, I nuked `.cache` and `elpa/*` and everything is working as expected.
