### ISSUE TITLE
M-0 does not work in Treemacs

### ISSUE THREAD

**Issue by iromise** [syl20bnr/spacemacs#9935]
#### Description :octocat:

M-0 does not work in Treemacs and the buffer number assgined to treemacs is not 10 as spacemacs said in the doc.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC f t`
- `M-0`

*Observed behaviour:* :eyes: :broken_heart:
no window 10 and no switch.

*Expected behaviour:* :heart: :smile:
switch to the treemacs buffer

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 65d5e42)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(javascript windows-scripts yaml
            (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'term shell-default-term-shell "/bin/zsh")
            tmux spell-checking syntax-checking helm
            (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets")
            semantic better-defaults shell-scripts emacs-lisp
            (markdown :variables markdown-live-preview-engine 'vmd)
            (latex :variables latex-enable-folding t)
            restructuredtext javascript
            (python :variables python-enable-yapf-format-on-save t python-sort-imports-on-save t)
            sage imenu-list
            (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t c-c++-enable-clang-format-on-save t)
            git org gtags treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by duianto** [comment]
It's a known issue, that's related to how to handle the Treemacs window numbers when there are multiple frames. It's being discussed here:
Treemacs assigning window number, in both layer and package #9865

**Comment by iromise** [comment]
Sorry, It is my fault..

**Comment by duianto** [comment]
There's no need to be sorry. You did the right thing by reporting the issue. I'm sure others have noticed the same thing. Now they'll find your issue, if they search for `m-0 treemacs`, and they'll be redirected to the other issue.

The discussion isn't easy to find, since it started on the thread of another issue, with a title that doesn't talk about selecting window numbers.
