### ISSUE TITLE
Can't copy from Spacemacs session running in PuTTY

### ISSUE THREAD

**Issue by pschorf** [syl20bnr/spacemacs#9936]
I've been using spacemacs for about a year or so and just switched to using a session running in a PuTTY terminal instead of over X forwarding (I have a windows desktop, running emacs on a remote linux server.) Everything works great, including paste (via Shift+Insert) but I can't copy text out via selection with spacemacs. This works in a vanilla emacs, so I'm assuming there's some kind of bad package interaction going on. Not sure what I can do to debug this but I'm happy to provide more info if needed.

#### Description
Cannot copy text via mouse selection when running in putty.

#### Reproduction guide
- Start Emacs
- Select text with the mouse by dragging

*Observed behaviour:*
Selected text is not copied to the Windows Clipboard

*Expected behaviour:*
Selected text is copied to the windows clipboard
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
‘‘‘elisp
(ansible markdown emacs-lisp c-c++ git org
         (spell-checking :variables spell-checking-enable-by-default nil)
         (syntax-checking :variables syntax-checking-enable-by-default nil)
         version-control scala clojure semantic auto-completion sql latex java spotify restclient spotify typescript
         (mu4e :variables mu4e-installation-path "/home/pschorfh/tools/mu-0.9.16/mu4e")
         html emoji javascript shell-scripts erc semantic ranger
         (shell :variables shell-default-shell ’eshell)
         yaml csv fasd)
‘‘‘
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11

**Comment by nixmaniack** [comment]
Could you describe the steps in more detail as mentioned [here](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)? 

What do you mean by not able to copy? How do you copy text - selection with mouse and copy via context menu or selection by visual state in vim mode and using `y`?

**Comment by pschorf** [comment]
I updated the original issue with the details from the link you provided. It's hard to describe what's happening, as far as I know there isn't any sort of X clipboard in PuTTY, it's just copying text selections to the windows clipboard, and then pasting on right click by entering the characters into the terminal. I'm guessing something is getting the wires crossed between what is selected by the mouse in spacemacs and what putty thinks is selected.

For instance, in normal mode i can select text with the mouse and delete it with `d` as expected, so mouse selection is working. It's just not being copied to the windows clipboard.

**Comment by CeleritasCelery** [comment]
Can you reproduce with stock emacs?

**Comment by pschorf** [comment]
Stock emacs works as expected (text selected with the mouse is copied to the windows keyboard)

**Comment by zqtheu** [comment]
Hi, I met the same issue when use emacs in putty, finally I found that's caused by xterm-mouse-mode enabled. once I disable it, I can copy from putty to windows clipboard. hope this will help.

**Comment by pschorf** [comment]
That works! Thanks very much for the help.

**Comment by xingfeT** [comment]
That works! Thanks very much for the help.
