### ISSUE TITLE
Minor Issue with Doom Themes

### ISSUE THREAD

**Issue by matthewa150** [syl20bnr/spacemacs#9937]
#### Description :octocat:
Some of the `doom-themes` do not work as intended when set as a default theme on the `~/.spacemacs` file. A fix for both "doom-one" and "doom-molokai" exists on `core-themes-support.el` and I can make any of the other doom themes work via the same method. They ("doom-nova", "doom-one-light", "doom-peacock", "vibrant") also need to be added to the file and they all should work. (Overall this is a pretty minor issue haha) (I used peacock as the example)

#### Reproduction guide :beetle:
- Start Emacs
- Make sure that the "doom-peacock" themes is the first option under `setq-default dotspacemacs-themes`

*Observed behaviour:* :eyes: :broken_heart:
An error is thrown while trying to play the theme (I can switch to the theme via `SPC T s` and selecting, so I know it exists).

*Expected behaviour:* :heart: :smile:
The theme should be applied properly.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion better-defaults emacs-lisp git markdown
     (shell :variables shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom)
     spell-checking syntax-checking version-control themes-megapack rust ruby elixir version-control c-c   java latex)
```

#### Backtrace :paw_prints:
```
Warnings:
    - An error occurred while applying the theme "doom-peacock", fallback on theme
      "spacemacs-dark". Error was: (error Package `doom-peacock-theme-' is
      unavailable)      
    - Please check the value of "dotspacemacs-themes" in your dotfile or open an issue
      so we can add support for the theme "doom-peacock".      
```

**Comment by DVN196** [comment]
Have you add doom-themes to your  dotspacemacs--additional-package?

**Comment by matthewa150** [comment]
Yeah, I have it there. Like I said, I don't have an issue with either doom-one or doom-molokai

**Comment by CeleritasCelery** [comment]
> doom-peacock-theme-

That extra dash at the end makes me suspect there is a typo somewhere.

**Comment by matthewa150** [comment]
Yeah, that stood out to me too, but I'm able to cycle to the peacock theme, it only doesn't work as a start-up theme. I checked for typos, and unless I named the package wrong (doom-themes) or set the theme wrong (doom-peacock) I think I spelled everything correctly. When I previously mentioned a fix for doom-one and doom-molokai I was referencing [this](https://github.com/syl20bnr/spacemacs/commit/40f80a077909fb5a458e395230a11957cb9f459f#diff-9faeac5d36ea37c9d1931a190c11ac19) and [this](https://github.com/syl20bnr/spacemacs/commit/05057449ff4699e61ebf3b9f69f97476109c763a#diff-9faeac5d36ea37c9d1931a190c11ac19) which I think might be applicable fixes for the other variants.

**Comment by DVN196** [comment]
It is the same with kaolin-themes. When spacemacs add -theme to the theme name to get the package unless specified in spacemacs-theme-name-to-package. There was a pull request #9088 to add support for those additional doom themes but it seem that it can cause errors.

**Comment by DVN196** [comment]
Edit: solution is in #9084, add "your-theme-name"-theme in excludede package, and add doom-themes in additional-package.
```elisp
dotspacemacs-additional-packages '(doom-themes)
dotspacemacs-excluded-packages '(doom-peacock-theme)
```

**Comment by CeleritasCelery** [comment]
Looks like fixed in develop

**Comment by matthewa150** [comment]
Alright, well if they fixed it in develop I don't see a need to keep this open anymore. Thanks for all the help!

**Comment by verajosemanuel** [comment]
happening again for doom-challenger-deep

following instructions above to no avail:

```
dotspacemacs-additional-packages '(doom-themes)
dotspacemacs-excluded-packages '(doom-challenger-deep-theme)
```

Warnings:
    - An error occurred while applying the theme "doom-challenger-deep", fallback on
      theme "spacemacs-dark". Error was: (error Package ‘doom-challenger-deep-theme-’
      is unavailable)      
    - Please check the value of "dotspacemacs-themes" in your dotfile or open an issue
      so we can add support for the theme "doom-challenger-deep".

**Comment by kevin77797** [comment]
Happening again when using `doom-oceanic-next` as a default theme. With 
```
dotspacemacs-additional-packages '(doom-themes)
dotspacemacs-excluded-packages '(doom-oceanic-next-theme)
dotspacemacs-themes '(doom-oceanic-next)
```

```
Warnings:
    - An error occurred while applying the theme "doom-oceanic-next", fallback on
      theme "spacemacs-dark". Error was: (error Package ‘doom-oceanic-next-theme-’ is
      unavailable)      
    - Please check the value of "dotspacemacs-themes" in your dotfile or open an issue
      so we can add support for the theme "doom-oceanic-next".  
```

I wonder if this problem could be solved absolutely by changing the strategy of loading the default theme. For example, when emacs launching, it tries to load the default theme in the first place, if the theme is not exist, then decides to download it or whatever.

**Comment by duianto** [comment]
@kevin77797 I'm guessing that your on the Spacemacs `master` branch.

Adding the theme `doom-oceanic-next` as the first theme in the `dotspacemacs-themes` list in `.spacemacs` works for me on the `develop` branch.

The `develop` branch is the recommended branch until the next version is released (I have no insight into when that is).

#### To try the `develop` branch:
Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

<details><summary>
Windows 1903, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c39399045)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion c-c++ dap emacs-lisp git helm html java
            (javascript :variables javascript-backend 'lsp)
            (latex :variables latex-build-command "LatexMk" latex-enable-magic t)
            lsp
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            python ruby semantic-web
            (shell :variables shell-default-shell 'eshell shell-default-height 30)
            spell-checking sql syntax-checking themes-megapack treemacs
            (typescript :variables typescript-backend 'lsp)
            version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by 0kaguya** [comment]
My rough solution is copying the exact theme file to `~/.emacs.d/private/local/doom-<name>-theme/package.el`, then add local package in additional package list with `dotspacemacs-additional-packages '(doom-<name>-theme :location local ...)`. It prohibits fallback theme to be loaded.
