### ISSUE TITLE
dired could not create directory

### ISSUE THREAD

**Issue by jack2gs** [syl20bnr/spacemacs#9939]
Hi guys,

Could someone help me on this?

`Ivy-mode` is enabled. So there's completion when using `+` to create a new directory. Some times it will match the existed ones. Then error happened that it reports directory is existed.

Thanks,
Jack

**Comment by duianto** [comment]
This might be what your looking for:
>C-M-j (ivy-immediate-done) - exit with the current action, calling it on the current input instead of the current candidate. This is useful especially when creating new files or directories - often the input will match an existing file, which you don’t want to select.

source: https://github.com/abo-abo/swiper/blob/master/doc/ivy-help.org#key-bindings-for-single-selection

**Comment by jack2gs** [comment]
Thanks man! That's helpful! :)
