### ISSUE TITLE
Always get this error when open spacemacs

### ISSUE THREAD

**Issue by duytrung** [syl20bnr/spacemacs#9942]
Hi,

I have this error when running emacs:

Found 1 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: pyenv@dotfile... [1/1]
Package pyenv is unavailable. Is the package name misspelled?

Is there anyway to fix this?

Thanks 

TN

**Comment by smile13241324** [comment]
@duytrung can you tell where this package comes from? From the quoted text I would asume that you have requested to install a not existing package in your dot file probably in the additional package block.

Also please post the standard system information which you can obtain from within emacs.

As I suspect the issue in your dot file please also post your dot file.
