### ISSUE TITLE
Can't install emacs in offline mode on windows

### ISSUE THREAD

**Issue by lislon** [syl20bnr/spacemacs#9958]
#### Description :octocat:

I trtied to install emacs on machine without internet access in windows machine
and faced with the issue, that spacemacs can't find packages in spacelpa.

#### Reproduction guide :beetle:
- Unzip .emacs.d from `develop` branch
- Unzip spacelpa into ~/.emacs.d/.cache/stable-elpa/25.1.1/spacelpa-0.300
- echo '0.300' > ~/.emacs.d/.cache/stable-elpa/25.1.1/version
- Disable internet access
- Start Emacs just to generate .spacemacs file and close it 
- Change `dotspacemacs-use-spacelpa` to `t` in ~/.spacemacs
- Start emacs again
- Emacs will try to refresh packages but will fail with an errors that it can't
find any packages

*Observed behaviour:* :eyes: :broken_heart:
```
File error: Cannot open load file, No such file or directory, bind-map
```

*Expected behaviour:* :heart: :smile:
Emacs installs fine

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d475a1ba)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(my-work helm
         (auto-completion :disabled-for org markdown)
         better-defaults emacs-lisp git python html javascript yaml colors typescript sql
         (markdown :variables markdown-live-preview-engine 'vmd)
         my-common my-org my-keys my-russian my-google-translate version-control latex oc
```

#### The reason :paw_prints:

I figured out that the path to spacelpa is wrong (Notice **https://** at the begining
of local path `spacelpa`):
Here is `package-archives` variable contents:
```
(("melpa" . "https://melpa.org/packages/")
 ("org" . "http://orgmode.org/elpa/")
 ("gnu" . "https://elpa.gnu.org/packages/")
 ("spacelpa" . "https://C:/Users/user/.emacs.d/.cache/stable-elpa/25.1.1/spacelpa-0.300"))
```

I used dirty workaround and it worked fine then:

```elisp
(defun configuration-layer//package-archive-absolute-path-p (archive)
  "Return t if ARCHIVE has an absolute path defined."
  (let ((path (cdr archive)))
    (or (string-match-p "http" path)
        (string-prefix-p "~" path)
        (string-prefix-p "/" path)
        (string-prefix-p "c:" path))))

```

**Comment by syl20bnr** [comment]
Thank you for the fix, should be fixed in develop branch.

**Comment by sail456852** [comment]
`(			    defvar configuration-layer--elpa-archives
  '(("melpa" . "C:\\myspacemacs\\spacemacs-elpa-mirror-master\\melpa")
    ("org"   . "C:\\myspacemacs\\spacemacs-elpa-mirror-master\\org")
    ("gnu"   . "C:\\myspacemacs\\spacemacs-elpa-mirror-master\\gnu"))`

I replaces the https URL with absolute path. but spacemacs complain can't find the packages. 
what could be wrong ,really need to install spacemacs without internet

**Comment by nedludd** [comment]
This does not appear to be fixed.  Spacemacs is still trying to download from the web.

**Here's what I did:**

- Unzipped emacs from the develop branch to .emacs.d
- Unzip spacelpa into ~/.emacs.d/.cache/stable-elpa/25.2.1/spacelpa-0.300
- echo '0.300' > ~/.emacs.d/.cache/stable-elpa/25.2.1/version
- Disable internet access
- Start Emacs just to generate .spacemacs file and close it
- Change dotspacemacs-use-spacelpa to t in ~/.spacemacs
- Start emacs again

**Observed behaviour**

Startup halts with:

`error: Could not create connection to github.com:443`

**System Info**

OS: windows-7
Emacs: 25.2.1
Spacemacs: 0.300.0
Spacemacs branch: develop (rev. e8a6bc2)
Graphic display: t
Distribution: spacemacs
Editing style: vim
Completion: helm

Any ideas?

**Comment by nedludd** [comment]
Next step: set and save `package-archives` variable to just:

```elisp
'(("spacelpa" . "c:/Users/o700156/AppData/Roaming/.emacs.d/.cache/stable-elpa/25.2.1/spacelpa-0.300"))
```

Restart emacs.

Same result.  Spacemacs doesn't seem to read that new variable definition, since after the startup fails the variable is back to its default state.
