### ISSUE TITLE
Please update to latest bugfixed Quelpa code!

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#9961]
Quelpa recently fixed a serious bug: Packages downloaded between 00.00 and 01.00 at midnight cannot be installed. Please update Spacemacs repo to the latest quelpa.el to fix it:

Info and link here:

https://github.com/syl20bnr/spacemacs/issues/6933#issuecomment-343659954

**Comment by SteveJobzniak** [comment]
@d12frosted @syl20bnr

**Comment by dineshbhosale** [comment]
Still happening.

**Comment by syl20bnr** [comment]
Thank you for reporting this, fixed in develop.

**Comment by SteveJobzniak** [comment]
@syl20bnr Perfect!
