### ISSUE TITLE
SPC j w (evil-avy-goto-word-or-subword-1) is requesting character

### ISSUE THREAD

**Issue by JoeSchr** [syl20bnr/spacemacs#9962]
#### Description :octocat:

`SPC j w` (`evil-avy-goto-word-or-subword-1`) is requesting character

#### Reproduction guide :beetle:

- Start Emacs

- Press `SPC j w`

*Observed behaviour:* :eyes: :broken_heart:

Emacs statusline asking for `Char:`

*Expected behaviour:* :heart: :smile:

Should work like `<leader><leader>w` [vim-easymotion](https://github.com/easymotion/vim-easymotion)
because there are other shortcuts like eg. `SPC j j` (`evil-avy-goto-char`) which are there to search for a character 

(%LAST_KEYS%)

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 emacs-lisp git markdown themes-megapack django autohotkey python html javascript markdown yaml vim-powerline)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace :paw_prints:

```

<<BACKTRACE IF RELEVANT>>

```

**Comment by JoeSchr** [comment]
Sadly couldn't report is via spacemacs itself: https://github.com/syl20bnr/spacemacs/issues/9963
Hope this is ok

**Comment by nixmaniack** [comment]
> Should work like <leader><leader>w vim-easymotion
because there are other shortcuts like eg. SPC j j (evil-avy-goto-char) which are there to search for a character

Why do you think that it should behave like `<leader><leader>w`? `SPC j <key>` shortcuts aren't based on `vim-easymotion` as far as I can tell, they are based on ease/frequency of use and spacemacs selected mnemonics. 

`SPC j j`(jump to any char) serves difference purpose than `SPC j w`(jump to a word/subword starting with char)

**Comment by duianto** [comment]
I haven't used vim-easymotion.
But it looks like vim-easymotion adds the target letters to every word:
https://github.com/easymotion/vim-easymotion#usage-example-for-the-base-features

The `avy-goto-word-0` command does this.

But it should probably not replace the current behaviour of the `SPC j w` keybinding, because targeting all words shows to many candidates. The current command `evil-avy-goto-word-or-subword-1` is more useful, since it only targets the words that start with the provided `Char:`.

**Comment by JoeSchr** [comment]
> Why do you think that it should behave like <leader><leader>w? SPC j <key> shortcuts aren't based on vim-easymotion as far as I can tell, they are based on ease/frequency of use and spacemacs selected mnemonics.
Ah that would be a misunderstanding on my part then. I just googled for spacemacs vim easymotion and read a post about just using avy, so I then just assumed this should work this way

**Comment by JoeSchr** [comment]
> I haven't used vim-easymotion.
> But it looks like vim-easymotion adds the target letters to every word:
> https://github.com/easymotion/vim-easymotion#usage-example-for-the-base-features
>
> The avy-goto-word-0 command does this.
> 
> But it should probably not replace the current behaviour of the SPC j w keybinding, because targeting all words shows to many candidates. The current command evil-avy-goto-word-or-subword-1 is more useful, since it only targets the words that start with the provided Char:.

Thank you for the explanation @duianto 
It still would be nice to have something like vim-easymotion in spacemacs. Sadly I can't get the [evil-easymotion](https://github.com/PythonNut/evil-easymotion) to work with spacemacs. Something about SPC being the leader, and I want it to be on \, because of the importance of SPC for spacemacs.
I tried this in my `dotspacemacs/user-config`:
```
(require 'evil-easymotion)
(evilem-default-keybindings (kdb "\\"))
```
but it's not starting :(

**Comment by nixmaniack** [comment]
> Something about SPC being the leader, and I want it to be on , because of the importance of SPC for spacemacs.

You can configure these in `~/.spacemacs` file - specifically the values of `dotspacemacs-leader-key` and `dotspacemacs-major-mode-leader-key`. I have never changed it so don't know about side-effects and I recommend the Spacemacs defaults which will help in the long run. 

> I tried this <..snip..> 
> but it's not starting :(

Correct way would be as follows:
1. Add `evil-easymotion` to `dotspacemacs-additional-packages`.
2. Add following in `dotspacemacs/user-config` section.
```elisp
  (use-package evil-easymotion
    :init (evilem-default-keybindings "\\"))
```
This seems to work at my end. 

<img width="1280" alt="screen shot 2017-12-11 at 12 35 17 am" src="https://user-images.githubusercontent.com/542810/33808382-55e66086-de0b-11e7-96ff-477ce153baec.png">


Please note that you'll be overwriting the `\` key which in normal state is bound to `evil-execute-in-emacs-state`.

**Comment by JoeSchr** [comment]
Thx for your research and sorry for the late reply. 

Sadly it seems, it doesn't overwrite `evil-execute-in-emacs-state` when it set it to `\` via the method you explained above. It still says `Switched to emacs state for next command`

I restarted the emacs server and confirmed `evil-easymotion` plugin is loaded and methods like e.g. `evil-forward-word-begin` I can call via `SPC SPC`

What else can I do?

**Comment by nixmaniack** [comment]
@JoeSchr Could you provide repro steps? I'm not sure what you're trying to achieve with what configuration. Would be helpful if you can paste your dotspacemacs file after removing any sensitive information.

**Comment by JoeSchr** [comment]
hi,
thanks for trying to help me.

here is my `.spacemacs` file in a gist: 
https://gist.github.com/JoeSchr/5d4d02e166c8b4bab3611c80a084e319

### expected beheaviour

I try to make easy-evilmotion working with spacemacs. what I want to do is pressing `\ w` or `\ \ w` and then start the `evil-forward-word-begin` function. 

### what actually happened
pressing `\` just starts default `evil-execute-in-emacs-state`

**Comment by nixmaniack** [comment]
There are couple of issues with your `.spacemacs`
1. There's `\` on [line #34 ](https://gist.github.com/JoeSchr/5d4d02e166c8b4bab3611c80a084e319#file-spacemacs-L34). Not sure why have you added that. 
2. I see you have added `evil-easymotion` as a layer on [line #69](https://gist.github.com/JoeSchr/5d4d02e166c8b4bab3611c80a084e319#file-spacemacs-L69). 
3. [Line #355](https://gist.github.com/JoeSchr/5d4d02e166c8b4bab3611c80a084e319#file-spacemacs-L355) is wrong. You should use your existing `dotspacemacs-configuration-layers` to add just `(spell-checking :variables spell-checking-enable-by-default nil)` as you've done for autocompletion on[ line #45](https://gist.github.com/JoeSchr/5d4d02e166c8b4bab3611c80a084e319#file-spacemacs-L45). 

Can you try after fixing above issues? I haven't given your config a try yet as I'm on develop.

**Comment by JoeSchr** [comment]
Thx again,
I updated my [.spacemacs and gist](https://gist.github.com/JoeSchr/5d4d02e166c8b4bab3611c80a084e319) according to your input. 

Sadly I still get `evil-execute-in-emacs-state` when pressing `\`. Did I do something else wrong?

I was unclear on your point about what was wrong.
> 2. I see you have added evil-easymotion as a layer on line #69.

So I tried to put it into either `dotspacemacs-configuration-layers` or `dotspacemacs-additional-packages`, but it isn't working with neither

**Comment by nixmaniack** [comment]
> I was unclear on your point about what was wrong.

Sorry for being unclear. I wanted you to remove that. 

I'm still unable to reproduce. At this point I'm out clues at the moment. Could you wipe out your `.emacs.d` and `.spacemacs` (AFTER taking proper backup) and re-clone and then just add the snippet I suggested and try again? 

I'll try on `master` to see if that's an issue - if above doesn't work for you.

**Comment by nixmaniack** [comment]
I just tried on `master` with `vim` as editing style which was something different from my editing style. But still unable to repro your issue. I'm able use the easymotion commands fine with `\`.

**Comment by JoeSchr** [comment]
I realised the same config (I share them via dropbox) works perfectly on my laptop. So I will investigate what difference there are and also update my emacs. I will figure it out. Thanks again for your time!
