### ISSUE TITLE
Can't report Spacemacs bug: `C-c C-c` is undefined

### ISSUE THREAD

**Issue by JoeSchr** [syl20bnr/spacemacs#9963]
#### Description :octocat:

Can't report Spacemacs bug: `C-c C-c` is undefined

#### Reproduction guide :beetle:

- Start Emacs

- `SPC h I`
- Type Report
- `C-c C-c`

*Observed behaviour:* :eyes: :broken_heart:

Statusline: `C-c C-c` is undefined

*Expected behaviour:* :heart: :smile:

Sends bug report

(%LAST_KEYS%)

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 emacs-lisp git markdown themes-megapack django autohotkey python html javascript markdown yaml vim-powerline)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace :paw_prints:

```

<<BACKTRACE IF RELEVANT>>

```

**Comment by CeleritasCelery** [comment]
Can you enable `toggle-debug-error` and try again to generate a backtrace?

**Comment by JoeSchr** [comment]
Tried it. But there is not *backtrace* buffer and this is what was in my clipboard (followed [spacemacs debbugging guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#get-the-backtrace) )

```
<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-c C-c` TO SUBMIT>>

#### Description :octocat:

<<DESCRIPTION OF THE PROBLEM>>



#### Reproduction guide :beetle:

- Start Emacs

- <<REPRODUCTION STEPS>>



*Observed behaviour:* :eyes: :broken_heart:

<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>



*Expected behaviour:* :heart: :smile:

<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>



(%LAST_KEYS%)

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 emacs-lisp git markdown themes-megapack django autohotkey python html javascript markdown yaml vim-powerline)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS




#### Backtrace :paw_prints:

```

<<BACKTRACE IF RELEVANT>>

```

```

**Comment by duianto** [comment]
This seems to be a duplicate of at least these two issues:
Cannot submit in internal issue reporting mode #7907
`C-c C-c` does not submit a bug report #9307

Both are marked as `Fixed in develop`.

**Comment by JoeSchr** [comment]
Then I will close it! :)
