### ISSUE TITLE
Spacemacs startup issue - use-package & ace-jump-buffer

### ISSUE THREAD

**Issue by willtm** [syl20bnr/spacemacs#9964]
#### Description :octocat:
 After attempting to update packages in Spacemacs via Spacemacs home buffer
'update packages' prompt, Spacemacs seems to have a problem with `use-package`.
After attempting to roll back packages, the problem is not resolved. That is,
`.spacemacs.d/init.el` does not load and I'm prompted to choose `vim`, `emacs`,
or `hybrid`.

Only the removal of the following code (see below) in my `.spacemacs.d/init.el`
allows me to load `.spacemacs.d/init.el` and start up normally.

```
 (use-package ace-jump-buffer
    :ensure t
    :bind
    ("C-;" . ace-jump-buffer)
    )

```

#### Reproduction guide :beetle:

- Start Emacs
1. Start up Spacemacs with the code in the description.

*Observed behaviour:* :eyes: :broken_heart:

After startup, Spacemacs refuses to load `.spacemacs.d/init.el` and I'm prompted
to choose `vim`, `emacs`, or `hybrid`.

*Expected behaviour:* :heart: :smile:

Start up Spacemacs, load `.spacemacs.d/init.el` and load elisp code in description.

(%LAST_KEYS%)

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion better-defaults deft emacs-lisp git org pandoc)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

#### Backtrace :paw_prints:

```

Debugger entered--Lisp error: (void-function use-package)
  (use-package ace-jump-buffer :ensure t :bind ("C-;" . ace-jump-buffer))
  eval-buffer(#<buffer  *load*-660237> nil "c:/Users/Will/.spacemacs.d/init.el" nil t)  ; Reading at buffer position 73515
  load-with-code-conversion("c:/Users/Will/.spacemacs.d/init.el" "c:/Users/Will/.spacemacs.d/init.el" nil nil)
  load("c:/Users/Will/.spacemacs.d/init.el")
  (condition-case err (load dotspacemacs) ((debug error) (message "Error loading .spacemacs: %S" err) nil))
  (if (condition-case err (load dotspacemacs) ((debug error) (message "Error loading .spacemacs: %S" err) nil)) nil (dotspacemacs/safe-load))
  (if (file-exists-p dotspacemacs) (if (condition-case err (load dotspacemacs) ((debug error) (message "Error loading .spacemacs: %S" err) nil)) nil (dotspacemacs/safe-load)))
  (let ((dotspacemacs (dotspacemacs/location))) (if (file-exists-p dotspacemacs) (if (condition-case err (load dotspacemacs) ((debug error) (message "Error loading .spacemacs: %S" err) nil)) nil (dotspacemacs/safe-load))))
  dotspacemacs/load-file()
  spacemacs/init()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (error (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat (file-name-directory load-file-name) "core/core-load-paths.el")) (require (quote core-spacemacs)) (spacemacs/init) (configuration-layer/sync) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "c:/Users/Will/.emacs.d/init.el" nil t)  ; Reading at buffer position 1264
  load-with-code-conversion("c:/Users/Will/.emacs.d/init.el" "c:/Users/Will/.emacs.d/init.el" t t)
  load("c:/Users/Will/.emacs.d/init" t t)
  #[0 "\205\266
```

**Comment by willtm** [comment]
This reported issue is still a problem.  The only way I've been able to avoid the reported error is by inserting the following code under `dotspacemacs/user-init`:

` (push '("melpa-stable" . "stable.melpa.org/packages/") configuration-layer--elpa-archives)
 (push '(use-package . "melpa-stable") package-pinned-packages)
  )
`

Provided that I retain this code, I'm able to avoid the problems but as soon as I remove it, the same occurs again.

**Comment by willtm** [comment]
@nixmaniack thanks for your reply.

> You should be adding your additional package configuration code to` dotspacemacs/user-config` instead of `dotspacemacs/user-init`. The function documentation states that `dotspacemacs/user-init` should be used only for setting variables before packages are loaded.

Yes, and in all other circumstances in my [dotspacemacs configuration](https://github.com/willtm/dotspacemacs), that's my approach.  However, [I encountered an issue in Spacemacs](https://github.com/syl20bnr/spacemacs/issues/9945) a few weeks ago that was also experienced by several others and was related to an error in `use-package`.  For many, the use of the following code under `dotspacemacs/user-init` resolved those problems:

For master branch:
```
  (push '("melpa-stable" . "stable.melpa.org/packages/") configuration-layer--elpa-archives)
  (push '(use-package . "melpa-stable") package-pinned-packages)
```
You can see this recommended code [in the context of the discussion here](https://github.com/syl20bnr/spacemacs/issues/9948#issuecomment-348897099).  My understanding is that this code, which pins the `use-package` package to only those provided in `melpa-stable` must be loaded early in the Spacemacs startup process because of how early `use-package` is loaded.

As of today, when I attempt to remove the `melpa-stable` code, I still encounter the problem I described in my initial post.  I'd still like to resolve this issue.

> That said, ace-jump-buffer like functionality is also provided, by default, with `ivy-switch-buffer` which is bound to `SPC b b` . Once you invoke `SPC b b` , hitting `C-' `gives you the hints as given by `ace-jump-buffer`.

I didn't know that `ivy-switch-buffer` provided hints like that.  Thank you!  However, when I tried out `ace-jump-buffer`, I bound it to `C-;` which gives me very quick access to the functionality with fewer keystrokes.

Thanks again.

**Comment by nixmaniack** [comment]
Well yes, I also faced the issue mentioned in that thread. Later [comments](https://github.com/syl20bnr/spacemacs/issues/9948#issuecomment-349162601) mention that the issue was fixed upstream. Could you try the steps mentioned in that comment and see if it resolves the issue?
