### ISSUE TITLE
Help needed on configuration layers

### ISSUE THREAD

**Issue by BugraK** [syl20bnr/spacemacs#9969]
I apoligize in advance, because it is a help cry from a noob, not a bug report. I am not a programmer, although I have a -very- limited experience with AppleScript and shell scripting. I was using Vim before, of course not as an expert and recently switched to Spacemacs. I have fascinated with the idea of using spacebar as leader key (and started to use a spacebar function layer on my mechanical keyboard too).

Anyway I couldn't figure out how could I use the configuration layers. I have read the manual page on layers dozens of times and searched the internet, but still I couldn't make it work. I have `writeroom` and `deft` configuration layers that work flawlessly, but they come from internet. When I try to use them as template for, let's say `auto-capitalize` or `sr-speedbar` packages I fail no matter what. 

I create the new configuration layer and add the package to `dotspacemacs-configuration-layers` in my .spacemacs file. In the configuration layer I try;

> (setq` auto-capitalize-packages
  '(auto-capitalize))

Or 

> (defun auto-capitalize/init-auto-capitalize ()
  (use-package auto-capitalize))

Even both of them at the same time. At the first restart Spacemacs installs the packages, but at the second restart it deletes them as orphans. I am sure there is something very easy and silly thing I am missing out. I am going to lose my mind for couldn't figure out such a simple thing.  

BTW they work under the `additional-packages` without any fuss, but I want to be able use configuration layers, which I think a great idea.

Again I am very sorry for taking your time for this thing. I will be most grateful if you help me out. Also I don't know I am violating any rules by opening an issue here, so if you let me know I could happily delete and move it to the appropriate location.

Thanks for your efforts :)

**Comment by fiveNinePlusR** [comment]
This is more of a thing to bring up inside the gitter chat if you need help. 

Instructions here:

https://github.com/syl20bnr/spacemacs#getting-help

**Comment by BugraK** [comment]
Sorry about the confusion. I'm closing this issue right now.
