### ISSUE TITLE
Where do I add a layer for emacs's melpa package?

### ISSUE THREAD

**Issue by vityafx** [syl20bnr/spacemacs#9972]
The [contributing page](http://spacemacs.org/CONTRIBUTING.html) is unavailable so I don't know where and how exactly do I add a layer for a emacs's melpa package?

**Comment by fiveNinePlusR** [comment]
It's in the repo but some of the links on the website don't seem to work... the repo has all the documentation though as the website is built from the repo

https://github.com/syl20bnr/spacemacs/blob/master/CONTRIBUTING.org

**Comment by duianto** [comment]
The contributing link has been fixed on the develop branch:
http://develop.spacemacs.org/CONTRIBUTING.html
I'm guessing that it will be fixed on the main page with the next major release.

**Comment by smile13241324** [comment]
@vityafx when you question has been answered please consider closing that issue
