### ISSUE TITLE
Can not set spacemacs-light theme after having a dark one used before.

### ISSUE THREAD

**Issue by vityafx** [syl20bnr/spacemacs#9973]
I cannot enable `spacemacs-light` theme after having enabled the `spacemacs-dark` theme used for a month. It looks like it tries to set the light one but some settings from the dark are still used:

![Screenshot](https://i.imgur.com/qdUpL78.png)

**Comment by vityafx** [comment]
Okay, after removing the `selected-packages` list and restarting everything went fine.

**Comment by apapsch** [comment]
This quickly resolved issue is very useful. Kudos to you for reporting it! For future reference: It might also be custom-set-faces, that somehow got into .spacemacs.
