### ISSUE TITLE
Incorrect syntax highlighting for Latex Math mode

### ISSUE THREAD

**Issue by tsoernes** [syl20bnr/spacemacs#9976]
#### Description :octocat:
Syntax highlighting showing Math mode in Latex is "intermittenly" incorrect.

#### Reproduction guide :beetle:
- I'm not sure how to reproduce this problem with guarantee, but it does pop up quite often.
- When the bug does pop up, editing anything within the math bracket makes the problem go away. 

*Observed behaviour:* :eyes: :broken_heart:
Take a look at the right/window pane of this picture:
![screenshot_20171209_200953](https://user-images.githubusercontent.com/6782404/33798704-bb44c20e-dd1d-11e7-83c7-39127231cf9f.png)
The bottom half is syntax highlighted as 'Math mode', which is incorrect. If you add more equations, i.e. $$, then remove them, the syntax highlighting is correct: 
![screenshot_20171209_201938](https://user-images.githubusercontent.com/6782404/33798744-776bbf50-dd1e-11e7-8945-deaf151a1f7d.png)
The text in these two pictures are the same, but they have different syntax highlighting.

The problem seem to occur when half of an equation is open (just one $), but does not always disappear when the equation is closed.  

*Expected behaviour:* :heart: :smile:
Should not be math mode colored

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml javascript python latex helm auto-completion better-defaults emacs-lisp git markdown org syntax-checking
      (haskell :variables haskell-process-type 'stack-ghci)
      (python :variables python-enable-yapf-format-on-save t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

```

**Comment by ntor** [comment]
I can report the same bug. Unfortunately, I could not find any pattern behind the occurence of this problem.

**Comment by ThomaKr** [comment]
I can also report the same problem - any progress found?

**Comment by pmillet** [comment]
For what it's worth: I also see this bug but can not really connect it to a specific action. Adding more equations helps sometimes, but not always. Saving the file and reverting the buffer as @ntor suggests seems to work fine for me.

**Comment by dougmvieira** [comment]
Duplicate of #8435 and #7722

**Comment by real-or-random** [comment]
A simpler workaround is `C-c C-n` (which runs the command `TeX-normal-mode`). Source: http://pragmaticemacs.com/emacs/refresh-auctex-syntax-highlighting/
