### ISSUE TITLE
Proposal: add helm-ctest as part of C++ layer

### ISSUE THREAD

**Issue by myrgy** [syl20bnr/spacemacs#9980]
Hi everyone,

Now we have cmake-ide as a part of C++ layer.
We have several rtags merge requests to improve that layers as well.

Please, let me know your opinion about [helm-ctest](https://github.com/danlamanna/helm-ctest).
I think it might be good extension for CMake part. 
I tried it locally - in general looks good, but if we consider it as useful part of spacemacs I'll prepare several MR to helm-ctest to be able to control build dir as predicate.

@robbyoconnor, @beta1440, @andschwa, @gnzlbg, please, let me know your opinion about that.
Thank you in advance!

**Comment by beta1440** [comment]
I'll take a look at this in about 2 weeks when I have time, although given the current state of Spacemacs I'm not sure if this will go anywhere,

**Comment by delaanthonio** [comment]
I don't use CTest, but it looks a useful module.

**Comment by myrgy** [comment]
Thank you @delaanthonio!
Then I'll consider a way t integrate it.

**Comment by myrgy** [comment]
Added, hence closed.
