### ISSUE TITLE
rcirc's /reconnect command does not preserve the server port

### ISSUE THREAD

**Issue by Miciah** [syl20bnr/spacemacs#9981]
#### Description :octocat:
rcirc's /reconnect command does not preserve the server port but instead attempts to reconnect to the server using `rcirc-default-port` (the default port) as the server port.

The rcirc-reconnect package defines a `/reconnect` command that checks the `rcirc-port` variable before falling back to `rcirc-default-server`, but rcirc does not set `rcirc-port`.

Moreover, rcirc has a built-in `/reconnect` command which *does* retain the server port on reconnect.  This built-in `/reconnect` command was added in Emacs 25.1 in [commit 0b816f158782bd668cea3f013a4d6fb277ffe95a](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=0b816f158782bd668cea3f013a4d6fb277ffe95a).  Emacs 25.1 shipped September 17, 2016, so it does not seem useful for Spacemacs to include its own `/reconnect` command.  I propose deleting the rcirc-reconnect package from Spacemacs.

#### Reproduction guide :beetle:
- Start Emacs.
- Enable the rcirc layer.
- Set `rcirc-server-alist` to a server with a custom port (i.e., a different value from `rcirc-default-port`).
- Run rcirc: `M-x rcirc`.
- Wait for rcirc to get disconnected from the IRC server.
- Issue the `/reconnect` command in rcirc.

*Observed behaviour:* :eyes: :broken_heart:
rcirc attempts to reconnect using the default port (`rcirc-default-port`, default value 6667).

*Expected behaviour:* :heart: :smile:
rcirc should attempt to reconnect using the port with which it had previously connected to the server.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: delete-rcirc-reconnect (rev. 0d493cff)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible asciidoc auto-completion csv emacs-lisp
         (git :variables magit-repository-directories
              '("~/src/" "~/go/src/")
              global-git-commit-mode t)
         github go haskell html javascript markdown notmuch org pdf-tools
         (python :variables python-sort-imports-on-save t)
         (ranger :variables ranger-show-preview t)
         rcirc restclient ruby ruby-on-rails rust
         (shell :variables shell-default-height 35 shell-default-position 'bottom shell-default-shell 'eshell eshell-visual-subcommands
                '("git" "log" "diff" "show"))
         shell-scripts slack spell-checking
         (syntax-checking :variables syntax-checking-enable-tooltips nil)
         systemd version-control xkcd yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 LCMS2

**Comment by syl20bnr** [comment]
Thank you ! 💯 
Cherry-picked into develop branch, you can safely delete your branch.

**Comment by syl20bnr** [comment]
Thank you for the fix, it is merged in develop branch.
