### ISSUE TITLE
Helm mini maximizes current buffer

### ISSUE THREAD

**Issue by adrianjord** [syl20bnr/spacemacs#9984]
#### Description :octocat:
Since updating, on start up, any command that brings up helm mini will cause the current window to maximize until spacemacs is `dotspacemacs/sync-configuration-layers` is called `SPC f e R`.

I have also made sure to update all packages when I updated spacemacs. I have this same issue on multiple machines.
#### Reproduction guide :beetle:
- Start Emacs
- Open new window(s) (`SPC w s`, `SPC w v`)
- Open helm mini (`SPC b b`, `SPC SPC`, `SPC f f`, etc..)
- Current window will maximize
- Close helm mini (`ESC`)
- Window will return to position in layout with remaining windows

*Observed behaviour:* :eyes: :broken_heart:
Layout goes from:
```
 _____________________
|-------------|-------|
|-------------|-------|
|-------------|-------|
|-------------|-------|
|-------------|-------|
|-------------|-------|
|-------------|-------|
|-------------|-------|
|doc1---------|doc2---|
|_____________________|
```
To:
```
 _____________________
|---------------------|
|---------------------|
|---------------------|
|---------------------|
|---------------------|
|doc1-----------------|
|_____________________|
|---------------------|
|helm-----------------|
|_____________________|
```

*Expected behaviour:* :heart: :smile:
Layout goes from:
```
 _____________________
|-------------|-------|
|-------------|-------|
|-------------|-------|
|-------------|-------|
|-------------|-------|
|-------------|-------|
|-------------|-------|
|-------------|-------|
|doc1---------|doc2---|
|_____________________|
```
To:
```
 _____________________
|-------------|-------|
|-------------|-------|
|-------------|-------|
|-------------|-------|
|-------------|-------|
|doc1---------|doc2---|
|_____________________|
|---------------------|
|helm-----------------|
|_____________________|
```

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(vimscript sql markdown html helm auto-completion emacs-lisp git markdown org typescript javascript html
           (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
           spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by duianto** [comment]
The issue was cause by the helm package renaming a variable. That caused the 
`helm-always-two-windows` variable to become enabled in Spacemacs.

There's a pending PR to fix it on the Spacemacs develop branch:
Update renamed helm split window variable #9983

The current solution is to add: `(setq helm-always-two-windows nil)` to the `dotspacemacs/user-config` section in `.spacemacs`.

If/when the PR is merged, then it will work on the develop branch, without the line above. And then the master branch might get fixed with the next major release (I have no insight into when that is).

**Comment by duianto** [comment]
This has been fixed on the `develop` branch, I forgot to add "Resolves" and this issue number to the PR description.

**Comment by duianto** [comment]
This is also working on the master branch.
