### ISSUE TITLE
cmake-ide error when opening c Makefile project

### ISSUE THREAD

**Issue by aurabindo** [syl20bnr/spacemacs#9985]
#### Description :octocat:
Upon launching a c makefile project, an error pops up in the bottom message buffer

#### Reproduction guide :beetle:
- Start Emacs
- Launch a C project

*Observed behaviour:* :eyes: :broken_heart:

Gives the below error in the bottom buffer:

`error in process sentinel: Wrong type argument: hash-table-p, nil`

*Expected behaviour:* :heart: :smile:

No error.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b4b7d63)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm c-c++ gtags shell auto-completion emacs-lisp git markdown neotree spell-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("/media/aj/Buffer/git-clones/myobeam/jag-freertos-revA/src/main.c" nil)
  cmake-ide--idb-file-to-obj(nil "/media/aj/Buffer/git-clones/myobeam/jag-freertos-revA/src/main.c")
  cmake-ide--set-flags-for-file(nil #<buffer main.c>)
  #[257 "\301\300\"\207" [nil cmake-ide--set-flags-for-file] 4 "\n\n(fn X)"](#<buffer main.c>)
  mapc(#[257 "\301\300\"\207" [nil cmake-ide--set-flags-for-file] 4 "\n\n(fn X)"] (#<buffer main.c> #<killed buffer> #<killed buffer>))
  cmake-ide--on-cmake-finished()
  #[514 "\300\301!\210\302 \207" [cmake-ide--message "Finished running CMake" cmake-ide--on-cmake-finished] 4 "\n\n(fn PROCESS EVENT)"](#<process cmake> "exited abnormally with code 1\n")

```

**Comment by myrgy** [comment]
looks like related to https://github.com/atilaneves/cmake-ide/issues/143

**Comment by aurabindo** [comment]
@myrgy settings `(require 'subr-x)` does not fix the issue for me. Today I updated develop and all the packages. Now spacemacs freezes at this error! This was on emacs 25.1.1. Same behavior on 25.3 as well!

**Comment by myrgy** [comment]
then we need to wait for this MR  https://github.com/syl20bnr/spacemacs/pull/9955
it will allow to disable cmake-ide

**Comment by dlyr** [comment]
Hi,
could you try my branch (it also has enhancement for multi project management and cmake-opts, using a different build dir dependeing on cmake-opts and project)
https://github.com/dlyr/cmake-ide/tree/wip_project_key
If it's not ok for you, I could investigate (on the cmake-ide side).

**Comment by aurabindo** [comment]
@dlyr Sure I can try. But I'm not sure how to tell spacemacs to use this branch. Could you please help ?

**Comment by myrgy** [comment]
I think it worth Its better to make mr to cmake-ide repo

**Comment by dlyr** [comment]
I'm not aware of the working of spacemacs ... if you can locate cmake-ide.el (or .elc) in your emacs directory (mine is .emacs.d)
say it's .emacs.d/emacs-lisp/cmake-ide
then save this directory somewhere (just in case ;) download and extract my version removing cmake-ide.elc and replace cmake-ide.el
Then you can test.
++

**Comment by aurabindo** [comment]
@dlyr Thanks a lot for that fix! Now I can use spacemacs again! Although I have one observation to record:

```
custom-initialize-reset: Symbol’s function definition is void: cmake-ide-message
```
 This message shows up in the bottom buffer once I launch emacs. Emacs stays in its default "spacemacs" front page, and does not focus the file I asked it to open. I need to switch to that buffer manually.

**Comment by dlyr** [comment]
my bad, typo in a function call ... corrected (you can download again)

**Comment by aurabindo** [comment]
@dlyr  That cleanly fixes the issue! Thanks a lot! ;)

**Comment by myrgy** [comment]
Waiting for this MR - https://github.com/atilaneves/cmake-ide/pull/141

**Comment by myrgy** [comment]
https://github.com/atilaneves/cmake-ide/pull/141 was merged to cmake-ide master.

**Comment by aurabindo** [comment]
@myrgy thanks for the heads up !

**Comment by dlyr** [comment]
I still have trouble (from time to time) when opening non cmake project ... another PR comming soon ;)
