### ISSUE TITLE
Invoking a GUI print dialog box (linux)

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#9986]
I've got this working in my init.el, was wondering if this could/should be included as a default in spacemacs? I'tl popup a GUI for managing print jobs when invoking `print-buffer`, `print-region` etc.

On Ubuntu `gtklp` seem to be installed by default (not verified).
Not sure if there as ways to invoke the printer dialog box in the same way on other OSs.

```emacs-lisp
  (cond
   ((spacemacs/system-is-linux)
    (setq lpr-command "gtklp"
          ps-lpr-command "gtklp")))
```

![screenshot from 2017-12-12 10-45-20](https://user-images.githubusercontent.com/1701421/33877758-98f25f6e-df29-11e7-9d25-c93412214fab.png)

**Comment by harindu95** [comment]
Not in Debian. I think it's probably a gnome application.
