### ISSUE TITLE
Question: what is the theme of the code snippets in the documentation?

### ISSUE THREAD

**Issue by vityafx** [syl20bnr/spacemacs#9987]
I very like this theme, how can I install it?

![Screenshot](https://i.imgur.com/Ses6irC.png)

It looks like `twilight-bright` but is not.

**Comment by CarlQLange** [comment]
I believe it might be `spacemacs-light`.

**Comment by vityafx** [comment]
@CarlQLange I have tried the `spacemacs-light` before posting this issue. It does not look the same as on the image I've posted.

**Comment by CeleritasCelery** [comment]
@CarlQLange is correct.
