### ISSUE TITLE
Use hippie-expand for yasnippet instead of TAB

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#999]
It really gets in the way when `yasnippet` detects that your string contains a snippet prefix.

**Comment by syl20bnr** [comment]
Sorry, I don't use hippie-expand.What's the benefit of doing what your propose ?

**Comment by tuhdo** [comment]
The benefit is that when I press TAB to complete and the prefix is part of a snippet, then instead of giving me completion popup, it inserts the snippet making me to undo the whole thing. Yoj should try the example above with company-mode. It's like a time bomb.

**Comment by tuhdo** [comment]
I mean the example in my PR to allow expanding snippets with hippie-expand instead of TAB.

**Comment by syl20bnr** [comment]
Perfect, thank you, I will check the PR.
