### ISSUE TITLE
, i c doesn't insert a citation

### ISSUE THREAD

**Issue by telekid** [syl20bnr/spacemacs#9990]
#### Description :octocat:
Running `, i c` correctly opens the helm citations buffer, but selecting a citation doesn't
actually insert it into the document.

Feels a lot like #8741.

#### Reproduction guide :beetle:
- Start Emacs
- Ensure you have bibtex and org layers installed
- Ensure you have a bibliography file specified:
```elisp
(setq org-ref-default-bibliography '("~/Dropbox/org/references.bib")
      org-ref-pdf-directory "~/Dropbox/org/references/"
      org-ref-bibliography-notes "~/Dropbox/org/reference-notes.org")
```
- Ensure you have a citation in your `references.bib` file
- Open an org-mode document
- Run `, i c` and select the citation
  ¯\\_(ツ)_/¯

*Observed behaviour:* :eyes: :broken_heart:
Citation doesn't appear in org document

*Expected behaviour:* :heart: :smile:
Citation should appera in org document

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b4b7d63e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((plantuml :variables plantuml-jar-path "~/org/plantuml.jar")
 bibtex rust swift csv javascript markdown python yaml helm auto-completion better-defaults emacs-lisp git react html parinfer
 (org :variables org-projectile-file "notes.org" org-enable-reveal-js-support t)
 clojure
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (spell-checking :variables enable-flyspell-auto-completion t)
 syntax-checking version-control typescript evil-commentary)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by CeleritasCelery** [comment]
Does the workaround in #8739 work?
