### ISSUE TITLE
centered-cursor-mode.el is two versions behind

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#9991]
The current version of `centered-cursor-mode.el`:
https://www.emacswiki.org/emacs/centered-cursor-mode.el
>;; Version: 0.5.4
;; Last-Updated: 2015-10-01

has had two updates:
>;; 2015-10-01 Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>
;;   * Avoided calling count-lines when unnecessary, which
;;     fixes slow scrolling in large files
;; 2015-03-01  andre-r
;;   * fixed bug where Emacs without X support (emacs-nox) didn't find mouse-wheel-mode

since the version `0.5.2` that comes with Spacemacs:
master: https://github.com/syl20bnr/spacemacs/blob/master/layers/+spacemacs/spacemacs-ui/local/centered-cursor/centered-cursor-mode.el
develop: https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bspacemacs/spacemacs-navigation/local/centered-cursor/centered-cursor-mode.el

>;; Version: 0.5.2
;; Last-Updated: 2009-08-31

(both branches use the same version)

Updating the Spacemacs version, would prevent someone from encountering the fixed issues.

**Comment by kommen** [comment]
It seems it would be better to switch to https://github.com/andre-r/centered-cursor-mode.el by @andre-r as it is actively maintained.

**Comment by duianto** [comment]
Agreed, it's also on MELPA, https://melpa.org/#/centered-cursor-mode

**Comment by kommen** [comment]
I tried to get spacemacs use the melpa version in a local fork, but my emacs hacking foo is not strong enough.

**Comment by duianto** [comment]
Neither is mine, I suggest asking in the gitter chat, someone there might know how to do it.

**Comment by kommen** [comment]
@duianto submitted PR #10258. maybe you can try it out?
