### ISSUE TITLE
Replace deprecate golang oracle with guru

### ISSUE THREAD

**Issue by webframp** [syl20bnr/spacemacs#9993]
The docs still suggest using oracle over guru here: http://spacemacs.org/layers/+lang/go/README.html

Based on this [google doc](https://docs.google.com/document/d/1SLk36YRjjMgKqe490mSRzOPYEDe0Y_WQNRv-EiFYUyw/view#) it seems like oracle is deprecated. 

This would seem to agree with why `go get -u -v golang.org/x/tools/cmd/oracle` fails for me with a ` cannot find package` error.

This could just be a docs issue. Should it be updated to support the Go Guru commands as described in this [google doc](https://docs.google.com/document/d/1_Y9xCEMj5S-7rv2ooHpZNH15JgRT5iM742gJkw5LtmQ/edit]?

**Comment by zer09** [comment]
Please check develop branch, it is already been implemented there. Maybe it will be included in master on v0.300 release.

**Comment by webframp** [comment]
Thanks, looking forward to that release!
