### ISSUE TITLE
Inserting block comment

### ISSUE THREAD

**Issue by jbharat** [syl20bnr/spacemacs#9999]
![comment](https://user-images.githubusercontent.com/6837979/34022872-ef120296-e195-11e7-8230-d7b927cceff5.gif)

Is there a way to get the above behaviour. Any code snippet . Hitting 'enter' in a comment block should add the appropriate comment and indent properly. 

I can use yasnippet to automatically insert block comments but when I press 'enter' the line is not prepended with comment character.

**Comment by fiveNinePlusR** [comment]
perhaps ask this in the gitter chat or modify this to a feature request? I am not aware of a way and none of the melpa packages seemed to be helpful on that.

**Comment by duianto** [comment]
The answer on the following page, might be what your looking for:
https://emacs.stackexchange.com/questions/14563/how-to-automatically-create-neat-c-comment-blocks-while-typing

But the animation on that page looks identical to yours, so maybe you've already seen it.

**Comment by jbharat** [comment]
duianto yes I have seen it. This is the same gif. The solution given seems to support c. I used Java, JavaScript and would like to use something that works on all languages that support block comments.

**Comment by jbharat** [comment]
@duianto thanks for the link. This works
```
       (defun my/block-comment-setup ()
         "Configure multi-line comments."
         (setq comment-start "/*"
               comment-end         "*/"
               comment-multi-line  t
               comment-padding     nil
               comment-style       'extra-line
               comment-continue    " * "
               comment-empty-lines t))
```
But need to bind a key to insert new line with comment. I would prefer 'enter' to insert new comment line within the block. But still this better. Thanks again
